### ISSUE TITLE
Apparent erratic behaviour of timeline

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/MapStore2#10001]
The cursors apparently moves randomly through the timeline with [this layer](https://development.demo.geonode.org/catalogue/#/dataset/84) (ImageMosaic).

![timeline](https://github.com/geosolutions-it/MapStore2/assets/571129/e6550531-277b-4639-9cab-4f94362062e3)

The time dimension in Geoserver is configured as the following:

![unnamed (1)](https://github.com/geosolutions-it/MapStore2/assets/571129/fa18712d-6370-4cbf-b847-9ee57cfb9fd3)

**Comment by offtherailz** [comment]
Confirmed on dev with this (private) []([map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/48847).)

**Comment by offtherailz** [comment]
Checking the requests, looks that WMTS multidim replies in a strange way.

In fact the tool asks dynamically the nearest value to the current point, performing 2 requests (1 asc and 1 desc) from the same starting point), to determine previous and next times.

This is the first request , asking the domain values ascending from `2013-09-10T18:59:16.451Z`

```
curl 'https://development.demo.geonode.org/geoserver/gwc/service/wmts?service=WMTS&version=1.0.0&request=GetDomainValues&tileMatrixSet=EPSG:4326&layer=geonode:temperature_surface&domain=time&fromValue=2013-09-10T18:59:16.449Z&sort=asc&limit=1&fromEnd=false' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.9,it-IT;q=0.8,it;q=0.7' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Origin: http://localhost:8081' \
  -H 'Pragma: no-cache' \
  -H 'Referer: http://localhost:8081/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="122", "Not(A:Brand";v="24", "Google Chrome";v="122"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"'
```
The server replies with 2013-09-14 at 02
```
<?xml version="1.0" encoding="UTF-8"?><DomainValues xmlns="http://demo.geo-solutions.it/share/wmts-multidim/wmts_multi_dimensional.xsd" xmlns:ows="http://www.opengis.net/ows/1.1">
  <ows:Identifier>time</ows:Identifier>
  <Limit>1</Limit>
  <Sort>asc</Sort>
  <FromValue>2013-09-10T18:59:16.449Z</FromValue>
  <Domain>2013-09-14T02:00:00.000Z</Domain>
  <Size>1</Size>
</DomainValues>
```
But there are more values before sept 14th
![image](https://github.com/geosolutions-it/MapStore2/assets/1279510/43aa6a13-1e19-466b-997a-27ed1642f1b1)

I suggest to investigate on WMTS multidim bahavior first

**Comment by giohappy** [comment]
Ok, we will investigate better.
FYI the timeline works fine in QGIS. It moves correctly between the time steps. Presumably, it's based on different requests, I will give a look at the network requests it performs.

![image](https://github.com/geosolutions-it/MapStore2/assets/571129/8a9240af-3f62-4076-b2de-9131f2f14f9b)

**Comment by gannebamm** [comment]
We can confirm this issue with a GeoNode 4.2.5 based instance. The dataset is a vector timeseries and is publicly accessible here: https://atlas.thuenen.de/catalogue/uuid/1cad7ad5-3c8f-4067-8865-2f0085cf841c

These are the GeoServer settings:
![grafik](https://github.com/user-attachments/assets/d7410903-0cb7-44fb-9aa1-53916666427b)


It worked properly in an older release of GeoNode with the above settings.

**Comment by giohappy** [comment]
Upgrading to Geoserver 2.24.5 fixes the problem, The map reported in the description is working fine now: https://development.demo.geonode.org/catalogue/#/dataset/84
