### ISSUE TITLE
Update GHA due to latest pom changes

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#10020]
## Description

To be in line with what has been done for PR https://github.com/geosolutions-it/MapStore2/pull/10015 the GHAs (for sure the one for automatically updating deps version) should be reviewed and updated if necessary.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by offtherailz** [comment]
I found why the PRs generated do not trigger actions.

https://github.com/orgs/community/discussions/65321

Probably we need to create a proper user and PAT token to generate the correct requests.

**Comment by offtherailz** [comment]
I created this issue because this involves several projects.

https://github.com/geosolutions-it/internal/issues/395
