### ISSUE TITLE
Possibility to create an Empty Map from MapManager

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#1004]

**Comment by offtherailz** [comment]
Something like this is ok? 

**desktop:**
![image](https://cloud.githubusercontent.com/assets/1279510/18749088/98415146-80d5-11e6-93d3-bb5ac1c6a616.png)

**tablet**
![image](https://cloud.githubusercontent.com/assets/1279510/18749128/b61fd2d2-80d5-11e6-836a-cd18a05f2c0a.png)

**mobile**
![image](https://cloud.githubusercontent.com/assets/1279510/18749186/f05c38c8-80d5-11e6-8c8c-057dc4ac95b2.png)

**Comment by MV88** [comment]
For the **Empty Map** we can:
- change the thumbnail 
- change the glyphicon

**Comment by offtherailz** [comment]
Change the icon seems hard (nested objects) without refactor something, for the moment can this work? 

![image](https://cloud.githubusercontent.com/assets/1279510/18749896/29a6f304-80d9-11e6-9efa-c7b92fc39caa.png)

**Comment by Gnafu** [comment]
Don't we have a designer's mockup for this feature? I don't like the single tile alone on the left.

**Comment by MV88** [comment]
![ebbf3061a7fed4ca8879e1f7c0c1e4959e3cf4b705dc10d01a tfile_urlpv](https://cloud.githubusercontent.com/assets/11991428/18750476/8780a4b4-80db-11e6-91f6-098130f4f606.png)
Someone suggest to add a button in one of this red areas. I would exclude the one near the languages flag.

**Comment by offtherailz** [comment]
Something like this is enough? It should be responsive, so everywere is placed have to automatically adapt. The faster way is to place it in a line, after maptype, waiting for some better suggestions for designers. 
![image](https://cloud.githubusercontent.com/assets/1279510/18751123/2da1e7e8-80de-11e6-932a-6ea6db0e32a3.png)
