### ISSUE TITLE
The Delete button does not work when the map has edit permission for the anonymous user. 

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#10064]
## Description

The Delete button does not work when the map has edit permission for the anonymous user. 

https://github.com/geosolutions-it/MapStore2/assets/56537133/03870571-727e-4b91-b12b-02b1a76069ad

## How to reproduce

-  Open a map
-  From Save panel, set Everyone can edit 
- Click on Save
- Log out
- Click on Delete button

*Expected Result*

For the anonymous user with edit permission, the Delete button works or eliminates the ability to have edit permissions for the anonymous user.

*Current Result*

For the anonymous user with edit permission, the Delete button is present  but it is not possible to delete the map and an error occurs.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
... and it should not work, indeed, since the MS model doesn't allow to anonymous to save/edit contents. The problem here is another: certain tools should not be available for anonymous users and it should not be possible to select can edit for everyone, that's a inconsistency in the UI.

**Comment by tdipisa** [comment]
@dsuren1 we should simply prevent this possibility in practice
![image](https://github.com/geosolutions-it/MapStore2/assets/1280027/332c04cc-7b09-4e3f-904c-778a389a71b1)
