### ISSUE TITLE
COG layers regression

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#10072]
## Description
When trying to add l COG layers to the map, I have the warning about projection (to check) and the zoom button do not appear anymore.

## How to reproduce

-  load this map in the context COG https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/COG/
[cog_regression.json](https://github.com/geosolutions-it/MapStore2/files/14605848/cog_regression.json)
- Try to add layers for the listed catalogs

*Expected Result*
Selecting layers in the TOC, they have a zoom button

*Current Result*
Selecting layers in the TOC, they do not have a zoom button
A popup with projection issue is shown, but theoretically, properly configuring projectionDefs, it shouldn't.

[screencast-mail.google.com-2024.03.14-18_23_07.webm](https://github.com/geosolutions-it/MapStore2/assets/1279510/7daa4600-19eb-4f78-9c21-c05f85d3ff75)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@offtherailz is the zoom to layer working when you add the layer from catalog? It should, if not we have to fix also this and if the CRS is supported in projDefs the orange popup should not appear in theory. All this points should be included in the things to fix if you confirm that.

**Comment by offtherailz** [comment]
I confirm. Both looks to have problems.

**Comment by offtherailz** [comment]
added the point to current result

**Comment by dsuren1** [comment]
@offtherailz @tdipisa 
The reason for this case is when the COG layer doesn't have metadata information. After this issue https://github.com/geosolutions-it/MapStore2/issues/9590, we have limited the metadata fetch and cancelling to only cog catalog service `on save` and **not** `on search`.

If we allow it also `on search`, then with current implementation, we may not be able to cancel the metadata fetch (if data is too big). Should we also allow it on search and also introduce a cancel button (limit to only cog service) on Catalog search panel?

**Comment by tdipisa** [comment]
@dsuren1 @offtherailz 

> ... we have limited the metadata fetch and cancelling to only cog catalog service on save and not on search.

This is not so clear for me. I remember we have decided to fetch metadata by default which is the aim of #9590 therefore metadata should be downloaded and used as expected. Did I miss something maybe? @offtherailz any feedback on that?

**Comment by offtherailz** [comment]
The metadata information is **foundamental** for properly handling the correct projection and zoom to the image.
So if we download it only on catalog save, for performance reasons, we **must save**  metadata in the catalog json, in order to be reused. I supposed it already worked like this. I don't remember if I tested it 
Otherwise is better to download metadata on search or on add and wait eons.

Also the issue says 
>  Because this takes a long time, a botton should allow it (with the option to cancel), and this information **will be saved in the catalog, among the records**. This means that also the UI with the URL(s) may need a revision, probably with a list of records, or we may have undefined behaviors when we edit URLs.

**Comment by dsuren1** [comment]
> So please @dsuren1 make sure that the metadata information is not used only on the fly when the user save, but saved in the map json (catalog) and maintained across reloads/imports etc...

Sure. I will make the necessary changes :thumbsup:

**Comment by tdipisa** [comment]
Closed in favor of https://github.com/geosolutions-it/MapStore2/issues/10083
