### ISSUE TITLE
The permission editor need some updates

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#1011]
- Some translations are missing and they also should be internationalized.
- If the user isn't the owner of the map --> hide permission editor
- The groups spinner should turn off if no available groups is left

**Comment by MV88** [comment]
@Gnafu What about removing the label "permissions" under the "Groups" "permissions"
![image](https://cloud.githubusercontent.com/assets/11991428/18755670/638cbbd0-80ed-11e6-83f6-8ea498b8b758.png)

Or mabye we can join the two label into just one in order to get better translations on other languages.

**Comment by MV88** [comment]
We should also change the style of disabled button. Now the + button remains green when disabled

**Comment by Gnafu** [comment]
I agree.  
Give priority to the infinite loading bug.
