### ISSUE TITLE
Improving geodesic distance for 3D mesurement

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#10121]
## Description

With #10000 the geodesic distance for 3D measurement has been included. There are a few necessary modifications  needed to make that measurement type usable and less ambiguous. 

1 - When you draw the first point its position is not fixed in the view and this make the measurement ambiguous: the first point should be anchored at the clicked point

![Image](https://github.com/geosolutions-it/MapStore2/assets/1280027/3b7d2e65-a69e-413c-8ccc-c5f13b931625)

2 - Currently the measurement is drawn for consistency on the ellipsoid at the absolute 0 and this make unclear the measurement position in many cases (specially if you are working at urban level). 

https://github.com/geosolutions-it/MapStore2/assets/1280027/7b08cd42-c8bd-479b-834a-1d86342af7da

The position of the measurement should be preserved as drawn by the user but it should be clearly indicated somehow that it is referencing a distance calculated at the absolute 0 (maybe we can do this info in tooltip and use guide).

![Image](https://github.com/geosolutions-it/MapStore2/assets/1280027/a07a77d4-3958-4c1b-a09d-f31a1568e8d7)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by ElenaGallo** [comment]
@MV88 the height of the geodetic measurement changes when you switch to area and angle measurement. (on DEV and QA)



https://github.com/geosolutions-it/MapStore2/assets/56537133/a11b5bf0-3f71-4924-ac87-b5f2a4de52d5
