### ISSUE TITLE
`SortBy` parameter is not retained in the configuration definition for catalog pluing in context

### ISSUE THREAD

**Issue by ale-cristofori** [geosolutions-it/MapStore2#10134]
## Description
The recently introduced `sortBy` parameter, to be included in the CSW catalog is not saved in the catalog plugin configuration when creating a context with a custom plugin configuration

## How to reproduce

-  in DEV, open the following context in edit mode https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/SortByContext 'SortByContext'
- Navigate to point 3 to define the custom plugins to be loaded in the context
- Click on the 'spanner' icon to define the JSON configuration for the catalog plugin
- Paste the attached json, that includes the `sortBy : {name: dc:title}` key/value (which is the one saved to the JSON when the configuration is save manually) [test_csw_services.json](https://github.com/geosolutions-it/MapStore2/files/14761598/test_csw_services.json)
- Save the context and re-open in view mode
- Notice how the configuration is not saved and the `sortBy` parameter is still empty
see below

https://github.com/geosolutions-it/MapStore2/assets/14953970/da05c70c-59dd-4ce2-9902-ddc0d59cb519

*Expected Result*
 The catalog plugin configuration should be saved and `dc:title` parameter should be included in the `sortBy` text box.

*Current Result*
The catalog plugin configuration is not saved and `dc:title` parameter is not included in the `sortBy` text box.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by dsuren1** [comment]
@ale-cristofori 
MetadataExplorer plugin doesn't allow configuring services directly via the [plugin config](https://mapstore.geosolutionsgroup.com/mapstore/docs/api/plugins#plugins.MetadataExplorer). Instead it default services are added to [`initialState`](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/configs/localConfig.json#L78) of localConfig. The same service is visualized in both the catalog of Map viewer and Step2 of context creator (i.e Catalog of Map), at least that's what I remember if I'm not wrong. 
If you like the context to have different default services configured, you may need to do so in the Catalog panel of Step2 (context-creator). When saved the services are saved to along with other map configurations. And eventually the same services are copied over to map created from the context
Ex: `#/context/SortByContext/50078`

Evidently for the video above, you have different services in json but you were able to visualize only the default list of catalog service configured.

**Comment by tdipisa** [comment]
Thank you @dsuren1. @ale-cristofori let me know if we can close the issue then.

**Comment by ale-cristofori** [comment]
@tdipisa @dsuren1, I can see the rationale of it. Though I test the following

> If you like the context to have different "default" services configured, you may need to do so from the Catalog panel of Step2 in context-creator. When saved the services are saved along with other map configurations. And eventually the same services are copied over to map created from the context

And I get errors 

https://github.com/geosolutions-it/MapStore2/assets/14953970/8830d213-dfca-491a-ab7e-a0f8db46583c

@tdipisa @dsuren1 is it something that needs to be looked into? If so let me know, it seems a bad response from gs-stable.
