### ISSUE TITLE
Specify custom DPI for ScaleBox Plugin

### ISSUE THREAD

**Issue by ndufrane** [geosolutions-it/MapStore2#1015]
Hi,

Right now the scales are computed with a default DPI value (96) witch is a good default. But it would be nice to be able to specify custom DPI .

I wonder where is the best place to specify the custom DPI information in the configuration.
 
Here is my proposal 

```
  "map": {
    ....,
    "mapOptions" : {
        "view" : {
            "resolutions" : [49.0, 42.0, 28.0, 21.0, 14.0, 7.0, 5.6, 3.5, 2.8, 2.1, 1.4, 0.7, 0.56, 0.28, 0.14, 0.07, 0.056, 0.035, 0.028, 0.014],
            "DPI" : 90.71428571428571
        }
    },

```
Next, the scalebox plugin can be slightly modify to handle this new parameter.

**Comment by mbarto** [comment]
Looks like the right place to me

**Comment by mbarto** [comment]
Fixed by https://github.com/geosolutions-it/MapStore2/pull/1019
