### ISSUE TITLE
Skipping 'Configure Map' step breaks context configuration

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#10197]
## Description

The context configuration will break if a user skip the configure map step while editing it

https://github.com/geosolutions-it/MapStore2/assets/19175505/20f33136-6158-4d6e-b2cb-f8a09d09fc4a

## How to reproduce

- create a new context and save
- edit the saved context
- click on `Configure Plugins` and skip `Configure Map`
- ad a new plugin (eg 3D)
- click on next and save
- open the context map viewer

*Expected Result*

The context map viewer is visible with the correct configuration

*Current Result*

The context map viewer is not visible with the infiinite loading spinner and an error in console

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@mahmoudadel54 
This problems affects also QA. We have to include a fix for this regression for 2024.01.00
