### ISSUE TITLE
Implement zoom all control

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#102]
Button to zoom to the user defined maxExtent (or to zoom 1, if not defined).
Should work with both leaflet and openlayers map components

**Comment by chrismayer** [comment]
I suggest a button component handling the zoom logic, which is customizable via CSS. The default position could be below the zoom-in and zoom-out buttons, like in this little mockup (ignore styling of the button):

![mockup-102-1](https://cloud.githubusercontent.com/assets/1185547/10192570/979b5560-677d-11e5-9a74-a95e7985e03e.png)

What do you think?

**Comment by mbarto** [comment]
Looks good to me.

Mauro


2015-09-30 14:15 GMT+02:00 Christian Mayer <notifications@github.com>:

**Comment by simboss** [comment]
I believe it should be better placed within the toolbar for consistency, no?

Feedback welcome.

**Comment by chrismayer** [comment]
I though it could be placed there to have all the "zoom-tools" on the same side of the map. But I agree for consistency it might be better having the new button in the toolbar. Seems we have then the advantage to have all tools in a common place. So toolbar?

**Comment by mbarto** [comment]
I think we can put "pure navigation tools" like zoom+, zoom-, zoom all on
the left (the first two are already there). I would leave the right toolbar
for other functionalities.

Mauro


2015-09-30 14:39 GMT+02:00 Simone Giannecchini <notifications@github.com>:
