### ISSUE TITLE
Binary issue 

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#10200]
## Description

The MA QA binary does not start.

> ERROR 2024-04-15 10:20:55.466 org.springframework.web.context.ContextLoader::initWebApplicationContext:313 - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'geostoreInitializer' defined in URL [file:/C:/Users/User/Desktop/mapstore2/webapps/mapstore/WEB-INF/classes/applicationContext.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'categoryService' defined in URL [jar:file:/C:/Users/User/Desktop/mapstore2/webapps/mapstore/WEB-INF/lib/geostore-services-impl-2.1-SNAPSHOT.jar!/applicationContext.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'categoryDAO': Injection of persistence dependencies failed; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [org.mapfish.print.MapPrinter] for bean with name 'mapPrinter' defined in URL [file:/C:/Users/User/Desktop/mapstore2/webapps/mapstore/WEB-INF/classes/applicationContext-print.xml]: problem with class file or dependent class; nested exception is java.lang.UnsupportedClassVersionError: org/mapfish/print/MapPrinter has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 (unable to load class [org.mapfish.print.MapPrinter])

## How to reproduce

- Use this bin.zip file: https://build.geosolutionsgroup.com/view/MapStore/job/MapStore/view/MapStore%20QA/job/MapStore2-QA-Build/302/

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@randomorder (FYI @ElenaGallo)

```notLoadBeanClassException: Error loading class [org.mapfish.print.MapPrinter] for bean with name 'mapPrinter' defined in URL [file:/C:/mapstore2-2024.01.xx/mapstore2/webapps/mapstore/WEB-INF/classes/applicationContext-print.xml]: problem with class file or dependent class; nested exception is java.lang.UnsupportedClassVersionError: org/mapfish/print/MapPrinter has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 (unable to load class [org.mapfish.print.MapPrinter])```

This is due to the fact that the binary is currently using a java version older than the one requested when the printing module is included in the build (and that is in the QA binary for testing purpose).

Current is:

![Image](https://github.com/geosolutions-it/MapStore2/assets/1280027/461b2c47-a9de-40d5-9f43-144e532d0a83)

**Comment by randomorder** [comment]
Hi @david7378 ,

Please download JDKs for linux and windows (not JRE) version 11 matching the same version that we are using in the latest tag of the docker image for MapStore and prepare the tar.gz archive. The structure must be the same as the current one [here](https://github.com/geosolutions-it/MapStore2/blob/master/binary/pom.xml#L120C36-L120C101).

Then upload the artifacts to dropbox and prepare two PRs to update the URLs in the locations reported above. One PR for master and one for QA branches.

**Comment by david7378** [comment]
### What I have done:
1. Checked the Java version of the latest tag of the Docker image for MapStore, which is 11.0.16_8.
2. Downloaded the Linux and Windows JDK version 11.0.16_8.
3. Prepared the folder similarly to the older JRE and compressed it to tar.gz.
4. Uploaded it to Dropbox.
5. Created a new branch with the updated URL and created a PR to master and QA.
6. Resolved a Maven complaint regarding the URL by replacing the character "&" with "& amp;".

![Image](https://github.com/geosolutions-it/MapStore2/assets/88064044/1877f374-0e56-4ec9-85d2-5697f621904f)

- From
```
https://www.dropbox.com/scl/fi/2rjaso3cxgab0jdjxwpjr/jre.tar.gz?rlkey=1wrf6mcemn5d2e88t8u0wxbk3&dl=0
```
- To
```
https://www.dropbox.com/scl/fi/2rjaso3cxgab0jdjxwpjr/jre.tar.gz?rlkey=1wrf6mcemn5d2e88t8u0wxbk3&amp;dl=0
```

All test have passed on master.

![Image](https://github.com/geosolutions-it/MapStore2/assets/88064044/b7ff06ed-48d6-4cfb-8a94-fd83b7845dbd)

All test have passed on QA.

![Image](https://github.com/geosolutions-it/MapStore2/assets/88064044/1394d1f3-16ea-4113-822c-042fb56e32ed)

**Comment by tdipisa** [comment]
@david7378 (FYI @randomorder) the binary sis starting correctly now. @ElenaGallo please resume the f[unctional test](https://studio.cucumber.io/projects/292756/test-runs/954589/folder-snapshots/11237673/scenario-snapshots/35031401/test-snapshots/46751833).
