### ISSUE TITLE
Increase Codacy Level to A

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#1021]
We should solve the existing issues with Codacy: https://www.codacy.com/app/simone-giannecchini/MapStore2/dashboard

**Comment by Gnafu** [comment]
We actually already have an A rating, most of the codacy errors are false-positive from JSHint.
JSHint does not support JSX so it can be disabled (we are using ESlint)

**Comment by offtherailz** [comment]
Updated codacy config. Closing...
