### ISSUE TITLE
Mobile issue - Overlay of tools and info

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#10214]
## Description

Tool and info overlay in the lower right corner of the map viewer.

![unnamed (1)](https://github.com/geosolutions-it/MapStore2/assets/56537133/7d75816f-4a83-4d94-8f96-eaa2ab5b6f83)

## How to reproduce

-  Open [this map](https://qa-mapstore.geosolutionsgroup.com/mapstore/#/viewer/10358) on mobile

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by 404answernotfound** [comment]
What would be the expected behaviour for this one?

**Comment by mahmoudadel54** [comment]
Hi @tdipisa 
Is is acceptable to move the scale bar from right side to left side to avoid the overlay? like this

![image](https://github.com/geosolutions-it/MapStore2/assets/58145645/f2a3b850-fcc0-48e3-8c4c-62f76dc34c25)

**Comment by tdipisa** [comment]
@mahmoudadel54 

> Hi @tdipisa Is is acceptable to move the scale bar from right side to left side to avoid the overlay? like this

Probably you didn't notice in that case the scalebar cover the footer and the attribution there reported. It should stay close to the navigation toolbar, I think. something like the following in case of widgets present in the map:

![image](https://github.com/geosolutions-it/MapStore2/assets/1280027/41792a0a-dd5b-43e5-afae-9922ff940e6b)

and this in case of missing widgets

![image](https://github.com/geosolutions-it/MapStore2/assets/1280027/afe3dd18-67e5-43e9-805b-285a3f885fb4)

It should be only a matter on CSS as far as I know.
