### ISSUE TITLE
Mobile issue - When the TOC opens the navigation toolbar change position

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#10213]
## Description

Opening the TOC the Navigation toolbar is horizontal instead of vertical

https://github.com/geosolutions-it/MapStore2/assets/56537133/365265f4-47e8-41a3-8149-3c1673c787d9

## How to reproduce

-  Open [this map](https://qa-mapstore.geosolutionsgroup.com/mapstore/#/viewer/10358) on mobile
- Open the TOC

**Comment by tdipisa** [comment]
@ElenaGallo moved to 2024.01.01. It is a behavior present also in 2023.02 series
