### ISSUE TITLE
Feature info issue on delete layer

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#10222]
## Description

When I delete a layer, the feature info stop working (probably it remains connected to the deleted layer, selected previously).

This doesn't look to happen with previous TOC.

## How to reproduce
- Take a map with at least two layers. No layers selected in toc
- delete one layer by selecting and clicking on remove (and confirm delete) from the toc
- try to perform again a feature info with no layer selected in TOC

[screencast-dev-mapstore.geosolutionsgroup.com-2024.04.19-11_42_58.webm](https://github.com/geosolutions-it/MapStore2/assets/1279510/3e54282e-1b8c-4ed7-bf1a-a6b5797585fb)

*Expected Result*
Because no layer is selected, the feature info should be performed on all layers

*Current Result*
Feature info do not work. Selecting and unselecting a layer from the TOC restores the previous behavior.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

Looks to be caused by the selected layer single feature info, not cleaned up. 

I'd suggest to make more visible, in any case, when you have only one layer selected. Several times, as a user, I have the impression there is a bug, while I simply forgot that, selecting a layer on the TOC, the feature info is performed only on that layer.

**Comment by tdipisa** [comment]
@ElenaGallo I confirm what reported by @offtherailz. I'm going to schedule a fix for this.
