### ISSUE TITLE
MS DEV build is not working in Jenkins

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#10228]
## Description

The job has not been triggered for the following during the last 2 days (even if I try to run it manually it from the Jenkins admin UI it doesn't start).

https://github.com/geosolutions-it/MapStore2/pull/10221

**Comment by ElenaGallo** [comment]
@tdipisa @randomorder Now Jenkins has built the PR

![sdasd](https://github.com/geosolutions-it/MapStore2/assets/56537133/f7a5d865-7aac-4333-a156-fb2f863852f4)

**Comment by tdipisa** [comment]
I'm going to close then @ElenaGallo
