### ISSUE TITLE
Enhance UX for simple 3D navigation in touch devices

### ISSUE THREAD

**Issue by mahmoudadel54** [geosolutions-it/MapStore2#10225]
## Description

We need to provide further options for the 3D map navigation aimed to limit the user interaction for a more guided 3D experience  in contexts where the navigation should not go outside to a particular area and the user should be well focused on a limited extent with limited navigation capabilities. This task mostly involves the 3D Camera settings for which further options should be provided 
(if possible) in the 3D map map settings UI (see documentation [here](https://docs.mapstore.geosolutionsgroup.com/en/latest/user-guide/mapstore-toolbars/#side-toolbar)).

![Image](https://github.com/geosolutions-it/MapStore-C299/assets/1280027/02b566f8-b4c4-4b15-912c-9fba26c38044)

Possible options we should provide to limit the 3D navigation are the following:
- Guided 3D navigation: fix camera orientation limits and/or fixed camera orientation ([this sandcastle](https://sandcastle.cesium.com/index.html#c=7Vrrc9u4Ef9XUF9nKvdkWO+H7XjqU+SJZvzI2Mpl2rqToylI4pkiVBC0497of+/iSVCkJNpKvzUfEhFYLH77xGIRn0YxR88BeSEMfUAReUEDEgfJAv8qxyoPB778HtCIe0FE2MPB4elD5Mt1sU8iAsvUeiw/7aQfUv8pnZSfMBkSjhiZEkYin1wyb0E+s2AR8OBZLH2Ipknk84BGaBq+jum9F30MyIxWDtEfDxFC8D3xvZiHBE+IH3qMVDJ0AhuyWwJz5mFJUJHLEZqQmAeRJ3Y4MaIOPMbhlxc18ZTRxUcyY4TElaN6vYvrnSpqNnC3XkX1dq1Ww7XDquC0Ejut8oA/EW8SRLPPAffndzQMdwFfp/+xAjQauNGoolYH1+EfFz9ClAUEbKoYaeYIzRUey/ra43PM6R2MelFcaTgMEFoK1JtIj5ptl5aBcCcIluuR1VY1XlFfItulPkN3KH0HoeNjNGDE4wT5Xhg+euCBU8rQI6MvMWF/idGM0FCvEfTurpUljQPJzKhjixneZAizBDSmt8A+pWwS45BGs4AnE1LdQgN7rJHUpSXNt1HySjnPyqriIn4yoks1GMmrCNQpREZ8DoGIBXnkPQczj1OGHRXBbz5IGMQq/6xRCb3njSY0dUd87kWzkGwxWobOGE3lixfQJ6SLo24X107T4ZgmfA7jzV5mmHiaupEZjiiT1C01nE4wsylMamNZHAW2EmC0ViUA/Vvsqn/KncTPooiNCRf5szBmLZI0ALS57uf0RVgkJcEI3VAB/t9JwMjkFP2egCzClDHQYmdjsBCYh8TYm0zMtpaNE9/SpwQWEq9DEX+mgYjSqRfG6RjIH0LmP0GcJbnRAfgKS/1ffOGvn0bjYakwL+MyWcJin+nX3uIzvW6xz2SZ/G895i1Z/v8eIz0GguouUzhscZocbdZvoFDhsuDZcYB227jd73a7VekczV6veeh4CGdwzoFqFymjsRmKsbD8jTD5l+WYXgbfyUSBVns7RhSZAgWRdJUj6SRHyRJNBbGDWDqJU07JbwVG+Y+kY6JGm1x8D+JC4b7cjMbf/uGuCil9uuAWtnZmK5lx3bQuTLmJ+qImD6Iqcn6aX4euqxtftZWfkm/NW6V7bigOQR5ZX+KlGVGemwP4kTwms2s6ISEUJCz4bjmkR/cinT3JyYpQSKIZh7pGnLI1p2KxEuX88g1VXwH1mm/utPS206VcISIdu9fqWpGle/fTb7fAKFkwHrll4OfRt9tfh3ffxl9v16vFQrrL2y93by8VA59NK9IrqogHEOQKVjBFahQLQ6M/fbChcC9GhW/g+8HwZtj8aEs9RnjCIrd+UtYQW+jwLYxyny6WCSejlEz5VUXiOTVw9MIJmYr4rDhcDy2EneY3JHQ6BRcoDHC4ZUWQYpSf2Ho2s7ogaynILekqd1SZWMoYqiLcGMaBrV3DcC5OJmloacy2QM1Xj6NoNLi73FE6KqKN5+cnCvm1ZsNJ3DjxIgl5sAwDme6b6K+oU5N/SSQ6o9CYf1lO4IQTGWX4DF5+FcQcppi01KFDOwvpI4Gz03sMyVUwm0PkzYCxOOiMe/r2Tj2Yw1kpHWdC/WQBfEVBPQyJ+PnL6wiy14FDp67W5oq8oM/knoNpT92RYTTJXpOV9BJ0vEV7LlnpfOOAgHmtZzuUV5YFVclcobR4OOavAlEQL0PvFRg+HDwKEz0cnNr4RqmY2R1h4AfsF0F0uNs59lJ7lbFYhjJvMz1RZCU1tdtMms7YSfAOAFLNUVAKNBsFvpZ9i66UopaEiUrEm8kiw+rv55+DTEwbXQYRMBmT78IRfhsol9FzJ+jPfwSrKvyd8sRcpQmbOjo6Yax+K2RfwjVy14dRdDEI+Ov2q4Mm2uDyKqbzJ+x7Oy7p+drE/V67V+s3G516t97ruSdtt9VrNVu1TqfXb/UadqbZaWIYbva6jW6j1Wk0WtnzVxw14ApQVhf4PRJlyBjOHKiyK4XzxcLt0ctwBYUqud3p9gF9NUsgxG132/1+q1UHsdr1tfl6r4PbtV6z125DQVLvdvvu/GGGurgAKdm3yjSuyrSv2rkVq8wXlOuw4aVWtWUzzAzjq9HN8OLu283tzdBZvTIHp2Aqiy0zsLHWCWl8AaESknhMx/TplVa8ibjbySpSm3m7dzsXF7H+din4invC+/283uzjXr2Venezjbv1VurT+i7wpkKy2B71dvnOY2dn3xGkTZhG0DBTEBi3z4RdmZ7cJv6dtAucUWvo/QidyrZzt9FPddrCrXa2NM+pNJWmvY+Sjwq1/O6K3ZxfRi/YpDBQUEGO2pXBMvnL9eE0eJxYMruL8jsfKigTBFhKeiGpPhFR1gFCwUozTiXYSmhuDi5Ou7TwDMv4WwHM4kMts0pJm08Pu/f7GvC53KxSfje7ZtO2ohK2WzsMoSAZUxo+euyaREnln2K1sQSUFSdw5OuyQuvr4UA5UbWA8jJ8FR0TD/lwtmtCcPkoBiQ+33BAMgIOVkkzr1tC2EEH8RzMGwoTr9URjoNvwsapYITkk9Qe8Nz3r50I1x/ByoA0zyfoBcxqkkNVxb18IxCBvZcA+c5ICUGKH8XKCHT9amXaC3b6/lQCrvsIVQ6mbSTvBdLpnpdAmWmh74ApW5Le/jDXnoW2o8y9De0AeU9srbPWVnwv3IIO83bIhW3m8rALoq66d9gVtiN3ivGOkDN9a9GS2cdBTOdnt3ek7Z8d0K7hhoyIbHa8F1m2r7Id23pzZQc6fc7pq7rCuR9M21gog9PpLpTIVqJEhZwaI33Oi/QlT3qwnYeGCaPLfbJYtgDanccKSp+tIlxR+oQm9CUSJbLo1ZHv3mwGWuBEvIALtj8KvVNOvU2MtZrKledfqnFRWEf9knAumrMHA1NVXxp58gK4d0Fbhit6VSmW2siDPBeW30aS5zexq7RGM0s1tGvKlkaR6w+WqgN2YfNa7l1IEVQ2vCS5i/gLIdE6xw1Ne6cbeui8G9hBa3bbwrTcSvclc0xhOok0gnX2ubnVDuwawDp6PbyGP+0wupuUa965fdaiXv36Q8HaO8To4/BmPBr/fUsnv443dPC1dt7TxJeP2ObqYh6QwA1NfJVoQKc5Qvr6QfXgTGrn3CSEvwWLJQWzJiysYHzMCbAWT+vHj4n/RDj24zh1GoR+cvzG3rZ/yvaqnU6YtsEJEgY4TcfFf4SaMQqGPPLV8zuz7qRai3LwZR7wdNlK/Tg7diU4mwTPKJh8KPh/gWAmL45hZpqE4X3wH/CA87NjoM8tDaksNkQSBLSCbF4/v1KDGOOzY/gsXslVRoIlBmU6l3lJOZfVif50eWVEyHbyz7N97QwC5/d/AQ) has a "set camera reference frame" example that could be interesting for our purposes)
- Block tilt operations to prevent the user from going underground 
- Limited zoom level if possible
- Quick reset of the 3D map view (the camera view) to restore the initial state (this could stay in the map [Navigation toolbar](https://docs.mapstore.geosolutionsgroup.com/en/latest/user-guide/navigation-toolbar/))
- Enable/disable the compass

Considering the above points (any other interesting idea?) we need first of all to investigate on possible options available in the Cesium JS version current used by MS and evaluate the effort for implementing them

**What kind of improvement you want to add?** (check one with "x", remove the others)

- [x] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by mahmoudadel54** [comment]
As per my initial investigation:
- Guided 3D navigation: fix camera orientation limits and/or fixed camera orientation 
[is applicable to implement by current map center]

- Block tilt operations to prevent the user from going underground 
[currently disable tilt will disable rotate/zoom by wheel but for applying disable only tilt will need a workaround to implement disabling only the tilt]
- Limited zoom level if possible [it is applicable]
- Quick reset of the 3D map view to restore the initial state 
[it is applicable preserve the stored camera map scene]
- Enable/disable the compass 
[it is applicable, if user disables the compass, the compass will hide --> as vice versa the compass widget will show it]

**Comment by tdipisa** [comment]
@mahmoudadel54 got it. Thank you.



> As per my initial investigation:

As I said in the call let's implement it for now only at plugin config level by exposing the new properties. We will evaluate for a possible UI in a second moment

> * Guided 3D navigation: fix camera orientation limits and/or fixed camera orientation
>   [is applicable to implement by current map center]

ok

> * Block tilt operations to prevent the user from going underground
>   [currently disable tilt will disable rotate/zoom by wheel but for applying disable only tilt will need a workaround to implement disabling only the tilt]

let's hear from @allyoucanmap but I would like to maintain things simple and in line with the Cesium JS lib for the moment without any workaround since there are not specific need for doing this.

> * Limited zoom level if possible [it is applicable]

ok 

> * Quick reset of the 3D map view to restore the initial state
>   [it is applicable preserve the stored camera map scene]

ok 

> * Enable/disable the compass
>   [it is applicable, if user disables the compass, the compass will hide --> as vice versa the compass widget will show it]

I think this can go together with point 2
