### ISSUE TITLE
On Dashboard and Geostory it is no longer possible to interact with layer filter 

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#10237]
## Description

If a layer filter is adde to a layer on map, then on Dashboard and Geostory it is no longer possible to interact with it.

## How to reproduce

-  Open a new Dashboard
-  Click the Map Widget
-  Select Demo map

*Expected Result*

* On PROD*

https://github.com/geosolutions-it/MapStore2/assets/56537133/c20e8a92-e651-443c-8ef8-fe665cdd7c0d

*Current Result*

*On DEV and QA*

https://github.com/geosolutions-it/MapStore2/assets/56537133/9b1ec618-50e8-4525-b4f3-298fc5a386af

https://github.com/geosolutions-it/MapStore2/assets/56537133/047e92a0-e26c-4d57-a4ff-4b70122d8c3e

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@allyoucanmap as we have agreed in the call let's fix the regression but open also a new issue to evaluate also to enable the ability to manage layer filters also in dashboards (I don't think this should be done for the geostory simple editor and in geostory advanced editor it is already possible).
