### ISSUE TITLE
User Session Plugin - Possibility to differentially save different parts of the map state

### ISSUE THREAD

**Issue by ale-cristofori** [geosolutions-it/MapStore2#10232]
## Description
The suggested enhancement would allow a more granular control over the elements that can be saved and retained in the Map resource using the User session plugin. 

At the moment the plugin saves the entire user session including plugin settings, catalog settings, annotations, measurements, bookmarks, etc. When a user wants to clear the user session all the elements, part of the map state are cleared and removed.

It is not possible for the user to control and differentiate which parts of the state they want to remove, the enhancement would see the user to choose which part of the user session clear, while retaining some other elements. For example a user might want to clear all measurements from a map but keeping all other annotations, this is not possible at the moment.

## Acceptance criteria

- [ ] as a user accessing a map resource that has the plugin user session activated and with an already saved map state I open a window dialog, similar to the one present in the browsers that would allow the user to choose which parts of the saved state they want to remove or keep.
- [ ]  User chooses which parts of the state they want to remove and click on save. The required parts of the state are cleared and the parts that the user wants to keep are still present on the state and in the map resource.

**Comment by tdipisa** [comment]
closed in favor of https://github.com/geosolutions-it/MapStore2/issues/10657
