### ISSUE TITLE
Issue adding layer when a group is present on TOC

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#10246]
## Description

When a group exists in the TOC but is not selected, add a layer via the Add Layer button, a new Default group with the added layer appears in the TOC.

https://github.com/geosolutions-it/MapStore2/assets/56537133/1aacfc74-ee6d-49c4-be18-e494c2d1b090

## How to reproduce

-  Open a map
- Create a group on TOC
- Click on Add Layer button 
- Select layer on Catalog

*Expected Result*

The layer is added without any groups

*Current Result*

The added layer is located under a new default group

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@ElenaGallo this is not an issue. The logic is still the same as before since it is not expected at the moment to have a layer outside a group.

**Comment by tdipisa** [comment]
> @ElenaGallo this is a know behavior we have maintained for retro-compatibility with old maps. A new issue will be openend to provide further updates for this in 2024.01.01

Opened this https://github.com/geosolutions-it/MapStore2/issues/10247

**Comment by tdipisa** [comment]
@allyoucanmap as discussed let's focus on a temporary fix for the specific use case reported in this issue waiting for https://github.com/geosolutions-it/MapStore2/issues/10247
