### ISSUE TITLE
Interaction between the Legend filter and the Layer filter

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#10241]
## Description

It should be possible in GS to filter the JSON legend according to the general filter defined in 'Layer filter' because now when there is an attribute filter for the layer and the interactive legend is enabled, the interactive legend does not work as expected.

https://github.com/geosolutions-it/MapStore2/assets/56537133/361e52af-1bfd-4d27-ad26-1502a2572f0f

## How to reproduce

-  Open [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/50089)
- Click on Filter Layer
- Set the Attribute Filter
- Click on Settings layer
- From Display tab, set Enable interactive legend 
- Click on X
- Open the layer Legend

- [x] Not browser related

## Acceptance criteria
- Interactive legend should be filtered based on the layer filter
- legend filter applied to the layer are not valid anymore, an inline warning is displayed along with a button to reset legend filter state https://github.com/geosolutions-it/MapStore2/issues/10684#issuecomment-2503955823

## Other useful information

Related to https://github.com/geosolutions-it/MapStore2/pull/10180#issuecomment-2071968824

**Comment by tdipisa** [comment]
To evaluate if it is possible to make cql_filter working with GetLegendGraphic on the GS side e.g.:
https://gs-stable.geo-solutions.it/geoserver/wms?service=WMS&request=GetLegendGraphic&format=image/png&height=50&width=100&layer=gs:us_states&style=pophade&version=1.3.0&SLD_VERSION=1.1.0&LEGEND_OPTIONS=forceLabels:on&LANGUAGE=en&SCALE=18489335&CQL_FILTER=("SUB_REGION"='E N Cen' OR "SUB_REGION"='E S Cen' OR "SUB_REGION"='Mid Atl' OR "SUB_REGION"='Mtn')

**Comment by allyoucanmap** [comment]
> On the MS side we can for sure prevent the interactive legend from displaying under certain conditions. In general, on the GS side, it would be good to evaluate a possible enhancement of the [GetLegendGraphic](https://docs.geoserver.org/main/en/user/services/wms/get_legend_graphic/index.html#content-dependent-legends) handling in JSON format
> 
> Standard GLG is filtered only if _hideEmptyRules_ is specified in the request:
> 
> `https://gs-stable.geo-solutions.it/geoserver/wms?service=WMS&request=GetLegendGraphic&format=image/png&height=50&width=100&layer=gs:us_states&style=pophade&version=1.3.0&SLD_VERSION=1.1.0&LEGEND_OPTIONS=forceLabels:on;hideEmptyRules:true&LANGUAGE=en&SCALE=18489335&CQL_FILTER=("SUB_REGION"='E N Cen' OR "SUB_REGION"='E S Cen' OR "SUB_REGION"='Mid Atl' OR "SUB_REGION"='Mtn')`
> 
> The JSON legend seems to completely lacking this logic:
> 
> `https://gs-stable.geo-solutions.it/geoserver/wms?service=WMS&request=GetLegendGraphic&format=application/json&height=50&width=100&layer=gs:us_states&style=pophade&version=1.3.0&SLD_VERSION=1.1.0&LEGEND_OPTIONS=forceLabels:on;hideEmptyRules:true&LANGUAGE=en&SCALE=18489335&CQL_FILTER=("SUB_REGION"='E N Cen' OR "SUB_REGION"='E S Cen' OR "SUB_REGION"='Mid Atl' OR "SUB_REGION"='Mtn')`

After an additional investigation it seems possible to filter rules in a legend but all the following parameters must be included in the GetLegend graphic request:

- BBOX
- SRS or CRS (depending on the WMS version, SRS for 1.1.1 and CRS for 1.3.0)
- SRCWIDTH and SRCHEIGHT, the size of the reference map (width and height already have a different meaning in GetLegendGraphic)
- Content dependent evaluation is enabled via the following LEGEND_OPTIONS parameters:
  - countMatched: adds the number of features matching the particular rule at the end of the rule label (requires visible labels to work). Applicable only to vector layers.
  - hideEmptyRules: hides rules that are not matching any feature. Applicable only if countMatched is true.

After testing, hideEmptyRules works also if the countMatched is not present in the request.
Here a working example:

`https://gs-stable.geo-solutions.it/geoserver/wms?service=WMS&request=GetLegendGraphic&format=image%2Fpng&height=50&width=100&layer=gs%3Aus_states&style=pophade&version=1.3.0&SLD_VERSION=1.1.0&LEGEND_OPTIONS=hideEmptyRules:true;forceLabels%3Aon&LANGUAGE=en&SCALE=231116&SRS=EPSG%3A3857&CRS=EPSG%3A3857&SRCWIDTH=512&SRCHEIGHT=512&BBOX=-8453323.832114212%2C4696291.017841227%2C-8140237.76425813%2C5009377.085697309&CQL_FILTER=(%22SUB_REGION%22%3D%27E%20N%20Cen%27%20OR%20%22SUB_REGION%22%3D%27E%20S%20Cen%27%20OR%20%22SUB_REGION%22%3D%27Mid%20Atl%27%20OR%20%22SUB_REGION%22%3D%27Mtn%27)`

Map
![Map](https://gs-stable.geo-solutions.it/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=gs%3Aus_states&STYLES=pophade&SRS=EPSG%3A3857&CRS=EPSG%3A3857&TILED=true&ENV=mapstore_language%3Aen&CQL_FILTER=(%22SUB_REGION%22%3D%27E%20N%20Cen%27%20OR%20%22SUB_REGION%22%3D%27E%20S%20Cen%27%20OR%20%22SUB_REGION%22%3D%27Mid%20Atl%27%20OR%20%22SUB_REGION%22%3D%27Mtn%27)&WIDTH=512&HEIGHT=512&BBOX=-8453323.832114212%2C4696291.017841227%2C-8140237.76425813%2C5009377.085697309)

Legend
![Legend](https://gs-stable.geo-solutions.it/geoserver/wms?service=WMS&request=GetLegendGraphic&format=image%2Fpng&height=50&width=100&layer=gs%3Aus_states&style=pophade&version=1.3.0&SLD_VERSION=1.1.0&LEGEND_OPTIONS=hideEmptyRules:true;forceLabels%3Aon&LANGUAGE=en&SCALE=231116&SRS=EPSG%3A3857&CRS=EPSG%3A3857&SRCWIDTH=512&SRCHEIGHT=512&BBOX=-8453323.832114212%2C4696291.017841227%2C-8140237.76425813%2C5009377.085697309&CQL_FILTER=(%22SUB_REGION%22%3D%27E%20N%20Cen%27%20OR%20%22SUB_REGION%22%3D%27E%20S%20Cen%27%20OR%20%22SUB_REGION%22%3D%27Mid%20Atl%27%20OR%20%22SUB_REGION%22%3D%27Mtn%27))

**Comment by ElenaGallo** [comment]
When the Interactive legend is enabled and then a filter layer is added, if I disable the filter layer it is no longer possible to filter the legend.

https://github.com/user-attachments/assets/7e8cd776-28ff-4d19-863b-104159302fb3


*How to Reproduce*
- Open [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/52184)
- Enable Interactive legend for the layer
- Create a Filter layer 
- Disable the filter layer
- > the legend is no longer filterable

**Comment by dsuren1** [comment]
@ElenaGallo This is the expected behavior. When you disable filter, it disables all the filters (layer and legend) and becomes applicable only when filter is enabled on the layer. This is to maintain consistent behavior
