### ISSUE TITLE
Axios 0.28.0 missing paramsSerializer

### ISSUE THREAD

**Issue by dsuren1** [geosolutions-it/MapStore2#10250]
## Description
With axios 0.28.0, the paramsSerializer functionality is [missing ](https://github.com/axios/axios/issues/6262)and was later fixed with release of [0.28.1](https://github.com/axios/axios/releases/tag/v0.28.1)

This feature is needed for projects relying on paramsSerializer feature of axios (ex. Geonode)

This will not impact any existing features that MS relies but only adds the missing paramsSerializer feature back into axios 0.28

>[!NOTE]
This release does not address missing paramsSerializer as function though, however supports paramsSerializer as an object

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Update library

**Comment by tdipisa** [comment]
Reviewing more in depth changes provided in [0.28.1](https://github.com/axios/axios/releases/tag/v0.28.1) with @offtherailz and @allyoucanmap we can include it in 2024.01.00.
