### ISSUE TITLE
User Guide - Use Cache Options from WMS service

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#10359]
## Description

Add Use Cache Options on [Catalog](https://docs.mapstore.geosolutionsgroup.com/en/latest/user-guide/catalog/#advanced-settings_2) section 

*Documentation section involved*
- [x] User Guide
- [ ] Developer Guide

## Other useful information
Related to #10281

**Comment by ale-cristofori** [comment]
@tdipisa, will it be part of this PR the documentation of the plugin configuration in the `localConfig.json`? If so, the PR does not seem to contain this part of doc 
https://github.com/geosolutions-it/MapStore2/pull/10362

**Comment by tdipisa** [comment]
that's the user guide @ale-cristofori as indicated in the title
