### ISSUE TITLE
TOC - Open on map initialization options does not work as expected

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#10371]
## Description

By enabling the option and saving the map, the toc does not remain open the first time.

## How to reproduce

-  See the video below

https://github.com/geosolutions-it/MapStore2/assets/56537133/42604420-ff0c-4a73-9723-94345c0be869

*Expected Result*

The toc is open after saving

*Current Result*

The toc is close after saving

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

See also https://github.com/geosolutions-it/MapStore2/issues/10375

**Comment by tdipisa** [comment]
@ElenaGallo @dsuren1 looking at my personal map context [here](https://qa-mapstore.geosolutionsgroup.com/mapstore/#/context/demo_context/44920), it seems it is working only when you open the map from home: if you for example reload the map in a second time, it doesn't work.

**Comment by dsuren1** [comment]
@tdipisa 
The plugins is sometimes not ready (context hasn't finished loading plugin yet) when map config is loaded to update TOC state which in turn results in TOC panel to remain closed. But sometimes the plugins is ready resulting in two different behavior when loading context
