### ISSUE TITLE
Missing libraries in Printing-module of the release

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#10396]
## Description

Trying to install the printing lib in 2024.01.00, there are some missing libs

## How to reproduce
-  download binary (from release)
- download printing module (from release)

*Expected Result*
- printing works

*Current Result*
- there are some missing libs. 

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

On QA binary this is not reproducible because it builds with the printing profile (for deploying on server), so the binary also already contains the proper files. 

Here I attach the list of libs provided by elena, sorted up and cleaned.

[2024.01.00-libs.txt](https://github.com/user-attachments/files/15534945/2024.01.00-libs.txt) binary downloaded from release and added with `printing-module.zip` jars
[2024.01.xx-libs.txt](https://github.com/user-attachments/files/15534946/2024.01.xx-libs.txt) build with `printing` profile on QA.

Here the patch of the comarison:

(We did with @ElenaGallo a test adding simply json-20230618.jar but it was not enough. We had an exception for other missing classes, so also other libs may be missing.  

This is caused by https://github.com/geosolutions-it/MapStore2/blob/master/java/printing/assembly/mapstore-printing.xml that has the includes that do not match anymore the libs to include. 

```diff
--- /home/offtherailz/work/tmp/2024.01.00-libs.txt
+++ /home/offtherailz/work/tmp/2024.01.xx-libs.txt
@@ -1,9 +1,12 @@
+
 
 acegi-security-1.0.7.jar
 acegi-security-tiger-1.0.7.jar
 activation-1.1.jar
+aircompressor-0.20.jar
 antlr-2.7.7.jar
 apache-mime4j-0.6.jar
+apiguardian-api-1.1.1.jar
 asm-2.2.3.jar
 aspectjrt-1.5.4.jar
 aspectjweaver-1.5.4.jar
@@ -26,6 +29,7 @@
 batik-xml-1.17.jar
 bcpkix-jdk15on-1.64.jar
 bcprov-jdk15on-1.68.jar
+bigint-0.7.1.jar
 btf-1.2.jar
 btf-1.3.jar
 byte-buddy-1.11.12.jar
@@ -107,6 +111,7 @@
 imageio-ext-streams-1.4.7.jar
 imageio-ext-tiff-1.4.7.jar
 imageio-ext-utilities-1.4.7.jar
+indriya-2.1.3.jar
 istack-commons-runtime-3.0.7.jar
 j2objc-annotations-1.3.jar
 jackson-annotations-2.16.1.jar
@@ -114,6 +119,7 @@
 jackson-coreutils-1.12.jar
 jackson-coreutils-1.6.jar
 jackson-databind-2.16.1.jar
+jackson-dataformat-yaml-2.16.1.jar
 jackson-jaxrs-base-2.10.5.jar
 jackson-jaxrs-json-provider-2.10.5.jar
 jackson-module-jaxb-annotations-2.10.5.jar
@@ -122,6 +128,7 @@
 jai_imageio-1.1.jar
 jakarta.activation-1.2.2.jar
 jakarta.activation-api-1.2.2.jar
+jakarta.annotation-api-1.3.4.jar
 jakarta.annotation-api-1.3.5.jar
 jakarta.jws-api-2.1.0.jar
 jakarta.mail-1.6.5.jar
@@ -138,6 +145,7 @@
 javassist-3.8.0.GA.jar
 javax.activation-api-1.2.0.jar
 javax.annotation-api-1.3.2.jar
+javax.inject-1.jar
 javax.persistence-api-2.2.jar
 javax.servlet-api-3.0.1.jar
 javax.xml.soap-api-1.4.0.jar
@@ -157,6 +165,7 @@
 jdom-1.0.jar
 jettison-1.4.0.jar
 jgridshift-core-1.3.jar
+json-20230618.jar
 json-lib-2.4-jdk15.jar
 json-lib-2.4.2-geoserver.jar
 json-patch-1.12.jar
@@ -210,7 +219,7 @@
 log4j-api-2.19.0.jar
 log4j-core-2.19.0.jar
 log4j-slf4j-impl-2.19.0.jar
-mapstore-services-1.7.0.jar
+mapstore-services-1.7-SNAPSHOT.jar
 metrics-core-4.2.12.jar
 metrics-healthchecks-4.2.12.jar
 metrics-httpclient-4.2.12.jar
@@ -223,12 +232,20 @@
 mime-util-2.1.3.jar
 msg-simple-1.1.jar
 msg-simple-1.2.jar
+net.opengis.ows-30.0.jar
+openpdf-1.3.26.jar
+org.eclipse.emf.common-2.15.0.jar
+org.eclipse.emf.ecore-2.15.0.jar
+org.eclipse.emf.ecore.xmi-2.15.0.jar
+org.w3.xlink-30.0.jar
 oro-2.0.8.jar
 pdfbox-2.0.26.jar
 pdfbox-debugger-2.0.26.jar
 pdfbox-tools-2.0.26.jar
 postgresql-42.3.9.jar
-print-lib-2.4-SNAPSHOT.jar
+print-lib-2.4-20240306.103658-2.jar
+profiler-1.1.1.jar
+re2j-1.6.jar
 reactive-streams-1.0.3.jar
 resteasy-client-3.13.2.Final.jar
 resteasy-jackson2-provider-3.13.2.Final.jar
@@ -244,6 +261,7 @@
 si-units-2.1.jar
 slf4j-api-1.7.25.jar
 slf4j-api-1.7.36.jar
+snakeyaml-2.2.jar
 spring-aop-5.3.18.jar
 spring-beans-5.3.18.jar
 spring-context-5.3.18.jar
@@ -266,6 +284,7 @@
 spring-webmvc-5.3.18.jar
 stax-api-1.0-2.jar
 stax-ex-1.8.3.jar
+stax-ex-1.8.jar
 stax2-api-4.2.1.jar
 systems-common-2.1.jar
 txw2-2.3.1.jar
@@ -273,6 +292,7 @@
 unit-api-2.1.2.jar
 uom-lib-common-2.1.jar
 woodstox-core-6.4.0.jar
+xalan-2.7.0.jar
 xercesImpl-2.7.1.jar
 xml-apis-1.0.b2.jar
 xml-apis-ext-1.3.04.jar
```

**Comment by ElenaGallo** [comment]
@offtherailz here are the two libraries of version 2024.01.00 and version 2024.01.xx:
[202.01.00.txt](https://github.com/user-attachments/files/15534710/202.01.00.txt)
[2024.01.xx.txt](https://github.com/user-attachments/files/15534713/2024.01.xx.txt)
