### ISSUE TITLE
Remove the list of associated groups of logged in user from the User Details modal window

### ISSUE THREAD

**Issue by mahmoudadel54** [geosolutions-it/MapStore2#10414]
## Description
It is required to implement within configuration level, to enable remove all the groups listing for an authenticated authorized user in MapStore, in the User Details modal window.

## Acceptance criteria
- [ ] As a logged in authenticated user.
- [ ] WHEN I log onto MapStore AND I click on the 'User Menu' icon and on the 'Account Info' menu item
- [ ] THEN The appearing modal window, showing the user's account info shows
- [ ] AND The list of info does NOT contain any `Groups` section, listing the groups that the logged in user belongs.

![image](https://github.com/geosolutions-it/MapStore2/assets/58145645/30c2c0ac-160c-45d1-ab02-00933ea2fb0b)

**Comment by tdipisa** [comment]
@mahmoudadel54 at least Admin user should see this information for management/troubleshooting purposes.
