### ISSUE TITLE
GeoProcessing Tool Intersection issue

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#10429]
## Description

It seems the tool is not able to calculate an intersection using a precalcuated buffer if the intersectin feature is not selected

## How to reproduce

- Open [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/demo_context/46500)
- Perform a buffer as indicated in figure below

![Image](https://github.com/geosolutions-it/MapStore2/assets/1280027/1be17fed-9c32-4b33-8d0a-30f5252bde84)

- Use this buffer to calculate the intersection with the bugsites layer wthout selecting the _Intersection feature_

*Expected Result*

The intersection should be calculated using the whole buffer layer whle now 'undefined' is sent to the server

*Current Result*

![Image](https://github.com/geosolutions-it/MapStore2/assets/1280027/2a23de7b-c155-41f0-b01d-415d24699693)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by MV88** [comment]
that context was missing a key property as it it the wpsUrl

i have fixed the demo_context cfg of GeoProcessingTool and now it is working

**Comment by tdipisa** [comment]
@MV88 I don't think the issue can be closed. I didn't understand which config fix you applied. Can you please better specify it.
In any case it seems the tool now no longer works as before: for each layer I've selected (e.g. for the buffer) I have the following, which leads me to think there is some missconfiguration now:

![image](https://github.com/geosolutions-it/MapStore2/assets/1280027/92fbb331-553f-4a30-89fa-a1fdc687371c)

Can you please review again?

**Comment by MV88** [comment]
yes I misstyped the protocol

this is the cfg added

```
{
  "cfg": {
    "wpsUrl": "https://gs-stable.geo-solutions.it/geoserver/wps",
    "selectedTool": "buffer",
    "buffer": {
      "quadrantSegments": 200,
      "capStyle": "Round"
    }
  },
  "override": {}
}
```

**Comment by tdipisa** [comment]
@MV88 thank you. It is working now. Is there something to fix on the JS documentation for this or something to fix in the plugin default config for contexts? If no, please feel free to close the issue.

**Comment by MV88** [comment]
I think that we could close this issue. the thing is that every time this property is not configured it will cause this issue because 
- the source is a generated vector layer
- this needs a geoserver behind

solutions
- we can maybe introduce a default value pointing to out geoservers this would avoid this issue even tough is not ideal.
- otherwise we have to block the run button when this situation occurs

what do you think ?

**Comment by MV88** [comment]
as agreed with @tdipisa we will harden more the geoprocessingtool adding
- [ ] a check that verify that if wpsUrl is not configured or the layer.url is not present it disables the run button, this will prevent to run into errors messages that can be avoided with correct configuration
- [ ] we can add a default config in the pluginsCfg with "wpsUrl":"https://yourdomain/geoserver/wps"

**Comment by ElenaGallo** [comment]
Test passed @MV88 please backport to 2024.01.xx. Thanks
