### ISSUE TITLE
Search Plugin - JavaScript console error after first search executed on search bar

### ISSUE THREAD

**Issue by ale-cristofori** [geosolutions-it/MapStore2#10427]
## Description
The Search Service within Maps only seems to work one time before locking up the map. I've included a a screen recording.

The first search works but then nothing after that. Furthermore, the entire map gets locked up after that where I cannot: save the map (if logged in), use the Home button to get back to the main landing page, add new layers from the WMS service or edit layer properties, etc.

## How to reproduce
-  On MapStore DEV or QA, open a new empty map
- Input a search term on the search plugin
- Wait for results to appear and click on a result item for the map to zoom at the result
- clear the search bar and try input another search term and press any button.

*Expected Result*
The search routine should re-execute and it could be possible to do another address search

*Current Result*
The search plugin does not work anymore, so other plugins and there is a JavaScript console error (see below)

https://github.com/geosolutions-it/MapStore2/assets/14953970/73d9158e-9598-435a-8ce9-590c6c91bef2

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by mahmoudadel54** [comment]
> @mahmoudadel54 @tdipisa, client agreed on 2 hours estimation for investigation

@ale-cristofori  @tdipisa 
This is resolved in this PR: https://github.com/geosolutions-it/MapStore2/pull/10419

**Comment by ElenaGallo** [comment]
@tdipisa @mahmoudadel54 the bug is only present on QA

https://github.com/geosolutions-it/MapStore2/assets/56537133/81c55b74-5f44-45a1-917e-5fcde9283617

**Comment by tdipisa** [comment]
@ElenaGallo because the backport here still need to be merged 
https://github.com/geosolutions-it/MapStore2/pull/10435

**Comment by tdipisa** [comment]
Reviewed and merged now @ElenaGallo please retest once deployed.

**Comment by ElenaGallo** [comment]
@tdipisa the test also passed on QA
