### ISSUE TITLE
Dev Guide - Add new missing GeoServer Extensions

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#10430]
## Description

Update the list of GeoServer Extensions [here](https://docs.mapstore.geosolutionsgroup.com/en/latest/developer-guide/integrations/users/geoserver/#geoserver-plugins-and-extensions):

- [x] Check for missing extensions and add them such as: 
   - [x] https://docs.geoserver.org/stable/en/user/community/wps-longitudinal-profile/index.html
- [x] In _WPS Extension_ add the WPS processes used by the GeoProcessing tool 
- [x] Check and fix existing hyperlinks and fix them if necessary
- [x] The paragraph should be also moved on a better place in the dev documentation which is: intergations -> general -> geoserver

*Documentation section involved*
- [ ] User Guide
- [x] Developer Guide

**Comment by tdipisa** [comment]
@ElenaGallo please fix the description as requested. Thank you.
