### ISSUE TITLE
Provides meaningful message is user has not enough access rights to view a maps. WAS: Mapstore page never finishes loading

### ISSUE THREAD

**Issue by aaime** [geosolutions-it/MapStore2#1045]
http://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/leaflet/1024?_k=ej86r7

![image](https://cloud.githubusercontent.com/assets/325433/18919597/172a307c-859f-11e6-9491-ef2c0f7382e5.png)

All I can see that's wrong are failed requests to mapquest and, I presume, google:
https://www.mapquestapi.com/sdk/leaflet/v2.2/mq-map.js?key=__API_KEY_MAPQUEST__
http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=25.14&action=apiboot2&rt=main.18

**Comment by aaime** [comment]
Btw, tested on Chrome (with adblock) and Firefox (no adblock), latest versions

**Comment by Gnafu** [comment]
This issue appears when the mapId is not found on the server

**Comment by simboss** [comment]
At least we know the reason, but we should give users a more meaningful feedback with respect to not loading anything.

In this case the map exists but the anonymous user was not allowed to see it.

This needs a fix IMHO.
