### ISSUE TITLE
Problems with GeoStory map configurations merge process

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#10489]
## Description

Legacy geostories used following configuration to store the difference between original resources and changes made to a map in a specific section:

original map resource
```
{
    "groups": [
        {
            "id": "group-02",
            "title": "over",
            "expanded": false
        },
        {
            "id": "group-01",
            "title": "base",
            "expanded": true
        }
    ],
    "layers": [
        {
            "id": "layer-01",
            "group": "group-01",
            "source": "osm",
            "name": "mapnik",
            "title": "Open Street Map",
            "type": "osm",
            "visibility": true
        },
        {
            "id": "layer-02",
            "format": "image/jpeg",
            "group": "group-02",
            "name": "workspace:layer",
            "opacity": 1,
            "title": "Layer",
            "type": "wms",
            "url": "/geoserver/wms",
            "visibility": false
        }
    ]
}
```

diff section map configuration
```js
{
    "groups": [
        null,
        {
            "expanded": false
        }
    ],
    "layers": [
        null,
        {
            "visibility": true
        }
    ]
}
```

The merging process of these two configuration has two steps:

- the diff configuration [was cleaned](https://github.com/geosolutions-it/MapStore2/blob/v2023.02.02/web/client/components/geostory/common/enhancers/map.jsx#L40) by replacing null layers with undefined
- then the [createMapObject](https://github.com/geosolutions-it/MapStore2/blob/v2023.02.02/web/client/utils/GeoStoryUtils.js#L176-L178) method was merging the two configuration so layers and groups array items were merged by index

This process had a problem in the step 1 because only null layers were converted but not group layers.

With the introduction of the new TOC the diff configuration for layers and groups was removed and this two field are cloned as soon there is a modification in the section. This introduced another problem described in this comment:

https://github.com/geosolutions-it/MapStore2/pull/10426#issuecomment-2176031801 

In conclusin we need to solve the issues described above:

- [ ] legacy geostory diff configuration should work also when groups are null
- [ ] new geostory diff configuration should not use the merge method for layers and groups becouse this two field are cloned using the new TOC

## How to reproduce

-  import this legacy geostory on MapStore: [legacy-geostory-with-null-groups.zip](https://github.com/user-attachments/files/16360425/legacy-geostory-with-null-groups.zip)

*Expected Result*

The geostory should be visible and working

*Current Result*

The application show the error message on full screen

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by mahmoudadel54** [comment]
> @mahmoudadel54 this issue need to be evaluated and estimates. Then a fix provided directly within the connected PR [here](https://github.com/geosolutions-it/MapStore2/pull/10438#issuecomment-2255366074).

Hi @tdipisa 
I have evaluated this issue and the initial estimate is 2 points [size 2]

**Comment by tdipisa** [comment]
@mahmoudadel54 you can proceed with this by updating the [connected PR](https://github.com/geosolutions-it/MapStore2/pull/10438) as requested.

**Comment by ElenaGallo** [comment]
waiting to resolve [this issue](https://github.com/geosolutions-it/MapStore2/pull/10426#issuecomment-2293383703) to close it
