### ISSUE TITLE
fetching the list of formats is disabled for a no-vendor WMS service

### ISSUE THREAD

**Issue by landryb** [geosolutions-it/MapStore2#10480]
## Description

my understanding is that it's a regression from #9712 which disabled loading formats when the servertype is no-vendor (eg the check added in https://github.com/geosolutions-it/MapStore2/blame/0b28a76d973374ea8d700c4f8e655391f43c5525/web/client/components/catalog/editor/AdvancedSettings/RasterAdvancedSettings.js#L196)

## How to reproduce
- add a no-vendor wms service to catalog

*Expected Result*
- one should be able to fetch formats from the wms service

*Current Result*
- the format refresh button and the format dropdowns are disabled

![image](https://github.com/user-attachments/assets/f54abb2b-4403-42a6-9370-a959ef9a01c3)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

witnessed on https://ids.craig.fr/mapstore/#/ where the regressing PR was backported to branch 2023.02, the `[CRAIG] orthophotographie` is such a no-vendor entry.

originally i wanted to ensure that for this catalog entry, the default format was `image/jpeg`, and i realized i can't set the format in the advanced options of the catalog entry. the format can still be fetched from the layer properties via the TOC, but not for the catalog entry.

i can workaround the issue by setting ` "layerOptions": { "serverType": "no-vendor", "format": "image/jpeg"}` in `localConfig.json` but fixing this annoying bug would be nicer. @mv88 ?

**Comment by tdipisa** [comment]
@rowheat02 the following could be used as an example of _no vendor_ OGC compliant server for reproducing the issue: https://tiles.craig.fr/pci/service

**Comment by allyoucanmap** [comment]
@rowheat02 the PR #9712 is connected to the issue #9295 where the problem was related to a CSW catalog, so in case of CSW catalog this option should be disabled for no vendor.

Note: the CSW and WMS catalog share the same component for the advanced settings ([RasterAdvancedSettings](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/catalog/editor/AdvancedSettings/RasterAdvancedSettings.js) component).
