### ISSUE TITLE
Custom Tile Grids settings for WMS service are not retained when adding a Background layer from Catalog

### ISSUE THREAD

**Issue by ale-cristofori** [geosolutions-it/MapStore2#10487]
## Description
We have the Custom Tile gridset to be enforced on every layer added from the catalog from a WMS service, acting on the `Use remote custom tile grids ` checkbox. Whenever we add a layer from the catalog the TOC or sidebar the setting is kept for every layer coming from the WMS service set to use the custom gridsets.

The setting is not retained when adding a layer from the background selector component. 

## How to reproduce
Open [this maps](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/51292)
-  On the Background layer selector click on the plus button to add a new layer. 
-  Select a the CLEV METRO BG layer WMS service layer from the catalog services list.
- Adding the layer to the map will open a dialog window
- Notice how the custom gridsets settings are not the default for the layer to be added. 

*Expected Result*
The layer to be added as BG layer should have the custom gridset option preset by default when opening the dialog window. Adding the layer to the map would already trigger the custom tiles settings for the BG layer

*Current Result*
The custom gridsets settings are not the default for the layer to be added. 

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information
https://github.com/user-attachments/assets/a80f4cd5-40f9-4edf-ad55-5f421a406c6b

**Comment by tdipisa** [comment]
@mahmoudadel54 the request should be similar to the one you have worked for https://github.com/geosolutions-it/MapStore2/issues/10281
