### ISSUE TITLE
Map Loading Spinner

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#105]
Introduce a spinner to show when the map is loading. The spinner should:
 * not be intrusive (small button / div to show over the map)
 * work with both leaflet and openlayers Map components
 * have a configurable delay before showing the spinner (so that is not shown at all if the map loading is very fast)

**Comment by simboss** [comment]
I would add to Mauro's the following:
* when the map is in full screen mode I would go for something similar to the one that cartodb has [see this](http://theconversation.com/big-data-reveals-the-business-risk-posed-by-unreported-ukraine-protests-24232)
* when the layer tree will be around we should rather use something on a per layer basis as the current version of MapStore has. 

It might be owrt to split this tank into two subtasks, one for the gloabl spinner, one for the per.layer one.

**Comment by simboss** [comment]
OK, we decide to split this task into a user story with two subtasks:
*  #108
*  #109
