### ISSUE TITLE
GetFeatureInfo in GeoStory does not trigger when one of the responses is an error (Popup)

### ISSUE THREAD

**Issue by dsuren1** [geosolutions-it/MapStore2#10577]
### Description
On the UI the GFI operation remains stuck to the initial results and every subsequent request is not executed, when clicking on another point on the map to identify the results remain the same as the first request.

> [!NOTE]
The scenario is reproducible only when the one of request ends up in error

### How to reproduce
- Open a geostory
- Make sure multiple layers are present with identify enabled
- Perform GFI by clicking on the map
- If one of the request fails, then any subsequent GFI calls are not fired instead previous results are only shown

### Current Result
The result of the GFI operation remains the same and there is an error on the response

### Expected Result
The result of the GFI operation should change according to the area

**Comment by giohappy** [comment]
The fix wasn't deployed due to this https://github.com/geosolutions-it/support/issues/3797#issuecomment-2454501220.
A new update is required.
