### ISSUE TITLE
Layer selectable even if the group it belongs to is turned off

### ISSUE THREAD

**Issue by danabit** [geosolutions-it/MapStore2#10632]
## Description
There is a problem in the selection similar to the printing problem which was solved here:
https://github.com/geosolutions-it/MapStore2/issues/10513

The same thing happens when you select on the map and the group is turned off but its nodes are turned on.
I take your map at the link as an example:
https://mapstore.geosolutionsgroup.com/mapstore/#/viewer/8613

If I turn off the “New York” group and select in an area where I know there is a State (but it is not visible because the group is turned off), the selection will still happen, even though the State of US layer is not visible.
This situation did not occur before version 2024.01.

## How to reproduce
-  Use a map with a group having at least one layer
-  Turn off the group (Leaving the layer inside turned on)
-  Try to select an area on the map where the layer is present (even if it is not visible)

*Expected Result*
There should be no results in the identify panel (since the layer is not visible on the map)

*Current Result*
The identify panel still shows results (even if the layer is not visible)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information
https://github.com/user-attachments/assets/482e6f16-f0ff-437b-a4f4-cc40a0a28516

**Comment by tdipisa** [comment]
Thank you for reporting @danabit
