### ISSUE TITLE
When logged in as an Admin account info is empty

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#1064]
See image below. We might want to check what happens also when you are not an administrator but an existing user.

![1](https://cloud.githubusercontent.com/assets/693880/19070823/6b2a8806-8a2d-11e6-940d-bd70846248d3.jpg)

**Comment by offtherailz** [comment]
This is because that user has no attributes associated. 

Let's add a message like this.
![image](https://cloud.githubusercontent.com/assets/1279510/19078978/50d2bf1c-8a52-11e6-8991-0b40b3d34eeb.png)

**Comment by offtherailz** [comment]
Maybe "there is no information..." is better

**Comment by simboss** [comment]
How it can happen that there is no information for the administrator??
