### ISSUE TITLE
Is not possible to add decimals in the aeronautical form

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#10663]
## Description

It is not possible to enter centesimal number 04 after the comma/dot

like 0.04

this bug was introduced here https://github.com/geosolutions-it/MapStore2/tree/ddf127e98663f55d02253496d7e4cba09c5f0416
provided for https://github.com/geosolutions-it/MapStore2/issues/10289 

## How to reproduce

- open map viewer
- open search by coordinate 
- switch to aeronautical
- try enter the decimal part as 04

*Expected Result*

to enter it 
*Current Result*

it resets to integer as soon one enters the first 0 and it removes the decimal separator too

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by MV88** [comment]
@ElenaGallo please test it in DEV

**Comment by tdipisa** [comment]
> [@ElenaGallo](https://github.com/ElenaGallo) please test it in DEV

@ElenaGallo please keep an eye on https://github.com/geosolutions-it/MapStore2/issues/10289 to improve its functional test including also this issue case.
