### ISSUE TITLE
Generic OpenID connect provider - Documentation update request

### ISSUE THREAD

**Issue by mdaehnert** [geosolutions-it/MapStore2#10666]
## Description
Since release 2024.01, there is support for generic OpenID Connect provider. Unfortunately the documentation isn't updated so far. Therefore setting up a generic provider is hard to understand and needs to be fetched from multiple PRs and Issue comments from MapStore2 and GeoStore.

It would be great, if the following elements can be documented:
* Where: https://docs.mapstore.geosolutionsgroup.com/en/latest/developer-guide/integrations/users/openId/
* What:
    * [MapStore-Client] Configuration inside _localConfig.json_
    * [MapStore-Server] Configuration inside _mapstore-ovr.properties_
    * [GeoStore] Configuration for GeoStore's _geostore-spring-security.xml_ file (As optional change, if no default version from GeoStore is used)

*Documentation section involved*
- [ ] User Guide
- [x] Developer Guide

## Other useful information
I'm also stuck at setting proper _mapstore-ovr.properties_ configuration so far. My server is failing to build locally if I add elements for oidcOAuth2Config. No exceptions and frontend loads, but backend returns 404 on each call (google: http://localhost:8081/rest/geostore/openid/google/login and generic oidc: http://localhost:8081/rest/geostore/openid/oidc/login and ). 
 If you could add a working example for the file in here early on, this would help me a lot! Thanks.

**Comment by tdipisa** [comment]
@mdaehnert thank you for reporting. We will check and try to improve the documentation for next releases.

**Comment by offtherailz** [comment]
Hi @mdaehnert . I checked it. The `latest` pointer was pointing to an older version of the documentation, because of a misconfiguration due to build system.
Now it should point to the documentation you need. Thank you very much for reporting. 👍 
I'm going to close this issue.
