### ISSUE TITLE
widgets in map wrongly align with a specific config

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#10676]
## How to reproduce

- use this config
```
{
        "name": "Widgets",
        "cfg": {
          "cols": { "md": 48, "xxs": 1 },
          "rowHeight": 10,
          "defaults": {
            "initialSize": {
              "h": 8,
              "w": 8
            }
          }
        }
      }
```
- open a map with some widgets in single widget layout (resize window until it triggers)

*Expected Result*

to see widgets panel correctly
*Current Result*

it goes very below and the widget is not fully visible, partially hidden 
this is due to the fact that rowHeight from configuration affect the baseHeight here 
https://github.com/geosolutions-it/MapStore2/blob/master/web/client/plugins/Widgets.jsx#L146-L148

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
Created https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/issue_10676/51750 for testing
