### ISSUE TITLE
Counter widget sends double requests, the first one has viewport as undefined

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#10674]
## Description

WpsCounter triggers a wrong request

## How to reproduce

- open a map  with a counter widget only
- inspect requests

*Expected Result*

to not see a first request with undefined in the payload
*Current Result*

two requests are sent
one has a payload geom as undefined
the other seems ok

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
note: the "undefined" filter is a more general problem, not related with counter widget (it appears also in WFS request of feature grid and in general whenever an and filter is used.

Here I opened a separate issue for the undefined filter problem https://github.com/geosolutions-it/MapStore2/issues/10695
