### ISSUE TITLE
Print bug in DEV

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#10692]
## Description

in DEV the printing tool is reporting an error when printing a map
![Image](https://github.com/user-attachments/assets/de222269-da56-4423-9374-1f2de0454798)

also in incognito the problem is the same
![Image](https://github.com/user-attachments/assets/8ff78e4b-368b-4551-bcf1-486a00ccc2e7)

while if you open the developer tool to see the response payload provided by the printing service, the PDF is available at the provided URL.

**QA and 2024.02.01 work as expected.**

## How to reproduce

- Open this map   
- Print the map

*Expected Result*

All print steps should work as expected 

![Image](https://github.com/user-attachments/assets/5cbcc536-2dcd-49e6-84a6-92510b071abe)

*Current Result*

The one above in description

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
I'd test also the build version, reading the documentation looks to need some attention more for webpack dist

**Comment by MV88** [comment]
working there
![Image](https://github.com/user-attachments/assets/01899c54-d01c-43b8-8833-81dff0423753)
