### ISSUE TITLE
Sources DD menu is too small in catalog Tool

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#10693]
## Description

It seems a recent commit broken the Catalog tool sources menu CSS

## How to reproduce

- Open a map in DEV
- Open the Catalog tool
- Expand the sources menu

*Expected Result*

The menu is long as the source field (see QA for example)
![Image](https://github.com/user-attachments/assets/c79d20b0-5897-4fee-b2fa-34c28d62a827)

*Current Result*

The menu is smaller 

![Image](https://github.com/user-attachments/assets/0a3198c4-57f2-410a-8935-b7e17b9cf204)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by mahmoudadel54** [comment]
@tdipisa @MV88 

I have tried to reproduced this issue locally on MS and it doesn't show this bug at all
when I have investigated on DEV I found an override style from an added extension called **cadastrapp** 

![Image](https://github.com/user-attachments/assets/16a39044-a4bb-45c4-934b-f9cbd1cc85de)

So the issue in not from MS code

**Comment by tdipisa** [comment]
Thank you for investigating that @mahmoudadel54 that's all for now, passing to @dsuren1
