### ISSUE TITLE
Logout handled incorrectly on user manager

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#1075]
- Log in as an admin
- Go to user manager
- Logout 

--> I still see all users

If I reload what we see below happens. We should do better.

![3](https://cloud.githubusercontent.com/assets/693880/19084654/b5bb123e-8a67-11e6-93e4-d5c8021cdaab.jpg)

**Comment by offtherailz** [comment]
A redirect plugin have been developed for this purpose, have to be extended a little bit to be used in the general mapstore 2 case

**Comment by offtherailz** [comment]
I integrated it and it is works as it is for the purposes of this issue, redirecting to the home page : 
![logout](https://cloud.githubusercontent.com/assets/1279510/19109715/d909d150-8af6-11e6-99e0-edc6a83f8997.gif)

Should I proceed to do a pull request for it?
