### ISSUE TITLE
Add link on the homepage to MapStore 2 linkedin group

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#1082]
https://www.linkedin.com/groups/7444734/profile

**Comment by saidaipparla** [comment]
linkedin group button mockup preview
![group1](https://cloud.githubusercontent.com/assets/22316694/19855993/ca619878-9f77-11e6-9c01-a7c1b85bda20.png)
![linkedin](https://cloud.githubusercontent.com/assets/22316694/19856001/d794175a-9f77-11e6-978b-02f1bb803efa.png)

**Comment by Gnafu** [comment]
This is also an helpfull tool to create linkedIn references: https://developer.linkedin.com/plugins/company-profile

**Comment by offtherailz** [comment]
is this still in dev?

**Comment by saidaipparla** [comment]
waiting for feedback from Simone about which we should use

**Comment by simboss** [comment]
Go ahead with your proposal.
