### ISSUE TITLE
Permission editor do not render correctly

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#1088]
With some browser [Firefox ESR 45.2.0] The permission editor is shown like this:
![image](https://cloud.githubusercontent.com/assets/1279510/19146763/41c500ac-8bb5-11e6-97ee-8b66f1e6538e.png)

This is caused by the use of `flex` display on the table. Removing all flex settings it looks like this anyway. 
![image](https://cloud.githubusercontent.com/assets/1279510/19146786/66b2bf62-8bb5-11e6-8ada-055456cfe9f0.png)

There was some reason why flex was used? Otherwise we should remove the `flex` options to make it compatible.

**Comment by offtherailz** [comment]
@Gnafu did you remember any reason to set the style this way?

**Comment by Gnafu** [comment]
With the old layout the flex was needed to display the menu items with the same width of the field.
Since the tools has been refactored you can remove it.

**Comment by offtherailz** [comment]
cool, going to do a pull request with my changes.
