### ISSUE TITLE
UserManager home button is beside the GeoSolutions logo

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#1089]
@offtherailz Is it done on purpose or is it a bug?

![2016-10-06 11_08_52-](https://cloud.githubusercontent.com/assets/11991428/19147058/9b47488c-8bb6-11e6-9a45-0341815a8d35.png)

**Comment by offtherailz** [comment]
It is a implementation. In the mock-up it was not present, but it was needed for allow the user to come back to home. 

Let's discuss, anyway I'll change the labels of this properly.

**Comment by mbarto** [comment]
In my opinion should go on the right, to be consistent with the other pages

**Comment by mbarto** [comment]
The Home Button moved also in the Map page (now it's after the Login, it should be the first button).
