### ISSUE TITLE
Define coding guidelines

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#11]
Some examples:

* [OpenLayers 3](https://github.com/openlayers/ol3/blob/master/CONTRIBUTING.md#follow-openlayers-3s-coding-style)
* [airbnb](https://github.com/airbnb/javascript)
* [W3C](http://www.w3schools.com/js/js_conventions.asp)

**Comment by mbarto** [comment]
Both eslint and editorconfig have been configured, and the CONTRIBUTING.md file compiled
