### ISSUE TITLE
Integrate vector querying for vector layers

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#1104]
Currently there is no support for querying vector layers in the MapStore product although we have widgets for doing all the bits.

Likewise MapStore 1 we need to be able to to query vector layers via WFS when available.

TASKS:
- [x] Remove useless code from existing codebase
- [x] Enable drawing on map for spatial filter
- [x]  Enable tool only for WMS vector layers (get the info from the map configuration, either saved from catalog or not)
- [x]  Complete results panel: see related issue #1320

**Comment by offtherailz** [comment]
Maybe I created this story that seems to be duplicated. https://github.com/geosolutions-it/MapStore2/issues/1121

Should I close it and port the discussion here?

**Comment by mbarto** [comment]
I would say yes.

Il 11/ott/2016 12:40, "Lorenzo Natali" <notifications@github.com> ha
scritto:

**Comment by offtherailz** [comment]
Porting the duplicated US details here : 

We should so integrate the current query panel and the feature grid to create an advanced search tool for the layers that covers the functinalities available in the old QueryPanel + FeatureManager + FeatureGrid available in MapStore (1).

Estimated tasks and decisions: 
- [ ] Provide a way to select the layer to query (e.g. a button in the TOC, context-menu). This should open the panel. This should be a panel like the toc (maybe from the opposite side) or inside it. 
- [ ] Add support to retrieve attributes and types from DescribeLayer ( current tool is configured statically). 
- [ ] Support numeric attribute validation
- [ ] The search action should switch the same panel to the table of results, and provide a button to back to search.

Advanced features:
- [ ] retrieve existing values from WPS, with pagination (requires changes in the widget library used, see `react-select` and `react-select-virtualized`

**Comment by Gnafu** [comment]
Here is a mockup of how it will look like:

![qp1](https://cloud.githubusercontent.com/assets/3932165/19928496/f39a93ec-a0fe-11e6-9d0e-f4c74a37d968.png)
![qp2](https://cloud.githubusercontent.com/assets/3932165/19928494/f3988c64-a0fe-11e6-833e-26c78b9041ae.png)
![qp3](https://cloud.githubusercontent.com/assets/3932165/19928495/f39a50c6-a0fe-11e6-9855-e0fd1baa1cc8.png)

**Comment by mbarto** [comment]
Let's put pagination into account...

**Comment by simboss** [comment]
We are missing the export of features as well as the ability to zoom to a single row on the map.
We need to have the same functionalities that we had on MapStore 1, the layour can be completely different though.

**Comment by Gnafu** [comment]
The following is designed for desktop users (mobile will have a separate user story), it has:
- Button to zoom to single feature
- Column sorting
- Pagination (should we also consider the infinite loading?)
- Highlight results on map
- Export (the server should be queried for supported formats)
-- "Current page export" and "All pages export" options should also be available/configurable

![results](https://cloud.githubusercontent.com/assets/3932165/19931929/86523bf4-a10e-11e6-998d-7da15694b2e2.png)

**Comment by simboss** [comment]
+1 on infinite loading, although I would expect something that allows me to jump to end and when I reach the end to jump to front.

Not sure this is feasible according to all WFS versions and paging. The same applies for the # of pages you are showing there.

**Comment by Gnafu** [comment]
Real pagination can be done only if the server supports it:
- it responds with the "totalFeatures"
- it supports "startIndex" and "count" parameters

It the server doesn't, the pagination will be "fake", loading a reasonable amount of results and browsing them without server interaction. ("reasonable" to be defined)
