### ISSUE TITLE
Investigate on how to make tile size customizable

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#1105]
Right now the tile size in pixels is fixed to 256*256.

On the desktop it would be great to go to 512*512 for large screens while on small screens we might want to go to a smaller size 128*128 or even 64*64.

This would need to be configurable somehow and possibly at runtime but not strictly.

**Comment by mbarto** [comment]
Closed by https://github.com/geosolutions-it/MapStore2/pull/1120
