### ISSUE TITLE
Allow search tool to query multiple services

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#1122]
As a MapStore 2 user, I want to use the search bar to find data from different services (not only GeoCoder).

Search bar should allow to query different services ( GeoCoding services, WFS, custom services...) , configured accordingly.
- [ ] A tool should show and allow to enable/disable the search services. 
- [ ] Each service should be customizable in output (with JSXTemplates). By default a click on a search result zooms and place a marker on the map, but we can add custon behiviour for JSXTemplate (e.g. more info...)

**Comment by tdipisa** [comment]
closed for inactivity.
