### ISSUE TITLE
Possibility to have different branded mapstores

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#1124]
As a manager of services provided to many companies, I want to be able to allow our companies to have their customized version of MapStore2. 

The home page could be different, headers, brand, footers, style, tools. Even the maps linked should be configured properly (e.g. the print configuration is different for each company, and even the tools scan be different for the default viewer).

**Comment by mbarto** [comment]
You should be able to do almost everything you mention loading different localConfig.json and maybe css. See if this can help

**Comment by tdipisa** [comment]
closed for inactivity.
