### ISSUE TITLE
GetFeatureInfo should be configurable

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#1125]
As an MapStore 2 maps manager, I'd like to have the possibility to customize feature info result with advanced tools to display related data.
I should be able at least to link the feature information to a table of related features. 

Using a template i should be able to configure mapstore (via configuration, UI is a plus)  with buttons and links that allow to open a table of related features.

**Comment by mbarto** [comment]
We can already use a jsx template to show json format data. See if this can help

**Comment by tdipisa** [comment]
In latest version we have now a support to customize the GFI output configuring a basinc template. Closed for inactivity.
