### ISSUE TITLE
Improve new delete button on TOC's layer

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#1181]
There is two things really:

- [ ] The color of the X, it should not be red (which indicates an error condition) but it should be of the same color of the other components

- [ ] when I click on the X a messa appears asking me if I want to make this change. Let's say I have changed my mind, how can I make this message go away?

- [ ] the confirmation message messes up the layout of the buttons as shown below

![xx](https://cloud.githubusercontent.com/assets/693880/19534960/2be7053c-9646-11e6-9c18-d6a448a3ae4f.jpg)

**Comment by offtherailz** [comment]
We can use this component instead https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/maps/modals/ConfirmModal.jsx 
or at least a pophover as confirm window. http://react-bootstrap.github.io/components.html#popovers
