### ISSUE TITLE
Remove big dependencies or limit their usage to selected plugins

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#1202]
And be sure to put them in separate bundles with require.ensure
Currently we should try to remove / limit:
- ogc-schemas (4.21Mb)
- turf (1.95Mb)
- react-color (1.16Mb)

**Comment by offtherailz** [comment]
We can update react color to 2.4.0
**current (2.0.0)**
```
react-color: 743.53 KB (5.57%)
```
**latest(2.4.0)
```
react-color: 287.53 KB (2.21%)
```
Should be compatible with react 14 and 15. We have to try if it works.

**Comment by offtherailz** [comment]
Tried with both raster and vector styler, it works even better. I have a pending pull request about color picker improvement. Going to cite this issue in the next commit
