### ISSUE TITLE
Handle map permission and setting from map - Merge Save / Save As functionalities

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#1205]
Right now we need to go back to the map manager, find the map we want to manage and then make a modification. 

Too complex, we should consider a shortcut.

Some hints:
 - [ ] on Save you should show all metadata
 - [ ] Save as functionality should be integrated in the Save metadata window, adding a button (create a copy). the UI should suggest a name for it (duplicated names are not allowed). **note:** geostore provides support for resource name hints on duplication 
 - [ ] owner, last update date and last modification date should be visible in metadata window
 - [ ] (optional): admin should be able to change the map owner

**Comment by tdipisa** [comment]
Closed in favour of #4391 and #4392
