### ISSUE TITLE
MapStore2 does not correctly import layers from pyCSW (GeoNode CSW) CSW Service

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/MapStore2#1219]
Trying to add layers from GeoNode CSW catalog (based on PyCSW implementation by default)

e.g.: http://demo.geonode.org/catalogue/csw?outputschema=http%3A%2F%2Fwww.opengis.net%2Fcat%2Fcsw%2F2.0.2&service=CSW&version=2.0.2&request=GetCapabilities

The list of records seems to be parsed correctly (even though previews do not work and often pagination does not work correctly), but adding a Layer seems to be broken somehow. The generated WMS request does not contain LAYERS query param at all or a "null" workspace is assigned to the layer.

**Comment by mbarto** [comment]
Most (all in the given service) of the layers do not have enough information to be added to a map.
I will fix a couple of bugs:
 * do not allow adding to a map if info is missing (e.g. layer name)
 * allow for some empty tags that are breaking pagination

**Comment by afabiani** [comment]
Issued to GeoNode and created a PR

https://github.com/GeoNode/geonode/pull/2721

**Comment by simboss** [comment]
See my analysis on the GeoNode associated issue [here](https://github.com/GeoNode/geonode/issues/2720).

We need to make MapStore 2 more resilient to read GetRecords responses.

**Comment by kappu72** [comment]
Give a look to decat code

**Comment by tdipisa** [comment]
@afabiani @simboss @kappu72 Can we close this?

**Comment by tdipisa** [comment]
closed for inactivity
