### ISSUE TITLE
Google background doesn't rotate with the map

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#122]
On mobile devices you can rotate the map using 2 finger rotation. Anyway Google Backgrounds doesn't rotate with the other backgrounds (Bing, openlayers and wms layers rotate correctly). We should disable this feature with Google backgrounds or fix this behaviour.

**Comment by mbarto** [comment]
Is this for OpenLayers3, Leaflet or both?

**Comment by offtherailz** [comment]
OpenLayers 3 only. Leaflet doesn't rotate.

**Comment by mbarto** [comment]
It depends on the way google background is implemented with OpenLayers3.
I don't know if we can do something using css rotate on the gmaps div and make it synchronous to openlayers rotation
