### ISSUE TITLE
Tool for converting MapStore1 maps to enable MapStore2 functionalities

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#1230]
Some functionalities in MapStore1 were dependent on the WMS GetCapabilities (e.g. queryable, zoom to layer, etc.). We should create a tool to:
- read MapStore1 maps
- issue a GetCapabilities on each WMS source
- update WMS layers info from capabilities to fill missing info
- save the new map

**Comment by tdipisa** [comment]
See also what reported in #1662 

> We should provide a tool that allows to update all the layers on the map.
> The "Refresh layers" tool will call the proper services (only for WMS layers now) to guess the missing information.

So the save functionality of the updated map should be optional.

**Comment by mbarto** [comment]
![image](https://user-images.githubusercontent.com/2770528/27171960-b12f37f4-51b3-11e7-87af-174b727f5382.png)

**Comment by mbarto** [comment]
![image](https://user-images.githubusercontent.com/2770528/27172105-50b0d83c-51b4-11e7-915f-170ca069d06b.png)

**Comment by mbarto** [comment]
![image](https://user-images.githubusercontent.com/2770528/27172142-731f8486-51b4-11e7-931c-d7f6ed1179ff.png)

**Comment by mbarto** [comment]
![image](https://user-images.githubusercontent.com/2770528/27172164-85baa742-51b4-11e7-84c0-e50d13265474.png)

**Comment by mbarto** [comment]
![image](https://user-images.githubusercontent.com/2770528/27323598-5b6ae51e-55a2-11e7-800c-63a7136b22f2.png)
Also on a layer by layer basis
