### ISSUE TITLE
Style selection widget can be confusing with many styles

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#1247]
People tend to copy styles without changing the title and right now that is what we show in the drop down, see image below, and results in duplicated names which is a confusing situation. We should mak good use of the style <name> as well which should not be duplicated (at least not withing workspaces boundaries).

In addition I do not understand why we are showing 4 styles for this layers while we have only 3. Default Styles means we don't specify and let the server decide?

One last thing, in the style section of WMS there is links to the Legend, we might want to allow people to check the legend while choosing a style? Maybe too much for this ticket.....

![styles](https://cloud.githubusercontent.com/assets/693880/20017761/48aeaa0e-a2c5-11e6-8e5b-8c5d24beed72.png)

**Comment by offtherailz** [comment]
We could  follow what we did with the catalog, placing the ID below the title in the list of styles, like this:
![image](https://cloud.githubusercontent.com/assets/1279510/20051873/898500a6-a4d1-11e6-9c74-a3443a32750f.png)

What do you think?

**Comment by simboss** [comment]
That could work.

Make a few tests with workspace specific styles as well.

**Comment by offtherailz** [comment]
In workspace specific styles, the service returns `workspace:layername`. Seems good to me.
