### ISSUE TITLE
Introduce support for Map Annotations

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#1251]
We are talking about the possibility to create annotations on the map that would be made of:

1. a geometry (point, polygon, line)
2. label (optional)
3. title
4. free text or even better HTML with an editor
5. a zoom interval od validity (i.e. the zoom range within which we show the annotation)
6. Activation style (e.g. Hover VS Click), to decid how to show the pop up

We also need the ability to 

- style the geometry
- style the pop-up (OPTIONAL)
- choose an icon (OPTIONAL)
- export and re-import 
- share along with the map
- print along with the map
- search them using title and labes (OPTIONAL)

Ideally (future cycles of development), it should also be possible to persiste them and therefore have control over:

- visibility (private, public, mixed visibility)
- modification permission
- history

**Comment by mbarto** [comment]
Partially done, should we leave this open as a reminder for missing functionality?

**Comment by tdipisa** [comment]
Annotations have been provided in [2019.02.00](https://github.com/geosolutions-it/MapStore2/releases/tag/v2019.02.00)
