### ISSUE TITLE
Document existing plugins using docma

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#1300]
We should document the existing plugins, for each of them:
 * available configuration properties, with explanation of usage
 * available containers (Toolbar, DrawerMenu, etc.) and related configuration options
 * styles / css
 * examples of usage

This should be done using proper JSDOC syntax (see http://usejsdoc.org/howto-commonjs-modules.html)
 * [ ] BackgroundSwitcher (https://github.com/geosolutions-it/MapStore2/blob/master/web/client/plugins/BackgroundSwitcher.jsx)
 * [ ] Identify (https://github.com/geosolutions-it/MapStore2/blob/master/web/client/plugins/Identify.jsx)
 * [ ] Map (https://github.com/geosolutions-it/MapStore2/blob/master/web/client/plugins/Map.jsx)

**Comment by offtherailz** [comment]
We should follow a structure like this for the jsdoc + some pages that describe how to build, create application etc...

![image](https://cloud.githubusercontent.com/assets/1279510/21267939/de56bd00-c3ac-11e6-8400-cd4382d46bd6.png)
@mbarto comments?

**Comment by simboss** [comment]
What do we do?
