### ISSUE TITLE
Investigate the use of react-docgen

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#1301]
https://github.com/reactjs/react-docgen

As part of https://github.com/geosolutions-it/MapStore2/issues/1300

To generate documentation (at least parttially) from code

**Comment by offtherailz** [comment]
I whould give a  try with this. 
https://github.com/lipp/doclets

**Comment by offtherailz** [comment]
This react app was documented using that https://doclets.io/tf/pageflow-react/add-to-doclets
