### ISSUE TITLE
Display the current MS2 version in the UI

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#1302]
Users have no way to tell what version of MapStore2 they are using.
Having a version displayed somewhere in the UI (even if hidden under menus, windows, tabs, or anything) is usefull when reporting a bug.

**Comment by offtherailz** [comment]
See this as an example: 
https://github.com/redux-observable/redux-observable/blob/master/scripts/preprepublish.sh

**Comment by mbarto** [comment]
![image](https://cloud.githubusercontent.com/assets/2770528/25960385/137b84e2-3677-11e7-8af8-9cdc26d3c540.png)

**Comment by Gnafu** [comment]
I'll keep just "Version"

**Comment by mbarto** [comment]
Should work like this:
 - you can specify a parameter to maven with the version: (e.g. -Dmapstore2.version=2017.00.04)
 - you can also give a parameter to build.sh (e.g. build.sh 2017.00.04
 - we can add a BUILD param to jenkins jobs so that this is passed to build.sh during the build
