### ISSUE TITLE
Reorganize UI of layer tools in the TOC

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#1318]
now we have something like this. 
![image](https://cloud.githubusercontent.com/assets/1279510/20842802/02d8e364-b8b9-11e6-9884-118368302173.png)

There are too many buttons on the same line. 
We should keep max a couple of them + one tool to display/hide the other ones. 

I suggest to keep only zoom and visibility toggle the list icon, that expand the legend and the other tools. 
When clicked, the other tools will be shown below the layer name, before the legend.

In my opinion this is very important for the next release, because we will have one more button in the TOC, and they become really too much.

**Comment by offtherailz** [comment]
I did it with following animation and icons.
@mbarto any comment?
![expand collapse](https://cloud.githubusercontent.com/assets/1279510/21098988/21ec75a8-c06c-11e6-8d1e-9445a00ca2bf.gif)

**Comment by mbarto** [comment]
Looks good to me

**Comment by offtherailz** [comment]
What about this light line on the left, to better identify that the block refers to the layer above?
![image](https://cloud.githubusercontent.com/assets/1279510/21102592/19d3485c-c07f-11e6-9e91-95c1fafefd85.png)

**Comment by mbarto** [comment]
Not bad
