### ISSUE TITLE
Groups cannot be created if the entered description is too long

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#1326]
In group manager, if the users inputs a long description the save can fail, so the error message appears:  

> "There was an error saving this groupInternal Server Error"

Is there a way to display the user the reason of the failure (description too long) ?

**Comment by offtherailz** [comment]
This is due to this https://github.com/geosolutions-it/geostore/blob/master/doc/sql/002_create_schema_postgres.sql#L90 
The limit can be set at client level, denying the user to digit more than 255 chars.

**Comment by MV88** [comment]
Should i set the limit also for the name of the group? (i.e. 255 for both)

**Comment by Gnafu** [comment]
I vote for it.
Make it configurable and set to the GeoStore's default value by default.
