### ISSUE TITLE
Dead Links in Developing-with-MapStore-2.md

### ISSUE THREAD

**Issue by geomC** [geosolutions-it/MapStore2#1400]
The links at the end of the file lead to a 404 page.

Since I am quite new to OpenSource-Development: 
If raising such an Issue about the projects documentation should be done differently, please let me know.

**Comment by offtherailz** [comment]
This developer-guide in the docs folder was an experimental export of the wiki, and will be most probably removed soon. Please refer to the wiki for the most recent and working developer guide.

**Comment by zachsa** [comment]
All the links on https://geosolutions-it.github.io/MapStore2/developer-guide/developing-with-mapstore-2-intro are still broken...
