### ISSUE TITLE
How to replace/insert the DefaultViewer using the plugin architecture?

### ISSUE THREAD

**Issue by alturium** [geosolutions-it/MapStore2#1410]
Hi,
What is the best to use a different and custom Feature Info panel for the Identify plugin, which defaults to the DefaultViewer?  There is a property for 'viewer' for Identify but I can't figure out how to best insert my viewer into the state with the current plugin architecture.  

One obvious solution is to insert via a custom action/reducer to change the viewer.  But when would be the best time to call this action in the setup sequences?  Another solution is to create my own Identify plugin, but with the 'viewer' prop it looks like it has designed for to be extended.  Plus, I don't want to maintain my own Identify, since there are 35 props being sent to it.

Part of my confusion is the plugin architecture and figuring out how it works.

Thanks ahead of time!

**Comment by mbarto** [comment]
Hi,
it's pretty simple:
 * develop your own viewer as a jsx component (e.g. MyViewer.jsx)
 * add a viewer property to localConfig.json, in the Identify plugin cfg section: "viewer": "{context.MyViewer}"
 * add your component in the require section of plugins.js: MyViewer: require('&lt;path to your component&gt;/MyViewer')

You are done.

**Comment by alturium** [comment]
I'm still having an issue with the viewer prop is not set.

I've added "viewer": "{context.CustomViewer}" but when evaluated in PluginUtils.js parseExpression() is undefined.

My CustomViewerPlugin.js is being loaded (also added it to localConfig.json).

Here is the localConfig.json ( I copied the "Identify" section from another example ):

```
{
    "proxyUrl": "/mapstore/proxy/?url=",
    "geoStoreUrl": "/mapstore/rest/geostore",
    "printUrl": "http://demo.geo-solutions.it/geoserver/pdf/info.json",
    "bingApiKey": "AhuXBu7ipR1gNbBfXhtUAyCZ6rkC5PkWpxs2MnMRZ1ZupxQfivjLCch22ozKSCAn",
    "translationsPath": "./MapStore2/web/client/translations",
    "plugins": {
        "desktop": [
            "Map",
            "Toolbar",
            "MousePosition",
            "ScaleBox",
            "BackgroundSwitcher",
            "TOC",
            "CustomViewer",
            {
                "name": "Identify",
                "cfg": {
                    "panelClassName": "modal-dialog info-panel modal-content",
                    "headerClassName": "modal-header",
                    "bodyClassName": "modal-body info-wrap",
                    "asPanel": false,
                    "headerGlyph": "",
                    "glyph": "map-marker",
                    "className": "square-button",
                    "closeGlyph": "1-close",
                    "wrapRevGeocode": true,
                    "enableRevGeocode": true,
                    "viewer": "{context.CustomViewer}",
                    "viewerOptions": {
                        "container": "{context.ReactSwipe}",
                        "header": "{context.SwipeHeader}",
                        "headerOptions": {
                            "useButtons": true
                        },
                        "containerProps": {
                            "continuous": false
                        },
                        "collapsible": true
                    },
                    "excludeOptions": [
                        "links",
                        "allowedSRS",
                        "title",
                        "type",
                        "visibility",
                        "params",
                        "legend",
                        "statistics",
                        "columnDefs",
                        "advancedFilter",
                        "boundingBox",
                        "capabilities",
                        "describeCoverage",
                        "describeLayer",
                        "loading"
                    ]
                }
            }
        ]
    }
}
```

Thanks!

**Comment by alturium** [comment]
Also, how do you change the info_format or format for the buildRequests from 'text/plain' to another value?  There is an action changeMapInfoFormat(), but I'm going to guess that this can be configured.

I think I'm almost there with my little custom viewer.  Just need to get the 'viewer' prop working and change the map info format.

thanks again!

**Comment by mbarto** [comment]
Did you add add your component in the require section of plugins.js: CustomViewer: require('<path to your component>/CustomViewer')?

**Comment by mbarto** [comment]
The simplest way to change the default info format is changing appConfig.js, there is an example for mobile mode, you can do the same for the defaultState:

mapInfo: {infoFormat: 'text/html'}

**Comment by alturium** [comment]
Hi mbarto,
Sorry for the late response, but got it working!

- plugin issue solved:  i used the plugin (connect version) class when all I needed was a straight up react class.  In other words, used the plugin component class vice react class (for my {context.CustomViewer} vice how Identify.jsx is created and used.

- was able to change the infoFormat to 'application/json' but now I have the problem that the feature info will be different per layer.  I will post this as different issue.

thanks for you help!

**Comment by MV88** [comment]
Hi @alturium you can send an email to the [developers mailing list ](https://github.com/geosolutions-it/MapStore2#communication) 

Regards,
Matteo

**Comment by alturium** [comment]
Hi Matteo, 

in regards to ?  i'm not sure which issue or what you have in mind.

-Michael

**Comment by MV88** [comment]
Hi Michael, I thought you could send an email to the mailing list describing your problem and then we (the Geosolutions team) would open a issue if needed or giving you an answer on the ML. So every user can access it.
