### ISSUE TITLE
Importing a shapefile doesn't work if Winrar 5.31 is installed

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#1430]
Recently I've installed WinRar (5.31 in my case) and I've associated it to also .ZIP files.
When I tried to drop a file into the shapefile's dropzone it was happening nothing, NO feedback with warnings or errors.  (i've fixed this feedback problem in the next pr i'm going to make)
After a quick investigation I noticed that the type of the file dropped was set to empty string "". 

Tested with: chrome, firefox, ie11
OS : Windows 10 Home
How to solve: Uninstall winrar

This should be investigated more to understand why WinRar changes the file or the information of the file when this is dropped into the shapefile's dropzone.

**Comment by tdipisa** [comment]
fixed with #2368
