### ISSUE TITLE
Attribution bad sized and placement

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#1433]
Well visible with NASAGIBS background.

![image](https://cloud.githubusercontent.com/assets/1279510/22795288/7004732c-eef6-11e6-9a6e-567aed02a92c.png)

**Comment by offtherailz** [comment]
This should be fixed with latest changes to the footer. Please test

**Comment by Gnafu** [comment]
Google attribution does not shows up

**Comment by mbarto** [comment]
Will be fixed by https://github.com/geosolutions-it/MapStore2/pull/2141
