### ISSUE TITLE
Wrong characters in layer name

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#1435]
Some saved maps have wrong characters.
See the picture, on the left there is the standalone package, on the right the QA deploy.
Both are 2017.01.00 
![2017-02-10_1503](https://cloud.githubusercontent.com/assets/3932165/22829421/ddcaa2da-efa2-11e6-956a-162b5948eef6.png)

Can this be a GeoStore issue?

**Comment by Gnafu** [comment]
It is a GeoStore issue, reproduced with MapStore1.

**Comment by simboss** [comment]
What's the status?

**Comment by Gnafu** [comment]
This was introduced by the old geostore resources manager, not handling the encoding.
The map is fixed now.

**Comment by mbarto** [comment]
There are still issues with maps saved with the Save trool
