### ISSUE TITLE
Create Locate Me Widget

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#144]
We need to create a widget that shows the current position when activated for both OL3 and LeafLetJS.

When the widget is activate it should change its appearance. The appearanche should clearly higlight when the position is not available VS when the position is not available.

I would like to see on the map the accuracy of the position available.

Examples:
* http://openlayers.org/en/v3.2.1/examples/geolocation.html
* http://openlayers.org/en/v3.2.1/examples/geolocation-orientation.html
* https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-locatecontrol/
* https://github.com/domoritz/leaflet-locatecontrol
* https://www.mapbox.com/mapbox.js/example/v1.0.0/geolocation/

**Comment by offtherailz** [comment]
This is a Leaflet style mockup. Openlayers should be similar.
![mapstore 2 viewer](https://cloud.githubusercontent.com/assets/1279510/10424651/2d07cf14-70d1-11e5-9d52-a95b6334dc2f.png)
Waiting for comments.

**Comment by mbarto** [comment]
Looks good to me.
