### ISSUE TITLE
Unclear how to add WFS layer to config

### ISSUE THREAD

**Issue by geomC** [geosolutions-it/MapStore2#1444]
I want to add a WFS service to a project created with `createdProject.js.`
Adding WMS-services to config.json works like a charm, but I can't figure out how to add a WFS.
Since there is not a lot of documentation, I took a look at the examples in `web/client/examples.`

In `examples/styler/config.json`, a couple of layer objects have a value "WFS" under the property `describeLayer.owsType`, while the properties `type,` `url` and `format` are used to describe a WFS.

```json{
  "map": {
    "center": {
      "x": 1250000.000000,
      "y": 5370000.000000,
      "crs": "EPSG:900913"
    },
    "layers": [
        // some WMS layers ..
        {
          "describeLayer": {
            "owsType": "WFS",
            "geometryType": "Point"
          },
          "format": "image/png",
          "group": "Vector",
          "name": "tiger:poi",
          "opacity": 1,
          "title": "NY PoI",
          "type": "wms",
          "url": "http://demo.geo-solutions.it/geoserver/wms",
          "visibility": true
        },
    ]
  }
}
```

**How can I add a WFS layer to the config file that is queried and displayed in the map?**
It would be handy just to state `"type":"wfs"` and the url, but that does not work.

BTW: First of all thanks guys, great project. I am currenty trying to dig into the code and I am not very experienced with web dev.

**Comment by simboss** [comment]
This is a question for the [developers mailing list](https://github.com/geosolutions-it/MapStore2#communication) not an issue.

I am going to close this one, please report this on the ML.
