### ISSUE TITLE
Random test failures with after recent updates

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#1447]
Notified some failures (noticed both on Firefox 51 and Firefox 31) 

![image_from_skype](https://cloud.githubusercontent.com/assets/1279510/22889741/7eab92f4-f20a-11e6-816b-9266505b35c1.png)

**Comment by allyoucanmap** [comment]
I reproduced the problem and it's not a mapstore2 bug.
I did several test and when I minimize the firefox browser window of the travis test while it's running, the function 'moveend' of openlayers doesn't start so the done() callback exceeds the timeout limit and travis throws the error.

**Comment by offtherailz** [comment]
Ok, so it is not an issue, going to close
