### ISSUE TITLE
Dynamically or configuring infoFormat for buildRequest (action) for different layers

### ISSUE THREAD

**Issue by alturium** [geosolutions-it/MapStore2#1449]
Hi,

How to configure a layer to define what a buildRequest (action prop, see Identify.jsx) to use a different info format?

From a previous comment, it is possible to change the default:

> The simplest way to change the default info format is changing appConfig.js, there is an example for mobile mode, you can do the same for the defaultState:
> 
> mapInfo: {infoFormat: 'text/html'}

How can I set it up to be 'text/html' for one layer and 'application/json' for another layer?

One possible solution would be to add a property to the 'layers' in config.json such as 'info_format'.

thanks

**Comment by mbarto** [comment]
Please, use the mailing list for questions
