### ISSUE TITLE
Measure panel in Drawer is not translated (immediately) when switching language

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#1460]
It happened to other components in the past. It's updated on the next action.

**Comment by MV88** [comment]
We need to fix also the fact that the tooltip is hidden from dialogs.
![image](https://cloud.githubusercontent.com/assets/11991428/22973288/6352de12-f37d-11e6-97e9-a02adb958768.png)

**Comment by MV88** [comment]
I also noticed that the measure tool remains opened when i change map. We should reset also the measure tool.
