### ISSUE TITLE
Measure window is not closed on map change

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#1464]
To reproduce:

- open a map
- open a measure tool
- click on home
- open a different map

The measure results window is visible on the map but no tool is active.

**Comment by MV88** [comment]
yes I noticed this, see https://github.com/geosolutions-it/MapStore2/issues/1460
i'm wondering if i can fix this small problem as long as i fix the other one in one single PR

**Comment by Gnafu** [comment]
Closed by #1466
