### ISSUE TITLE
Review the query panel layout

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#1468]
The query panel should be refactored in terms of style and usability.

**Comment by allyoucanmap** [comment]
here some possible changes

initial state

- before
![03b](https://cloud.githubusercontent.com/assets/19175505/22986717/b58f2a62-f3ac-11e6-814e-ed1e9dc47bc5.png)

- after
![00](https://cloud.githubusercontent.com/assets/19175505/22985111/c292ac3e-f3a7-11e6-8c36-e2adef9e62f1.png)

-----------------
with add condition

- before
![02b](https://cloud.githubusercontent.com/assets/19175505/22986658/90e5649c-f3ac-11e6-90b7-e96677fcb70e.png)

- after
![01](https://cloud.githubusercontent.com/assets/19175505/22985115/c4885688-f3a7-11e6-8d5c-e8adf5fbad80.png)

-----------------
with add group

- before
![01b](https://cloud.githubusercontent.com/assets/19175505/22986512/1a031c70-f3ac-11e6-8054-f7185b221314.png)

- after
![02](https://cloud.githubusercontent.com/assets/19175505/22985118/c5f305a4-f3a7-11e6-90a0-ecac8da2032c.png)

gif

- after
![03](https://cloud.githubusercontent.com/assets/19175505/22985123/ce4f9910-f3a7-11e6-969a-63eab02bb266.gif)

**Comment by simboss** [comment]
search e reset ora sono in alto...

**Comment by allyoucanmap** [comment]
this should be with search & reset in the right position:

initial state

- before
![00d](https://cloud.githubusercontent.com/assets/19175505/23013229/0ff8f0d2-f42a-11e6-85ab-98d567df1d24.png)

- after
![00c](https://cloud.githubusercontent.com/assets/19175505/23012850/7345a0ec-f428-11e6-8941-3e3aa5919066.png)

---

with add condition

- before
![01d](https://cloud.githubusercontent.com/assets/19175505/23013234/138a711c-f42a-11e6-9697-bbb012f2ceca.png)

- after
![01c](https://cloud.githubusercontent.com/assets/19175505/23012851/759fbe36-f428-11e6-9ca2-e7dde1be8620.png)

---

with add group

- before
![02d](https://cloud.githubusercontent.com/assets/19175505/23013239/1852a124-f42a-11e6-9b94-81f1bf3cebc0.png)

- after
![02c](https://cloud.githubusercontent.com/assets/19175505/23012852/772b9cb6-f428-11e6-8e3b-b795f850a924.png)

**Comment by allyoucanmap** [comment]
we could integrate the query builder header with the back button

![move](https://cloud.githubusercontent.com/assets/19175505/23014379/0718e45e-f42f-11e6-9bcc-33005f696f43.png)

**Comment by offtherailz** [comment]
I should use shadows instead of borders to highlight nested filters. Like this: 
https://codepen.io/sdthornton/pen/wBZdXq

**Comment by allyoucanmap** [comment]
I just tried it and box-shadow works better than borders,
it's cleaner than before

![sha](https://cloud.githubusercontent.com/assets/19175505/23015545/87ea6dce-f433-11e6-8b3e-1df4d0107a2e.png)

**Comment by allyoucanmap** [comment]
here the scroll bar is only inside the body so the query builder header is static.
the reset & search buttons are always accessible in this situation

![scroll](https://cloud.githubusercontent.com/assets/19175505/23017431/871cd9a2-f43a-11e6-8b34-eae460c58cc4.gif)

**Comment by offtherailz** [comment]
many nested objects are still confusing. Maybe we can think about collapsing groups. 
Can you show a real example? (1 level of nesting is enough)

**Comment by allyoucanmap** [comment]
![nested](https://cloud.githubusercontent.com/assets/19175505/23020381/1e63e4c0-f447-11e6-9de6-36596e13b7b5.png)

**Comment by offtherailz** [comment]
Almost there, but it is not clear what is doing yet...
What if we use cards even for the 1 row condition? And complex conditions should be collapsible.

**Comment by allyoucanmap** [comment]
this is an update with card for every attribute filter group

![00](https://cloud.githubusercontent.com/assets/19175505/23060777/81c535a6-f4ff-11e6-8420-0473984d52dc.png)

![01](https://cloud.githubusercontent.com/assets/19175505/23060780/83229114-f4ff-11e6-883b-82dc94bb3567.png)

**Comment by simboss** [comment]
much better...

**Comment by allyoucanmap** [comment]
latest update
- added bbox/circle panel style

![6](https://cloud.githubusercontent.com/assets/19175505/23075414/add0b3cc-f53c-11e6-9d1b-90c1aef8d1ff.png)
![5](https://cloud.githubusercontent.com/assets/19175505/23075415/b00b61b4-f53c-11e6-86ce-288d2825e8c6.png)
![4](https://cloud.githubusercontent.com/assets/19175505/23075418/b128c94c-f53c-11e6-8b2a-436656ee189e.png)
![3](https://cloud.githubusercontent.com/assets/19175505/23075422/b2aae106-f53c-11e6-9b27-bc103c73baa3.png)
![2](https://cloud.githubusercontent.com/assets/19175505/23075424/b420be2a-f53c-11e6-8394-395164d95f9e.png)
![1](https://cloud.githubusercontent.com/assets/19175505/23075427/b574f714-f53c-11e6-8597-e36556caba17.png)
![0](https://cloud.githubusercontent.com/assets/19175505/23075429/b6747f40-f53c-11e6-8040-ad491bdc6dee.png)

**Comment by simboss** [comment]
I like it !
