### ISSUE TITLE
Investigate on react-docgen to create reference docs

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#1475]
[react-docgen](https://github.com/reactjs/react-docgen) is a library to create docs from react components in JSON format.

Other tools exist to create markdown from this JSON:
 * https://github.com/travelperk/react-docgen-markdown
 * https://github.com/IonicaBizau/json2md
 * https://github.com/thebuilder/react-docs-markdown
 * https://github.com/morlay/react-docgen-ui

We have to create a workflow to:
 * generate reference docs for our plugins (and components)
 * save them in MD format, in the docs/developer-guide/reference folder so that they become part of the github pages website
 * create an index of files for the docs/developer-guide/reference folder

Let's start documenting ONE plugin properly (e.g. MousePosition) and creating docs for it

**Comment by offtherailz** [comment]
We may check docma instead
