### ISSUE TITLE
Feature Info starts collapsed

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#1501]
![image](https://cloud.githubusercontent.com/assets/1279510/23297070/44cacb42-fa78-11e6-88fd-d0494ab7f606.png)

You have to browse to forward and back to expand.

**Comment by mricca** [comment]
If you replace the cfg for Identify plugin in localConfig.json everything works fine. But I don't think is the right fix.

**Comment by offtherailz** [comment]
It is probably a bug due to https://github.com/geosolutions-it/MapStore2/pull/1485
Can you post the config that fixes the problem? 
Placing the cfg inside the plugins' getDefaultProps do not solves the problem?

**Comment by mricca** [comment]
I simply restored the old cfg "Identify" configuration in web\client\localConfig.json. This configuration has been moved in getDefaultProps, but does not work.

"cfg": {
         "panelClassName": "modal-dialog info-panel modal-content",
         "headerClassName": "modal-header",
         "bodyClassName": "modal-body info-wrap",
         "asPanel": false,
         "headerGlyph": "",
         "glyph": "map-marker",
         "className": "square-button",
         "closeGlyph": "1-close",
         "wrapRevGeocode": false,
         "enableRevGeocode": true,
         "viewerOptions": {
          "container": "{context.ReactSwipe}",
          "header": "{context.SwipeHeader}",
          "headerOptions": {
            "useButtons": true
          },
          "containerProps": {
            "continuous": false
          },
          "collapsible": false
        }
       }
