### ISSUE TITLE
TOC should manage long layers name

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#1502]
on the left the actual situation - on the right a possible solutions
![image](https://cloud.githubusercontent.com/assets/11991428/23299428/d6e401ac-fa81-11e6-9b42-ef04422c1f15.png)

If you agree I can prepare a PR to fix this.

I also noticed that the name of the layer is not perfectly aligned with the icons
![image](https://cloud.githubusercontent.com/assets/11991428/23299612/7c0c7d58-fa82-11e6-9ea6-ec3a91e5b7e3.png)

**Comment by simboss** [comment]
Is this a bug?

I mean the name on the left seems properly truncated to me. I am not so sure that showing the entire name in the TOC will help when that name is too long since it will make the TOC huge difficult to use.

**Comment by MV88** [comment]
Yes, but can exist some cases when two or more layers start with the same text. Just wanted to highlight this situation.

**Comment by Gnafu** [comment]
Maybe we can expand the name when the "additional tools" icon is clicked

**Comment by simboss** [comment]
Good point @Gnafu.

The default view should be compact, that is my point.

**Comment by MV88** [comment]
Ok, let's move with the Gnafu's solution. 
Also limit the name to three rows when the "additional tools" is closed. 
When it is expanded we can show the entire name of the layer.

Let's wait the theme integration for the alignment of the group and the icons.
