### ISSUE TITLE
Localized components returns null in queryform and featuregrid examples

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#1504]
The problem should be in the connect function.
'state.locale.locale' becomes 'state.locale.current'  

```
module.exports = connect((state) => {
    return {
        locale: state.locale && state.locale.locale, 
        messages: state.locale && state.locale.messages || {}
    };
})(QueryForm);
```

**Comment by mbarto** [comment]
Yes. That's the issue. I have it fixed in a PR I am working on

Il 24/feb/2017 17:06, "stefano" <notifications@github.com> ha scritto:

**Comment by mbarto** [comment]
Fixed
