### ISSUE TITLE
Catalog can't be closed if dragged too much in top direction

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#1538]
To replicate:
- Open the catalog
- Drag the header in top direction having it hidden  

You can't drag again because the header is gone. That's because the only the header is draggable and there is no close button. 

Using the history of the browser is not enough, because user can't save the map or do any other operation other than open dev tools.

**Comment by tdipisa** [comment]
Now the catalog tool is fixed so we can close this issue
