### ISSUE TITLE
Measure controls

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#154]
Implements measuring controls: length, area, Bearing
Make them configurable to use different units of measure

**Comment by chrismayer** [comment]
Here is a UI mockup for the measurement tool:

![154-1](https://cloud.githubusercontent.com/assets/1185547/10312895/5274da86-6c4d-11e5-956d-5eb384b3867e.png)

What do you think? I haven't found any well matching glyphicons so far.

**Comment by chrismayer** [comment]
For technical implementation details: Will it be suitable to use the draw controls of Leaflet (https://github.com/leaflet/Leaflet.Draw) and ol3 (http://openlayers.org/en/v3.9.0/apidoc/ol.interaction.Draw.html) or isn't that an option?

**Comment by mbarto** [comment]
It's ok for me, both for the mockup and about using leaflet and ol3 tools.

**Comment by chrismayer** [comment]
How should the bearing function work exactly? Should this be a separate tool? Or should it be derived from the drawn sketch (either LineString or Polygon)?

**Comment by mbarto** [comment]
I would implement it as a different tool, have a look at the old MapStore (http://mapstore.geo-solutions.it/mapcomposer/viewer?locale=en&mapId=165) to see how it was working there.

**Comment by chrismayer** [comment]
Okay, agree for a new tool. Therefore I have to extend the UI:

![154-2](https://cloud.githubusercontent.com/assets/1185547/10536462/8bbcca2e-73eb-11e5-88cb-08f723d5d3eb.png)

Okay?

**Comment by mbarto** [comment]
Fine
