### ISSUE TITLE
Implement dynamic help system

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#155]
Help should be enabled by a toggle button.
When enabled, all the "help-augmented" components should be highlighted on the UI, so that the user can ask help on a specific UI part. When an highlighted part is selected, the related help should be shown to the user.
We need to define how to help-augment any component and how to recognize them.

**Comment by chrismayer** [comment]
Hi, I have a few questions about this issue:

The preferred layout:

Where do you want to have the toggle button to be placed? As part of the toolbar or as single element somewhere in the app? If second: Where should it be placed?
![155-2](https://cloud.githubusercontent.com/assets/1185547/10967065/37de96e4-83b8-11e5-99f3-51231d360f76.png)

![155-1](https://cloud.githubusercontent.com/assets/1185547/10967072/459da2ac-83b8-11e5-92d8-4533ba526f1e.png)

About the highlighting of the "help-augmented" elements: Either a CSS solution like a border around the elements? Or a separate element like a badge or something showing a help icon which can be clicked?

About the display of the help information: Is another panel rendering the help text OK?

**Comment by mbarto** [comment]
The position of the button as the last button of the toolbar is ok.
I would use a badge if possible to highlight elements with help.
Yes, there will be a new panel to display help text (I would accept HTML as we could include formatted text, images and so on).
