### ISSUE TITLE
Changes to create project script (repo name and project name)

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#1596]
We should add a <repoName> parameter to the createProject script. This allow to create a repository with a customized name: 
`
node ./createProject.js <repoName> <projectName> <projectVersion> <projectDescription> <gitRepositoryUrl> <outputFolder>
`

**Comment by MV88** [comment]
Actually the repo name is defined in the url and there is no need for the new parameter.
The documentation needs to be fixed removing the part "the repository name on github," inside the description of the projectName param.

**Comment by tdipisa** [comment]
closed for inactivity.
