### ISSUE TITLE
Add support to other tile services

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#163]
Evaluate the possibility and support some tile services:  
Some options are: 
* OpenSeaMap
* OpenTopoMap
* Thunderforest
* OpenMapSurfer
* Hydda
* MapBox
* Stamen
* Esri
* OpenWeatherMap
* HERE
* Acetate
* FreeMapSK
* MtbMap
* CartoDB
* HikeBike
* BasemapAT
* NASAGIBS
 
Evaluate alternatives not supported for OpenStreetMap. 
List derived from [this](https://github.com/leaflet-extras/leaflet-providers/blob/master/leaflet-providers.js).

**Comment by simboss** [comment]
Duplicated by #192

**Comment by mbarto** [comment]
It is not the same as #192, this is about adding more backgrounds on the default configuration, the other one is about adding more types of supported backgrounds

**Comment by kappu72** [comment]
These are all tile layers, we have to options:
1) Configure each layer in a new class lik OSMLayer.js  both for ol that for L
2) Create a new TileLayer.js class like WMSLayer.js both for ol and L that allow options configuration. So will be possible to  create above layers in config.json. This options needs more time

**Comment by mbarto** [comment]
I would go for option 2
