### ISSUE TITLE
Investigate the SearchBar error state

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#1637]
- [ ] When and error occurs the tooltip over the icon is empty
![2017-03-24 15_43_11-mapstore 2 homepage](https://cloud.githubusercontent.com/assets/11991428/24301036/b753b6d2-10ae-11e7-80ce-58f913237336.png)

- [ ] the text is not selectable

**Comment by offtherailz** [comment]
Can not reproduce. 
Probably a temp issue of nominatim services. If we don't have the error that produced the issue (no error message) we can not replicate it.
It correctly handles the errors by my side: 
![image](https://cloud.githubusercontent.com/assets/1279510/24355823/b8272828-12f7-11e7-83d9-039d1697631b.png)

 Let's close it.
