### ISSUE TITLE
Provide a tool to update the map layers

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#1662]
Actually all legacy maps from mapstore1 do not contain the bbox and the wfs URL (for vector layers, if any)  that are needed to show the "zoom to layer" and the "search" tool.

In addition, if the layers changes their settings (e.g. become not queriable, change bbox...) the only way to update them is to remove and add again them from the catalog. 

We should provide a tool that allows to update all the layers on the map.
The "Refresh layers" tool will call the proper services (only for WMS layers now) to guess the missing information.

**Comment by Gnafu** [comment]
Here is a couple of mockups on where I'll put the tool
![mock1](https://cloud.githubusercontent.com/assets/3932165/25812867/f94e51e6-3417-11e7-9dca-5401ed008798.png)
and its configuration
![mock2](https://cloud.githubusercontent.com/assets/3932165/25812868/f9522d7a-3417-11e7-93a6-d966777a611f.png)

I'd make the tool configurable by the localconfig.json and then give the option to the users to customize it via GUI.

The button will show up for everyone as the tool is not intended to persists the changes (it will be done by the existing "Save" tool)

**Comment by tdipisa** [comment]
Closed in favour of #1230
