### ISSUE TITLE
Change TOC Icon from Pen to Layers

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#1670]
Quick change, the icon we use for the TOC when it's collapsed does not make much sense:
![1](https://cloud.githubusercontent.com/assets/693880/24586474/1949a082-17a2-11e7-9dac-ceb021712fa6.jpg)

I would use the icon for the layers:
![2](https://cloud.githubusercontent.com/assets/693880/24586476/2287a5b8-17a2-11e7-855a-6e2621e85090.jpg)

**Comment by offtherailz** [comment]
Sorry, there was an issue about the UI review here: 
https://github.com/geosolutions-it/MapStore2/issues/1545

So we want the layer's icon, not the arrow?
