### ISSUE TITLE
BackgroundSwitcher review

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#1672]
Background switcher floating on the map, with the current background preview showing. When clicked the tool should display the alternative backgrounds. Should be perfect if it is somehow merged with the overview map.

**Comment by allyoucanmap** [comment]
![switcher](https://cloud.githubusercontent.com/assets/19175505/25347992/fd077174-291c-11e7-9919-4b00ee2b88d9.gif)

![00](https://cloud.githubusercontent.com/assets/19175505/25347976/f638dc2a-291c-11e7-9f3e-f72f6986c132.png)
![01](https://cloud.githubusercontent.com/assets/19175505/25347980/f7903e56-291c-11e7-8ad7-be2641c65b34.png)
![02](https://cloud.githubusercontent.com/assets/19175505/25347988/fa2de0be-291c-11e7-8ea8-35f48c0f5d15.png)

**Comment by simboss** [comment]
It would be nice to show somehow the name of the background in use.

[Geoadmin](https://map.geo.admin.ch/?lang=en&topic=ech&bgLayer=ch.swisstopo.swissimage&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&X=190000.00&Y=660000.00&zoom=1) does this very well IMHO.

**Comment by allyoucanmap** [comment]
sizes:
preview main button closed = 1.5 * standard button
preview main button open = 2 * standard button
preview button list open = 1.5 * standard button

![00](https://cloud.githubusercontent.com/assets/19175505/25945469/50d63df8-3647-11e7-80ec-5886849a80d4.png)
![01](https://cloud.githubusercontent.com/assets/19175505/25945470/52236eb0-3647-11e7-9bfc-53f29d35ec5d.png)
![02](https://cloud.githubusercontent.com/assets/19175505/25945472/5369541a-3647-11e7-9044-49709c046c60.png)

**Comment by allyoucanmap** [comment]
mobile
![00](https://cloud.githubusercontent.com/assets/19175505/25959838/52efcb80-3675-11e7-88a2-7d3aef3a5322.png)
![01](https://cloud.githubusercontent.com/assets/19175505/25959840/5489b64a-3675-11e7-85a4-69866c2b581b.png)
![02](https://cloud.githubusercontent.com/assets/19175505/25959841/559ab368-3675-11e7-8daf-27182d67becc.png)
![03](https://cloud.githubusercontent.com/assets/19175505/25959843/56fb8c5a-3675-11e7-9bf0-1979e2197423.png)
![04](https://cloud.githubusercontent.com/assets/19175505/25959844/5841d4a2-3675-11e7-9267-81f4f6fa68cd.png)
