### ISSUE TITLE
GetFeatureInfo and WMTS

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#1686]
FeatureInfo on [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/leaflet/1758?_k=zkqy5a) map does not do anything. 

Is that normal?

**Comment by mbarto** [comment]
That map has no queryable layer (Identify is not supported on WMTS layers), we could:
 * disable identify if no queryable layer is available
 * show a warning message that no layer can be queried (on click)

**Comment by mbarto** [comment]
We can also add support for Identify for WMTS, of course

**Comment by simboss** [comment]
I would do as follows:

- For the time being show a message rather not showing anything
- Open an issue for implementing this.

**Comment by mbarto** [comment]
Opened https://github.com/geosolutions-it/MapStore2/issues/1699
