### ISSUE TITLE
GetFeature does seem to not work anymore on Dev MapStore

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#1687]
I am trying on Dev to make queries using the query builder for WFS creating a query like STATE_NAME ilike %a% and I don't get anything back.

I checked the requests and there is two requests failing directly ad two that returns empty responses.

It is important to chet what is going on here, might depend on the recent changes on the query builder?

I would do also some manual testing.

**Comment by mbarto** [comment]
The wildcard to be used is *, not % for "every number of any char" and ? for any character (just one)

**Comment by offtherailz** [comment]
These are the options.
```
wildCard="*" singleChar="." escapeChar="!"
```
We could display them in some tooltip?

**Comment by simboss** [comment]
Thx Mauro, yeah, it would be great to have a suggestion for like and ilike.

@offtherailz can you open an issue for this?

**Comment by offtherailz** [comment]
sure, here it is https://github.com/geosolutions-it/MapStore2/issues/1691 
Going to close this one
