### ISSUE TITLE
Elevation slider

### ISSUE THREAD

**Issue by mricca** [geosolutions-it/MapStore2#1693]
Some layers will have elevation support (flag in layer configuration).
The list of supported elevations will be statically configured in the layer cfg.
The slider will change a parameter that will be sent in WMS requests.
The slider will be put in the layer properties panel (new tab).

**Comment by MV88** [comment]
closed by #1697

**Comment by mbarto** [comment]
Improvements in https://github.com/geosolutions-it/MapStore2/issues/1701
