### ISSUE TITLE
Create toolbar

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#171]
Create a toolbar (on the right side) to contain current (and future) controls (info, background switcher, layers. Review panels to be full screen on smartphones, windows on bigger screens.

**Comment by offtherailz** [comment]
Mockup 
![toolbar](https://cloud.githubusercontent.com/assets/1279510/10171961/fbe0b778-66dc-11e5-9fa9-ce9d443a43c5.png)
