### ISSUE TITLE
Support for linking a map directory to a 3rd level domain

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#1715]
MapStore should provide the functionalities to allow sharing maps with a direct URL. 
This is useful when MapStore's map manager is used as back office software, and the final products are the maps, exposed one by one with a single URL. 

So the map should be published without any acknowledge of the full infrastructure. This can be realized using the JSAPI or a custom bundle to build in a separate way (see share version with JSAPI). 
Still to have to define what functionalities should MapStore provide to fulfill this requirement.

**Comment by tdipisa** [comment]
closed for inactivity.
