### ISSUE TITLE
GetFeatureInfo should really use a spinner for slow servers

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#172]
If I load a slow layer and then I do a GetFeatureInfo (which might be slower than GetMap) it looks like nothing happens and people keep clicking.

We need to show some visual feedback and have a glass pane (with a timeout) to block people from keep on clicking.

**Comment by kappu72** [comment]
I propose to open modal window on click event, adding a big spinner in the middle. when the component receives the first response, the spinner is moved on a side. When all responses have been received, the spinner disappears.
The spinner should show the number of missing response.
User should be able to close modal window, and missing response should be skipped.
