### ISSUE TITLE
Map Thumbnails do not refresh automatically on update

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#1760]
Go to the main page and change a thumbnail.
The new thumbnail is not visible until reload (vie page refresh or search)

**Comment by MV88** [comment]
Could not reproduce it.

**Comment by Gnafu** [comment]
User is not admin
Tested on dev with Chrome
![2017-05-09](https://cloud.githubusercontent.com/assets/3932165/25862396/309183fa-34e8-11e7-8268-8bfa5d2b6c29.gif)

The thumbnail briefly flashes as it was updated but then the old one is displayed.
In the video, to see the new thumbnail I trigger an empty search.

**Comment by MV88** [comment]
Ok, i've tried with an admin user, maybe that's the reason. I'll check this
