### ISSUE TITLE
Plugin configuration does not separate UI config from plugin config

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#1766]
When a plugin is configured, the "toolCfg" and "cfg" are merged into the <Tool> props by the ToolsContainer (unless tool.tool == true)

This means that the plugin configuration ends up in all the UI elements, therefore React launches lots of error for non-defined props

I suggest to:
1 - Use a more descriptive naming
2 - Separate the container configuration from the component configuration

**Comment by tdipisa** [comment]
This issue is out of date, closing
