### ISSUE TITLE
Query panel fails when selecting a boolean attribute

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#1775]
![image](https://cloud.githubusercontent.com/assets/1279510/25533474/0595f204-2c31-11e7-9800-8fa5fc6924a8.png)

Extract from DescribeFeatureType:
```
localType:"boolean",

name:"S5000",
nillable:true,
type:"xsd:boolean"
```

**Comment by tdipisa** [comment]
In addition the code must be properly improved to manage similar use cases and avoid this kind of error (i.e. excluding the unsupported attribute in the query form).
