### ISSUE TITLE
Move Measure Tools to the burger menu

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#1776]
Currently the measure tools are located in a panel within the TOC.

That placement is at least strange, we should move them somewhere else, ideally as a section with subsections in the burger menu.

This requires some thinking and some mockups prior to implementation.

**Comment by offtherailz** [comment]
![image](https://cloud.githubusercontent.com/assets/1279510/25796873/7da9ebae-33db-11e7-9ded-fead89582bd7.png)
![image](https://cloud.githubusercontent.com/assets/1279510/25796975/cac0ded4-33db-11e7-92f4-eb38439ada6a.png)
