### ISSUE TITLE
Improve 3D map support

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#1780]
We already introduce a 3D switcher. We should enhance the navigation tool to fit the 3D use case and disable tools that are not supported yet. 
Remove tools when 3D mode is enabled:
- [x] ScaleBox
- [x] Zoom In
- [x] Zoom Out
- [x] Print
- [x] Locate
- [x] Shapefile
- [x] Measure tool

Fixes/Improvements: 
 - [x] Attibution is not rendered as html

Tools to Add: 
 - [x] Navigation for cesium
 - [x] Hints for navigation

**Comment by MV88** [comment]
Remove tools when 3D mode is enabled:
- [ ] ScaleBox
- [ ] Print
- [ ] Locate
- [ ] Shapefile
