### ISSUE TITLE
Features not displayed correctly with Cesium

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#1782]
**PROBLEM:**
Some features with Unesco map are not displayed correctly.
![2017-05-03 17_05_58-mapstore 2 homepage](https://cloud.githubusercontent.com/assets/11991428/25667120/d79b5aba-3022-11e7-991a-73ce269cc09d.png)

**Comment by offtherailz** [comment]
I tried with some other map doesn't happen. I think it is the server that has some bug. It is a 19-Nov-2012 build of GeoServer, version 2.2

**Comment by offtherailz** [comment]
I replaced the layer with same data published on demo and it solved the problem. Most probably is due to old issues of WMS in the unesco server.
Going to close this issue
