### ISSUE TITLE
Review Catalog UI

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#1783]
A mockup for a minimal review [here](https://drive.google.com/file/d/0B9nuKyTvUeXcb0hpaUVnd0R0c0E/view)
In milestone 2017.06.00 we will consider a complete review.

**Comment by tdipisa** [comment]
A possible mockup for a minimal review [here](https://drive.google.com/file/d/0B9nuKyTvUeXcb0hpaUVnd0R0c0E/view)
In milestone 2017.06.00 we will consider a complete review.

**Comment by tdipisa** [comment]
Some additional points to do:

1. when the user needs to manually enter a new catalog's service to the default list the panel's content switch his mode, so the he can enter the new service:

**Comment by Gnafu** [comment]
The current panel height is too much for small screens (1366x768)
The pagination toolbar is unreachable.

I guess this will not be an issue after the redesign.

![cattura](https://user-images.githubusercontent.com/3932165/29484891-bed90220-84c8-11e7-87af-ecc6ab1cb90f.PNG)

**Comment by MV88** [comment]
@Gnafu yes, the catalog will be positioned as a side on the right and, vertically, it will cover all the space available.
It will be used a % for the width.

**Comment by MV88** [comment]
A few notes about this issue that will be implemented:
- [ ] Center pagination 
- [ ] Reduce size of the record items
- [ ] Autocomplete field for service list
- [ ] Icon change if there is a service selected, if so it is edit (pencil) if empty it is add (pencil with plus)
- [ ] In edit mode move down the type, and leve the url with full width

**Comment by MV88** [comment]
A goal of the catalog GUI review can be this:
![image](https://user-images.githubusercontent.com/11991428/29613194-2f9916be-8805-11e7-8916-b29e1f58761a.png)

**Comment by MV88** [comment]
@allyoucanmap @mbarto  Set showLabels to false in config and then the style is messed up.
https://github.com/geosolutions-it/MapStore2/blob/master/web/client/localConfig.json#L302

**Comment by Gnafu** [comment]
So the "final step" layout has been rejected in favor of a simple button color change ?

**Comment by Gnafu** [comment]
> the default list can be hosted in the plugin's configuration

Do we have an example?

**Comment by MV88** [comment]
https://github.com/geosolutions-it/MapStore2/blob/master/web/client/localConfig.json#L34-L69
