### ISSUE TITLE
Improve edit map MetadataModal error handling and feedbacks

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#1832]
There are some improvements todo:

- [ ] If some errors occurs show the error without closing the panel
- [ ] In MetadataModal reached from SaveAs, if no name is provided display a message 
- [ ] In MetadataModal reached from Home, It is actually possible to change the map name to an empty one. avoid this showing the message added for the previous point.

**Comment by tdipisa** [comment]
closed for inactivity.
