### ISSUE TITLE
Mouse position 

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#184]
EPSG:4326 wrong notation
![mouseposition](https://cloud.githubusercontent.com/assets/1279510/10198851/38782592-679e-11e5-8549-d224f00e128a.png)

As you can see we have degrees, minutes and seconds with decimals, so decimals have to be removed. Plus the coordinates doesn't change when passing the date change line.

**Comment by kappu72** [comment]
Sorry Mirco, I haven't seen that the issue was assigned to you. I have fixed, if you haven't already done I'll send you the related pull request
 Let me know

**Comment by mircobe87** [comment]
![mousep-](https://cloud.githubusercontent.com/assets/5262132/10216791/e0e751fc-682b-11e5-9adb-20fa1e1289c8.png)
negative values are shown for both min. and sec.
