### ISSUE TITLE
Review Homepage to make it more modern and informative

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#1842]
- [ ] more modern L&F
- [ ] automatic loading of new maps
- [ ] better footer (possibly as a plugin)
- [ ] background as a plugin (it could be an image, it could be a movie, let's talka bout it)
- [ ] introduce preferences for the style and mapping engine

**Comment by tdipisa** [comment]
The section of the examples should be reviewed too. In my opinion a grid with cards could be more readable.

**Comment by MV88** [comment]
Maybe with an accordion style

**Comment by MV88** [comment]
Note: if one configure to use only the theme selector, it's bad positioned
![image](https://user-images.githubusercontent.com/11991428/33326653-d55891aa-d455-11e7-8849-b8335452665c.png)

**Comment by allyoucanmap** [comment]
additional changes
- [ ] enable theme switcher in navbar
- [ ] enable map engine but in  navbar
- [ ] search integrated with banner (initialize search on focus)
- [ ] multiselect of map cards (remove, featured)

**Comment by tdipisa** [comment]
closed for inactivity, we can review the MS home in #4254
