### ISSUE TITLE
Provide a reset button to back to vertical position in 3D mode

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#1850]
Sometimes users, navigating the 3D map, fall into a situation that is difficoult to recover (i.e. looking at the sky near the earth).

So a button to reset the view is useful when you are in 3D mode

**Comment by MV88** [comment]
There is the zoom to max extent that does the trick.
![image](https://user-images.githubusercontent.com/11991428/27434717-eaa766b8-5759-11e7-9cd3-dc61b33fbb79.png)

Shall we close this issue then ? @tdipisa @mbarto @offtherailz

**Comment by MV88** [comment]
OK, as discussed with lorenzo, I'll make always visible this tool
