### ISSUE TITLE
About plugin hidden by background selector

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#1857]
Currently the about button is hidden by the background selector we should move it from that location.

![_about](https://cloud.githubusercontent.com/assets/19175505/26247413/12c476a8-3c9e-11e7-9089-4e1da5ce7997.png)

**Comment by MV88** [comment]
What about adding a button in the settings panel or in the burger menu ? 
@offtherailz @mbarto @Gnafu  ?

**Comment by offtherailz** [comment]
Yes @MV88 , @simboss suggested it too.

**Comment by mbarto** [comment]
Done
