### ISSUE TITLE
Mouse Position doesn't work on mobile

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#188]
The mouse position on mobile shows: 
Y: NaN, X:NaN
It also overlaps the zoom tools and  the crs selection should be hidden( not needed on the map at any time). 
The NaN should not appear (in any case). 

I addition, for mobile devices the mouse position should be replaced with another tool or removed. 
I suggest to draw a cross at map center and show it's coordinates instead.

**Comment by kappu72** [comment]
Hi Lorenzo, mobiles don't have pointermove or mousemove events. In touch devices you tap and drag map.

**Comment by simboss** [comment]
Then we should decide if we want to disable this controlo for mobile or what.

It cannot simple NOT work.

**Comment by mbarto** [comment]
I would disable it

**Comment by kappu72** [comment]
We have tow option:
1) First disable on touch devices
2) On touch devices use click event to show clicked position.
First quicker, let me know your choice.

**Comment by mbarto** [comment]
Go for the first option

**Comment by kappu72** [comment]
Both Ol and Leaflet are able to determine if device is touch or not.
(L.Browser.touch ol.has.TOUCH) this could be a useful info to be retained in app state. 
Maybe we can add a browser objet to app state  including  some browser properties.
Other option is to add a method in utils that return touch property.
Waiting form suggestions
