### ISSUE TITLE
Review cookie policy 

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#1898]
Cookie policy popup should have a "read-more" link, maybe also an opt out to exit. 
The read more link should open the detailed privacy page, with the list of the used cookies.

**Comment by MV88** [comment]
- [ ] Add leave option that redirect to google.com
- [ ] Add a page "more details" inside mapstore.
- [ ] Accept button will dismiss the cookie panel
- [ ] The url "more details" must be configurable

Make it similar to http://www.geo-solutions.it/
