### ISSUE TITLE
Feature zoom do not zoom correctly with certain features

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#1906]
Here the sample json that is not correctly managed. 

[issued_fc.json.zip](https://github.com/geosolutions-it/MapStore2/files/1044922/issued_fc.json.zip)

**Comment by MV88** [comment]
I need some more details:
- Where i can find the layer that gives the error
- Which layers is that gives the error  (Edifici_PUC ?)

**Comment by tdipisa** [comment]
closed for inactivity.
