### ISSUE TITLE
Add optional 'show on map' support to feature grid 

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#1918]
The 'show on map' option is required into the FeatureGrid toolbar as action to show on map the results retrieved in the current page.

**Comment by kappu72** [comment]
Notes:
When user selects the sync_filter_wms control, in featuregird toolbar, the filterObject state is pasted in the featureGrid selectedLayer.
At layer level, the WMS layer plugins (leaflet, cesium, openlayers) use WMFFIlterUtils to generate the corresponding CQL_FILTER and update the layer.
When the featuregrid panel is closed everything is restored.
In editing mode this functionality is disabled.
Wait for @offtherailz merge to finish the issue
