### ISSUE TITLE
Queryform FilterField could be created with a not unique rowId

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#1938]
Investigate how can two filterfields can be connected together even if they are in different groups or in the general one.
As soon as I can reproduce it i'll post the instructions here.

**Comment by MV88** [comment]
We need to use the getTime() method to get a unique id instead of .getUTCMilliseconds() in the queryform reducer
https://www.w3schools.com/jsref/jsref_gettime.asp
https://www.w3schools.com/jsref/jsref_getutcmilliseconds.asp

**Comment by tdipisa** [comment]
fixed with #1948
