### ISSUE TITLE
Avoid closing the list when clicked on the pagination tools

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#1940]
- [ ] The list should stay opened.
![autocomplete combobox](https://user-images.githubusercontent.com/11991428/27335596-5631fd50-55cd-11e7-812b-7952f7050e3a.gif)

**Comment by MV88** [comment]
In this moment we are using React-Widgets and is not possible to keep the list opened because it manages so internally.
We can try to change to other libraries. React-Select had some other problems.

**Comment by MV88** [comment]
Waiting a feedback [here](https://github.com/jquense/react-widgets/issues/591)

**Comment by tdipisa** [comment]
closed for inactivity
