### ISSUE TITLE
Provide fullscreen support for mobile devices

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#195]
On mobile devices the navigation bar should be hidden when possible. 
See this : http://www.html5rocks.com/en/mobile/fullscreen/?redirect_from_locale=pt
See also how to add the application to the home screen of the device (using it as an app).

**Comment by mircobe87** [comment]
The addition of tag `<meta name="mobile-web-app-capable" content="yes">` in the viewer's `index.html` page, seems to work on Chrome for Android. If the web app is added to home screen (see [Add to Homescreen](https://developer.chrome.com/multidevice/android/installtohomescreen)), after it has been launched, it goes fullscreen.
![webapp](https://cloud.githubusercontent.com/assets/5262132/10316103/19707e50-6c5e-11e5-8d00-c7c09d7ad08f.png)

An alternative could be [this](https://github.com/sindresorhus/screenfull.js) which allows a cross-browser usage of the JavaScript Fullscreen API.

**Comment by offtherailz** [comment]
So I suggest to :
* add an Icon for home screen 
* Place in the future setting panel ( https://github.com/geosolutions-it/MapStore2/issues/202 ) a button to add the application to the home screen. 

Did you also take a look to the scroll workaround?

**Comment by offtherailz** [comment]
Full screen button is present. To discuss the possibility to add the application to the home page and then allow the application to open without the navigation bar.
See [this](https://developers.google.com/web/fundamentals/native-hardware/fullscreen/) to understand the difference between fullscreen and add to home page

**Comment by tdipisa** [comment]
closed for inactivity.
