### ISSUE TITLE
Mutation error using cesium

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#1951]
I used the wheel button of the mouse and i ended up with this error.
What I've done is to zoom and then try to "look the sky" 
![image](https://user-images.githubusercontent.com/11991428/27438659-42f0c952-5766-11e7-9331-6f73edb144f1.png)

**Comment by MV88** [comment]
![image](https://user-images.githubusercontent.com/11991428/27438795-a4034f08-5766-11e7-9238-fac310743e47.png)

**Comment by offtherailz** [comment]
Unable to replicate, close for inactivity
