### ISSUE TITLE
Refresh button style is different in different contexts

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#1975]
The position of the refresh button is different in different contexts
![image](https://user-images.githubusercontent.com/1279510/27545321-cf4f0a72-5a8f-11e7-962f-aa8d6517b54e.png)

**Comment by offtherailz** [comment]
Patched with a style that should fit both use cases(#1973 via 46ce943df8ba26e60fdcfbace4a1e3d718bd522b)
Still not clear why different context (e.g custom project vs product) has different results

**Comment by tdipisa** [comment]
Not more needed
