### ISSUE TITLE
ES6 syntax not parsed by Docma

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#1978]
See this issue: 
https://github.com/onury/docma/issues/18

This causes documentation generation error.

**Comment by mbarto** [comment]
After a round of investigation:
 * docma, uses jsdoc, that uses espree that uses acorn with some plugins to parse JSX / ES6-7 syntax
 * this syntax is not supported by acorn + used plugins:
  * static property initializers (e.g. static propTypes = { ... } ), an acorn plugin called acorn-static-class-property-initializer support those already exists, we should try to integrate it
  * method definition using arrow functions (e.g. myMethod = () => {}), I could not find a plugin for this yet, we can try to implement it by ourselves

Plan of solution:
 * implement acorn-static-class-property-initializer and method definition using arrow functions for acorn and test them
 * implement support on our fork of the involved libraries
 * prepare PRs for related projects to include support in future releases
