### ISSUE TITLE
Zoom to layer and vector search for imported shapefiles

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#1990]
![2017-06-29_1144](https://user-images.githubusercontent.com/3932165/27681716-6d14ec68-5cc0-11e7-9636-29c87c2e3ba9.png)

**Comment by offtherailz** [comment]
I changed this into an enhancement and postponed. Filtering is a little more difficult, but zooming is trivial.

**Comment by tdipisa** [comment]
closed for inactivity
