### ISSUE TITLE
How to set a Google API key when using the API?

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#1996]
I created a map and generated the html to use the MapStore2 API.
After the deploy the Google background shows an error because it misses the Google Maps API key.

How can I give MapStore2 my Google Maps API key to make it work?

**Comment by offtherailz** [comment]
You should pass it when you include the script in the  script tag, isn't it?
`<script async defer
      src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap">`

**Comment by Gnafu** [comment]
Correct, I'll add it to the documentation
