### ISSUE TITLE
Query panel breaks if WPS is not available

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#2019]
If the query panel is configured to use WPS to autocomplete the values and there is any issue with the WPS service (service unavailable, cors not allowing connection, network error) the query panel becomes unusable.

In this case the user cannot input values to create filters.

**Comment by MV88** [comment]
Basically the spatial filter is empty but the cause is not the broken wps. Continue to investigate.
![image](https://user-images.githubusercontent.com/11991428/27902889-acb79fd8-6237-11e7-9f22-342fee73ab9e.png)

**Comment by MV88** [comment]
The problem was if the spatial operations and methods were missing in configuration the spatial field would not work properly.
