### ISSUE TITLE
Cannot save a new map with more than 4 layers 

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#2021]
Using a local geoserver (created from installer) and some layers with postgis.

- create new map
- add at least 5 layer
- an error occures.

the cause is in the payload requests due to the **allowedSrs** property that is huge.
This should be investigated.
(a quick workaround was to limit some srs on geoserver).

**Comment by allyoucanmap** [comment]
Related issue #2354

**Comment by offtherailz** [comment]
can this be closed?

**Comment by offtherailz** [comment]
We should test this with a GeoServer from installer.
For sure the issue is related to this: https://github.com/geosolutions-it/geostore/issues/170

**Comment by tdipisa** [comment]
@offtherailz we need to better explain why we need this issue opened

**Comment by mbarto** [comment]
We should also avoid saving all the SRS list in geostore, maybe (e.g. filtering the WMS capabilities list with the MapStore2/proj4 supported ones)
