### ISSUE TITLE
Add a new toolbar to clean up the lower right corner area

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#2023]
A complete review of the lower right corner area is needed adding a new toolbar that contains only useful controls:

- the preview map control should be removed as default 
- the info tool should be moved into the right toolbar

The new toolbar contains:

- scale and scalebar
- coordinates
- coordinate reference system

![tools-footer](https://user-images.githubusercontent.com/1280027/27908098-81c65db0-624a-11e7-85cd-f7114c4f45e2.png)

**Comment by mbarto** [comment]
Some open points:
 * what happens to MapStore2 logo and MadeWithLove (not appearing in the mockup image)
 * what happens in mobile mode

**Comment by MV88** [comment]
@allyoucanmap @mbarto Set showLabels to false in config and then the style is messed up.
https://github.com/geosolutions-it/MapStore2/blob/master/web/client/localConfig.json#L302

Also if there is a label too long and the combobox is not large enough to see it

**Comment by tdipisa** [comment]
see also feedbacks on #2136

**Comment by offtherailz** [comment]
I add a notification about the Google attribution, that is not visible anymore.

**Comment by Gnafu** [comment]
Google logo and  the Google attribution are partially covered.  
Do you want to address it in this issue or in a different one?

**Comment by tdipisa** [comment]
@mbarto @Gnafu I think the logo's issue can be closed here. Can we move a bit background box?
