### ISSUE TITLE
Native EPSG export option with WGS84

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2024]
Allow export (from feature grid) in native EPSG as default. As an option allow to export in WGS84

**Comment by kappu72** [comment]
Do you need something configurable by the UI?

**Comment by tdipisa** [comment]
Yes, it shold be great. I suggest a configurable list of EPSG options to use and a dropdown below the format selector, with the possibility to choose the default selected by plugin's configuration.
