### ISSUE TITLE
Trigger notification if a map is an old one asking for updating it

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#2031]
**requirements:**
- The user must have write access for the resource map.
- Must be a mapstore map (old mapstore)
- remove the refresh tools from the TOC

**behaviour:**
if the requirements are met then show a notification in top center position with warning style (yellow) containing:
- an update button that will update the map in background (with all the options selected). 
![image](https://user-images.githubusercontent.com/11991428/28072857-778c3082-6654-11e7-8d1a-8d0080a62096.png)

- a body text "This is an old map, thus not all the functionalities can be enabled. Click on update button in order to update the map or simply dismiss this notification if you don't want to update it."

**Comment by allyoucanmap** [comment]
Implemented with progress bar
![autorefresh](https://user-images.githubusercontent.com/19175505/28278393-38295fd2-6b1d-11e7-9b41-f2de3ab5016e.gif)
