### ISSUE TITLE
Elevation slider send a GetLegendGraphic request with elevation attribute that cause an exception

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2041]
![screenshot from 2017-07-18 16-51-54](https://user-images.githubusercontent.com/19175505/28324427-a4525af6-6bdb-11e7-9d73-eb041f03db2c.png)

![screenshot from 2017-07-18 16-54-15](https://user-images.githubusercontent.com/19175505/28324418-9d93bc0a-6bdb-11e7-857d-78d7b27446dc.png)

**Comment by tdipisa** [comment]
@allyoucanmap Can you specify some reproducible steps for this?

**Comment by tdipisa** [comment]
closed for inactivity
