### ISSUE TITLE
Speed up MapStore2 loading

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2042]
We should speed up application loading.

Here a list of suggested tasks:
- [ ] Put resources on CDN (for the demo)
- [ ] Check if all the resources are well boundled and compressed (images, css, fonts)
- [ ] Reduce bundle size:
- [ ] try loading Cesium only when needed (first time 3d is enabled)

Analyzing with `BundleAnalyzerPlugin`, the dynamic requires (require-ensure) to `ogc-schemas` doesn't seem to work anymore. `ogc-schemas` is still included in the main bundle, an in every chunk loaded on demand. 
![image](https://user-images.githubusercontent.com/1279510/28327552-0e71363e-6be4-11e7-97f2-b731a1ee83ec.png)
In detail some possible optimizations to the bundle could be: 
- [x] `ag-grid` should be removed from the final bundle soon (~500KB)
- [x] `ogc-schemas` (4.71MB) Should be removed from the main bundle. While removing completely it should be loaded only via require-ensure.
- [ ]  `ogc-schemas` should be removed forever using xml2js or some custom code instead. This could allow to remove also `w3c-schemas` and `jsonix` (450 KB together). 
- [ ] `pdf.js` could be loaded on demand with require-ensure
- [ ] `lodash` could be included in separated packages packages. 

We have to merge this analysis with the [Google's one](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdev.mapstore2.geo-solutions.it%2Fmapstore%2F&tab=mobile) to optimize the application both for mobile and desktop devices.
Some other _futuristic_ changes to speed up the application are : 
 - isomorphic javascript executed on backend to produce the initial page while loading. 
 - Separate the application in 1 bundle for each page (@mbarto already tried a long time ago, but the solution had some bad side-effect and required a revert. We didn't investigated more on this)

**Comment by mbarto** [comment]
From the picture it looks like it's react-data-grid that is about 500k, not aggrid, am I wrong?

**Comment by offtherailz** [comment]
I highlighted react-data-grid in error. Anyway ag-grid is above it in the picture, with more or less the same size.
