### ISSUE TITLE
Map Update tool cannot save the map if a layer fails to update

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#2047]
> Uncaught TypeError: Cannot convert undefined or null to object at Function.from (native)

To reproduce:

- Load an old mapstore1 map (the map must have at least one misconfigured layer)
- Use the update tool --> The tool notifies that one layer could not be converted
- Save the map

Expected result: the map is saved, the layer is still broken.

Actual result: Click on "Save" does nothing, map is not saved.

**Comment by mbarto** [comment]
An example of map with this behaviour would be useful

**Comment by Gnafu** [comment]
The bug is not currently reproducible.

**Comment by tdipisa** [comment]
To test within the reviewed update tool
