### ISSUE TITLE
Drawer Menu shows a scroll bar in Edge and IE 

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2049]
It seems that overflow-y of a div element (content) in Sidebar has been set to scroll in the in line style.
The same element had an overflow auto in the previous release.

Also in Chrome the scroll bar has a width but is invisible.
![sc](https://user-images.githubusercontent.com/19175505/28416743-8fc2d464-6d55-11e7-86d9-8e78dad8e7aa.png)

**Comment by tdipisa** [comment]
Fixed with #2094
