### ISSUE TITLE
Share link title in linkedin share is "GeoSolutions" and is not overridable

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2052]
Share buttons trigger use the title "GeoSolutions" for the shared resources. 
The share title is used only by Linkedin, as far as I know. This causes the link you are sharing on Linkedin contains the "GeoSolutions" as title.  
We should get the title of the current page or map.

**Comment by MV88** [comment]
What if we use for linkedin a generic title as: 
Check out my new map : "url"
