### ISSUE TITLE
Back to the home page causes reload of the first page

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2055]
When you search a map, you open it and you go back to the home page, you see the first page is reloaded loosing the original search results . Sometimes during reloads the page size is not 12, as usual (#1998).

**Comment by MV88** [comment]
After the login and logout the size of the page is set to 20, but if we enter a map and go back to the homepage the limit is set to 12 again.

Which size do you want to keep, 12 or 20 ?
@tdipisa @mbarto @offtherailz @Gnafu @simboss

**Comment by Gnafu** [comment]
Fix verified in QA-2017.05.00
