### ISSUE TITLE
Reduce the boilerplate for a custom project

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2073]
Produce a clone of the MapStore 2 with custom plugins is hard and maintenance of these files during MapStore 2 evolution is hard too.

Some reasons are: 
 - Project script generate a minimal project with a lot of customization, the way to have something similar to MapStore 2 is too long. 
 - Too many files to copy and keep in sync, all with their differences
 - Breaking changes are not so trivial to be identified and solved.

Instead we need to:
 - Analyze what files can be reused for dependent projects (e.g. appConfig, pages, containers) and list what files must be created for the custom project (e.g. index.html, package.json...)
 - Separate the demo from the MapStore 2 project, reusing most of the code. This way we need: 
   - A product
   - A demo that extends the product
   - every depended project should extend the product as the demo does

Other improvements can be : 
 - Create a build folder with all the functions needed to create the wepback configs, so every projects reuses most of the code to generate its own configuration. 

Other things to investigate: 
 - How to detect changes to the other files needed (package.json, index.html...). Maybe an update script that checks all these changes.

**Comment by riaanvddool** [comment]
My workflow currently:

Use createProject.js to create two identical projects, one with the previous version of MapStore2 (release or commit on master) and one with the new. Then do a diff between the two to determine what has changed and what changes I should make to my previously created project.

    $ node createProject.js standard compare 0.0.1 "Compare" https://gitlab.com/compare compare
    $ mv compare compare_old
    $ git pull origin master
    $ node createProject.js standard compare 0.0.1 "Compare" https://gitlab.com/compare compare
    $ mv compare compare_new
    $ meld compare_old compare_new
`
Dont know if there is a better way of doing this?
