### ISSUE TITLE
Feature grid style messed up on Firefox and EDGE

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#2081]
The problem appear when you try to resize down the grid or just switching the settings tool
![image](https://user-images.githubusercontent.com/11991428/28963063-0983e5d2-7908-11e7-8815-a5b880b29a0f.png) 
![firefox style messed up](https://user-images.githubusercontent.com/11991428/28963538-bd422268-7909-11e7-88c4-5787550e66f0.gif)

how to replicate:
- open Firefox/Edge
- open the grid
- swtich settings tool on/off   or   resize up and down the grid

a scrollbar appears and it messes up the style of the feature grid.

**Comment by MV88** [comment]
On Edge there is also a scroll bar on the left of the map
![image](https://user-images.githubusercontent.com/11991428/28963659-32bfe192-790a-11e7-932a-98bede7452ff.png)

**Comment by aaime** [comment]
So you fixed the edge on Edge?
