### ISSUE TITLE
MapStore 2 escapes single quotes when saving

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2083]
Try to change the title of a layer of the map as: 
```
CITTA' 
```
The map title will be converted into: 
```
"title": "CITTA\' "
```
That is not a valid JSON (because of the \').
Probably because of this: 
https://github.com/mathiasbynens/jsesc#quotes

**Comment by Gnafu** [comment]
There is now an issue with re-saving a map with encoded characters.

Add a layer translation with a double quote ( for example  !"£  )
Save it
Open it  -> It will display fine
Save it again
Open it -> Cannot load

**Comment by mbarto** [comment]
Create new PR to fix that
