### ISSUE TITLE
Rethink the layout and behaviour of the sidebar on the right.

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#2084]
We need to decide how to change some tools of mapstore when the feature grid is opened which hides some of the following tools.

in particular these tools
![image](https://user-images.githubusercontent.com/11991428/28969381-a8c6a00a-7924-11e7-8f13-fec8d96a2408.png)

**Comment by tdipisa** [comment]
The Map should be resized accordingly

**Comment by simboss** [comment]
I bumped the priority of this issue since in many cases the fact that the side toolbar disappears hinders the possibility for a user to interact with the map.

As an instance when the data grid is open we cannot enable GetFeatureInfo!

**Comment by mbarto** [comment]
![image](https://user-images.githubusercontent.com/2770528/31024218-a72012ea-a53e-11e7-92fd-c48f692f6130.png)

**Comment by simboss** [comment]
I am going to rephrase and improve this one as well.
