### ISSUE TITLE
Eslint doesn't allow nested destructuring

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2089]
When try to write something like: 
```
const {a : {b} } = ...
```
You have an error like: 
```
b used outside of binding context  block-scoped-var
```
this is probably because of an issue for eslint. Solved in eslint v4.4.0. (see [this](https://github.com/eslint/eslint/commit/1c55e95a3b069eb70fae2a3022926d44cb008676)) Updating eslint should solve the issue.

**Comment by tdipisa** [comment]
closed for inactivity.
