### ISSUE TITLE
Disposal axios request

### ISSUE THREAD

**Issue by kappu72** [geosolutions-it/MapStore2#2099]
Could be useful to have really disposable axios request.
At time fo writing, if wrapping an axios request with Rx, the observable is disposable, but the undergoing axios request isn't rally cancelled when the observable is disposed.
I suggest to add to axios rxGet rxPost rxPut and rxPatch methods,  that will have same signature of corresponding axios get, post, put, patch methods, but will return an observable that really cancels axios request when It's disposed.

**Comment by tdipisa** [comment]
closed for inactivity.
