### ISSUE TITLE
Disable featuregrid editing and spatial filter with Cesium

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#2103]
Featuregrid editing doesn't work with cesium and also the spatial filter.

We can go in two directions.
- remove the feature grid when switching to cesium (this will also remove the possibility to reach the queryform)
- just disable/remove some functionalities like spatial filter and edit mode

**Comment by offtherailz** [comment]
Disable query panel and editing when you are in cesium. A tooltip should explain that "This functionality is not available in 3D mode"
When query panel is open, 3D switch action closes the query panel.

**Comment by MV88** [comment]
```js
var i = 0;

// a `while..true` loop would run forever, right?
while (true) {

// stop the loop?
	if ((i <= 9) === false) {
		break;
	}

	console.log( i );
	i = i + 1;
}
// 0 1 2 3 4 5 6 7 8 9
```
