### ISSUE TITLE
Home page load time is too high and slow responses to extjs search queries

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#2105]
Related to the GeoStore issue geosolutions-it/geostore#161

**Comment by etj** [comment]
geostore@b590e07aeb7c81503b95bd320f1b6020ce3d9d55

**Comment by tdipisa** [comment]
@Gnafu can we close this issue? it's been testet, rigth?

**Comment by Gnafu** [comment]
It has been manually tested but the build still points to the old GeoStore version.
We need to change the dependency to geostore 1.4.2-SNAPSHOT

**Comment by tdipisa** [comment]
@Gnafu, ok please send a PR for this.
