### ISSUE TITLE
Layer transparency value should update during slider changes

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#2106]
The layer transparency widget is currently showing the value only after the user has finished to move the slider.
The value should change when the slider is dragged, no only when the mouse is released.

**Comment by allyoucanmap** [comment]
I tried to use onSlide event rather than onChange with `react-nouislider` and it seems to work.
Maybe it needs some throttle control to reduce the actions.

**Comment by tdipisa** [comment]
closed for inactivity
