### ISSUE TITLE
Wrong gray style on hover in map editing

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2108]
On mouse hover, the permission rows become gray.  Seems to be an issue due to the recent theme changes (tables and hover)

![image](https://user-images.githubusercontent.com/1279510/29206474-63dd3ee6-7e82-11e7-8570-6611fa567850.png)

**Comment by allyoucanmap** [comment]
related issue #2437

**Comment by tdipisa** [comment]
closed for inactivity
