### ISSUE TITLE
Catalog improvements

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#2116]
- [ ] When the url lose the focus an on-the-fly validation should apply. it should verify that the service is available
- [ ] After the previous check, if positive, it should infer and populate the type and/or title of the service if possible.
- [ ] Add a tooltip on the service list that shows the url of that service or only of the service selected
- [ ] Save services with the map configuration.
- [ ] Add a delete button in edit mode and implement the related funcionality.
- [ ] The record items should not be cut (avoid scrollbar), but they should be displayed as a whole. We can change the page size accordingly to the height available
- [ ] Move the add to map button to the left as indicated in the mockup present in #1783 
- [ ] Move all the tools & plugin hidden by the catalog to the left of the catalog sidebar
- [ ] add localization of titles?

**Comment by tdipisa** [comment]
Issue out of date after recent catalog improvement provided in 2019.02.00
