### ISSUE TITLE
Catalog reducer has an error if Catalog services are not included in the configuration of initialState

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#2131]
```
TypeError: Cannot read property 'services' of undefined
    at catalog (catalog.js:96)
```

**Comment by Gnafu** [comment]
Which plugin should I remove to test this?

**Comment by MV88** [comment]
You can just remove the catalog services list and it should not appear the typeError inside the console.

**Comment by Gnafu** [comment]
I tried the following:
 - In the MAP json, removed "catalogServices.services" object
 - In the LOCALCONFIG json, removed the "MetadataExplorer" object from "plugins.desktop" array
 - In the LOCALCONFIG json, removed the "initialState.defaultState.catalog.services" object
 - In the LOCALCONFIG json, removed the "initialState.defaultState.catalog" object

The last test case caused the following error to show up in console when closing the catalog or adding a new services to the catalog.

```
Uncaught TypeError: Cannot read property 'undefined' of undefined
    at o (mapstore2.js:150)
    at mapstore2.js:46
    at A (mapstore2.js:113)
    at p (mapstore2.js:19)
    at mapstore2.js:92
    at mapstore2.js:68
    at mapstore2.js:54
    at dispatch (mapstore2.js:46)
    at mapstore2.js:193
    at mapstore2.js:54
```

**Comment by MV88** [comment]
is there an error if initialState.defaultState is an empty object
i guess this is not related to the fix for this issue. but a new issue instead.
