### ISSUE TITLE
Feedback on new footer

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#2136]
Some feedback inline below; let's discuss and the schedule eventual tasks that come out of it.

- [x] Not sure about the gray aspect. At a second look is not probably the gray but the fact it does not really look in synch with the L&F of the other components: it misses profondity (it looks too flat) and it is easy to confuse it with the browser own toolbar (see below).
- [x] The mouse icon: too small, no tooltip, difficult to understand what it does!
- [x] Labels can be improved; mouseCoordinates and mousePositionCRS, wait shouldn't this be mouseCoordinates and mouseCoordinatesCRS or mousePosition and mousePositionCRS? Maybe we want shorter names? Let's think about this.
- [x] The GetFeatureInfo is now hidden, should we make it on by default? This would be important to have right away, I believe; we are confusing users right now IMHO.

@tdipisa Check my feedback and let's decide together what we do with this.

![ms2_1](https://user-images.githubusercontent.com/693880/30036614-4037207e-91b5-11e7-89ba-3dd87bcd29c2.jpg)

**Comment by tdipisa** [comment]
In latest versions we have a reviewed footer. Closed for inactivity. We will open a new issue if needed io the future
