### ISSUE TITLE
Legends for specific styles are forced to be too small

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#2138]
Every style choose other than "Default" will try to request a legend with `height=12&width=12`

Expected Result: 
![2017-09-05_1452](https://user-images.githubusercontent.com/3932165/30062009-ee7ecfa8-9249-11e7-97d2-b1363d31a674.png)

Actual Result:
![2017-09-05_1451](https://user-images.githubusercontent.com/3932165/30062019-f5f881ac-9249-11e7-9378-694eca20c6ed.png)

https://cloudsdi.geo-solutions.it/geoserver/eumetsat/ows?service=WMS&request=GetLegendGraphic&format=image%2Fpng&height=12&width=12&layer=wind_ascat_thinned&style=&version=1.3.0&SLD_VERSION=1.1.0&LEGEND_OPTIONS=forceLabels%3Aon%3BfontSize%3A10&SCALE=18489335

**Comment by tdipisa** [comment]
@offtherailz I think this can be closed now

**Comment by tdipisa** [comment]
Closed with #5176
