### ISSUE TITLE
Mouse position on mobile is confusing

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#2145]
User's feedback here but potentially easy to address.

Showing a client the mobile version I got feedback about the mouse position to be  too intrusive and also confusing as it is not clear what kind of position that is ( I assumed the center of the map).

![file 07-09-17 13 24 15](https://user-images.githubusercontent.com/693880/30161661-d341018c-93d1-11e7-859a-724430488084.png)

I would suggest that:

- [ ] By default we show no position coords
- [ ] If position is enabled we need to point out clearly where this position is coming from like using a target symbol or whatever.

We need to address this quickly, no need to implement both points.

**Comment by mbarto** [comment]
We already have coordinates on tap (via Identify), so in my opinion we can remove the MousePosition plugin from mobile completely

**Comment by simboss** [comment]
👍

**Comment by Gnafu** [comment]
Fixed in QA-2017.05.00
