### ISSUE TITLE
3D On Mobile with IPhone is hard to use

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#2148]
User's feedback again.

Using the 3D version on the mobile (i.e. IPhone here) is very difficult. The zoom in and out with double pinch interact badly with the double pinch of the browse and instead of zooming the map we get the browser zoom (see below).

**Before**
![file 07-09-17 15 11 54](https://user-images.githubusercontent.com/693880/30165052-eb7cdb06-93de-11e7-8e86-49b8d82a4acd.png)

**After**
![file 07-09-17 15 11 40](https://user-images.githubusercontent.com/693880/30165053-ef48b494-93de-11e7-8449-1020f309facb.png)

I have no idea if this works any better on Android, but on IPhone I would rather not have it enabled by default.

**Comment by MV88** [comment]
let's disable it for the moment.

**Comment by offtherailz** [comment]
as from [this discussion](https://stackoverflow.com/questions/4389932/how-do-you-disable-viewport-zooming-on-mobile-safari) it seems `user-scaleable=no` is disabled in Safari for iOS 10.
We should try to use [this](https://stackoverflow.com/questions/4389932/how-do-you-disable-viewport-zooming-on-mobile-safari/39711930#39711930) workaround
