### ISSUE TITLE
Provide a feedback for mismatching password in user editing card

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#2150]
Some characters are not allowed and this should be notified.
at least a tooltip that says to align the password even if this should be very intuitive.
also the min length of the password is not notified
![image](https://user-images.githubusercontent.com/11991428/30165432-58bce1ec-93e0-11e7-99af-47572a43821d.png)

**Comment by tdipisa** [comment]
closed for inactivity.
