### ISSUE TITLE
Full Screen button does not work on IPhone

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#2151]
Not sure this happens on Android but on IPhone it does nothing, see below.

**Nothing happens :( **
![file 07-09-17 15 17 20](https://user-images.githubusercontent.com/693880/30166070-82038428-93e2-11e7-80f3-e2980b395ded.png)

**Comment by MV88** [comment]
On android it works correclty, at least with Android 7.0 
@simboss  Can you let me know which version of safari were you using ?
