### ISSUE TITLE
Review of FeatureInfo look and feel

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#2155]
Make featureinfo tool docked to the side.

**Comment by mbarto** [comment]
@tdipisa Do toolbars and right sided tools move to the left when the docked panel is open?

**Comment by mbarto** [comment]
@tdipisa so... all  we want to do is to put the panel on the right? Nothing of the other stylistic changes I can spot on the mockup?

**Comment by mbarto** [comment]
![image](https://user-images.githubusercontent.com/2770528/30210085-448ccf00-949b-11e7-96cc-4fffe1fa7764.png)

**Comment by tdipisa** [comment]
@mbarto in my opinion the map should be resized when the info panel is open so the right side tools and the toolbar should be moved to the left. I think this is an issue in general in MS2, also other tools like the feature grid and the TOC overlap the map when opened. So probably this should be considered as a separated, what do you think?

**Comment by tdipisa** [comment]
@mbarto, yes just put the panel on the right at this stage.
