### ISSUE TITLE
WFS download will not work via proxy

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#2168]
Using a wfs service via proxy (the server url is not in "useCORS" list) will fail to export the features from the features grid.

To replicate see [map 2940](https://mapstore2.geo-solutions.it/mapstore/#/viewer/leaflet/2940) 

The "cloudsdi" service is CORS-enabled but it is not in the useCORS configuration list so MapStore2 will try to use the proxy. And the proxy will fail to fullfill the request.

**Comment by simboss** [comment]
@Gnafu keep me posted

**Comment by MV88** [comment]
see https://github.com/geosolutions-it/http-proxy/issues/46
