### ISSUE TITLE
Shapefile import - prj is not correctly parsed

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#2175]
The following files should be loaded by MapStore2 in the same area.

Axis order is inverted in the data as it is in the prj but currently MapStore2 is ignoring the axis order and is treating the native_latlon.zip shapefile as it has LON LAT coordinates instead of LAT LON as declared in the prj file:

```AXIS["Geodetic latitude", NORTH], AXIS["Geodetic longitude", EAST]```

[4326_lonlat.zip](https://github.com/geosolutions-it/MapStore2/files/1299745/4326_lonlat.zip)
[native_latlon.zip](https://github.com/geosolutions-it/MapStore2/files/1299746/native_latlon.zip)

**Comment by allyoucanmap** [comment]
Hi @mbarto can you please check if this has been solved after the other fixes you did on the shp importer?

**Comment by mbarto** [comment]
@allyoucanmap no, it is not, it is a different bug

**Comment by mbarto** [comment]
@allyoucanmap we can probably fix it updating this in a proper way: https://github.com/geosolutions-it/wkt-parser/tree/towgs84_datum_params
