### ISSUE TITLE
Current font is not well readable for numbers

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2178]
Proposal is to change it in favor of 'OpenSans' font

top: Raleway (current font)
bottom: OpenSans
![footer](https://user-images.githubusercontent.com/19175505/30419170-b640ba3c-9935-11e7-85f9-69754231cd19.png)

top: Raleway (current font)
bottom: OpenSans
![grid](https://user-images.githubusercontent.com/19175505/30419174-b88cddca-9935-11e7-9e4f-1b3a5aff88cf.png)

left: Raleway (current font)
right: OpenSans
![toc](https://user-images.githubusercontent.com/19175505/30419175-ba478750-9935-11e7-9b00-3e37c987adab.png)

**Comment by tdipisa** [comment]
We are reviewing the entire MS's layout (closed in favor of #4254).
