### ISSUE TITLE
Change all the spinners to make them uniform to the initial loader

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2179]
current initial loader
![lo](https://user-images.githubusercontent.com/19175505/30419600-3cc99500-9937-11e7-8088-8927eae88ae4.gif)

current spinner
![sp](https://user-images.githubusercontent.com/19175505/30419617-5170d068-9937-11e7-900a-1de6885cfb0b.gif)

result
![sp-n](https://user-images.githubusercontent.com/19175505/30419620-52c4125e-9937-11e7-9737-253d1dff69fd.gif)

**Comment by simboss** [comment]
nice 👍

**Comment by tdipisa** [comment]
closed for inactivity.
