### ISSUE TITLE
Make uniform the styles of all modals

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2180]
Some modals have different styles, we need to uniform them.

![modal](https://user-images.githubusercontent.com/19175505/30419949-6773ec14-9938-11e7-9fd2-786cbeb247d9.png)

![modal-s](https://user-images.githubusercontent.com/19175505/30419875-33d88cac-9938-11e7-86c3-9a97165a010e.jpg)

**Comment by tdipisa** [comment]
closed for inactivity.
