### ISSUE TITLE
Enabling LDAP support on GeoStore must be simplified

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#2184]
Create a maven profile to add the necessary files to configure the LDAP integration in GeoStore.

The same must be set on the project creation scripts so new projects can configure LDAP when needed.

**Comment by Gnafu** [comment]
The LDAP configuration process should also be simpler, see #2204

**Comment by simboss** [comment]
@Gnafu I think this issue needs to be reworded and the priority bumped.

It is simply unaccetable that it is so difficult to enabler LDAP for GeoStore.

**Comment by tdipisa** [comment]
closed for inactivity
