### ISSUE TITLE
Add an opacity slider on collapsible panel of layer in TOC

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2187]
e.g.:
enabled
![screenshot from 2017-09-15 12-44-16](https://user-images.githubusercontent.com/19175505/30493697-809701b4-9a45-11e7-8107-0fae022fa23c.png)
disbled
![screenshot from 2017-09-15 12-44-27](https://user-images.githubusercontent.com/19175505/30493700-828f930a-9a45-11e7-80bd-d4be6dbb5d23.png)

**Comment by allyoucanmap** [comment]
- removed full title (it will display only from properties)
- percentage of opacity on slider 

![screenshot from 2017-09-22 11-51-20](https://user-images.githubusercontent.com/19175505/30746233-6759829e-9fa9-11e7-8050-c703517e5f55.png)
![screenshot from 2017-09-22 11-51-32](https://user-images.githubusercontent.com/19175505/30746234-68f31f66-9fa9-11e7-850c-3209f1eb9c37.png)

**Comment by tdipisa** [comment]
That's really nice, +1
