### ISSUE TITLE
Infinite loading of saved local shape

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2202]
to reproduce:
- create new map
- add a shape file
- save map
- back to homepage
- open again the map

loading icon doesn't stop
![o](https://user-images.githubusercontent.com/19175505/30688582-dd0d6a3c-9ebe-11e7-8c19-5a57295aff1e.gif)

**Comment by mbarto** [comment]
Solved by https://github.com/geosolutions-it/MapStore2/pull/2198

**Comment by Gnafu** [comment]
Verified in QA-2017.05.00

**Comment by mbarto** [comment]
Duplicate of https://github.com/geosolutions-it/MapStore2/issues/2294, and it's already closed
