### ISSUE TITLE
Enter Exit from editing mode causes error in attribution removal

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2213]
This is a new bug due to the Map.jsx changes probably due to the attribution component. 
Steps to reproduce:
 - Login as admin
 - Open or create a new map
 - Add vector layer
 - Open feature grid (open TOC, select layer, click on grid button)
 - Enter edit mode
 - Exit edit mode --> **note** the attribution is not visible anymore
 - Click on the home button

*Result*
The map is not correctly unmounted and is rendered over the home page. 
![image](https://user-images.githubusercontent.com/1279510/30752727-7f9f5360-9fbd-11e7-8a8f-35bcbfc893e8.png)

Possible workaround: 
try/catch exception here : 
https://github.com/geosolutions-it/MapStore2/blob/0954585887b6e9ec8aa24579a810598d6e0e8ac3/web/client/components/map/openlayers/Map.jsx#L207
And here: 
https://github.com/geosolutions-it/MapStore2/blob/0954585887b6e9ec8aa24579a810598d6e0e8ac3/web/client/components/map/leaflet/Map.jsx#L104

And maybe also in cesium map.

**Comment by Gnafu** [comment]
Fixed in QA-2017.05.00
