### ISSUE TITLE
Allow creation of new groups / subgroups from the TOC

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#2215]
We should have:
 - [ ] an "Add group" button next to "Add layer" to add first level groups
 - [ ] an "Add group" tool when a group is selected to create subgroups
 - [ ] an "Add layer" tool when a group is selected to create a layer and assign it directly to the selected group
 - [ ] a plugin configuration option to limit the level of nesting allowed
 - [ ] use icons instead of text in the buttons at all times

We should also change the group selection combo behaviour in layer settings, to only allow changing the group of layer and remove the ability to create new groups from there.

**Comment by mbarto** [comment]
![image](https://user-images.githubusercontent.com/2770528/58021881-78eaf980-7b0c-11e9-9764-13703d9e1921.png)

![image](https://user-images.githubusercontent.com/2770528/58022301-7b018800-7b0d-11e9-847d-2c43896cf85d.png)

**Comment by simboss** [comment]
I would use icons instead of button with texts. This is tru in all cases, not only where there is a layer or a group selected.

Please, suggest some icons or ask @allyoucanmap to build two.

**Comment by simboss** [comment]
Referring to this "We should also change the group selection combo behaviour in layer settings, to only allow changing the group of layer and remove the ability to create new groups from there."

I would simply remove entirely the combo from the layer settings. People can move things around manually. This way we reduce the paths of code to handle to manage groups. @tdipisa what do you think?

**Comment by tdipisa** [comment]
@simboss In my opinion this could be useful instead, essentially in cases with big TOCs with many layers and groups where the user may have trouble in moving layers simply dragging them.

**Comment by simboss** [comment]
I agree but this is too hiddne and too difficult.

What we have to do in the future is to add arrows on the layers like there are in most webgis software.

I am still in favour of removing this to simplify the whole thing.

**Comment by tdipisa** [comment]
@simboss ok we will remove it.
Anyway even though in the future we can introduce a mechanism based on arrows, since this is a small piece of code and a simple functionality, I think it's better to have it as reported in the description than haven't it at all (this is only my opinion).

**Comment by mbarto** [comment]
If we remove it there is no way, right now, to move a layer from a group to another group, because drag&drop only reorders stuff inside the containing folder, moving layers/groups to different groups is not supported through drag & drop, only using the combobox.

**Comment by simboss** [comment]
@mbarto so we should fix this, otherwise we leave a functionality that is partially implemented in two places completely different.

Fixing it means, removing the combo and making it possible to move layers between groups, which is the standard in all software I have ever used so I believe it is what users would expect us to support.

**Comment by tdipisa** [comment]
@simboss, this requires a significant effort and a TOC review, something that we are not able to complete within May. I would like to split this issue to work on the drag&drop of layers between groups in another issue soon.

**Comment by simboss** [comment]
I see your point, but I would want to see this investigation now not later.
Once we have a clear plan we can decide to execute in steps and accept some inconsistencies.

So please, talk to @mbarto to review and plan the overall approach, split it and then decide what to do now and what to delay.

**Comment by tdipisa** [comment]
@mbarto @simboss I have created an Epic to collect issues related to this topic, @mbarto will investigate tomorrow on #3781 to provide an estimate and needed tech details

**Comment by simboss** [comment]
thx
