### ISSUE TITLE
Identify plugin closes feature grid while editing

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2216]
to reproduce:
- login as admin
- open feature grid from WMS layer
- click on the edit mode button
- minimize the feature grid and click on identify plugin button
- click on the map
the feature grid will close without any alert and the identify panel will appear

**Comment by MV88** [comment]
I think is better to hide the GFI tool when edtiting is enabled.
ATM if it was enabled it gets disabled, but this is not sufficient because a user can enable it again.
