### ISSUE TITLE
Review scroll to top plugin style

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2226]
possible changes
- opacity (to test)
- position on mobile

current style on mobile
![screenshot from 2017-09-26 16-03-54](https://user-images.githubusercontent.com/19175505/30864613-6d47697c-a2d4-11e7-9ce1-74d1b9f0b12d.png)

**Comment by tdipisa** [comment]
Already reviewed and implemented in latest versions with the home page refactor, we can close this.
