### ISSUE TITLE
Annotations improvements

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#2232]
* [ ] add the marker icon on the annotations detail page
 * [ ] add a label with the title over the marker on the map
 * [ ] improve styling using the new TOC as a guideline
 * [ ] allow opening annotations panel from the TOC annotations layer (maybe also adding a new annotation from there)
 * [ ] allow snapping on the annotations layer or other vector layers during drawing / editing of geometries

**Comment by tdipisa** [comment]
This is an old issue (out of date), several annotations improvement have been released in 2019.02.00. We can consider to open new issues to provide additional improvements on the current tool if needed in future releases.
