### ISSUE TITLE
Improve notifications feedback  

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2233]
**When possible could be useful to get specific information/warning/error feedback**
- AutomapUpdate refresh action feedback
![error](https://user-images.githubusercontent.com/19175505/30960477-66a1d664-a443-11e7-83ec-f0f69019eb3a.png)

**TOC the following warning happens when the tiles haven't been loaded correctly**:
causes
- layer cannot be read from user
- layer isn't on the requested server
- layer is disabled on the server
![aa](https://user-images.githubusercontent.com/19175505/30960766-50988326-a444-11e7-9f87-cb8cfff57d6f.png)

**Save - Save As**
Notify success/error on save map

**Map Settings**
Notify if a rule has been changed and not added before close the modal
![screenshot from 2017-09-28 14-38-59](https://user-images.githubusercontent.com/19175505/30966897-cd8f308a-a45a-11e7-8379-1955a29bce2f.png)

**Feature Grid**
![screenshot from 2017-09-28 16-24-58](https://user-images.githubusercontent.com/19175505/30979083-d8947cd4-a47c-11e7-9a78-b161fe93cd06.png)

**Identify** 
![screenshot from 2017-09-28 11-54-29](https://user-images.githubusercontent.com/19175505/30960607-d06b37ca-a443-11e7-96d5-db1230eb95e1.png)

**Comment by tdipisa** [comment]
We are reviewing the entire MS's layout (closed in favor of #4254).
