### ISSUE TITLE
Feature grid doesn't show boolean values

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2234]
to reproduce:
- open a layer with boolean attribute in the feature grid
- the column seems empty (every cell)
- filter the column with false or true
- the number of features doesn't change

Instead advanced filter returns the correct number of features  based on the value.

**Comment by MV88** [comment]
See https://github.com/adazzle/react-data-grid/issues/882

**Comment by MV88** [comment]
To reproduce this:
- open a new map
- add lhtac:web2014all_mv layer which contains some boolean attributes like (intersection_related)
- open feature grid, active sync
- Write in the quick filter input field any value between (t, tr, tru, true, f, fa, fal, fals, false) to filter the attribute
- at this point:
  - rows are not filtered and all of them are shown in the grid and none in the map
![image](https://user-images.githubusercontent.com/11991428/33067322-1372cdf0-ceae-11e7-9366-3f029993a500.png)
------
  - the column is empty, nothing is shown 
![image](https://user-images.githubusercontent.com/11991428/33067286-f944b06a-cead-11e7-9900-5b244af2e7d6.png)

**Comment by chiaracurcio** [comment]
ok for this fix (correct for the previous example gived: **quick filter** and using also the **Attribute Filter**)
but only one problem still occurs when the **Layer filter** is applied, i give you this absurdly example: 
- open the same map with this layer: lhtac:web2014all_mv layer
- open the featureGrid and the advanced search
- filter by layer as in the following picture
![layer_filter](https://user-images.githubusercontent.com/33256901/34053186-0a430b66-e1c6-11e7-9a65-0b5bc9326ec7.JPG)
- verify that none values fit this request
- now  active sync map with filter and note that nothing happens (see the illustration below)
![layer_filter1](https://user-images.githubusercontent.com/33256901/34053265-6844d424-e1c6-11e7-8ac4-4f67b23aa2d1.JPG)

expected result: no feature are also shown on map
