### ISSUE TITLE
No information on account info

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2238]
There aren't account information by clicking on account info button
![screenshot from 2017-09-28 14-22-12](https://user-images.githubusercontent.com/19175505/30966224-7e9777dc-a458-11e7-8ac7-446a7a062dd1.png)

![screenshot from 2017-09-28 12-57-22](https://user-images.githubusercontent.com/19175505/30963123-9b48b686-a44c-11e7-8b05-7d7ac25d32c0.png)

**Comment by allyoucanmap** [comment]
Preview of user details modal:

![modal-user](https://user-images.githubusercontent.com/19175505/33936608-6a77e9e2-e000-11e7-9061-9556f230b95b.png)

**Comment by offtherailz** [comment]
Some notes/questions
 - [ ] No attributes? 
 - [ ] Groups can be many, should we show them? 
 - [ ] Everyone is applied to everyone, should we show it.
