### ISSUE TITLE
Recognize editing error due to missing primary key

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2241]
Many times db-admins forget to set primary keys. This sometimes causes problems with WFS and WFS-T (in GeoServer). 
 - Pagination is not allowed without explicit sort attribute
 - In oracle you can not write using WFS-T if the p-key is not set

With the pagination issue MapStore already catches the error and retries with the first attribute as sort attribute.
Unfortunately the write errors are not so explicit. But MapStore can catch the previous error (pagination issue, that is more explicit) to risa a flag.
If a WFS-T save error happens on the feature that raised the sorting error flag with p-key, most probably the problem is the same. So the notification can be more specific. Something like: 
> Error saving. Probably the problem is due to a missing primary-key. Contact the administrator reporting this error

**Comment by tdipisa** [comment]
closed for inactivity.
