### ISSUE TITLE
mapTypeSelector used in BackgroundSelector plugin depends on MapType plugin state witch is only available in the product (not on custom projects)

### ISSUE THREAD

**Issue by ndufrane** [geosolutions-it/MapStore2#2242]
Hi,

On a custom project (made by create project script), who is using BackgroundSelectorPlugin and openlayer as map. The mapTypeSelector return the default leaflet as maptype -> https://github.com/geosolutions-it/MapStore2/blob/master/web/client/selectors/maptype.js#L15 because maptype is not in the state.  Causing wms background layers to be invalidated.

state.maptype.mapType seems (if i am not wrong) to be in the state only when product plugin "maptype" is loaded. It is not always the case if the project is only using one map provider. https://github.com/geosolutions-it/MapStore2/blob/master/web/client/product/plugins/MapType.jsx#L65

Regards,

**Comment by mbarto** [comment]
Have you tried using initialState in localConfig.json to initialize mapType to openlayers?

Something like:

```
"initialState": {
   "defaultState": {
      ...
      "mapType": {
          "mapType": "openlayers"
      }
      ...
   }
}
```

should work

**Comment by ndufrane** [comment]
Hi,

Thanks a lot for the reply. But i have already tried to set the mapType in the initialstate. Making this modification throw the following error 

`Unexpected key "mapType" found in previous state received by the reducer. Expected to find one of the known reducer keys instead: "localConfig", "locale", "browser", "controls", "help", "map", "mapInitialConfig", "layers", "mousePosition", "print", "queryform", "query", "measurement", "draw", "highlight", "search", "mapInfo", "locate", "catalog", "brugisTree", "localMaps", "tutorial", "brugisSurvey". Unexpected keys will be ignored.`

**Comment by mbarto** [comment]
You are right. I think the right approach is to include the mapType reducer in app.jsx as we do for the standard product.

Have a look here: https://github.com/geosolutions-it/MapStore2/blob/master/web/client/product/app.jsx#L27

**Comment by ndufrane** [comment]
Great, it works indeed. Thanks :smile:
