### ISSUE TITLE
Duplicated slider component on layers and opacity support

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2250]
questions from @offtherailz  issue #2212 
Now we have opacity slider in TOC and layer settings.

> Does it make sense to leave them together for the moment?

> Display and support opacity for annotation or remove it for certain types of layers? which types?

![image](https://user-images.githubusercontent.com/1279510/31008386-3cc8cd0e-a504-11e7-8d93-b75aa88b507f.png)

**Comment by tdipisa** [comment]
@allyoucanmap, in my opinion the opacity slider in Display tab should be removed. In case of annotations or layers without other Display settings like Format, the display tab should be hidden I think. @simboss @offtherailz @mbarto what do you think?

**Comment by simboss** [comment]
I agree with Tobia.

Generally speaking, there should always be a single way to do things. At most we could have a simple immediate way and a more complex way. In this case we have to path to do the exact same thing with a slight different Look&fell; the result of such an approach is usually end-user confusion.
