### ISSUE TITLE
MetadataExplorer breaks when mounted to burgermenu

### ISSUE THREAD

**Issue by Retiefasaurus** [geosolutions-it/MapStore2#2254]
Hello

If the MetadataExplorer plugin is contained within the burger menu and toggled it crashes the application. The problem seems to be coming from react-container-dimensions. If the ContainerDimensions component is removed from the MetadataExplorerComponent the plugin seems to be working fine.
![mapstore2metadata](https://user-images.githubusercontent.com/20558205/31117225-627a6756-a829-11e7-9e6b-042c2fbcf41c.png)

**Comment by MV88** [comment]
Can you open a thread in the mailing list and provide there also the errors present in the console?
Here you can find the [link](https://groups.google.com/forum/#!forum/mapstore-users)
Which release are you using?

**Comment by Retiefasaurus** [comment]
@MV88 Thank you for the response and you are welcome.

I created a new post on the mailing list 
[https://groups.google.com/forum/#!topic/mapstore-users/YuxOhZktVDw](url)

**Comment by tdipisa** [comment]
closed for inactivity.
