### ISSUE TITLE
Define an API for Annotations

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#2256]
We should introduce an API to interact with annotations:
 * integrated into the existing JS API
 * also usable through urls for simple use cases

The API should allow:
 * creating permalinks to maps, zooming / showing a specific annotation
 * injecting annotations on the map from the url (single annotation) or the JS API (full GeoJSON)
 * interacting with annotations (e.g. simple style change from url, more complex interactions from the JS API)

**Comment by tdipisa** [comment]
closed for inactivity.
