### ISSUE TITLE
MapStore2 default categories in custom projects are wrong

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#2265]
This is an issue with projects using MapStore2.
Using an empty database, MapStore2 creates "cat1" and "cat2" categories instead of all the needed ones.  
MAP
THUMBNAIL

**Comment by mbarto** [comment]
This file should do the job https://github.com/geosolutions-it/MapStore2/blob/master/web/src/main/resources/sample_categories.xml

Isn't it included in final war?

**Comment by Gnafu** [comment]
Right, the issue is with projects using MapStore2.
I'll update the description
