### ISSUE TITLE
Some maps doesn't work

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#227]
The following mapId on the demo give a blank screen in the viewer: 
* 451
* 461
* 464
* 467
* 476

**Comment by kappu72** [comment]
They works in ol but not in leaflet investigation to be continued!

**Comment by kappu72** [comment]
Investigated 461, this layer configuration crash the app 
{"source":"ol","title":"None","visibility":false,"opacity":1,"group":"background","fixed":true,"selected":false,"type":"OpenLayers.Layer","args":["None",{"visibility":false}]}
type OpenLayers.Layer dosen't exist in Leaflet layer plugin.
If you remove the app starts to show the toolbar and an empty map this is because of other layer are missing type configuration property and at least one background layer should be visible.

**Comment by offtherailz** [comment]
OpenLayers.Layer is the old version of a blank background. In the past the
maps was working. I think is an error in the middle of the layer rendering
process (react side). We should support old maps , so we should avoid this
error.

2015-10-14 16:50 GMT+02:00 Andrea <notifications@github.com>:

> Investigated 461, this layer configuration crash the app
>
> {"source":"ol","title":"None","visibility":false,"opacity":1,"group":"background","fixed":true,"selected":false,"type":"OpenLayers.Layer","args":["None",{"visibility":false}]}
> type OpenLayers.Layer dosen't exist in Leaflet layer plugin.
> If you remove the app starts to show the toolbar and an empty map this is
> because of other layer are missing type configuration property and at least
> one background layer should be visible.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geosolutions-it/MapStore2/issues/227#issuecomment-148073836>
> .
>



-- 


Regards,
Lorenzo Natali

==
GeoServer Professional Services from the experts! Visit
http://goo.gl/it488V for more information.

==

Dott. Ing. Lorenzo Natali
Software Engineer

GeoSolutions S.A.S.
Via Poggio alle Viti 1187
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39  333 8128928

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

*AVVERTENZE AI SENSI DEL D.Lgs. 196/2003*

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.



The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

**Comment by kappu72** [comment]
Thanks Lore, you are right i have fixed
