### ISSUE TITLE
Localization error in TOC

### ISSUE THREAD

**Issue by dracic** [geosolutions-it/MapStore2#2276]
'Filter layers' at the top of the TOC doesn't translate:

![screenshot_20171009_180329](https://user-images.githubusercontent.com/4533263/31347364-6759c512-ad1c-11e7-9d8d-1703b724f4ca.png)

**Comment by dracic** [comment]
Sorry for the mess, this pull request wasn't supposed to be saved...

**Comment by MV88** [comment]
yes, there is an hardcoded string.
We accept PR if you want to contribute.

**Comment by dracic** [comment]
I tried as you suggested, but now I'm getting [object Object] in the control. Also the "Clear filter" tooltip message doesn't translate despite having

`filterTooltipClear={<Message msgId="toc.clearFilter" />}`

![screenshot_20171010_211618](https://user-images.githubusercontent.com/4533263/31406285-1dbccb8a-ae01-11e7-8d8b-019d5c9c05b3.png)

I just started digging through Mapstore2, need some more time with it and React in general....

**Comment by mbarto** [comment]
Hi Davor, unfortunately the Message component cannot be used everywhere. This is one of the cases where only a string (not a component) is accepted.
In these cases you have to use LocaleUtils.getMessageById(...).
There are many examples in the code (e.g. here: https://github.com/geosolutions-it/MapStore2/blob/f1f9a271ebce3c1719ee94ef1fc0d57166f8139f/web/client/components/style/RasterStyleTypePicker.jsx#L30).

Also remeber to add context if it's not already defined in the component:

```
static contextTypes = {
        messages: PropTypes.object
};
```

**Comment by chiaracurcio** [comment]
Note that also the "Clear filter" tooltip message doesn't translate if Deutsch and Espanol languages are selected
