### ISSUE TITLE
OL Feature Info marker disappear on second click

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2284]
FeatureInfo with OpenLayers map changes marker on second click. 

### Steps to reproduce: 
 - Open an OpenLayers map (with at least one layer)
 - Enable feature info tool
 - Click on the map. You see the marker
 - Click again in another point. Now you see a red circle instead of marker

**Comment by Gnafu** [comment]
Fixed in QA-2017.05.00
