### ISSUE TITLE
Allow customization of GetFeatureInfo visualization per layer

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2285]
A user should be able to customize the feature info visualization tool. 
This should be available from the layer properties, in a new tab called "Feature Info".
Initially we will provide this functionality only for WMS layers. 
For WMS layers, the list of available viewer should be:
 - HTML 
 - Text
 - Properties
 - Table

This list have to be extensible because in the future we could add other options. (i.e. a custom templates)
Custom application should be able to register their own viewer for their specific purpose.

**Comment by chiaracurcio** [comment]
These 4 options are not available, now i can see only 3  viewer: TEST, HTML and JSON (see the screenshot below).

A new scenario is available in hiptest to test the feature info tab:
see folder TOC, scenario: TEST 2285 - Feature Info

![2285_FEATURE_INFO.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f8802bba0b5e001143f95b/125516c66e82c728ace21e0d46bac6c276bda58caedd8a718162d9ba0f69653f6b14b1247a80e03cfd1839545a091ffd4709564cfbfa892da2b535708a580cbbd7385966da2f53fde6d640e258f075c95d8fa4be8a46c1ed3d2ce1888c463a1605118eed10.jpg)

**Comment by offtherailz** [comment]
Thanks @chiaracurcio The table format was not a strict requirement, but only an example. I'm going to remove the table from the issue definition to make it more clear.
BTW you can link tests to the issues using the badge.
![image](https://user-images.githubusercontent.com/1279510/32500921-01ec4d18-c3d7-11e7-8787-183ffc60f644.png)
I suggest this way to link issue, avoiding issue number in the title too. It can be confusing and difficoult to maintain. @Gnafu do you agree or do you have more suggestion about testing procedure?

[![Hiptest Status](https://hiptest.net/badges/scenario/1268889)](https://hiptest.net/app/projects/48097/test-plan/folders/316443/scenarios/1268889)
