### ISSUE TITLE
Infinite loop triggered by MapInfo errors

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2289]
I tried to blindly require('../MapInfoUtils') in `../mapinfo/wms` from [this pull request](https://github.com/geosolutions-it/MapStore2/pull/2286) code. Because of the missing function you get an error in build request. You can replicate this by throwing an exception in buildRequest (editing the code).

An error in buildRequest creates an infinite loop of actions because every render triggers this: 
https://github.com/geosolutions-it/MapStore2/blob/2698577c0770d9fd23cdb9cc3fe9fa51a8324cd0/web/client/components/data/identify/Identify.jsx#L127
This loop happens because a re-render is triggered by annotations epic that catch every purge, and the re-render triggers purge because the props didn't change. 
https://github.com/geosolutions-it/MapStore2/blob/2698577c0770d9fd23cdb9cc3fe9fa51a8324cd0/web/client/epics/annotations.js#L152

This may be caused on every unknown error triggered during getFeautreInfo. 
We should refactor how identify works, using epics, to prevent this issue. @mbarto can you find an easier solution to this?

**Comment by tdipisa** [comment]
closed for inactivity
