### ISSUE TITLE
Support for editing in geometry-less layers

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2293]
To support editing of geometry-less features we should : 
 - [ ] improve featuregrid to disable geometry editing and proper avoid errors. [Work in progress here](https://github.com/offtherailz/MapStore2/tree/geometryless_support)
 - [ ] Enable the grid tool in TOC even if the layer errored per-se (actually auto-disable hides FG button)

**Comment by tdipisa** [comment]
closed for inactivity
