### ISSUE TITLE
Map changes are lost on login

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#2306]
On the previous release an user could:
- Access MapStore2 as anonymous user
- Open a public map
- Add/remove layers
- Login
- Save as a new map

Currently this is not possible because when a user logs in from an open map, that map reloads, lossing any change made in the meanwhile.

Is this by design?

**Comment by MV88** [comment]
I would say yes. this was implemented in order to fix the cases described [here](https://github.com/geosolutions-it/MapStore2/issues/2036)

**Comment by Gnafu** [comment]
If the map is not public, the user does not have any tool to view anything on the map, so it has nothing to save.
The (maybe unintentional) feature I'm talking about was particularly helpful for someone that uses MapStore2 on a daily basis.

If an anonymous user cannot save the changes he makes, it should be warned and/or asked to login before editing.

**Comment by MV88** [comment]
Let's restore the previous behaviour for public maps
