### ISSUE TITLE
Wrong zoom in print preview

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2319]
When open the print window the preview has not the correct zoom. Present on Dev. Not in QA.
Printed document has the main map bounding box (not the preview's one). 

### steps to reproduce
 - Open a map
 - Open the print preview

![iss](https://user-images.githubusercontent.com/1279510/31884580-e13a2fb2-b7ed-11e7-800c-e94c5b936750.gif)

**Comment by mbarto** [comment]
Is this merged on master?

https://github.com/geosolutions-it/MapStore2/commit/016a4b2b155de4be0593ce0f96153890d53e0efe

**Comment by offtherailz** [comment]
Uh, sorry,I didn't noticed it was an issue that have to be ported on master, my fault. let's check again when the release is completed.

**Comment by offtherailz** [comment]
Now it works, going to close
