### ISSUE TITLE
Create some more examples

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#232]
We need some more examples to show in the home page gallery: also remove the mapmanager examples (already available in home).
Some suggestions:
 * [x] custom layertree (with both layers and backgrounds)
 * [x] custom mouseposition template
 * [x] custom scalecombo templates

**Comment by offtherailz** [comment]
We should use the viewer with different configuration or isolated examples
in different subfolders?

Il giorno gio 15 ott 2015 alle ore 12:01 mbarto <notifications@github.com>
ha scritto:

**Comment by mbarto** [comment]
I would go for the second option

**Comment by kappu72** [comment]
Mauro, we have done custom layertree, mouseposition and scalecombo, so if we don't want more examples this issue is closed.

**Comment by mbarto** [comment]
Yes, please, close the issue.

Mauro
Il 30/ott/2015 15:25, "Andrea" <notifications@github.com> ha scritto:
