### ISSUE TITLE
Custom WMTS gridsets are not supported

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#2322]
Layers using a custom gridset are incorrectly displayed on the map, even if the gridset information is available in the GetCapabilities document.

To reproduce:
 - Open a map
 - Open the catalog
 - Select the GeoSolutions DEMO WMTS service
 - Search for tasmania_test layer and add it to the map

Expected result: the Tasmania polygons are placed south of Australia, with the correct size.

Actual result: the Tasmania polygons are displayed spanning from Canada to Antarctica.

The tasmania_test layer is set to have a custom gridset with a boundary smaller than the projection maximum bounds.

**Comment by allyoucanmap** [comment]
Question in PR:

> About tasmania_test:
> I tried this fix with another custom grid set and the world grid set and it works with both (right position and size).
> I noticed also an issue with the same layer in WMS (tasmania_test).
> Could it be that the gridset isn't configured correctly?
> Could it be that on high scale denominator there's a loss of precision in the gridset pyramid?
> 
> About last question I noticed that at small scale denominator the precision increases.
