### ISSUE TITLE
Shapefile Import display objects with an offset

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#2325]
Importing a shapefile will result in misplaced features on the map.

See below the same ShapeFiles imported in QGIS and MapStore2:

![2017-10-24_1008](https://user-images.githubusercontent.com/3932165/31934195-bf5d60f8-b8ab-11e7-8f5e-bd8c54b2a7c3.jpg)
![2017-10-24_1009](https://user-images.githubusercontent.com/3932165/31934196-bff50f66-b8ab-11e7-9179-c6d5860a07a0.jpg)
![2017-10-24_1016](https://user-images.githubusercontent.com/3932165/31934197-c0121a98-b8ab-11e7-95e1-a46b83ffdf6d.jpg)
![2017-10-24_1017](https://user-images.githubusercontent.com/3932165/31934198-c0390b3a-b8ab-11e7-979f-992e7e8c4eae.jpg)

This is the same shapefile exposed by GeoServer via WMS (grey) and imported in MapStore2 (blue):

![2017-10-24_1054](https://user-images.githubusercontent.com/3932165/31934282-f2337454-b8ab-11e7-9928-ab838be6ed48.png)

Maybe related to #2175 and #1307

**Comment by MV88** [comment]
Hi @Gnafu , Can you add the shapefile ypou have used to this issue?

**Comment by Gnafu** [comment]
http://demo.geo-solutions.it:80/geoserver/test/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=test:Linea_costa&maxFeatures=1000&outputFormat=SHAPE-ZIP

**Comment by mbarto** [comment]
proj4js wkt parser ignores towgs84 params. I will prepare a PR for proj4js to fix it.

**Comment by mbarto** [comment]
https://github.com/proj4js/wkt-parser/pull/6
