### ISSUE TITLE
Button visibility of TOC's toolbar based on layer/group properties + replace toolbar component

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2333]
We should use the standard toolbar component (misc folder) and add a selector to set the button visibility.
About selector see 7a48eed

**Comment by allyoucanmap** [comment]
Update:
This improvement was required in C111 project were some layers needed to be unremovable so some leyers didn't show remove button when selected.
The commit linked  in the description of the issue show how it was implemented in that particular case.
Probably we could find a better solutions to hide buttons because in most of the cases they are related to plugins see https://github.com/geosolutions-it/MapStore2/issues/2759.

The replace of Toolbar is not required but probably needed to have a pluggable toolbar.

**Comment by tdipisa** [comment]
We are reviewing the entire MS's layout (closed in favor of #4254).
