### ISSUE TITLE
Implement Permalink support

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#2336]
Implement a new Page for permalink support.
The link should:
 - open a specific map
 - zoom to a specific object (e.g. annotation)

Implement permalink creation tool from annotations.

**Comment by arp43b** [comment]
Hello, I need to be able to pass an element of the map to zoom by parameter url. Could this feature be implemented in this case?
Thank you very much

**Comment by tdipisa** [comment]
Support for URL actions have been inclused in v2019.03.00, doc [here](https://mapstore.readthedocs.io/en/latest/developer-guide/map-query-parameters/)
