### ISSUE TITLE
Improve catalog loading spinner

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2344]
We should improve the loading phase of catalog, the spinner on button is not visible and it's difficult to understand if the request has been sent.
Update:
Sometimes the capabilities are too heavy (e.g. wmts with gridsets) and the parsing phase is longer than expected, that causes the end of loading with the results page still empty.

**Comment by kasongoyo** [comment]
@allyoucanmap do you suggest that we track the progress of the capability parsing? I have tried to  select WMTS several times and the experience is just like on the other capabilities. i.e the result shows up immediately after response.
