### ISSUE TITLE
Single layer getCapabilites for layergroup return 404 Not Found error

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#2365]
### Description
When the layer properties of a layergroup is opened a getcapabilites to the single layers is performed returning a 404 Not Found error. This can be related to geofence.

Note: i was logged in as ADMIN
In this case if the description was missing it is not fetched due to this error
If then i go to the style tab an error appears.

### Please indicate if this issue is related to a bug or a new feature request
- [x] Bug

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*
Chrome 61.0.3163.100

*Steps to reproduce*
- Open the layer properties of a layergroup for which the description was missing

*Expected Result*
The Description should appear in the textarea if present on geoserver

*Current Result*
An empty field appear on the description
You can find in console under Network an error for the getCapabilities request.

### Other useful information (optional):
layer used  SITGEO:ROLLI_GEOPORT
here is part of the log of geoserver
```
2017-11-06 17:37:32,489 DEBUG [org.geoserver.geofence] - Admin level access, returning full rights for workspace SITGEO
2017-11-06 17:37:32,489 TRACE [org.geoserver.ows.OWSHandlerMapping] - No handler mapping found for [/SITGEO/ROLLI_GEOPORT/wms]
```

**Comment by tdipisa** [comment]
closed for inactivity
