### ISSUE TITLE
change the JSON label in feature info visualization tool

### ISSUE THREAD

**Issue by chiaracurcio** [geosolutions-it/MapStore2#2370]
![2285_feature_info](https://user-images.githubusercontent.com/33256901/32550255-bad0aa30-c48c-11e7-97fa-8664e9c22cf6.jpg)
### Description
The label JSON in the new tab "Feature Info" is unclear for a non-expert user.

### Please indicate if this issue is related to a bug or a new feature request
- [ ] Bug
- [x] New Feature

### In case of New Feature 
*Acceptance Criteria - AC*
could be useful replace the label JSON with this other "Properties"

**Comment by MV88** [comment]
So the list will become:
HTML
TEXT
PROPERTIES
 or
Html
Text
Properties
