### ISSUE TITLE
Autocomplete in Data Editor -  date-time picker in data field not available

### ISSUE THREAD

**Issue by chiaracurcio** [geosolutions-it/MapStore2#2377]
### Description
When autocomplete in Data Editor is present (in case of data field) the date-time picker in data field is not available

### Please indicate if this issue is related to a bug or a new feature request
- [ ] Bug
- [x] New Feature

### In case of New Feature
*Acceptance Criteria - AC*
- the date-time picker allows you to choose the data in the correct format accepted

### Other useful information
*Steps to reproduce*
double click in the data field

![data](https://user-images.githubusercontent.com/33256901/32663411-2a004c24-c62e-11e7-98a5-622a3c152b3a.JPG)

**Comment by tdipisa** [comment]
This issue is out of date, feature  has been implemented in 2019.02.00
