### ISSUE TITLE
Validate url of catalog services

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2384]
### Description
When add/edit catalog services could be useful to recognize the type (CSW/WMS/WMTS) with a regex and change it automatically or show a notification.

### Depends On (optional)
 - A list of other involved issues (with link)
 - ...

### Please indicate if this issue is related to a bug or a new feature request
- [x] New Feature

### In case of New Feature (otherwise remove this paragraph)

*Acceptance Criteria - AC*

- recognize service type from url
- show an alert with a warning text about mismatch of type and url
- or/and switch to the correct type

**Comment by tdipisa** [comment]
Closed for inactivity, this issue is out of date.
