### ISSUE TITLE
Print plugin does not update the preview after change locale

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2385]
### Description
When language has been changed and the print preview is still open, the title doesn't change

### Depends On (optional)
 - #2374

### Please indicate if this issue is related to a bug or a new feature request
- [x] Bug

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Browser Version Affected*

- all

*Steps to reproduce*

- open a map with a layer
- verify if the layar has title with translation (if not add translations from layer settings)
- open print plugin from burger menu
- add legend from print settings
- print
- verify that the preview is correct with the legend
- leave the print plugin open and go to the settings from burger menu
- change language

*Expected Result*

- preview updates the titles in legend

*Current Result*

- the preview doesn't update the title in legend

**Comment by tdipisa** [comment]
fixed in 2018.02.00
