### ISSUE TITLE
Spatial selection in Query tool

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#2389]
### Description
When the user perform a spatial search the area selection should be maintained in the map.

### Please indicate if this issue is related to a bug or a new feature request
- [x] New Feature

### In case of New Feature

*Acceptance Criteria - AC*

- After the spatial search the selection should not be removed from the map

**Comment by kappu72** [comment]
So, when we have to remove?

**Comment by tdipisa** [comment]
@kappu72 I'm going to close this issue. The user have the ability to see the filtered features  in the map using the 'sync map' functionality. The the spatial filter selection is currently shown again when the user reopen the query tool, this is enough in our opinion.
