### ISSUE TITLE
Query tool state

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#2390]
### Description
Evaluate the possibility to maintain the query tool state until a new layer is selected in TOC.
Currently, after performing a search, the query tool state is reset if the user close the feature grid, open the TOC or performs other operations.

### Please indicate if this issue is related to a bug or a new feature request
- [x] New Feature

### In case of New Feature

*Acceptance Criteria - AC*

- The state of the query panel should be maintained after a search until a new layer is selected in TOC

**Comment by kappu72** [comment]
Should not be the query's state saved per layer or directly in the query's state?
In this way a user could filter different layer at same time

**Comment by tdipisa** [comment]
@kappu72 yes we can do that, also in my opinion that's probably the best way. However we cannot allow persistence for the filter's state per layer because the size of the map context  could increase too much.

**Comment by kappu72** [comment]
I'll wait for a pull from @offtherailz that partially overlap this issue

**Comment by offtherailz** [comment]
@kappu72 the pull request has been merged, you can continue on that.
