### ISSUE TITLE
Virtual scrolling in Feature Grid

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#2391]
### Description
Improve the Feature Grid component with virtual scrolling instead of the standard pagination.

### Please indicate if this issue is related to a bug or a new feature request
- [x] New Feature

### In case of New Feature

*Acceptance Criteria - AC*

- Enable virtual scrolling in Feature Grid for navigating features

**Comment by kappu72** [comment]
@tdipisa  So we have to eliminate the pagination from the Ui but we have  to use in features fetching. 
I guess we have to decide some prefetching strategy to avoid ugly effects during user scroll. We also have to shows some loader.
