### ISSUE TITLE
FeatureInfo results window fails to show the results in some cases

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#2395]
### Description
FeatureInfo results window fails to show the results in some cases

- [x] Bug
- [ ] New Feature

*Browser Affected*
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Browser Version Affected*

- All

*Steps to reproduce*

- Open this map http://mapstore2.geo-solutions.it/mapstore/#/viewer/leaflet/2940
- Click on the featureinfo tool (button in the bottom right corner)
- Click on a the orange areas (in the atlantic ocean)
- Wait for the featureinfo window to come up
- Click on the arrow on the right
- Click on the dark blue areas in the pacific ocean

*Expected Result*

- The FeatureInfo window should display the informations about the clicked point

*Current Result*

- It shows a message saying that no info is available

![video_2017-11-13_233035](https://user-images.githubusercontent.com/3932165/32827939-0790784e-c9ee-11e7-88ba-78f23a473f9b.gif)

**Comment by tdipisa** [comment]
closed for inactivity.
