### ISSUE TITLE
Leaflet WMS sends some unwanted querystring parameters

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2398]
### Description
Leaflet sends some internal parameters in WMS request. 

### Please indicate if this issue is related to a bug or a new feature request
- [x] Bug
- [ ] New Feature

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

any version

*Steps to reproduce*
- open http://dev.mapstore2.geo-solutions.it/#/viewer/leaflet/3230
- see wms requests in the developers tool

*Expected Result*
- WMS requests have only the valid and/or vendor parameters.
- Describe here the expected result 

*Current Result*
You can see some parameters in the request like: 
ZINDEX:5
SRS:EPSG:3857
CRS:EPSG:3857

**Comment by tdipisa** [comment]
closed for inactivity
