### ISSUE TITLE
Add documentation to configure MapStore2

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2400]
### Description
As a sysadmin/devop that want to install and configure MapStore2, I want to have a page that helps me to configure the initialState and links to the various plugins configuration. 

The documentation should contain some common configuration hits, typically to fix mapTypes.
Other things can be how to setup UOM of the tools, add projections and so on. 

Another useful thing is to show a screenshot of the home page and the map to display visually what the various plugins are, like this: 

![image](https://user-images.githubusercontent.com/1279510/32884878-0ef09834-cabc-11e7-9c57-9bf23a44442d.png)

### Please indicate if this issue is related to a bug or a new feature request
- [ ] Bug
- [x] New Feature

### In case of New Feature (otherwise remove this paragraph)

*Acceptance Criteria - AC*

- Documentation should allow a sysadmin to configure some common cases:
  - set maptype
  - set units of measure
  - set additional projections
  - set default and available languages
  - add/remove plugins
  - how to integrate security with GeoServer
  - ... (any suggestion welcome)

**Comment by tdipisa** [comment]
We need to improve Js documentation of plagins, this issue is out of date. We can refere #2305 for this
