### ISSUE TITLE
Improve consistency of filter created for feature editor

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#2408]
### Description
Actually the filter (attribute and/or a spatial) created in the query panel and is overridden by the filters created in the quick filter. We should take the two filters and put them in AND condition.

### Please indicate if this issue is related to a bug or a new feature request
- [x] New Feature

### In case of New Feature (otherwise remove this paragraph)
*Acceptance Criteria - AC*

- open this [map](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/leaflet/1740)
- create a filter in the query form like this
![image](https://user-images.githubusercontent.com/11991428/32941489-42517192-cb86-11e7-9f20-34bf9dddfd6b.png)
- search for result and actyvate the synch tool.
the map should appear as this
![image](https://user-images.githubusercontent.com/11991428/32941614-a38d7064-cb86-11e7-866d-37d7dbce160e.png)
- now write a k under STATE_NAME
![image](https://user-images.githubusercontent.com/11991428/32941651-c04c7e52-cb86-11e7-8087-5d52654f492f.png)
- the map is something like this
![image](https://user-images.githubusercontent.com/11991428/32941669-cd61536a-cb86-11e7-83fd-362022eda047.png)
- **but** it should be a combination of the two filters. (it should show onlly the one that have a k and a la in the name)

**Comment by tdipisa** [comment]
This issues has already been fixed in 2018.02.01
