### ISSUE TITLE
Travis build should check also "compile"

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2409]
### Description
Now travis build runs only tests but not full application compilation. We could improve it adding the "npm run compile" to ensure that it works and avoid possible compilation issues in the final application. 

### Please indicate if this issue is related to a bug or a new feature request
- [ ] Bug
- [x] New Feature

### Acceptance Criteria - AC*

- Travis build should block any compilation error for Javascript
- Check also mvn build is a plus

**Comment by tdipisa** [comment]
closed for inactivity.
