### ISSUE TITLE
Re-design language selector tool for managing a great number of languages

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#2414]
### Description
Settings panel manages at most 7 languages per row. 
We should tranform it into a dropdown.
![image](https://user-images.githubusercontent.com/11991428/33020671-5f08eb0a-cdff-11e7-88f4-c9ba9c4b0c2f.png)

Some changes need to be done also for the home.
### Please indicate if this issue is related to a bug or a new feature request
- [x] Bug

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*
Chrome 62.0.3202.94

*Steps to reproduce*
- add in configuration more than 8 languages with at least the relative flag

*Expected Result*
A dropdown should appear

*Current Result*
Some flags goes to a new line
![image](https://user-images.githubusercontent.com/11991428/33020943-61484f7c-ce00-11e7-992e-b819dc3b1c0e.png)

### Other useful information (optional):
We could add the flag and the label in the drodown list, or just only the labels

**Comment by tdipisa** [comment]
closed for inactivity
