### ISSUE TITLE
Fix waffle bot interaction with PRs

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#2417]
### Description
When i create a PR at the moment wafflebot adds these labels:
![image](https://user-images.githubusercontent.com/11991428/33069636-73756350-ceb5-11e7-89a0-7840472918d0.png)
while it is enough the "pending review" label

### Please indicate if this issue is related to a bug or a new feature request
- [x] New Feature

### In case of New Feature (otherwise remove this paragraph)

*Acceptance Criteria - AC*

- When creating a PR it should add only "pending review" label and move it under the pending review column in the kanban

**Comment by tdipisa** [comment]
not needed after latest kanban updates
