### ISSUE TITLE
Get feature info doesn't scroll horizontally when width of responses table is greater than container (mobile)

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2430]
### Description
This should be due to some conflicts on touch events.

### Depends On (optional)
 - A list of other involved issues (with link)
 - ...

### Please indicate if this issue is related to a bug or a new feature request
- [x] Bug

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Chrome v.62

*Steps to reproduce*

- Open MapStore on mobile device
- Open the map 356
- Change the response format of Get Feature Info to HTML (from settings)
- Click on a place crowded of points on the map
- The response will show the right arrow available
- Try to scroll horizontally on the HTML table

*Expected Result*

- The table scrolls horizontally without change page

*Current Result*

- The table changes page

**Comment by tdipisa** [comment]
It seems to be fixed in latest releases, please retest.
