### ISSUE TITLE
Still a default Leaflet map if you open a New Map

### ISSUE THREAD

**Issue by chiaracurcio** [geosolutions-it/MapStore2#2435]
### Description
If you open a New Map in Mapstore 2 you still open a leaflet map (even though you change the "Select Map Viewer" the new map is still a Leaflet map).
To work around that problem you can modify the link of the new map created from "https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/leaflet/new" to "https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/new" and reload the page.

### Please indicate if this issue is related to a bug or a new feature request
- [x] Bug
- [ ] New Feature

*Browser Affected*
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [ ] Safari

*Browser Version Affected*
All.

*Steps to reproduce*
- Modify the Select Map Viewer from "Leaflet" to "OpenLayers"
- open a new map.

*Expected Result*
- The new map has a OpenLayer viewer if "OpenLayers" is selected.

*Current Result*
- The new map is still a Leaflet map even through "OpenLayers" is selected

**Comment by MV88** [comment]
For completeness this happens also if you select cesium and then create a new map
