### ISSUE TITLE
One only feature highlighted in map but more feature selected in table

### ISSUE THREAD

**Issue by chiaracurcio** [geosolutions-it/MapStore2#2447]
### Description
Selecting more than one One only feature highlighted in map but more feature selected in table

### Please indicate if this issue is related to a bug or a new feature request
- [x] Bug
- [ ] New Feature

### In case of Bug
*Browser Affected*
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [ ] Safari

*Steps to reproduce*
- in edit mode single click on the first row, the checkbox is checked in this way and 1 feature is highlighted in map
- click on the checkbox of another row (both the rows are selected in table), now none features are highlighted in map
- click on the checkbox to cancel one selection and note that one feature is now highlighted in map

*Expected Result*
- both features are highlighted in map

*Current Result*
- only if one feature is selected in map, you can see the one highlighted feature in map, if 2 features (or more) are selected, none features are highlighted in map
![multiselection](https://user-images.githubusercontent.com/33256901/33488961-bc6284f8-d6b2-11e7-8051-ff7064ac5d04.JPG)

**Comment by tdipisa** [comment]
closed for inactivity.
