### ISSUE TITLE
Download WFS data (KML, SHP, CSV, GML, etc.)

### ISSUE THREAD

**Issue by mricca** [geosolutions-it/MapStore2#2448]
### Description
If for a WMS layer a corresponding WFS is available the user shall be able to download the WFS data of this layer from within the map/legend. The formats available are configured in the WFS definition (GetCapabilities).

### Please indicate if this issue is related to a bug or a new feature request
- [ ] Bug
- [X] New Feature

### In case of New Feature (otherwise remove this paragraph)

*Acceptance Criteria - AC*

We will:
 - Read the list of supported formats from WFS capabilities
 - Extend format selection of from data export of feature grid
 - Allow direct download from the TOC with a custom tool
It would be important to have a list of WFS that we intend to use in order to start testing interoperability with them.

**Comment by mricca** [comment]
This is the first implementation inside feature grid download:

![wfs_download](https://user-images.githubusercontent.com/1880571/33544600-b082f304-d8db-11e7-9d4b-40ce19da135b.gif)

**Comment by mbarto** [comment]
Please introduce a couple of improvements to the fetched list:
 * recognize common formats and use a meaningfull label for them (e.g Shapefile, instead of SHAPE-ZIP)
 * recognize eventual duplicates

**Comment by mricca** [comment]
This is a fetched list:
Can someone help me about rename and filter this list? I think of a possible solution in the meantime.
```
	[
		{
			"name": "text/xml; subtype=gml/3.1.1",
			"label": "text/xml; subtype=gml/3.1.1"
		}, {
			"name": "GML2",
			"label": "GML2"
		}, {
			"name": "KML",
			"label": "KML"
		}, {
			"name": "OGR-CSV",
			"label": "OGR-CSV"
		}, {
			"name": "OGR-FileGDB",
			"label": "OGR-FileGDB"
		}, {
			"name": "OGR-GPKG",
			"label": "OGR-GPKG"
		}, {
			"name": "OGR-KML",
			"label": "OGR-KML"
		}, {
			"name": "OGR-MIF",
			"label": "OGR-MIF"
		}, {
			"name": "OGR-TAB",
			"label": "OGR-TAB"
		}, {
			"name": "SHAPE-ZIP",
			"label": "SHAPE-ZIP"
		}, {
			"name": "application/gml+xml; version=3.2",
			"label": "application/gml+xml; version=3.2"
		}, {
			"name": "application/json",
			"label": "application/json"
		}, {
			"name": "application/vnd.google-earth.kml xml",
			"label": "application/vnd.google-earth.kml xml"
		}, {
			"name": "application/vnd.google-earth.kml+xml",
			"label": "application/vnd.google-earth.kml+xml"
		}, {
			"name": "application/x-gpkg",
			"label": "application/x-gpkg"
		}, {
			"name": "csv",
			"label": "csv"
		}, {
			"name": "geopackage",
			"label": "geopackage"
		}, {
			"name": "geopkg",
			"label": "geopkg"
		}, {
			"name": "gml3",
			"label": "gml3"
		}, {
			"name": "gml32",
			"label": "gml32"
		}, {
			"name": "gpkg",
			"label": "gpkg"
		}, {
			"name": "json",
			"label": "json"
		}, {
			"name": "text/xml; subtype=gml/2.1.2",
			"label": "text/xml; subtype=gml/2.1.2"
		}, {
			"name": "text/xml; subtype=gml/3.2",
			"label": "text/xml; subtype=gml/3.2"
		}
	]
```

**Comment by mricca** [comment]
@tdipisa @allyoucanmap @offtherailz 
how can i implement the download WFS feature in the TOC?
We could add a button in the TOC Toolbar that open the Data Export panel, like the feature grid one?
Do you notice any particular problems?  Thanks.
