### ISSUE TITLE
Wrong z-index for search result, omnibar and toolbar

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2453]
### Description
Wrong z-index for search result, omnibar and toolbar. The toolbar should be below the search bar. 

![image](https://user-images.githubusercontent.com/1279510/33566874-a6ae7db2-d921-11e7-9814-21a009d89197.png)

### Please indicate if this issue is related to a bug or a new feature request
- [x] Bug
- [ ] New Feature

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Mobile android

*Steps to reproduce*

- Open a map on mobile
- Try to perform a search

*Expected Result*

- The search bar is fully visible to edit

*Current Result*

- The search bar is partially covered by the toolbar

**Comment by tdipisa** [comment]
closed for inactivity.
