### ISSUE TITLE
GetFeatureInfo sometimes window covers marker

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2457]
### Description
The GetFeatureInfo Panel partially covers the marker of the selected point. The issue is the same for Mobile and Desktop but in the first case the panel covers the bottom area of the map, in the second the right area. 

### Please indicate if this issue is related to a bug or a new feature request
- [x] Bug
- [ ] New Feature

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
any browser

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- Open map 
- Click on a feature (on right or bottom depends on desktop or mobile version)

*Expected Result*

- The map shows the panel and the marker of the clicked point

*Current Result*

- when I click on a feature in the area where the panel appears, the marker is covered by the gfi panel. 

### Other useful information (optional):
The issue conceptually similar to the highlight feature in feature grid.

**Comment by tdipisa** [comment]
Fixed in 2018.02.00
