### ISSUE TITLE
Change the spatial filter preview style

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2458]
### Description
The default style of drawing tool (yellow) is hard to see if you're working on a light background. We should evaluate to change it by default for every editing or only for spatial filter. 
MapStore 1 used yellow for editing and red for spatial filter. 

### Please indicate if this issue is related to a bug or a new feature request
- [x] New Feature

### In case of New Feature (otherwise remove this paragraph)

*Acceptance Criteria - AC*

- TBD
- ...

**Comment by tdipisa** [comment]
closed for inactivity.
