### ISSUE TITLE
During editing, allow to select an element on the map and then highlight it in the feature grid table

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2471]
### Description
Clicking on the map you should highlight the element in the feature grid table. 
This feature is very useful in edit mode, but also for the normal feature grid. 
A task like this is not easy as expected because of the pagination. 
There is not a service that provides direct information about position (e.g. index or page number) of the selected item. 
So you can not find directly the page where the selected item is present to highlight it when the user clicks on it. 
Some suggestion about possible behavior: 
 - We could provide a button that allow to select items by click. When the user clicks on the map, only the clicked item(s) is (are) visible in the feature grid, the other ones disappear. When the button is clicked again the "filter by clicked point" disappears and the feature grid back to the nomal mode.  

 - We can allow click on map (and it replaces the feature info when feature grid is open) and when the user clicks the row is highlighted only if the row is present in the current page. If the clicked item is not present in the page a notification tells the user if he wants to go to the feature. If the user tells "Yes" the featuregrid will show only the item (maybe in edit mode)

All the above solutions are only thoughts, a mock-up is needed to define the behavior 

### Acceptance Criteria - AC*
- TBD

**Comment by tdipisa** [comment]
closed for inactivity.
