### ISSUE TITLE
Error on Openlayers when WMTS with custom grid has be added from Catalog (Firefox)

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2481]
### Description
It's happens when the boundingbox of tilematrix and the one of the layers don't match.

### Please indicate if this issue is related to a bug or a new feature request
- [x] Bug

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [x] Firefox
- [ ] Safari

*Browser Version Affected*

- Firefox v.57

*Steps to reproduce*

- Open a map
- Open catalog
- Add a WMTS service that provide a layer with custom tilematrix* and layer bbox [-180, -90, 180, 90] 
- Add the layer described in the previuos step from Catalog

*Expected Result*
- Layer should be displayed on map

*Current Result*
- Map is empty and the app crashed

**Comment by tdipisa** [comment]
Should be fixed in 2018.02.02, please retest.
