### ISSUE TITLE
Some tests are particularly slow to execute

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#2488]
### Description
Some tests are particularly slow to execute

### Other useful information (optional):
This is a list of the slowest ones (>100ms):

 * trigger retrieveLayerData in componentWillReceiveProps (slow: 0.13 secs)
 * test legend img error content (slow: 0.104 secs)
 * test legend img error reload (slow: 0.103 secs)
 * test cancel on blur (slow: 0.104 secs)
 * Test FeatureGrid rendering (slow: 0.175 secs)
 * crossLayerFilter not supported (slow: 0.22 secs)
 * check if the handler for "click" event is called (slow: 0.604 secs)
 * snapshot creation (slow: 0.128 secs)
 * enables openlayers controls (slow: 1.004 secs)
 * click on feature (slow: 0.508 secs)
 * test styler select glyph (slow: 0.441 secs)
 * test autofocus on selected items (slow: 0.216 secs)
 * ChartType rendering with defaults (slow: 0.114 secs)
 * error management (slow: 0.107 secs)
 * clean highlight without layer (slow: 1.001 secs)
 * should do nothing (slow: 1.003 secs)
 * should still do nothing (slow: 1.002 secs)
 * trigger update map (slow: 1.004 secs)
 * trigger draw support on selection change with not supported geometry (slow: 1.001 secs)
 * test clear notifications on location change (slow: 0.501 secs)
 * produces the search epic (slow: 0.283 secs)
 * wfsQueryEpic stop on update query (slow: 1.001 secs)

**Comment by tdipisa** [comment]
closed for inactivity
