### ISSUE TITLE
GetFeatureInfo request without cookies causes empty feature info

### ISSUE THREAD

**Issue by kgaeb** [geosolutions-it/MapStore2#2502]
### Description
The GetFeatureInfo request from within MapStore2 doesn´t send the Cookies in the Request Headers.
We use session cookies for authorization in an external application. GetMap requests in MapStore2 are using cookies and an authenticated user is able to view layers but is not able to query an object in the map (using a GetFeatureInfo request).
Tested version: 2017.05

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
any

*Steps to reproduce*
- Open a map with some queryable layer
- Open developer tools
- Click on a feature to display the result of GetFeatureInfo
- check the Request Headers in the developer tools of the GetFeatureInfo request for cookies
- do the same for a GetMap request

*Expected Result*
GetFeatureInfo request headers should send cookies as it is done in the GetMap request

*Current Result*
GetFeatureInfo request doesn´t send any cookies

### Other useful information (optional):
GetFeatureInfo does not send Cookies to the API for GetFeatureInfo request:
![image](https://user-images.githubusercontent.com/34339627/34567118-3f4cfc22-f161-11e7-8b57-edd3a5bba713.png)

The Cookie is present for GetMap requests:
![image](https://user-images.githubusercontent.com/34339627/34567202-8869c2a0-f161-11e7-9a1c-57796c913f99.png)

**Comment by mbarto** [comment]
AJAX requests (like GetFeatureInfo) need explicit handling of authentication (while image requests are usually handled by the browser directly).

Currently we handle some authentication methods here: https://github.com/geosolutions-it/MapStore2/blob/master/web/client/libs/ajax.js#L36

It should not be that difficult to add a new **case** for cookies.

**Comment by kgaeb** [comment]
to be closed: see PR #2995

**Comment by kgaeb** [comment]
see above PR #2995
