### ISSUE TITLE
Add lines and polygons for Annotations

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#2531]
### Description
Add the possibility to add lines and polygons to a single annotation (Multi Geometry)

### AC
- You can draw multiple lines at the same time
- You can draw multiple polygons at the same time
- You can switch from the geometry types and draw with the selected type

**Comment by chiaracurcio** [comment]
note these observations:
1) when you want add a polygon, a line or a maker to an existing text annotation (for example), the second button has not the label to explain what it is , unlike the others:
![immagine](https://user-images.githubusercontent.com/33256901/36675589-bc07d12a-1b09-11e8-9851-3180505cfe51.png)
it could be for example called 'Add new geometry to annotation' as the [mockup](https://demo.geo-solutions.it/mockups/mapstore2/#/annotations) 

2) note that line and polygon type of annotations hasn't a title when you want modified them using the edit button:
![immagine](https://user-images.githubusercontent.com/33256901/36676023-dbeb04fc-1b0a-11e8-98e1-da0cb32795d3.png)

**Comment by chiaracurcio** [comment]
please look at the note above
