### ISSUE TITLE
Improve search bar position on mobile devices / small width

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2549]
### Description
Currently the search bar is responsive for small screen and mobile devices but we could improve this beahaviour to get a better look & feel and ux.
Now the css triggers the search dimension when width is below of 768px and when match 768px causes that the searchbar cannot be toggled.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Chrome v63

*Steps to reproduce*

- Change the screen size until it matches 768px
- Click on search button to hide/show searchbar

*Expected Result*

- Searchbar will show or hide when the button has been pressed

*Current Result*

- Searchbar is always visible even if the button has been pressed

### Other useful information (optional):
Note: Changes apply to searchbar could affect the global behaviours of layout, e.g. dock panels and toolbars positions

**Comment by simboss** [comment]
I would keep the google to active and decativate the bar.

I would also want to to keep the behavour consistent with what we do on the desktop, i.e. the search bar stays below the buttons.

**Comment by tdipisa** [comment]
closed for inactivity
