### ISSUE TITLE
Map Viewer doesn't work on Apple Ipad's Safari

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#255]
You have a blank screen when opening the viewer.

**Comment by kappu72** [comment]
Doesn't work in OSX Leopard Safari too.

2015-10-23 10:14 GMT+02:00 Lorenzo Natali <notifications@github.com>:

**Comment by offtherailz** [comment]
We should try to fix OSX issue, (that is easier to find) to verify if it is the same issue. 
There is another issue, but I don't know if it related or not: On the home page the 3rd item of carousel is the red error page on iPad. Can you replicate the same issue on the desktop version of safari?

**Comment by kappu72** [comment]
No this is not possible, home page works fine. It's interesting that in
safari works only the scalebare example application.
If you want I can try to investigate

2015-10-23 11:21 GMT+02:00 Lorenzo Natali <notifications@github.com>:

**Comment by offtherailz** [comment]
verified 720f72b solves issues for iPad safari (and desktop's as in #257).
