### ISSUE TITLE
None feature highlighted selecting more than 1 features in feature grid (edit mode)

### ISSUE THREAD

**Issue by chiaracurcio** [geosolutions-it/MapStore2#2564]
Description:
Selecting more than 1 features in feature grid (using the edit mode) you can't see any highlighted features in the map

*Browser Affected*
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [ ] Safari

*Steps to reproduce*:

- open mapstore2 and login
-open a new map 
- add from WFS catalogue a poligonal layer (example 'poly_landmarks')
- open the FeatureGrid of the layer and select the edit mode
- select one feature in the table using the checkbox
- verify that the feature is now highlight in the map
- select more than one featyre using che checkbox in the same way
- note that none feature are highlighted now (so you can't see on the map your selection)

*Expected Result*

- all feature selected highlighted also if more than one (so you can find your selectiuonon the map)

*Current Result*

- none feature highlighted if you select more than one feature

### Other useful information (optional):
![2 selec](https://user-images.githubusercontent.com/33256901/35396019-269618f8-01ec-11e8-9e32-7ebd18fbf7e1.JPG)
![one selection](https://user-images.githubusercontent.com/33256901/35396020-26c16544-01ec-11e8-93e9-d5d796a001ee.JPG)

**Comment by tdipisa** [comment]
closed for inactivity
