### ISSUE TITLE
Upgrade of the Leaflet version

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#2569]
### Description
We need to plan an update of the Leaflet lib version. We need to establish which version.

**Comment by mbarto** [comment]
* Latest release: 1.3.1
 * dependencies:
   * leaflet-plugins (bing and google layers): https://github.com/shramov/leaflet-plugins
     * 3.0.2: bing (google support removed)
     * GoogleMutant: https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant 0.6.4
   * leaflet-minimap: 3.6.0
   * leaflet-simple-graticule: 1.0.2 (does it work?)
   * leaflet.locatecontrol: 0.62.0
   * leaflet.nontiledlayer: 1.0.7
   * leaflet-extra-markers: 1.0.6 (does it work?)
