### ISSUE TITLE
Fix layout of the dialog "About this app"

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#2570]
### Description
With low resolution screen the "about this app" dialog is displayed partially. 
You have to drag it to see it completely.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Browser Version Affected*
any 

*Steps to reproduce*

- Open a map
- click on "about this app" tool 
![image](https://user-images.githubusercontent.com/11991428/35501673-e21547b6-04da-11e8-8678-f80de76efd2a.png)

*Expected Result*
To see full dialog

*Current Result*
it is clipped depending on the resolution and it also starts with some margin top.
(if you see it completely you can change the zoom to see the effect)
### Other useful information (optional):

note: Maybe we can change it to a modal or to a side panel.

**Comment by tdipisa** [comment]
closed for inactivity.
