### ISSUE TITLE
In case of saving error the map is saved anyway corrupted

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2575]
### Description
When you try to save a map with a big shape file, the map should not be saved because of the size limit on DB. Anyway the map is saved anyway. Sometimes you can see even some wrong notifications like "A map with this name already exists".

*Browser Affected*
any

*Steps to reproduce*
- start creating a new Map
- add [this shapefile](https://github.com/geosolutions-it/MapStore2/files/1678519/Census2011_Province_generalised20m.zip)
 
- Try to save the map

*Expected Result*

- I see a spinner that shows me it's still saving and then an error because the shapefile is too big to be saved. 
 - The map is not saved

*Current Result*

- No spinner
- The map is saved anyway, but it doesn't work.

**Comment by offtherailz** [comment]
The issue is partially cause of GeoStore. GeoStore creates the resource anyway, but is empty. There is no way to retrieve the resource ID because of the error. 
*evaluation of possible workarounds on mapstore* 

MapStore could if the error is **not** due to map with same name. so find the resource by name and remove it (because of the unique name constraint) but we want to remove that constraint in the future.  So the best approch is to fix GeoStore. 

MapStore needs anyway to give better feedback by showing loading spinner during save procedure and showing correct notifications.

**Comment by mbarto** [comment]
https://github.com/geosolutions-it/geostore/issues/173

**Comment by mbarto** [comment]
Fixed by geostore update
