### ISSUE TITLE
Measure and Feature info tools should be mutually exclusive

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#258]
Measure tool and info tool can be activated at the same time. They should be in a toogle group or something else. 

To reduce the number of buttons in the toolbar I suggest to put the tools that can be active on the map in the setting panel, and when one of them is active, it should be placed on top.

Example: on startup the info button is on top of the bar, as now is. When the user opens the settings panel , maybe in an area dedicated to the tools, and he selects the measure tool, the measure tool appears active on the top of the bar. the info button is now available again in the settings panel.

**Comment by Gnafu** [comment]
Can't we just disable the measure tool when the user clicks on the Info tool and vice-versa?

**Comment by mbarto** [comment]
I would prefer the tools to be independent and make this kind of decisions at an higher level
