### ISSUE TITLE
Introduce text widget

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2592]
### Description
Add a widget to add html text. 

### Acceptance Criteria - AC
 - The widget can be added both to the geodashboard and the map
 - User can set text with a WYSIWYG editor

**Comment by chiaracurcio** [comment]
Although it was added you cant't see the Description of the text widget created, only the Title is visible.
(try to create a new text widget, add description and title in Widget Info and save the widget to add it on the map).

**Comment by offtherailz** [comment]
I'll check the first issue. 
The 2nd issue is present also on qa, so it is existing and not caused by this changes. Probably is due to some changes in save and reload procedure. 
I'll open a separate issue for that.
