### ISSUE TITLE
Add geodashboard skeleton

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2593]
### Description
Support base geodashboard editor and skeleton as for the [mockup] (https://demo.geo-solutions.it/mockups/mapstore2/#/dashboard). 

### Acceptance Criteria - AC
 - There should be a first version of editor for dashboard (reachable at `https://dev.mapstore2.geo-solutions.it/mapstore/#/dashboard) (not save yet) 
 - Charts and text widgets can be added to the dashboard

**Comment by mbarto** [comment]
Where is the mockup?
