### ISSUE TITLE
Details on map cards should be enabled/disabled from localConfig

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2603]
### Description
Details on map cards should be enabled/disabled from localConfig.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Chrome v63

**Comment by Mloweedgar** [comment]
@allyoucanmap  I want to work on this issue. Iam requesting for more clearification. Iam  new to MapStore

**Comment by allyoucanmap** [comment]
@Mloweedgar 

you can create a detail for the map from here by clicking on the wrench of map card in homepage

![details_card_01](https://user-images.githubusercontent.com/19175505/39432388-9fddcc28-4c93-11e8-8a39-07f4ef63e908.png)

if you create a details on map a new button will be displayed on map card

third button from left in image below
![_map_card](https://user-images.githubusercontent.com/19175505/39429319-c9f523ca-4c8a-11e8-9857-be2f62c1a7be.png)

we should add and verify that it's possible to enable/disable button and editor from mapcards using the configuration
in localConfig.json every plugin could be configured adding a `cfg` object with params that they will be used as props of plugin

here an example of configuration in localConfig

https://github.com/geosolutions-it/MapStore2/blob/master/web/client/localConfig.json#L476&L482

currently it seems there is a props to enable/disable the details row but not for the button
