### ISSUE TITLE
Improve iframe on react quill textarea

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2605]
### Description
Improve iframe functionality to react quill editor.
Currently the react quill editor uses an iframe component to display video, without the possibility to change width or height of the component.
The aim of this issue is to add a module to react-quill that enable the edit of resize and src of iframes.

This functionality could be useful on get feature template where it's possible to make a iframe view based on one or more variables.

**Comment by mbarto** [comment]
Can you explain a little better why it is useful to have an iframe and how would you use it?

**Comment by allyoucanmap** [comment]
@mbarto 
Yes, I just updated the description with a better explanation

**Comment by georgepoulos** [comment]
I try to compile MapStore2 today and there is problem with Quill. 
When i create a save a chart. It has no frame when is saved on map,
and a second problem is selected layers properties are not working

> quill

 Overwriting formats/video with 

> 

`IFrame()
​blotName: "video"
​className: "ql-video"
​create: function create()
​formats: function formats()
​length: 0
​name: "IFrame"
​prototype: Object { … }
​sanitize: function sanitize()
​tagName: "DIV"
​value: function value()
​__proto__: function Embed()`

**Comment by allyoucanmap** [comment]
Hi @georgepoulos,
could you move the discussion on the mailing list and send us more details?

> When i create a save a chart. It has no frame when is saved on map

could you please send a screentshoot of chart saved without frame on map ?

> and a second problem is selected layers properties are not working

this is issue seems related to #2759
now property plugin need to be configured

add TOCItemsSettings to plugins.js

`TOCItemsSettingsPlugin: require('path-to-plugin-folder/TOCItemsSettings')`

and to localConfig.json:
desktop

`"TOCItemsSettings" `

mobile
```
{
    "name": "TOCItemsSettings",
    "cfg": {
        "width": 300
    }
}
```

> I try to compile MapStore2 today and there is problem with Quill.

The warning message is due to an override of video functionality to extend the ability to edit iframe on quill textarea and shouldn't cause issues.
