### ISSUE TITLE
CI should Fail if documentation has some errors

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2607]
docma doc build returns 0 even if some errors occours in build. 
So this line in package.json is not enough to check documentation correctness. 
```
    "travis": "eslint web/client --ext .jsx,.js && npm run i18n && karma start ./karma.conf.single-run.js --browsers Firefox --reporters dots,junit,coverage,coveralls && docma -c docma-config.json --dest web/docs"
```
We could find a way to make the (travis or jenkins) build fail when documentation build has error. (e.g. check file existence in web/docs or change docma script to return -1)

**Comment by mbarto** [comment]
Doesn't the script return an exit code > 0 when it fails?

**Comment by tdipisa** [comment]
closed for inactivity.
