### ISSUE TITLE
Layer loading icons in TOC blink when many layers have been added

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2611]
### Description
Layer loading icons in TOC blink when many layers have been added.
This is more frequent on project rather than master.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- open a map
- add layers from catalog (more than 7)
- move the map

*Expected Result*

- loading icons in TOC doesn't blink

*Current Result*

- loading icons in TOC blink

**Comment by tdipisa** [comment]
fixed in latest version
