### ISSUE TITLE
Maybe geoserver security problem

### ISSUE THREAD

**Issue by georgepoulos** [geosolutions-it/MapStore2#2617]
When I try to get data from a map it is possible only when I am logged in geoserver in the same browser if i try from another browser i cannot see my data.
I get this error

> :8080/mapstore/rest/geostore/resources/resource/30/attributes/details Failed to load resource: the server responded with a status of 404 (Not  Found)

but  GET http://localhost:8080/geoserver/wms?SERVICE=WMS&REQUEST............. is OK

**PROBLEM is when I am logged out from geoserver i cannot see my data.**

I use  geostore authentication tutorial and these settings

User Group Services
geostore | JDBC user/group service from postgre
Role Services
JDBC role service

Authentication
Authentication Providers geostore | JDBC database authentication +
Authentication Filters geostore | Authentication using a key +
Filter Chains  geostore to default

**Comment by mbarto** [comment]
Hi George, could you move the discussion on the mailing list and send us more details about the GeoServer and MapStore2 configuration?
In particular: how you configured authkey and if you added the right authentication rules in localConfig.json (you can send copy of the actual configuration file if you want)

**Comment by georgepoulos** [comment]
Ok thank you I move this discussion on yours mailing list. # #
https://groups.google.com/forum/#!topic/mapstore-developers/CRHnsjJi1rM
