### ISSUE TITLE
Improve Sidecard component styles

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2618]
### Description
Sidecards contents should be adaptable to fit correnclty their container.
We need to improve:
- text, descprition, caption height and width
- add text ellipsis when text are too long
- use of flex container instead of percentages

### Other useful information (optional):
SideCard/SideGrid currently in MapStore2:
- widget list dashboard / map view
- chart list dashboard / map view
- layer selector dashboard
- compact catalog dashboard
- get feature info settings format in layer properties

check all card lists in dashboard

**Comment by chiaracurcio** [comment]
also opening the dashboard using a mobile device and then the charts widget there are any problems and you cant't see the charts labels from the widget catalog
