### ISSUE TITLE
Missing KMZ and GPX file format in the export layer data tool

### ISSUE THREAD

**Issue by chiaracurcio** [geosolutions-it/MapStore2#2620]
### Description
Two missing usefull file format when you want to download data from the map: KMZ and GPX

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [X] Internet Explorer
- [X] Chrome
- [X] Firefox
- [X] Safari

*Steps to reproduce*
- open a map example this one: Unesco Italian Items
- select the export layer data tool
- verify that KMZ and GPX file format are not available from the list of File Format that  you can download

*Expected Result*
- you can download file using the KMZ and GPX file format

*Current Result*
- you can't download file using the KMZ and GPX file format

**Comment by tdipisa** [comment]
closed for inactivity.
