### ISSUE TITLE
Some improvements/bugs in mobile version

### ISSUE THREAD

**Issue by chiaracurcio** [geosolutions-it/MapStore2#2621]
### Description
Below a list of some improvements/bux to fix observed using the mobile device:

1) when you open the LAYER METADATA INFO tool ("i" button in the TOC) a black label with this description 'show the selected layer's metadata' overlays the layer metadata window

2)  when you open the LAYER METADATA INFO tool ("i" button in the TOC) you can't see all the window because is bigger than the screen, expecially if you turn the sreen horizontally it's not easy move the window to see all the data: it would help to have a full screen window for layer metadata in mobile device

3) when you are in home, login and select the accunt information menù of your account: note that the ACCOUNT INFO window not overlay the green label 'fork me on Github'

4) when you are in home, login and open the account manager menù and then MANAGE ACCOUNTS, note that the HOME BUTTON has a strange position below the GeoSolution header.

5) open a map and the window of layer properties for a layer (in TOC) note that this window is bigger than the screen, expecially if you turn the sreen horizontally it's not easy move the window to see all the data or save/close the window: it would help to have a full screen window for layer metadata in mobile device.

*Browser Affected*
- [ ] Internet Explorer
- [X] Chrome
- [ ] Firefox
- [ ] Safari

*Steps to reproduce*
(steps described in description)

*Expected Result*
- enhanced use of the mobile version of mapstore2

*Current Result*
- Some improvements/bugs found

### Other useful information:
android device used

**Comment by tdipisa** [comment]
closed for inactivity, fixed in latest versions.
