### ISSUE TITLE
Implement table widget

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2623]
### Description
Table widget for both dasboard and map

### Acceptance Criteria
 - [ ] The table should be configurable from the widget build tools as for the mockup

### Issues
 - Part of issue #2622

**Comment by mbarto** [comment]
Where is the mockup? Can you link it here?

**Comment by chiaracurcio** [comment]
Please note this observations:
1) when you write long description in table widget Info you have this result (this happens also if you write a long text in title, in this case you can't see the whole title in the table):
![2623](https://user-images.githubusercontent.com/33256901/36981907-abb9c10e-208e-11e8-8113-e6f8f54d9a1b.jpg)

**Comment by offtherailz** [comment]
The notified issue may belong to all widgets (not related to the table). If there is nothing else you noticed for the table widget, we should close this and open a new issue related to the description problem
