### ISSUE TITLE
length measurement in nautical miles (along great circles)

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#2626]
### Description
see [this issue](https://github.com/geosolutions-it/austrocontrol-C125/issues/4)

### Other useful information (optional):
for this issue non need to add the add as annotation button

**Comment by chiaracurcio** [comment]
please note this observation: 
in Leaflet when you drow a measure distance in nautical mile (nm unit of measure selected) you have the flag with the measure in Km and not in NM as requested, 
you have the NM measure correcly displayed only inside the meature tool window:
![leaflet_meas_tool](https://user-images.githubusercontent.com/33256901/37155970-fda47e34-22e4-11e8-9cb0-b41038708f80.jpg)

**Comment by chiaracurcio** [comment]
there is a new problem to fix in Leaflet now: 

- when you select the Measure Distance tool (whatever unit of measure you choose) and you drow a measure, you have the correct measure inside the flag but then, when you click the second point you can't see the result in the measure window (you always get Length =0.00)
![immagine](https://user-images.githubusercontent.com/33256901/37455183-cc9a49d8-283c-11e8-87b5-a39adbcd5022.png)

**Comment by MV88** [comment]
i've opened a new issue #2748 for these errors

**Comment by tdipisa** [comment]
@chiaracurcio I think that this issue can be closed in favour of #2748
