### ISSUE TITLE
Editing new features in featureEditor not working well (OL)

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#2629]
### Description
when you create a new feature and after adding one geometry, if you try to edit that geometry it moves the point but not the geometry.
to fix this you have to click again on add new geometry.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome 
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*
Chrome 64.0.3282.167

*Steps to reproduce*
- open **wfs test map** with openlayers
- open feature editor (login as admin)
- add new feature and draw one geometry
- try to edit that geometry

*Expected Result*
the geometry follow the dragged point

*Current Result*

only the point is moved 

### Other useful information (optional):
probably related to drawSupport

**Comment by tdipisa** [comment]
closed for inactivity.
