### ISSUE TITLE
Identify marker still on map after opening feature editor

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2634]
### Description
Identify marker still on map after opening feature editor

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- v64

*Steps to reproduce*

- open a map with layers
- click on map
- verify get feature info is open with marker on map
- open TOC
- select a vector layer
- open feature editor

*Expected Result*

- marker is still on map even if feature info panel is closed

*Current Result*

- marker should be cleared from map if feature info panel is closed

**Comment by tdipisa** [comment]
closed for inactivity.
