### ISSUE TITLE
Vector data upload coordinates issue

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#2638]
### Description
Importing KML / GPX and shapefile with null 3d coordinates breaks printing.
We should parse coordinates and remove 3d stuff, at least for printing purposes.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- A list of steps to reproduce the bug
- ...

*Expected Result*

- Describe here the expected result 

*Current Result*

- Describe here the current behavior

**Comment by kappu72** [comment]
This is more a print pdf issue then a data upload issue. The 3rd coordinates is stripped when submitting data to mapfish.
