### ISSUE TITLE
KML attributes import

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#2639]
### Description
We should avoid importing styling attributes as GeoJSON properties.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- A list of steps to reproduce the bug
- ...

*Expected Result*

- Describe here the expected result 

*Current Result*

- Describe here the current behavior

**Comment by chiaracurcio** [comment]
Please note comments in [Issues with data upload #31](https://github.com/geosolutions-it/austrocontrol-C125/issues/31)
