### ISSUE TITLE
Widgets:  Improve legend presentation for pie chart

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2650]
# Description
The legend provided by recharts for pie charts is ugly. 
![image](https://user-images.githubusercontent.com/1279510/36790542-73afb856-1c95-11e8-8942-6228d7ffe5c2.png)
It should be aligned on a side. 

# Acceptance criteria AC
 - The legend should be aligned on one side for pie charts

# Implementation notes
This is a sample with legend aligned to the right. 
https://jsfiddle.net/offtherailz/ducnsveo/1/
WIP on this branch: https://github.com/offtherailz/MapStore2/tree/pie_legend_wip

Needings (See the branch `pie_legend_wip`): 
 - Update recharts to the latest version
 - Fix issues due to update (I noticed now the grid of the chart is above the chart, not below, and mouse hover on bar charts hides the bar)
 - Auto positioning of legend OR advanced option that defines legend position and size
 - Responsive layout with every widget size

**Comment by simboss** [comment]
I want to see a mockup for this before moving on.

**Comment by MV88** [comment]
just a note: there is a new label, "mockup needed"

**Comment by tdipisa** [comment]
@simboss the mockup is already there but not updated online, I asked @allyoucanmap to check.

**Comment by tdipisa** [comment]
The mockup is already available in the dashboard editor mockup [here](https://demo.geo-solutions.it/mockups/mapstore2/#/dashboard):

![pie_chart_legend.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5943f6b8abdc49001a6611c9/125516c66e82c728ace21e0d46f89d9f1c818ba89dfd804fa15af59a2d046b313916ac217586f76ae5002e00585b48ad10515915afac8c22a6b63e778f580ce882654d68d47f40f2ecdd42e64bef62994597b7b4804dc5ea3426e6888d463f1900189bb2.gif)

We can discuss on this if needed.

**Comment by offtherailz** [comment]
Some notes: 
1 - Image export should work as expected (the exported image should look very similar to what the user see (of course the scrollbar of the legend should not appear)
2 - The legend issue, at least for the moment, is only a problem of the Pie chart. The other charts have only one value, so there is no issue. So it should be better to work only on Pie chart. 
3- The mockup is only an idea. You have a flag to make the legend disappear, so it is not mandatory to make the legend disappear when there is not enough space. 

@baloola There are 3 possible I see to solve this issue: 
1 - Try to use existing legend options, customized a little bit, with some css if needed
This may be hard but is the cleaner way and the more maintainable one. Also image export should work out of the box in this case (Except for the scrollbar of the legend). See [these](http://recharts.org/en-US/api/Legend) options: 
2 - The one in the mock-up: Make a component called "ResponsiveLegendChart" that use 2 SimpleCharts, one to render the legend and the other one to render the chart, then use it instead of SimpleChart inside widgets.  
You may have some troubles to compose the final image to export, but it should be easy, using canvas
3 - Write the legend on your own, and a component that contain SimpleChart and legend to use instead of the current SimpleChart inside the widget
This is the most complicated solution for the image export, but it allows to make it on your own, so without the limits of recharts API.

The solutions are in order of preference. I strongly suggest the 1st one. 
Please justify the reason if you will want to move to solution 2 or 3 or suggest your one.

**Comment by offtherailz** [comment]
This is a sample with legend aligned to the right. 
https://jsfiddle.net/offtherailz/ducnsveo/1/

I've to check how to do this (and if this is feasable) with dynamic size of tooltips

**Comment by tdipisa** [comment]
Closed in favor of #6139
