### ISSUE TITLE
Widgets: Indicate percentage on pie charts

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2651]
### Description
User should see. percentage on pie charts. Recharts doesn't provide this option out of the box. Labels are external and exceed the chart box (see the picture to understand how they whould exceed). 
![image](https://user-images.githubusercontent.com/1279510/36790912-97186c9c-1c96-11e8-8b41-ebf8f4108649.png)

We should investigate how to do it. As an alternative solution we could indicate it on legend. 

### Acceptance Criteria AC
 - Pie charts should indicate percentage

**Comment by simboss** [comment]
I want to see a mockup before moving forward with this.

**Comment by MV88** [comment]
On light colors the white text is not clearly visible

**Comment by baloola** [comment]
would removing the yellow color by changing the color range work? the only color in the current range that has a bad contrast when using white text is the yellow. shifting the range would result in a chart like this:
![range_change](https://user-images.githubusercontent.com/28819736/43716175-680c6bc8-9983-11e8-81ab-c440a0c391aa.png)

**Comment by offtherailz** [comment]
Color sometimes depends on how many items are in the pie chart. Maybe we should show the percentage on mouse hover, in the tooltip, so the user can move the mouse on it to see the number, when it is difficult to read.

Moreover: What happens for small charts? I see only big charts, so I'm afraid there are have some graphical issue with small charts.

**Comment by baloola** [comment]
the approach is to render percentages if there is enough area on the chart ( percent >= 25% in the smallest chart ). But a tooltip would be convenient for all the scenarios.

**Comment by offtherailz** [comment]
If showing the labels on pie sections is too hard (e.g. you can not hide them in small pies an this causes graphical issues), use only tooltips.
