### ISSUE TITLE
Widgets: Rethink gaudge chart

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2652]
### Description
We can improve gauge look and feel and usability. 
[This was the original gauge](https://gist.github.com/emiloberg/ee549049ea0f6b83e25f1a1110947086) chart for recharts used.
We can improve : 
 - [ ] Label Position - Placing variable and value above and below the chart
 - [ ] a margin between gaudges - that helps to distinguish them
 - [ ] calculate max from all data - a max could be retrieved with the current filter (viewport not included) 
 - [ ] background style - reduce the size of the background will help readability

**Comment by simboss** [comment]
Step 0, let's remove it!

**Comment by tdipisa** [comment]
closed for inactivity.
