### ISSUE TITLE
Widgets: Advanced chart options

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2654]
### Description
Some things in the charts should be configurable. 
- [x] hide/ display background grid (for bar/line charts) 
- [x] Optional Y axis labels
- [x] allow customization of y axis name. By default is something like `Count(attribute_name)`.

A collapsible panel with advanced options for charts should be present to allow these config. 

All these suggestions come from feedback from C040

**Comment by simboss** [comment]
it might be worth splitting this.

**Comment by simboss** [comment]
The Y axis labels are not really optional, without them the charts do not deliver important information about the values!

**Comment by baloola** [comment]
according to https://github.com/react-bootstrap/react-bootstrap/issues/2930 using Panel children components requires  react-bootstrap  version "0.32.0", we use "0.31.0"

**Comment by mbarto** [comment]
I don't think react-bootstrap upgrade is needed, header and body are available also in older versions, with a different syntax (header is an attribute).
recharts proposed upgrade is to a beta version, so we need to be sure we really need it and we don't introduce regressions.

**Comment by offtherailz** [comment]
@tdipisa Yes we would like to update them. 
Anyway some libs evolve to fast, we have to allocate time to investigate of what are the changes in the API  update and test.
Bootstrap is widely used in MapStore so an update may require a lot of changes, on both MS2 and dependent projects.
Recharts on the other side is used in some specific context (elevation and widget) and so an update can cost less in terms of lines to update. 

Anyway a more precise evaluation need an investigation.

**Comment by tdipisa** [comment]
I agree with @mbarto, @offtherailz and @baloola I would like to avoid beta version for this

**Comment by chiaracurcio** [comment]
Please note that the space for numbers in y axis is limited so for example if you choose PERSONS as Y ATTRIBUTE and the SUM as operator you have this result: 

![immagine](https://user-images.githubusercontent.com/33256901/43905757-01123b8e-9bf2-11e8-8c93-673918077cb5.png)

Big numbers could be write in smaller font or we can use abbreviations for zeros (like K).

**Comment by offtherailz** [comment]
You can even take into account to use 1k 10k .... as unit, to shorten them up

**Comment by baloola** [comment]
The same issue appears when using oblique labels for the x axis #2655. 
The use of k can be used to overcome big numbers, but what about long strings? 
@offtherailz suggested to try something like ellipsis (css).

**Comment by offtherailz** [comment]
Closing, Pending tasks moved in #2655
