### ISSUE TITLE
Widgets: minor changes to evaluate

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2655]
### Description
Some minor changes to evaluate: 
- [x] Evaluate possibility to collapse widgets
- [x] Oblique labels  - Not available out of the box. 
(feedback from C040) to allow to display long labels. 
Actually we have this effect:
![image](https://user-images.githubusercontent.com/1279510/44780338-043ced00-ab82-11e8-8ba3-5e5059847551.png)

Something like this may allow to display bigger strings. 
![image](https://user-images.githubusercontent.com/1279510/36888854-a1e63282-1df7-11e8-8428-7e2f353e22d5.png)

More below:

- [ ] Add the ability to configure the angle of labels with the possibility to put them vertically

**Comment by simboss** [comment]
What do you mean by oblique label @offtherailz ?

**Comment by offtherailz** [comment]
means, rotated, like this, to prevent most of label conflicts.
![image](https://user-images.githubusercontent.com/1279510/36888854-a1e63282-1df7-11e8-8428-7e2f353e22d5.png)

Unfortunately the lib doesn't provide them out of the box. This was an investigation task to check feasibility.

**Comment by gioscarda** [comment]
A borderline case: the `gs:us_states` layer.
When creating a line/bar chart widget on that layer some graphic errors occur:
- some Y labels, if not shortened (< 1.000.000), are not completely visible, both in preview and in the widget, with vertical X labels
- using `state_name` on the X axis the chart is not readable in preview even if you change the labels' orientation

![chart_widget_glich](https://user-images.githubusercontent.com/43670920/60801913-1f03c900-a178-11e9-838a-11d74a2c21ff.gif)

Data configuration:
- X attribute `STATE_NAME`
- Y attribute `LAND_KM`
- Operation `MAX`

Errors evidences:

![Selection_040](https://user-images.githubusercontent.com/43670920/60802369-fdefa800-a178-11e9-843f-1caa42de01f5.png)

![Selection_039](https://user-images.githubusercontent.com/43670920/60802328-eb756e80-a178-11e9-9228-e6c09c5ea40a.png)


@offtherailz, shold we consider this case as blocking?

**Comment by offtherailz** [comment]
@MV88 can we add that couple of pixels missing easely ?

**Comment by MV88** [comment]
@offtherailz regarding the extra margin to the left yes if we need just a few extra pixels
a little more to see if this can be calculated dinamically

**Comment by MV88** [comment]
update, i will:
- add some pixels 
- make the threshold be configurable if it is not the case
- change the default value of threshold from 1000000 to 1000
