### ISSUE TITLE
Widgets: Export legend in image

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2658]
### Description
Now chart image export allow only to export the chart, not the legend.
 - Legend in recharts is pure html so to do it you may need to use html2canvas + manually draw legend on/near chart. (on/near depends on  #2650)
This task depends on the chart effective implementation, so changes due to  chart and legend rendering (i.e. #2650 ) may need to adjust this functionality.

**Comment by tdipisa** [comment]
Done in 2021.01.00 using PlotlyJS
