### ISSUE TITLE
ColorRamp not selected when editing existing chart

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#2680]
When I edit a Pie Chart (but also other charts) I get presented with the editing view of the chart but the current colorramp is not selected in dropdown.
![ramp.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53db821e82b317f7d9ad3aa2/125516c66e82c728ace21e0d46fa959733c0cfeb9ffbb049a15ee4d6730472727e50f57a71dcb529bc472e585f5f4cab445c5841aff19b37b4f46d2ede0356b49b381d66cc2f13acb2831abe08b329824a86bfbc8f49d2a5.jpg)

**Comment by offtherailz** [comment]
This is correct, going to close it.
