### ISSUE TITLE
Label Change in Pie Chart

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#2681]
Change *Value:* in *Use:*

**Comment by baloola** [comment]
could you elaborate more please?

**Comment by chiaracurcio** [comment]
Note that using italian language the "Use" label is not correct: "Usa" as you can see following:
![immagine](https://user-images.githubusercontent.com/33256901/43721124-3e472ab2-9992-11e8-9969-4acaceb19471.png)
please correct with "Uso"

**Comment by offtherailz** [comment]
If showing the labels on pie sections is too hard (e.g. you can not hide them in small pies an this causes graphical issues), use only tooltips.

**Comment by offtherailz** [comment]
@tdipisa can you help us with this atrocious dilemma :) 
OtherwiseIf we don't have any valid argument in favor of "Uso" i should keep "Usa"
