### ISSUE TITLE
Measure tool, dbl click zoom the map instead of closing the area(polygon)

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#2694]
### Description
see Title

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome 64.0.3282.186
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

*Steps to reproduce*

- open new map with leaflet 
- open measure tool
- choose area
- start drawing
- try to close the draw with double click

*Expected Result*
to close the area
![image](https://user-images.githubusercontent.com/11991428/36966786-2b1fab92-205e-11e8-92e1-c25be1a7f009.png)

*Current Result*
it zooms the map while maintaining the draw status active
![image](https://user-images.githubusercontent.com/11991428/36966888-82545e6c-205e-11e8-830e-8b65317d75bc.png)

### Other useful information (optional):
using new version for leaflet libraries (leaflet 1.3.1)

**Comment by tdipisa** [comment]
closed for inactivity
