### ISSUE TITLE
Measure tool, initial mispositioning of tooltip while drawing

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#2695]
### Description
When you start drawing something the tooltip starts in the top left corner

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome 64.0.3282.186
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

*Steps to reproduce*
- open new map with leaflet 
- open measure tool
- choose any tool

*Expected Result*
The tool selected gets enabled and no tooltip is shown in the map

*Current Result*
The tool selected gets enabled and a tooltip appear in the top left corner
![image](https://user-images.githubusercontent.com/11991428/36967222-707aead4-205f-11e8-82b1-1c9a07081c83.png)

### Other useful information (optional):
using new version for leaflet libraries (leaflet 1.3.1)

**Comment by tdipisa** [comment]
fixed in latest versions

**Comment by tdipisa** [comment]
closed for inactivity
