### ISSUE TITLE
Cannot display shapefile from NaturalEarth site

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#2702]
### Description
I would like to view NaturalEarth vectors with MapStore2

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [ ] Firefox untested
- [ ] Safari untested

*Browser Version Affected*

- Microsoft Edge 38.14393.2068.0
- Chrome 64.0.3282.186

*Steps to reproduce*

- Download http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_boundary_lines_land.zip
- Open a map in MapStore2
- Click on the menu an select "Carica Files Vettoriali"
- Drag & drop the downloaded file in the window that opens

*Expected Result*

- The shapefile content is displayed on the map

*Current Result*

- An error saying "Il file non è stato caricato correttamente sulla mappa"

### Other useful information (optional):

I also tried re-packaging the file removing unnecessary files (readme.html and version.txt)
The same file is correctly loaded by http://mapshaper.org/

**Comment by tdipisa** [comment]
Solved in 2018.02.00
