### ISSUE TITLE
Long description and title in widgets

### ISSUE THREAD

**Issue by chiaracurcio** [geosolutions-it/MapStore2#2707]
### Description
when you write long DESCRIPTION and TABLE in widgets you have this result (almost when you use Chrome, not always in Firefox)
![2623](https://user-images.githubusercontent.com/33256901/36981907-abb9c10e-208e-11e8-8113-e6f8f54d9a1b.jpg)
![image](https://user-images.githubusercontent.com/33256901/37040507-4fe52590-215a-11e8-8855-0633b69ff527.png)

### In case of Bug 
*Browser Affected*
- [ ] Internet Explorer
- [x] Chrome
- [x] Firefox
- [ ] Safari

*Steps to reproduce*
- create a widget with long TITLE and DESCRIPTION, 
- open the menù to see the TITLE and the DESCRIPTION entered

*Expected Result*
- you can see the entire TITLE and DESCRIPTION inside the box area

*Current Result*
- you see a part of the TITLE / DESCRIPTION outside the box area

**Comment by baloola** [comment]
I couldn't reproduce the issue on chrome and Firefox.
However,I have noticed that the options button disappears when using a long title
![before-](https://user-images.githubusercontent.com/28819736/44735374-9abecf00-aaec-11e8-9589-b2f612d9aa54.png)
![after-](https://user-images.githubusercontent.com/28819736/44735382-9db9bf80-aaec-11e8-9106-bd60ce68941b.png)
I will make a PR for this fix

**Comment by MV88** [comment]
Maybe you can try with a text without using the spaces

**Comment by baloola** [comment]
O.K, I got it.
Thanx

**Comment by chiaracurcio** [comment]
note that using the Chrome browser the title is cutting it in 2 row when you shrink the chart area (the problem coul be that the title is placed even below the chart in this way):
![immagine](https://user-images.githubusercontent.com/33256901/44992258-0c889400-af97-11e8-9d26-eec3f83dd70a.png)
