### ISSUE TITLE
OpenLayers WMS requests are, by default, 1.5 times bigger than the current screen size

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#2741]
### Description
OpenLayers WMS requests are, by default, 1.5 times bigger than the current screen size.
We should configure the default to 1 and allow overriding it from configuration.

*Steps to reproduce*

- A list of steps to reproduce the bug
- Configure a WMS layer as "Single Tile"
- using Chrome DevTools look at GetMap requests width and height
 - a 1.5 ratio is used (leaflet does not do that)

*Expected Result*

- The requested image is as big as the browser window, not bigger

*Current Result*
- The requested image is 1.5 times as big as the browser window

**Comment by mbarto** [comment]
Look here: https://openlayers.org/en/latest/apidoc/ol.source.ImageWMS.html

ratio is the option to change

**Comment by simboss** [comment]
@mbarto what about leaflet. Does it do anything similar?

**Comment by mbarto** [comment]
No
