### ISSUE TITLE
Safari doesn't allow mixed content

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2750]
### Description
Layers with http url are not displayed when requested from mapstore whit https url

message that show up on safari browser
`[blocked] the page at https://... was not allowed to display insecure content from http://...`

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [x] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- open `Historical Maps of Florence` on Safari (be sure to use https url of mapstore)

*Expected Result*

- Layers show up

*Current Result*

- Layers doesn't show up

**Comment by tdipisa** [comment]
This happens also on Chrome in IOS 12.0.1

**Comment by tdipisa** [comment]
closed for inactivity
