### ISSUE TITLE
Map widget editing

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#2754]
The ability to configure layers by adding/removing them to the map widget (you will see a TOC in the wizard with the possibility to add layers from an embedded catalog)
Acceptance criteria
 - [x] Configure/modify map position
 - [x] Display map TOC
 - [x] Allow to add layers from the catalog
 - [x] Allow to remove selected layers/layergroups
 - [x] Allow to edit layer properties
 - [x] Allow to change layer order

**Comment by chiaracurcio** [comment]
note that there are any problems when you update the position of the map in the edit mode (refer to issue for this)
