### ISSUE TITLE
If TOCItemsSettings isn't configured it doesn't show up in TOC

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2759]
### Description
The need to configure TOCItemsSettings when TOC plugin is enable represents a bad design of TOCItemsSettings plugin.
TOC plugin should work without additionally configuration.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Browser Version Affected*

- all

*Steps to reproduce*

- remove TOCItemsSettings from localConfig.json
- open a map
- click on settings icon

*Expected Result*

- settings panel will show up

*Current Result*

- settings panel doesn't show up

**Comment by allyoucanmap** [comment]
connected to https://github.com/geosolutions-it/MapStore2/issues/2333

**Comment by tdipisa** [comment]
We are reviewing the entire MS's layout (closed in favor of #4254).
