### ISSUE TITLE
Default number of loaded records in FeatureGrid

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#2765]
### Description
To make the feature loading more responsive we should decrease the number of features loaded by default in the FeatureGrid (now we have 20 as default number, probably 10 should be better).

**Comment by offtherailz** [comment]
AS you can see here: https://github.com/geosolutions-it/MapStore2/pull/2840 
10 items cause a problem. We should instead make the table load the missing results.

**Comment by tdipisa** [comment]
closed for inactivity
