### ISSUE TITLE
Styles misalignment in BorderLayout component

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2775]
### Description
Some elements contained in BorderLayouts are misaligned.
- info popup
- buttons margins
- scroll bar on some widgets

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Chrome v65

*Steps to reproduce*

- open dashboard
- click on charts widget

*Expected Result*

- info popup should be inside the left panel

*Current Result*

- info popup is positioned outside the left panel

### Other useful information (optional):

Verify styles of all the BorderLayouts in MapStore2

**Comment by offtherailz** [comment]
I report other issues coming from the same changes on css/less, to be sure they are also fixed solving this issue: 
 - Margin of top button in text widget
![image](https://user-images.githubusercontent.com/1279510/37982088-c9d3aa34-31ef-11e8-847d-e7e4ad87f7ef.png)
 - Widgets sometimes has scrollbar (expecially map widgets) ![image](https://user-images.githubusercontent.com/1279510/37982018-8da661e6-31ef-11e8-86a9-278186bcb2d8.png)
