### ISSUE TITLE
Legend not available for annotations and vectors: a notification message would be helpful

### ISSUE THREAD

**Issue by chiaracurcio** [geosolutions-it/MapStore2#2784]
### Description
when you print a map with only annotations (setted for it) and vector you can't print the legend but you can select this option in the print tool, 
at the same time when you select this possibility you haven't a any notification message and it is not what you would expect ,
indeed in a map whith WMS, annotations and vector the only available legend in pdf is those relating to WMS

*Browser Affected*
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [ ] Safari

*Steps to reproduce*
- print a map with annotation (setted for it) and/or vector

*Expected Result*
- you can see a notification message

*Current Result*
- you can't see the legend but you haven't any notification message

**Comment by tdipisa** [comment]
closed for inactivity.
