### ISSUE TITLE
Google background doesn't work in openlayers/widget map

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2786]
### Description
Because of some issues with style and with timing, if a map has google as background, it will have some problems when used as a widget with openlayers.
### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
any

*Steps to reproduce*

- Open Dashboard
- Add a map widget
- Select a map with a google background from the list

*Expected Result*

- you can see the map

*Current Result*

- there are some errors and some graphical glitches both in widget and preview context

**Comment by offtherailz** [comment]
Unfortunately the google background solution in openlayers works well only in the full window map context.
The customization made to support window resize and rotation are valid only in the full map context, because of a limitation of the Javascript API. 

There are some polyfill and techniques that could allow it to work also in a small size and resizable context as the widget is, but it takes a lot of time of investigation and implementation.
I suggest, as a temporary solution, to exclude google backgrounds in case of widgets only in the widget case. 
If google background was the visible one, automatically osm will be selected (as in the print use case).

When background selection will be allowed we can try to fix this issue.

**Comment by ElenaGallo** [comment]
This issue is no longer valid, it can be closed.
