### ISSUE TITLE
Allow to add a catalog service to the dashboard layer selector

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2797]
### Description
The catalog service to retrieve layers for geodashboard is pre-configured. We need to allow to add and select different sources from UI as it is possible in map viewer catalog tool (a [mockup here](https://demo.geo-solutions.it/mockups/mapstore2/#/dashboard))

### Acceptance Criteria 
   - User must be able to select a catalog from  the UI. The initial list is configured in `localConfig.json` as for the map's catalog
   - User must be able to add his own source, as for the map's catalog. 
   - When the user save the dashboard, if the list of sources has been modified, the sources must be saved in the dashboard resource, for a future re-use. When a user load an existing dashboard, the list of catalog should contain the ones added by the user when he saved it the last time. If there was no sources list saved, the list will be the one configured in `localConfig.json`
 - The aim is to have also for geodashboards the same catalog capabilities available inside the map viewer (eg. support all source types MS supports and related advanced options)

**Comment by MuhweziDeo** [comment]
@tdipisa I Hey Just want to confirm this from you. Reusing the existing catalog. Do you by any chance mean the one below?
![Screenshot 2021-03-11 at 18.50.52.png](https://images.zenhubusercontent.com/60350ba854742f543a9fa5ff/bcaa3ce1-9952-4f7e-98ad-55685189cae9)

This would mean overwriting the current implementation below.
![Screenshot 2021-03-11 at 18.51.22.png](https://images.zenhubusercontent.com/60350ba854742f543a9fa5ff/a580a808-d072-4f82-b90d-eabb9c1807ac)

**Comment by tdipisa** [comment]
@MuhweziDeo yes, it is the catalog tool available for the map viewer: the aim is to have also for geodashboards the same catalog capabilities to allow the user to configure one of the catalog source types MS supports along with they advanced options (the UI changes a bit as reported also in the mockup because the user interaction in dashboard is a bit different). @offtherailz will put in a comment some more details that will clarify dev aspects to take into account about the logic to reuse also for dashboards.
After this we can clarify the UI if you need.

**Comment by offtherailz** [comment]
Hi @MuhweziDeo 

Catalog and the layer selector are two different tools with two different goal. The only thing they have in common is they are backed by some services of the same kind and allow to browse them.
In the "CatalogPlugin" everything is strictly connected to the catalog state and with a lot of options (for displaying layer data, add to the map, advanced options of catalog creation, layer creation ) that are out of scope in a simple tool for layer selection. 

The other component, `CompactCatalog` that is the one used here (in a layer selector). It fits better the scope of this requirement. Actually the CompactCatalog has an incomplete implementation ( you can enable by setting `showCatalogSelector`  (`={true}`) here.
https://github.com/geosolutions-it/MapStore2/blob/c88123cbda835d21dff1e0ff8b0582b21a4cba1a/web/client/components/catalog/CompactCatalog.jsx#L107

![image](https://user-images.githubusercontent.com/1279510/111140687-ed651700-8582-11eb-949c-348c32ce7a7f.png)

You can clean up this old incomplete implementation if you need.

Note: The same catalog is used also for adding layers to the map widgets or selecting layer for the chart wizard. We need to define if some differences should be applied @tdipisa (e.g. do not allow certain types of services, like TMS, in catalog selection).

The things to do should be: 
 - Load a list of catalogs from a configured list in `localConfig.json` (as the current `catalog` property), or from the current dashboard saved, if customized.
 - User can add catalogs using the plus button. The UI should be similar to the one in Catalog plugin (sync with @tdipisa about the UI and the differences with the other catalog tool). 
 - The new catalogs should be available in a second time, so they should be added to the state and saved in the dashboard.

**Comment by MuhweziDeo** [comment]
thanks @offtherailz

**Comment by MuhweziDeo** [comment]
@tdipisa Should the add Catalog service be similar to the existing one

**Comment by tdipisa** [comment]
After the initial investigation a new issue has been open for this implementation (see #6664).
