### ISSUE TITLE
Search icon in home should be clickable

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#2798]
### Description
This icon ![image](https://user-images.githubusercontent.com/11991428/38409721-c0ae9898-3982-11e8-8b0f-8510b17428ad.png) should be clickable and perform search

**Comment by MV88** [comment]
@tdipisa what about the dimensions of the icons?
both small or both big?

**Comment by tdipisa** [comment]
@MV88 'X' icon a bit smaller then the magnifying glass.
