### ISSUE TITLE
Add popover to *synch map* tool in the feature grid

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#2803]
### Description
the synch map tool is a bit hidden and we need to enhance its visibility

a solution is to add a popover the first time the application is launched and have the possibility to remove forever the popover with a flag

**Comment by chiaracurcio** [comment]
Note that the popup is not intuitive for a user, 
if you select the checkbox: 
- [ ] Don't show this message again
you'd expect that if you reopen the FeatureGrid you don't have any message, but it's not.
You have to close the popup with the X to save the save the change (but it is not intuitive).
