### ISSUE TITLE
mapOptions empty object saved in map config override localConfig mapOptions

### ISSUE THREAD

**Issue by mricca** [geosolutions-it/MapStore2#2811]
### Description
If users save or create a new map the option "mapOptions: {}" is added to map config 

https://github.com/geosolutions-it/MapStore2/blob/37367aefa6f4776be9f561be95e036a49c64b824/web/client/utils/MapUtils.js#L337

For example, in cesium viewer, https://github.com/geosolutions-it/MapStore2/blob/37367aefa6f4776be9f561be95e036a49c64b824/web/client/components/map/cesium/Map.jsx#L81 this.props.mapOptions is empty end this options https://github.com/geosolutions-it/MapStore2/blob/37367aefa6f4776be9f561be95e036a49c64b824/web/client/localConfig.json#L15 are overwritten and, in this case, terrainProvider is no longer present

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [X] Internet Explorer
- [X] Chrome
- [X] Firefox
- [X] Safari

*Steps to reproduce*
Open a map with no mapOptions in config.
Login
Save the map.
Now an empty mapOptions is present in config

*Expected Result*

- the user should see viewers with default mapOptions config

*Current Result*

- the user see viewers with empty mapOptions config

**Comment by tdipisa** [comment]
closed for inactivity.
