### ISSUE TITLE
Warning icon and message to improve in dashboard

### ISSUE THREAD

**Issue by chiaracurcio** [geosolutions-it/MapStore2#2822]
### Description
When we cannot use a layer for a specific widget the tooltip containing the warning appears immediately and the icon is a grey triangle + exclamation mark, in addiction we have this warning tooltip:

![i282 cimgpsh_orig](https://user-images.githubusercontent.com/33256901/38738889-94d66fb4-3f33-11e8-9acc-d9e0e086eb0f.jpg)

note that the grey triangle is not clear and the warnig message overlap the bar on the top

*Browser Affected*
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [ ] Safari

*Steps to reproduce*
- select for example this layer 'A sample ArcGrid file' from the widget list when you create a CHART WIDGET a TABLE WIDGET or a COUNTER WIDGET

*Expected Result*
- we have a more clear icon (yellow or orange) when we cannot use a layer for a specific widget 
- the warning window is not overlapped to the bar on the top

*Current Result*
- the grey triangle is not clear and the warnig message overlap the bar on the top

**Comment by tdipisa** [comment]
closed for inactivity
