### ISSUE TITLE
Tooltip to enhance and one little improvement

### ISSUE THREAD

**Issue by chiaracurcio** [geosolutions-it/MapStore2#2825]
## Description
Tooltip to enhance if a layer has not data in a table widget

![err](https://user-images.githubusercontent.com/33256901/38856035-936f8cb0-4225-11e8-8642-151bad277ce7.png)

### In case of Bug 
*Browser Affected*
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [ ] Safari

*Steps to reproduce*
- select a table widget
- select this layer: polygon
- check the box and note that no data are available for this layer

*Expected Result*
- a more clear tooltip appear when we try to following the wizard
- it could be usefull a notification to let you know that no data are available also when you try to check box

*Current Result*
- a not clear tooltip appear when we try to following the wizard (see the screenshot)

**Comment by chiaracurcio** [comment]
one other little improvement is also requested:
when the italian language is selected and you need to chose the tye of chart of the widget note that a little error is present in the following card:
_"Grafico a Linea
Crea un grafico a linea da aggiungere alla mapp"_

- note that the "**a**" is missing

![immagine](https://user-images.githubusercontent.com/33256901/38859857-330e55ea-422f-11e8-83a9-1b9653f1e2c5.png)

**Comment by offtherailz** [comment]
This issue happens also for charts and counters.
I added a more clear notification valid both for dashboard and widgets:
![image](https://user-images.githubusercontent.com/1279510/39037614-4d104fbc-4481-11e8-9266-9abb282e0e73.png)
 I'm going to provide this fix in the next PR

**Comment by chiaracurcio** [comment]
- note that the tooltip '!' (you must select at least one column) is not available if there aren't any attribute, example using the layer 'polygon' and a table widget: it could be improve
![immagine](https://user-images.githubusercontent.com/33256901/39115256-76debdee-46e1-11e8-9166-c5639050b703.png)


- note that after this, if you click 'back to the widget type selection' the feature grid opens in this strange way (note also tooltips):
![immagine](https://user-images.githubusercontent.com/33256901/39115392-d44ffc7c-46e1-11e8-8bc5-d38a36351ce4.png)

**Comment by tdipisa** [comment]
@chiaracurcio 
I think point #1 is not a problem.
The point #2 could be a bug introduced in the issue #2807 and this must be absolutely fixed @MV88

**Comment by offtherailz** [comment]
@chiaracurcio could i change it to "The selected layer has no attributes to show. Please select another widget type or layer" ?
This message is the same for dashboard and map widgets workflow, so it should be usable in both cases.

**Comment by chiaracurcio** [comment]
yes, it might be good
