### ISSUE TITLE
add layer permission

### ISSUE THREAD

**Issue by joagomes7** [geosolutions-it/MapStore2#2837]
Hi. i am Joao from portugal and I would like to know how can I hide the option to add layer to a map where it only has read permissions? basically I would like to hide this option from the "burger menu" and from the layers tab "Add Layer"

**Comment by tdipisa** [comment]
@joagomes7 I think we have lost this for a while, I'm really sorry. I'm going to close this issue for inactivity now. If you still need support on this please, send an email to the dev mailing list for this kind of topics. You can join the list from the MS2 demo home page [here](https://mapstore2.geo-solutions.it/mapstore/#/)
