### ISSUE TITLE
Red screen error on catalog

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2883]
### Description
TypeError: Cannot read property 'type' of undefined

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- all

*Steps to reproduce*

- open a map
- open catalog
- click on clear catalog before it ends to load

*Expected Result*

- end loading

*Current Result*

- error

### Other useful information (optional):
gif below
![error catalog](https://user-images.githubusercontent.com/19175505/39917029-920b46a8-550c-11e8-8682-73147e9d7984.gif)

**Comment by MV88** [comment]
just a note, clear the browser cache before reproducing it.
if you reload and then try to reproduce it again, it does not display the error page
