### ISSUE TITLE
Embed functionality conflicts with video embedding

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2885]
### Description
Makes the detail card video embedding not working.
### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
any
*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*
 - Create a detail sheet for a map
 - Try to embed a video
 - Save the map (click on save and then save again on the map properties window)
 - Reopen the detail card

*Expected Result*
 - I can see the video as in the preview

*Current Result*
 - You can not see the video saved
 - Sometimes you can see the viedeo but in view mode you can see this text:
```
ï»¿
```

**Comment by chiaracurcio** [comment]
only using firefox browser V62.0.2
i can't save the detail card with the video
i have this error message:
![immagine](https://user-images.githubusercontent.com/33256901/46214845-43568d80-c33c-11e8-8f90-a6d762cdf844.png)

steps are:
- create a new map and save it
- open the 'Edit Map Properties' in the map card of this saved map
- Add New Details' and verify the possibility to add a video entering the embedded URL
- save
- save the detail card (the Edit Map Properties window)
- Then verify you can save the detail card with the added video 'Success - The details have been saved correctly'
- Then verify you can open the detail card with de video saved: you can see the viedeo correctly

note: using Chrome and Explorer you can do it correctly, there are problems only using Firefox

**Comment by tdipisa** [comment]
@baloola, fix needed. This issues has been meved back on ready status.
