### ISSUE TITLE
Layers support for Leaflet Map Component

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#29]
Implement layer support and configuration for the following layer types:
 * background layers:
  -  OSM / MapQuest
  - Google / Bing
  - WMS(T) - TMS
  - None

**Comment by offtherailz** [comment]
Many issues using leaflet plugins dependencies:
* the leaflet-plugins module on npm doesn't supports modules. 
* tried to use a module friendly tarball from a pull request. Now google doesn't seems to work. 

Check this Work in progress for details : https://github.com/offtherailz/MapStore2/tree/googlebing_support
