### ISSUE TITLE
Enhancements to the locate me tool

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#290]
* [ ] Locate me tool now tracks by default. This should be an option in the settings panel. 
* [ ] The icon should be something like [this one](http://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_ref_glyph_screenshot&stacked=h) to avoid confusion with markers on the map

**Comment by simboss** [comment]
Question, why we did not create a mock-up BEFORE doing the work?

**Comment by offtherailz** [comment]
The mockup was in the issue : https://github.com/geosolutions-it/MapStore2/issues/144 and has been created before the work.

**Comment by kappu72** [comment]
As we discuss in  our meeting at Geosolutions, to avoid to much configuration I suggest to do the same as other mapping library:
When users pushes button, locate tool is active and following, as user drags map, the tool will be still active but not following.
Do you agree?
For the icon sorry it's my fault.
Waiting for comments before proceeding

**Comment by offtherailz** [comment]
Right, let's move on.
