### ISSUE TITLE
Update to future AGI terrain provider policies

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2928]
### Description
AGI will not provide terrain from Sept the 1st, 2018. [see this](https://cesium.com/blog/2018/03/01/introducing-cesium-world-terrain/). 
We disabled the terrain background that has been discontinued.

We have to to investigate how to update cesium support in MapStore, together with the library version, accordingly to new policies (api keys, other settings, update cesium version if needed...) in order to use  new terrain models provided by AGI

**Comment by tdipisa** [comment]
closed for inactivity
