### ISSUE TITLE
USER Permissions don't return correctly from GeoStore with Basic Authentication

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2946]
### Description
USER Permissions don't return correctly from GeoStore with Basic Authentication.
GeoStore authentication rules need to be configured with "method": "basic"

### Dependencies 
 - Blocked by https://github.com/geosolutions-it/geostore/issues/182

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Chrome v66

*Steps to reproduce*

- login as USER
- create a new map
- save map
- back to home page
- open saved map or click on map settings (wrench button)

*Expected Result*

- USER can access to map and settings

*Current Result*

- USER can't access to map and after clicking on wrench button list of maps disappear

**Comment by tdipisa** [comment]
closed for inactivity
