### ISSUE TITLE
Feedback Not clearly visible when adding an image (>500 KB) in the Details section for the map

### ISSUE THREAD

**Issue by fouad-semaan** [geosolutions-it/MapStore2#2954]
![image](https://user-images.githubusercontent.com/38422316/40660347-010a2dc4-6351-11e8-9493-d7acb5d545fb.png)

![image](https://user-images.githubusercontent.com/38422316/40660456-586ed362-6351-11e8-937f-ed793dd783cf.png)

**Comment by MV88** [comment]
closed in favor of #2964

**Comment by tdipisa** [comment]
closed for inactivity.
