### ISSUE TITLE
TOC - On the Layers list menu, the tooltip title is "Display" for displaying and hidding the legend.

### ISSUE THREAD

**Issue by fouad-semaan** [geosolutions-it/MapStore2#2955]
![image](https://user-images.githubusercontent.com/38422316/40660723-3169a11a-6352-11e8-9894-b2d29d4c1524.png)

  ---------------------------------------------------

![image](https://user-images.githubusercontent.com/38422316/40660769-59bd6994-6352-11e8-94db-7315948abdd0.png)

**Comment by tdipisa** [comment]
We are reviewing the entire MS's layout (closed in favor of #4254).
