### ISSUE TITLE
Authentication Popup

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#2965]
### Description
If an anonymous user accesses a map without having rights a login dialog should be provided instead of showing the following:

![xsxsxweew](https://user-images.githubusercontent.com/1280027/40829518-fc2cdef2-6583-11e8-8f0c-1d13f6740f46.png)

Currently the user has to manually open the login form. 

![efewfw](https://user-images.githubusercontent.com/1280027/40829603-3cda33b4-6584-11e8-9ae9-627d8a2b89d2.png)

**Comment by simboss** [comment]
I don't think this is a real fix, IMHO this introduces more confusion:

1. I don't want to see that criptic error message. I don't want to see any error message at all! We should just show the login form and that is it.
2. If I close the login form I should be sent back to the mapmanager. Right now if I close the login form by mistake I am left with a blank map and a criptic red error message which just confuses me.

This is not rocket science, we just have to create a simple, decent login form with a predictavle behavior. Can we? :)
