### ISSUE TITLE
Add autocomplete in cross layer filter

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2972]
### Description
Cross layer filter attribute filter should allow autocomplete. 

![2021_03_12_17_34_56_MapStore_HomePage](https://user-images.githubusercontent.com/1280027/110970039-a2b48680-8359-11eb-9b27-e37ba77cfddc.png)

### Acceptance Criteria (AC)
- Attribute Filter in cross layer filter should allow autocomplete as for the Attribute Filter of the query panel

![image](https://user-images.githubusercontent.com/1280027/110970566-2a9a9080-835a-11eb-9644-6bb7e2028a98.png)

**Comment by ElenaGallo** [comment]
@MuhweziDeo a note after testing this issue:

Scrolling through the list, with the left/right arrow buttons, the drop-down menu is closed

**How to Reproduce**
See the gif below:
![list](https://user-images.githubusercontent.com/56537133/114748715-77ef9080-9d52-11eb-948c-315949c89820.gif)


*Curret Result*
The is no longer visible if you go forward/backward in the list though the left/right arrow button.

*Expected Result*
The list remains visible in the drop-down menu

**Comment by tdipisa** [comment]
@ElenaGallo below is a gif that shows how the same component is working for the above filter. We should have at least the same behavior.

![autocomplete](https://user-images.githubusercontent.com/1280027/114837596-2be53000-9dd4-11eb-94ad-5bbee4e70c0f.gif)
