### ISSUE TITLE
Limit the zone where draggable dialogs can be dragged or change them

### ISSUE THREAD

**Issue by chiaracurcio** [geosolutions-it/MapStore2#3025]
### Description
Opening the ABOUT window from the BURGER MENU' (menù options) you can move this window also outside the screen but after this you can't close the window using the X.

### In case of Bug (otherwise remove this paragraph):
*Browser Affected*
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [ ] Safari

*Steps to reproduce*
- Open a new map
- open the burger menù
- open the ABOUT option
- move the window outside the screen 
- try to close using the X

*Expected Result*
- you can't move the window outside the screen and you can close the window using the X 

*Current Result*
- you can move the window also outside the screen but after this you can't close the window using the X.

![immagine](https://user-images.githubusercontent.com/33256901/41764956-e95daf92-7602-11e8-8b7f-ccb8a48e5d45.png)

**Comment by MV88** [comment]
This happens with all the draggable dialogs (Print, Measure, Settings, Share, Shapefiles)
I think is better to generalize the title of this issue

**Comment by chiaracurcio** [comment]
This is correct, this happens also with all other draggable dialogs you mentioned.

**Comment by kasongoyo** [comment]
@chiaracurcio I see I can move it outside the screen but as long as *X* is still visible then on click, it close the draggable. Can you confirm this behaviour that the X button works regardless

**Comment by chiaracurcio** [comment]
yes i confirm that (the X button works regardless of the position of the draggable) 
but please note that you can't click the X of this window if you move it outside the screen because you are not able to move it again if you want to close after those action
