### ISSUE TITLE
Openlayers button to restore the north orientation is covered by the toolbar

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#303]
On mobile devices, OpenLayers shows an additional button to reset the map orientation when changed (rotating with 2 fingers). This tool is overlapped by the MapStore's map toolbar.

**Comment by offtherailz** [comment]
now it is not covered anymore. Maybe we can add a better style for it. 
![image](https://cloud.githubusercontent.com/assets/1279510/17177199/8f4f98aa-5410-11e6-92ac-4957c52e5c7c.png)

**Comment by MV88** [comment]
You can rotate the map on desktop mode on openlayers using ALT + SHIFT pressed together

**Comment by tdipisa** [comment]
Added more styling capabilities in 2018.02.00
