### ISSUE TITLE
Error in layer properties Title field for Annotations layer

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#3040]
### Description
The application throws an invariant error in console that makes the application unusable.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Chrome 67.0.3396.99

*Steps to reproduce*

- open a map with annotations or create a new annotation
- open TOC
- open layer settings for Annotations and title will be empty
- insert some data in title input field
- try to clear the input field (remove all chars)

*Expected Result*

- you can delete all the chars

*Current Result*

- the applications throws an error in **Console** and you cannot use the application

**Comment by tdipisa** [comment]
The annotation layer title does not appears in the new legend panel

![clipboard01](https://user-images.githubusercontent.com/1280027/43324937-9da6f74c-91b5-11e8-8b00-476579c0b8b5.png)

**Comment by MV88** [comment]
I suggest to use the name of the layer as a default value and contextually add the title to the annotations layer
