### ISSUE TITLE
Create a GeoServer instance dedicated to MapStore

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#3063]
### Description
Create a geoserver instance dedicated to MapStore demo and integrated with it for authentication.
The ideal solution is to 2 different instances for demo  (current release) and for test. 

This allows a series of improvements: 
 - Easier testing of GS integration 
 - Devs and PMs can manage layers for Test and demo purposes

**Comment by tdipisa** [comment]
Closed in favour of #3200
