### ISSUE TITLE
Legend no more shows the missing message 

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#3075]
### Description
If you try to load the legend from layer MARCIAPIEDE it should show the message error "Legend is not available"
This layer is available only on Genova test env

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- Login and open a new map
- Add MARCIAPIEDE layer and open TOC
- Click on > to show the legend of that layer

*Expected Result*

- The message "Legend is not available" should appear

*Current Result*

An image of 1px x 2 px is shown (i.e you can't see it because has the same color of the background)

**Comment by offtherailz** [comment]
The 1×2 legend is generated by default when getlegendgraphic has no legend to render (eg no rule to match for the zoom level) or it is only a specific issue for this layer?
