### ISSUE TITLE
Flickering loading in TOC

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#3092]
### Description
Flickering of loading icon on TOC layers should be reduced.
This is visible with more than 4 layers.
![loading_pulse](https://user-images.githubusercontent.com/19175505/42885384-15f3a64e-8aa1-11e8-90f4-237949794cbd.gif)

**Comment by tdipisa** [comment]
We are reviewing the entire MS's layout (closed in favor of #4254).
