### ISSUE TITLE
Improve performances when loading map with a great number of layers (~30)

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#3093]
### Description
Loading a map with a lot of layers (~roughly 30) slows down the entire application

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Chrome 67.0.3396.99

*Steps to reproduce*

- create a map with a lot of layers (30) or try to load one if already exists
- set all layers visible
- save it.
- load it
- try to pan zoom ecc.

*Expected Result*

- At least one can easily disable visibility of the layers
- Any other suggestion are welcome

*Current Result*

- the site is stuck and it has high latency for responding to user actions

**Comment by tdipisa** [comment]
closed for inactivity
