### ISSUE TITLE
Improvements for create project script and/or Standard files

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#3098]
### Description
It would be nice to have a reduced/custom configuration for the standard project.
Actually it uses the the one present in web/client folder.

Can it be created a filterConfiguration.json where you place list of paths and values to be excluded in order? @mbarto opinions?

for example in the standard project it is not need some of the plugins like MailingLists or Fork.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- run [createproject ](https://dev.mapstore.geo-solutions.it/mapstore/docs/project-creation-script) script
for example:
use a proper value for repo and outputFolder  (create it before running the script) 
`node createproject,js standard name version desc repo outputFolder`

*Expected Result*

- you find in the root of the project the reduced localConfig

*Current Result*

- it uses the one present in MapStore2/web/client/

**Comment by mbarto** [comment]
We should distinguish the demo site from the standard product.

The standard product should not have the demo site homepage, but only a simplified one.

So, I would go the other way around: 
 * simplify configuration for the standard product, removing "demo" only plugins. This will build  the downloadable war for the user.
 * have a distinct configuration / build that will be used for publishing the demo site: this should be put OUTSIDE of the product folder (e.g. /web/client/demo)

**Comment by tdipisa** [comment]
Closed in favor of #6314
