### ISSUE TITLE
Print a map is unstable with respect to zoom levels or Sheet size

### ISSUE THREAD

**Issue by fouad-semaan** [geosolutions-it/MapStore2#3104]
### Description
Changing the zoom level in the print preview then printing or changing the Sheet size gives two errors types:
1) Stretched layout 
2) Blank layout

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
- All

*Steps to reproduce*

1) Stretched layout
- Open a map with a vector layer, specifically open this one https://dev.mapstore.geo-solutions.it/mapstore/#/viewer/openlayers/3264
- zoom in/out the map  
- From the main menu, click on print. Leave the default options then print.
  
![image](https://user-images.githubusercontent.com/38422316/43065239-83a0be16-8e61-11e8-8fb4-4f1d14399580.png)

- You will get a stretched layout

![image](https://user-images.githubusercontent.com/38422316/43065279-a6bddbea-8e61-11e8-9cad-62102f8d22af.png)

2) Blank layout
- Zoom out in order to see all the north american continent in the preview

![image](https://user-images.githubusercontent.com/38422316/43065470-3a1a36f4-8e62-11e8-93f9-0277ded56a5e.png)

- Leave the default options then print, you will get a blank layout
![image](https://user-images.githubusercontent.com/38422316/43065503-567a3a06-8e62-11e8-900e-777e6592d324.png)

### Other useful information (optional):
Try it also changing from A4 to A3 and Portrait to Landscape. 
Moreover try to zoom out in order to see all the world map in the preview. You will get this error

![image](https://user-images.githubusercontent.com/38422316/43065708-ee3538be-8e62-11e8-9ab8-0fa5e6c67113.png)

**Comment by mbarto** [comment]
The issue is caused by the geodetic flag set to true by default: https://github.com/geosolutions-it/MapStore2/blame/master/web/client/utils/PrintUtils.js#L154

We should set it to false by default. The original fix was to allow override, setting it to true by default was probably not needed, and caused more issues than it solved. I will create a PR to set it to false again by default.
