### ISSUE TITLE
Improvement on Error Feedback when saving a map containing a big local shapefile

### ISSUE THREAD

**Issue by fouad-semaan** [geosolutions-it/MapStore2#3105]
### Description
- Add a big local shapefile to the map
- Saving the map, it takes long time to receive the following feedback
![image](https://user-images.githubusercontent.com/38422316/43069561-ae9571fa-8e6d-11e8-893d-a7430bb37569.png)
- Adding a spinner highlighting that something is happening behind the scenes?
- Now, remove the shapefile from the map then retry to save it, You will get this massage: 
![image](https://user-images.githubusercontent.com/38422316/43069681-08e52452-8e6e-11e8-870c-425593661dba.png)

**Comment by tdipisa** [comment]
closed for inactivity
