### ISSUE TITLE
Improvements on floating legend plugin

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#3109]
### Description
Improvements:
- Resizing of legeng should start only when it recieve all lagend images to fit correctly the content
- Layers should not disappear from Floating Legend but should display their status ( eg. layer with error should be displayed similar to TOC with exclamation mark icon)

in general we should avoid unexpected visual changes (eg.: layer disappearing due to change of status)

**Comment by tdipisa** [comment]
@allyoucanmap Can we also use the same dimensions of the legend in TOC

**Comment by tdipisa** [comment]
The floating lagend plugin is no longer maintained, I'm going to close this issue for now: we are reviewing the entire MS's layout (#4254).
