### ISSUE TITLE
Measure tool graphical limitations 

### ISSUE THREAD

**Issue by fouad-semaan** [geosolutions-it/MapStore2#3110]
Since the tool measures a Geodetic distance, it has some graphical limitations when measuring long distances. There are two cases:

- It does not show the geodetic line:
1) Try to measure horizontally a long distance
![image](https://user-images.githubusercontent.com/38422316/43195317-0328876e-9005-11e8-86ed-e81dac498c85.png)
2) You will get only the tool tip distance
![image](https://user-images.githubusercontent.com/38422316/43195376-3022b23a-9005-11e8-8ece-c60260eb1412.png)

- It draws non significant geometries:
1)  Try to measure diagonally a long distance
![image](https://user-images.githubusercontent.com/38422316/43195500-85171010-9005-11e8-9c87-106896e21de7.png)
2) You will get these kinds of geometries 
![image](https://user-images.githubusercontent.com/38422316/43195545-a9ce0db4-9005-11e8-840e-9c1bef3845b6.png)
![image](https://user-images.githubusercontent.com/38422316/43195575-bec5fc04-9005-11e8-94c5-3220afd818e2.png)

A solution could be to plot the measure value (the geodetic distance value) and to plot a straight line between the two points since we are in 2D. Suggestions?

**Comment by tdipisa** [comment]
closed for inactivity
