### ISSUE TITLE
Region of interest Filter: Applying the BoundingBox as Geometric Operation does not make sense 

### ISSUE THREAD

**Issue by fouad-semaan** [geosolutions-it/MapStore2#3112]
The BoundingBox does not make sense as a Geometric operation since it is not an operation indeed applying it with the Filter Type list (Rectangle, Circle, Polygon) generates a simple intersection with an erroneous CQL query. 
![image](https://user-images.githubusercontent.com/38422316/43196767-539ec79a-9009-11e8-9c4a-feb8bab4d564.png)

Could not parse CQL filter list. Encountered "Polygon" at line 1, column 17. Was expecting one of: "-" ... <INTEGER_LITERAL> ... <FLOATING_LITERAL> ... Parsing : (BBOX(the_geom, Polygon((223847.3958022772 4552853.567227472, 213513.7511261719 4271833.729053922, 634804.0826114463 4267843.5149840405, 629946.5035265995 4548798.018170883, 223847.3958022772 4552853.567227472))))

**Comment by tdipisa** [comment]
@offtherailz can we remove BoundingBox from configuration?
