### ISSUE TITLE
Update Cesium Terrain

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#3134]
### Description
Cesium default terrail will be remove soon, we should align. @tdipisa This may need to be included in the current release ( or in a next minor )
![cesium](https://user-images.githubusercontent.com/1279510/43507787-4f8e3db0-956e-11e8-8720-0c01f36e447f.jpg)

**Comment by offtherailz** [comment]
We have to 2 two things: 
 - remove default terrain because It's going to be dismissed
 - Provide support for API keys (If to hard, open a separate issue for that)

**Comment by baloola** [comment]
The default terrain removal is currently applicable.
The alternative function that requests the terrain data from cesium new server (from 1st September with a key) requires Cesium >= 1.43.
[https://cesium.com/blog/2018/03/01/introducing-cesium-world-terrain/](url)
