### ISSUE TITLE
Repeated get feature info requests cause visual glitch if widgets are on map

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#3138]
### Description

Widgets are appearing/disappearing every get feature request.

![w_glitch](https://user-images.githubusercontent.com/19175505/43586928-3c650880-9669-11e8-963a-b220179e9089.gif)

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- v68.0.3440.84

*Steps to reproduce*

- open a map with widgets
- click on map
- Identify panel shows up and widget disappear
- click again on map

*Expected Result*

- Identify panel is open and a new response will be displayed

*Current Result*

- Identify panel is open and a new response will be displayed and widgets appear/disappear

**Comment by MV88** [comment]
This bug (or a very similar one) appeared again use this map on DEV with id [3264](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/3264)

![widgets_blinking_with_gfi](https://user-images.githubusercontent.com/11991428/53094528-a4187980-351a-11e9-92de-c72e4424ebc4.gif)

**Comment by tdipisa** [comment]
This regression affects also QA so needs to be solved before the release.

**Comment by offtherailz** [comment]
It affects also 2018.02.00. (anyway it was solved for that release). I'm trying to find out the reason why this problem has not been solved.
