### ISSUE TITLE
Proposal for a new GetDomainValues endpoint for Geoserver's mutidim extension

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/MapStore2#3145]
@offtherailz @aaime @nmco this proposal is for the creation of a new **GetDomainValues** endpoint to the [WMTS MultiDimensional extension](http://docs.opengeospatial.org/per/16-042r1.html).

The goal is to let a client request **a (paged) list of sorted unique domain values lower / greater then a certain value**.

### Description

The following request parameters should be implemented:

- **LAYER**: the (multi) dimensional layer we're asking the domain values
- **DimensionIdentifier**: the parameter will be the name of the LAYER's dimension we're querying (obtained from the GetCapabilities or the DescribeDomain results). The value is the lower / upper inclusive domain value
- **ORDER**: optional value to set the ordering, which also defines if the DimensionIdentifier value must be considered **gte** or **lte**. The parameter values can be **asc | desc** (asc will be the default)
- **LIMIT**: number of unique values we want to obtain, capped by a fixed limit configured server side (max_page_values). I.e. the number of returned values will be **min(LIMIT,max_page_values)**

To make the request truely "paged" another **OFFSET** parameter would help the client building the next requests. This parameter sets the unique domain values index offset starting from the DimensionIdentifier value. 
E.g. give the next 20 values after the first 60 values (offset), starting from 2017-08-01T00:00:00.000

The OFFSET is not a hard requirements but a nice to have if not too much complicated to implement.

### Sample requests

- http://server.com/ows?Service=WMTS&Request=GetDomainValues&Layer=<layername>&time=2017-08-01T00:00:00.000&Limit=20
  
  will return the next 20 (or max_page_values) unique time values since 2017-08-01T00:00:00.000

- http://server.com/ows?Service=WMTS&Request=GetDomainValues&Layer=<layername>&time=2017-08-01T00:00:00.000&Limit=20&Offset=20&Order=desc
  
  will return the previous 20 (or max_page_values) values, before the first 20, since 2017-08-01T00:00:00.000

**Comment by mbarto** [comment]
I don't realize why this should be a MapStore2 issue...

**Comment by giohappy** [comment]
@mbarto it was a suggestion from @aaime to keep it somewhere in our repos. We don't have a repo for that, and it's a requirement stemming from the MapStore Timeline development.

**Comment by aaime** [comment]
Yep... we could have kept it in the GeoServer Jira, but then our discussion would have been public (not so nice since we don't have a clear idea yet) and the Jira is a giant mess, hard to find something in it.

**Comment by mbarto** [comment]
Also this one is a public place, where people discuss about MapStore2

**Comment by giohappy** [comment]
https://github.com/geosolutions-it/smb-portal/issues/122
