### ISSUE TITLE
Embedded doesn't work on ie11

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#3153]
### Description
Embedded displays blank page with infinite loading spinner instead of the selected map.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- ie11

*Steps to reproduce*

- open an embedded map with ie11 eg. /mapstore/embedded.html#/356

*Expected Result*

- embedded will show up

*Current Result*

- blank page with infinite loading spinner

**Comment by MV88** [comment]
after a quick debug i've found this message in console appears only for embedded:
```
SCRIPT5007: Impossibile recuperare la proprietà 'apply' di un riferimento nullo o non definito
d=Object.assign.apply(Object,[{}].concat(s(c(this.props,this.state)))),
```
and if i try to load a new map (not in embedded mode) i get this instead:
```
L'oggetto non supporta la proprietà o il metodo 'closest'
return e&&l&&n?e.closest(n||"*")
```

**Comment by mbarto** [comment]
It looks like embedded page is missing polyfills for Object.assign. The viewer page has them. Not clear how they are included / not included in the two pages.

**Comment by offtherailz** [comment]
We use everywhere spread operator or `object-assign` from npm. 
I see only these usages of Object.assign.
![image](https://user-images.githubusercontent.com/1279510/44648547-affb0700-a9e1-11e8-9ca5-fc0733ff9737.png)

You can replace them with `object-assign` and everything should work. Probably some dependency adds a polyfill in the viewer, but it's included by a plugin that is not present in the embedded version.

**Comment by MV88** [comment]
I have checked this and it turns out that this problem is related to [this issue](https://github.com/geosolutions-it/MapStore2-c126/issues/4)

By fixing that i got another error, only for IE11, which i need more investigation.

although I agree that we can replace the Object.assign with the object-assign
