### ISSUE TITLE
First point annotation has unknown icon [ ] 

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#3155]
### Description
font-awsome icon is not correctly render on first Annotation point

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Chrome v68

*Steps to reproduce*

- open a map
- refresh the page
- open annotations panel from burger menu
- add a new point Annotation
- add a point geometry on map
- click on map

*Expected Result*

-  The icon should be the one showed in the select form

*Current Result*

-  ![2018-08-09 14_45_59-mapstore homepage](https://user-images.githubusercontent.com/19175505/43899784-4bb2393c-9be3-11e8-8074-706cea44fd2d.png)

**Comment by tdipisa** [comment]
@baloola if the fix is trivial, please proceed.

**Comment by MV88** [comment]
found a reference [here](https://stackoverflow.com/questions/48208570/how-to-wait-for-css-when-using-icons-in-openlayers-markers)
