### ISSUE TITLE
Annotation can not be removed from delete button in MapInfo context

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#3174]
### Description
MapStore shows a special MapInfo when an annotation is clicked. The Delete Button doesn't seem to work in this context.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
any

*MapStore 2 Version Affected*

- 2018.01.00, 2018.02.00, master

*Steps to reproduce*

- Open a [map with annotations](http://localhost:8081/#/viewer/openlayers/3109) or create annotation on a new map
- Click on the annotation marker
- Click on the remove button in the map info

*Expected Result*

- A confirm window is shown and then, if confirm, the annotation is removed

*Current Result*

- Nothing happens

**Note**: Also trying to edit the annotation using "Edit" and then click on the thrash icon do not work

This may become obsolete when #3127 is solved.

**Comment by tdipisa** [comment]
@baloola if the fix is trivial, please proceed.

**Comment by MV88** [comment]
the map with id 3109 has been removed,  I have created the map with id [8654](http://localhost:8081/?debug=true#/viewer/openlayers/8654)
