### ISSUE TITLE
Long title rendering issue in Internet Explorer 

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#3179]
### Description
Originally reported by @chiaracurcio 
note that using the Explorer browser the title is cutting it in 2 row when you shrink the chart area (the problem coul be that the title is placed even below the chart in this way):
![immagine](https://user-images.githubusercontent.com/33256901/44992258-0c889400-af97-11e8-9d26-eec3f83dd70a.png)

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- 11

*Steps to reproduce*

- Open MS2 with Internet Explorer 
- Create a widget with a long title (like the picture

*Expected Result*

- The title disappears

*Current Result*

- The title goes behind the chart

**Comment by tdipisa** [comment]
IE is not longer supported, closing
