### ISSUE TITLE
Print: uncorrect layout when you zoom out (too much) the map

### ISSUE THREAD

**Issue by chiaracurcio** [geosolutions-it/MapStore2#3198]
### Description
You get an uncorrect layout when you zoom out (too much) the map

*Browser Affected*
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [ ] Safari

*Steps to reproduce*
- open this map https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/3264
- open the print tool 
- zoom out the map (in order to see more than a world map in the preview)
![i367 cimgpsh_orig](https://user-images.githubusercontent.com/33256901/45946723-0ca60d80-bff2-11e8-8e08-f0ffcda3d7c5.jpg)
- click print

*Expected Result*
- you see a correct preview with only a map replicated (and not outside the map box area)

*Current Result*
- you get this layout:
![immagine](https://user-images.githubusercontent.com/33256901/45946772-319a8080-bff2-11e8-9d48-11efd4f7d5ca.png)

**Comment by tdipisa** [comment]
closed for inactivity
