### ISSUE TITLE
Support Domain Sharding Configuration

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#3208]
### Description
Actually mapstore supports domain sharding only inside the map's JSON configuration. We should allow to configure domain sharding also through the UI. 

### Acceptance Criteria
 - A user should be able to edit the WMS/WMTS base URL and add multiple domains to the list, from the layer properties
 - Evaluate the possibility to configure a catalog that automatically configure this for every layer coming from the service

**Comment by tdipisa** [comment]
There was an existing issue for this (#3194), already opened some time ago. I'm going to mark it as duplicate in favour of this.

**Comment by MV88** [comment]
Another Acceptance Criteria is:
- it should be possible to edit layer settings

at the moment if you open [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/8208) map that has a layer configured to use domain sharding it throws an error if you try to open the layer settings

**Comment by tdipisa** [comment]
We already support this in the Catalog tool where it is possible to provide multiple URL comma separated for WMS Catalog type. We can consider more UI enhancements for the future with dedicate issues.
