### ISSUE TITLE
Fix potential security vulnerabilities in project dependencies

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#3217]
### Description
A dependency defined in package.json has known [security vulnerabilities](https://github.com/geosolutions-it/MapStore2/network/dependencies) and should be updated.

**Comment by baloola** [comment]
The security venerability  is caused by the bootstrap version used in MapStore2, the github notifications recommends upgrading to bootstrap 4.
A first look at the possibility of upgrading to bootstrap 4 shows a problem, which is that bootstrap 4 uses SASS instead if LESS.

**Comment by mbarto** [comment]
Upgrading is a lof of effort, we should also migrate from react-bootstrap to reactstrap (that supports bootstrap 4, while react-bootstrap only supports 3).
It's not worth doing it only for a vulnerability (that I suspect also cannot happen the way we use it in MS2).

**Comment by offtherailz** [comment]
I agree with @mbarto , the migration is very hard. 
I suggest to check what this vulnerability exactly is and if it affects also MapStore.
If it doesn't affect MS2 we could find an easy way to mute this alert, otherwise plan the update, but in this case the effort changes a lot

**Comment by tdipisa** [comment]
@baloola, since this is a moderate alert we can decrease the priority of the issue and plan  the update later. I'm going to close it for the moment.

**Comment by zachsa** [comment]
Why was this closed without a fix applied? Github is actually flagging quite a few security vulnerabilities now:

![GitHub security warnings](https://user-images.githubusercontent.com/6336500/60811657-0e5f4d00-a190-11e9-8ae5-5e30abab750f.PNG)

**Comment by zachsa** [comment]
Doing an `npm install`, I get the following list of deprecated dependencies:

```
npm WARN deprecated babel-istanbul-loader@0.1.0
npm WARN deprecated babel-preset-es2015@6.6.0
npm WARN deprecated extract-text-webpack-plugin@2.1.0
npm WARN deprecated ag-grid@3.3.3
npm WARN deprecated @turf/inside@4.1.0
npm WARN deprecated json-2-csv@2.1.2
npm WARN deprecated openlayers@4.6.4
npm WARN deprecated @turf/polygon-to-linestring@4.1.0
npm WARN deprecated turf-bbox@3.0.10
npm WARN deprecated turf-buffer@3.0.10
npm WARN deprecated turf-intersect@3.0.10
npm WARN deprecated turf-point-on-surface@3.0.10
npm WARN deprecated turf-union@3.0.10
npm WARN deprecated minimatch@2.0.10
npm WARN deprecated jade@0.26.3
npm WARN deprecated istanbul@0.4.5
npm WARN deprecated core-js@2.3.0
npm WARN deprecated doc-path@1.2.0
npm WARN deprecated nomnom@1.8.1
npm WARN deprecated intl-relativeformat@1.3.0
npm WARN deprecated core-js@2.4.1
npm WARN deprecated turf-meta@3.0.12
npm WARN deprecated geojson-normalize@0.0.0
npm WARN deprecated turf-combine@3.0.12
npm WARN deprecated turf-helpers@3.0.12
npm WARN deprecated turf-distance@3.0.12
npm WARN deprecated turf-center@3.0.12
npm WARN deprecated turf-inside@3.0.12
npm WARN deprecated turf-explode@3.0.12
npm WARN deprecated core-js@1.2.7
npm WARN deprecated minimatch@0.2.14
npm WARN deprecated graceful-fs@2.0.3
npm WARN deprecated turf-bbox@3.0.12
npm WARN deprecated turf-invariant@3.0.12
npm WARN deprecated browserslist@1.7.7
npm WARN deprecated hawk@3.1.3
npm WARN deprecated graceful-fs@3.0.11
npm WARN deprecated json3@3.3.2
npm WARN deprecated flatten@1.0.2
npm WARN deprecated hoek@2.16.3
npm WARN deprecated sntp@1.0.9
npm WARN deprecated cryptiles@2.0.5
npm WARN deprecated boom@2.10.1
npm WARN deprecated natives@1.1.6
npm WARN deprecated uws@9.14.0
npm WARN deprecated graceful-fs@1.2.3
```

**Comment by mbarto** [comment]
This one has been closed because we opened another issue to keep track of needed updates: https://github.com/geosolutions-it/MapStore2/issues/3528
That said, thanks for notifying us of security vulnerabilities. If you could also provide pull requests to solve some of them it would be greatly appreciated!

**Comment by zachsa** [comment]
I would love to contribute! When I finally figure out how to use the
software I will do so!

Zach
