### ISSUE TITLE
Circle drawn by LeafletDraw 1.0.x is not the same calculated for the filter

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#3244]
### Description
The circle drawn by leaflet is not the same used in the spatial query filter. 

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Chrome 69.0.3497.100

*Steps to reproduce*

- Open a map (USA) with leaflet and the query form of it 
- Draw a circle like this
![image](https://user-images.githubusercontent.com/11991428/47076639-75eafc00-d1ff-11e8-8a8a-2941f6aa9c9e.png)
- Click on Search

*Expected Result*

- Some results returned, the form of the circle does not change

*Current Result*

- there are no results because the circle used is calculated in another (old) way
![image](https://user-images.githubusercontent.com/11991428/47076915-222ce280-d200-11e8-9457-fd0e0e9ee5f9.png)

### Other useful information (optional):

The problem is that there is a difference from leaflet draw 0.7x to 1.0.x in the way the circle is drawn
and in particular [here](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/map/leaflet/DrawSupport.jsx#L238)

**Comment by tdipisa** [comment]
closed for inactivity
