### ISSUE TITLE
TimeLine - Guide Layer support

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/MapStore2#3253]
Guide layer is meant to provide the points in time for marker and animation snapping.
When no guide layer is selected no snapping is applied: the marker is set exactly where the user drops it, animation will move according to a default configuration or configuration values set by the user through the animation panel options.

see also #3225

**Comment by offtherailz** [comment]
This was fixed by #3247. Waiting for some tests in the next few days, when everything is merged in geonode_integration branch
