### ISSUE TITLE
3D map needs CORS

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#3255]
### Description
Adding a new GeoServer in the catalog and adding layers to the map works.
The 3D map will work only if the GeoServer have CORS headers allowing MapStore to use its resources.

So if you don't set CORS, the 2D map will work because it uses the proxy, but the 3D map will not.

I suggest to disable the 3D map button when the GeoServer instance must rely on the proxy to work.

**Comment by mbarto** [comment]
Can't we use proxy also in CesiumJS when needed?

**Comment by tdipisa** [comment]
closed for inactivity.
