### ISSUE TITLE
3D map should never use single tile option

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#3258]
### Description
If a layer is set to use "Single Tile", the 3D map will not display the correct resolution

The single tile will be earth sized, so it will appear badly when zooming in.

In this image I am in 3D mode, with the tiled background, and a single-tiled overlay.
The overlay appears out of focus.

![3d_tiles](https://user-images.githubusercontent.com/3932165/47158133-44e7f580-d2eb-11e8-8db4-754632e97d15.PNG)

**Comment by tdipisa** [comment]
closed for inactivity.
