### ISSUE TITLE
UI for the auto-refresh layer feature

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#3259]
### Description
Layers can be automatically refreshed with the "refresh" property.

This property is not accessible to the users via the UI, it can only be set by manually editing the JSON

We should provide an UI to activate and configure this option:
- Active : ON or OFF
- If active: input the refresh interval

**Comment by MV88** [comment]
in favor of https://github.com/geosolutions-it/MapStore2/issues/7289
