### ISSUE TITLE
TimeLine - Localization of timeline and playback tools

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#3264]
### Description
During the styling improvements, the timeline and playback plugin was not localized. Strings have to be localized. 

please check the components and the plugins involved in timeline and playback plugins:
 - web/client/plugins/timeline/InlineDateTimeSelector.jsx 
 - web/client/plugins/Timeline.jsx
 - web/client/plugins/timeline/Timeline.jsx
 - web/client/plugins/playback/Playback.jsx
 - web/client/plugins/Playback.jsx

Most of them should be tooltips, so you can simply replace tooltip with tooltipId (buttons)

**Comment by chiaracurcio** [comment]
please note that there are tooltips not localized opening the TOC and exapanding the timeline, 
see the immage below and red circles:
![local](https://user-images.githubusercontent.com/33256901/50147220-dbb63b80-02b5-11e9-9020-379842a71372.jpg)
