### ISSUE TITLE
Styles list cannot load styles if the catalog url has an authkey parameter

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#3292]
If the GeoServer catalog is defined with an "authkey" parameter, that parameter is not preserved in the GetCapabilities to retrieve the layers styles.

May be related to #1248

*Browser Affected*
Tested on Chrome

*Steps to reproduce*

- Create a new map
- Add a new server in the catalog using the "&authkey=xxxxxxxxxx" parameter for authentication
- NOTE: the layers must be protected and accessible to the user only
- Load the layers in the catalog
- Add a layer to the map
- Open the Layer properties
- Select Styles tab
- Click "Update styles list"

*Expected Result*

- The layer's styles list should display

*Current Result*

- An error message is displayed (404 in console)

### Other useful information (optional):

The GetCapabilities request does not include the authkey parameter that will allow access to the styles list

**Comment by tdipisa** [comment]
closed for inactivity.
