### ISSUE TITLE
Get Feature Info does not work on rotated maps

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#330]
When you rotate the map and click, the getFeatureInfo is empty or reply with an error.
Steps to repoduce:
* go to http://mapstore2.geo-solutions.it/mapstore/examples/viewer/?type=openlayers&mapId=165
* disable all layers except `c0601046_areecritfauna`
* activate feature info tool 
* Click on the ball on the top right 
![image](https://cloud.githubusercontent.com/assets/1279510/12424414/56ad5a94-bed0-11e5-8390-4a94216055b3.png)
*  you can see it gives you a response gid = 38
* Rotate the map 90 degrees to right
* Click on the same ball
![image](https://cloud.githubusercontent.com/assets/1279510/12424464/9c98b364-bed0-11e5-9903-51b5cf18105b.png)

Expected result: 
* response with gid = 38

Actual result:
* `no features were found`

**Comment by jsparber** [comment]
How can i rotate the map?

**Comment by mbarto** [comment]
Use Shift + Alt + Pan

**Comment by jsparber** [comment]
What is the error msg? Is "no features were found" a error msg or a valid output?

**Comment by mbarto** [comment]
"no features were found" is a valid output, when no feature is returned by a GetFeatureInfo request.

**Comment by jsparber** [comment]
I could not reproduce this bug. Which GetFeatureInfo response format are you using?

**Comment by offtherailz** [comment]
updated the issue with detailed steps to reproduce this issue.

**Comment by jsparber** [comment]
So that means "no features were found" is not a valid output?

**Comment by offtherailz** [comment]
Of course. The result of a click should be the same of in the 2 cases if the point clicked is the same. 
It seems like the tool don't calculate the correct parameters to sent to the GetFeatureInfo service when the map is rotated.

**Comment by offtherailz** [comment]
There was a misunderstanding. `no features were found` is a valid output in general if you click on an area without features.
In the case above `no feature were found` is not the expected expected result. I'll update again the issue to be more clear.

**Comment by offtherailz** [comment]
This issue has been fixed with this commit: f721555804b017c91cd57bdefe8a176e998a9d27
closing.
