### ISSUE TITLE
Mouse position shows wrong coordinates

### ISSUE THREAD

**Issue by kgaeb** [geosolutions-it/MapStore2#3311]
### Description
The coordinates of the mouse position are wrong!!
When showing coordinates based on the mouse position, minutes are increased and decreased whenever a threshold of 30 seconds is reached. The wrong position is shown for latitude and longitude.

### In case of Bug (otherwise remove this paragraph)
*Browser Tested*
- [x] Edge
- [x] Chrome
- [x] Firefox

*Steps to reproduce*
-switch on show/hide position
-zoom in until the mouse movement range is within one minute
-move the mouse from below 30" to slightly above 30" and observe the displayed minutes
-do the movement along latitude and longitude

*Expected Result*
Minutes should be increased when reaching 60 seconds

**Comment by tdipisa** [comment]
Dear @kgaeb, thank you for reporting this. It seems that we are able to replicate the issue, we will provide a fix soon.

**Comment by MV88** [comment]
here are the action to dispatch for replicating the issue

before 010° 28' 29.97
```
{
  type: 'CHANGE_MOUSE_POSITION',
  position: {
    y: 43.70726776739903,
    x: 10.47499179840088,
    crs: 'EPSG:4326',
    pixel: {
      x: 671,
      y: 549
    }
  }
}
```
after 010° 29' 30.05"

```
{
  type: 'CHANGE_MOUSE_POSITION',
  position: {
    y: 43.70726776739903,
    x: 10.475013256072998,
    crs: 'EPSG:4326',
    pixel: {
      x: 672,
      y: 549
    }
  }
}
```

**Comment by MV88** [comment]
the problem was [here](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/mapcontrols/mouseposition/MousePositionLabelDMS.jsx#L38) because when you set maximumFractionDigits: 0 then react-int API rounds the number that in this cast was 28.50 which become 29.
