### ISSUE TITLE
Wrong position for FB social share link

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#3315]
### Description
In some cases the FB share link has a wrong position

![ms2_social](https://user-images.githubusercontent.com/1280027/48124812-83832700-e27d-11e8-926b-63a11cb87cd9.png)

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [X] Internet Explorer
- [X] Chrome
- [X] Firefox
- [ ] Safari

*Steps to reproduce*

- Load [this map](http://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/749) 
- Open the Share panel / Social

*Expected Result*

- All the social share links should be aligned

*Current Result*

- The FB share link is not aligned

**Comment by tdipisa** [comment]
@allyoucanmap I think this issue has already been closed by #3545. Can we close it?

**Comment by allyoucanmap** [comment]
@tdipisa yes
