### ISSUE TITLE
Scroll bar over the account  icon in the home page using IE

### ISSUE THREAD

**Issue by chiaracurcio** [geosolutions-it/MapStore2#3329]
### Description
Scroll bar over the account  icon in the home page using IE
![explores_ms2](https://user-images.githubusercontent.com/33256901/48355837-30eaa600-e695-11e8-85e1-b76bfda953d4.JPG)

*Browser Affected*
IE11

*Steps to reproduce*
- open the home page

*Expected Result*
- the account icon is not overlapped by the scroll bar

*Current Result*
- the account icon is overlapped by the scroll bar (see the immage)

**Comment by tdipisa** [comment]
closed for inactivity
