### ISSUE TITLE
Details sheet "About this Map" appears in burger menu but the details are not present

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#3337]
### Description
For some maps (example: [](http://localhost:8081/#/viewer/openlayers/3264)) The "About this Map" (details sheet visualization) but if you click you see a notification about "details not available". 

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
any

*Steps to reproduce*

- Open a map that has this issue. Here some examples: 
    - [Production](https://mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/464)
    - [Dev](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/464)
- Open the burger menu

*Expected Result*
- You should not see the details map (at least if the map has not details. You can verify if details are present looking for the map in the home page (the home page details sheet functionalities don't seem to be affected by this issue)

*Current Result*

 - You see the entry "About this map", clicking on it show an error notification. (Note: About this map is not "About". In some languages is translated as "Info about this map", or something like this)

### Other useful information (optional):

This is probably because some maps has "NODATA" inside the configuration as details URL and so this check passes: 

https://github.com/geosolutions-it/MapStore2/blob/2f95cdedc8a4c3cfca44d6d72541e12263ed0746/web/client/plugins/Details.jsx#L44

We should check: 
1. to avoid this behiviour and skip also "NODATA" strings.
2. verify that saving "NODATA" is correct. 

This is athe attributes list of the resource
```
{
  "AttributeList":{
    "Attribute":[
      {
        "name":"thumbnail",
        "type":"STRING",
        "value":"https:\/\/demo.geo-solutions.it\/share\/MapStore2-previews\/histo-flowrence.png"
      },
      {
        "name":"owner",
        "type":"STRING",
        "value":"geosolutions"
      },
      {
        "name":"details",
        "type":"STRING",
        "value":"NODATA"
      },
      {
        "name":"featured",
        "type":"STRING",
        "value":true
      }
    ]
  }
}
```

**Comment by francoperversi** [comment]
Probably fixed with #4420

**Comment by tdipisa** [comment]
@francoperversi can you test it please in QA to check if we can close or if a backport is needed (it is not clear to me)

**Comment by francoperversi** [comment]
@tdipisa test ok in QA. #4420 PR commit is present in QA history. Closing
