### ISSUE TITLE
Implement optional animation range 

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#3341]
Make the animation range optional.
When animation range is enabled, some buttons should make easier a quick setup: 
 - A button that moves the timeline viewport to the current animation range
 - A button that  Fit animation range to current viewport
 - A button that Fit animation range to selected layer data (only if in guide layer mode)

When enabled, it the playback range should be set to a good default (current viewport or selected layer data)

**Comment by chiaracurcio** [comment]
note that the setting of the optional animation range in the setting tool have some problems:
- you are not able to define the range in the control cells as you want
- when you click play the animation not starts

**Comment by offtherailz** [comment]
Probably a regression due recent updates. The playback cursors are simply not visible anymore. Please @allyoucanmap, can you check if it is a regression from your side?

**Comment by offtherailz** [comment]
@chiaracurcio please re-test this feature. It should be working again due to fixes in #3424 (when deployed)
