### ISSUE TITLE
Widgets button is not aligned anymore

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#3352]
### Description
The widget menu button is not aligned correctly. 

the left image is the current release (2018.02.01) , the right one is from the dev server (next major)
![image](https://user-images.githubusercontent.com/1279510/48765367-4aea4100-ecb2-11e8-9959-5a70e0a66391.png)

**NOTE**: this bug affects only the current **master**. 

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
any (tested on chrome)

*Steps to reproduce*

- Open a map with widgets

*Expected Result*

- The menu, the title and the info icon are aligned

*Current Result*

- The menu, the title and the info icon are not well aligned

**Comment by tdipisa** [comment]
Closed for inactivity
