### ISSUE TITLE
Style editor  invalid style

### ISSUE THREAD

**Issue by kappu72** [geosolutions-it/MapStore2#3366]
### Description
The style editor plugins could save an invalid style, this cause a layer loading error
### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*
To reproduce add a style rule that has a filter, and use double quote for the filter value.
 add  layer boxes_with_end_date
enter style editor
add a new css style
add this rule
      [date="2000-06-07T22:00:00Z"] {
	stroke: #999999;
	mark: symbol(square);
	:mark { fill: #8b572a; };
}
save new style
save the style for the layer
- ...

*Expected Result*

- Describe here the expected result 

*Current Result*

The style is saved and the layer throws an error on reload

**Comment by tdipisa** [comment]
closed for inactivity.
