### ISSUE TITLE
Stop the animation only when the selected layer was removed

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#3367]
### Description
Now any time the user removes a layer from the map, the animation stops. This is not needed at all. You may need to stop the anymation only when the user removes the guide layer (**if any**). 

### Acceptance criteria
 - The animation should not stop when the user remove a layer if
   - There are remaining layers to animate in the timeline. (if there are not layers with time dimension, you should stop anyway). 
   - The removed layer is not the guide layer

### Suggested solution 

The REMOVE_NODE removes the selected layer before any epic can do some check on it. 
So you may need to keep in the epic the last selected layer by intercepting SELECTED_LAYER event, and use it to check if the layer removed is the correct one. 

Please take also into account that 
 - `undefined` is a valid value for selection (means no layer selected)
 - You have also to check if there is any layer in the timeline. If not, there is no reason to continue animation and you must stop it.

**Comment by tdipisa** [comment]
@offtherailz now the issue seems to be different. If I add two time layers and then start the animation then, during the animation, I remove one layer (not the guide one) the animation continue but the removed layer still persists in the timeline. I have increased the priority to high and this issue must be solved soon (@gioscarda).

**Comment by offtherailz** [comment]
I confirm the issue notified. It have to be solved.

**Comment by offtherailz** [comment]
Anyway is related to delete of layers and timeline, but is not the same issue, maybe is a good idea to open a different one.

**Comment by offtherailz** [comment]
@tdipisa why did you reopened this. I already back-ported it. did you found any issue?
