### ISSUE TITLE
Title and abstract don't update in the same edit session (Style Editor)

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#3371]
### Description
If title and abstract don't update in the style list if they have been changed in the editor.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- all

*Steps to reproduce*

- open a map with a vector layer
- select layer and open settings
- select style tab
- select a style to edit
- change title and abstract of the style and save
- back to style list

*Expected Result*

- title and abstract are updated

*Current Result*

-  title and abstract are still the old ones, you need to close the setting and open again to see the applied changes of title and abstract

**Comment by tdipisa** [comment]
@allyoucanmap can we close this. I'm no longer able to reproduce.

**Comment by allyoucanmap** [comment]
@tdipisa the issue is still there but only when using the textarea editor. I think we can close this for now

**Comment by tdipisa** [comment]
@allyoucanmap I tested it with the text area indeed, but I haven't reproduce the issue.
