### ISSUE TITLE
cesium default empty basemap

### ISSUE THREAD

**Issue by baloola** [geosolutions-it/MapStore2#3386]
Cesium's default globe color is blue, when the user set the base map/ background to none in leaflet and openlayers, the background is white.
I think this has a map design flaw, since color selection based on a white background would not fit a blue background. (see the examples below).
![blue](https://user-images.githubusercontent.com/28819736/49389883-aba06180-f727-11e8-815c-fe3e208af294.png)
![shagaf](https://user-images.githubusercontent.com/28819736/49389887-ae02bb80-f727-11e8-8754-9bc4d809bcf1.png)

In the second snapshot the background was set to white simply adding this line to components/cesium/Map.jsx
`map.scene.globe.baseColor = Cesium.Color.WHITE;`

**Comment by mbarto** [comment]
I agree, it is a simple and nice improvement
