### ISSUE TITLE
"standard" project template produces wrong links to resources

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#3388]
The following resources give 404:

/mapstore/dist/web/client/components/catalog/img/default.jpg
/mapstore/dist/web/client/components/maps/style/default.jpg 

To reproduce:
- Create a new project with "standard"
- Build it and deploy

**Comment by mbarto** [comment]
@Gnafu did you use latest master templates?

Just tried this:
 * node ./createProject.js standard TestProject 1.0.0 TestProjectDesc https://github.com/geosolutions-it/test-project /C/Develop/TestProject
 * run ./build.sh in /C/Develop/TestProject
 * deployed the built war on a tomcat 7.0.92
 * did a quick tour (created a map as admin, added a layer from catalog, saved, back to home)

The mentioned resources are correctly loaded from:
 * /TestProject/dist/MapStore2/web/client/components/catalog/img/default.jpg
 * /TestProject/dist/MapStore2/web/client/components/maps/style/default.jpg

Any difference in your test flow?

**Comment by Gnafu** [comment]
@mbarto I think I only renamed the war to "mapstore"

**Comment by mbarto** [comment]
@Gnafu gotcha.
I think we can apply the same improvement we did on the main product here: https://github.com/geosolutions-it/MapStore2/pull/3356

Do you think you can test if this works doing similar changes to template(s) webpack config files and eventually produce a PR?
If not I can do it when I have some time.

**Comment by tdipisa** [comment]
@MV88 this is an old issue, is it still valid or we can close it?

**Comment by MV88** [comment]
the current templates are fixed too, i think we can close it
