### ISSUE TITLE
Feature Map not updated at login/logout

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#3393]
### Description
Featured Map section in home page is not updated at login/logout

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [X] Internet Explorer
- [X] Chrome
- [X] Firefox
- [X] Safari

*Steps to reproduce*

- Login with an user that can acces private maps that have been set as featured
- These maps do not appear in featured section
- Refresh the home page and the featured maps appears
- Logout 
- The private maps remain in featured section but not in maps section
- Refresh the home page and the private featured maps disappear

*Expected Result*

- The featured section should be updated according to the rights without refreshing the home page

### Other useful information (optional):
Maybe related to #3385?

**Comment by kappu72** [comment]
I'm unable to reproduce, when user logs in and out Dashboards, user maps and featured maps are reloaded.
I'm only able to see that all the requests are done twice.
