### ISSUE TITLE
Improve timeline's buttons

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#3397]
### Description
Current buttons bars do not fit the size of geonode's preview. In addition, the button to step forward and backward should always be visible. 

Suggested solution:
 - Transform expand button in a small handle outside the timeline (suggested on top) 
 - Remove playback button to collapse buttons
 - Always show all animation buttons, without any possibility to hide. 
![scan_tl_simone](https://user-images.githubusercontent.com/1279510/49591232-2490fa80-f96e-11e8-8a29-8ac8bea3bd1e.png)
- settings button should be separated from the animations button

**Comment by gioscarda** [comment]
The last requirement is not satisfied, the playback settings button is contiguous to the animations button. A little space between these two types of buttons is needed.

**Comment by tdipisa** [comment]
@gioscarda @offtherailz the setting button position if fine now. What should be fixed now is the position of the settings panel:

![time.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5943f6b8abdc49001a6611c9/125516c66e82c728ace21e0d46fc9d9726c0cfeb9ffbb049a15ee4d6730472727e50f57a71dcb529bc472e585f5f4cab445c5841aff19b37b4f46d2ede0356b49b381d66cc2f10abb2831abb06b821824780b4bc8f49d2a5.png)
