### ISSUE TITLE
WMS and WMTS layers don't show attributions

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#3400]
### Description
Adding attribution params on layer object or [via GeoServer](https://docs.geoserver.org/stable/en/user/data/webadmin/layers.html#wms-attribution) doesn't work for WMS/WMTS layers.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- all

*Steps to reproduce*

- add attribution to a WMS/WMTS layer object in configuration (eg. for a background layer)
- open mapstore and create a new map
- select the background with attribution

*Expected Result*

- attribution is visible in map

*Current Result*

- attribution is not visible

**Comment by tdipisa** [comment]
closed for inactivity.
