### ISSUE TITLE
Resources properties editing form Homepage causes issues

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#3406]
### Description
Saving a new resource only with the name, and after settings that resource properties from homepage, some issues are introduced:

### MAPS
* Login as admin
* Create new map
* Save writing only the name
* Go back to homepage
* From homepage, set a thumbnail, some detials and the permission `Testers can edit`
* Logout from admin and login as tester
* Open edit properties from homepage

**Problem 1:** Can't see the details (`NO_DETAILS_AVAILABLE`) and can't edit them
**Problem 2:** If I set a new thumbnail, the prevous one is not deleted (`DELETE 403 forbidden`)

### DASHBOARDS AND STORIES

* Login as admin
* Create new dashboard/story
* Save writing only the name
* Go back to homepage
* From homepage, set a thumbnail

**Problem 1:** The console gives the following error: `GET .../thumbnail 404 (Not Found)`

* Login as admin
* Create new dashboard/story
* Save writing only the name
* Go back to homepage
* From homepage, set the permission `Testers can edit`
* Logout from admin and login as tester
* Open edit properties from homepage

**Problem 2:** Tryng to set a thumbnail in console: GET .../thumbnail 404 Not Found

**Comment by offtherailz** [comment]
#5772

**Comment by ElenaGallo** [comment]
Reopen this issue, the following problem are not solved:

* Login as admin
* Create new *map/dashboard/story*
* Save writing only the name
* Go back to homepage
* From homepage, *set a thumbnail*

**Problem 1:** The console gives the following error: `GET .../thumbnail 404 (Not Found)` and `GET .../details 404 (Not Found)`

* Login as admin
* Create new *map/dashboard/story*
* Save writing only the name
* Go back to homepage
* From homepage, *set permissions*

**Problem 2:** The console gives the following error: `GET .../details 404 (Not Found)`

* Login as admin
* Create new *dashboard/story*
* Save writing only the name
* Go back to homepage
* From homepage, set the permission Testers can edit
* Logout from admin and login as tester

**Problem 3:** The console gives the following errors: 
- `https://dev.mapstore2.geo-solutions.it/mapstore/rest/geostore/extjs/resource/29362 403 (Not Found)`
- `https://dev.mapstore2.geo-solutions.it/mapstore/rest/geostore/resources/resource/29362/attributes 404 (Not Found)`
- `https://dev.mapstore2.geo-solutions.it/mapstore/rest/geostore/data/29362 403 (Not Found)`

* Login as admin
* Create new *dashboard/story*
* Save writing only the name
* Go back to homepage
* From homepage, set the permission Testers can edit
* Logout from admin and login as tester
* Open edit properties from homepage
* Set a *thumbnail*

**Problem 4:** The console gives the following errors:  `GET .../thumbnail 404 (Not Found)` and `GET .../details 404 (Not Found)`

* Login as admin
* Create new *map*
* Save writing only the name
* Go back to homepage
* From homepage, set the permission Testers can edit
* Logout from admin and login as tester
* Open edit properties from homepage
* Set a *thumbnail*

**Problem 5:** The console gives the following errors:
- `GET .../permissions 403 (Not Found)`
- `GET .../thumbnail 404 (Not Found)`
- `GET .../details 404 (Not Found)`
