### ISSUE TITLE
Lazy loading for GetFeatureInfo

### ISSUE THREAD

**Issue by mircobe87** [geosolutions-it/MapStore2#341]
The tool should show only one feature for each layer and load additional features via user interaction, for instance, clicking on "show more" button or something like that.

**Comment by simboss** [comment]
@tdipisa changed priority since sooner or later we need to do the following enhancements:

1. paging
2. deciding whether or not we should load the geometry
3. format configuration

**Comment by tdipisa** [comment]
closed for inactivity.
