### ISSUE TITLE
Fixed-pitch functioning by settings tool (animation step)

### ISSUE THREAD

**Issue by chiaracurcio** [geosolutions-it/MapStore2#3413]
### Description
When you want change the Fixed-pitch of the animation you open the setting and now you have to enable the step animation checkbox to set a different step (1 day is the default step).
This checkbox has to be removed because is not usefull.
The loop function should be setted in a separate functionality to set when the animation moves inside the domain or not.

*Browser Affected*
- [x ] Internet Explorer
- [x ] Chrome
- [ x] Firefox
- [x ] Safari

*Steps to reproduce*
- open the setting tool in the timeline to set the step of the animation

*Expected Result*
- you have 2 different functionalities for step and loop

*Current Result*
- you have 1 only functionality not easy to understand 
![immagine](https://user-images.githubusercontent.com/33256901/50153742-9bf84f80-02c7-11e9-9012-a4e3a0724313.png)

**Comment by offtherailz** [comment]
loop functionality has not been implemented yet (see the task sheet to see the work is blocked for it).
Concerning a more understandable interface @tdipisa and @allyoucanmap, do you have some suggestion?

**Comment by offtherailz** [comment]
We are going to refactor the GUI this way, to clarify the purpose of each component:

![image](https://user-images.githubusercontent.com/1279510/51111708-32ebf500-17fd-11e9-8994-d155c09e34ab.png)

The logic remains the same, except that guide layer is the opposite of fixed step switch.

### Other minor changes:
 - Some tooltips (?) will clarify the settings options 
 - Following label becomes "Follow the animation"
