### ISSUE TITLE
Infinite loading with IE v.11

### ISSUE THREAD

**Issue by chiaracurcio** [geosolutions-it/MapStore2#3414]
### Description
Opening a new map or a pre-saved map with IE v.11 you have a infinite loading and the map not opens, this is probally due to a syntax error in configuration, see below:
![immagine](https://user-images.githubusercontent.com/33256901/50157359-7ec87e80-02d1-11e9-9543-ed5bf12f58ff.png)

### In case of Bug 
- [x] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*
- version 11

*Steps to reproduce*
- open a new map or a presaved map

*Expected Result*
- you can open maps

*Current Result*
- you can't open maps

**Comment by offtherailz** [comment]
This is an issue of geonode-mapstore-client. Going to close this in favour of the one in the correct repository

https://github.com/geosolutions-it/geonode-mapstore-client/issues/133
