### ISSUE TITLE
UI for WMS custom tile size

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#3425]
### Description
Allow configuring a custom tile size for WMS layers added from catalog, and change it from the TOC item settings.

The tile size settings should be provided on both Catalog advanced settings (by default 256px) and Layer Settings (Display tab). Available values for the tile size should be configurable by plugin config (by default 256x256). A list of possible sizes should be provided instead of having a free number field: possible values by default should be 256x256 (default) or 512x512.

Catalog tool advanced settings (WMS catalog type), two new fields required for **width** and **height**

![image](https://user-images.githubusercontent.com/1280027/88911795-a9750a00-d25e-11ea-80ed-122b76073199.png) 

just below **Format**. In this way, all WMS layers added from the WMS source will have the configured tile size by default.

Layer Settings (display tab), two new fields required  for **width** and **height**

![image](https://user-images.githubusercontent.com/1280027/88912202-3f109980-d25f-11ea-92f2-ddc052d67715.png)

just below **Format**. The default value for this fields is the one configured in the related catalog source the first time the layer is added to the map. With the new layer setting option the user has the possibility to change the tile size setting as needed for each single layer.

Both tile size options (Catalog tool and Layer settings) must be persisted in the map configuration as soon as the map is saved, in the same way of other existing configurations.

### Other useful information (optional):
Currently we have support at the framework level, but no way to to configure the option for layers added from the catalog, or to change the setting from the TOC.

**Comment by tdipisa** [comment]
This issue follow the development made in #4895 that introduced the support to configure the tile size by configuration
