### ISSUE TITLE
Timeline not overlaying properly above layer selection panel

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/MapStore2#3431]
### Description
![screenshot from 2018-12-21 09-55-09](https://user-images.githubusercontent.com/5264230/50334217-e49e4b80-0507-11e9-9283-7b7e1fba91c3.png)

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [x] Firefox
- [ ] Safari

*Browser Version Affected*

- Chrome 71.0.3578.98

*Steps to reproduce*

- A list of steps to reproduce the bug
- load timeline enabled map
- open layer selection panel

*Expected Result*
timeline above layer selection panel

- Describe here the expected result 

*Current Result*
timeline not completely above layer selection panel

- Describe here the current behavior

**Comment by tdipisa** [comment]
floating legent is no longer supported, closed for inactivity.
