### ISSUE TITLE
IE11 Login Do not work in debug mode

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#3432]
### Description
Because of this issue https://github.com/axios/axios/issues/507 login is not working in debug mode. This makes hard to work debug in IE11
### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- 11

*Steps to reproduce*

- start mapstore in debug
- Open mapstore in IE11
- Try to login

*Expected Result*

- Login success

*Current Result*

- Login error

### Other useful information (optional):

Updating axios to 0.15.3 solves the problem but makes the test fail and can cause issues concerning the following topics: 

### Error handling

Tests are failing because of [this breaking change:](https://github.com/axios/axios/blob/master/UPGRADE_GUIDE.md#error-handling
) for error handling

This may affect all the error handlings in real world response (non mocked with tests). So probably this is not a straight-forward updated to do. 

Other breaking changes that may break work:

### progress config
https://github.com/geosolutions-it/MapStore2/blob/a6461c39df49d563983eb131828f19411b964497/web/client/actions/importer.js#L652

See the upgrade guide
https://github.com/axios/axios/blob/master/UPGRADE_GUIDE.md#progress-config-option

**Comment by tdipisa** [comment]
closed for inactivity
