### ISSUE TITLE
Implementation of reverse GeoCoder for Mobile and Desktop

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#344]
On long press (mobile) or with a proper active tool + click on desktop the user should be able to open a contextual menu (modal for mobile) with an option for the reverse-geocoding on the point clicked.
[see this, in the new UI, as an example of the right click menu](https://rawgit.com/geosolutions-it/MapStore2-theme/master/samples/map/right-button.html) 
We should use the same component of the GetFeatureInfo (floating or bottom panel, for desktop and mobile).

If the feature info window is open, you should be able to do see also the reverse geocode info (on demand, not on start). 
![image](https://cloud.githubusercontent.com/assets/1279510/15356434/f3248376-1cf8-11e6-8fb5-3c0b74390376.png)

Note: the tools for the location will be planned and implemented in a second phase, leave only the address, no slide up functionality. 

The 
On click on map, the address is removed (not on pan, only on click). 
Here the old wireframe
![wireframe_reverse_geocoder](https://cloud.githubusercontent.com/assets/1279510/11957958/2372d9b8-a8c5-11e5-9ee5-0fbb5808cd7d.png)

**Comment by simboss** [comment]
Nice example Lorenzo.

I did not know the river flowing through London was named Arno!
