### ISSUE TITLE
Some Timeline L&F Review

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#3442]
Some last minute details to review regarding the L&F of the timeline:

- [ ] Add more depth to the tick and range elements and increase the usability (frequently is difficult to identify the right point to click to drag the element). 

- [ ] Choose better icons: 
- Range/tick drag should have the same icon (the hand, [grab css](https://www.w3schools.com/cssref/playit.asp?filename=playcss_cursor&preval=grab))
- Can we use a different icon corresponding to the the range limit move action?
Something like [ew-resize](https://www.w3schools.com/cssref/playit.asp?filename=playcss_cursor&preval=ew-resize) instead of [move](https://www.w3schools.com/cssref/playit.asp?filename=playcss_cursor&preval=move)

**Comment by offtherailz** [comment]
@allyoucanmap worked on it, some ideas?

**Comment by offtherailz** [comment]
@allyoucanmap during my dev i found out that simply adding:
```
 pointer-events: none;
```
To the `::after` object of the custom-time css should improve usability a lot. Try it.
