### ISSUE TITLE
Changing printing layout

### ISSUE THREAD

**Issue by rayediaz** [geosolutions-it/MapStore2#3447]
### Description
A few sentences describing the overall goals of the issue.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

**QUICK QUESTION**
Is there any way to changing the map printing layout?

*Steps to reproduce*

- A list of steps to reproduce the bug
- ...

*Expected Result*

- Describe here the expected result 

*Current Result*

- Describe here the current behavior

**Comment by tdipisa** [comment]
closed for inactivity.
