### ISSUE TITLE
Animation range and current time handles are grabbable while playing [Timeline]

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#3464]
### Description
Users can move and grab animation range handles  and current time handle while playback is playing even if this action hasn't effect on the handles position.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- all

*Steps to reproduce*

- open a map and add a layer with time dimension
- timeline will show up
- expand the timeline plugin
- open timeline setting (cog icon)
- switch on action range panel
- click on play button
- drag one of the handles (current time, animation start, animation end, ...)

*Expected Result*

- handles are not draggable while playing

*Current Result*

- handles are not draggable but they have not effect on the layer

**Comment by tdipisa** [comment]
Currently fixed in dev
