### ISSUE TITLE
Timeline - Start and end should not overlap

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#3468]
### Description
When time range is active it's possible to move start time over end time. (start time > end time)

![overlap](https://user-images.githubusercontent.com/19175505/51397161-e5df8a00-1b40-11e9-9d76-800622c17509.gif)

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- all

*Steps to reproduce*

- open a map and add a layer with time dimension
- expand time slider
- enable time range
- move start time over end time

*Expected Result*

- should not be possible move the start over the end, or at least they should switch

*Current Result*

- start and end time are applied in the wrong order so layer result empty

**Comment by tdipisa** [comment]
This issues has already been fixed with recent fixes on timeline tool in master and 2019.01.xx
