### ISSUE TITLE
Build fails due to tests failing 

### ISSUE THREAD

**Issue by rayediaz** [geosolutions-it/MapStore2#3469]
### Description
When trying to build the war file with the command `build.sh`. it fails due to a test failing (BaseDateTimeFilter).

### In case of Bug (otherwise remove this paragraph)
- [x] Bug

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*
- Browser information: (whatsmybrowser.org/b/23LAD59)
Chrome 71.0.3578 (Linux 0.0.0) is idle

*Steps to reproduce*

- Trying to build the war running `build.sh`

*Expected Result*

- Expect a war file  

*Current Result*

- Get an error saying a test (BaseDateTimeFilter) failed.

### Other useful information (optional):
![screenshot from 2019-01-19 17-58-03](https://user-images.githubusercontent.com/15975670/51432847-f5300780-1c14-11e9-8e18-31b2781b6d8f.png)

**Comment by tdipisa** [comment]
closed for inactivity.
