### ISSUE TITLE
SEO for home page

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#349]
This is the result for a google search:
![image](https://cloud.githubusercontent.com/assets/1279510/11958468/54dd5f84-a8c8-11e5-9fc0-3e4848ff62ba.png)

**Comment by Gnafu** [comment]
Looks like it is fixed now
![2016-05-20_1128](https://cloud.githubusercontent.com/assets/3932165/15423505/130ff63a-1e7e-11e6-8b28-d321431837cf.png)
