### ISSUE TITLE
LayerTree

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#35]
Implement a simple static layertree with:
 * turn on / turn off
 * grouping (multi - level)
 * expand / collapse (of groups)
 * background layers (distinct component)

**Comment by offtherailz** [comment]
Some mockups:

* collapsed: 
![layerswitchercollapsed](https://cloud.githubusercontent.com/assets/1279510/10131244/26fe902e-65cf-11e5-8991-aa793e108f09.png)

*expanded :
![layerswitchermock1](https://cloud.githubusercontent.com/assets/1279510/10131246/2bc33736-65cf-11e5-9139-b98905c2d19e.png)
