### ISSUE TITLE
Improve url parsing of GeoServer layers in style editor

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#3507]
### Description
Relative url path of layer return undefined after toggle style editor (list).

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- all

*Steps to reproduce*

- add geoserver in proxy buildConfig.js and start a GeoServer on http://localhost:8080

```
devServer: {
    proxy: {
        ...
        '/geoserver': {
            target: "http://localhost:8080"
        }
        ...
    }
},
```
- start mapstore in dev `npm start`
- open a map
- open catalog
- add a new service with url `geoserver/wms` and type `WMS`
- add a layer from catalog
- select a layer from TOC and open setting
- select style tab

*Expected Result*

- panel shows list of styles

*Current Result*

- panel doesn't show list of styles

**Comment by offtherailz** [comment]
I think the input is wrong usage of catalog itself. You should set /geoserver from catalog.
