### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#352]
We should:
- [x] make state to component connection more granular (review current Viewer -> plugins infrastucture)
- [x] use reselect where needed to avoid props recalculation
- [ ] introduce ImmutableJS (https://facebook.github.io/immutable-js/)
- [x] Evaluate to use [Recompose](https://github.com/acdlite/recompose/) HOCs to encapsulate complex property transformations

**Comment by offtherailz** [comment]
Introduction of ImmutableJS is the only task pending for this issue. 
ImmutableJS donit introduce performaces improvements, maybe can increase dev speed or bug prevention.
 Anyway it's hard to be included at this time.
I'm going to include some immutable utilities for reducers instead(I'm doing it during my current project).
@mbarto I think we can close this.

**Comment by tdipisa** [comment]
@mbarto @offtherailz  can we close this?
