### ISSUE TITLE
Address and coordinate search

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#3523]
### Description
We would like to add to the search bar in the viewer the possibility to zoom to a specific point and place a marker in that point that will be the center of the map.
There will be two possible formats: aeronautical or decimal.

This button in the search toolbar will be disabled on mobile, showing only the search for addresses

by changing the config you can:
- hide this tool (active by default only in map viewer)
- change default zoom level (default 12)
- select the search tool active (default adddres)

**Comment by MV88** [comment]
some fixes made [here](https://github.com/geosolutions-it/MapStore2/pull/3606), need to be porter on master

**Comment by gioscarda** [comment]
Some problems occur when trying to reset the coordinate search editor:
- decimal format
  ![error_coord_search.gif](https://images.zenhubusercontent.com/5cda9c3818690954352b7b76/ae7361e2-01f0-4106-bff0-3047eda4c5b8)
- aeronautical format
  ![error_coord_search_aeronautical.gif](https://images.zenhubusercontent.com/5cda9c3818690954352b7b76/e5bde864-ddeb-49b7-8755-7756ea0bf892)

The wrong behavior exists when typing the "e" character in some field.
