### ISSUE TITLE
Zoom to Layer is missing in Dashboard map widget

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#3533]
### Description
A Zoom to Layer tool is missing in the TOC toolbar when you edit a dashboard map widget. It is an useful tool and it should be added to be able to zoom to the layer extent, we should be basicaly enable the same functionality that we have in the TOC of the MS webgis.

**Comment by kasongoyo** [comment]
The zoom to layer tool, will be added in this toolbar right? @tdipisa 

<img width="1427" alt="Screenshot 2019-12-02 at 12 29 01" src="https://user-images.githubusercontent.com/1956062/69947897-ad019700-14ff-11ea-8eb9-e9e6aa962dd0.png">

**Comment by tdipisa** [comment]
> The zoom to layer tool, will be added in this toolbar right? @tdipisa

yes

**Comment by tdipisa** [comment]
@MV88 please check it after closing #4614 to check if we are able to close this too within this milestone or not.
