### ISSUE TITLE
Some resources not correctly versioned

### ISSUE THREAD

**Issue by gioscarda** [geosolutions-it/MapStore2#3561]
### Description
Opeing a map some resources are not versioned correctly.
Referring to this [failed test](https://app.hiptest.com/projects/48097/test-runs/237259/folder-snapshots/1982089/scenario-snapshots/7653629/test-snapshots/9887072), both the default.css and the ms2-api.js resources are not correctly versioned.

### In case of Bug

*Browser Affected*
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Browser Version Affected*

- All

*Steps to reproduce*

- Open a map from the MapStore homepage
- Open the dev console
- Check the versions of the resources "default.css" and "ms2-api.js"

*Expected Result*

- The resources are versioned accordingly with the enviroment in which MapStore has been deployed

*Current Result*

- The resources have versions not compliant with the enviroment in which MapStore has been deployed

**Comment by offtherailz** [comment]
The issue was in the build process of QA in jenkins. It was overwriting the existing war with another to build the binary in the old way. It has been updated and the problem is solved.
