### ISSUE TITLE
Problem with embedded map using APIs

### ISSUE THREAD

**Issue by gioscarda** [geosolutions-it/MapStore2#3562]
### Description
The embedded code for map sharing through API doesn't work with Firefox browser.
Refer to [this test](https://app.hiptest.com/projects/48097/test-runs/237259/folder-snapshots/1982098/scenario-snapshots/7653718/test-snapshots/9887161) .
### In case of Bug

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [ ] Safari

*Browser Version Affected*

- All

*Steps to reproduce*

- Open a map in MapStore
- Open the SHARE panel from the Burger Menù
- Got o the EMBED tab
- Copy the text inside the "Using APIs" box
- Paste it into a new file and save it as HTML
- Open the html file in a Firefox browser 

*Expected Result*
The map is visible in an embedded window

*Current Result*
The map is not visible, a blank page is displayed

- Describe here the current behavior
When you open the html file in a Firefox browser a blank page is displayed

**Comment by tdipisa** [comment]
The same happens also in chrome
