### ISSUE TITLE
QueryPanel DateTime filter issues

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#3585]
### Description
 - [x] DateTime attribute time is not supported, only date. (not sure if time is supported) 3PT. We need to add datetime support
 - [x] If you edit one date time Filter and then change the operator (e.g. > to <), without changing the date, the filter will not be applied. 1PT
 - [x] The hour of the filter in the final timestamp is set randomly (current hour when create the first attribute filter). It should be 00:00:00 (or use date-only format). 1PT

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
any

*Steps to reproduce*

- Add a new Layer with dates and date-time attributes
- Open the query panel

*Expected Result*

- I can create filters for all attributes
- filters should work

*Current Result*

- Datetime (timestamp) attributes are not available
- When I change the operator after changing the date, the filter is not applied: 
   - Add an attribute filter on a date field
   - Select operator > 
   - Select a date using the date picker (e.g . today)
   - Change the opearator to <
   - Click on search ( thie filter is not applied, the button is not green, if you re-open the query panel you can not see the attribute fiter you did)
- Dates are relative to my date time instead of absolute. 
   - open dev tools
   - perform a search with a date attribute filter
   - check network tab in dev tool
   - select the request o and check the effective xml: I see some random hours (It should be 00:00:00).
![screenshot](https://user-images.githubusercontent.com/1279510/53556289-d130e180-3b43-11e9-9cfe-4f5e84d20445.png)

### Other useful information (optional):
Notes for developers: 
Only for dates (not dateTime), we should check if the filter is correctly applied as expected with > or >= (we are using timestamp for simple dates: 
 -Example:  2018:01:01 (original attribute) > 2018-01-01:00:00:00 (timestamp filter) is misleading.

**Comment by simboss** [comment]
Let's fix this one.
