### ISSUE TITLE
Printing layouts have wrong width set for legends

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#3598]
### Description
Current legends width are bigger than the container space for most of the layout, so long labels overflow.

**Comment by gioscarda** [comment]
@mbarto When using very long labels some characters exceed the right border of the legend box:
![image.png](https://images.zenhubusercontent.com/5cda9c3818690954352b7b76/2e0e0b9e-0aca-4566-8c75-6f8f0675277e)
