### ISSUE TITLE
TOC mouse over tooltip customization

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#3608]
### Description

The administrator shall be able to configure the content of the "mouse over" display in the TOC.
This shall be done for each TOC entry separately.
Currently it is the title; preferable it should be the title and description;

- Add an **Advanced Options** as switch panel in the layer settings.
It is enabled by default and can be disabled by a flag (showAdvancedOptions = false)  
- By default the switch panel is closed (expandedAdvancedOptions = false)
- In the switch panel there will be a combobox showing the property of the node that can be used to create the final tooltip. (title, description, both, none)

**Comment by gioscarda** [comment]
Using IE11, in the layer settings panel, options for `Tooltip` and `Placement` are not visible.

**Comment by MV88** [comment]
Those options are not being saved in the map
