### ISSUE TITLE
Toolbar do not back in position when featureinfo layer are removed

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#3615]
### Description
When you have only one queriable layer on the map, do the get feature info, then delete the layer and do the getFeatureInfo again, the toolbar remains in the middle of the page while the feature info panel closes. 

I suggest to fix it by cleaning up the featureInfo when the layers queried are not on the map anymore. So the panel should close on Delete and not on next click on map. 
### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
any

*Steps to reproduce*

- Set the map with only one (queriable) layer
- Click on map and wait for getFeatureInfo panel to open
- Without closing the getFeatureInfo panel, open the TOC and delete the layer. 
- Click on map again --> a popup saying "No queriable Layers" appears

*Expected Result*

- The toolbar is in position

*Current Result*

- The toolbar remains in the middle of the page

**Comment by tdipisa** [comment]
This seems already solved in DEV, please test.
