### ISSUE TITLE
Annotation problems, cannot draw SVG on IE11 and ol 4.6.4

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#3620]
### Description
IE11 has problems with SVG symbols.

also it does not show coordinate editors rows (to solve this do use flex-basis: auto on the coordinateEditor row)
### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer 11

*Steps to reproduce*
use ol 4.6.4

- open ie11
- open a new map 
- create a point annotations
- change the style to symbol

*Expected Result*

- the default symbols is drawn to the map

*Current Result*

- on the map nothing appears and in the preview there is a symbol not found icon.

### Other useful information (optional):
there is a discussion on [this](https://github.com/openlayers/openlayers/issues/6281) issue in ol 
but adding imgSize of [64, 64] does not solve the problem.

Edge is working fine

### for testers

use an updated version of annotations not actual master

**Comment by tdipisa** [comment]
browser no longer supported, closing
