### ISSUE TITLE
Solve Widgets / Timeline Conflicts

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#3642]
### Description
Timeline and Widgets must be managed in mutually exclusive way:

1. When Widgets are visible and time layers are present in map, the Timeline is collapsed in the widgets toolbar and the time dimension is disabled for time layers too

2. When Timeline is visible, Widgets are collapsed and time dimension is enabled for every timelayers in map

   **note1:** if we add a time layer from catalog a dialog can appears to ask if the Timeline should    activated or not: if yes, eventual Widgets present in map will be collapsed automatically according to points 1 and 2 above.

   **note2:** we can also have both Widgets and Timeline collapsible with two different toolbar controls to expand the whole widgets set excluding the timeline and so respect the mutual exclusion between them
Both Widgets and Timeline can be collapsed in this context
![time](https://user-images.githubusercontent.com/1280027/54828710-0cdb4900-4cb5-11e9-9952-adc846e392cd.jpg)

**Comment by offtherailz** [comment]
# Some ideas and questions
- about **note 1** : So I think we should have the tray anyway (if some widgets or timeline are present).

About timeline and FeatureGrid
- We have the same problem of the widgets (data in map and data in FeatureGrid are not consistent). What if we simply make it disappear (also widgets do that) as well as the sync is not supported ?
When integration with feature grid will be completed, the FeatureGrid will be sync only if the timeline is expanded. If the timeline is present, the tray should be visible to collapse/disable it.

- The collapsed status of the timeline have to be saved in map. (aka - when I open a map with timeline and/or widgets, I should see the timeline or not)

Finally I think that all the popups should have a "do not show me anymore" checkbox

# Various workflows
I list the various workflows to Identify problems

## Empty Map
I add a time layer --> 
  Option 1: I see the timeline, no widgets tray 
  Option 2: I see the widgets tray, with timeline collapsed (and a popup that suggest to expand the timeline) or expanded automatically
I add also a widget --> I see the new widget, the timeline is collapsed (Maybe a popup or a notification that explains what happened) and all time layer are reset to no-time param.
If I expand again the timeline, the widgets will be collapsed and the map will filter again to the current time. 


# Draft task list

## Widgets / TImeline conflict
- [ ] Enable/Disable flag for timeline, with side effects ( animation stop, time reset/restore of layers ) 3 PT
- [ ] Changes to tray 1 PT
- [ ] mutual exclusion of widgets and tray 2 PT
- [ ] Popups and notification 1 PT

## Timeline FeatureGrid
- [ ] Opt 1: Force disable on expand - 1 PT (requires tasks of timeline conflict
- [ ] Opt 2: Resize when expanded TBD (is hard to identify the size of the toolbar)

## Resize the query panel
- TBD

**Comment by offtherailz** [comment]
@tdipisa I noticed that this issue is assigned to 2019.01.01 but 2019.01.xx do not has the widget's tray.

**Comment by tdipisa** [comment]
@offtherailz #3531 needs to be included in the next minor 2019.01.01 before proceedings with this.

**Comment by offtherailz** [comment]
@tdipisa what about pinned widgets, that can not be collapsed?
![image](https://user-images.githubusercontent.com/1279510/56201920-31230f00-6042-11e9-9023-ae4780ef05ae.png)

**Comment by offtherailz** [comment]
From the discussion with @tdipisa this issue has been splitted in two:
 - Timeline/Widgets conflicts in this issue
 - Layout tuning in #3699
About the de-activation of time when collapse, we choose to avoid this because it doesn't solve anything about data coherence: 
In fact when time is not added to a layer, the default time is used. This is not the same to use the whole data, as widgets does. So disabling the time dimension is not a solution, only a complication
