### ISSUE TITLE
Add zoom to feature and highlight to table widget

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#3659]
### Description
Add highlighting and zoom to feature functionality to the table widget. Evaluate how it should work in map and dashboard context

## (draft) Acceptance Criteria
 - The zoom to/ highlight features should be optional 
If enabled, When the user select a row the feature is highlighted on the (connected) map
If enabled, When the user click on zoom button (that will be available only if zoom to feature is eanbled) the (connected) map should zoom to the feature extent.

**Comment by mahmoudadel54** [comment]
Closing in favor of https://github.com/geosolutions-it/MapStore2/issues/9567
