### ISSUE TITLE
Pressing tab cause white space on right

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#3664]
### Description
Pressing TAB many times causes the map to show a white space on the right. 

![image](https://user-images.githubusercontent.com/1279510/55388797-30fc1d00-5534-11e9-82cc-99bf9a83767e.png)

This is caused by the input components in dock panels, rendered in a side div (instead of the main container, this to prevent issues in fullscreen mode). The input are : 
 - catalog's input boxes
 - coordinate editor in feature info

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [x] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- open the map
- click on the search bar to get the focus (blinking cursor)
- Press tab many times (how many depends on the current configuration, the browser and the map content, but in a map without widgets and with the default plugins the issue should be visible pressing it around 20 times)

*Expected Result*

- No graphical glitch

*Current Result*

- A white space on the right appears

**Comment by tdipisa** [comment]
@offtherailz and @gioscarda before accepting this issue, the fix must be backported to the stable branch.
