### ISSUE TITLE
Routing migration (FOR DISCUSSION ONLY)

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#3684]
### Description

Some libraries has conflict with # usage

**Comment by allyoucanmap** [comment]
Some libraries for slideshows, such as `reveal.js` or `spectacle`, replace hash in the url location with the number of the slide. This behaviour can conflict with the current routing of MapStore.
MapStore uses hash for the routing of the application's pages by default.

**Question**: How could we manage libraries that uses location hash as internal link of the page without confilct with the routing of MapStore?

First attempt to solve this conflict was to disable hash functionalities from the tested libraries but I didn't find configuration that provide this behaviour (even if we could propose a fix to the libraries)

@mbarto proposed to add a configuration to let choose between hash routing and browser routing (`history/createHashHistory` or `history/createBrowserHistory`).
In this case we could move from `/mapstore/#/viewer/:map_type/:id` to`/mapstore/viewer/:map_type/:id`
and let to use hash for internal links or libraries functionality.
This option could cause a breaking change with old MapStore installation.

The use of `reveal.js` or `spectacle` is not a priority right now and probably we could find different solution to solve this problem but the question is still valid.

**Comment by tdipisa** [comment]
closed for inactivity.
