### ISSUE TITLE
Pop up Validation error doesn't show up for SLD

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#3713]
### Description
SLD validation error return a stateMessage with columnNumber and lineNumber instead of line column.
We need to parse also columnNumber and lineNumber.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Browser Version Affected*

- all

*Steps to reproduce*

- user needs to login as admin and MapStore configured with GeoServer to edit styles
- open a map with a polygon layer
- select layer in TOC and open the properties
- select style tab and create a new SLD style from template
- select the saved style in the list and click on edit </> icon
- remove a close tag from style (eg: `</sld:Name>`)

*Expected Result*

- error pop up shows up with the validation error

*Current Result*

- error pop up doesn't shows up

**Comment by gioscarda** [comment]
@allyoucanmap 
The style editor shows an error popup but the message inside the popup is not so human readable:

![image.png](https://images.zenhubusercontent.com/5cda9c3818690954352b7b76/11b30e6b-99c4-490c-a215-54a56480cbd0)

The message reports the exception type and some HTML entities are encoded (es. &quot;)

**Comment by gioscarda** [comment]
In MS2 environments DEV and QA the error popup is not shown.
