### ISSUE TITLE
Custom decimal places of coordinates related to mousePosition

### ISSUE THREAD

**Issue by PedG** [geosolutions-it/MapStore2#3756]
### Description
Custom decimal places displayed for coordinates related to mousePosition.

Currently my maps are set to expand footer to display coordinates by mousePosition, but my coordinates are in meters, so for us decimals places are not relevant and makes difficult to read coordinates. I would like to know if it's possible to develop a customisation for decimal places to be displayed.

Thanks. 
Regards.

**Comment by tdipisa** [comment]
Hi @PedG thank you for this issue but please ask in mailing list for this kind of questions, you can subscribe [here](https://mapstore2.geo-solutions.it/mapstore/#/) in our demo site. Thank you so much.

**Comment by PedG** [comment]
Sorry @tdipisa I thought this was the place when an user suggests an issue for developers. I haven't very clear if that is possible and where I can make requests to be implemented by developers if they consider suitable.
