### ISSUE TITLE
Autogenerated package-lock.json should be gitignored or committed 

### ISSUE THREAD

**Issue by kasongoyo** [geosolutions-it/MapStore2#3758]
### Description
Autogenerated `package-lock.json` should be gitignored or committed to help new collaborators not to accidentally commit it or to wonder about the fate of that file because deleting it is counter-intuitive option for js developer.  

### Other useful information (optional):
I propose it to be committed since it is controlled by `package.json` so even though package.json is currently solving the problem lock file tried to solve but having both will not have negative effect rather it will compliment the dependency versioning done in `package.json`.

**Comment by mbarto** [comment]
I agree. Can you prepare a PR for this?

**Comment by kasongoyo** [comment]
Sure, I will do that.
