### ISSUE TITLE
Problem with Feature Grid filter state -1-

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#3779]
### Description
There are problems with the filter state in Feature Grid when the column filter is removed:
- the grid content is not updated accordingly 
- the _synch to map_ filter is not updated too

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [X] Internet Explorer
- [X] Chrome
- [X] Firefox
- [X] Safari

*Steps to reproduce*

- Open this [map](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/4093)
- Select the 'USA Population' layer and open the Feature Grid
- Open the Query Panel and filter as reported below:

![issue_attr](https://user-images.githubusercontent.com/1280027/58084108-937bac00-7bba-11e9-9775-59eeb4d21bb1.jpg)

- Activate the _synch to map_ tool
- Go into the STATE_FIPS colum and type something to filter (i.e. '04')
- The grid and map state are updated according to the provided filter
- Clear the column filter 

*Expected Result*

- The grid will be updated accordingly and the layer in the map too

*Current Result*

- The grid is not updated and the layer in map too, you have to go back into the query panel and perform a query again to update the grid and map content.

**Comment by kappu72** [comment]
This issue is solved with fix for #3788
