### ISSUE TITLE
Allow drag&drop of layers/groups between groups

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#3781]
### Description
Currently drag&drop only reorders stuff inside the containing folder, moving layers/groups to different groups is not supported through drag & drop now: using the **group** combobox inside **Layer Settings** is the only way to accomplish this now.

What we need in this issue is to improve that behavior by implementing drag&drop of layers/groups to a different group (not only the possibility of reordering them in TOC).

**Comment by mbarto** [comment]
TOC items (groups and layers) are currently reordered with drag&drop thanks to the Sortable component (react-sortable-items) that only allow reordering inside a single container.
To have a more generic ability to reorder items or move them into a different container we need a more generic approach. We should start using react-dnd (http://react-dnd.github.io/react-dnd/examples) and implement drag&drop on top of it.
With a more generic approach we can implement both reorder and move,

**Comment by francoperversi** [comment]
Testing the groups drag and drop, I found some issues:

1) If the TOC contains separate groups of layers, if you nest a group to another (as subgroup) is than impossible to separate them back

![Groups](https://user-images.githubusercontent.com/54808782/66558212-7d638d80-eb53-11e9-97ac-00b2e7cb90d8.gif)

2. Is impossible to move or nest the Defalut group inside another group (the default group is created, for example, when you add a layer from catalog with no groups existing)

![def](https://user-images.githubusercontent.com/54808782/66559612-f6fc7b00-eb55-11e9-99d2-a91d2629a952.gif)
@tdipisa

**Comment by offtherailz** [comment]
@vlt1 please take into account these requirements:
 - [ ] the default group must be always on top. 
 - [ ] Dragging default group or dragging (in general) other groups above the default group should be denied, 
 - [ ] When the user tries to do one of the operations above, a warning notification tells the user the operation is denied explaining that the default group must remain on top.

**note**: the default group can be deleted, but when the user adds a layer from the catalog, the default group will appear again on top. (this is already implemented, please take into account during your changes)
**note** the default group can be renamed but it will keep its role, so even with rename it, the rules remain the same.  --> so the notification should tell something like:

> The <Title> group is set as default target group, therefore it must be remain on top.

@tdipisa can you confirm ?
