### ISSUE TITLE
Problem between FeatureGrid, TOC and FeatureInfo bx

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#3789]
### Description
I think I have found a mismatch between TOC, FI and FG.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

See GIF below, for [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/191) map.
![ms1](https://user-images.githubusercontent.com/693880/58138068-0b86b800-7c35-11e9-820f-f8c207f534a1.gif)

*Expected Result*

The FG should not bump again once I close the FI, right?

*Current Result*

The FG  bump again once I close the FI, this is unepxted.
However, if I start interacting again, things become normal.

**Comment by offtherailz** [comment]
@kasongoyo we decided for option 2. Break the re-bump behavior only if the user open the TOC.

**Comment by kasongoyo** [comment]
I think the requested behaviour is in place already. I have inspected and found that the TOC opening action also call FG close action. So nothing should be done as far as this issue is concerned.

**Comment by offtherailz** [comment]
That happens only if the feature grid is open. When it's temporary closed, that doesn't has effect.

As I said, the feature grid should not reopen if the TOC has been open. So close the re-open action flow in `autoReopenFeatureGridOnFeatureInfoClose` if the TOC has been opened in the meanwhile.
