### ISSUE TITLE
Fix user/group names limits

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#3806]
### Description
The limit for group name on the database seems to be 255 but when I try to insert a name, the limit seems to be fixed to 20. 
If I insert a name of 21, I have a not well defined error.

We should : 
 - [ ] Verify the nature of this limit
 - [ ] Limit the user to insert only the allowed characters, suggest the limit or at least provide a better error message
- [ ] Investigate if this kind of limit exists also for username and fix also it. 

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
any
*Steps to reproduce*

- Create a new usergroup with a name of at least 21 characters 

*Expected Result*

- I can not insert a name if it's too long, somehow the UI shows me why, or at least when I try the UI explains the nature of the error.

*Current Result*

- I receive a not well specified error

**Comment by ElenaGallo** [comment]
This issue is no longer valid, it can be closed.
