### ISSUE TITLE
New MapStore2 HomePage for the MapStore2 product application

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#381]
Create a new HomePage for the MapStore2 application.
The homepage will contain a list of maps from GeoStore.
- [ ] desktop layout (https://github.com/geosolutions-it/MapStore2/issues/382)
- [ ] mobile layout (https://github.com/geosolutions-it/MapStore2/issues/383)
- [ ] search / filter (https://github.com/geosolutions-it/MapStore2/issues/384)
- [ ] thumbnails (https://github.com/geosolutions-it/MapStore2/issues/385)
- [ ] infinite scrolling (https://github.com/geosolutions-it/MapStore2/issues/386)
- [ ] go to viewer and back or share same page (https://github.com/geosolutions-it/MapStore2/issues/387)
  ![home_page_layout_v1 1](https://cloud.githubusercontent.com/assets/2770528/12351080/71c20b66-bb7b-11e5-8411-df90ca1e2d3b.png)

**Comment by offtherailz** [comment]
old issue, closing
