### ISSUE TITLE
Enhancement of TOC: L&F, groups and more

### ISSUE THREAD

**Issue by PedG** [geosolutions-it/MapStore2#3811]
### Description
I consider that the way of working groups of layers to make its content visible is a little confuse or messy for user. I explain: when a group is not expanded and contains visible and not visible layers (even subgroups with more layers) it's difficult to know which layer is visible in case you want to toggle visibility. I propose for group entries (not layers) toggle button should works not toggling all its content but respecting current status for each layer/subgroup inside it. And when a group entry is selected, add a button on top to expand/unexpand or swith on/off all its content.

Besides, when a layer uses a style that only display it on an interval of scales, user could know this, if layer name appears greyed when is not on this interval although eye icon is on.

Finally, when a map have lots of layers and groups, it would be advisable a cleaner view of TOC, more compacted, removing some ornament like 3 bands or lines next to eye icon (on desktop version), removing the transparency slider under each layer (that mislead to user), and increasing the identation of layers inside groups. 

*Expected Result*

These ideas are based on my experience using Esri products and you can test as they are solved  in following link https://arcgis.boonecountygis.com/JavaScript/BooneCounty/

**Comment by tdipisa** [comment]
We are reviewing the entire MS's layout (closed in favor of #4254).
