### ISSUE TITLE
Enhancement - Allow for a wider area to be displayed on search result

### ISSUE THREAD

**Issue by pgssimon** [geosolutions-it/MapStore2#3815]
### Description
Allow for a wider area to be displayed on search result (instead of zoom up hard to feature found, allow for the map to be N-times bigger than the feature).
* Configured by a number value "zoom to value" in Configure search services.

**Comment by tdipisa** [comment]
@pgssimon what you requested has been implemented in 2021.01.00, [here](https://mapstore.readthedocs.io/en/latest/user-guide/menu-bar/#configuring-a-search-service) the doc: it is now possible to configure the max zoom level.
