### ISSUE TITLE
Enhancement - Launch MapStore to a particular location (x,y) or initiate a search using parameters supplied in the URL

### ISSUE THREAD

**Issue by pgssimon** [geosolutions-it/MapStore2#3817]
### Description
Launch MapStore to a particular location (x,y) or initiate a search using parameters supplied in the URL

e.g. 

https://data.wairoadc.govt.nz/mapstore2-wairoadc/#/viewer/openlayers/38?x=xxxxxxx.xxx&y=yyyyyyy.yyy

https://data.wairoadc.govt.nz/mapstore2-wairoadc/#/viewer/openlayers/38?search=address%20search&searchvalue=25%20white%20street

**Comment by tdipisa** [comment]
Dear @pgssimon,
in last MapStore release (2019.01.01) we have provided a new feature that allows to open a MapStore map to a specific location by using a **bbox** query parameter, something like the following: 

https://mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/6200?bbox=4.34360039207968,50.85627846708186,4.353900074696867,50.859356588945694

If I understood correctly this is what you need.
