### ISSUE TITLE
Home Page Desktop Layout

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#382]
![home_page_layout_v1 1](https://cloud.githubusercontent.com/assets/2770528/12351352/2a1098a8-bb7d-11e5-920d-3e446adeae91.png)

**Comment by offtherailz** [comment]
new mockup 
![image](https://cloud.githubusercontent.com/assets/1279510/16481711/f6ff9ca8-3eac-11e6-8bb5-3d18eb716dc8.png)

available at : http://lf.mapstore2.geo-solutions.it/samples/map/home.html#

**Comment by offtherailz** [comment]
We should use the maps page for the home page instead of the current home to close this issue?
