### ISSUE TITLE
Catalog - UI improvements and add a configurable template

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#3824]
### Description
- [ ] Allow cards to be expanded for a more detailed view of the metadata associated to the informations related to the CSW. 
The metadata shown are the one configured in the template system

- [ ] add possibility to use a template to customize title and description in the the expanded section (similar to feature info)
- [ ] this should be configurable via localConfig and via UI
- [ ] if any of the metadata are not available they will not be shown (MapStore2 support the format Dublin Core for the catalog tool)

Mockup [here](https://demo.geo-solutions.it/mockups/mapstore2/catalog-template/#/viewer/openlayers/new)

**Comment by gioscarda** [comment]
A couple of notes:
- in Firefox the cards width does not fit the catalog window size
- the example shown in the 'Advanced settings' panel of the CSW Service configuration window contains some escaping characters (like the backslash "\") that should not be visible
