### ISSUE TITLE
WMTS error: No TILEMATRIX specified

### ISSUE THREAD

**Issue by gioscarda** [geosolutions-it/MapStore2#3838]
### Description
Mapstore does not load some WMTS layers correctly.
It seems that when loading layers for which the capabilities document doesn't have more than one `<TileMatrixSetLink>` tag, a `MissingParameterValue` exception occurs showing this message: *No TILEMATRIX specified*.

An example:

https://sdigeot-free.austrocontrol.at/geoserver/gwc/service/wmts?layer=free%3ALOVV-ATC&style=MRVA_SMAESR_CSS&tilematrixset=EPSG%3A3857&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image%2Fpng&TileCol=281&TileRow=178

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- Set this WMTS service in the mapstore catalog: https://sdigeot-free.austrocontrol.at/geoserver/gwc/service/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=getcapabilities
- Add the following layer to the map:
  - free:LOVV-ATC
  - free:DTM_250

*Expected Result*

Layers load correctly

*Current Result*

Layers don't load correctly. A `MissingParameterValue` exception occurs with this message: *No TILEMATRIX specified*.

- Describe here the current behavior

It seems that when loading layers for which the capabilities document doesn't have more than one `<TileMatrixSetLink>` tag, a `MissingParameterValue` exception occurs showing this message: *No TILEMATRIX specified*.

**Comment by tdipisa** [comment]
@vlt1 please try to replicate this issue to see if MS is still affected by this problem.

**Comment by vlt1** [comment]
@gioscarda @tdipisa I couldn't find the layers mentioned in the service. The [example link](https://sdigeot-free.austrocontrol.at/geoserver/gwc/service/wmts?layer=free%3ALOVV-ATC&style=MRVA_SMAESR_CSS&tilematrixset=EPSG%3A3857&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image%2Fpng&TileCol=281&TileRow=178) returns XML with exception text "LAYER free:LOVV-ATC is not known.". Looking through the capabilites it seems that all layers have two TileMatrixSetLinks for EPSG:3857 and EPSG:4326. Is the problem still relevant?

**Comment by tdipisa** [comment]
@offtherailz can we close this?

**Comment by offtherailz** [comment]
Couldn't find the indicated layers or a way to replicate trying some layers from that catalog. I think we can close this issue until we find a way to replicate again the problem
