### ISSUE TITLE
Annotation do not work without setting initial state

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#3852]
### Description
Creating a new project and adding the plugin, I can not create the annotation(it fails when add geometry). 
To make annotations work, i need to set up the initial state.
```
 "annotations": {
        "config": {
          "multiGeometry": true,
          "validationErrors": {}
        },
        "format": "aeronautical",
        "defaultTextAnnotation": "New"
      },
```
### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
any

*Steps to reproduce*

- localConfig.json should contain "Annotations" plugin, with no annotations `initialState` set.
- Try to create a new annotation (annotations from burger menu -> click on "+")
- Add a new geometry, of type marker (pencil+ button-> marker) 
- click on map

*Expected Result*

- I see the marker on map

*Current Result*
- nothing happens
- a row appears in the panel

**Comment by MV88** [comment]
alreday backported to 2019.02.xx with this pr https://github.com/geosolutions-it/MapStore2/pull/4084
