### ISSUE TITLE
Dashboards are accessible via mobile, but they should not

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#3862]
### Description
from mobile is not possible to create a new dashboard,
but is possible to open them

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Chrome mobile 75.0.3770.101 Andorid 7.0

*Steps to reproduce*

- via mobile enter mapstore homepage
- login as admin
- click on dashboards tab 
- you can select dasboard here

*Expected Result*

- to see no dashboard when using mobile

*Current Result*

- you cna select them and open them.
- you can also copy and paste url and access it directly instead of using UI

**Comment by tdipisa** [comment]
it is working as expected
