### ISSUE TITLE
Timeline performance issues with many time layers

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#3866]
### Description
When there are 5 layers, the timeline's performances slow down when update times. 

Unfortunately the timeline does a full re-render each time items change, so this slows down mapstore.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
any 
*Steps to reproduce*
add 5 layer with time dimension
- Zoom timeline 

*Expected Result*

- the application is fluid

*Current Result*

- the application has problems and slow down in rendering

### Other useful information (optional):

One possible cause can be that there are too many render events.
Analyzing the profile attached (you can read it in google chrome dev tools - performance) some of the blocking events seems to be caused by `epics/timeline.js#updateRangeDataOnRangeChange`. 

[Profile-20190621T163554.zip](https://github.com/geosolutions-it/MapStore2/files/3314871/Profile-20190621T163554.zip)

Placing the timeline well zoomed and panning it a little, to trigger reload but expecting the same result, I see there are 10 set-items events. 
Debugging i see that Timeline component receives a variable  number of items, 10 times different.

Also the selectors/timeline/itemsSelector.js return a different set of data during the load to return to the same number of items at the end.

This is because for every layer we have 2 requests: One for histogram, one for domain values. 
At the end we will draw the better of the two visualizations, but this means that during the load every row will be rendered twice (one to render the histogram, one for the single points.

We can do several things to improve performances: 
 - trigger only one update when histogram and domains are loaded, to do half of the renderings and avoid unnecessary re-render.
 .- trigger only one action to update everything when all the layers loaded

**Comment by ElenaGallo** [comment]
This issue is no longer valid, it can be closed.
