### ISSUE TITLE
Coordinate editor(s) and restrictedExtent have not desired interactions

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#3885]
### Description
The coordinate editors do not consider any restrictedExtent applied via [configuration](https://dev.mapstore2.geo-solutions.it/mapstore/docs/api/plugins#plugins.Map)

it should be possible to use some contraints appliead to decimal and aeronautical format.
Here is a list of plugins that use the coordinate editor :
- Search
- GFI
- Measure
- Annotations

Another component that is affected by this problem is:
- GeometryDetails section of the spatial filter inside the Query Panel

NOTE: Also Catalog and Import (shapefiles) can add vectors that are outside of the restricted extent

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- any (not broser related)

*Steps to reproduce*

- be sure to have configured a restricted extent in mapstore
- open any map, for example: [US Population Statistics - DEV](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/4093)
- click anywhere to trigger GFI
- enable coordinate editor
- enter a point which is outside the restricted extent

*Expected Result*

- an error feedback to show the invalid number inserted

*Current Result*

- for the GFI it zooms an center to the point inserted
- for other editors you are simply allowed to enter invalid numbers (outside restricted extent)

### Other useful information (optional):

consider to treat this issue as an epic and split the two issues (query panel and editors)

**Comment by ElenaGallo** [comment]
This issue is no longer valid, it can be closed.
