### ISSUE TITLE
CRS Selector has various problems with draw tools (Annotations, Query Panel, Measure, Feature grid editing)

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#3886]
### Description
- [ ] 1) When editing an annotation feature I tried to use the crs selector dicovering this issue

![CRS selectors and annotations](https://user-images.githubusercontent.com/11991428/60330482-ccb1f380-9992-11e9-8d61-141513c69fef.gif)
- [ ] 2) another issue in annotations is passing from 4326 to 3857 before start drawing

- [ ] 3) also the query panel has problem with the crs selectors

- [ ] 4) Also the measure has problems with this

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- any (not browser related)

*Steps to reproduce*

- open a new map
- open annotations and start creating a new one (a line)
- change crs from 3857 to 4326

*Expected Result*

- you should be able to continue drawing (or you should not be able to change crs while drawing )

*Current Result*

- all the features disappears

### Other useful information (optional):

NOTE: There are also problems if you change crs before entering in the annotations panel.
steps:
- open new map
- change crs to 4326
- create a new marker annotation
- switch to 3857
- zoom out and the marker is near [0, 0] point

**Comment by tdipisa** [comment]
- The CRS Selector can be disabled in Create/Edit mode of the Annotation tool.
