### ISSUE TITLE
Widgets tray is not visible / usable in IE11

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#3888]
### Description
widgets tray is not visible on IE 11

![image](https://user-images.githubusercontent.com/11991428/60337459-6d101400-99a3-11e9-8386-f7d8ee3f035d.png)

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer 11

*Steps to reproduce*

- open ie 11
- open a map with widgets like [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/4093) one

*Expected Result*
- to see the widgets tray

*Current Result*
- the icons are not present

**Comment by tdipisa** [comment]
Starting 2020.02.00 the IE 11 compatibility is no longer supported.
