### ISSUE TITLE
Developer Guide still has dead links

### ISSUE THREAD

**Issue by zachsa** [geosolutions-it/MapStore2#3895]
### Description
This issue - https://github.com/geosolutions-it/MapStore2/issues/1400 - mentions that documentation that was previously linked to from https://geosolutions-it.github.io/MapStore2/developer-guide/developing-with-mapstore-2-intro has been moved to the Wiki. However if that is the case then I can't find the correct Wiki. 

It seems that the Wiki is still missing information that is on the developer guide. As a user that is trying to figure out how to use MapStore, I think it should still be available.

### The BUG
In the deployed version of the documentation there are dead links

### Workaround
Manually edit the URI's that the links point to to include `/developer-guide/`.

For example, the link to `https://geosolutions-it.github.io/MapStore2/project-structure`, should be manually changed to `https://geosolutions-it.github.io/MapStore2/developer-guide/project-structure`.

**Comment by tdipisa** [comment]
@zachsa the developer guide has been moved to: https://mapstore.readthedocs.io/en/latest/developer-guide/

**Comment by tdipisa** [comment]
closed for inactivity
