### ISSUE TITLE
Snapshot tool

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#390]
Create a tool to snapshot the map. 
As a user, when I click on the snapshot tool a window should show a preview of the snapshot with some information (date, size...) and allow me to download the image. 

The tool should work of course with OpenLayers and Leaflet maps. 

Here a mockup: 
![snapshot tool](https://cloud.githubusercontent.com/assets/1279510/12415279/2f2af272-be9b-11e5-841b-4469d2dcd2ca.png)

Here some useful link:
* Original Plugin in MapStore (1) : https://github.com/geosolutions-it/MapStore/blob/master/mapcomposer/app/static/externals/gxp/src/script/plugins/PrintSnapshot.js
* Server side part of the original Plugin: https://github.com/geosolutions-it/servicebox/blob/master/src/main/java/it/geosolutions/servicebox/UploadCanvas.java

**Comment by kappu72** [comment]
OpenLayers3 uses canvas as default render, so we don't need anymore html2canvas lib as  in mapstore plugin. Otherwise, as far as I know, Leaflet canvas rendering is 'experimental' and should be enabled ... setting global variable L_PREFER_CANVAS to true before the Leaflet include on your page .. (from Leaflet docs). 
For Leaflet we have a plugin [leaflet-image] (https://github.com/mapbox/leaflet-image) but It has some limitation, see docs. 
In this case html2canvas  could be another options.

**Comment by mbarto** [comment]
I would not go for L_PREFER_CANVAS, I don't think having leaflet canvas rendering in general is a good ide.
if we can make it work with leaflet-image, go for it, if not let's use html2canvas that we are already familiar with.

**Comment by kappu72** [comment]
So, not going for L_PREFER_CANVAS let only one option for Leaflet: html2canvas lib
Approved?

**Comment by offtherailz** [comment]
Yes.

**Comment by kappu72** [comment]
FYI Chrome is restricting the length of URLs that can be deserialized  to 2MB

**Comment by offtherailz** [comment]
This is why we do a POST to send the image and a GET to get it. Chrome URL limit is the bigger one, Firefox and IE are less permissive for this
What's the problem exactly ?

**Comment by kappu72** [comment]
It was just an info not a problem, Firfox is the only one working if the img size is bigger then 2MB, ie doesn't support download attribute in <a> element. I have to test mobile browser.

**Comment by offtherailz** [comment]
I didn't understand what you mean: 
* that the `toDataURL` function don't work well with big images ?
* `toDataURL` works. The preview is an `<img>` but if the image is too big and overflows the browsers' limit for the `src` attribute the browser crash (or something like that) 

In the second case the answer is simple. We have to use a `<canvas>` for the preview instead of an `<img>` and copy the canvas using canvas `drawImage` (this can also scale the image) if we can't use the same canvas for the preview and image generation, properly scaled with css .

Let me know your opinion about it.

**Comment by offtherailz** [comment]
Ok, we clarified. 
Chrome don't support image size bigger than 2mb for **in browser** downoload. We have to introduce a check that use the server side service if the img is bigger than 2MB and the browser is Chrome.
