### ISSUE TITLE
Updating fixed NPM dependency versions

### ISSUE THREAD

**Issue by zachsa** [geosolutions-it/MapStore2#3901]
### Description
Doing an `npm install` shows that many library versions labeled as deprecated are used. including the `openlayers` package, which has been deprecated in favor of a different package (`ol`).

Is there a plan to update to non-deprecated libraries? I see that a similar thing was raised last year (Issue https://github.com/geosolutions-it/MapStore2/issues/3217), but that the decision was NOT to update to newer versions of dependencies due to this effort involved.

Whilst this is understandable, is it not likely that MapStore will soon be using versions of libraries that are behind the current documented versions of libraries? I'm still trying to figure out MapStore - or more particularly, assess whether it's a good fit for a project. And this seems like a deal breaker... My understanding is that if I choose to use openlayers with MapStore then I will almost certainly need to work with the openlayers code directly (but I'm not sure on this yet), and that using a deprecated version of openlayers will be quite frustrating.

**Comment by mbarto** [comment]
Specifically about OpenLayers: we already tested OpenLayers 5 (latest) for a customer, and the changes to MapStore code to make it work were trivial, so I am optimistic that we will update our dependency to openlayers 5 soon.

**Comment by zachsa** [comment]
As I mentioned on issue #3217 thread (which is closed), the list of deprecated dependencies is here:

```
npm WARN deprecated babel-istanbul-loader@0.1.0
npm WARN deprecated babel-preset-es2015@6.6.0
npm WARN deprecated extract-text-webpack-plugin@2.1.0
npm WARN deprecated ag-grid@3.3.3
npm WARN deprecated @turf/inside@4.1.0
npm WARN deprecated json-2-csv@2.1.2
npm WARN deprecated openlayers@4.6.4
npm WARN deprecated @turf/polygon-to-linestring@4.1.0
npm WARN deprecated turf-bbox@3.0.10
npm WARN deprecated turf-buffer@3.0.10
npm WARN deprecated turf-intersect@3.0.10
npm WARN deprecated turf-point-on-surface@3.0.10
npm WARN deprecated turf-union@3.0.10
npm WARN deprecated minimatch@2.0.10
npm WARN deprecated jade@0.26.3
npm WARN deprecated istanbul@0.4.5
npm WARN deprecated core-js@2.3.0
npm WARN deprecated doc-path@1.2.0
npm WARN deprecated nomnom@1.8.1
npm WARN deprecated intl-relativeformat@1.3.0
npm WARN deprecated core-js@2.4.1
npm WARN deprecated turf-meta@3.0.12
npm WARN deprecated geojson-normalize@0.0.0
npm WARN deprecated turf-combine@3.0.12
npm WARN deprecated turf-helpers@3.0.12
npm WARN deprecated turf-distance@3.0.12
npm WARN deprecated turf-center@3.0.12
npm WARN deprecated turf-inside@3.0.12
npm WARN deprecated turf-explode@3.0.12
npm WARN deprecated core-js@1.2.7
npm WARN deprecated minimatch@0.2.14
npm WARN deprecated graceful-fs@2.0.3
npm WARN deprecated turf-bbox@3.0.12
npm WARN deprecated turf-invariant@3.0.12
npm WARN deprecated browserslist@1.7.7
npm WARN deprecated hawk@3.1.3
npm WARN deprecated graceful-fs@3.0.11
npm WARN deprecated json3@3.3.2
npm WARN deprecated flatten@1.0.2
npm WARN deprecated hoek@2.16.3
npm WARN deprecated sntp@1.0.9
npm WARN deprecated cryptiles@2.0.5
npm WARN deprecated boom@2.10.1
npm WARN deprecated natives@1.1.6
npm WARN deprecated uws@9.14.0
npm WARN deprecated graceful-fs@1.2.3
```

And pushing a project generated via the `createProject.js` script I get a lit of security vulnerabilities on my GitHub page:

![GitHub security warnings](https://user-images.githubusercontent.com/6336500/60812636-4071ae80-a192-11e9-82d7-57c381402865.PNG)
