### ISSUE TITLE
Zoom on marker or text annotations doesn't work

### ISSUE THREAD

**Issue by gioscarda** [geosolutions-it/MapStore2#3905]
### Description
When zooming on marker or text annotation the map zoom to max extent.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Browser Version Affected*

All

*Steps to reproduce*

- open a map (or create a new one)
- create a marker annotation
- create a text annotation
- from the annotation list click on the marker annotation to open its details panel
- click on zoom
- go back to the annotation list
- click on the text annotation to open its details panel
- click on zoom

[This](https://dev.mapstore.geo-solutions.it/mapstore/#/viewer/openlayers/10335) is the dev map used for testing.

*Expected Result*

- Zoom works fine for marker and text annotations

*Current Result*

- The map zoom to the max extent
![wrong_zoom_annot.gif](https://images.zenhubusercontent.com/5cda9c3818690954352b7b76/db026866-219f-43c8-8177-5c21ac140dc0)

**Comment by kasongoyo** [comment]
It seems this issue is a duplicate and have already been solved, perpahs by this commit https://github.com/geosolutions-it/MapStore2/commit/3578a7d356fb87825d2511dd60769f80967843ea
