### ISSUE TITLE
Text annotations - wrong text align in preview

### ISSUE THREAD

**Issue by gioscarda** [geosolutions-it/MapStore2#3910]
### Description
When changing the style of a text annotation, if you change the 'Text Align' property to left/right the preview shows the opposite (right/left). The same change in the map applies correctly. 

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Browser Version Affected*

- All

*Steps to reproduce*

- open a map
- open the annotations tool from the burger menu
- click on '+' to add a new annotation
- click on 'Add a new geometry' and select 'Text'
- insert a Text
- set the annotation position by clicking on the map or through the coordinate editor (optional)
- click 'change style'
- change the 'Text Align' property to left/right from the 'Font' section
- see the results in the preview and on the map

*Expected Result*

- If 'left' selected the text annotation should be aligned on the left both on the map and in preview
- If 'right' selected the text annotation should be aligned on the right both on the map and in preview

*Current Result*

- If 'left' selected the text annotation is aligned on the left on the map and on the right (wrong!) in preview
- If 'right' selected the text annotation is aligned on the right on the map and on the left (wrong!) in preview
![text_annot_align.gif](https://images.zenhubusercontent.com/5cda9c3818690954352b7b76/b5f61bbe-f912-4ff7-867a-534274381f84)

**Comment by MV88** [comment]
While testing on dev [this map](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/10415) with Chrome 75.0.3770.142 i found this layout problem with TEXT annotation style panel

![Text style annotation layout bug](https://user-images.githubusercontent.com/11991428/61281793-8645fc80-a7ba-11e9-9783-225cbb7d5c51.gif)

It seems happening only on windows machines,
@offtherailz @kasongoyo if you have linux can you check this?

**Comment by kasongoyo** [comment]
@MV88 If it is about text alignment then I experienced it even with mac. I didn't test much with other style and I have difficulty following the example you have posted.

**Comment by gioscarda** [comment]
@kasongoyo , I close this issue because another issue has been opened (see #3970 ) to refer the problem reported by @MV88 .
