### ISSUE TITLE
Broken links on readthedocs.io documentation

### ISSUE THREAD

**Issue by zachsa** [geosolutions-it/MapStore2#3912]
### Description
There are quite a lot of broken links on the Developer Guide.

These include:

1.  On  https://mapstore2.readthedocs.io/en/latest/developer-guide/plugins-architecture/, there is a link to http://dev.mapstore2.geo-solutions.it/mapstore/examples/plugins/ that doesn't work. Instead it should be https://mapstore.geo-solutions.it/mapstore/examples/plugins/

2. On https://mapstore2.readthedocs.io/en/latest/developer-guide/plugins-howto/, there is a link to https://mapstore2.readthedocs.io/en/latest/developer-guide/plugins-howto/mapstore-projects that doesn't work

**Comment by mbarto** [comment]
It is indeed broken at the moment.
If you want to have a look at the last stable plugins example, go here: https://mapstore.geo-solutions.it/mapstore/examples/plugins/
Thanks for the notification, we will check what is broken and restore it in dev

**Comment by zachsa** [comment]
Thank you

**Comment by tdipisa** [comment]
The Example plugin is available [here](https://dev.mapstore.geo-solutions.it/mapstore/examples/plugins/).
