### ISSUE TITLE
Query panel errors when switching CRS

### ISSUE THREAD

**Issue by gioscarda** [geosolutions-it/MapStore2#3922]
### Description
The spatial filter of the query panel allows to filter geometries by drawing a region on the map. Drawn rectangles, circles and polygons disappear when switching CRS.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Browser Version Affected*

- All (browser independent)

*Steps to reproduce*

- open a map with vector layers
- open the TOC and select a vector layer
- open the layer attribute table
- open the Advanced Search tool
- select a filter type (rectangle, circle or polygon) in the 'Filter Type' field of the 'Region of interest' section
- draw it on the map
- change CRS through the CRS selector
- verify the region geometries are correctly represented on the map
- open the region Details and change some geometry
- verify the changes apply correctly

*Expected Result*

- the region geometries are correctly represented on the map
- the region can be correctly modified

*Current Result*

- the region geometries disappear
- the region can't be correctly modified

![changing_CRS_0](https://user-images.githubusercontent.com/43670920/60874979-42db1380-a239-11e9-905e-9c881b1012e1.gif)

### Other useful information (optional):

When using the circle as region of interest, without the 3857 EPSG (default), if you try to change the radius it produces unexpected changes to the circle size.

**Comment by tdipisa** [comment]
The following behavior needs to be fixed:

>When using the circle as region of interest, without the 3857 EPSG (default), if you try to change the radius it produces unexpected changes to the circle size.

Then CRS Selector should be disabled if the Query Panel is active

**Comment by MV88** [comment]
> Then CRS Selector should be disabled if the Query Panel is active

it is not enough to disable the CRS plugin while the query panel is opened because the problem persist.

steps to reproduce:
- open [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/4093)
- login as admin
- change crs to 4326
- open query panel 
- draw a circle
- edit radius

expected result :
current result the circle becomes big

**Comment by tdipisa** [comment]
@MV88 the first part of my previous comment means exactly what you wrote.
