### ISSUE TITLE
Measurement errors when switching CRS

### ISSUE THREAD

**Issue by gioscarda** [geosolutions-it/MapStore2#3923]
# Description
Lines/areas/bearings drawn on map have unexpected changes when switching CRS during measurements.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Browser Version Affected*

- All

*Steps to reproduce*

- open a map
- open the measure tool from the burger menu
- select distance/area/bearing as measurement type
- draw the geometry you want to measure on the map
- switch CRS through the CRS selector
- verify no graphic errors occurs (geometry does not change its size, geometry does not disappear)
- verify the measure value is correct
- draw another geometry to measure (do not change the last CRS selected)
- switch CRS through the CRS selector
- verify no graphic errors occurs (geometry does not change its size, geometry does not disappear)
- verify the measure value is correct

*Expected Result*

- When switching CRS the geometry to measure does not change its size and it does not disappear.

*Current Result*

- When switching CRS the geometry to measure seems to disappear or to change its size.

![changing_CRS_1](https://user-images.githubusercontent.com/43670920/60877598-6f455e80-a23e-11e9-93d4-5160696efaa6.gif)

**Comment by tdipisa** [comment]
The CRS Selector can be disabled when the Maesure Panel is active, it can be re-enabled as soon the Measure panel is closed.
