### ISSUE TITLE
Graphic glitch when filtering features by region

### ISSUE THREAD

**Issue by gioscarda** [geosolutions-it/MapStore2#3924]
### Description
When filtering the features of a vector layer by region, the region geometry should not be visible after the search has been triggered.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Browser Version Affected*

- All

*Steps to reproduce*

- open a map with vector layers
- open the TOC and select a vector layer
- open the layer Attribute Table
- open the Advanced Search tool
- select 'Filter Type' and 'Geometric Operation' in the 'region of interest' section
- draw the region geometry on the map
- click on search

*Expected Result*

- the advanced search window closes, the feature grid opens and the region geometry is not visible on the map
- if the filter is configured to stay in the map it should not have the white fill

*Current Result*

- the advanced search window closes, the feature grid opens and the region geometry is still visible on the map (it has an opaque fill also which is wrong)

![Selection_041](https://user-images.githubusercontent.com/43670920/60881809-cb13e580-a246-11e9-9372-d9c0c649c6df.png)

**Comment by MV88** [comment]
addendum: if the filter is configured to stay in the map it should not have the white fill
