### ISSUE TITLE
Wrong area in printing when using EPSG:4326

### ISSUE THREAD

**Issue by gioscarda** [geosolutions-it/MapStore2#3926]
### Description
When using EPSG:4326 CRS a wrong area is considered by the print tool.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Browser Version Affected*

- All

*Steps to reproduce*

- open a map
- switch to EPSG:4326 through the CRS selector
- open the print tool from the burger menu
- click on 'Print' to print the area visible in the preview
- download the result as pdf and verify it reflects the previous image

*Expected Result*

- the print preview, the printed image and the downloaded pdf image reflect the visible area of the map

*Current Result*

- the printed image and the downloaded pdf image do not reflect the visible area of the map

![Selection_042](https://user-images.githubusercontent.com/43670920/60887450-c48c6a80-a254-11e9-9227-ed89077a0215.png)

### Other useful information (optional):
It works fine with default EPSG (3857).
It should be tested with more CRS (only EPSG:4326 available)

**Comment by tdipisa** [comment]
I cannot reproduce the issue following the provided steps. Anyway there are problems when switching the CRS with the print preview opened: the preview isn't updated and a wrong area is printed clicking on Print button.

**However the CRS Selector can be disable while opening the Print panel and re-enabled as soon it is closed.**
