### ISSUE TITLE
Dashboard error in console when exporting a chart with no data

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#3927]
### Description
there is an error in console when exporting a chart with no data

the app continues to work though

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- open [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/dashboard/5728) dashboard as admin
- move the map where no us states are visible
- click on export of the poulation per region chart
![image](https://user-images.githubusercontent.com/11991428/60895012-23a5ab80-a264-11e9-909d-caabb8dfbf64.png)

*Expected Result*

- export of empty widgets does not provoke any error (even if harmless)
- probably the export should be disabled while no data are there (and the "download chart data" tool too)

*Current Result*

in console it appears this
![Uploading image.png…]()

**Comment by kasongoyo** [comment]
@MV88 After experimentation, I realised that the best fix for this issue is to hide export when the chart is not available.

**Comment by francoperversi** [comment]
@kasongoyo 

>Open Mapstore
> Login as admin
> Click on Dashboard
> Click on All Widgets
> Move the map where no data exists
> Population per region Chart options

When I click on "Download Data", which is now displayed as disabled, start a download with a empty .csv file, can you please fix this issue?

![Disabled](https://user-images.githubusercontent.com/54808782/64343117-392d1c80-cfec-11e9-8829-a861f23a00d4.gif)
