### ISSUE TITLE
Cross layer filter cannot be disabled when filled

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#3929]
### Description
see title

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- open a new map 
- add us states layer
- enter advanced search for it (via feature grid)
- compile the cross layer filter section
- try to disable the cross layer filter with the switch button

*Expected Result*

- you can disable cross layer filter

*Current Result*

- you cannot disable cross layer filter

### Other useful information (optional):

if disabled it should not be applied when searching (same as ROI)
this happen also in production

**Comment by kappu72** [comment]
Searching the code, I have seen that this behavior is wanted [see](https://github.com/geosolutions-it/MapStore2/blob/ce9f78b4c4a1231dd76151450f63b256e11aa67f/web/client/components/data/query/CrossLayerFilter.jsx#L55)

**Comment by kasongoyo** [comment]
@kappu72 Yeah, the current behaviour prevent the switch button to respond when cross layer filter operation and queryCollection type is set. This need to be fixed, the switch button must respond to user action regardless.
