### ISSUE TITLE
Dashboard: toolbar does not update when last layer is removed from map widget

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#3931]
### Description
the toolbar does update after deleting last layer from map widget

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- open home mapstore
- login as admin and create a new dashboard
- start creating a map widget with one layer
- select the layer and click for remove
![image](https://user-images.githubusercontent.com/11991428/60961872-58ba0880-a30d-11e9-93d2-348a70d827c6.png)

*Expected Result*

- to see animation that removes the delete and layer settings button from the in toolbar

*Current Result*

- they stay in the toolbar clicable with inconsisten behaviour
![image](https://user-images.githubusercontent.com/11991428/60961890-6079ad00-a30d-11e9-90f8-14634bd357af.png)

**Comment by tdipisa** [comment]
Dupluicate of #3958
