### ISSUE TITLE
Resizable DrawerMenu produces unexpected behaviour of the TOC

### ISSUE THREAD

**Issue by gioscarda** [geosolutions-it/MapStore2#3936]
### Description
Investigations needed about the resizable DrawerMenu (see #3767 ).
Applying the following configuration, the TOC panel remains visible even if the layer settings panel (or the widget panel) opens (see the picture):
```
{
    "name": "DrawerMenu",
    "cfg": {
        "menuOptions": {
            "resizable": true
        }
    }
}
```
![Selection_003](https://user-images.githubusercontent.com/43670920/60978379-5669a580-a331-11e9-94ff-ff4483efb298.png)

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [x] Firefox
- [ ] Safari

*Browser Version Affected*

- All

*Steps to reproduce*

- configure the DrawerMenu to be resizable
- open a map
- add a layer to it
- open the TOC
- resize the TOC to make it wider
- open the layer settings panel

*Expected Result*

- once the settings panel opens the TOC should be not visible

*Current Result*

- the TOC panel is still visible behind the layer settings panel

### Other useful information (optional):
It happens with the widgets panel also.

**Comment by tdipisa** [comment]
We are reviewing the entire MS's layout (closed in favor of #4254).
