### ISSUE TITLE
maxNativeZoom parameter

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#394]
`maxNativeZoom` should be a parameter that indicate the max available zoom for the tile source (wms, wfs...). 
OL3 support maxZoom on the ol.source object to support this. If the map zoom is higher, the tiles are streached. 

Leaflet has a `maxNativeZoom` parameter but it doesn't seems to work as expected. Investigate when leaflet migrate to the next version.

**Comment by simboss** [comment]
is this still open??

**Comment by offtherailz** [comment]
Leaflet support is still missing. We could investigate if the recent leaflet 2.0 supports it

**Comment by offtherailz** [comment]
We have #394 #1639 and #2163. I suggest to test the functionalities before to close.

**Comment by tdipisa** [comment]
@offtherailz I think we can close this issue, right?

**Comment by tdipisa** [comment]
closed for inactivity.
