### ISSUE TITLE
layer filter is not enable

### ISSUE THREAD

**Issue by snuffer82** [geosolutions-it/MapStore2#3953]
Hi,
I don't understand how to enable the filter layer. I have some layers from geoservers that show the data and the table correctly but the filter layer option is always disabled.
Do you have any suggestions?
thank you so much

![layre](https://user-images.githubusercontent.com/17122286/61122596-81bfd200-a4a2-11e9-99a4-d9e39394425b.png)

Geoserver active services
![geoserver](https://user-images.githubusercontent.com/17122286/61122584-7a98c400-a4a2-11e9-8b91-8ab16a5e1ede.png)

**Comment by mbarto** [comment]
@snuffer82 can you please use the mailing lists for this kind of questions?
Short answer: you need the querylayer module in GeoServer to use this functionality.
You can find more info about this module here: https://docs.geoserver.org/stable/en/user/extensions/querylayer/index.html

**Comment by snuffer82** [comment]
I apologize for not using the mailing list...next time I will use it.
I thank you for the suggestion, now everything works correctly
thanks 
paolo
