### ISSUE TITLE
Some examples broken in released war

### ISSUE THREAD

**Issue by landryb** [geosolutions-it/MapStore2#3962]
Testing a bit the war for v2019.01.01, locally hosted on a tomcat on my machine, the following examples don't work (all the others under `examples/` seem fine):
  * http://localhost:8080/mapstore/examples/login/ (doesnt error out, but shows nothing)
  * http://localhost:8080/mapstore/examples/myapp/ (myapp.js missing in dist ?)
  * http://localhost:8080/mapstore/examples/layertree/ (layertree.js missing in dist ?)
  * http://localhost:8080/mapstore/examples/queryform/ (queryform.js missing in dist ?)
  * http://localhost:8080/mapstore/examples/rasterstyler/ (rasterstyler.js missing in dist ?)
  * http://localhost:8080/mapstore/examples/styler/ (styler.js missing in dist ?)

**Comment by landryb** [comment]
I see this matches the examples commented out in https://github.com/geosolutions-it/MapStore2/blob/master/build/examples.js but then maybe they shouldnt be shipped in the war ?

**Comment by mbarto** [comment]
@landryb thanks for notifying us, I created a PR to remove those examples, that are not mantained anymore: https://github.com/geosolutions-it/MapStore2/pull/3986
