### ISSUE TITLE
GFI unavailable when the 'Filter Layer' Query Builder window is opened

### ISSUE THREAD

**Issue by gioscarda** [geosolutions-it/MapStore2#3981]
### Description

In #3785 it was required that:

> Once a valid filter is created the Apply icons is enabled. In order to see it applied on the map I need to click on the Apply Icon in the Toolbar; Once I click on the Apply Icon, the map content should be updated accordingly, no FG is shown. **If I do a GetFeatureInfo, the filter I am creating is applied to the content I get, the QB is not closed so that I can keep working**. Now I can save or discard.

and

> Save enables so I can save my work, **I click on Save Icon in the QB Toolbar. The filter is persisted but the QB is not closed ( I might want to keep playing).**

When applying/saving a filter the GetFeatureInfo is unavailable.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- All

*Steps to reproduce*

- open a map
- load a vector layer
- open the TOC
- select the layer
- open the QueryBuilder by clicking the 'Filter Layer' icon of the TOC toolbar
- set up a filter
- click on 'Apply' in the QB toolbar
- click a point on the map
- verify that GFI works
- click on 'Save' in the QB toolbar
- click a point on the map
- verify that GFI works

*Expected Result*

- GetFeatureInfo window opens

*Current Result*

- Nothing happens (GFI unavailable)

### Other useful information (optional):

More in general, when the QB window is opened the GFI is unavailable (it is the same for the FeatureGrid query builder).

**Comment by tdipisa** [comment]
**The Identify tool must be disabled if the drawing tool of the ROI is active.**
