### ISSUE TITLE
Undo/Discard button disabled even if changes have been made to the filter

### ISSUE THREAD

**Issue by gioscarda** [geosolutions-it/MapStore2#3990]
### Description
Some discrepancies between the `Layer Filter` behaviour and what said in #3785 :

> Discard is new. It discards the changes we do and restore the previous saved filter if there is one or an empty filter. **It enables everytime we make a change to the filter or we Apply|Reset it** and we have a previous filter that was Saved in the QB or when we start with empty (it send us back to empty in this case). It updates map content immediately.

and

> As soon as I make changes the Discard icon is enabled. If I discard now I go back to empty.

Start with a new empty filter. All the QB toolbar buttons are disabled. When setting up a filter the `Apply` button is enabled but the `Undo/Discard` one is still disabled.

![undo_discard_filter](https://user-images.githubusercontent.com/43670920/61616252-3f4b8180-ac68-11e9-9617-359b9d38f86b.gif)

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Browser independent

*Steps to reproduce*

- open a map
- load a vector layer form the catalog
- open the TOC and select the vector layer
- click the `Filter Layer` button of the TOC toolbar (the Query Builder opens)
- verify all the QB toolbar buttons are disabled
- set up a filter
- verify the `Apply` and `Undo` buttons state

*Expected Result*

- `Apply` and `Undo` buttons are enabled

*Current Result*

- `Apply` button is enabled, `Undo` button are disabled

### Other useful information (optional):
The 'Undo/Discard' button remains disabled even if the changes have been applied and if they have been saved. I can `Undo/Discard` the filter only after a `Reset`.

**Comment by tdipisa** [comment]
> The 'Undo/Discard' button remains disabled even if the changes have been applied and if they have been saved. I can Undo/Discard the filter only after a Reset.

This isn't true. The Undo button is enabled also at each Apply.

Speaking with @simboss we decided to leave the functionality as it is now.
