### ISSUE TITLE
TOC Review - layer filter

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#4007]
### Description
When toc has no layers, hide the filter field

*Steps to reproduce*

- Open a new map
- Open Toc

*Expected Result*

- layer filter is **not** visible

*Current Result*

- layer filter is visible

**Comment by tdipisa** [comment]
@MV88 please, can you backport this to 2019.02.xx stable branch ?

**Comment by MV88** [comment]
it has already been backported in this pr https://github.com/geosolutions-it/MapStore2/pull/4084

the confusion/problem can be related to the fact that it lists the id of prs instead of the issues
