### ISSUE TITLE
Trojan on file WPS_2_0.js

### ISSUE THREAD

**Issue by metourneau** [geosolutions-it/MapStore2#4024]
### Description
When I want to install the nodejs project (npm install) - WPS_0_2.js is blocked as trojan.
After I cant start MapStore.

check that => https://news.drweb.com/show/?i=13315&lng=en

*Steps to reproduce*

- git clone --recursive https://github.com/geosolutions-it/MapStore2.git
- npm install => file move to the quarantine. (https://www.f-secure.com/v-descs/trojan-downloader_js_maljas.shtml)
- npm start => Module not found: Error: Can't resolve './lib/WPS_2_0' in 'E:\wamp\www\MapStore2\node_modules\ogc-schemas'

There is a way to start without that file?

**Comment by mbarto** [comment]
@metourneau I don't think we can do much for this. Probably this is a false-positive from your antivirus (F-secure ?).  The links you sent are talking about obfuscated javascript code recognized as trojans. Most of the code in any nodejs application dependencies list (node_modules) is obfuscated.
You can probably change your antivirus settings to ignore node_modules folder(s) or any specific path you need.

**Comment by tdipisa** [comment]
closed for inactivity
