### ISSUE TITLE
Confirmation dialog in map on user logout 

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#4034]
### Description
When you logout from a new map containing unsaved changes, MS should shows a confirmation dialog to proceed or not. The redirect to the home page should be performed if the user choose to discard changes.

The same behavior should be adopted in case of existing maps with pending changes on them and must be applied also when the user click on the Home button (not just when disconnecting).
Obviously, the confirmation dialog must be shown only if the user has write permissions.

Modifications on map center can be excluded from the check but not the zoom level.

### Other useful information:
This warning must be enabled by configuration (by default is enabled)

**Comment by ElenaGallo** [comment]
@kboczkowski-clurgo When you logout from a new map containing unsaved changes, and click on yes on the unsaved changes modal.You are redirect to the login modal window.
![test34](https://user-images.githubusercontent.com/56537133/71190088-31844180-2284-11ea-8547-8ed07eede34e.gif)

*How to reproduce*

- Open MapStore
- Login as admin
- Open New Map
- Add a layer or change zoom level
- Log out 
- Click on yes on the unsaved changes modal

*current:*

- The login modal opens

*expected:*

- Redirect to the Home Page

**Comment by ElenaGallo** [comment]
@kboczkowski-clurgo When disconnecting from a new map that contains no changes. You are redirect to the login modal window.
![issue 4034](https://user-images.githubusercontent.com/56537133/71983621-7d912900-3227-11ea-87e8-9e5a0d69a79a.gif)


*How to reproduce*

- Open MapStore
- Login as admin
- Open New Map
- Log out 

*current:*

- The login modal opens

*expected:*

- Redirect to the Home Page
