### ISSUE TITLE
Not easy to scroll dashboards on mobile

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#4035]
### Description
If you have many widgets that have some sort of internal scroll or drag events (map, tables) and you can edit the dashboard is very hard to stroll, because touch events are captured by the widgets (scrolling the table, moving map, dragging widgets) 
![widgets-mobile](https://user-images.githubusercontent.com/1279510/62379091-8548f500-b546-11e9-9427-5ad04b1016c9.gif)

A possible solution is to add a small margin on the right to allow to scroll easy by using it. 

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
tested on chrome mobile.

*Steps to reproduce*

- Open a dashboard like (this)[http://dev.mapstore2.geo-solutions.it/mapstore/#/dashboard/5652] where you have edit permissions (with widgets like table or map)
- try to scroll up and down with the finger

*Expected Result*

- It should be easy to find a way to scroll widgets

*Current Result*

- It's hard to find out a point on the viewport to activate scroll.

**Comment by vlt1** [comment]
@tdipisa @offtherailz 
I suggest to add  margin-top/bottom between widgets for mobile devices.
What do you think about it?

**Comment by tdipisa** [comment]
> I suggest to add margin-top/bottom between widgets for mobile devices.
What do you think about it?

we wouldn't like to add other margin betweek widgets, if adding some margin on the right solves the issue is enough for us.
