### ISSUE TITLE
Enhancement - Create a Map Switcher Module

### ISSUE THREAD

**Issue by pgssimon** [geosolutions-it/MapStore2#4040]
### Description
Create a Map Switcher Module
Would be similar to the background switcher plugin but would display available maps and allow switch to the map chosen keeping the bbox and zoom from the original map

**Comment by mbarto** [comment]
@pgssimon it would be a nice addition: are you working on it and wishing to contribute?

**Comment by pgssimon** [comment]
I would love to - I just need to find some time to properly learn reactjs and redux.
The new docs are pointing me in the right direction... https://mapstore.readthedocs.io/en/latest/developer-guide/reactjs-and-redux-introduction/

My dev skills are mainly in .Net, javascript and python.

**Comment by tdipisa** [comment]
@pgssimon maybe the [Map Catalog tool](https://mapstore.readthedocs.io/en/latest/user-guide/map-catalog/) recently developed can suits your needs.

**Comment by wdcsimon** [comment]
@tdipisa the map catalog tool is great, but only opens to the default map view - could we have a checkbox option to enable passing through the current maps bounds to the new map?
