### ISSUE TITLE
Settings and delete buttons once a layer has been removed in map widget

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#4048]
### Description
Private test failed failed i can't follow the test, it is not possible add a layer to the 'Empty Map', in the Select a layer window there is this message: No record matched

We should avoid sending the authkey from QA GS since the user integration is set only in DEV

### Other useful information (optional):

Hiptest URL:
https://app.hiptest.com/projects/48097/test-runs/266514/folder-snapshots/2539630/scenario-snapshots/9747830/test-snapshots/12559302

**Comment by offtherailz** [comment]
After merging #4057 ( solves #4056) this test passes
