### ISSUE TITLE
Filter timeline by viewport

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#4049]
### Description
It seems that the histogram is not updated according to the viewport, then the filter by veweport button is not enabled by default.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [ ] Safari

*Steps to reproduce*

- Open this map
For DEV: https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/10279
For QA: https://qa.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/7377

![timeline3](https://user-images.githubusercontent.com/1280027/62556169-a24a3480-b874-11e9-9bd8-977e66bdc2ee.gif)

### Other useful information (optional):

**Comment by offtherailz** [comment]
@tdipisa The button should not be enabled by default (only for specific projects it should be). Probably the test has been copied from a custom installation with custom configuration. 
The linked test has to be fixed an repeated when the #4056 is solved

**Comment by offtherailz** [comment]
About the problem with the viewport, it seems it has been fixed on geoserver introducing support to advanced projection handling and wrap continuous map support. 
I'm going to verify and close this issue.
