### ISSUE TITLE
Improve the Attribute table User Guide

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#4074]
### Description
In the [Attribute Table User Guide](https://mapstore.readthedocs.io/en/v2019.02.00/user-guide/attributes-table/) a documentation on how to use the column filter per attribute is still missing. That documentation need to be introduced with an explanation of the supported operators (<, >, <>, !=, >=, ...)

### Other useful information (optional):
Images included in the documentation must be small and optimized for the web.

**Comment by francoperversi** [comment]
Please @kasongoyo the text has some errors to fix (see below)
And there are also points missing after the word "column", on the text under the image below

![Cattura](https://user-images.githubusercontent.com/54808782/64172495-65fafb80-ce55-11e9-933e-5ce8752efa42.PNG)

**Comment by kasongoyo** [comment]
@francoperversi Can you elaborate a bit about your suggestions? I want to be sure.

**Comment by kasongoyo** [comment]
@francoperversi I don't think if I have understood well about the text errors? Maybe you can rewrite the text without errors and also I don't get it about the missing text after the image.
