### ISSUE TITLE
Sometimes the getFeatureInfoOnFeatureInfoClick WMS fails

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#4090]
### Description
Sometimes the order of data returned changes and this is caused by the asynchronous flow in the epic [here](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/epics/identify.js#L52)

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- i was not able to reproduce it locally but it was failing sometimes on travis...

*Expected Result*

- to make this test always pass

*Current Result*

- sometimes it fails because of [this](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/epics/__tests__/identify-test.js#L102) line

**Comment by francoperversi** [comment]
Impossible to test, this issue fixes a test that was randomly failing
