### ISSUE TITLE
Implement sample home page

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#41]
with links to available examples:
* viewer
* i18n sample

And the list of the maps from GeoStore with the possibility to open the viewer.

**Comment by offtherailz** [comment]
Here a mockup.

![home page](https://cloud.githubusercontent.com/assets/1279510/9601016/f814fdce-509e-11e5-9e8c-d15fc3103a7d.png)

**Comment by mbarto** [comment]
Looks good

**Comment by offtherailz** [comment]
Duplicated issue? the updated one is this: https://github.com/geosolutions-it/MapStore2/issues/84 .
Ported mockup
