### ISSUE TITLE
Layers list for CrossLayerFilter sometimes is wrongly created

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#4143]
### Description
- Layer list can be wrongly created when you are trying to access the query form directly from the TOC. 

The reason is that the condition that filters the layers list does not use the correct search url (if available). 
when opening the query form from the feature grid infact it uses the url present in search.url while when opening directly the filter from toc it uses the url property present in the layer object.

- another problem is that it does not filter out the background layers (@offtherailz is this by design? )

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- not browser related

*Steps to reproduce*

- open [this](http://vm-linuxgeofetest.comune.genova.it/MapStore2/#/viewer/openlayers/1000001498) map 
- open toc
- select AREE DI EMERGENZE
- open the query form from here 
![image](https://user-images.githubusercontent.com/11991428/64273526-c6676700-cf41-11e9-8dc7-f7c0f7ed30a6.png)
- check and note the list of layers in cross layer filter section
- now close the queryform 
- open feature grid and then the query form from there
- check and note the list of layers in cross layer filter section

*Expected Result*

- to have same list

*Current Result*

- list are different

**Comment by offtherailz** [comment]
you can remove the backgrounds, if you prefer.

**Comment by MV88** [comment]
> you can remove the backgrounds, if you prefer. It looks more correct, also to me

i did it in the pr
