### ISSUE TITLE
Enable the Identify tool for Map widgets in dashboards

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#4150]
### Description
The Identify tool should be enbled for map widgets in dashboards to perform GFI request and show resuls in a popup. Things to consider are:

1. The Identify should be enabled by default for map widgets in dashboard, if the user clicks on the map the Info popup appears
2. The Identify should be enabled by default for map widgets but there should be the possibility to disable it if necessary by map widget configuration panel. A new button can be added for this in the toolbar as reported by the image below

![image](https://user-images.githubusercontent.com/1280027/97025451-5e664c80-1558-11eb-9e2f-3f9c30752150.png)

3. The popup could generate strange behavior in too small map widgets, we can consider to deactivate the identify tool and therefore not show the popup on the user click if the map is too small

### Other useful information (optional):

**Comment by offtherailz** [comment]
Some temporary work is present in this PR.
https://github.com/geosolutions-it/MapStore2/pull/5390

**Comment by ElenaGallo** [comment]
@AGMETEOR the map widget is not displayed correctly and zooming in or scrolling the map does not load.
![mapwidget](https://user-images.githubusercontent.com/56537133/102480750-05e79300-4061-11eb-9002-cff8b0935150.gif)

**How to Reproduce**
- Open a new dash
-  Click on Widgets
-  Click on Map
- Click on Empty map
- Click on Save
- Pan on map
- Zoom in 

*Current Result*
Panning the map is not displayed correctly and zooming in on the map does not load

**Comment by tdipisa** [comment]
@ElenaGallo this is probably a problem related to [this PR](https://github.com/geosolutions-it/MapStore2/pull/6309). @AGMETEOR can you please confirm?

**Comment by AGMETEOR** [comment]
> @ElenaGallo this is probably a problem related to [this PR](https://github.com/geosolutions-it/MapStore2/pull/6309). @AGMETEOR can you please confirm?

@ElenaGallo , looking at the gif indeed there's already PR solving that issue

**Comment by tdipisa** [comment]
@ElenaGallo the PR mentioned above has been merged few minutes ago. Please test again as soon as dev is updated.
