### ISSUE TITLE
Error print Mapstore 2019.02.00

### ISSUE THREAD

**Issue by dpadron** [geosolutions-it/MapStore2#4164]
### Description

Installation using docker
Mapstore 2019.02.00
At the time of printing the following error is generated:

Error on printing: Error while generating PDF: java.lang.NullPointerException at sun.awt.X11FontManager.getDefaultPlatformFont(X11FontManager.java:779) at sun.font.SunFontManager$2.run(SunFontManager.java:433) at java.security.AccessController.doPrivileged(Native Method) at sun.font.SunFontManager.<init>(SunFontManager.java:376) at sun.awt.X11FontManager.<init>(X11FontManager.java:32) at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.lang.reflect.Constructor.newInstance(Constructor.java:526) at java.lang.Class.newInstance(Class.java:383) at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83) at java.security.AccessController.doPrivileged(Native Method) at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74) at java.awt.Font.getFont2D(Font.java:490) at java.awt.Font.getFontName(Font.java:1278) at java.awt.Font.getFontName(Font.java:1260) at com.lowagie.text.pdf.PdfGraphics2D.getCachedBaseFont(Unknown Source) at com.lowagie.text.pdf.PdfGraphics2D.setFont(Unknown Source) at com.lowagie.text.pdf.PdfGraphics2D.<init>(Unknown Source) at com.lowagie.text.pdf.PdfContentByte.createGraphics(Unknown Source) at org.mapfish.print.config.layout.ImageBlock$SvgDrawer.renderImpl(ImageBlock.java:191) at org.mapfish.print.ChunkDrawer.render(ChunkDrawer.java:55) at org.mapfish.print.ChunkDrawer.tableLayout(ChunkDrawer.java:49) at com.lowagie.text.pdf.PdfPTable.writeSelectedRows(Unknown Source) at com.lowagie.text.pdf.PdfPTable.writeSelectedRows(Unknown Source) at com.lowagie.text.pdf.ColumnText.goComposite(Unknown Source) at com.lowagie.text.pdf.ColumnText.go(Unknown Source) at com.lowagie.text.pdf.ColumnText.go(Unknown Source) at com.lowagie.text.pdf.PdfPRow.writeCells(Unknown Source) at com.lowagie.text.pdf.PdfPTable.writeSelectedRows(Unknown Source) at com.lowagie.text.pdf.PdfPTable.writeSelectedRows(Unknown Source) at com.lowagie.text.pdf.ColumnText.goComposite(Unknown Source) at com.lowagie.text.pdf.ColumnText.go(Unknown Source) at com.lowagie.text.pdf.ColumnText.go(Unknown Source) at com.lowagie.text.pdf.PdfPRow.writeCells(Unknown Source) at com.lowagie.text.pdf.PdfPTable.writeSelectedRows(Unknown Source) at com.lowagie.text.pdf.PdfPTable.writeSelectedRows(Unknown Source) at com.lowagie.text.pdf.PdfPTable.writeSelectedRows(Unknown Source) at org.mapfish.print.config.layout.ColumnsBlock$1.render(ColumnsBlock.java:67) at org.mapfish.print.PDFCustomBlocks.addAbsoluteDrawer(PDFCustomBlocks.java:183) at org.mapfish.print.config.layout.ColumnsBlock.render(ColumnsBlock.java:56) at org.mapfish.print.config.layout.Page.render(Page.java:80) at org.mapfish.print.config.layout.Layout.render(Layout.java:67) at org.mapfish.print.output.AbstractOutputFormat.doPrint(AbstractOutputFormat.java:30) at org.mapfish.print.output.PdfOutputFactory.print(PdfOutputFactory.java:62) at org.mapfish.print.MapPrinter.print(MapPrinter.java:184) at org.mapfish.print.servlet.MapPrinterServlet.doCreatePDFFile(MapPrinterServlet.java:409) at org.mapfish.print.servlet.MapPrinterServlet.createPDF(MapPrinterServlet.java:190) at org.mapfish.print.servlet.MapPrinterServlet.doPost(MapPrinterServlet.java:107) at javax.servlet.http.HttpServlet.service(HttpServlet.java:650) at javax.servlet.http.HttpServlet.service(HttpServlet.java:731) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104) at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445) at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1137) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637) at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2574) at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2563) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:748) 

![image](https://user-images.githubusercontent.com/7094961/64477056-39b5e680-d197-11e9-8362-f2df6449ad69.png)

**Comment by tdipisa** [comment]
@dpadron I'm going to close this issue now since we have not identified issues in latest releases. Let me know if you are still experiencing issues with this in latest versions o MapStore, if yes please include more details on what you are trying to print.

**Comment by gobinathp** [comment]
@tdipisa still I'm facing same issues.

**Comment by tdipisa** [comment]
@gobinathp it seems that the calculated path [here](https://github.com/geosolutions-it/MapStore2/blob/master/resources/geoserver/print/config.yaml#L65) is not properly reconized or valid, from your log:

/C:/Program Files/Apache Software Foundation/Tomcat 8.5/webapps/mapstore/printing/print_header.png

Can you please try by avoiding paths with spaces?
