### ISSUE TITLE
'Remove all annotations geometry' doesn't work properly without setting initial state

### ISSUE THREAD

**Issue by francoperversi** [geosolutions-it/MapStore2#4182]
### Description
Without setting the initial state:

         "annotations": {
          "config": {
            "multiGeometry": true,
            "validationErrors": {}
          },
          "format": "decimal",
          "defaultTextAnnotation": "New"
        },

When I create a new annotation geometry and I save it, the buttom 'Remove all annotations geometry' doesn't remove the annotation immediatly. The annotation is only removed after clicking on 'back' and 'confirm'

![Anno](https://user-images.githubusercontent.com/54808782/64701206-9c192a80-d4a8-11e9-8d61-7cda750a9b56.gif)

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- localConfig.json should contain "Annotations" plugin, with no annotations initialState set.
- Open Mapstore
- Open a random map
- Open Burger Menu
- Click on 'Annotations'
- Click on 'New'
- Click on 'Add New Geometry'
- Click on 'Marker'
- Click on the map
- Click on 'Save'
- Click on 'Remove all annotations geometry'
- Click on ' Confirm'

*Expected Result*

- The geometry shouldn't be displayed

*Current Result*

- The geometry is still displayed

### Other useful information (optional):
See #3852

**Comment by kasongoyo** [comment]
@francoperversi  & @tdipisa. It seems to work as expected on my side. see

![MapStore HomePage ](https://user-images.githubusercontent.com/1956062/64848354-ac9ce280-d619-11e9-8231-b8cbac9a3e4d.gif)

**Comment by MV88** [comment]
@kasongoyo have you removed the initial state of annotation in localConfig.json?

to me it seems not, notice how the pencil (with plus) does not disables.

please check if it is related to the mutliGeometry set to false (or not being set, i.e. defaults which is falsy).

**Comment by kasongoyo** [comment]
> @kasongoyo have you removed the initial state of annotation in localConfig.json?
> 
> to me it seems not, notice how the pencil (with plus) does not disables.
> 
> please check if it is related to the mutliGeometry set to false (or not being set, i.e. defaults which is falsy).

@MV88 You're right. I forgot to remove the initial state. Now I can replicate, thanks
