### ISSUE TITLE
Widgets on protected data are not correctly reloaded

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#4203]
### Description
If a map contains a protected layer, widgets related to this layer are not correctly reloaded when an user with required rights (as ADMIN) login into MapStore.

![states_permissions](https://user-images.githubusercontent.com/1280027/64967261-7ae97d00-d8a0-11e9-8f5d-40fc7079e770.gif)

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Steps to reproduce*

- Open [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/10828) map as anonymus user 
- Login as admin

*Expected Result*

- Widgets are updated according to the user rights

*Current Result*

- Widgets are updated only after a pan in the map

### Other useful information (optional):
To fix this probably the user integration with GeoServer needs to be set

**Comment by vlt1** [comment]
I imported the map in the issue into my local installation and it doesn't load the layers. When I log in as admin/admin requests to geoserver fail with 500 Internal Error, and the response is an Exception Report with a message: "User not found in usergroupservice: geostore".

**Comment by offtherailz** [comment]
using npm start by default you're connected to dev.geo-solutions.it. 
You can use this map to replicate the issue.
http://localhost:8081/#/viewer/openlayers/10828

I created a user for you to solve this issue. @tdipisa will give you the credentials
