### ISSUE TITLE
CRS Selector and custom projection, problem when switching back and forth

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#4230]
### Description
The problem is when you switch from the custom projection to 3857 and you go back to the custom projection.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- non browser related

*Steps to reproduce*

This can be reproduced locally by changing the following configurations or with a map where the default crs is a custom one. (but it needs to be supported, i.e. bveing added to localConfig projectionDefs)

In order to reproduce the issue locally you have to:
- add a custom projection in the localConfigJSON
```
"projectionDefs": [{
        "code": "EPSG:31468",
        "def": "+proj=tmerc +lat_0=0 +lon_0=12 +k=1 +x_0=4500000 +y_0=0 +ellps=bessel +towgs84=598.1,73.7,418.2,0.202,0.045,-2.455,6.7 +units=m +no_defs",
        "extent": [
          4036308.74,
          5255076.75,
          4617579.38,
          6108355.90
        ],
        "worldExtent": [
          5.87,
          47.27,
          13.84,
          55.09
        ],
        "axisOrientation": "neu"
      }
    ],

"mapConstraints": {
      "minZoom": 3,
      "crs": "EPSG:31468",
      "restrictedExtent": [
        4036308.74,
        5255076.75,
        4617579.38,
        6108355.90
      ]
    },

             {
              "name": "CRSSelector",
              "cfg": {
                "additionalCRS": {
                  "EPSG:31468": {"label": "EPSG:31468" }
                },
                "filterAllowedCRS": [
                  "EPSG:31468",
                  "EPSG:4326",
                  "EPSG:3857"
                ],
                "allowedRoles": [
                  "ADMIN"
                ]
              }
            }
```
- change the configuration of new.json like this:
```
{
  "map": {
    "projection": "EPSG:31468",
    "units": "m",
    "center": {
      "x": 4467720.00,
      "y": 5333820.00,
      "crs": "EPSG:31468"
    },
    "zoom": 1,
    "maxExtent": [
      4386596.4101,
      5172656.9694,
      4673316.4101,
      6104496.9694
    ],
    "layers": [
      {
        "type": "wms",
        "url": "https://demo.geo-solutions.it/geoserver/wms",
        "visibility": true,
        "opacity": 1.0,
        "singleTile": true,
        "title": "Grey Earth",
        "name": "GRAY_HR_SR_OB_DR",
        "group": "Meteo",
        "format": "image/png",
        "bbox": {
          "bounds": {
            "minx": -25.6640625,
            "miny": 26.194876675795218,
            "maxx": 48.1640625,
            "maxy": 56.80087831233043
          },
          "crs": "EPSG:4326"
        }
      },
      {
        "source": "ol",
        "group": "background",
        "title": "Empty Background",
        "fixed": true,
        "type": "empty",
        "visibility": true,
        "args": [
          "Empty Background",
          {
            "visibility": false
          }
        ]
      }
    ]
  }
}
```

- then you have to load the new map
- check the crs present in crs selector is EPSG:31468
- change to EPSG:3857
- change to EPSG:31468

- reload map
- try now switching to EPSG:4326 and then again back to EPSG:31468

*Expected Result*

- everything continues to work normally

*Current Result*

- A notification error appear in the map
[see source code](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/plugins/CRSSelector.jsx#L78)

**Comment by AGMETEOR** [comment]
@MV88 followed these steps and I didn't see an error notification. Can you still see this locally on your side?

**Comment by MV88** [comment]
it's an old issue, i do not remember honestly. i have to test it again, but maybe in the meanwhile this problem has already been resolved

**Comment by AGMETEOR** [comment]
> it's an old issue, i do not remember honestly. i have to test it again, but maybe in the meanwhile this problem has already been resolved

@MV88 will you have some time to test on your side?

**Comment by tdipisa** [comment]
@MV88 can you please check it again?

**Comment by MV88** [comment]
this is not happening anymore, closing it
