### ISSUE TITLE
Add icons for GeoStory

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#4270]
### Description
List and add the icons needed to the MapStore icon font . 

List icons to add below:
- [x] GeoStory
- [x] Title Section
- [x] Paragraph Section
- [x] Media Section
- [x] Immersive Section
- [x] Immersive Content
- [x] Fit Cover
- [x] Fit Contain
- [x] Small Size
- [x] Medium Size
- [x] Large Size
- [x] Full Size
- [x] View Height
- [x] Auto Height

**Comment by MV88** [comment]
see https://github.com/geosolutions-it/MapStore2-C039/issues/85
