### ISSUE TITLE
Annotations Circle has problem with radius

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#4274]
### Description
Especially when changing the center only via click on map and via changing radius in the form

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Not browser related

*Steps to reproduce*

Common steps:
- Create a new circle annotation
- While being in edit mode of the circle (coordinate editor in the right panel)

<hr>

#### change center problem
- Click on another point on the map

<hr>

#### radius edit problem
- Change the radius (note the unit of measure)
<hr>

*Expected Result*

#### change center problem
Circle in map does not change, it just moves its center to the clicked point

#### radius edit problem
Radius changes should take into account UoM
Especially if meters and I change from 300000 to 300001 it should not "explode"

*Current Result*

#### change center problem
Circle resizes to a small point in map (wrong uom probably)

#### radius edit problem
The size of the circle is clearly wrong

### Other useful information (optional):
All tests were done in with default CRS i.e. EPSG:3857

**Comment by francoperversi** [comment]
@kasongoyo the exploding circle is still present in 2 situations:

- Changing radius
- Changing center lat/long
