### ISSUE TITLE
Logout in map session does not stop loading

### ISSUE THREAD

**Issue by francoperversi** [geosolutions-it/MapStore2#4279]
### Description
When you open/create a map and you logout, the map doesn't stop loading, with no errors reported in the console

![Logout](https://user-images.githubusercontent.com/54808782/66053316-61983000-e532-11e9-8572-3bb6425567be.gif)

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [X] Internet Explorer
- [X] Chrome
- [X] Firefox
- [X] Safari

*Browser Version Affected*

- Not browser related

*Steps to reproduce*

- Open Mapstore
- Login
- Open/Create a map
- Logout

*Expected Result*

- A modal window opens asking to login

*Current Result*

- Doesn't stop loading a Map

### Other useful information (optional):
This problem is not present in dashboards

**Comment by kasongoyo** [comment]
The issue seems to exist no more. I cannot reproduce. @tdipisa

**Comment by tdipisa** [comment]
@kasongoyo ok thank you, in these cases the issue needs to be moved in test column and testers must be informed for a double check.
