### ISSUE TITLE
Clicking "New Group" button on Manage Accounts nothing happens

### ISSUE THREAD

**Issue by francoperversi** [geosolutions-it/MapStore2#4282]
### Description
See title

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [X] Chrome
- [X] Firefox
- [X] Safari

*Browser Version Affected*

- Not browser related

*Steps to reproduce*

- Open Mapstore
- Login as admin
- Open the account manager
- Go to manage group section
- Click on New Group

*Expected Result*

- The New Group modal window opens

*Current Result*

- Nothing happens

**Comment by tdipisa** [comment]
Fixed by #4375
