### ISSUE TITLE
Search result on map fill color is wrong on mobile

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#4296]
### Description
![image](https://user-images.githubusercontent.com/1279510/66196699-472c9680-e699-11e9-9850-1fad260d0b7d.png)

### In case of Bug (otherwise remove this paragraph)

*Steps to reproduce*

- open a map in mobile browser (android chrome) or chrome with mobile tool active in dev tools
- search for "pisa" 
- select the first result

*Expected Result*

- Like QA or desktop, the result should look like this
![image](https://user-images.githubusercontent.com/1279510/66197026-d5088180-e699-11e9-936d-a8c04d547c7b.png)

*Current Result*

- The polygon fill is not transparent

** Useful information**
This issue affects only the current master branch, 2019.02.02 is not affected

**Comment by tdipisa** [comment]
No longer an issue, fixed in latest releases
