### ISSUE TITLE
Investigated on bundle sizes( too high) and memory usage during build

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#4297]
We should investigate and propose solutions to:
 - [ ] reduce bundle size
 - [ ] reduce memory usage during prod build

**Comment by MV88** [comment]
what about [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin)?
maybe something can be found [here](https://dev.to/sheddy_nathan/possible-ways-to-reduce-your-webpack-bundle-size-js-secrets-550)

**Comment by MV88** [comment]
@offtherailz you were talking about https://www.npmjs.com/package/babel-plugin-lodash

but maybe we can generalize it with https://www.npmjs.com/package/babel-plugin-import

**Comment by mbarto** [comment]
I would First do an ordered list of libraries by size. Then evaluate effort to remove for the Firsts in list. I would start removing the ones on top with the less effort to remove.
Repeat

**Comment by MV88** [comment]
Here reporting the ones >1% of size

```
npm run analyze

> mapstore2@0.1.0 analyze C:\Work\Projects\MapStore2
> npm run clean && mkdirp ./web/client/dist && webpack --json --config build/prod-webpack.config.js | webpack-bundle-size-analyzer


> mapstore2@0.1.0 clean C:\Work\Projects\MapStore2
> rimraf ./web/client/dist

(node:24844) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(node:24844) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
ogc-schemas: 4.21 MB (11.0%)
pdfjs-dist: 2.25 MB (5.92%)
ol: 2.13 MB (5.59%)
ag-grid-community: 1.87 MB (4.92%)       
babel-standalone: 1.68 MB (4.42%)        
lodash: 825.93 KB (2.12%)
react-data-grid-addons: 781.68 KB (2.00%)
recharts: 748.1 KB (1.92%)
  core-js: 13.2 KB (1.76%)
  prop-types: 3.04 KB (0.406%)
  <self>: 731.86 KB (97.8%)
rxjs: 643.01 KB (1.65%)
draft-js: 617.43 KB (1.58%)
  immutable: 139.19 KB (22.5%)
  fbjs: 80.12 KB (13.0%)
  <self>: 398.12 KB (64.5%)
moment: 501.5 KB (1.29%)
codemirror: 497.75 KB (1.28%)
@turf: 458.65 KB (1.18%)
jsts: 436.61 KB (1.12%)
quill: 427.05 KB (1.10%)
intl: 412.44 KB (1.06%)
```

**Comment by Gmarquis45** [comment]
It is really problematic .. We try to use it and deploy with CICD on gitlab but we need to add 
`export NODE_OPTIONS=--max_old_space_size=4096`
It take 38min to npm run compile...

Have you find a solution?

Thanks in advance

**Comment by offtherailz** [comment]
#6622 and #6621 should reduce from 12Mib to around 9Mib the main bundle size. We can then procede optimizing:
- [ ] lodash : using `transform-imports` plugin for babel.config and converting the remaining global requires. (500kb not uglified)
- [ ] recharts can be removed o loaded dynamically (500kb not uglified) ( used only for elevation chart in layer properties)
- [ ]` react-data-grid ` and r`eact-data-grid-addons` can be loaded together dynamically when open grids.
- [ ] `pdf.js` can be loaded dynamically.
- [ ] quill can be removed and replaced with ìdraft-js` (429 kb not ugified)
- [ ] `react-wysiwyg` and `draft-js` can be loaded dynamically when an editor is loaded at the first time. (300kb+600kb not ugified)
![image](https://user-images.githubusercontent.com/1279510/110513363-6dfcc100-8106-11eb-8dd1-c38129e8401f.png)

TODO: see the effective uglified sizes in production.

**Comment by offtherailz** [comment]
I changed the milestone, all the optimization are on the 2021.02.00 now.

**Comment by offtherailz** [comment]
As a final report of the current operation we can compare stable with master
![image](https://user-images.githubusercontent.com/1279510/113402044-b1182000-93a4-11eb-8622-cbf1b3820717.png)
The improvements is not so significant in terms of performance. **Anyway these improvements solved a lot of issues due to build size. Now `export NODE_OPTIONS=--max_old_space_size=4096` can be removed without having any issue**

the bundle size (main bundle) decreased of 23%, 15% gizipped. (~3MB to ~2.5MB transferred), that is not enough for a visible improvement in terms of page load 

The analysis from lighthouse will port to create a second issue #6735
