### ISSUE TITLE
Burger Menu - Settings modal window text and dropdown problems

### ISSUE THREAD

**Issue by francoperversi** [geosolutions-it/MapStore2#4304]
### Description
On settings modal window from Buger menu, the version text isn't correct and when you open 'Identify response format' dropdown menu the 'template' option (witch is not possible to select) appears

![settings](https://user-images.githubusercontent.com/54808782/66224110-621cfc00-e6d5-11e9-89e4-336f0de3744b.gif)

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [X] Chrome
- [X] Firefox
- [X] Safari

*Browser Version Affected*

- Not browser related

*Steps to reproduce*

- Open Mapstore
- Open a Map
- Open burger menu
- Click on settings

*Expected Result*

- The version text should be properly displayed
- Dropdownmenu shouldn't have unselectable elements

*Current Result*

- The version text is not properly displayed
- Dropdownmenu has unselectable elements (template)

**Comment by francoperversi** [comment]
The text after "Version" in Burger menu settings modal window is still wrong

![version](https://user-images.githubusercontent.com/54808782/67378618-d1289a80-f587-11e9-8199-561f87e397a8.jpg)

@kasongoyo please can you fix it?

**Comment by kasongoyo** [comment]
@francoperversi The version value is coming from build process. So we should fix the version during build time before deploying it. 

<img width="520" alt="Screenshot 2019-10-23 at 13 37 28" src="https://user-images.githubusercontent.com/1956062/67384820-8bc19880-f59a-11e9-8a24-e5b091c4a3ef.png">

Rebuild can fix the incorrect version you're seeing.

**Comment by tdipisa** [comment]
@francoperversi should be fixed now, please retest.
