### ISSUE TITLE
Add SRID to cql spatial filter geometry definition

### ISSUE THREAD

**Issue by kappu72** [geosolutions-it/MapStore2#4306]
### Description
As the time of writing MS take care about the reprojection of a spatial filters GeometryLiteral when the layer's nativeCrs and the crs of the filter are different.
Adding the SRSID to the spatial filter GeometryLiteral definition, will delegate this to the geoserver.
Remember to remove also all the part of the code that try to retrive the layer's nativeSrs.

**Comment by offtherailz** [comment]
Remember also to update with this feature the CQL_FILTER parser [here](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/ogc/Filter/CQL/parser.js)

**Comment by kappu72** [comment]
> Remember also to update with this feature the CQL_FILTER parser [here](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/ogc/Filter/CQL/parser.js)

The parser doesn't work with WKT geometry, consider this when this functionality will be added.

**Comment by offtherailz** [comment]
Yes, I see. Didn't remember, so you can move on.
