### ISSUE TITLE
Linear layers editing - adding a geometry to an existing feature, saving problems

### ISSUE THREAD

**Issue by francoperversi** [geosolutions-it/MapStore2#4315]
### Description
In linear layers editing, an error occurs trying to save after adding a new geometry to an existing feature

![liena](https://user-images.githubusercontent.com/54808782/66387119-9806fc80-e9c3-11e9-9f64-00f91f655dab.gif)

The error reported by mapstore is the following:
```
An error occured with saving operation
java.lang.RuntimeException: Parsing failed for posList: java.lang.RuntimeException: Parsing failed for null: java.lang.NumberFormatException: empty String Parsing failed for posList: java.lang.RuntimeException: Parsing failed for null: java.lang.NumberFormatException: empty String Parsing failed for null: java.lang.NumberFormatException: empty String empty String
```

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [X] Chrome
- [X] Firefox
- [X] Safari

*Browser Version Affected*

- Not browser related

*Steps to reproduce*

- Open [this](https://dev.mapstore.geo-solutions.it/mapstore/#/viewer/openlayers/11099) map
- Open TOC
- Select 'roads' layer (linear)
- Open attribute table
- Click on 'edit mode'
- Select a feature
- 'Add a shape to the existing geometry'
- Draw the geometry and finish it with a double click
- Click on 'save changes'

*Expected Result*

- The changes are saved and the new geometry is added to the feature

*Current Result*

- Saving changes is impossible because an error occurs

**Comment by MV88** [comment]
i removed label react because the regession is caused by ol5 migration
