### ISSUE TITLE
Measure to annotation - title text and saving problems

### ISSUE THREAD

**Issue by francoperversi** [geosolutions-it/MapStore2#4322]
### Description
Adding a measure as annotation, on title text box there's the default written 'New annotation' that does not disappear after a click on it (creating a new annotation the behaviour is different).
Furthermore, if you close the new annotation window without save it, the annotation is anyway saved

![annot](https://user-images.githubusercontent.com/54808782/66461944-5b4a0c80-ea7a-11e9-9509-5547dd6cd89a.gif)

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [X] Chrome
- [X] Firefox
- [X] Safari

*Browser Version Affected*

- Not browser related

*Steps to reproduce*

- Open mapstore
- Open a random map
- Click on burger menu
- Click on measure
- Draw a geometry
- Click on 'Add as annotation'
(1)
- Close without save (with 'X' or with 'back', is the same)
(2)

*Expected Result*

(1) The title text box is empty (like when you open annotations panel directly from burger menu)
(2) When you close without save the annotation shouldn't be saved

*Current Result*

(1) The title text box contains the 'New annotation' written (that doesn't desappear after a click on it)
(2) When you close without save the annotation is anyway saved

**Comment by tdipisa** [comment]
Also the symbology in the annotation card is wrong, it should be the following:
![annotation_symb](https://user-images.githubusercontent.com/1280027/66555073-5bb3d780-eb4e-11e9-91bc-d30f823bea29.jpg)

**Comment by MV88** [comment]
> Furthermore, if you close the new annotation window without save it, the annotation is anyway saved

this was by design, when annotation is created from measure then it is saved by default and it enters in edit mode if it
