### ISSUE TITLE
Problems in switch/exit fullscreen (browser related)

### ISSUE THREAD

**Issue by francoperversi** [geosolutions-it/MapStore2#4324]
### Description
1) Switching fullscreen from sidebar, if you exit fullscreen with F11, ESC or the browser esc window, the button on sidebar doesn't update and it remains green.

![full1](https://user-images.githubusercontent.com/54808782/66463791-14f6ac80-ea7e-11e9-9286-06783a6e55ba.gif)

2) Switching fullscreen with F11 the sidebar button doesn't update, and clicking on it, it doesn't exit fullscreen.

![full2](https://user-images.githubusercontent.com/54808782/66464632-a581bc80-ea7f-11e9-9d30-fe529998fbe0.gif)

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [X] Internet Explorer
- [X] Chrome
- [x] Firefox
- [X] Safari

*Browser Version Affected*

- It's browser related:

In Chrome, both (1) and (2) problems are detected
In Firefox, only the (2) problem is detected
In Internet Explorer, only the (2) problem is detected
In Safari, the fullscreen button is not present

*Steps to reproduce*

1)
- Open Mapstore
- Open a random map
- Click on 'Switch to fullscreen' from sidebar
- Try to exit fullscreen with F11, ESC or browser esc window

2)
- Open Mapstore
- Open a random map
- Switch to fullscreen with F11
- Try to exit fullscreen with the sidebar button

*Expected Result*

1) The button on sidebar is update and it becomes blue again
2) The sidebar button is updated and becomes green as soon as you click on F11. If you click on it again, it exit fullscreen and returns blue

*Current Result*

1) The button on sidebar doens't update and it remais green
2) Clicking on F11 the sidebar button doesn't update and remains blue. If you click on it several times it changes colour but doesn't exit fullscreen

**Comment by vlt1** [comment]
Concerning F11 fullscreen, it seems that it is not part of Fullscreen API and thus there is no supported way of detecting that browser is in fullscreen or going back from fullscreen in this case. Fullscreen button in Safari is hidden on purpose with a stated reason that Fullscreen API in Safari is not fully supported. Looks like [not much has changed](https://caniuse.com/#feat=fullscreen) on that front, so it probably should stay disabled.(the button was disabled in [this pull request](https://github.com/geosolutions-it/MapStore2/pull/2166)).

**Comment by tdipisa** [comment]
@ElenaGallo @francoperversi I moved this in test. I think that if the problem affect only Safary and on FF and Chrome this functionality is properly working, this issue can be closed (ho safary the full screen button should be disabled now for the reason mentioned by @vlt1 in the above comment).
