### ISSUE TITLE
Resize cursor for right side panels

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#4332]
### Description
The component currently used for the options panels (Catalog, Annotations etc.) and also Identify present a resize cursor but these panels are not resizable at the moment. This happens due to a **cursor: col-resize;** that should be removed.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Steps to reproduce*

- Open a map
- Open a right side panel

*Expected Result*

- The resize cursor is not displayed

*Current Result*

- The resize cursor is displayed

### Other useful information (optional):
As future improvement we will need to change the base component currently used for right side panels (this may be part of #4254)

**Comment by francoperversi** [comment]
@kasongoyo the resize cursor is still present in GetInfo panel

**Comment by francoperversi** [comment]
@kasongoyo the problem is still present also in 'About this map' button from Burger Menu (present if a map has details)
