### ISSUE TITLE
Filtering error with demo service layer

### ISSUE THREAD

**Issue by francoperversi** [geosolutions-it/MapStore2#4346]
### Description
An error occurs when the spatial filter is applied in layers with demo service. This issue is probably related to #4306 

![filtercs](https://user-images.githubusercontent.com/54808782/66740376-510d8100-ee73-11e9-931b-4825709b9f2f.gif)

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [X] Chrome
- [X] Firefox
- [X] Safari

*Browser Version Affected*

- Not browser related

*Steps to reproduce*

- Open mapstore
- Open a trial map with demo service in catalog
- Add a vector layer
- Open TOC
- Select the vector layer
- Click on Filter layer
- Draw a geometric filter
- Click on apply

*Expected Result*

- The filter should be properly applied without errors

*Current Result*

- The filter is not applied because an error occurs

### Other useful information (optional):
This error occurs only for layers with demo service

**Comment by tdipisa** [comment]
Recently we have introduced the support to introduce the map SRID in spatial CQL filter for GetMap requests. 

https://demo.geo-solutions.it/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png8&TRANSPARENT=true&LAYERS=topp:states&SRS=EPSG:3857&CRS=EPSG:3857&TILED=true&layers=topp:states&CQL_FILTER=(INTERSECTS(the_geom**,SRID=3857;**Polygon((-11447209.355987996 5070526.708325452, -11447209.355987996 3881778.044434391, -10018754.171394624 3881778.044434391, -10018754.171394624 5070526.708325452, -11447209.355987996 5070526.708325452))))&WIDTH=256&HEIGHT=256&BBOX=-12523442.714243278,4383204.9499851465,-12210356.646387195,4696291.017841228

The SRID in CQL filters is supported only from GeoServer v2.13.x. Thsi issue does not affect newer version like our gs-stable instance. This issue can be closed.
