### ISSUE TITLE
The space under Geosolutions footer isn't uniform

### ISSUE THREAD

**Issue by francoxyz** [geosolutions-it/MapStore2#4347]
### Description
Looking at the bottom of the web page, the space under 'Geosolutions' footer has the following differences:

### - Mapstore homepage 
   **Big space** under Geosolutions footer
### - Account Manager - Manage Users and Manage Groups
   **No space** under Geosolutions footer when the page has 3 lines of users/groups cards
   **Little space** under Geosolutions footer when the page has 1 or 2 lines of users/groups cards

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [X] Chrome
- [X] Firefox
- [X] Safari

*Browser Version Affected*

- In Safari, when the account manager page has 1 or 2 lines of users/groups cards, there's **No space** under footer (tested with the browser simulator BrowserSatck)

*Steps to reproduce*

- Open Mapstore
- Verify the space under footer
- Click on account manager (groups and users)
- Verify the space under footer

**Comment by tdipisa** [comment]
Close for inactivity.
