### ISSUE TITLE
Dashboards - Adding new widgets position problems

### ISSUE THREAD

**Issue by francoxyz** [geosolutions-it/MapStore2#4354]
### Description
Adding a new widget in a Dashboard with already existing widgets, the new widget is placed in a standard position, changing the position of the already existing widgets

![addwidg](https://user-images.githubusercontent.com/54808782/66754087-7ca16300-ee95-11e9-8a7f-2d2890ac5997.gif)

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [X] Chrome
- [X] Firefox
- [X] Safari

*Browser Version Affected*

- Not browser related

*Steps to reproduce*

- Open Mapstore
- Login as admin
- Open a dashboard with various widgets like [this one](https://dev.mapstore.geo-solutions.it/mapstore/#/dashboard/11092)
- Add a random widget to the dashboard

*Expected Result*

- The new widget is located in a free space, and the already existing widgets prosition won't change

*Current Result*

- The new widget is located in a standard position, and if there are already existing widgets in that position, the will be moved

**Comment by offtherailz** [comment]
I report here my comment on PR #4576 about suggested solution and considerations about real need about fixing this bug:
Please have a look 

> To have a real solution we need to calculate the first hole available (1x1) with the minimal x.
> 
> So a solution is to browse the current layout to find out the first 1x1 hole for x=0, then continue for x = 1 and so on...
> 
> @francoperversi @tdipisa 
> IMHO this is not a bug, but at least a not optimized approch to add widgets to the dashboard. 
> Please evaluate the effort of this "fix" proportionally to the real advantage. 
> Anyway this doesn't seems to have a big priority as labeled, therefore can even postponed by milestone.

**Comment by offtherailz** [comment]
I suggest to postpone this fix to the next release. @tdipisa is it ok?

**Comment by tdipisa** [comment]
Closed for inactivity.
