### ISSUE TITLE
Import a map from QA does not work in some cases

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#4355]
### Description
see title

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- open [this](https://qa.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/4093) map in QA
- export it
- open the same map in dev
- import the exported map

*Expected Result*

- layers to be overridden from the imported config (in this case is the same layers list)

*Current Result*

- Error
![image](https://user-images.githubusercontent.com/11991428/66754764-fbe36680-ee96-11e9-98ea-9a91ae03afd4.png)

### Other useful information (optional):
it works exporting and importing on the same map in qa.
it works exporting in qa and importing in a new map in dev

**Comment by tdipisa** [comment]
@MV88 this works for me, @ElenaGallo @francoperversi, please retest.

**Comment by MV88** [comment]
> @MV88 this works for me, @ElenaGallo @francoperversi, please retest.

works both from qa to qa and from qa to dev ?

probably buy fixing the map configuration that had some problems this issue has been fixed

**Comment by francoperversi** [comment]
I confirm that the problem is not present anymore, both importing from dev to qa and from qa to dev
