### ISSUE TITLE
Improve TOC style to make d&d and sub-groups more clear

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#4377]
### Description
Now that sub groups can be created in a easy way and drag&drops works between groups, a better design for TOC is needed.

This is the current situation: 
![Peek 18-10-2019 11-27](https://user-images.githubusercontent.com/1279510/67082888-5aac2700-f19a-11e9-9ddf-84193293bf56.gif)

Here my draft solution (10 mins test, so it should be improved and tested):

Adding borders on the left and some more margins and paddings here and there : 

![Peek 18-10-2019 11-15](https://user-images.githubusercontent.com/1279510/67082461-7cf17500-f199-11e9-98cb-c402f239e2bc.gif)

```diff
diff --git a/web/client/themes/default/less/toc.less b/web/client/themes/default/less/toc.less
index f068f2cb4..09a69f41e 100644
--- a/web/client/themes/default/less/toc.less
+++ b/web/client/themes/default/less/toc.less
@@ -123,6 +123,10 @@
     &.toc-default-group {
         padding-bottom: 10px;
     }
+    border-left: thin solid lightgrey;
+    margin-bottom: 5px;
+    padding-bottom: 10px;
+
 }
 
 .layer-collapsed {
@@ -247,7 +251,7 @@
         float: right;
         margin-right: 10px;
     }
-    
+
     .toc-filter-icon.disabled {
         opacity: 0.5;
     }
@@ -280,8 +284,9 @@
     }
 
     .toc-group-children {
-        margin-left: 8px;
-        margin-right: 8px;
+        margin-left: 10px;
+        margin-right: 6px;
+        margin-bottom: 2px;
     }
 
     &.visibility {
@@ -804,4 +809,4 @@
 
 #mapstore-add-toc-group {
     padding: 15px;
-}
\ No newline at end of file
+}

```

**Comment by tdipisa** [comment]
We are reviewing the entire MS's layout (closed in favor of #4254).
