### ISSUE TITLE
Mobile - GetInfo areonautical coordinates display problem 

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#4382]
### Description
The areonautical coordinate is not aligned to the page. 

![issue1](https://user-images.githubusercontent.com/56537133/67196179-96ddc280-f3fa-11e9-8a48-e09a0e985977.gif)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [ ] Firefox
- [x] Safari

*Browser Version Affected*

- Not browser related

*Steps to reproduce*

- Open a map
- Click on the map for the point information
- Show coordinate Editor
- Setting on AREONAUTICAL

*Expected Result*

- The areonautical coordinate is aligned to the page. 

*Current Result*

- The areonautical coordinate is not aligned to the page.

**Comment by ElenaGallo** [comment]
@MV88 In same case (galaxy S7) the setting button is not propertly display.
![ff](https://user-images.githubusercontent.com/56537133/70811407-d7880580-1dc5-11ea-8113-d6749d150803.JPG)

**Comment by ElenaGallo** [comment]
@MV88 in some cases (galaxy s7) the setting button is not properly displayed
![ff](https://user-images.githubusercontent.com/56537133/70811500-fbe3e200-1dc5-11ea-88df-0e0a178a67fc.JPG)

**Comment by ElenaGallo** [comment]
@MV88 in some cases (galaxy s7) the setting button is not properly displayed
![ff](https://user-images.githubusercontent.com/56537133/70811659-567d3e00-1dc6-11ea-8fc2-1608c8cbf933.JPG)

**Comment by tdipisa** [comment]
@ElenaGallo please open a new issue for [this](https://github.com/geosolutions-it/MapStore2/issues/4382#issuecomment-565485276) in 2020.01.01
