### ISSUE TITLE
Mobile - Dashboard display problem

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#4385]
### Description
On dashboard display click and drag to the left of the screen and a blank page appears

![issue3](https://user-images.githubusercontent.com/56537133/67266225-fb0e8e00-f4af-11e9-88a2-45c4334cadba.gif)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Browser Version Affected*

Chrome and Firefox

*Steps to reproduce*

- Click on a Dashboard 
- Click and drag to the left of the screen

*Expected Result*

The blank page dosen't appear or you can return to the home page

*Current Result*

Click and drag to the left of the screen and a blank page appears

### Other useful information (optional):

On safari when you click and drag to the left of the screen 
return to the home page

**Comment by AGMETEOR** [comment]
The QueryPanel plugin is run in a Sidebar component created from this library [react-sidebar](https://www.npmjs.com/package/react-sidebar/v/2.3.2). This library provides for the ability to touch and drag open the Sidebar on mobile devices by setting the `touch:boolean` and `onSetOpen:func` props on react-sidebar's Sidebar component.

By default `touch:boolean` is `true`. 

## Solution 1
To stop this issue from happening we can disable `touch` on the Sidebar by setting `touch:boolean` to `false`.
### *Cons*
This means anywhere that QueryPanel (e.g. viewer) is used there has to a dedicated button that can be clicked to open the sidebar

## Solution 2
The QueryPanel doesn't have any filters while in the Dashboard. We can detect the path and check that we're on the dashboard currently and then disable touch on the Sidebar.

**Comment by offtherailz** [comment]
If the query panel has that behaviour, well, opening it only by dragging is not allowed at all. It is tipical of side menus, this interaction doesn't make sense for query panel., so you can disable that touch behaviour.
