### ISSUE TITLE
Mobile - No button 'QUERY OBJECT ON MAP' in the Side Bar

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#4386]
### Description
In Side Bar is not present the 'QUERY OBJECT ON MAP' button for the mobile version of MapStore

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Browser Version Affected*

No browser related

*Steps to reproduce*

- Click on a Map
- Click on Side Bar

*Expected Result*

*Current Result*

No button 'QUERY OBJECT ON MAP' in the Side Bar

**Comment by tdipisa** [comment]
Issue not clear, closed for inactivity.
