### ISSUE TITLE
Mobile - New Deshboard with map error page

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#4390]
### Description
Create a new deshboard on pc with a map widget. 
Open it on mobile. An error page appears.

![issue6](https://user-images.githubusercontent.com/56537133/67373565-295b9e80-f580-11e9-87b6-fa892ea42caa.gif)

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Browser Version Affected*

No browser related

*Steps to reproduce*

- login with admin
- Create new Deshboard with map widget on pc
- save the deshboard
- Open this Deshboard on mobile

*Expected Result*

- Describe here the expected result 

*Current Result*
An error page appears when you try to open a deshboard with map on mobile

### Other useful information (optional):
Insert a new map widget in a deshboard from mobile obtain same problem

**Comment by tdipisa** [comment]
@jstrR this issue seems to be solved now on both master branch (DEV instance) and 2020.02.xx branch (QA instance).
If you are not able to replicate this too, please move the issue in test column and ask @ElenaGallo for a new test.

**Comment by jstrR** [comment]
@ElenaGallo could you retest this one?

**Comment by ElenaGallo** [comment]
Issue solved and closed.
