### ISSUE TITLE
Handle map permission and setting from map

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#4391]
### Description
To change permissions on maps we need right now to go back to the home page, find the map we want to manage and then make a modification. 

The Map properties modal must be shown every time we click on **Save** or **Save as**, in the same way we are doing now for GeoStory and shouldn't only available in the map catalog in home page.

Below what should be shown to the user: 

**Save:**

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/2518d344-0b24-4a48-b42f-ead8d20ca9d7)

**Save as:**

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/2f55ef14-f2ee-4735-915e-16296423858c)

**Comment by offtherailz** [comment]
We must use same functionalities and components used for dashboards and stories. To unify all the resources saving system

Please take into account #2908 this requirements

**Comment by offtherailz** [comment]
Please take into account #2908 this requirements

**Comment by francoperversi** [comment]
@kasongoyo when I save/save as a map with a new thumbnail, the thumbnail is not immediatly applied to the card on the homepage (but only after a page refresh)

![thumb_settings gif](https://user-images.githubusercontent.com/54808782/68948912-3e130700-07b9-11ea-8a51-6f88f2f6f64c.gif)

@tdipisa I noticed that the window title when the user click on save and save as, is always EDIT PROPERTIES: is this something that needs to be changed (for example editing the title in SAVE and SAVE AS when the user access the window form those buttons)?

**Comment by francoperversi** [comment]
Issue solved for **Save** button, needs to be solved also for **Save as**
