### ISSUE TITLE
Enrich visualized resource metadata (Map, Dashboard, GeoStory)

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#4392]
### Description
At the moment we don't know the following information for a created Map, Dashboard or GeoStory:

- Creation date
- Modification date

These information are already available but but not reported. 

![dates_modal.jpg](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/9ce9ef68-67ec-48df-80c3-46f79da9d65d)

The metadata above must be shown inside the Properties modal just below **Title** and **Description**.

![modal_dates.jpg](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/5af74b4f-387c-4ddb-a247-7198aad3488d)

### Other useful information (optional):
The Date format should be configurable from plugin configuration and by default it should be represented according to the selected language

**Comment by offtherailz** [comment]
This should be a part of this #2908 reusing the same code.

**Comment by ElenaGallo** [comment]
@kasongoyo the scroll bar must be removed on the edit propertis and on save/save as. (is only necessary on the edit propertis of the map)
![scroll bar](https://user-images.githubusercontent.com/56537133/70156262-f1ce2f00-16b3-11ea-8168-e7878c7107a7.JPG)

**Comment by kasongoyo** [comment]
@ElenaGallo 
> @kasongoyo currently the scrollbar happears even when not strictly necessary, probably this has been generated after the inclusion of the modified/created date fields; the modal size could be probably increased a bit to solve this situations. Which is your opinion?

The modal height is not configurable so to change it's size, will require that I edit the root component which power many modals in MS, I feel like the required soln is overkill for only this component. Once the root component changed then we will start dealing with any other place the modal might break. Anyway, may be @offtherailz and @tdipisa  can decide about this. 

Note: The save modal use resizable modal

**Comment by offtherailz** [comment]
> The modal height is not configurable so to change it's size, will require that I edit the root component which power many modals in MS, I feel like the required soln is overkill for only this component. 
You don't have to configure the height of the window. You may need simply to: 
 - [ ] Not show the rows of createdAt/modifiedAt if the dates are not present
 - [ ] Reduce a little the size of them (There is too much blank space)
I suggest this layout: @tdipisa what do you think?

![image](https://user-images.githubusercontent.com/1279510/70249517-c5321a00-177c-11ea-887e-e02bdc84b0ab.png)
