### ISSUE TITLE
Saving Dashboards

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#4393]
### Description
Dashboard save flow is not the same as Maps and GeoStory. Right now we have a Save button in the right sidebar:

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/79b47c06-8a84-4569-aa75-949a38738350)

At the same time you cannot clone a dashboard (Save as is missing). Save and Save as must be placed in the option menu in the same way of Maps and teh save button in the sidebar removed:

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/dcac0dca-8fff-456a-812b-ee4213efe450)

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- A list of steps to reproduce the bug
- ...

*Expected Result*

- Describe here the expected result 

*Current Result*

- Describe here the current behavior

**Comment by francoperversi** [comment]
@kasongoyo actually it is possible to save an empty dashboard: please, make it possible

**Comment by kasongoyo** [comment]
@francoperversi yeah, I intentionally did it. I can modify to make it possible.

**Comment by francoperversi** [comment]
@kasongoyo yes, the original behaviour is that it is impossible to save an empty dashboard, but after a talk with Tobia, we decided to make it possible
