### ISSUE TITLE
Map Detail documentation

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#4406]
### Description
There isn't documentation on how to edit map details:

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/3de85cb0-b794-423b-8ff4-ea6f62b6e17c)

The user guide must be updated with this by including an hyperlink in this section to another page where the procedure to manage map details is described.

**Comment by francoperversi** [comment]
Details part will be implemented in another branch where a more wide re-organization of the documentation is going to be done. This behaviour to avoid conflicts.
