### ISSUE TITLE
Warning "layer and map projection not compatible" occurs though CRS in WMS requests and map CRS fit

### ISSUE THREAD

**Issue by Benni5K** [geosolutions-it/MapStore2#4425]
### Description
We use custom projection EPSG:31468 in our MapStore. When creating an new map and adding a WMS layer from a service that provides this EPSG, a warning occurs: "the current layer(s) and map projection are not completely compatible. Parts or all of the data might not appear in the map."
This error now allways occurs when opening the created map. 

Looking at the network connections, all WMS requests have parameter CRS/SRS=EPSG:31468. 
All WMS services used offer EPSG:31468 (Check GetCapabilities response).
The coordinates measured in MapStore and in QGIS on the geodata used do perfectly fit.

*Browser Affected*
Chrome 77, IE 11

*Steps to reproduce*

See our localConfig.json and new.json attached.

*Expected Result*

As all requests use EPSG:31468 and the map view and coordinates measured seem correct, there should be no warning message.

*Current Result*

Warning message occurs:
![add_map-layer_warning](https://user-images.githubusercontent.com/25839469/67927511-1288fd80-fbb9-11e9-9c90-0c3e916975c2.PNG)

map CRS settings:
![01_crs_settings](https://user-images.githubusercontent.com/25839469/67927119-18caaa00-fbb8-11e9-8f48-bf7aed30171b.PNG)

getMap-Request for map layer used in the map (QGIS Server running in company network):
![getMap_request_map-layer_qgis](https://user-images.githubusercontent.com/25839469/67926233-c7212000-fbb5-11e9-93ff-6e922f8803dd.PNG)

getMap-Request for other map layer used in the map:
![getMap_request_map-layer_lfu](https://user-images.githubusercontent.com/25839469/67926380-2c751100-fbb6-11e9-8260-73c74dabe0e9.PNG)

getMap-Request for background layer used in the map:
![getMap_request_background-layer](https://user-images.githubusercontent.com/25839469/67926482-6d6d2580-fbb6-11e9-83df-088fb46a0cfd.PNG)
)

localConfig.json and new.json:

[json.zip](https://github.com/geosolutions-it/MapStore2/files/3792575/json.zip)

**Comment by mbarto** [comment]
Hi @Benni5K today we put a fix on master that should fix these kind of warnings.
Could you test if this is also fixing your issue?

**Comment by Benni5K** [comment]
Thank you very much @mbarto! Unfortunately we face problems again with the new dependencies behind our proxy. We will come back on you about this soon, until this is solved we're not able to test.
