### ISSUE TITLE
Implement support for a WFS based vector layer

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#4426]
### Description
Either by adding support for a wfs source to the existing vector layer or by implementing a new wfs specific one.
We had a simple implementation for C039 available here: https://github.com/geosolutions-it/MapStore2/commit/2e38f311e61a1d9ad5d49584476284c323b71ebc
This has also support for clustering data.

In addition, add these changes suggested from
- [ ] https://github.com/geosolutions-it/MapStore2/pull/5089#discussion_r401455165
- [ ] https://github.com/geosolutions-it/MapStore2/pull/5089#discussion_r401456643
- [ ] https://github.com/geosolutions-it/MapStore2/pull/5089#discussion_r401469580

## Acceptance criteria
User should be able to: 
- Browse a WFS service as an additional catalog type
- add layers to the map from this catalog
- browse features from feature grid 
- style the vector data as well as I style shape files

**Comment by tdipisa** [comment]
@mbarto, related to https://github.com/georchestra/mapstore2-georchestra/issues/30
