### ISSUE TITLE
RESTful WMTS using not standard CRS

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#4433]
### Description
Issues actually present in WMTS openlayers implementation:
 * in RESTful mode URLs query string should not be removed
 * resolutions calculation does not convert strings to numbers

In addition, added projections miss units in their definition, so resolutions calculation cannot be done.

**Comment by overkamp** [comment]
I successfully tested this fix.
See https://groups.google.com/forum/#!topic/mapstore-developers/UCVqBMirn5U

**Comment by mbarto** [comment]
Hi @overkamp I have just merged the fix you tested on master, patched with another fix for the wrong notification of CRS compatibility.
