### ISSUE TITLE
Map details not visible to anonymous user

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#4443]
## Description
If the view permission is added by the Edit properties, the details cannot be viewed by anonymous users.

![issue new](https://user-images.githubusercontent.com/56537133/72793010-326d1200-3c3a-11ea-998f-e1161ce474b8.gif)

## How to reproduce
- click on new map
- click on save 
- add details from edit properties
- add everyone can view from edit properties 
- click on save
- logout
- click show map details

*Expected Result*
The details are visible in the window

*Current Result*
The details windows shows the error: No_details_available.

## Other useful information
The details are shows for the anonymous usere only if the view permission is added and saved before to add and save the details
 
*How to reproduce*
- click on new map
- click on save
- add permission from edit properties
- click on save
- reopen edit properties and add details
- click on save
- logout
- click show map details

**Comment by offtherailz** [comment]
going to close this issue in favor of #5772
