### ISSUE TITLE
Mobile -  Widget layout on Dashboard

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#4451]
### Description
There is an horizontal line in the widget bar 

![issue #3861](https://user-images.githubusercontent.com/56537133/68303564-622d6480-00a4-11ea-94b9-3a09073dc07e.PNG)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Browser Version Affected*

no browser related

*Steps to reproduce*

- open a dashboard on mobile
- click on widget 
- scroll down

*Expected Result*

There is not an horizontal line in the widget bar 

*Current Result*

There is an horizontal line in the widget bar

**Comment by tdipisa** [comment]
@ElenaGallo it should not be possible to create widgets on mobile. Can we close this?
