### ISSUE TITLE
Application Context - Admin UI

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#4457]
### Description
An administration UI must be created to allow Admin users to create and manage viewer contexts.

The manage context section will be reachable from the manager menu:

![app_context_1.jpg](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/10322547-2d7e-4413-9443-3a3a391fae86)

The manage context section will appear as reported below

![app_context_3.jpg](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/257c5ab4-e325-4d46-bbfe-9008af6ec92a)

### Other useful information:

By default created contexts should are public and the administrator can setup permissions as usual. Once an user Save a map starting from a saved context this map is private as usual and the user can change permissions as usual.

**Comment by francoperversi** [comment]
@vlt1 some problems about contexts manager UI:

- [ ] Adding more than 12 contexts a new page should appears, but actually the new contexts are added just below the firsts 12. This problem remains also after a page refresh

![adding](https://user-images.githubusercontent.com/54808782/69344473-b3765000-0c6f-11ea-973f-b889156970a7.gif)

- [ ] Removing a context that is below the firsts 12 contexts, an error occours, and the page needs to be refreshed to apply changes (probably related to previous problem). The errors reported are:

`Uncaught TypeError: Cannot read property 'start' of undefined`

`GET https://dev.mapstore.geo-solutions.it/mapstore/rest/geostore/resources/resource/13031/attributes 404 (Not Found)`

![delete](https://user-images.githubusercontent.com/54808782/69344774-40b9a480-0c70-11ea-840c-a4fd45973ebe.gif)

- [ ] When you logout or login the page is not immediately refreshed

![login](https://user-images.githubusercontent.com/54808782/69345089-d3f2da00-0c70-11ea-8867-f614e03c6ea8.gif)

**Comment by francoperversi** [comment]
@vlt1 the warning message saving a context with a name that already exists is now the following:

![saving](https://user-images.githubusercontent.com/54808782/69737235-562d4380-1134-11ea-9b87-0703b95d178d.jpg)

Is better, under the red title "Context saving failed" insert the following warning message:
**"A resource with the same name already exists"**

**Comment by tdipisa** [comment]
@francoperversi @vlt1 the [PR](https://github.com/geosolutions-it/MapStore2/pull/4567) of @MV88 must cover the last message so we can ignore this for this issue.
