### ISSUE TITLE
Application Context - MS Landing Page

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#4460]
### Description
Some updates are needed in MS home page to manage context maps.

1 - Possibility to filter maps by context to show resources belonging to a specific context. It should be possible to enable/disable the context filter by configuration file (localConfig). 

**Note:** This filter tool could be improved in the future to host additional filtering capabilities (like data, keywords etc).

The mockup for this is available [here](https://demo.geo-solutions.it/mockups/mapstore2/georchestra-search-filter/#/):

![image](https://user-images.githubusercontent.com/1280027/72161143-d98eb580-33bf-11ea-9047-ca6a46e24e00.png)

2 - Possibility to create maps starting from a created application context instead of the default one: clicking on "New Map" button a modal opens to show the list of app context the user can access to. If one of them is clicked the viewer opens and the user can create the map as usual.

3- If you have not access to the context you now see the full screen message that explain that the resource is not accessible. You have to add the possibility (this functionality can be turned off via configuration) to redirect the user to the default viewer, sending a warning message:
`The context of this map is not accessible or has been deleted, you have been redirected to the default viewer`

### Other useful information (optional):
Generally speaking Users that are able to access an application context defined in MS, should be able to create maps from it, this means maps with a final URL like the one below:

https://dev.mapstore2.geo-solutions.it/mapstore/#/context/{ContextName}/{MapId}

**Comment by vlt1** [comment]
When context is deleted, do we need to find maps that belong to this context and delete them as well?

**Comment by offtherailz** [comment]
@vlt1 I opened an issue about this on geostore, 

In order to batch update all the resources.
[see this](https://github.com/geosolutions-it/geostore/issues/205)
We can move the task of "updating maps when context has been updated in another issue

**Comment by offtherailz** [comment]
@vlt1 for the moment the only thing you need to add to this task is, in case of missing or not accessible context, redirect to the main viewer to see the map. A warnig message will notify the user that the context is not accessible, so he has been redirected to the default viewer. This behaviour should be turned on or off via configuration.

**Comment by ElenaGallo** [comment]
@tdipisa @vlt1 

1_When log out from MS, the filter should be disabled and the pop up closed
![filtercontext](https://user-images.githubusercontent.com/56537133/76546189-56efa880-648b-11ea-8222-d512df2e200c.gif)

**How to reproduce**
- open MapStore
- Login as admin
- filter a context from search bar
- log out 

*Current Result*
The filter still enable and the pop up is open

2_ The scroll bar is slightly out of modal
![scroll bar not centered](https://user-images.githubusercontent.com/56537133/76546519-f4e37300-648b-11ea-9165-33bb2c645aa8.JPG)

3_You are always redirected to the default viewer 

**How to reproduce**
- open mapstore
- login as admin
- click on new map (existing context) 
- search 4460_context
- Click on it

*Current Result*
you have been redirected to the default viewer

**Comment by tdipisa** [comment]
>1_When log out from MS, the filter should be disabled and the pop up closed
@ElenaGallo, it is questionable. If you logout the filter is anyway updated, @offtherailz what do you think?

>2_ The scroll bar is slightly out of modal
@ElenaGallo you are right, @vlt1 please provide a fix for this, thank you.

>3_You are always redirected to the default viewer
@ElenaGallo you are right, but I suppose that the curent logic whants to ensure the possibility to save the new map even if the plugin Save is not present in the context: @offtherailz, @vlt1 can you confirm this or explain which is the logic applied there? @offtherailz if my understanding is confirmed, probably we should discuss this a little bit.

**Comment by offtherailz** [comment]
1. If the filter is updated with the resources the user has access to, it may stay. Anyway to keep things easy to maintain, I like also resetting the filter on login/logout (it is a trivial task, as far as I know).

3. You're right @tdipisa . 
Yes, I had the same effect when I tried the first time. It is misleading, even it is the only way to do it, now. We could improve this, but we have to think to an alternative solution.

**Comment by offtherailz** [comment]
Ok. 
Please @vlt1 can you do these tasks:

 - [ ] reset the filter when login/logout (point 1)
 - [ ]fix the issue with the scroll bar (point 2) 

@tdipisa  will process point 3. Thank you all

**Comment by vlt1** [comment]
@offtherailz I've tested with firefox and chromium, the issue with the scroll bar is not present on my machine :(
