### ISSUE TITLE
Backup MS DBs

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#4464]
### Description
Periodic backups must be provided for MS DBs (DEV, QA, STABLE).

**Comment by Gnafu** [comment]
- Weekly backup
- Backup retention of 2 weeks

I'd like to add another requirements
- Backup must NOT be stored on the same disk where the actual database resides

Good to have:
- Push the backup on Dropbox (or another online service)

**Comment by giacomoc92** [comment]
Status: DB backup and dropbox push are running on a separate machine (mapstore2) in a weekly schedule. 
@tdipisa 
If this is an acceptable level of security, we can move the issue to test, if it's not, we will need to add a new drive to the mapstore machine and move the backups there, this will require taking down the machine for a little while.

**Comment by tdipisa** [comment]
@giacomoc92 ok for now, thank you.
