### ISSUE TITLE
Some of the dev map are broken due to incorrect override of map object

### ISSUE THREAD

**Issue by kasongoyo** [geosolutions-it/MapStore2#4468]
### Description
Some of the dev map are broken due to incorrect override of map object so the updated map returned  from geostore have empty map object. This bug was produced when  save and saveAs feature were tested by the developer. So far the knowing affected maps are as follows;
 - `4093`
- `7965`

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- Open the afore mentioned maps 
- ...

*Expected Result*

- The maps open smoothly

*Current Result*

- The maps does not open with dev console error  
<img width="867" alt="Screenshot 2019-11-08 at 15 34 12" src="https://user-images.githubusercontent.com/1956062/68476967-3ee9ed00-023d-11ea-8a2b-87e2c4a9bdcb.png">

**Comment by offtherailz** [comment]
I fixed the following
- [x] 4093
- [x] 7965
