### ISSUE TITLE
Improve Error page when app crashes

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#4491]
### Description
Actually we have this 
![image](https://user-images.githubusercontent.com/11991428/68780770-08461500-0637-11ea-9cce-1b5ce1f2473a.png)

Which does not provide any info at least for developers

*Steps to reproduce*
- find a way to generate a crash

at the moment this story is doing it
https://dev.mapstore2.geo-solutions.it/mapstore/#/geostory/12081

*Expected Result*

- to have more information about the error and to notify users the github repository and mailing list

*Current Result*

- the only info is on hover

**Comment by MV88** [comment]
actually i would propose something like this (can be improved more)
![Error boundary proposal](https://user-images.githubusercontent.com/11991428/68840880-d75ff180-06c3-11ea-9f0e-37da47d544f2.gif)

**Comment by MV88** [comment]
@tdipisa @offtherailz @mbarto what about prod ? shall we use the same error page?

**Comment by mbarto** [comment]
I am +0 about production.
One nice support we could discuss is something like this: https://sentry.io/welcome/

**Comment by tdipisa** [comment]
@MV88 I would like to completelly remove the red screen by making it **much more discreet**: suddenly visualize this red page while using MS terrifies the user and prevents him to continue using the application if possible. The red screen only makes you angry :)

**Comment by MV88** [comment]
We can proceed by following the two steps:
1) We would like to replace current ErrorPage with a new one
2) Eventually move the ErrorBoundary to plugin level

## 1) New Error page
It must have:
- an error Icon like a !
- a title: "Ops, something went wrong" or similar
- a description of the error
- a refresh page button

If possible:
- it should be a modal with the application in background with some opacity
- otherwise just replace the current Red page with the new one

can be something similar to
![image](https://user-images.githubusercontent.com/11991428/76615327-1bec8400-6522-11ea-93be-f72f6ced0e80.png)

## 2) Error page to plugin level
This task needs to be discussed and a new issue is required for this point

**Comment by mbarto** [comment]
+1 for the plugin level errorboundary, maybe we can enforce it in the PluginsUtils functions

**Comment by MV88** [comment]
(Quoting the official doc)
> Error boundaries are React components that catch JavaScript errors anywhere in their child component tree, log those errors, and display a fallback UI instead of the component tree that crashed

This means that we cannot display a modal with the application as a background.
So for the moment we can replace the current ErrorBoundary (red face) with the new one with low effort.

> +1 for the plugin level errorboundary, maybe we can enforce it in the PluginsUtils functions

This should be analyzed case per case depending on the plugin, we can even add ErrorBoundaries to some Components down the tree, not necessarily to the root comp of the plugin

**Would be best to** 
(Quoting the official doc) 
> We also encourage you to use JS error reporting services (or build your own) so that you can learn about unhandled exceptions as they happen in production, and fix them.

**Comment by mbarto** [comment]
> This means that we cannot display a modal with the application as a background.
> So for the moment we can replace the current ErrorBoundary (red face) with the new one with low effort.

This is because error boundaries should be the last chance for catching crashes, so the application or the wrapped component is usually not in a consistent state when this happens.

> 
> > +1 for the plugin level errorboundary, maybe we can enforce it in the PluginsUtils functions
> 
> This should be analyzed case per case depending on the plugin, we can even add ErrorBoundaries to some Components down the tree, not necessarily to the root comp of the plugin

But... errorboundaries are not to be confused with error handling, that should be done in a cleaner way, they are only a way to catch fatal errors (not recoverable ones) and capture them so that a bug can be filed.

> > We also encourage you to use JS error reporting services (or build your own) so that you can learn about unhandled exceptions as they happen in production, and fix them.
Yes, you are right they are usually combined with error tracking services (e.g. Sentry.IO) to have a meaningful use.

**Comment by MV88** [comment]
> But... errorboundaries are not to be confused with error handling, that should be done in a cleaner way, they are only a way to catch fatal errors (not recoverable ones) and capture them so that a bug can be filed.

I meant this paragraph  [Where to Place Error Boundaries](https://en.reactjs.org/docs/error-boundaries.html#where-to-place-error-boundaries)

> The granularity of error boundaries is up to you. You may wrap top-level route components to display a “Something went wrong” message to the user, just like server-side frameworks often handle crashes. You may also wrap individual widgets in an error boundary to protect them from crashing the rest of the application.

**Comment by mbarto** [comment]
@MV88, ok, my opinion is that we should not go too deep
