### ISSUE TITLE
Update your documentation

### ISSUE THREAD

**Issue by iamtekson** [geosolutions-it/MapStore2#4494]
I read both (user and developer) documentation of this system. I tried to figure out the documentation of this system. I also search on youtube. The latest video for the instruction was 2 years ago. After reading all the documentation, I think, I can develop the system If and only if I have a core concept of the project. If I understand all of the code and concept of the projects, then I will be able to develop the system. Am I correct?
Also, there is no shortcut method to install this system on our local machine. is it a framework or something else?

**Comment by tdipisa** [comment]
Hi @iamtekson, thank you so much for opening this issue, anyway please use the mailing list for this kind of questions: you can subscribe [here](https://mapstore2.geo-solutions.it/mapstore/#/) on our demo site. We are currently improving our documentation and there are some issues still opened for this (you can see all of them filtering by "Documentation" label): we have in plan to finalize missing parts in next months.
