### ISSUE TITLE
Map Inline Editing - Advanced

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#4501]
# Description
When the Map inline editing is active, we should consider on having some controls to:
- [x] add tabs for each section: TOOLS, TOC
- [x] enable/disable the zoom in/out buttons and their position in the map
- [x] enable/disable the pan movement in the map (should disable both DragPan and KeyboardPan)
- [x] when inline editing is opened and zoom control is enabled, then MouseWheelZoom is enabled 
- [x] when zoom control is disabled then outside inline editing all the possible ways to zoom should be disabled (DoubleClickZoom, KeyboardZoom, PinchZoom, DragZoom, MouseWheelZoom)

NOTE: there is no support for disabling enabling interactions in openlayers map. part of the time will be used to add it.

see https://github.com/geosolutions-it/MapStore2-C039/issues/118

**Comment by ElenaGallo** [comment]
Writing mistake in zoom in/out interactions dropdown menu. not 'Angolo in basse a destra' but 'angolo in basso a destra'. 
![issue 4501](https://user-images.githubusercontent.com/56537133/69791801-8ec92d80-11c5-11ea-92c3-1d6f4124b82b.JPG)
