### ISSUE TITLE
Background selector improvements

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#4504]
### Description
- [x] Edit buttons of Background Selector:

![selector_1](https://user-images.githubusercontent.com/1280027/68878884-c1c0eb00-0708-11ea-95d3-29cf9bc87ae1.jpg)

must be available only to users with write permissions to the map.

- [x] Currently too much clicks are needed to edit a background: you need to select a background and then reopen the tool to be able to click on the edit button. The tool must be enhanced as illustrated below.

![selector_2](https://user-images.githubusercontent.com/1280027/68879642-09944200-070a-11ea-802c-53ca359e7542.jpg)

**Comment by francoperversi** [comment]
@vlt1 when the user removes all the backgrounds from backgrounds selector except one, if the last background has the settings button, it remains in his default position. It's more good looking to move it on the right when the remove button is not present.

![removeb](https://user-images.githubusercontent.com/54808782/69153228-23ed6780-0ade-11ea-9d2a-b936bef2ba05.jpg)
