### ISSUE TITLE
Investigate on pdfjs pdf.worker.js inclusion

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#4511]
### Description
PDFjs used by the print plugin dinamically loads pdf.worker.js from the application root folder.
Currently the file is not copied to the final deploy, so it is never loaded.
Probably it's not used by the PDF viewer utilities (or not mandatory); we need to:
 * understand if we have any advantage if we include it in the build
 * eventually mock the original file to avoid network errors in the browser

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- A list of steps to reproduce the bug
- ...

*Expected Result*

- Describe here the expected result 

*Current Result*

- Describe here the current behavior

**Comment by tdipisa** [comment]
Fixed with https://github.com/geosolutions-it/MapStore2/pull/6492
