### ISSUE TITLE
Builder - Content Editor - Web page

### ISSUE THREAD

**Issue by kboczkowski-clurgo** [geosolutions-it/MapStore2#4514]
### Description
See [geosolutions-it/MapStore2-C039/issues/32](https://github.com/geosolutions-it/MapStore2-C039/issues/32)

**Comment by ElenaGallo** [comment]
@kboczkowski-clurgo 

- [ ] The drag and drop, works, but the modal appears
-  open a web page section
- add a web page
- drag and drop the web page

*current result*
the modal appears

![32 1](https://user-images.githubusercontent.com/56537133/70799378-c5986980-1da9-11ea-8ed1-62a1cde29d1f.gif)

- [ ] The web page is not more editable in immersive section.
- Open an immersive section
- Add web page content 
- Click on Edit we page URL

*current result*
the page is not editable 
![32 3](https://user-images.githubusercontent.com/56537133/70802524-f7adc980-1db1-11ea-821e-34e9e805ffdd.gif)

**Comment by ElenaGallo** [comment]
@kboczkowski-clurgo 
- The drag and drop described [here](https://github.com/geosolutions-it/MapStore2/issues/4514#issuecomment-565435794) still dose not work propertly.

- The WebPage content creation has a different icon button after an immersive section. 
*Expected Result*
![test14si](https://user-images.githubusercontent.com/56537133/71079594-da9b4100-218b-11ea-8fa8-919d6af238da.JPG)
*Current Result*
![test14](https://user-images.githubusercontent.com/56537133/71079642-ed157a80-218b-11ea-8951-ab5a83cbd953.JPG)
