### ISSUE TITLE
Geostory - Maps are not properly aligned/masked when the inline editor is active

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#4523]
### Description
1 - When the Map Inline Edit is activated, maps must be centered in the view to be completely visible. Situations like below must be avoided:

![inline_edit_bug_2.jpeg](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/546ae5cd-1c46-4ace-949b-a26f6ed4cf6a)

![inline_edit_bug_3.jpeg](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/50310db4-fd10-41df-adba-1bb4baa55978) 

2 - In some cases the view is not well masked when the Map Inline Edit is activated, so other unrelated parts of the story (sections) are not masked but they should be. 

![inline_edit_bug](https://user-images.githubusercontent.com/1280027/68948680-b2997600-07b8-11ea-8d5a-77495b494619.gif)

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Steps to reproduce*

- Open [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/geostory/11555) story 
- For bug number 1, create an image section and then scroll down to activate just a part of the map, then activate the Inline Map Editor
- For bug number 2, scroll at the bottom of the second immersive section to visualize just the bottom part of the map and some part of sections below, then activate the Inline Map Editor.

*Expected Result*

- Maps contents are centered and other part of the viewer are properly masked before opening the Inline Map Editor

*Current Result*

- See images above

**Comment by ElenaGallo** [comment]
@MV88 The tooltip for Edit Map Configuration is still visible when the operation is finished.
![test23](https://user-images.githubusercontent.com/56537133/71098966-d0d90400-21b2-11ea-966b-5cd58f02a69a.gif)
