### ISSUE TITLE
Embedded style and UI problems

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#4529]
### Description
Embedded version has some problems:
- with the style of polygons from search bar
- with the spinner that does not fit the space

### In case of Bug (otherwise remove this paragraph)

*Steps to reproduce*

**Search style problem**
- open [this](https://dev.mapstore2.geo-solutions.it/mapstore/embedded.html#/4093) embedded map
- write armenia in the search bar
- select the first result

**Spinner identify**
- open the same map (as above)
- go to network and reduce network speed (fast 3G or lower)
- click on a state
- take note of the spinner dimension

*Expected Result*

**Search Bar problem**
![image](https://user-images.githubusercontent.com/11991428/69243535-8fe5d380-0ba3-11ea-8409-227001483d51.png)

**Spinner identify**
- the spinner should use the available space or be like the initial loading spinner used for maps, stories etc
![image](https://user-images.githubusercontent.com/11991428/69243921-477ae580-0ba4-11ea-88be-e8849cd2f29e.png)

*Current Result*

**Search bar problem**
![image](https://user-images.githubusercontent.com/11991428/69243580-ab50de80-0ba3-11ea-9a0f-388004c06a31.png)

**Spinner identify**
- it does not fit the available space
![image](https://user-images.githubusercontent.com/11991428/69243734-f3700100-0ba3-11ea-8ede-fc070e58765c.png)

**Comment by tdipisa** [comment]
No longer reproducible, the issue has been fixed in latest releases.
