### ISSUE TITLE
Warning message problems saving resources with same name

### ISSUE THREAD

**Issue by francoperversi** [geosolutions-it/MapStore2#4535]
### Description
Actually the behavior of the warning message when saving resources with the same name is quite various, depending of resource type:
1. **Renaming a resource with an existing  resource name from the Edit properties button**
    - For maps the following warning message appears : `A thumbnail with this name already exist` (see image 1. in 'Other useful information')
    - For dashboards no warning message appears, when you try to save nothing happens (see image 2. in 'Other useful information')
    - For stories same than dashboards
    - For contexts same than dashboards
2. **Naming a resource with an existing resource name from Save/Save as button**
     - For maps the following warning message appears : `A resource with this name already exist, try 'resourcename - 2'` and a warning window on background appears with the following message: `Cannot save current map - A map with this name already exist` (see image 3. in 'Other useful information')
    - For dashboards only a warning message appears: `A resource with this name already exist, try 'resourcename - 2'` (see image 4. in 'Other useful information')
    - For stories same than dashboards
    - For contexts same than the others

I propose to uniform the behavior that has to be the same for all the resources (maps, dashboards, stories and contexts), in this way:
1. **Renaming a resource with an existing resource name from the Edit properties button**
    - The following warning message appears: `A resource with this name already exist`
2. **Naming a resource with an existing resource name from Save/Save as button**
    - The following warning message appears: `A resource with this name already exist`
    - The following warning window appears in background: `Cannot save current resource - A 
resource with this name already exist`

Moreover, a little fix is needed, only for maps and stories:
When you rename a resource with an existing resource name from the Save button, if you close the Save and you open the Save as (or again the Save), the warning message is still there. All the way around, when you rename a resource with an existing resource name from the Save as button, if you close the Save as and you open the Save (or again the Save as), the warning message is still there (see image 5. in 'Other useful information')

### Other useful information (optional):
1. 
![maps_ep](https://user-images.githubusercontent.com/54808782/69352020-7795b780-0c7c-11ea-9fb5-fb849096de7b.jpg)
2.
![dash_ep](https://user-images.githubusercontent.com/54808782/69352037-7e242f00-0c7c-11ea-91a3-d713fdb14d86.gif)
3.
![maps_s](https://user-images.githubusercontent.com/54808782/69352048-82e8e300-0c7c-11ea-8dae-833ae70b6c12.jpg)
4.
![dash_s](https://user-images.githubusercontent.com/54808782/69352063-87ad9700-0c7c-11ea-8175-60f51fd6f617.jpg)
5.
![tooltipk](https://user-images.githubusercontent.com/54808782/69354271-1ec81e00-0c80-11ea-9d05-768746a22eb3.gif)

**Comment by francoperversi** [comment]
- [ ] The following problem is still present for stories:

> Moreover, a little fix is needed, only for maps and stories:
> When you rename a resource with an existing resource name from the Save button, if you close the Save and you open the Save as (or again the Save), the warning message is still there. All the way around, when you rename a resource with an existing resource name from the Save as button, if you close the Save as and you open the Save (or again the Save as), the warning message is still there (see image 5. in 'Other useful information')

- [ ] Another issue for contexts:
Creating a new context, or editing an existing one with the "Edit Context" button, if you insert an already existing name the warning message appears when you Save (actually 2 step). It is better to make the warning message appears just after the "Next" button in step 1

**Comment by MV88** [comment]
@francoperversi no problem with 1) i'll fix it quickly

@tdipisa what about 2) ? should this be a separated issue or are we going to ignore it ?

**Comment by tdipisa** [comment]
@francoperversi @MV88 I agree with the point 2 but I would like to open a new issue for this

**Comment by MV88** [comment]
for second point see https://github.com/geosolutions-it/MapStore2/issues/4615
