### ISSUE TITLE
Application Context - Parametric viewers - Viewer

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#4550]
### Description
The base support to manage multiple parametric viewers has been defined in #4379. An additional step must be included on the context creation/edit wizard that is related to the viewer's content settings; a fully configured MS webgis is opened in this wizard step (this means a viewer like the one you open while creting a new map) to allow the administrator to configure  the contents (initial state) of the application context in terms of:

Catalogs
Layers/groups in TOC
TOC settings
Map initial extent/center
Background layers
Map CRS

What reported above means that a map configuration must be associated to the context: **that map configuration must be included within the application context configuration.**

The step of the wizard must be enabled only if valid context name/title have been provided in the step n°1 (the mockup [here](https://demo.geo-solutions.it/mockups/mapstore2/geoorchestra/#/app-context/general-settings))

**note:** until the issue [#22](https://github.com/georchestra/mapstore2-georchestra/issues/22) is provided, the wizard step described in this issue must be the step n°2 of the wizard itself.

According to the mockup the admin can navigate between the available wizard steps.

### Other useful information:
The aim of this task is to have a viewer where a map has been pre-configured by the administrator at a dedicated URL (see issue #4379)

**Comment by ElenaGallo** [comment]
@mbarto on  the wizard the Background layers and the Side bar overlap the others funcionality
![geO step2](https://user-images.githubusercontent.com/56537133/70150530-70be6a00-16aa-11ea-9792-eadcf443a8d4.JPG)
