### ISSUE TITLE
Drag and drop doesn't work in some browsers

### ISSUE THREAD

**Issue by michegg** [geosolutions-it/MapStore2#4553]
### Description
Drag and Drop function for moving vertices while drawing annotations doesn't work for Edge and IE.

### Bug

*Browser Affected*
- [x] Edge
- [x] Internet Explorer

*Browser Version Affected*

- Edge 17
- IE 11

*Steps to reproduce*

- Draw a polygone in annotations with at lest 3-4 vertices.
- Try to move the order of vertices by drag and drop option.
- Moving of vertices will not be possible.

*Expected Result*

- Should work as in Chrome, Firefox etc.

*Current Result*

- Vertices can't be moved by drag ans drop option.

**Comment by tdipisa** [comment]
@dsuren1 since you are working on annotations, can you please consider this issue too?

**Comment by dsuren1** [comment]
Sure @tdipisa , I will consider this issue too
