### ISSUE TITLE
Share tool problems

### ISSUE THREAD

**Issue by francoperversi** [geosolutions-it/MapStore2#4566]
### Description
The following fixes have to performed for the share tools:

**Opening the share tool from the Homepage:**

- [ ] Add `/mapstore/` in link for maps, dashboards, stories and contexts (an example of correct link is `https://dev.mapstore.geo-solutions.it/mapstore/#/viewer/openlayers/356`)

- [ ] Remove the embed tab in dashboards and stories

- [ ] Add `/mapstore/` in embed iframe for maps, and contexts 

- [ ] Remove the _Show TOC_ option in embed section for contexts 

- [ ] Fix the maps API that is not working (in order to fix this, see the API from the share in burger menu that works)

**Opening the share tool from the Burger Menu:**

- [ ] Remove the _Show TOC_ option in embed section for contexts

**Comment by francoperversi** [comment]
@offtherailz after the test I report the following observations:

- [ ] Opening the share tool from burger menu in contexts, the `Show TOC` option is still present

- [ ] Opening the share tool from featured maps in homepage, the embed tab is not present

**Comment by tdipisa** [comment]
> @offtherailz after the test I report the following observations:
> 
> * [ ]  Opening the share tool from burger menu in contexts, the `Show TOC` option is still present

@francoperversi Contexts will not be released now, so please put a note for this in [this](https://github.com/georchestra/mapstore2-georchestra/issues/22) issue. 

> * [ ]  Opening the share tool from featured maps in homepage, the embed tab is not present

@francoperversi we know about that, please open a new issue for this and put it on 2019.03.00
