### ISSUE TITLE
Wrong UOM reported in annotation and filter panel when map projection in EPSG:4326

### ISSUE THREAD

**Issue by kasongoyo** [geosolutions-it/MapStore2#4577]
### Description
When map projection is in EPSG:4326, it's by default report distance in degrees unit but annotation and filter panel report it as meters. 
![Annotation](https://user-images.githubusercontent.com/1956062/69794421-487ec900-11db-11ea-8b64-b75eeeaf3199.gif)

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*
Not browser related

*Steps to reproduce*

- Set the map projection to EPSG:4326
- Open any map
- Follow the normal steps to create circle annotation
- Draw the circle in the map
- See in the annotation form, the reported radius value is in degree but the form unit field indicate meters. Internal this radius is treated as meters while it is in degrees 

*Expected Result*
The radius UOM is in correct unit i.e in degrees or if it is meters, then it has been converted from degree to meters accordingly. 

*Current Result*
The radius in degrees treated as meters. 

- Describe here the current behavior

### Other useful information (optional):
If you edit radius in the form, it produce tiny circle, may be because the geometry calculation is done with assumption that the radius is in meters. Same behaviour happens if you change the center points

**Comment by offtherailz** [comment]
Sorry, we opened these two issue at the same time :smile:  See #4578. I did because I didn't see it, so I did it on my own. 
Can you please take the information you need from it. I'm going to close it.

**Comment by francoperversi** [comment]
@MV88 Drawing a circle from query panel, the dynamic uom of the radious is not shown. This happens with both CRS (4326 and 3857)

![unit](https://user-images.githubusercontent.com/54808782/70227449-e2ea8980-1752-11ea-93b6-8e3891868412.jpg)
