### ISSUE TITLE
Annotations has error when drag center out from projection limits

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#4579]
### Description
Moving the circle in invalid coordinates and then back to valid, you have an error in console and the editing stop working. Thiis problem exists since 2019.02 (and more likely previously).

Projection of the test is EPSG:436 (radius is wrong becuse of #4578)
![Peek 2019-11-27 11-12](https://user-images.githubusercontent.com/1279510/69714617-084e1680-1107-11ea-9696-303507ac3470.gif)
### In case of Bug (otherwise remove this paragraph)

*Steps to reproduce*

- Create a circle annotation
- Drag it out of the world and bck.

*Expected Result*

- Continue working (or deny to drag out)

*Current Result*

- The annotation editing stop working.

**Comment by ElenaGallo** [comment]
This issue is no longer valid, it can be closed.
