### ISSUE TITLE
Share tool - embed tab missing in featured maps

### ISSUE THREAD

**Issue by francoperversi** [geosolutions-it/MapStore2#4597]
### Description
Opening the share tool from the homepage, the embed tab is missing in featured maps

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [X] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Not browser related

*Steps to reproduce*

- Open mapstore
- Click on the share tool on a featured map

*Expected Result*

![good](https://user-images.githubusercontent.com/54808782/70069315-dd296280-15f1-11ea-890d-1b8e1e4e42eb.jpg)

*Current Result*

![bad](https://user-images.githubusercontent.com/54808782/70069320-df8bbc80-15f1-11ea-9b04-3159e2f113a9.jpg)

**Comment by ElenaGallo** [comment]
@UMarkau  Opening the share tool from homepage, the embed tab is present in featured dashboard but it is not required.

*Steps to reproduce*

- Open mapstore
- Click on the share tool on a featured dashboard

*Expected Result*
![issue](https://user-images.githubusercontent.com/56537133/72341612-f6323280-36ca-11ea-9cc7-3a8ccd656a2f.JPG)


*Current Result*
![good](https://user-images.githubusercontent.com/54808782/70069315-dd296280-15f1-11ea-890d-1b8e1e4e42eb.jpg)
