### ISSUE TITLE
Add lists to the text editor in geostory

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#4603]
### Description
add ordered and unordered lists 

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- open a new geostory
- open text editor
- check in the editor toolbar the presence of lists

*Expected Result*

- to find list tools for ordered or unordered lists

*Current Result*

- the tool is not present

**Comment by ElenaGallo** [comment]
- [ ] In the ordered list the number is not aligned with the test
![issue 4603 90](https://user-images.githubusercontent.com/56537133/70231014-d1f14680-1759-11ea-9668-ddb81e72e5be.png)

- [ ] If the list is aligned to the center and to the left, the text is not correctly displayed and the text editor gets bigger.
![issue 4603 1](https://user-images.githubusercontent.com/56537133/70231634-044f7380-175b-11ea-875c-7dd5f8b05154.gif)

**Comment by MV88** [comment]
1) The first point is related to the fact that the text and the number have a different font size 

2) I think we can ignore the second point because there is also in the original library
see the demo [here](**https://jpuri.github.io/react-draft-wysiwyg/#/**)
Anyway i'll check why the editor increases in height

**Comment by tdipisa** [comment]
@ElenaGallo this functionality can stay as it is now.
