### ISSUE TITLE
Problem with map widget preview on editing

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#4614]
### Description
Map widget when edited does not show the preview.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- open a new dashboard
- create a map widget (with a casual layer)
- add it to the dashboard
- enter edit

*Expected Result*
- to see the preview

*Current Result*
- no preview at all is visibile (inspecting the dom, it is missing)

**Comment by offtherailz** [comment]
Also editing some existing dashboard (not all) the same problem is there... And the widget seems to render 2 maps. Probabily a problem of the div ID that causes a render of the preview map inside the widget.

**Comment by MV88** [comment]
i think is more related to the id returned [here](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/widgets/builder/wizard/map/enhancers/handleMapSelect.js#L28) which is the cause of the problem for this issue.

I still need to check it was needed in the stories workflow
