### ISSUE TITLE
Improve context creation flow, if context name already exists

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#4615]
### Description
This issue is created from the comment [here](https://github.com/geosolutions-it/MapStore2/issues/4535#issuecomment-561737405)

When using an already existing name for a context then it should check for it before enabling forward button

*Steps to reproduce*

- Open a new context
- use an existing name for it (prova)
- enter a title
- go to the next step

*Expected Result*

- the conflict name message to be displayed here (maybe with the field highlighted)

or
- to validate on the fly with a debounce effect

*Current Result*

- You can go to the next step, but then when saving a conflict message is displayed

### Other useful information (optional):

see https://github.com/georchestra/mapstore2-georchestra/issues/141

**Comment by ElenaGallo** [comment]
@vlt1 an observations:
When using an already existing map/dash/story' s name for a context then it should check for it before enabling forward button

*Steps to reproduce*

- Open a new context
- use an existing map/dash/story's  name for it (States)
- enter a title
- go to the next step

*Expected Result*
- the conflict name message to be displayed here (with the field highlighted)

*Current Result*
- You can go to the next step, but then when saving a conflict message is displayed
