### ISSUE TITLE
Create new release of http-proxy and GeoStore for 2020.01.00

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#4627]
### Description

**HTTP-PROXY**
Stable branch 1.1.x of Http-Proxy must be created from current master, MS master must use this.
v1.1.0 of Http-Proxy must be released from current master 1.1-SNAPSHOT, MS [2020.01.xx](https://github.com/geosolutions-it/MapStore2/tree/2020.01.xx) must use this.

**GEOSTORE**
Stable branch 1.4.x already exists for GeoStore and MS master is using this.
v1.4.2 of GeoStore must be released from current 1.4.x branch, MS [2020.01.xx](https://github.com/geosolutions-it/MapStore2/tree/2020.01.xx) must use this.

**Comment by mbarto** [comment]
* [x] Create v1.1.0 tag for http-proxy and deploy to maven
 * [ ] Create v1.4.2 tag for geostore and deploy to maven
 * [ ] update MapStore http-proxy and geostore versions in pom.xml
