### ISSUE TITLE
Allow runtime plugin loading 

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#4629]
### Description
Currently plugins can only be dinamically loaded if they are included in the product plugins.js.
We want to be able to load / render also (compiled) plugins that are not included in the plugins.js list.

**Comment by ElenaGallo** [comment]
@mbarto 
Loading the [My](https://github.com/geosolutions-it/MapStore2/files/4152847/plugin.zip) extencion , it appears several times in the list of available plugins. 

*Step to reproduce*
- Open new context 
- Insert a Tilte
- Click on Add an extencion to Mapstore
- D&d the zip file
- Search My plugin on the list of available plugins

![plug my](https://user-images.githubusercontent.com/56537133/73739197-11caaf00-4746-11ea-8327-faa0e033e7dd.JPG)

**Comment by ElenaGallo** [comment]
> @mbarto
> Loading the [My](https://github.com/geosolutions-it/MapStore2/files/4152847/plugin.zip) extencion , it appears several times in the list of available plugins.

Now the problem explained above is fixed but the [plugin](https://github.com/geosolutions-it/MapStore2/files/4193388/plugin.zip) is no longer visible in context

**Comment by ElenaGallo** [comment]
Closed in favor of #[166](https://github.com/georchestra/mapstore2-georchestra/issues/166)
