### ISSUE TITLE
Mobile -  The setting button is not properly displayed on the GetInfo 

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#4659]
### Description
In some cases (galaxy s7) the  setting button for aeronautical coordinates is not displayed correctly

![test2.JPG](https://images.zenhubusercontent.com/5da5b30f66de7b0001e4e77c/5804c571-9232-488c-bfb1-523930f4edc3)

*Browser Version Affected*

no browser related

*Steps to reproduce*

- Open  Mapstore from mobile
- Open a map
- Click on the map and GetInfo modal opens
- Click on Show coordinate Editor
- Click on Setting - AREONAUTICAL

*Expected Result*
-  The setting button is appropriately centered

*Current Result*
- The setting button is above the coordinates

**Comment by tdipisa** [comment]
No longer an issue, fixed in latest releases.
