### ISSUE TITLE
WMTS background problems

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#4667]
## Description
Is not possible import this map background ([rvr.zip](https://github.com/geosolutions-it/MapStore2/files/3977489/rvr.zip)) on a map because the crs is not supported but now the error page opens.

![test2](https://user-images.githubusercontent.com/56537133/71018603-19cc8200-20f9-11ea-951f-e4448ec47c1e.gif)

## How to reproduce

- Open Mapstore
- Click on New Map
- Import the rvr.json map

*Expected Result*

It must be open an allert message for indicate  that it is impossible open the map because the crs is not supported

*Current Result*

The error page opens 

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome|x|
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@ElenaGallo, but where is the rvr.json json file? Please put some additional info regarding the console error in **Other useful info**.

**Comment by tdipisa** [comment]
@UMarkau, here we just need to catch the error and report to the user the reason of the problem (we will need probabli to update translations files for this).

**Comment by ElenaGallo** [comment]
@UMarkau Now the allert message also opens when the import file has the supported pojection, like this one [map (13).zip](https://github.com/geosolutions-it/MapStore2/files/4108291/map.13.zip)

**Comment by tdipisa** [comment]
@ElenaGallo please test it in QA and then close
