### ISSUE TITLE
Add possibility to connect widgets to TableWidget

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#4674]
## Description

This issue is part of #4149 

A Table Widget TW, present inside a Dashboard, can be an alternative connection target (Parent Table PT) as done for the Map widgets.

## Acceptance criteria

Here a list of rules to follow
- [x] Now connections between widgets can be shown with a button in the dashboard toolbar. It must be active by default and better visible
- [x] Quick filter, can be visible only for PT and not in TW (cannot be configurable)
- [x] A widget can be connected to a Map widget or to a Table widget, a double connection at the same time isn't allowed
- [x] A widget can be connected to a Table widget (Parent Table) only if it refers the same dataset (layer)
- [x] A widget can be connected to a Table widget (that in this case become **Parent Table**) only if the Table isn't already connected to another Table widget or a Map widget
- [x] A Parent Table cannot be connected to another Table widget and cannot be connected to a Map widget 
- [x] A widget can be connected to a Map widget that is at the same time connected to a Parent Table, in such case:
  - [x] If the widget has been created on the same dataset (layer) of the Parent Table then two filters will be applied in AND to the widget itself: the spatial filter of the Map widget and the attribute filter defined in the Parent Table
  - [x] If the dataset isn't the same only the spatial filter of the Map widget will be applied as usual

- [x] A Map widget connected to a Table (Parent Table) receives the filter of the Table widget and:
  - [x] Perform a zoom to the extent that contains all the Table widget records (the result of a filter in the table attributes). A WPS in GeoServer can be used to calculate it since we have virtual scrolling.
  - [x] If the Map widget contains the same dataset (layer) published in it, also the layer on map need to be filtered using the cql_filter query parameter in the WMS request (the same that currently happens with the synch map tool in the viewer Attribute Table)

- [x] A widget can have its own filter defined and can be directly connected to a Table widget (Parent Table). In that case the widget filter is ANDed with the one defined on the Parent Table 

## Other useful information

The diagram below shows the interactions between widgets and not allowed connections:

![COMUNE GENOVA - Dashboard filtering capabilities](https://user-images.githubusercontent.com/1280027/64352670-bb254180-cffc-11e9-975f-6dfbeb892d04.jpg)

The images below show two possible use cases while a widget is connected to a Map/Table

![widget_connection_3](https://user-images.githubusercontent.com/1280027/64346934-53b6c400-cff3-11e9-975c-8aa25417e5ed.jpg)

![widget_connection_2](https://user-images.githubusercontent.com/1280027/64346937-56b1b480-cff3-11e9-8ffd-346fa971ef46.jpg)

**Comment by ElenaGallo** [comment]
@MV88 some observations:
1_
The connection between a table (layer A) and a table (layer B) is allows 

**Steps to reproduce**
- add a table widget (ex:states)
- add one more table widget (ex:poi)
- click on connect to the other widget
- click on save

*Expected Result*
Is not possible connect table layer A with a table layer B

*Current Result*
Is possible connect table layer A with a table layer B


2_
If there are a connection between a map (layer A) and the widget (layer B) and PT (layer A), the interaction couse an error on the widget (layer B)

**Steps to reproduce**
- add a table widget (ex:poi)
- add a map widget (ex:poi) and connectes to the table
- add a counter widget (ex:states) and connectes to the map

*Expected Result*
The interaction between the table and the counter work

*Current Result*
The interaction between the table and the counter cause an error on the counter

**Comment by MV88** [comment]
@tdipisa the problem 5_ should be prevented by not allowing a map to connect to a table when they not share the same layer, right?
you should not be able to connect a map widget (ex:poi) to a table widget (ex:states), but the viceversa is possible.

**Comment by tdipisa** [comment]
> @tdipisa the problem 5_ should be prevented by not allowing a map to connect to a table when they not share the same layer, right?
> you should not be able to connect a map widget (ex:poi) to a table widget (ex:states), but the viceversa is possible.

This is possible indeed, look at the diagram where a Map (with Layer C) is connected to a Parent Table

**Comment by ElenaGallo** [comment]
@MV88 Now the second point has a problem with the interaction betwee the table and the map (layer A) and the widget (layer B)
