### ISSUE TITLE
Import vector files problems

### ISSUE THREAD

**Issue by francoperversi** [geosolutions-it/MapStore2#4678]
## Description
Importing vector files the following issues are detected:

1. Importing more than one vector file at the same time, the **Add local vector files** window doesn't allow to switch between the various layers (in order to reproduce it, you can try to import the following zip file with two shapefiles inside: [vector.zip](https://github.com/geosolutions-it/MapStore2/files/3987518/vector.zip))

![change](https://user-images.githubusercontent.com/54808782/71243403-938a8880-2310-11ea-971f-6566963ffc3a.gif)

2. The widgets button present in TOC toolbar when you select a layer should be disabled for imported files since this option is not available

![widgets](https://user-images.githubusercontent.com/54808782/71243804-65f20f00-2311-11ea-8fe3-43d1b83ec85f.jpg)

## How to reproduce

1.
- Open mapstore
- Login as admin
- Create a new map
- Open burger menu
- Import
- Drag and drop more than one layer at the same time (you can use [vector.zip](https://github.com/geosolutions-it/MapStore2/files/3987518/vector.zip))
- Try to switch between the layers

2. 
- Open mapstore
- Login as admin
- Create a new map
- Open burger menu
- Import
- Drag and drop a vector file and add it
- Open the TOC
- Select the imported layer

*Expected Result*
1. It is possible to switch between the layers
2. There's not the widgets button

*Current Result*
1. Impossible to switch betweeen layers
2. There's the widget button

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
The issue #1 can be solved by removing the dropdown and changing a bit the UI to have a clear wizard with miltiple steps, one for each layer inside the zip. Considering the sample zip archive provided in the description we can finally have something like the following:

![shp_import](https://user-images.githubusercontent.com/1280027/72259543-0dace500-3611-11ea-9557-4c20725a7736.png)

The user can:

1 - Click on "Cancel" button to cancel the import operation as it is now: next layer ar not imported and the modal closed

2 - Click on "Skip" button to skip to the next layer: the current layer will be ignored

3 - Click on "Add" button to add the layer on the map with the selected style and proceed to the next layer in the list or close the modal if all layers have been added

**Comment by francoperversi** [comment]
@UMarkau 
Seems that with different languages the space dimension between the buttons isn't the same. In particular, with english language set there's a space between buttons that could be considered like the ideal one, while on other languages it's less or it's absent

![import-eng](https://user-images.githubusercontent.com/54808782/72622858-5e3f7d80-3944-11ea-859a-40bdf3b03a03.jpg)

![import-de](https://user-images.githubusercontent.com/54808782/72622863-613a6e00-3944-11ea-8f08-0c41253baffd.jpg)

**Comment by ElenaGallo** [comment]
@UMarkau 
If you try to import the layers for the second time, the first validation message remains on the modal window.
![issue 78](https://user-images.githubusercontent.com/56537133/72908869-62014480-3d36-11ea-8374-d24a9493543d.gif)

## How to reproduce

- Open mapstore
- Login as admin
- Create a new map
- Open burger menu
- Import
- Drag and drop more than one layer
- click next 
- click cancel
- Open burger menu
- Import
- Drag and drop more than one layer

*Current Result*

The first layer validation message is still present in the modal windows
