### ISSUE TITLE
Warning messages needed when server doesn't work

### ISSUE THREAD

**Issue by francoxyz** [geosolutions-it/MapStore2#4686]
## Description
Accessing server resources from mapstore, warning messages are needed when the server is not found or doesn't work for some reason
For example, creating a chart widget in a new dashboards, if gs-stable is not working, it displays like the following:

![not-found](https://user-images.githubusercontent.com/54808782/71889340-3aa95580-3142-11ea-94d3-ee9ebd0347c1.gif)

As you can see, user can't immediately understand from UI that is a server problem

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by tdipisa** [comment]
@UMarkau 
At the moment the catalog tool for Dashboards can have just one source URL: you can find it in [localConfig.json](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/localConfig.json#L626) 

You can try to replicate the issue using the following source URL:
http://geoserver.055055.it/geoserver/wms
or
http://geoserver.055055.it/geoserver/csw

You have to add logic to properly manage cases when there are problems on retrieving the server response and show a MS's warning message to the user in these case. The message can be a general message like: "There are problems on retrieving contents from the server".
