### ISSUE TITLE
Update MapStore to use the new REST entry point for attribute update

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#4687]
## Description
Update MapStore to use the new REST entry point for attribute update, instead of URL double encoded one.

See geosolutions-it/geostore#198 and so https://github.com/georchestra/mapstore2-georchestra/issues/101

NOTE FOR TESTERS: after this fixes are merged geostore and mapstore should be tested to continue working as usual. So please re-test resources thumbnails 
- old thumbnails still working
- thumbnail update 
- new resources with thumbnail

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by ElenaGallo** [comment]
@offtherailz  the following problems occur with thumbnail and details:

 **1** -   It is impossible add a thumbnail when you save new map/dash/story
![STEP1](https://user-images.githubusercontent.com/56537133/72081421-be0fa600-32fe-11ea-813a-243bba32efc5.gif)

**How to reproduce**
- open new map/dash/story
- open save as
- add thumbnail
- add name
- save

*Current Result*
A modal window appears with error 405: 'Method not allowed'

**2** - It is impossible add a thumbnail when you edit properties of new map/dash/story
![STEP2](https://user-images.githubusercontent.com/56537133/72081432-c1a32d00-32fe-11ea-9f68-aa4bc3c10659.gif)

**How to reproduce**
- open new map/dash/story
- save with name
- go home page
- open edit properties
- add thumbnail
- save

*Current Result*
The thumbnail is not saved on the card

**3** -  1 and 2 also occur on a map/dash/story that has already been created

**4** - It is impossible add details when you edit properties of a map
![STEP3](https://user-images.githubusercontent.com/56537133/72081444-c49e1d80-32fe-11ea-91e9-48b07a1eb97e.gif)

**How to reproduce**
- open a map without details
- open edit properties
- add details
- save

*Current Result*
The details are not saved and the Details button is not displayed

## Other useful information
If a map has already the details it is possible modify it
