### ISSUE TITLE
API example doesn't work

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#4688]
## Description

only on dev so 2020.01.xx is not affected,only master.
![image](https://user-images.githubusercontent.com/1279510/71965644-5ecb6c00-3200-11ea-8e12-5883de471d56.png)

error
```
VM3118:1 Uncaught TypeError: Cannot read property 'includes' of undefined
    at eval (eval at parseExpression (PluginsUtils.js:NaN), <anonymous>:1:56)
    at parseExpression (PluginsUtils.js:123)
    at handleExpression (PluginsUtils.js:145)
    at Object.filterDisabledPlugins (PluginsUtils.js:168)
    at eval (PluginsContainer.jsx:146)
    at Array.filter (<anonymous>)
    at PluginsContainer.eval [as loadPlugins] (PluginsContainer.jsx:145)
    at PluginsContainer.UNSAFE_componentWillMount (PluginsContainer.jsx:184)
    at callComponentWillMount (react-dom.development.js:14310)
    at mountClassInstance (react-dom.development.js:14409)

react-dom.development.js:21704 The above error occurred in the <PluginsContainer> component:
    in PluginsContainer (created by Context.Consumer)
    in Connect(PluginsContainer) (created by Embedded)
    in Embedded (created by StandardContainer)
    in IntlProvider (created by Localized)
    in Localized (created by StandardContainer)
    in div (created by StandardContainer)
    in StandardContainer (created by Context.Consumer)
    in Connect(StandardContainer) (created by DragDropContext(Connect(StandardContainer)))
    in DragDropContext(Connect(StandardContainer)) (created by StandardApp)
    in Provider (created by StandardApp)
    in ErrorBoundary (created by StandardApp)
    in StandardApp
React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

## How to reproduce

-  open http://dev.mapstore2.geo-solutions.it/mapstore/examples/api/
- 

*Expected Result*

a see the map

*Current Result*

I see the redbox error

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by ElenaGallo** [comment]
@offtherailz the map does not open and the redbox error appears

**Comment by offtherailz** [comment]
Tested on dev Thursday I noticed this issue too , but fiday it was working, probably some cache issue or some error checking if it was deployed by ourself. 

So now it seems to work. If no other comment, please accept
