### ISSUE TITLE
Update geostore and http-proxy dependency versions

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#4692]
## Description
GeoStore and http-proxy dependencies should be updated in MS master to latest 1.5-SNAPSHOT and 1.2-SNAPSHOT respectively. Previous PR provided for #4627 has been reverted (#4691) due to  some missing GeoStore schema updates.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [X] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by offtherailz** [comment]
About GeoStore upgrade, @tdipisa and @mbarto  we should open an issue or epic to keep track of: 

 - [ ] update migration guide on mapstore doc
 - [ ] update all servers with latest changes on db schema

**Comment by francoperversi** [comment]
Test not needed
