### ISSUE TITLE
Dashboard - Share tool button missing in the Options menu 

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#4712]
## Description

Opening a dashboard, in Options menu, missing the share button.  

## How to reproduce

-  Open MapStore
-  Login as Admin
-  Open a Dashboard
-  Click on OPTIONS MENU

*Expected Result*

![DASH-SHARE-ADDING](https://user-images.githubusercontent.com/56537133/72272593-2e813480-3629-11ea-9f94-522b116f9790.jpg)

*Current Result*

![DASH-SHARE](https://user-images.githubusercontent.com/56537133/72272598-317c2500-3629-11ea-8d52-50b6709f8459.JPG)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
Didn't noticed during PR review, but It need more fixes.
 - embedded tab should be hidden
 - advanced options should be hidden (it's empty)
