### ISSUE TITLE
Problem setting Thumbnails, Map Details and Favourites in DEV

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#4716]
## Description
In DEV is no longer possible to create [Thumbnails](https://mapstore.readthedocs.io/en/latest/user-guide/resources-properties/#thumbnail), [Map Details](https://mapstore.readthedocs.io/en/latest/user-guide/resources-properties/#details) and put resources in [Favourites](https://mapstore.readthedocs.io/en/latest/user-guide/home-page/#featured)

## How to reproduce
Simply try to create them as reported in User Guide

*Expected Result*
Thumbnails, Map Details and Featured functionalities are workingas expected (see User Guide links)

*Current Result*
A request to the MapStore backend:

https://dev.mapstore2.geo-solutions.it/mapstore/rest/geostore/resources/resource/17049/attributes/

fails with the following HTTP error:

405 Method Not Allowed

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information
Related to #4687

**Comment by offtherailz** [comment]
This is due to missing method, required and missing 
minimal version form master is GeoStore 2.5(-SNAPSHOT)
We need changes from this PR https://github.com/geosolutions-it/MapStore2/pull/4665
that has been reverted. 

Now the scripts has been added, so we could re-do the PR

**Comment by tdipisa** [comment]
Even updating the GeoStore version to 1.5-SNAPSHOT, problems still occur setting thumbnails and details, Favourites does not seems to have problems.

As soon as you set a thumbnail or details, they are created and available in the UI but if you refresh the UI they are no longer available and the following request fails in DevTool:

**Thumbnail**
```
Request URL: https://dev.mapstore2.geo-solutions.it/mapstore/rest%2Fgeostore%2Fdata%2F18075%2Fraw%3Fdecode%3Ddatauri
Request Method: GET
Status Code: 404 Not Found
Remote Address: 164.132.80.72:443
```

**Details**
```
Request URL: https://dev.mapstore2.geo-solutions.it/mapstore/rest/geostore/data/null
Request Method: GET
Status Code: 404 Not Found
Remote Address: 164.132.80.72:443
```

**Comment by offtherailz** [comment]
A backport should not be needed because the API change for GeoStore is only on master.
