### ISSUE TITLE
Pluggable TOC to enable toolbar buttons

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#4719]
- [ ] Create `AddLayer`, `FilterLayer` (for query panel), plugins as well as the others and modify `TOC` to be also a `PluginContainer` that receives the buttons for that functionalities. The existing `AddGroup`, `FeatureGrid` and `LayerSettings` should render a button as well 
- [ ]  Query Panel becomes hidden dependency of `FilterLayer`, `FeatureEditor` and `WidgetBuilder`

**Comment by ElenaGallo** [comment]
A minor problem in second point is fixed with this [comment](https://github.com/geosolutions-it/MapStore2/issues/4774#issuecomment-577146525)
