### ISSUE TITLE
Components folder structure cleaning

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#472]
* buttons -> deprecated (we can implement any kind of button using HTML or react-bootstrap components, the current button components are not so useful)
 * Layers -> rename to TOC
 * Legend and BackgroundSwitcher -> move inside TOC
 * MeasureComponent, ScaleBox, Search -> move inside mapcontrols
 * menu -> deprecated (only used by the mobile viewer, should stay in the example / application components folder)
 * data: new folder, move QueryForm, template here
 * data/identify: move some components from misc here (FeatureInfoFormatSelector, PropertiesViewer) and create standard GetFeatureInfo and viewers implementation in the framework
 * misc/ApplyTemplate -> move in data/template

**Comment by tdipisa** [comment]
+1

**Comment by kappu72** [comment]
+1
