### ISSUE TITLE
Changing language the Tutorial doesn't work anymore

### ISSUE THREAD

**Issue by francoxyz** [geosolutions-it/MapStore2#4739]
## Description
No errors are reported in console

![tutorialxx](https://user-images.githubusercontent.com/54808782/72624460-4caba500-3947-11ea-8038-af63f2fe72ff.gif)

## How to reproduce
- Open mapstore
-  Open a random map
- Open burger menu
- Click on tutorial and verify that it's working
- Close tutorial
- Open buger menu
- Click on Settings
- Change language
- Close settings
- Open burger menu
- Click on tutorial

*Expected Result*
The tutorial should work

*Current Result*
The tutorial doesn't work

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@ElenaGallo I saw you put the accepted label for this, burt did test it in QA too? Moved back in test for now, please confirm.

**Comment by ElenaGallo** [comment]
no, I haven't tested this problem in QA. I move its in test
