### ISSUE TITLE
Problems applying thumbnail for dashboards

### ISSUE THREAD

**Issue by francoperversi** [geosolutions-it/MapStore2#4754]
## Description
Applying a thumbnail from homepage for the first time in a dashboard, the following error appears in console:
`mapstore2.js?59774502c1fb320dd959:1 GET https://qa.mapstore.geo-solutions.it/mapstore/rest/geostore/resources/resource/19341/attributes/thumbnail 404 (Not Found)`
As soon as i save again the dashboard without thumbnail, the default image gets darker

![thumb](https://user-images.githubusercontent.com/54808782/72807745-5a6b6e00-3c58-11ea-8bfc-bb3af489b878.gif)

## How to reproduce
- Open Mapstore
-  Login as admin
- Create a new dashboard
- Save it with only the name
- Search that dashboard in homepage
- Click on Edit properties for that dashboard
- Set a thumbnail and save
1) An error appears in console
- Open the edit properties window again
- Remove the thumbnail and save
2) The default thumbnail is darker than before

*Expected Result*
1) No error appears in console
2) The default thumbnail isn't changed

*Current Result*
1) An error appears in console
2) The default thumbnail is darker than before

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information
This Issue is present in DEV, QA and in the RELEASE (test done 21/01/2020)

**Comment by offtherailz** [comment]
The console error is due to a preventive check of thumbnail existence during setting it up. 
I'm going to sent a fix for the darken thubmnail

**Comment by ElenaGallo** [comment]
> The console error is due to a preventive check of thumbnail existence to clean up, if any),
> Second time it doesn't happen because the thumbnail attribute extists (or contains NODATA).
> 
> so it's ok. It's not an error but a desired behavior (you can not avoid browser logging http errors in console). We can improve it by getting all the attributes (the entry point should always return something ) to avoid a 404, anyway this is an improvement.
> I'm going to sent a fix for the darken thumbnail

@tdipisa can I open new issue for this improvement?
