### ISSUE TITLE
Adding and removing thumbnails creates problems

### ISSUE THREAD

**Issue by francoxyz** [geosolutions-it/MapStore2#4757]
## Description
Creating a new map or a new dashboard, in homepage when you add a thumbnail and you save, and than you remove the thumbnail and you save, some problems occours:
1. Changing existing details or adding new ones, it gets impossible to save and the changes don't persist, with no errors in console (only for maps)

![details](https://user-images.githubusercontent.com/54808782/72816061-e89b2080-3c67-11ea-8d03-8a3ec58ffa68.gif)

2. If you add a new permission rule  or you edit an existing one, and you click on the save button, the _Edit properties_ window doesn't close, but the changes are saved (for maps and for dashboards)

![permessi](https://user-images.githubusercontent.com/54808782/72816392-58111000-3c68-11ea-981f-cd7a4f08fe2e.gif)

## How to reproduce
- Open Mapstore
- Login as admin
- Create a new map/dashboard
- Saave it with only the name
- From homepage open edit properties
- add a thumbnail and save
- reopen edit properties
- remove the thumbnail and save
- reopen edit properties
- try to add some details and save (only for maps)
1) can't save details and the window doesn't close (only for maps)
- reopen edit properties
- add some permission and save
2) The edit properties window doesn't close

*Expected Result*
1) Details are saved and window closes
2) Edit properties window closes

*Current Result*
1) can't save details and the window doesn't close (only for maps)
2) The edit properties window doesn't close

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information
This issue involves DEV, QA and RELEASE mapstore istance (test done 21/01/2020)

This issue is one of the several issues opened in order to fix some bug in EDIT PROPERTIES window. The other more recent issues abut this window are: #4744, #4756, #4754, #4716, #4758

**Comment by offtherailz** [comment]
Going to close because:
- Dashboards works 
- Maps issue is a duplication of #3096
