### ISSUE TITLE
QA Docker image build is broken

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#4762]
The QA docker image is failing to build since December.
Is the QA docker image needed at all?

**Comment by tdipisa** [comment]
Yes it is needed.

**Comment by Gnafu** [comment]
The build job was not finding the correct artifact (mapstore.war)
I changes the config and restarted the build.
Status here:
http://build2.geo-solutions.it/job/MapStore2_DEV_Build/16/
