### ISSUE TITLE
Can't logout in LoginPlugin (undefined method)

### ISSUE THREAD

**Issue by make4711** [geosolutions-it/MapStore2#4765]
## Description
While testing the "/examples/login/" app,  i realized an issue on logout.
You can't logout in this example
In component `/web/client/components/security/UserMenu.jsx` we need additional checks.

## How to reproduce
- start app with `npm run examples`
- start app in browser
- type admin/admin in login dialog
- choose logout in usermenu

*Expected Result*
The user icon should be blue and only `login menu` should apper

*Current Result*

The user isn't logout

- [x] Not browser related

## Other useful information
In Component `/web/client/components/security/UserMenu.jsx` 
line 87 need an additional check and line 95 also.

If you want, i can make a pull request to solve this issue.

**Comment by ElenaGallo** [comment]
This issue is no longer valid, it can be closed.
