### ISSUE TITLE
Warning for unsupported browsers

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#4809]
## Description

Make the webapp able to intercept the unsupported browser type (eg. IE 11) before loading MS to redirect the user to a static page that contains a warning message, something similar to the following:

![browser_unsupported](https://user-images.githubusercontent.com/1280027/73277799-f104d580-41ea-11ea-8222-f2cd39a2b024.jpg)

**Comment by MV88** [comment]
My proposal is to add [this](https://github.com/lancedikson/bowser#filtering-browsers) lib that allows us to quickly filter browsers.

Detection will be made at the very top of the application and specifically  in the StandardApp component [here](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/app/StandardApp.jsx#L225)

Also the examples will be updated with new redirect functionality or with some mask

**Comment by MV88** [comment]
Another possibility is to detect browser familiy before running everything at index.html level

**Comment by tdipisa** [comment]
@MV88 @offtherailz if we can do that without adding a new library is better in my opinion. @offtherailz let me know your thoughts.
