### ISSUE TITLE
WMS/WMTS issues with mapproxy server

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#4810]
## Description
Our wms and wmts implementations have some issues with mapproxy services.
In particular:
 * style / styles parameters are mandatory, but mapstore do not include them if they are empty
 * we always use a png format for catalog added layers, also if the service is not compatible with it

## How to reproduce

-  Configure https://tiles.craig.fr/ortho/service (both as a WMS and WMTS service) in the catalog
- try to add some layers

*Expected Result*

Layers correctly work.

*Current Result*

Some errors are returned by mapproxy about style(s) parameter missing and wrong image format.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by mbarto** [comment]
Look at https://github.com/georchestra/mapstore2-georchestra/issues/108

**Comment by landryb** [comment]
I'll add to that issue a bit from my previous comment.. on a sidenote, i noticed the js was trying a `DescribeDomains` request type, which is AFAICT a geoserver vendor extension (not advertised in `GetCapabilities`), and might not be liked by remote servers...i know mapproxy replies with a 500 code in that case, sure mapproxy could be improved, but if loading a mapproxy layer in mapstore fills its logs with python tracebacks that's not going to be nice.

Could we improve interop here by only issuing the `DescribeDomains` request if we're sure the remote server supports it (ie checking for some vendor extension in `GetCapabilities`?)
