### ISSUE TITLE
Updating the TableWidget in the User Guide

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#4827]
## Description

The user guide must be updated in the Dashboard section with the connections between the Widgets and the TableWidget

*Documentation section involved*
- [x] User Guide
- [ ] Developer Guide

## Other useful information
The reference issue is  #4149

**Comment by francoperversi** [comment]
@tdipisa I provided a review that I already merged in the dedicated branch. You can do a last review in [HERE](https://mapstore.readthedocs.io/en/dashboard_guide/user-guide/connecting-widgets/)
