### ISSUE TITLE
Map with cql_filter are not correctly added to the Dashboard

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#4857]
## Description

cqlFilter is lost when a map is added in the dashboard

This does not allow me to test properly my fixes for #4674

## How to reproduce

- Open an empty dashboard
- add the map "POI - With cql filter

*Expected Result*

map applies cql_filter on *ny* layer

*Current Result*

it does not apply the cql_filter

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

note that cql filter is something similar to NAME like "*r*"

When the WIDGETS:INSERT action is dispatched the layer contains the cqlFilter
the sub sequent WIDGETS:UPDATE_PROPERTY does not contain it 

Pay attention that the sample map is manually customized, if you configure a map filtering the layer using the Filter Layer tool in TOC, it works.

**Comment by ElenaGallo** [comment]
This issue is no longer valid, it can be closed.
