### ISSUE TITLE
If no background is present, you can not add it

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#4866]
## Description
Expecially when you import WMC Templates, if no background is present, the background tool disappears so is not possible to add backgrounds.

To avoid this, if no backround layer is present in context, we should add empty background by default in "background" group.

**Comment by vlt1** [comment]
@offtherailz Currently, if no backgrounds are present in WMC, an empty one is added automatically. Is this issue still relevant?

**Comment by offtherailz** [comment]
I think no. I'll put it in test
