### ISSUE TITLE
Bug with Multidim extension URL conversion with particular URLs

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#4875]
## How to reproduce

-  Add this wms catalog to the "https://wms.eumetsat.int/geoserver/wms" (type WMS)
- add layer SOSI

*Expected Result*
Timeline shows

*Current Result*
Timeline is now shown

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information
The issue is in this replacement
https://github.com/geosolutions-it/MapStore2/blob/master/web/client/epics/dimension.js#L29

Because the CATALOG URL has 2 `/wms` in the url: 

https:/**/wms**.eumetsat.int/geoserver*/wms*

It replaces the first

**Comment by ElenaGallo** [comment]
It is no longer possible to open the URL attached above, Eumetsat has changed the address.
