### ISSUE TITLE
Unsaved changes also appear when not needed

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#4882]
## Description

When editing a map, the Unsaved Changes modal appears, after changing something (eg. the map zoom), even if the map has just been saved

![tutto subito](https://user-images.githubusercontent.com/56537133/74234778-eb6cbc80-4ccd-11ea-957c-940efdd676d2.gif)

## How to reproduce

- Open a map
- Add a layers
- Click on save
- Click on back to home page 

*Expected Result*

If the map has just been saved, the modal window is not displayed

*Current Result*

After saving the map, the modal window appears to ask if you want to leave without saving

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
this issue doesn't seems to affect QA. @tdpisa please can you confirm? In this case it can be changed of milestone, and it will not need a back-port.

**Comment by tdipisa** [comment]
@offtherailz you are right, moved to 2020.02.00 not backport is needed for this.
