### ISSUE TITLE
User Extensions panel covers the toolbar 

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#4884]
User Extensions panel covers the toolbar on the right (where there are zoom +/-, zoom to max extent, undo/redo ecc.. button)

**Comment by francoperversi** [comment]
@offtherailz also in Map Templates panel the problem needs to be fixed. Moreover, in Map Templates panel the resize cursor appears as soon as the cursor goes on the left border of the panel

**Comment by tdipisa** [comment]
@francoperversi this issue has been fixed with #4886. Please open a new issue in geOrchestra for what concerns your comment [here](https://github.com/geosolutions-it/MapStore2/issues/4884#issuecomment-585148966) and assing it to @offtherailz
