### ISSUE TITLE
Add support for not handled errors when method (PUT) is not allowed

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#4906]
## Description

This issue has been discovered in the project [MapStore2-C039](https://github.com/geosolutions-it/MapStore2-C039) because the method PUT is not supported and therefore it was causing an error when for example you were trying to create a resource (story) with a thumbnail.

## How to reproduce

- Open this [dev](https://devgeoweb.neftex.com/GeoStory/) instance (ask @mv88, or @mbarto how to login )
- enter a new story
- save it with a thumbnail

*Expected Result*

The story is saved and a message is shown saying that thumbnail has not been saved because of a problem server side

*Current Result*

The usual red error page appears.
the error in console is this one:

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

request that is not allowed on the deployed version
![image](https://user-images.githubusercontent.com/11991428/74724098-08f4d580-523c-11ea-9613-806da78c0700.png)

Error in console on deployed version
```
Invariant Violation: [React Intl] An `id` must be provided to format a message.
    at e.exports (https://devgeoweb.neftex.com/GeoStory/dist/MapStoreHalliburton.js?266742503b7f5e2af227:92:368851)
```

Error in console locally

```
xhr.js:160 PUT http://localhost:8081/rest/geostore/resources/resource/113/attributes/ 403 (Forbidden)

backend.js:6 [React Intl] Missing message: "Forbidden" for locale: "en-US" 
    in FormattedMessage (created by Message)
    in Message (created by Anonymous)
    in Anonymous (created by SaveModal)
    in SaveModal (created by withStateHandlers(withProps(SaveModal)))
    in withStateHandlers(withProps(SaveModal)) (created by withStateHandlers(withStateHandlers(withProps(SaveModal))))
    in withStateHandlers(withStateHandlers(withProps(SaveModal)))

backend.js:6 [React Intl] Cannot format message: "Forbidden", using message id as fallback. 
    in FormattedMessage (created by Message)
    in Message (created by Anonymous)
    in Anonymous (created by SaveModal)
    in SaveModal (created by withStateHandlers(withProps(SaveModal)))
    in withStateHandlers(withProps(SaveModal)) (created by withStateHandlers(withStateHandlers(withProps(SaveModal))))
    in withStateHandlers(withStateHandlers(withProps(SaveModal)))
```

The problem is in ErrorBox component that does not handle 403, and 405 errors

**Comment by offtherailz** [comment]
@MV88 I added the "blocked" label to avoid the testers to try without your test instance has been updated. Please handle the testing of this issue on your own

**Comment by MV88** [comment]
hi, do you mean after it is merged?

**Comment by tdipisa** [comment]
@MV88 @offtherailz I think that we only have merged a [PR on master](https://github.com/geosolutions-it/MapStore2/pull/4908) while this is in 2020.01.01 and a backport is still needed. Correct me if I'm wrong, in the meantime I move this in **Backport Needed** removing **Blocked**.
