### ISSUE TITLE
Contents - Map - Popups

### ISSUE THREAD

**Issue by kappu72** [geosolutions-it/MapStore2#4910]
@tdipisa commented on [Tue Feb 19 2019](https://github.com/geosolutions-it/MapStore2-C039/issues/52)

Actually MS has not popups. We need to design how to display data for clicked points. 

Investigation:

- [x] Evaluate possible solution to implement a Popup component as an alternative for the Identify tool (the Popup must be available for both OL and Leaflet). As an implementation suggestion it should be implemented as a support component like the DrawSupport and MeasurementSupport. Provide the possibility to have the popup as an alternative visualizzation of the Identify tool, this must be configured in plugin config.

Write a small document with the results of the investigation and the proposed solution.

Then:

- [ ] The identify tool needs to be available for layers/vector features in the map with a popup as the Identify tool currently does
- [ ] The identify can be activated by the Map Inline Editor to show or not the info popup if the user click on the map (by default disabled)

---

@ghost commented on [Mon Dec 02 2019](https://github.com/geosolutions-it/MapStore2-C039/issues/52#issuecomment-560400155)

Both tools (Openlayers and Leaflet) provides API for popup handling.  
 
Openlayers  provides API to create popup instance:
https://openlayers.org/en/latest/apidoc/module-ol_Overlay-Overlay.html
Overlay should be added via `addOverlay` method on map instance:
https://openlayers.org/en/latest/apidoc/module-ol_Map-Map.html#addOverlay
Example of working popup:
https://openlayers.org/en/latest/examples/popup.html?q=popup

In leaflet there is also specific API for create popup instance:
https://leafletjs.com/reference-1.6.0.html#popup
But in this case it can be provided via marker/map feature or adding as layer

Based on MapStore2 code main element of popup which will be displayed can be created as single component. It can be used in both solutions (OpenLayers and Leaflet). For adding support of popup it can be managed like DrawSupport or MeasurementSupport written separately for each library.

---

@tdipisa commented on [Mon Dec 02 2019](https://github.com/geosolutions-it/MapStore2-C039/issues/52#issuecomment-560413168)

@offtherailz can you please provide your opinion on the above comment?

---

@offtherailz commented on [Fri Dec 06 2019](https://github.com/geosolutions-it/MapStore2-C039/issues/52#issuecomment-562194584)

sure, this is more or less the thinked solution. I'd like to have a prototype of this <PopupSupport> so it can be used in our maps.
I'm writing here a draft of the tasks to support popups, taking into account that can be controlled internally or externally.

<BaseMap> component can accept the `popup` property, in addition that can be (an array of) object of this kind : 
```javascript
{
   "position": {}, // coordinates and crs
   "content": <ReactElement /> // this allows to properly add hadlers to this element to satisfy links actions and so on...
}
```
the popup should be shown when present as properties. Click on map can be (optionally) handled externally to produce the `popup` property.

## Implementation of Popup Support in OL/Leaflet
In `compontents/map/plugins/<openlayers>|<leaflet>` we should add a PopupSupport tool that handles popups, and/or a Popup component that handles one single popup (more or less how we do with Feature compoent). This should get the popup property and render it accordingly.

In case of Popup support: 
In BaseMap it can be passed as tool's option's (see getTool) or we could enhance getTool to pass also mapProperties to the tools and so get the new popup property, we will see during implementation what is the best option. 

Then about specific implementations:
### Openlayers
 there should be possible to render a div connected to the popup content in OL,(so called overlay) so, generating somehow a unique ID it should be easy to render the ReactComponent above and use it in the popup.

### Leaflet 

 In leaflet we have to explicitely call [setContent](https://leafletjs.com/reference-1.6.0.html#popup) that accepts an HTMLElements, so we could expect we can use ref to link the popup content

## Usage in GeoStory
the popups should be a temporary property (therefore not stored in the map) controlled by the Map Media. (other maps will control this property in different ways). 
This state has to be controllable from actions as temporary zoom events. See (TODO: add actions issue link) 

@kboczkowski-clurgo . Did you produced something during your investigation?

---

@mbarto commented on [Wed Feb 05 2020](https://github.com/geosolutions-it/MapStore2-C039/issues/52#issuecomment-582294019)

FYI: MapStore already has a layer to implement popups using the library functionality, at least for OpenLayers: https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/map/openlayers/plugins/OverlayLayer.js
If you are ever going to complete this one, you should consider using / improving it for this purpose, instead of rewriting something new

**Comment by ElenaGallo** [comment]
1_When a map, in Media Section, is setting on small size the Properties\html\text popup is not displayed correctly

![1](https://user-images.githubusercontent.com/56537133/76881278-35bafd80-6879-11ea-8bf2-e5ff50f783fc.JPG)

*How to reproduce*
- open a story
- add Media Section
- open a map
- click on Change Size
- click on Small
- click on Edit map configuration
- click on setting
- enable the Identify
- click on Save
- click on map

**Other useful information**
The same happens in the Media content of the Immersive section in all types of map sizes

2_On mobile, after closing the popup, an empty popup remains on the display.

![2](https://user-images.githubusercontent.com/56537133/76882323-c8a86780-687a-11ea-86a7-cad30c82894d.gif)
