### ISSUE TITLE
Import/export of WMC

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#4912]
## Description

https://github.com/georchestra/mapstore2-georchestra/issues/60

## Acceptance criteria

- https://github.com/georchestra/mapstore2-georchestra/issues/60

**Comment by francoperversi** [comment]
@vlt1 An example: exporting the following map in WMC:

![export](https://user-images.githubusercontent.com/54808782/75964473-90db1080-5ec7-11ea-8853-3bb559b10f0b.jpg)

If I import it in a map or in a context the result is the following:

![import](https://user-images.githubusercontent.com/54808782/75964552-aea87580-5ec7-11ea-8105-ea3e2af392cf.jpg)

In particular, the zoom is not set properly and the the background selector contains only an empty background

@tdipisa I noticed that the WMC export format is available only for maps and not for context, is that something chosen?

**Comment by tdipisa** [comment]
@francoperversi 

>@tdipisa I noticed that the WMC export format is available only for maps and not for context, is that something chosen?

WMC export should be present also for contexts, @offtherailz is there a missing configuration for that?

**Comment by offtherailz** [comment]
By default (without configuratin) now MapExport exposes only MapStore format.

MapStore is configured in localConfig,json to use also wmc. 

This configuration has not been copied in pluginConfig.json (that contains all the initial configurations for plugins), so you have to add it explicitly.

Try to put this in the MapExport plugin cfg in the UI.
```
"enabledFormats": ["mapstore2", "wmc"]
```
and it should work.

I see that it looks a little confusing...

If you want always to provide wmc, we may modify code to provide by default (without configuration) both formats and avoid to explicitly configure localConfig and/or plugin.

**Comment by vlt1** [comment]
@francoxyz @offtherailz unless the background is a WMS layer, it won't be present in an exported WMC context, as this format supports only WMS layers. Zoom is also not preserved, instead when importing WMC context, the map zooms to max extent.

**Comment by tdipisa** [comment]
@offtherailz and @vlt1 I cannot longer export maps in WMC, it looks like a regression intruduced in the last couple of days

@offtherailz the following sound like something to better clarify and review
>@francoxyz @offtherailz unless the background is a WMS layer, it won't be present in an exported WMC context, as this format supports only WMS layers. Zoom is also not preserved, instead when importing WMC context, the map zooms to max extent.

@offtherailz the WMC export option must be available by default **everywhere** for the export tool
>If you want always to provide wmc, we may modify code to provide by default (without configuration) both formats and avoid to explicitly configure localConfig and/or plugin.

**Comment by offtherailz** [comment]
I'll fix the regression this morning, so we can try replicate the issue notified.
@vlt1 Did you replicated the zoom issue in your local env ? Do you have a context that has this problem?
If so: There was a bounding box to export in WMC that should be re-used when imported. I didn't understand your comment about that. Can you explain better.

**Comment by vlt1** [comment]
@offtherailz I've said that the current zoom, when you export the map, is not preserved in WMC, instead on load, as you yourself requested, the map zooms to max extent. The example that @francoxyz posted, it seems like maxExtent and the zoom level that is present in the first image are different, but that is unclear. If indeed they are, then everything is working as intended and there is nothing to fix.

**Comment by offtherailz** [comment]
I tested and when exporting in mapstore2 format, the current bbox (Zoom) is used. 

In WMC the zoom doesn't exist. We should use the bbox to have the same effect (using bbox is a better choice in general, IMHO, because of different screen sizes possibilities).
Is it feasable @vlt1 ?

**Comment by ElenaGallo** [comment]
1_ Exporting in WMC format the server access pop-up appears but authentication is not required and the file is downloaded.
![WMC](https://user-images.githubusercontent.com/56537133/77309579-2dd9de00-6cfd-11ea-8b7e-6d45eccefef0.gif)

In console this error appears:
https://dev.mapstore2.geo-solutions.it/mapstore/proxy/?url=https%3A%2F%2F1maps.geo-solutions.it%2Fgeoserver%2Fs2cloudless%2Fs2cloudless%2Fwms%3Fservice%3DWMS%26version%3D1.3.0%26request%3DGetCapabilities 401 (Unauthorized)

*How to reproduce*
- Open a map/context
- Click on Export
- Export in WMC

2_After importing a WMC file, the default catalog services are no longer available and you cannot add a new one.

*How to reproduce*
-  Open new map/context
-  Import a WMC file
-  Click on Catalog

**Comment by tdipisa** [comment]
@ElenaGallo I think you have to better specify the steps to reproduce the two issues:
1. probably it happens only in maps with certains data?
2. please specify what happens and which is the error occurred.

**Comment by ElenaGallo** [comment]
@taba90 
1_ It happens with all the data available on gs-stable:
- https://gs-stable.geo-solutions.it/geoserver/csw
- https://gs-stable.geo-solutions.it/geoserver/wms
- https://gs-stable.geo-solutions.it/geoserver/gwc/service/wmts

2_ 
Importing a WMC [context_.zip](https://github.com/geosolutions-it/MapStore2/files/4370820/context_.zip), this is what is reported in the console:

> [DOM] Found 6 elements with non-unique id #inlineDateTime: (More info: https://goo.gl/9p2vKq)
 <input placeholder=​"DD" disabled type=​"text" id=​"inlineDateTime" class=​"form-control" value>​ 
 <input readonly placeholder=​"MM" disabled type=​"text" id=​"inlineDateTime" class=​"form-control" value>​ 
 <input placeholder=​"YYYY" type=​"text" id=​"inlineDateTime" class=​"form-control" value=​"2013">​ 
 <input placeholder=​"hh" disabled type=​"text" id=​"inlineDateTime" class=​"form-control" value>​ 
 <input placeholder=​"mm" disabled type=​"text" id=​"inlineDateTime" class=​"form-control" value>​ 
 <input placeholder=​"ss" disabled type=​"text" id=​"inlineDateTime" class=​"form-control" value>​

Opening a Catalog is no more possible serach gs-stable service and if you trye to add one this is what is reported in console:

> [DOM] Found 2 elements with non-unique id #title: (More info: https://goo.gl/9p2vKq) 
 <select id=​"title" class=​"form-control">​…​</select>​
 <input placeholder=​"inserisci un titolo" type=​"text" id=​"title" class=​"form-control" value style=​"text-overflow:​ ellipsis;​">

**Comment by vlt1** [comment]
> 1_ Exporting in WMC format the server access pop-up appears but authentication is not required and the file is downloaded.

Judging by the console error, authorization was required to perform GetCapabilities request on a particular layer. Currently if this request fails(as was the case here, since the authorization information was not provided and server returned 401 Unauthorized), then WMC exporting proceeds without this information. Capabilities are needed to extract Dimensions and Style information from the layer. If capabilities are not available this information will not be present in the resulting WMC file. @tdipisa if this behaviour needs to be changed, let it be known.

**Comment by ElenaGallo** [comment]
> 1_ Exporting in WMC format the server access pop-up appears but authentication is not required and the file is downloaded.

@vlt1 this point is no longer replicable because the map used in that case was a temporary map

**Comment by tdipisa** [comment]
@vlt1, considering the latest comment of @ElenaGallo, please proceed only with the fix for the point 2: as we agreed during the status meeting, also the catalog sources configured in the map context must be present in the WMC export.

**Comment by ElenaGallo** [comment]
@vlt1 The second poit still present on MS

> 2.1_After importing a WMC file, the default catalog services are no longer available  
> *How to reproduce
> -  Open new map/context
> -  Import a WMC file
> -  Click on Catalog

> 2.2 If you trye to add another service, this is what is reported in console:
> [DOM] Found 2 elements with non-unique id #title: (More info: https://goo.gl/9p2vKq) 
 <select id=​"title" class=​"form-control">​…​</select>​
 <input placeholder=​"inserisci un titolo" type=​"text" id=​"title" class=​"form-control" value style=​"text-overflow:​ ellipsis;​">

![catalogerror](https://user-images.githubusercontent.com/56537133/78338716-8fb70500-7593-11ea-9e50-805abcacf36a.gif)
