### ISSUE TITLE
Openlayers WMS issues

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#4921]
## Description

 * TILED param is not set to false on singleTile layers
 * empty params (e.g. styles) are removed on layer update

## How to reproduce

 -  configure a WMS layer using the catalog
 - switch to single tiled: you will see TILED=true in requests sent after the change
 - change the image format for the layer: requests will not have the styles parameter

**Comment by tdipisa** [comment]
@francoperversi can you please check if also QA is affected by this issue? thank you.

**Comment by francoperversi** [comment]
@tdipisa yes, also QA is affected

**Comment by tdipisa** [comment]
ook thank you @francoperversi. @mbarto I've changed the milestone to 2020.01.01 so also a backport will be needed to 2020.01.xx branch. Thank you.

**Comment by tdipisa** [comment]
@mbarto the PR on master has been merged, can you please provide a backport for this to 2020.01.xx?

**Comment by mbarto** [comment]
@tdipisa done
