### ISSUE TITLE
updating maps when context has been deleted

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#4927]
When remove a context all the maps created in this context should be updated.

There are two options: 
 - Delete all the maps
 - Update then to open in the default viewer 

When deleting a context, we can prompt the admin to do a choice or automatically do one of the above operations.
By default we can update the maps to the default viewer. 

This task requires this entry point on GeoStore to run: 

https://github.com/geosolutions-it/geostore/issues/205

**Comment by tdipisa** [comment]
Closed in favor of #5149
