### ISSUE TITLE
The position of the wizard close button should be changed.

### ISSUE THREAD

**Issue by gitcontributor** [geosolutions-it/MapStore2#4943]
## Description
https://github.com/georchestra/mapstore2-georchestra/issues/184

## How to reproduce
https://github.com/georchestra/mapstore2-georchestra/issues/184

**Comment by francoperversi** [comment]
@tdipisa the "Back" button in step 1 of the Wizard is unuseful. Instead of make it unselectable like it is, I was wondering if it's not better to simply remove it only for this step

![Back_btn](https://user-images.githubusercontent.com/54808782/75539162-18350980-5a1a-11ea-974b-baa684e724af.gif)
