### ISSUE TITLE
Introduce user session base support

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#4954]
## Description
Needed by https://github.com/georchestra/mapstore2-georchestra/issues/36.

We want the ability to periodically persist the user session as a geostore resource.
The session details will be configurable by project (no default):
 * session identifier
 * session content (state fragments to include)
 
## Acceptance criteria

- [x] epic creator to save the user session, triggered by a specific action
- [x] epic creator to schedule periodic persistence of user session
- [x] epic creator to load user session at request
- [x] epic creator to remove user session
- [x] actions and reducers to manage current user session status

**Comment by tdipisa** [comment]
We leave this in progress untill the georchestra work is completed (#36 and #20) then we will open a new issue for the enablement in MS (using probably localStorage).

**Comment by tdipisa** [comment]
@mbarto moved back in ready as reported [here](https://github.com/georchestra/mapstore2-georchestra/issues/36#issuecomment-625222957). Can you please provide the fix on Monday morning?
