### ISSUE TITLE
GeoStory on Mobile

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#4963]
## Description
Stories should be available and usable on small screens from mobile devices (view mode only)

Tasks:

- Disable editing mode in mobile 
- Update styles to be responsive on small, medium and large screens (width)
- Interactivity of background maps should be enable via user input 
  - background map is not interactive by default
  - add a toggle button on top left corner
  - on button click the map is full screen, overlay and interactive
  - on second button click the map is back to static background

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Improvement of LESS styles and responsiveness of the page:

**Comment by ElenaGallo** [comment]
@tdipisa @allyoucanmap 
I noticed that there are two different behaviors when a background map is closed after its position has been changed:

1_ 
when the user opens a background map, in a title section and in a immersive section with only one background map, and interacts with it, once closed the map is not centered in the initial position

**How to reproduce**
- Open Backgrund test story
- Open the background map
- zoom on it
- Closed it

*Current Result*
The map is not centered in the initial position

2_ 
the background maps in the immersive section return to the initial position if you switch from one to the other (ex Demo Observatories story), once closed a map and scroll down to othw

**How to reproduce**
- Open Demo Observatories story
- Scroll to immersive section with more than one background maps
- Open the first background map
- zoom on it
- Closed and the map is in the last modified position
- Scroll down
- Retourn to tha first map

*Current Result*
The map is centered in the initial position

**Comment by tdipisa** [comment]
@ElenaGallo this is a desired behavior for consecutive immersive contents to make them always logically consistent with the expected story flow for an immersive section.

**Comment by ElenaGallo** [comment]
@tdipisa ok for immersive contents (point 2) but for point 1, which is present in all sections and has a result different from point 2, is it also correct?

**Comment by tdipisa** [comment]
@ElenaGallo yes
