### ISSUE TITLE
Random build failures in themeload section

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#4970]
## Description
This failure https://build.geo-solutions.it/jenkins/job/MapStore2_Dev_Build/1528/console 
```
FAILED TESTS:
  StandardRouter
    ��� if we wait for theme onThemeLoaded is called when theme is loaded (slow: 2.001 secs)
      HeadlessChrome 78.0.3904 (Linux 0.0.0)
    Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

happened also on travis during a pull request.
![image_2020_03_03T16_14_57_333Z](https://user-images.githubusercontent.com/1279510/75798930-9aedf980-5d77-11ea-90fb-64358e765382.png)

## How to reproduce
-  Randomly happens on jenkins or travis

## Other useful information
 `onThemeLoaded` has been recently changed. @mbarto do you think this is related to your recent changes ? Can you figure out a way to avoid this problem?

**Comment by mbarto** [comment]
@offtherailz there is a setTimeout to wait for theme loading, currently set to 0, I will try to raise it a little bit

**Comment by offtherailz** [comment]
This issue can be tested verifying that travis and jenkins do not fail for this reason for some builds.
Let's wait a some days, then we can close it.
