### ISSUE TITLE
Implement generic tileprovider to support custom URL template

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/MapStore2#4983]
## Description
Implement a generic tileprovider to permit the configuration of background layers beyond those predefined inside [ConfigProviders.js](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/ConfigProvider.js).

The basic idea is to be able to configure a background selector using a custom URL template
E.g.:

```
{
	"type": "tileprovider",
	"title": "UNESCO Geodata",
	"provider": "custom",
	"url": "http://en.unesco.org/tiles/geodata/${z}/${x}/${y}.png",
	"group": "background"
}
```

**Comment by offtherailz** [comment]
This is fully covered by #5088
