### ISSUE TITLE
New map - logging out and logging in again background list changes

### ISSUE THREAD

**Issue by francoxyz** [geosolutions-it/MapStore2#4992]
## Description
Creating a new map, if I logout and I immediately login, in the background list I will find only a background available

![background](https://user-images.githubusercontent.com/54808782/76096078-ba7a6180-5fc5-11ea-85c0-3c589971ed75.gif)

## How to reproduce
-  Login as admin
- Create a new map
- verify that in background list several background are available
- logout and immediately login in the same session
- verify background list

*Expected Result*
background list shouldn't change

*Current Result*
in background list only a background is present

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by dsuren1** [comment]
Could you kindly retest this issue as it cannot be reproducible at the moment @ElenaGallo

**Comment by ElenaGallo** [comment]
This issue is no longer reproducible after the changes introduced [here](https://github.com/geosolutions-it/MapStore2/issues/4034#issue-476181113)
