### ISSUE TITLE
Missing translation in extension folder

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#5047]
## Description

Missing file blocks the application loading
![image](https://user-images.githubusercontent.com/19175505/77183598-dfdf9300-6ace-11ea-8162-6e40d16d05ab.png)

## How to reproduce

-  open dev

*Expected Result*

application should load

*Current Result*

application does not load

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
The problem is related to an issue found in the extension installation. The problem is under control with other issues (#5026 and https://github.com/georchestra/mapstore2-georchestra/issues/17)

**Comment by mbarto** [comment]
@tdipisa I would fix this one by making the translations loader more resilient, when you have multiple translations locations (main, project, extensions) it should block only if the translations is missing in the first location, the other ones should be optional
