### ISSUE TITLE
Small issue while saving a context

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#5062]
## Description

When a context is saved through the wizard, saving operation take some time and there is any spinner to notify that the save operation is in progress.

Furthermore, when the context is saved, the user is brought back to the context list page where the green popup message does not appear completely but cut and there is a strange blink of the page 

![image](https://user-images.githubusercontent.com/1280027/77449405-2e07d580-6df2-11ea-8beb-ff1f4590d409.png)

## How to reproduce

- Open the context manager
- Open a context in edit mode
- Navigate the wizard steps untill step 3 and save

*Expected Result*

A loading spinner appears when you click on Save to notify that the saving operation is in progress.
As soon as the context is saved the user is brought back to the context list page without any blink effect on that page and with the popup's message entirely visible on top-right.

*Current Result*

The saving spinner is missing and the green popup message is not entirely visible on top-right and there is a strange blink of the page.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by ElenaGallo** [comment]
@vlt1 Saved a new context the green popup's message is not visible on top-right.

**How to reproduce**
- Open the context manager
- Click on new context
- Navigate the wizard steps untill step 3 and save

*Current Result*

The saving spinner is visible but the green popup message is not  visible on top-right.

**Comment by tdipisa** [comment]
@ElenaGallo I've tested it again yestarday and I wasn't able to replicate the issue. Can you test it again please to see if also for you it now works?

**Comment by ElenaGallo** [comment]
@taba90 now it works properly, I close the issue.
