### ISSUE TITLE
Feature Attribute Popup - Floating Identify tool

### ISSUE THREAD

**Issue by gitcontributor** [geosolutions-it/MapStore2#5068]
## Description
https://github.com/georchestra/mapstore2-georchestra/issues/46

## How to reproduce
https://github.com/georchestra/mapstore2-georchestra/issues/46

**Comment by ElenaGallo** [comment]
@gitcontributor 

- [ ] Triggering hover over the map of the Identify tool does not have to be active if the user is using the measurement/annotation tool

*How to reproduce*
- Enable the hover for Identify tool
- Click on Burger Menu
- Click in Annotatotion
- Click on +
- click on Add geometry
- click on Marker
- click on map (wait a few seconds)

*Current Result*
Waiting a few seconds on the clicked point the popup opens and the new marker panel closes

- [ ] If the trigger hover over the map is activated, the identify marker is visible by clickung on the map 

![identify marker](https://user-images.githubusercontent.com/56537133/80380035-42cb0380-889f-11ea-8d54-2a36928469a1.gif)

*How to reproduce*
- Enable the hover for Identify tool
- Click on a map

*Current Result*
The identify marker appears

- [ ] If the mouse point is too close in the menu bar, sidebar, toc, burger menu) the pop-up that opens is not completely visible

![NOVISIBLE](https://user-images.githubusercontent.com/56537133/80380048-478fb780-889f-11ea-9d8e-14eb79ba944b.gif)

*How to reproduce*
- Enable the hover for Identify tool
- Hover over the map near same tool

*Current Result*
The identify popup is not completely visible
