### ISSUE TITLE
Improve domain sharding support in catalog WMS configuration

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#5072]
## Description

 * [ ] fix configuration of wfs url for search services when domain sharding is used
## How to reproduce

-  configure a WMS service with multiple urls (comma separated)
- add a layer from the service
- open the TOC and select the new layer
- FeatureEditor button is not available

*Expected Result*

FeatureEditor button should be available

*Current Result*

FeatureEditor button is not available

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by ElenaGallo** [comment]
@mbarto The layer in the map reports an error by adding layers from the created service (with two URLs), as follows:
![layererror](https://user-images.githubusercontent.com/56537133/78343395-102d3400-759b-11ea-9990-3f146c1160f3.JPG)

The following error is reported in console:

> https://demo.geo-solutions.it/geoserver/wms,%20https://gs-stable.geo-solutions.it/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=spearfish&STYLES=&SRS=EPSG%3A3857&CRS=EPSG%3A3857&TILED=true&authkey=d938b3da-11fe-413b-846b-c24bba615407&WIDTH=256&HEIGHT=256&BBOX=-11603752.389916036%2C5557277.704445455%2C-11584184.510675032%2C5576845.583686461

**Comment by ElenaGallo** [comment]
@mbarto The layer in the map reports an error by adding layers from the created service (with two URLs).
![wmc_error](https://user-images.githubusercontent.com/56537133/79235406-d8ac6a80-7e6b-11ea-8401-94dee33b61f4.JPG)


The following error is reported in console:

> Cross-Origin Read Blocking (CORB) blocked cross-origin response https://demo.geo-solutions.it/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=gs%3Atasmania_roads&STYLES=&SRS=EPSG%3A3857&CRS=EPSG%3A3857&TILED=true&authkey=7a0d4c79-3089-4839-a052-5322b434dd28&WIDTH=256&HEIGHT=256&BBOX=15967389.460660178%2C-5322463.153553393%2C16280475.52851626%2C-5009377.085697311 with MIME type text/xml. See https://www.chromestatus.com/feature/5629709824032768 for more details.

**Comment by mbarto** [comment]
The error you get is because you configured two servers that are not two names of the same server,
demo.geo-solutions.it is not the same as gs-stable.geo-solutions.it, so you get this error:

Could not find layer gs:tasmania_roads
