### ISSUE TITLE
Layer properties for other groups in map widget causes crash

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#5075]
## Description

There is a problems with maps that have groups in the wizard (dashboard page)

## How to reproduce

-  Open a new dashboard or 
-  Add a widget map that has some other groups other than Default
-  while adding it, when you have the TOC, select one layer that is not under Default group
- open layer properties

*Expected Result*

to see layer properties

*Current Result*

crash 

because of [withSelectedNode.js](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/widgets/builder/wizard/map/enhancers/withSelectedNode.js#L13) is returning null
and in [nodeEditor.js](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/widgets/builder/wizard/map/enhancers/nodeEditor.js#L70) it tries to do a selectedNode.nodes 

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

[this]( https://mappe.comune.genova.it/MapStore2/#/dashboard/1000002176) dashboard in genova has this problem

**Comment by ElenaGallo** [comment]
@dsuren1 
The group name displayed in the dashboard is not the same as the one entered on the map.

On map:
![maptest](https://user-images.githubusercontent.com/56537133/77906148-c0dbc080-7287-11ea-9a46-c02ea3b43541.JPG)

On dashborad:
![dash](https://user-images.githubusercontent.com/56537133/77906165-c89b6500-7287-11ea-82c1-06efd919d41f.JPG)

**Comment by dsuren1** [comment]
Hi @ElenaGallo 
#5084  A separate issue has been created and tracked separately

**Comment by offtherailz** [comment]
Yes @ElenaGallo , the issue of group naming is a different one. 
This is a crash when try to edit layer properties from a layer in a group different from default in dashboard's map widget wizard.

The fix to the bug you said will be fixed very soon in the day. I move this issue in test again
