### ISSUE TITLE
Maps and web pages media inside columns or paragraph need to change height size instead of width size

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#5083]
## Description

These media should have a width equal to 100% and change the height inside columns or paragraphs content.
The options should be: `LG`. `MD` or `SM`.
We should use the same size button and apply a style targeting the height.
Note: Remove align button also for these media.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features

**Comment by ElenaGallo** [comment]
The Italian tooltip for  the Change Size button is 'Cambia Larghezza' instead of 'Cambia Lunghezza' o 'Cambia Dimensioni'.

![tooltip IT](https://user-images.githubusercontent.com/56537133/79475521-10501980-8008-11ea-9ea5-50130feb0ad7.JPG)

**Comment by tdipisa** [comment]
@ElenaGallo please provide a PR for this ("Cambia Dimensione") and close the issue if it is working as expected.
