### ISSUE TITLE
Show Layer Metadata - Layer metadata

### ISSUE THREAD

**Issue by gitcontributor** [geosolutions-it/MapStore2#5090]
## Description
https://github.com/georchestra/mapstore2-georchestra/issues/50

## How to reproduce
https://github.com/georchestra/mapstore2-georchestra/issues/50

**Comment by tdipisa** [comment]
@vlt1 moving it in ready. As specified in the original issue description

>Also a link to the original metadata catalog page will be included in the Layer Metadata modal.
