### ISSUE TITLE
Example MapStore2 Viewer does not start

### ISSUE THREAD

**Issue by justb4** [geosolutions-it/MapStore2#511]
The viewer app:
http://mapstore2.geo-solutions.it/mapstore/examples/viewer/ gives a blank page
as the file http://mapstore2.geo-solutions.it/mapstore/dist/viewer.js cannot be found (404).
btw: Great work you're doing on a NG JS-mapping framework!

**Comment by mbarto** [comment]
Hi Just,

the viewer has been integrated with the homepage in latest releases, so the link to the viewer example does not exist anymore.
To access the viewer page you can now use this link: http://mapstore2.geo-solutions.it/mapstore/#/viewer/leaflet/0

**Comment by justb4** [comment]
Should have mentioned the page: on the Wiki: https://github.com/geosolutions-it/MapStore2/wiki the link http://mapstore2.geo-solutions.it/mapstore/examples/viewer/ is still there as the Viewer link.

**Comment by mbarto** [comment]
Thanks.  I fixed the link to point to the new application,
