### ISSUE TITLE
Tooltips on map widget TOC

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#5111]
## Description

On Map Widget TOC the tooltips is not activated on layers

## How to reproduce

- Open a new dashboard
- Click on Map Widget
- Search Meteorite Landings
- Click on Use this map
- Hover over the layers

*Expected Result*

The layers' tooltips are visible when hover oven the layers as follows:
![dash2](https://user-images.githubusercontent.com/56537133/78162131-b74c8700-7446-11ea-87a8-0ab43cb0973e.gif)

*Current Result*

The tooltips are not activated on layers 

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by MuhweziDeo** [comment]
Hello @ElenaGallo and @tdipisa. I have tested this in dev and cannot see how the tooltips are activated on hover in layer selector in the dashboard section. Please confirm this on your end.

**Comment by tdipisa** [comment]
@MuhweziDeo tooltips are not visualized in the TOC for dashboards if you hover the mouse over the layer card.
![Immagine](https://user-images.githubusercontent.com/1280027/111662455-38e02500-8810-11eb-9121-fef321ed5863.png)

Tooltips should be visualized instead as it happens in TOC for the map viewer.

![image](https://user-images.githubusercontent.com/1280027/111662942-a55b2400-8810-11eb-9f33-7c0b18155d33.png)

**Comment by MuhweziDeo** [comment]
thanks Understood
