### ISSUE TITLE
Timeline mapsync error if projection not supported

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#5115]
## How to reproduce
-  Add a layer with time dimension and with data CRS not defined in MapStore
- toggle map sync

*Expected Result*
It works or at least it triggers a notification, if something get wrong.

*Current Result*
The sync doesn't work. In console you have an error like this: 
![image](https://user-images.githubusercontent.com/1279510/78238747-37bdc700-74dd-11ea-9ae9-28de57ecbd95.png)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information
Debugging in local, looks like this line
https://github.com/geosolutions-it/MapStore2/blob/d6e1c5be80117b0561fabf80d1927925b7f6a91a/web/client/utils/TimeUtils.js#L237 
asks for the property `@version` but the property is inside "version" attribute. We didn't have any errors until the projection of the original data is supported

**Comment by offtherailz** [comment]
There is an indirect way to verify that this tool system is now active:

Verify that, activating on timeline the "mapSync tool" and zooming or panning the map, you will see the request with the following parameter: 
bbox: -20138855.216121837,1386487.7542791336,-15533065.639770256,3717511.3688638685**,EPSG:3857**
![image](https://user-images.githubusercontent.com/1279510/78645632-1df2fa00-78b8-11ea-8859-b464095f9c43.png)


You can verify (on QA, where the bug still exist) that old request contain
bbox: 120.98724843750323,-54.8592929497037,286.48529531250324,17.588928776623273

(without the epsg at the end)

![image](https://user-images.githubusercontent.com/1279510/78645562-00259500-78b8-11ea-8fa3-fc9735acd589.png)

**Comment by ElenaGallo** [comment]
@offtherailz on DEV, the tool does not seem active yet.

![epsg-error](https://user-images.githubusercontent.com/56537133/78649130-4fba8f80-78bd-11ea-8ea4-bb1aa76080c7.JPG)

**Comment by offtherailz** [comment]
I tried it right now on dev and it works for me. Maybe it was not deployed yet.
@ElenaGallo can you please re-test.
