### ISSUE TITLE
Improve extensions upload UI

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#5131]
## Description

Look here: https://github.com/georchestra/mapstore2-georchestra/issues/197

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by chiaracurcio** [comment]
note that one of the two buttons in the bottom right corner si called 'Close' and not 'Cancel'

**Comment by mbarto** [comment]
@chiaracurcio @offtherailz asked me to change Cancel into Close

**Comment by chiaracurcio** [comment]
thanks for update me

**Comment by chiaracurcio** [comment]
- only using Firefox (v. 75.0) and only testing the warning icon for the not valid uploaded extension i note that the message appearing in the pop-up not list the corresponding occurred error and has not been  correctly translated (language: english):

![err](https://user-images.githubusercontent.com/33256901/79572547-6cc14080-80bd-11ea-8c3a-57ce184204c3.png)
rightly using Explorer ands Chrome you have this correct message:
![-](https://user-images.githubusercontent.com/33256901/79572811-e0634d80-80bd-11ea-95c1-3b2f85f37298.png)

- using Chrome and Explorer and setting the language from english to others language there is one other error in the same message pop-up: it has not been  correctly translated to the correct language used.
![--](https://user-images.githubusercontent.com/33256901/79573342-caa25800-80be-11ea-8b70-870bba54afae.png)

**Comment by ElenaGallo** [comment]
> 5 - There must be two buttons in the bottom right corner: Cancel and Install
 Clicking on Cancel a confirmation dialog appear so the user can discard the installation or not
 Clicking on Install all the uploaded extensions will be installed

@mbarto   Clicking Cancel a confirmation dialog -to cancel the installation or not-  does not appear

*How to reproduce*
- Cllick on Add an extension on the 3 step of the wizard
- D&d a plugin
- Click on Close

*Current result*
The popup closes without closing confirmation

**Comment by ElenaGallo** [comment]
@mbarto  The problem described in this [comment](https://github.com/geosolutions-it/MapStore2/issues/5131#issuecomment-621313172) is still present on MS

**Comment by mbarto** [comment]
@ElenaGallo @tdipisa I did not fix that, not sure if having a confirmation dialog for closing is useful or just one more click for the user

**Comment by tdipisa** [comment]
@mbarto we can leave it as it is, @ElenaGallo close this please if other stuff are working properly.
