### ISSUE TITLE
Exported measurements issues with import/styiling

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#5138]
## Description
If you export measures and re-import, the styler is shown but the styles are not applied.

## How to reproduce

- Open the measurement tool and create a measure
- Export as GeoJSON
- Close measure tool 
- Open Import tool
- Import the just exported json
- Apply the style

*Expected Result*
The style is applied (or the styler is not shown, if it was exported as annotation
*Current Result*
The style is not applied.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
Just as reference (missing the stage of this solution) was implemented in #5399

**Comment by MuhweziDeo** [comment]
Hi @MV88 I just want to confirm if to check if one of the `features.style` has a value. Incase of an array the length should be greater than 1 and incase of an object it should have atleast one item. Does the the `feature.type` matter in any way.

**Comment by MuhweziDeo** [comment]
Hi, @MV88 @tdipisa @offtherailz. does the design below work. If not do have any recommendations.

![Screenshot 2021-03-17 at 16.10.26.png](https://images.zenhubusercontent.com/60350ba854742f543a9fa5ff/05c12226-3db1-40da-8a12-301c7ffcc360)

**Comment by MV88** [comment]
> Hi @MV88 I just want to confirm if to check if one of the `feature.style` has a value. Incase of` feature.style` of an array the length should be greater than 1 and in the case of an object, it should have at least one item. Does the `feature. type` matter in any way?

by has a value it means  
- feature.style.length > 0 if is an array
- !lodash.isEmpty(feature.style) if is not an array

for the message please change it to "This layer has already a style defined and is not possible to customize it"
