### ISSUE TITLE
Add apply button to coordinate editor

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#5144]
What is the current behavior?
geosolutions-it/austrocontrol-C125#143

What is the new behavior?
geosolutions-it/austrocontrol-C125#143

**Comment by ElenaGallo** [comment]
Pressing Enter is not possible to change North/South for Latitude or East/West for Longitude in the aeronautical coordinates 
![nord-sud](https://user-images.githubusercontent.com/56537133/79468704-8b610200-7fff-11ea-838a-1dd20cc7ff8c.gif)

**Comment by dsuren1** [comment]
@ElenaGallo The behavior of the select field when hitting enter will open the drop-down menu as this is the select field's default behavior and hence overriding this behavior will not result in an appropriate user experience. Hitting 'enter' to perform apply operation is valid only for the input fields. Thanks!

**Comment by tdipisa** [comment]
@ElenaGallo 
I agree with @dsuren1, this isn't an issue, we can close if the other things here are properly working.
