### ISSUE TITLE
Minor fixes to Search tool

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#5166]
## Description
- [x] Placeholder doesn't show anymore 
2020.01.01
![image](https://user-images.githubusercontent.com/1279510/79869544-cf7a4b00-83e1-11ea-93e9-3d8185f57844.png)
2020.02.00
![image](https://user-images.githubusercontent.com/1279510/79869583-e325b180-83e1-11ea-99ec-b7dd8576feab.png)

- [x] componentDidMount of search pluginis called frequently, triggering the action updateResultsStyle on everyAction.
![image](https://user-images.githubusercontent.com/1279510/79869809-41eb2b00-83e2-11ea-9d04-47ca7aa62f85.png)

 
## How to reproduce
-  open a map and  open dev tools in debug mode
- Interact with the map to see this continuous triggering of this action.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@offtherailz it seems working now, can we close this?

**Comment by offtherailz** [comment]
Yes, it is a duplicate of https://github.com/geosolutions-it/MapStore2/issues/5200
