### ISSUE TITLE
GeoStory Contents - Video - Component

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#5173]
## Description

Add video content for GeoStory

- [ ] Video player should display controls related to the provider (File, Youtube, ...)
- [ ] Video settings should contain: Thumbnail, Source (required), Title (required), Description, Credits and Autoplay Toggle.
- [ ] Thumbnail should be generated from the source video when possible. They could be issue while generating a thumbnail due to CORS so MapStore should provide a thumbnail placeholder and the manual upload of the thumbnail. Verify external provider such as Youtube for thumbnail support (*).
- [ ] When possible the thumbnail should be resized to 640px x 360px and saved in base64 inside the story JSON (MapStore should verify that the generated thumbnail has a limited size ~100 kb max). 
- [ ] Thumbnail should be centered in the video content and reach the maximum size of 640px x auto
- [ ] Verify support of video/audio provider of `react-player`
- [ ] Video should stop when not in view
- [ ] Autoplay should be activete once per session, if the user stops the video or scroll down to the story it should not be played again when the video is in view

(*) we could create a thumbnail from youtube using the standard structure of a thumbnail url

eg: `http://img.youtube.com/vi/${youtubeId}/sddefault.jpg`

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features

**Comment by ElenaGallo** [comment]
@allyoucanmap here are some comments after testing this issue:

- [ ] Adding a background video in the Immersive section and aligning it in the center, the Change size button does not work properly

*How to reproduce*
- Open this story
- Click on Change Size for the background video in the Immersive section

*Current Result*
Is not possible cahnage the size for the background video

- [ ] The first opening of the Multimedia Editor in the Video section does not present an initial description

*How to reproduce*
- Open a new story 
- Click on change Media source
- Switch on Video tab

*Current Result* 
There is no initial description as already happens for maps, as follows:
![description_first](https://user-images.githubusercontent.com/56537133/82224168-d4b8b000-9923-11ea-9682-04c1da3f45d6.JPG)

**Comment by allyoucanmap** [comment]
@ElenaGallo @tdipisa this issues should be fixed with this PR https://github.com/geosolutions-it/MapStore2/pull/5294
