### ISSUE TITLE
Add true bearing to measure tool

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#5180]
## Description
- Adjust strings formats and localization
- Support different display format or bearing, configurable in localConfig.json (“default” vs “ISO 19018”)

Adding to "cfg" of the Measure plugin ( in a context) this:
```
"defaultOptions": {
    "trueBearing": {
        "measureTrueBearing": true,
       "fractionDigits": 2
       }
}
```
The format of the bearing will result thanged as for the specs, and the label of the button "bearing" will indicate "true bearing"

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Other useful information
ISO specs
https://www.sis.se/api/document/preview/905247/

**Comment by ElenaGallo** [comment]
```
"defaultOptions": {
    "trueBearing": {
        "measureTrueBearing": true,
       "fractionDigits": 2
       }
}
```

@dsuren1 The above configuration has not been added to the "cfg" of the Measure plug-in (in a third step of the context wizard)

![measure_cfg](https://user-images.githubusercontent.com/56537133/80396697-4f5a5680-88b5-11ea-8369-3c33bc0aee01.JPG)

**Comment by offtherailz** [comment]
@ElenaGallo This configuration should be added only in customer's installation. By default MapStore should continue to use the default one (without configuration).
Make you sure only that adding this configuration to a specific context works.

```
"cfg": {
"defaultOptions": {
    "trueBearing": {
        "measureTrueBearing": true,
       "fractionDigits": 2
       }
}
}
