### ISSUE TITLE
Allow switch to edit directly from identify tool

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#5185]
## Description
As an admin user I want to use the identify tool and switch directly editing the selected features.

# Acceptance criteria
 - If allowed, the admin user should see an edit button on getFeatureInfo tool, that allows to open the attribute table in edit mode. The attribute table is filtered on the specific point clicked. 

Take into account requirement in original issue https://github.com/georchestra/mapstore2-georchestra/issues/45 and discussion in PR

**Comment by tdipisa** [comment]
@vlt1 I've moved it back in ready because I've just noticed that if you choose an identify format other than HTML or TEXT, the edit icon does not appear in the identify panel:

![image](https://user-images.githubusercontent.com/1280027/80397220-1b336580-88b6-11ea-9c04-2c9491e68f89.png)

**Comment by ElenaGallo** [comment]
@vlt1 here are some observations: 
* the second point of this [comment](https://github.com/geosolutions-it/MapStore2/pull/5167#pullrequestreview-398846476) is : 
> When user clear the geometry filter using the button, it should be de-activated. A second click looks hard to understand, to me. Instead is great that the user can change the selection continuously

*Current Result*
for now the user cannot continuously change the selection because the second click is necessary.

* the third point of this [comment](https://github.com/geosolutions-it/MapStore2/pull/5167#pullrequestreview-398846476) is : 
>when the user start editing one field or the geometry the filter functionality should be deacivated and the button disabled or clicking on the map can cause UI inconsistency (the map is filtered by ID).

*Current Result*
when the user start editing one field the filter functionality is not deacivated

**Comment by offtherailz** [comment]
@ElenaGallo  about the deactivation I see the expected behaviour: 
- When the tool is active, I can click on the map here and there selecting the features
- When I reset (by clicking on the (x) , the filter click is deactivated and clicking on map causes normal feature info (if you are not in edit mode).

about the second point you're right. The tool disables only when you edit geometry, not when you edit an attribute field. Good catch

**Comment by tdipisa** [comment]
@vlt1 all is ok for us about the point 1 in [this comment](https://github.com/geosolutions-it/MapStore2/issues/5185#issuecomment-623941020)

Please provide a fix only for the second point as also reported by @offtherailz in the [above comment](https://github.com/geosolutions-it/MapStore2/issues/5185#issuecomment-623955832)

>about the second point you're right. The tool disables only when you edit geometry, not when you edit an attribute field. Good catch. We should fix this @vlt1
