### ISSUE TITLE
Add Feature Info and Leaflet support to WFS layer

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#5220]
## Description
We need information on map click also for WFS layer, and finalize support in leaflet layers. Contextually we can complete some additional task for stability.

## Acceptance criteria

Improvements for WFS layer: 
 - [ ] Feature Info
 - [ ] Support for leaflet
 - [ ] add maxFeatures or other types of control to limit the download / rendering of too big data.
 - [ ] Improve loading and error handling

## Other useful information
This completes https://github.com/georchestra/mapstore2-georchestra/issues/30

**Comment by ElenaGallo** [comment]
@offtherailz here some observation after testing this issue: 

- [ ] Changing the coordinate in the coordinate editor the layer informations does not change accordinatly 
![coordin](https://user-images.githubusercontent.com/56537133/81705130-f969df00-946e-11ea-91ff-131b931b18eb.gif)

*How to reproduce*

- Open a WFS layer in a map
- Click on an feature 
- Click on Show Coordinate editor
- Change coordinate


- [ ] By changing the format to TEXT or HTML, GetFeatureInfo remains with the PROPERTIES format. 

*How to reproduce*

- Open a WFS layer in a map
- Click on Burger Menu
- Click on Settings
- Change format to HTML
- Click on an feature 

*Current Result*

The GFI format is PROPERTIES

**Comment by offtherailz** [comment]
The second point is not feasable, becuase the WFS feature info is an emulation and the real format is only in properties format from vector data (as well as local shape files imported).
