### ISSUE TITLE
GeoStory Tutorial

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#5226]
## Description

refer to https://github.com/geosolutions-it/MapStore2-C039/issues/167

The existing Tutorial tool in MapStore must be improved also for GeoStory.
We need to include the main functionalities for the edit mode.

## Acceptance criteria

- [ ] Overview in view mode
  - [ ] intro
  - [ ] header
  - [ ] navigation bar { edit button - nav items - title & logo }
  - [ ] content container
as next step (if logged as admin) it will go in edit mode
- [ ] over view in edit mode edit mode
  - [ ] sidebar (each element has icon, zoom drag drop)
  - [ ] toolbar in sidebar ( list of buttons explained)
  - [ ] section toolbar ( list of buttons explained, if present)
  - [ ] content toolbar 
  - [ ] add new content toolbar
  - [ ] media editor image tab and map

**Comment by ElenaGallo** [comment]
@MV88 here some observations:

- [ ] If the user has only view permission, the tutorial does not have to show the edit mode
![tutorial1](https://user-images.githubusercontent.com/56537133/81553591-aa944a80-9385-11ea-99ff-77ab65af73ca.gif)

**How to reproduce**
- Open Mapstore
- Open [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/geostory/11555) story
- Show the Tutorial
 
- [ ] If the User had the edit permission the tutorial show first the view mode Story Content popup over the Story Content in edit mode and then the Story Content popup rigth. 

**How to reproduce**
- Open MapStore
- Login as admin
- Open new story
- Navigate the Tutorial

*Current result*
View mode Story Content popup over the Story Content in edit mode
![1](https://user-images.githubusercontent.com/56537133/81553567-a0724c00-9385-11ea-9a6a-14d0e1ba6dc1.JPG)

*Expected result*
 Story Content popup in edit mode
![2](https://user-images.githubusercontent.com/56537133/81553580-a405d300-9385-11ea-8771-ab40e41179db.JPG)

- [ ] By finishing the tutorial, the Media Editor popup remains open in the story
![tutorial2](https://user-images.githubusercontent.com/56537133/81554042-62c1f300-9386-11ea-96d5-2bf8fbaa125c.gif)

**How to Reproduce**
-Open MapStore
- Login as admin
- Open new story
- Navigate the tutorial until the end

**Comment by tdipisa** [comment]
@MV88 also some important additional reviews are needed here. I will report back them asap.

**Comment by tdipisa** [comment]
@MV88, following up our call today, please see my comments below:

- I would not like to open automatically the edit mode to continue the tutorial there if I'm in veiw mode: the tutorial for the edit mode should starts as soon the story editor is opened

- I would like to prevent situations where, if I close the tutorial somehow, the Media Editor or the story settings remain open

- I would like to enrich a bit your descriptions by including also images of sections toolbars in the related tutorial step with a brief description of each button. We should find the right compromise between tutorial usability and user guide: as soon the user guide will be available in master, we could also include some links to it to allow the user to go through some details.

- You can ingore the point 2 in the [above comment](https://github.com/geosolutions-it/MapStore2/issues/5226#issuecomment-626631777)

**Comment by ElenaGallo** [comment]
@MV88 On a new story in view mode, the tutorial reported some steps of the edit mode

*How to reprodue*

- Open MapStore
- Login as admin
- Open new story
- Swith to View Mode
- Open the Tutorial
- Navigate the tutorial

*Current Result*
There are the Story Content and the Add New Content steps, and there are missing the Navigation Bar steps


On an existing story in edit mode, some steps are missing in the tutorial

*How to reprodue*

- Open MapStore
- Login as admin
- Open [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/geostory/11555) story
- Swith to Edit Mode
- Open the Tutorial
- Navigate the tutorial

*Current Result*
The Side Bar steps are missing on the tutorial

**Comment by ElenaGallo** [comment]
@MV88 The link in the Media Editor step is broken.
![link rotto](https://user-images.githubusercontent.com/56537133/84360031-c16ace80-abc9-11ea-90f0-eddf7f7c1a3a.JPG)
