### ISSUE TITLE
Print map preview with scale selector enabled does not set initial zoom correctly

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#5227]
## Description

The initial zoom is always the smallest scale (e.g. 1:500).
Needed by https://github.com/georchestra/mapstore2-georchestra/issues/54

## How to reproduce

-  enable fixed scales and preview scalebox selector in the print plugin

```javascript
           {
              "name": "Print",
              "cfg": {
                "useFixedScales": true,
                "mapPreviewOptions": {
                  "enableScalebox": true
                }
              }
            }
```
- open a map and try to print it

*Expected Result*

The selected preview scale is similar to the actual map scale

*Current Result*

The selected scale is always the min available from the server (e.g. 1:500)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by ElenaGallo** [comment]
@mbarto 
* A Refresh button appears but it does not work
![refresh](https://user-images.githubusercontent.com/56537133/81179755-603c5380-8faa-11ea-9887-27abb62004dc.JPG)


* Opens the context for the second time the zoom print preview is not on the smallest scale (1:500)

*How to reproduce*
- open a context with print configuration above
- click on print
- close the context
- open the context
- click on print

*Current Result*
the scale preview is not the smallest

**Comment by tdipisa** [comment]
@ElenaGallo 

For the first point:

>A Refresh button appears but it does not work

If you enable the above configuration for the print plugin you have round scales available so you can now switch from one to another: the button is useful to reset the scale in the print map preview to the initial value

For the second point:

>Opens the context for the second time the zoom print preview is not on the smallest scale (1:500)

Probably it is a typo, perhaps @mbarto meant 1:500**0**. @mbarto can you confirm this?

@mbarto maybe a tooltip is useful for that button to better understand it

**Comment by mbarto** [comment]
@ElenaGallo I don't understand what you expect from the refresh button. What it does is restoring the map scale to the one more similar to the scale of the main map. Are you seeing something different?

**Comment by ElenaGallo** [comment]
@mbarto @tdipisa Thx for the update, I thought the update button was needed to restore the preview to the first default preview (1:500).  The button works properly.
