### ISSUE TITLE
Can not add WMS background in WGS84

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#5229]
## Description
When you have a map in WGS84, adding a background shows an error:
![image](https://user-images.githubusercontent.com/1279510/81160586-8baf4600-8f8a-11ea-8710-e8a522d62282.png)

It works with CSW or WMTS catalogs.

## How to reproduce
-  Login as admin (to show crs selector)
-  create a new map and switch to WGS84
- Try to add a new background from WMS service (tested with https://gs-stable.geo-solutions.it/geoserver/wms)

*Expected Result*
The layer is added if the CRS is supported

*Current Result*
An error tells the CRS is not compatible

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
I noticed that 4326 is not published on SRS List in WMS configuration. For this reason adding the layer from that service is not allowed.
![image](https://user-images.githubusercontent.com/1279510/81383465-5fbdcd00-9110-11ea-918e-ddb7d60046b1.png)
It's a preventive check.

 CSW instead doesn't contains the list of available CRS and skips the stage of asking for getCapabilities and so the list of allowed SRS.

**Comment by simboss** [comment]
go ahead and add 4326, 4329 seems like a mistake

**Comment by tdipisa** [comment]
Added 4326 to gs-stable in WMS settings

**Comment by simboss** [comment]
thx
