### ISSUE TITLE
Improve geostory settings

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#5280]
## Description

refer to https://github.com/geosolutions-it/MapStore2-C039/issues/166

The popup settings available in the Map inline editor should be enhanced by including the possibility to define custom templates as it is currently possible in [Layer Settings](https://mapstore.readthedocs.io/en/latest/user-guide/layer-settings/#templates).

## Acceptance criteria

- [ ] 
- [ ]

**Comment by MV88** [comment]
The Identify settings in Inline editor are related to all map layers. It is already possible to define a custom template in the advanced editor of the map as described [here ](https://mapstore.readthedocs.io/en/latest/user-guide/layer-settings/#templates). We could anyway put a tooltip in the inline editor to inform the user that he need to use the advanced editor to configure a custom template with a link to the user guide is possible.

**Comment by ElenaGallo** [comment]
@MV88 it is no longer possible to get information about the features of the layer after changing the custom template in the advanced map editor and changing the Identify tool from the  inline editor.

*How to reproduce*
- open new story
- add map background
- set PROPERTIES on the advanced editor of the map
- enable the Identify from inline editor
- set Identify to TEXT
- click a feature on map

*Current Result*
![test](https://user-images.githubusercontent.com/56537133/82820379-55d2f280-9ea2-11ea-93e9-fa4283b1fa74.JPG)

**Comment by tdipisa** [comment]
@MV88 @ElenaGallo we can just improve the info text in the help tooltip

![image](https://user-images.githubusercontent.com/1280027/84478544-ca26d780-ac91-11ea-8e36-6ed8a2d3d1b6.png)
