### ISSUE TITLE
Examples plugin not working as expected

### ISSUE THREAD

**Issue by naveennagar88** [geosolutions-it/MapStore2#5298]
When I try to work on the plugin examples, no map is displayed. I can only see loading message in the browser.
Please find the below url in order to reproduce:
https://dev.mapstore.geo-solutions.it/mapstore/examples/plugins/

Expected Result:
I expect the map load and allow me to use the application

Current Result
Message displaying loading status is observed always

Browser Related:
I am not sure if it is browser related but I have used chrome to access the above URL
![MapStore_Examples](https://user-images.githubusercontent.com/49786368/82339187-62bb9600-9a0b-11ea-8a1e-a0b456552685.PNG)

**Comment by offtherailz** [comment]
I tried it and it works for me (Both with http or https, https://dev.mapstore.geo-solutions.it/mapstore/examples/plugins/). 

Do you see any error in the console?

P.s. Take into account that some of the functionalities of this tool are available in [application contexts](https://mapstore.readthedocs.io/en/latest/user-guide/application-context/).

**Comment by tdipisa** [comment]
This example is no longer maintained since we have recently implemented the new [application context tool](https://mapstore.readthedocs.io/en/latest/user-guide/application-context/). It is deprecated.
