### ISSUE TITLE
Confirmation dialog for geostory 

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#5309]
## Description

- A confirmation dialog is needed if there are pending changes to the story and the user click on home button for example

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by ElenaGallo** [comment]
@offtherailz If you logout after clicking Leave, the white page appears.

![error](https://user-images.githubusercontent.com/56537133/85143213-c672f200-b249-11ea-86a1-3b9364660e74.gif)

**Comment by ElenaGallo** [comment]
Closed in favor of #5517
