### ISSUE TITLE
Better document feature grid plugin and toolbar buttons

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#5353]
## Description

see title 
*Documentation section involved*
- [ ] User Guide
- [x] Developer Guide

**Comment by tdipisa** [comment]
@MV88 I see a closed PR connected here but the issue is still open. Can we close?

**Comment by MV88** [comment]
no, the documentation still needs to be improved

**Comment by tdipisa** [comment]
It is not so clear which part of the documentation need to be improved.

**Comment by MV88** [comment]
We need to add documentation for the [toolbar in feature grid](https://github.com/geosolutions-it/MapStore2/blob/111edbccc3b587ef57d8192a28a52043eb400bc9/web/client/components/data/featuregrid/toolbars/Toolbar.jsx#L25)

And for the [Feature Grid plugin](https://github.com/geosolutions-it/MapStore2/blob/111edbccc3b587ef57d8192a28a52043eb400bc9/web/client/plugins/FeatureGrid.jsx#L14)
and include it in the plugins doc
