### ISSUE TITLE
Problems with deployment on Ubuntu 18.04.

### ISSUE THREAD

**Issue by lukalazovic** [geosolutions-it/MapStore2#5362]
## Description

I am following the tutorial for deployment on mapstore2 docs and I put mapstore.war in tomcat8 webapps folder, but when I want to access localip:port/mapstore I get 404 error. Does someone having same issues and how I can solve it. I am newbie with this, any help would be great. Thanks in advance!
## How to reproduce

-  

- 

*Expected Result*

*Current Result*

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
Hi @lukalazovic, could you please write to the mailing list first ? 
https://groups.google.com/forum/#!forum/mapstore-users

Here on GitHub we report only confirmed bugs, and this looks an installation issue. You can read more about this policy here: 
https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md#reporting-bugs

It could be useful if you report some details about the version you're trying to install and to (take a look and) attach the tomcat logs to the email on the mailing list and any additional information you can include (java version, tomcat version ...)
I'm going to close this issue, Thank you.
