### ISSUE TITLE
MapStore not respecting WMS protocol version!

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#5378]
Steps to reproduce using [this map](https://dev.mapstore.geo-solutions.it/mapstore/#/viewer/openlayers/5849).

If I add the S52 Standard layer from the ENC WMS 1.1.1 server with [this GetCapabilities](http://encws.geo-solutions.it/geoserver/ows?service=wms&version=1.1.1&request=GetCapabilities), subsequent requests are using the 1.3.0 version of the protocol.

If I add a layer using the GetCapabilities in a certain version, I should stick to that version for the upcoming requests!

**Comment by ElenaGallo** [comment]
@vlt1 do you know why the map WMS service mentioned above ( `http://encws.geo-solutions.it/geoserver/ows?service=wms&version=1.3.0&request=GetCapabilities`  ) is not visible and causes this error on console:

> https://encws.geo-solutions.it/geoserver/gwc/service/wmts?layer=EMSA%3AS52%20Standard&style=CMAP&tilematrixset=EPSG%3A4326&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image%2Fpng&TileMatrix=EPSG%3A4326%3A11&TileCol=2209&TileRow=614

**Comment by vlt1** [comment]
@ElenaGallo Both ENC WMS 1.3.0 and ENC WMS 1.1.1 are present and work in the map mentioned in the issue on dev. What do you mean?

**Comment by simboss** [comment]
@ElenaGallo you mention WMS and then you link a WMTS query. Please, clarify.

**Comment by ElenaGallo** [comment]
@vlt1 @simboss yes, sorry. The fact is that the connection to the `encws.geo-solutions.it` service (both for ENC WMS 1.3.0, ENC WMS 1.1.1 and ENC WMTS) don't work for me. 
.

**Comment by simboss** [comment]
@vlt1 leave this aside for the moment.

**Comment by simboss** [comment]
@chpicone @randomorder apparently the [EMSA ENC GeoServer](https://encws.geo-solutions.it/geoserver/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=EMSA%3AS52%20Standard&STYLES=&SRS=EPSG%3A4326&CRS=EPSG%3A4326&TILED=false&WIDTH=1858&HEIGHT=435&BBOX=35.85512638092041%2C14.307117462158203%2C35.892462730407715%2C14.466590881347656) is not reachable at all.
Can you double check?

**Comment by randomorder** [comment]
It's only reachable via HTTP, not HTTPS

**Comment by simboss** [comment]
Strange, it was a the time...

**Comment by simboss** [comment]
@ElenaGallo please, clone this map (leave the original one for reference) and change it to use HTTP and not HTTPS.

The check if my report above is still valid and let us know here your findings.

**Comment by ElenaGallo** [comment]
With the [new map](http://dev.mapstore.geo-solutions.it/mapstore/#/viewer/openlayers/31140) the S52 Standard layer of the ENC WMS 1.1.1 server has requests with the same [GetCapabilities version](http://encws.geo-solutions.it/geoserver/ows?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=EMSA%3AS52%20Standard&STYLES=&SRS=EPSG%3A3857&CRS=EPSG%3A900913&TILED=true&WIDTH=256&HEIGHT=256&BBOX=0%2C0%2C20037508.342789244%2C20037508.342789244) and the layers of the ENC WMS 1.3.0 server have requests with the GetCapabilities 1.3.0  version. The issue can be closed.

**Comment by simboss** [comment]
The new map still does not work for me as it still points to HTTPS.

Am I missing something?

**Comment by ElenaGallo** [comment]
new issue for the HTTPS request problem  [here](#6127)

**Comment by tdipisa** [comment]
@simboss @ElenaGallo see my comment [here](https://github.com/geosolutions-it/MapStore2/issues/6127#issuecomment-718885376)
