### ISSUE TITLE
Map Template Extension - Window size on QA

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#5381]
## Description

The default "Upload Map Template" window height should be a little resize in order to avoid the scrollbar  (as happens on dev).

## How to reproduce

-  Open MapStore
- Open New context
- Navigate the wizard untill step 3
- Enable Map Template Extension 
- Open the Configure Templates
- Open the Upload Map Templates

*Expected Result*

![bar2](https://user-images.githubusercontent.com/56537133/83275418-69969580-a1cf-11ea-9cc9-07a42b59e922.JPG)

*Current Result*

![bar1](https://user-images.githubusercontent.com/56537133/83275433-6d2a1c80-a1cf-11ea-924d-0d69a3ad2a31.JPG)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@gitcontributor Can you check this please? I cannot replicate but a double check is suggested I think.

**Comment by gitcontributor** [comment]
Hi @tdipisa, I found that when the browser window height is 868px or less vertical scroll appears.
