### ISSUE TITLE
Search by bookmark

### ISSUE THREAD

**Issue by dsuren1** [geosolutions-it/MapStore2#5388]
## Description
It shall be possible to switch between different views (based on bbox function - https://mapstore.readthedocs.io/en/latest/user-guide/share/) directly in the map.
For this reason there shall be a drop down list left to the search bar. Whenever a drop down element is selected the map shall be opened at the specified bbox.

## Acceptance criteria

 a) The entries for the drop down list shall be configurable by the administrator only and there shall be a configuration button similar to the one for search services, but only visible to the administrator.
b) The administrator shall be able to set a name for the drop down list entry.
c) The administrator shall have two options to set a bbox: 1) manually by entering coordinates and 2) automatically get bbox parameters from the current view.
d) The administrator shall have a choice between the following settings
1) when a list entry is chosen the respective bbox shall be loaded and the visibility of the layers shall be reloaded as defined in the map configuration file and
2) when a list entry is chosen the respective bbox shall be loaded and the visibility of the layers shall be kept as currently (at the moment of the list entry selection) set by the user for each entry.
e) all settings shall be stored in the map configuration file

## Other useful information
Related to https://github.com/geosolutions-it/austrocontrol-C125/issues/152

**Comment by ElenaGallo** [comment]
@dsuren1  If you are on Search by bookmark and log out, you can still search by bookmark.
![bookmark logout](https://user-images.githubusercontent.com/56537133/85567429-21815c00-b631-11ea-8972-13bcf1713832.gif)

**How to Reproduce**
- Open this [map(https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/26581)
- Click on Search by bookmark
- Click on Log out
