### ISSUE TITLE
GeoStory enhancement requests

### ISSUE THREAD

**Issue by om2468** [geosolutions-it/MapStore2#5400]
Is it possible to get two functionality changes in:

- The ability to change the font for a block type- at the moment you cant change the font and size when you assign bullet points to a set of text.

- Ability to copy and paste hyperlinks from word into the text editor without losing they hyperlink.

These would really help to improve the use of GeoStory.

**Comment by tdipisa** [comment]
Dear @om2468,
thank you so much for this. We already opened [this Epic](https://github.com/geosolutions-it/MapStore2/issues/5303) in MS to collect some possible improvements for GeoStory; some of them, as you can see in the epic status, are already part of the current milestone (a new MS release is coming). Your points are already included in the epic, therefore I'm going to close this issue to avoid duplicate.

I have few feedbacks for you anyway:

>The ability to change the font for a block type- at the moment you cant change the font and size when you assign bullet points to a set of text.

The font for a block type can be already changed:

![image](https://user-images.githubusercontent.com/1280027/83872253-e676c180-a731-11ea-9eb6-394059b64f31.png)

We will include the font size in this milestone really soon (the issue [here](https://github.com/geosolutions-it/MapStore2/issues/5406))

>Ability to copy and paste hyperlinks from word into the text editor without losing they hyperlink.

It is part of the Epic #5303 but it needs some investigation to see if we can accomplish that with the text editor we are using.
