### ISSUE TITLE
mkdocs-material issues with new version

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#5419]
## Description
Mkdocs v5 is installed by default in some cases, but the current MapStore theme supports only v4. When this happens, you can not run mkdocs serve. 

We should find out how to avoid this issues and/or update to v5.

We should also investigate if this is a problem of for all the new installations of mkdocs-material (set-ups that gave problems are all new installations) or if this is a problem related to the version of python or other causes.

Issue found in : 
- Ubuntu 20.04 --> python 3.4
- MacOSX

**Comment by offtherailz** [comment]
I found out that removing extra-social allows at least to run `mkdocs serve` but the theme is not consinstent (still using v5 vs v4 configuration)-

**Comment by ElenaGallo** [comment]
This issue is no longer valid, it can be closed.
