### ISSUE TITLE
GFI - Improvement

### ISSUE THREAD

**Issue by dsuren1** [geosolutions-it/MapStore2#5465]
## Description

- Order of GFI https://github.com/geosolutions-it/austrocontrol-C125/issues/155

- Selection of mulitple GFI in window https://github.com/geosolutions-it/austrocontrol-C125/issues/165

- Reduce space used for coordinates and buttons in GFI https://github.com/geosolutions-it/austrocontrol-C125/issues/166

**Comment by ElenaGallo** [comment]
@dsuren1 here some observations after testing the Identify tool:

1- Sometimes when there are more then three features, the identify tool is displayed incorrectly, as follows:
![GFI hover](https://user-images.githubusercontent.com/56537133/91545502-6a9ba800-e921-11ea-8b05-9550a9ad77c0.gif)

2- Even though there is only one feature, the Identify tool displays arrows, as follows:
![Arrows GFI](https://user-images.githubusercontent.com/56537133/91545509-6cfe0200-e921-11ea-8215-fcdfaff1ab8d.png)

*How to reproduce*

- Open [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/27883) map
- Hover over the features on map

**Comment by dsuren1** [comment]
@ElenaGallo The above issues have been addressed as part this PR https://github.com/geosolutions-it/MapStore2/pull/5787. Kindly retest when the PR is merged with master
