### ISSUE TITLE
Create a raster style editor for layer

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#547]
The style editor allows to create a color map for the raster layer, and have a preview on map.

**Comment by kappu72** [comment]
<img width="719" alt="screen shot 2016-05-09 at 12 03 45" src="https://cloud.githubusercontent.com/assets/9317650/15109934/376dcfbe-15de-11e6-9ecb-854e97535ff7.png">

**Comment by offtherailz** [comment]
Opacity  should be a slider or a number. Can you Explain more the opacity? 
What about to select color ramp presets (max, min, step)?

**Comment by kappu72** [comment]
In rastersymbolyzer we can define a general opacity at layer level and a color opacity that overwrite the general one for a class entry. 
The former's value is configured by the slider under type selector. The latter's value is configured by the color selector  in color column, but is used only if the user checks the opacity checkbox in opacity column the opacity column

**Comment by kappu72** [comment]
Ramp Color selector based on  [colorbrewer2](http://colorbrewer2.org/) colors schema
<img width="600" alt="screen shot 2016-05-11 at 12 11 45" src="https://cloud.githubusercontent.com/assets/9317650/15177711/cc34fc96-1771-11e6-9ad0-0aa8beb64abc.png">

**Comment by kappu72** [comment]
<img width="586" alt="screen shot 2016-05-11 at 13 31 28" src="https://cloud.githubusercontent.com/assets/9317650/15179549/ca6401a4-177c-11e6-9d1a-25b7f975d7ee.png">
