### ISSUE TITLE
Map Tutorial displaying problem

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#5470]
## Description

The buttons of some steps of the tutorial are not highlighted correctly

![tutorial-map](https://user-images.githubusercontent.com/56537133/84412859-221cfa00-ac10-11ea-988e-6ae84ca95ce4.gif)

## How to reproduce

-  Open a map
-  Click on Burger Menu
- Click on Tutorial
- Navigate the tutorial

*Expected Result*

The buttons are highlighted correctly

*Current Result*

The buttons of Option Menu and Zoom in steps are not highlighted correctly

- [ ] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| x |
|Chrome| x |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@ElenaGallo I cannot reproduce it,

**Comment by ElenaGallo** [comment]
@tdipisa It is only on QA, using chrome and edge.

**Comment by tdipisa** [comment]
@ElenaGallo as I wrote above, I cannot reproduce it, for me it is working fine: on both chrome and edge.
This means, provide more info to make other able to reproduce the issue, for example chrome version etc

**Comment by ElenaGallo** [comment]
@tdipisa  The  chrome version is  83.0.4103.97 and the edge version is 44.18362.449.0. My screen resolution is 1920x1080.

**Comment by MV88** [comment]
I also tried , but i was not able to reproduce it with chrome
