### ISSUE TITLE
Infinite loading after loading a certain template

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#5512]
## Description

There is a specific Map Template present in MS, if you add it to the map and then reload the context, an infinite loading occurs.

## How to reproduce

- Open [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/context/plui_advanced) context (the context has the user session active)
- Open the Map Template tool in Option menu 
- Add the template **Espace Verts** to the map
- Reload the map 

![template_infinite loading ](https://user-images.githubusercontent.com/1280027/85130739-c7018d80-b235-11ea-9f2b-9962aed75559.gif)

*Expected Result*

The context is properly loaded also with user session information (available in localStorage for that context, i.e. the loaded map template layers)

*Current Result*

An infinite loading occurs with the following error in console after few seconds:

```
mapstore2.js?bfcec54000861ea0b7a0:347 Uncaught TypeError: t.matrixIds.reduce is not a function
    at C (mapstore2.js?bfcec54000861ea0b7a0:347)
    at mapstore2.js?bfcec54000861ea0b7a0:347
    at Array.map (<anonymous>)
    at P (mapstore2.js?bfcec54000861ea0b7a0:347)
    at Object.splitMapAndLayers (mapstore2.js?bfcec54000861ea0b7a0:347)
    at I (mapstore2.js?bfcec54000861ea0b7a0:347)
    at a (mapstore2.js?bfcec54000861ea0b7a0:347)
    at Object.g [as dispatch] (mapstore2.js?bfcec54000861ea0b7a0:283)
    at i (mapstore2.js?bfcec54000861ea0b7a0:1)
    at mapstore2.js?bfcec54000861ea0b7a0:78
    at mapstore2.js?bfcec54000861ea0b7a0:283
    at mapstore2.js?bfcec54000861ea0b7a0:283
    at mapstore2.js?bfcec54000861ea0b7a0:283
    at t.dispatch [as _next] (mapstore2.js?bfcec54000861ea0b7a0:283)
    at t.__tryOrUnsub (mapstore2.js?bfcec54000861ea0b7a0:283)
    at t.next (mapstore2.js?bfcec54000861ea0b7a0:283)
```

**_At this point you have to manually clean the local storage entry to be able to load the app context again_**

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by MV88** [comment]
@ElenaGallo this needs to be tested in QA
