### ISSUE TITLE
Measure tool has a bug when switching type of measure

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#5531]
## Description

There are some problems when you use measure tool and switch tool while drawing the measure

## How to reproduce

- open measure tool
- start drawing, do not complete the measure
- enable bearing
- as you can see some measure tooltips remains floating on the map
- check console 

*Expected Result*

to reset previous setup of measure (remove tooltips etc)

*Current Result*

this
![image](https://user-images.githubusercontent.com/11991428/85394867-895f7600-b54f-11ea-8191-53e21d27518d.png)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@ElenaGallo why you have reopen this issue? what we have to do with this? Should we move in ready? Is there a bug?

**Comment by ElenaGallo** [comment]
@tdipisa because the backport is missing.
