### ISSUE TITLE
Group manager card has layout problem

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#5532]
## Description

If the text is too long it overlap the description 
![image](https://user-images.githubusercontent.com/11991428/85395555-a34d8880-b550-11ea-8814-d09d3e01c550.png)

## How to reproduce

- open group manager
- add a new group with long name like "area dedicata alla sicurezza"
- check the result

*Expected Result*

to not have overlaps

*Current Result*

overlaps happens

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

TODO: check it something similar happens also the for the user

**Comment by ElenaGallo** [comment]
@vlt1 
Now if the group name is long, an error occurs and the group cannot be saved.
![group name](https://user-images.githubusercontent.com/56537133/86013641-a7314d00-ba1f-11ea-8e15-d294a81592bb.JPG)


On console: POST `https://dev.mapstore2.geo-solutions.it/mapstore/rest/geostore/usergroups/`500 (Internal Server Error)

**Comment by tdipisa** [comment]
@ElenaGallo there is an issue for this in the DB, it it not something connected with the work of @vlt1.
Our DEV DB has not been updated after [this commit](https://github.com/geosolutions-it/geostore/commit/76e59ff9d0f7209b8d1bda1a9d6537967fbb85dd) where the purpose was to increase the size of the name and description attributes in DB

**Comment by randomorder** [comment]
I've updated the table **in DEV**
```
geostore_mapstore2_dev=# \d+ geostore.gs_usergroup
                                           Table "geostore.gs_usergroup"
   Column    |          Type          | Collation | Nullable |   Default   | Storage  | Stats target | Description
-------------+------------------------+-----------+----------+-------------+----------+--------------+-------------
 id          | bigint                 |           | not null |             | plain    |              |
 groupname   | character varying(255) |           | not null |             | extended |              |
 description | character varying(255) |           |          |             | extended |              |
 enabled     | character(1)           |           | not null | 'Y'::bpchar | extended |              |
Indexes:
    "gs_usergroup_pkey" PRIMARY KEY, btree (id)
    "gs_usergroup_groupname_key" UNIQUE CONSTRAINT, btree (groupname)
Referenced by:
    TABLE "geostore.gs_security" CONSTRAINT "fk_security_group" FOREIGN KEY (group_id) REFERENCES geostore.gs_usergroup(id)
    TABLE "geostore.gs_user" CONSTRAINT "fk_user_ugroup" FOREIGN KEY (group_id) REFERENCES geostore.gs_usergroup(id)
    TABLE "geostore.gs_usergroup_members" CONSTRAINT "fkfde460db9ec981b7" FOREIGN KEY (group_id) REFERENCES geostore.gs_usergroup(id)
```

Can you please test again @ElenaGallo ?

**Comment by tdipisa** [comment]
@randomorder I've tested, and it is working fine in DEV

**Comment by randomorder** [comment]
Done for Stable Too

**Comment by tdipisa** [comment]
@ElenaGallo moving the issue in test again, please check and close.

**Comment by offtherailz** [comment]
repoening for back-port
