### ISSUE TITLE
Update Layer Title and Description

### ISSUE THREAD

**Issue by vlt1** [geosolutions-it/MapStore2#5539]
The title and description layers changes periodically, as we publish data every month.
MapStore does not automatically update this data, therefore a function shall be implemented to

a) update the title and description in the TOC from WMS and WMTS services for all used layers.
b) This function shall only be visible to the admin.
c) There shall be an option to update all layers at once
d) There shall be an option to update individually a single layers
e) There shall be an option to update a selection of layers (more than one, but not all)
f) The implemented function shall also give immediate feedback (warning), if the selected layers are not available in GeoServer anymore. (E.g. a layer has been implemented in MS, but the name in GeoServer has changed)

**Comment by vlt1** [comment]
refers to [austrocontrol-C125/#168](https://github.com/geosolutions-it/austrocontrol-C125/issues/168)

**Comment by offtherailz** [comment]
@tdipisa one question about this requirement:
```
At the end, the map state containing the updated information needs to be saved to make changes persistent

```
`needs to be saved` means that the user have to save it manually or you mean that this information will be automatically saved on the server when updated ?

**Comment by tdipisa** [comment]
@offtherailz it means that the user have to save it manually

**Comment by offtherailz** [comment]
I supposed.
The PR #5538 contains an automatic and sophisticated save, that updates only the layers saved. I think we should remove this part to avoid unnecessary complexity.
