### ISSUE TITLE
3D tool problem when new map opens

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#5555]
## Description

The 3D tool remains enabled by opening a new map after it has been activated in a previously opened map

## How to reproduce

- Open a new map
- Click on 3D
- Go back to homepage
- Click on new map

*Expected Result*

Opening a new map the 3D button is not enabled

*Current Result*

Opening a new map the 3D button is enabled

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
Closed in favor of #6456
