### ISSUE TITLE
Javascript error when geolocation is not enabled

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#5560]
## Description

On Firefox (but we should check other browsers too), the following error appears in console when the geo.enabled setting is set to false:

```
TypeError: "navigator.geolocation is undefined"
    value http://localhost:8082/mapstore/dist/mapstore2.js?e77b3b7f1b4c87ec99f6:125
    vi http://localhost:8082/mapstore/dist/mapstore2.js?e77b3b7f1b4c87ec99f6:85
    Ma http://localhost:8082/mapstore/dist/mapstore2.js?e77b3b7f1b4c87ec99f6:85
    Ls http://localhost:8082/mapstore/dist/mapstore2.js?e77b3b7f1b4c87ec99f6:85
    tl http://localhost:8082/mapstore/dist/mapstore2.js?e77b3b7f1b4c87ec99f6:85
    $s http://localhost:8082/mapstore/dist/mapstore2.js?e77b3b7f1b4c87ec99f6:85
    Gs http://localhost:8082/mapstore/dist/mapstore2.js?e77b3b7f1b4c87ec99f6:85
    Uo http://localhost:8082/mapstore/dist/mapstore2.js?e77b3b7f1b4c87ec99f6:85
    unstable_runWithPriority http://localhost:8082/mapstore/dist/mapstore2.js?e77b3b7f1b4c87ec99f6:93
    No http://localhost:8082/mapstore/dist/mapstore2.js?e77b3b7f1b4c87ec99f6:85
    Uo http://localhost:8082/mapstore/dist/mapstore2.js?e77b3b7f1b4c87ec99f6:85
    zo http://localhost:8082/mapstore/dist/mapstore2.js?e77b3b7f1b4c87ec99f6:85
    Ws http://localhost:8082/mapstore/dist/mapstore2.js?e77b3b7f1b4c87ec99f6:85
    wn http://localhost:8082/mapstore/dist/mapstore2.js?e77b3b7f1b4c87ec99f6:85
```

## How to reproduce

-  open Firefox
- type about:config in the url bar
- find geo.enabled and set it to false, save the settings
- open a MapStore map

*Expected Result*

No errors in console.

*Current Result*

Error in console.

- [ ] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Firefox| |
</details>

**Comment by ngmars** [comment]
Hey, I am new to contributing to open source, I would like to know if this bug is still open and if so could I work on it.
I think I have a fair idea of how to resolve this bug, we could take the location input from the user or directly load the map with a default location. Do you have any alternative suggestions in mind?
