### ISSUE TITLE
Sample of configuration for each plugin

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#5561]
There should be a sample of configuration for each plugin reported in the [online documentation](https://dev.mapstore.geo-solutions.it/mapstore/docs/api/plugins#plugins.MapTemplates) along with the info of the related location in localConfig.json file. Some of them are currently missing (i.e. MapTemplate)

**Comment by ElenaGallo** [comment]
@offtherailz the GeoStory plugin is also missing in the plugins doc and after that it must be linked in the user guide as indicated in [this](https://github.com/geosolutions-it/MapStore2/pull/5906/commits/28d308e964b49f3938f93032ace620fbcaafde11#r501769319) comment

**Comment by offtherailz** [comment]
WIP for this issue at: 
https://github.com/offtherailz/MapStore2/tree/doc_plugins
