### ISSUE TITLE
Story section URL

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#5569]
## Description

Related to issue 
https://github.com/geosolutions-it/MapStore2-C039/issues/190

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe: some updates to interlink for stories

**Comment by ElenaGallo** [comment]
@jstrR here are some annotations after testing this issue:
- [ ]  It is no longer possible to share the story by copying the link from the Options button
![share ](https://user-images.githubusercontent.com/56537133/88056014-2964eb00-cb60-11ea-861f-f50c6da5c956.gif)

*How to reproduce*
- Open [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/geostory/11555/title_section_id1) story 
- Click on Options 
- Click on Share
- Copy the Story link

*Expeted Result*
The story link should be https://dev.mapstore2.geo-solutions.it/mapstore/#/geostory/shared/11555

*Current Result*
The link of the story is: https://dev.mapstore2.geo-solutions.it/mapstore/#/geostory/shared/

- [ ] After scrolling down the story, the sharing link became the URL with the section id parameter even if the scrolling position is not activated
![2share](https://user-images.githubusercontent.com/56537133/88058839-53b8a780-cb64-11ea-81e1-f18a0d25eaf1.gif)

*How to reproduce*
- Open [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/geostory/11555/title_section_id1) story
- Scroll down the story 
- Click on Options 
- Click on Share
- Copy the Story link

*Expeted Result*
The story link should be https://dev.mapstore2.geo-solutions.it/mapstore/#/geostory/shared/11555

*Current Result*
The link of the story is: https://dev.mapstore2.geo-solutions.it/mapstore/#/geostory/shared/11555/7eca906c-5dae-431c-b313-80721d4af301/7ee2c8a2-e960-45aa-b008-f75589606d6b

**Comment by tdipisa** [comment]
@jstrR, in addition to the above points mentioned by @ElenaGallo, I have to add also the following one.

- [ ] the first time you open the story from home page, the URL is the following one:
https://dev.mapstore2.geo-solutions.it/mapstore/#/geostory/11555/title_section_id1

but it should be:
https://dev.mapstore2.geo-solutions.it/mapstore/#/geostory/11555

**Comment by jstrR** [comment]
> @jstrR, in addition to the above points mentioned by @ElenaGallo, I have to add also the following one.
> 
> * [ ]  If you open the story from home page or if you open the story with the following URL:
>   https://dev.mapstore2.geo-solutions.it/mapstore/#/geostory/11555
> 
> the URL becomes the following one:
> https://dev.mapstore2.geo-solutions.it/mapstore/#/geostory/11555/title_section_id1
> 
> but it should remain:
> https://dev.mapstore2.geo-solutions.it/mapstore/#/geostory/11555

@tdipisa now, for newly created stories, a uuid will also be generated for the first section.

**Comment by ElenaGallo** [comment]
@jstrR  The scrolling position works properly only on the Demo Observatories story.
If you are on a new story, with the scrolling position activated, the sharing link does not bacame a URL with the section id.

*How to reproduce*

- Open [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/geostory/27102/a846c154-e329-4fb2-94dc-86236e3f0bd3) story
- Scroll down the story
- Click on Options
- Click on Share
- Enable the scrolling position
- Copy the story link

**Comment by ElenaGallo** [comment]
@tdipisa the comment above is my test error. The issue can be closed.
