### ISSUE TITLE
Restore an empty background for Story section

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#5571]
## Description

It is not possible now to remove a background content without changing it with a new content through the media editor or removing the section. 

option 1
A solution could be allow to deselect the media in media editor and click on apply or 

option 2
to add a new section in media editor to select a solid background. 

We can proceed first on option 1, a new issue will be raised for option 2.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by ElenaGallo** [comment]
@jstrR Removing the media from the media content a warning message appears and it is not possible remove the content. 
![media content](https://user-images.githubusercontent.com/56537133/89050406-03ef9280-d353-11ea-9eef-47c4e4cb439b.gif)

*How to reproduce*
- Open a story 
- Scroll down on a media content
- Click on Change Media Source
- Deselect the media
- Click on Apply
