### ISSUE TITLE
Empty cover for stories

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#5574]
## Description

Allow adding a banner without necessarily having a text on it (like the Title section). 

![image](https://user-images.githubusercontent.com/1280027/86459697-7c007380-bd27-11ea-8183-46ea6c457a83.png)

The desired solution is having for now the possibility to add a new kind of section like Title but without the text element in it (we will call this section **Banner**).
Only for this new section we will need also to enable the trash button for the background toolbar to allow the section removal from the story.

![2020_07_03_12_21_27_MapStore_HomePage](https://user-images.githubusercontent.com/1280027/86459979-e2859180-bd27-11ea-9bdc-0b0911ada6d0.png)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by ElenaGallo** [comment]
@jstrR   In view mode, the Banner section is not present in the NavaBar, even if the Banner Section has been added to the NavigationBar from the Settings panel.
![banner](https://user-images.githubusercontent.com/56537133/88911692-7e8ab600-d25e-11ea-8601-c99cb60853f0.gif)


*How to reproduce*
- Open a story with banner section
- Click on Settings
- Enable NavaBar e Banner Section
- Click on Save
- Switch on View Mode
