### ISSUE TITLE
Attribute Table doesn't refresh point geometry filter in editing

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#5576]
## Description

If you open the attribute table in edit mode for a Point layer and you edit one of the existing point features by changing its position (after selecting it clicking on map), the record disappear from the Attribute Table.

## How to reproduce

-  Open [this map](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/10103) and login with admin
- Select the **Types** layer in TOC and open the Attribute Table
- Go in edit mode
- Select a feature on map to edit it (the video below shows how to do that)
- Change the geometry point position and click on save

*Expected Result*

The geometry is properly persisted, the position on map updated accordingly and the record still present in attribute table to edit other attributes if needed.

*Current Result*

The Geometry disappear from the map and from the Attribute Table

![grid](https://user-images.githubusercontent.com/1280027/86332498-e4c5ee00-bc4a-11ea-8e6e-8c36032582f0.gif)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
@tdipisa If you apply a geometric (Point, with buffer) filter and then you move the geometries outside the filter, is normal that they disappear from the current filter. I think this is the expected result. User should reset the filter.
Is the same of applying a filter by attribute and then change the attribute.

**Comment by tdipisa** [comment]
@offtherailz it cannot be considered an expected behavior, because I'm in edit mode and the record disappear from the table. In case of points the filter in the attribute table should be updated according to the new position. That's it.

**Comment by tdipisa** [comment]
@jstrR I've discussed the current behavior with @offtherailz and we agreed on leaving that as it is now.
