### ISSUE TITLE
The about window is not visible on small screens

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#5583]
## Description

The about window is not visible on small screens and cannot be moved, only closed

## How to reproduce

![about](https://user-images.githubusercontent.com/1280027/86377101-30e35380-bc88-11ea-9ff3-a004ff85c59f.gif)

*Expected Result*

The about window should be completelly visible also on small screens

*Current Result*

The about window is not completelly visible at the bottom on small screens

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
Please backport 2020.02.xx
