### ISSUE TITLE
Coveralls and coverage plugin test different things

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#56]
Is impossible to test locally the coverage as coveralls does because the local tool is not aligned with the coveralls rules. 
We should find a solutions to speed up the development and don't force developers to try to guess what Coveralls wants.

**Comment by mircobe87** [comment]
In Coveralls report, lines seem to be shifted.
The `karma-coverage` html report seems to show the right lines coverage.

The local reporter `lcovonly` which is used by `karma-coverage` seems to report the same coveralls results.
For [Atom](https://atom.io/) editor we can use the [lcov-info](https://atom.io/packages/lcov-info) plugin to show `lcovonly` report.

**Comment by offtherailz** [comment]
We noticed 2 lines shift: 
Can this be useful ? 
https://www.npmjs.com/package/karma-remap-coverage

**Comment by offtherailz** [comment]
Also this may help 
https://github.com/webpack/karma-webpack/issues/21#issuecomment-216467317

**Comment by offtherailz** [comment]
Did some experiment, but did not get the solution.
Someone uses isparta, that is not a mantained project.
Someone else use istanbul.1.0.0-aplha.1. We should try it
