### ISSUE TITLE
First npm install after createProject does not work

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#5607]
## Description

- [ ] There is a problem during the first **npm install** 

- [ ] if you run the create project from a branch that is not master a checkout to that submodule needs to be done.

## How to reproduce

-  create a standard project both from master or from 2020.02.xx
-  when finished go to the outputFolder and run npm install

*Expected Result*

all completes correctly 

*Current Result*

here is the partial log 
[first npm install after CREATE_SCRIPT  does not work.txt](https://github.com/geosolutions-it/MapStore2/files/4885065/first.npm.install.after.CREATE_SCRIPT.does.not.work.txt)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by ElenaGallo** [comment]
@MV88 This error occurs when creating a new project:

> errorTypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type object
