### ISSUE TITLE
Remove deprecated styler plugins and related components

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#5628]
## Description

Currently we have two plugins [Styler](https://github.com/geosolutions-it/MapStore2/blob/v2020.02.00/web/client/plugins/Styler.jsx), [RasterStyler ](https://github.com/geosolutions-it/MapStore2/blob/v2020.02.00/web/client/plugins/RasterStyler.jsx)and [VectorStyler](https://github.com/geosolutions-it/MapStore2/blob/v2020.02.00/web/client/plugins/VectorStyler.jsx) not imported in the MapStore product configuration. We could remove those styler to avoid duplication because the new visual style editor covers the same functionality. We should also remove all the dependant components and merge together the `component/styleeditor` with the `component/style` directory.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Other... Please describe: Remove deprecated code

**Comment by tdipisa** [comment]
@allyoucanmap as we discussed and reviewed together with @offtherailz, I think we can remove this deprecated code to clean up the MS codebase.
