### ISSUE TITLE
Geodesic options are not applied when editing geometry details

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#5633]
## Description

if you edit a geodesic Circle from Query panel (which is a Polygon with 100 points) the geodesic property gets lost

## How to reproduce

- Assure to have in localConfig for the query panel plugin the "geodesic":true property for the circle method
- draw a circle
- edit radius

*Expected Result*

to change the radius accordingly to the value that has changed

*Current Result*

the circle is smaller than expected and is no longer geodesic
see also https://github.com/geosolutions-it/MapStore2-C028/issues/143

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
@ElenaGallo I created this context for testing
https://dev.mapstore2.geo-solutions.it/mapstore/#/context/geodesic-query-panel
It contains the following cfg, for query panel (the difference from default is geodesic: true)
```
{
                  "activateQueryTool": true,
                  "spatialOperations": [
                      {"id": "INTERSECTS", "name": "queryform.spatialfilter.operations.intersects"},
                      {"id": "CONTAINS", "name": "queryform.spatialfilter.operations.contains"},
                      {"id": "WITHIN", "name": "queryform.spatialfilter.operations.within"}
                  ],
                  "spatialMethodOptions": [
                      {"id": "Viewport", "name": "queryform.spatialfilter.methods.viewport"},
                      {"id": "BBOX", "name": "queryform.spatialfilter.methods.box"},
                      {"id": "Circle", "name": "queryform.spatialfilter.methods.circle", "geodesic": true},
                      {"id": "Polygon", "name": "queryform.spatialfilter.methods.poly"}
                  ]
              }
```
