### ISSUE TITLE
Number inputs are not customizable in the classification style

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#5646]
## Description

Number inputs are not customizable in the classification style. It seems a request is sent before the actual update of the imput.

Note: if the classification is custum also the method should have the label custom

![classification-error](https://user-images.githubusercontent.com/19175505/87432871-e13a4b80-c5e8-11ea-8a22-d2ddbdcaab48.gif)

## How to reproduce

-  open a map as admin
- select a wms layer (eg US States)
- open settings and select style tab
- select a style and edit (ensure to use the visual style editor)
- change style to classification (on GeoServer must be installed sldservice extension)
- apply a classifiaction by select an attribute
- edit an number in the classification list

*Expected Result*

- the number should update correctly

*Current Result*

- the number does not change

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by ElenaGallo** [comment]
Blocked by #5783
