### ISSUE TITLE
Error on style editor toggle causes recursive requests

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#5649]
## Description

If the style editor fails initial requests for style services it retries without end.
We should stop the requests after an error on the initializiaton providing a notification.

## How to reproduce

-  open this map [451](https://dev.mapstore.geo-solutions.it/mapstore/#/viewer/openlayers/451)
- select the layer and open settings
- select style tab

*Expected Result*

- it should display a notification with error

*Current Result*

- the style editor continue to send requests until it has been closed

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@allyoucanmap 
I've found an use case to replicate the bug I think. MS performs recursive GetCapabilities requests in the following case:

- Add this source to the catalog: https://sdigeo-free.austrocontrol.at/geoserver/tn-a/wms
- Add to the map the layer with name **Transport Network Austria** (name in GeoServer INSPIRE_VIEW_SERVICE)
- Open the Layer Settings->Style
