### ISSUE TITLE
Mapstore Integration with Geoserver with AuthKey 

### ISSUE THREAD

**Issue by curiousaboutgis** [geosolutions-it/MapStore2#5653]
Hello,

I am accessing [GeoServer through Docker](https://hub.docker.com/r/geonode/geoserver) and I try to integrate it with MapStore2. 

I try to follow the [developers guide link ](https://mapstore.readthedocs.io/en/latest/developer-guide/integrations/users/geoserver/
). However, when I try to add new User Group Service, there is no org.postgresql.driver in the dropdown menu. There is only org.h2.driver. 

My question: how do I add this driver? Do I need to edit docker file for that and add download link from official website?
https://jdbc.postgresql.org/download.html

**Comment by tdipisa** [comment]
@curiousaboutgis thank you for this but, can you please use the mailing list for these questions? You can subscribe to both user and dev lists [here](https://mapstore2.geo-solutions.it/mapstore/#/). Thank you so much again.

**Comment by curiousaboutgis** [comment]
@tdipisa  I posted my issue there 1 week ago, unfortunately I did not get any reply.
