### ISSUE TITLE
Undescore is not allowed for User password

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#5654]
## Description
If you try to create a user with and `_` you are not allowed.

This is because of this line: 

https://github.com/geosolutions-it/MapStore2/blob/b9466bce5b7bac68f6c74e0aa15b5ad695037ab0/web/client/components/manager/users/UserDialog.jsx#L263
Originally added for this reason

https://github.com/geosolutions-it/MapStore2/commit/553146bc68c4ff505626b2bc617a72ef1af8fd28

Anyway no information is prompted about the allowed charapter, only the limit of 6 chars. 

We should add the `_` and make more explicit the allowed chars, and / or why the password is not allowed.
## How to reproduce

-  Login as admin
- Open the manager menu and open the "Manage accounts" entry
- Click on "create user" button
- type a user name (e.g. `testUser1`)
- type a password with underscores (e.g. `test_password`)
- re-type the password in the confirm password field
*Expected Result*
The create buttons enables and I'm able to create the user

*Current Result*
The password label is yellow (warning color) and the info tool indicates you need 6 chars.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by AGMETEOR** [comment]
@tdipisa I am running a dev server connected to the `mapstore online demo as back-end`. I am trying to use `username: admin` and `password: admin` but I have failed to authenticate. Any alternative credentials I can use?

I also tried using a local backend but it seems there some issues currently [here](https://github.com/geosolutions-it/MapStore2/issues/5474)

**Comment by tdipisa** [comment]
@AGMETEOR can you please check if also the message in the tooltip need to be improved a bit?
![image](https://user-images.githubusercontent.com/1280027/88030849-09233500-cb3c-11ea-82be-87dc0125cd59.png)
