### ISSUE TITLE
Activate "filter with click on map" by default when FeatureGrid editing is active

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/MapStore2#5658]
## Description
It looks quite uninuitive having to actively select the "filter with click on map" tool when entering editing mode in feature grid.
The actual behaviour is a no-action when clicking on the map. In the context of editing I would expect to be able to "select" a feature for editing when clicking on the map, without having to toggle the tool.

![image](https://user-images.githubusercontent.com/571129/87659056-4911a300-c75d-11ea-8c0c-198efe20029e.png)

**Comment by offtherailz** [comment]
I think it is ok, but we can cause a misleading between the concepts of selection and filtering.

We introduced this:
https://github.com/geosolutions-it/MapStore2/issues/5657

Applying this change will make something like this (ignore the click on the tool)
![Peek 17-09-2020 11-27](https://user-images.githubusercontent.com/1279510/93452572-da75d080-f8d8-11ea-8083-b2413a5b12ac.gif)

That on click filter the table automatically, together with the map. 

I think we should keep one of these: 

- When turn on edit mode, deactivate sync map and activate click selection tool
![Peek 17-09-2020 11-28](https://user-images.githubusercontent.com/1279510/93452687-fe391680-f8d8-11ea-875a-def8afe0df90.gif) that emulates more the concept of "selection".
- When turn on edit mode, keep active the sync map and not activate the click selection tool (like it is now). This asks explicitly the user to activate a filter tool.

Don't know, maybe is more intuitive like you said, I'm rising the issue. 

The change is quite easy to be implemented. More than estimate or try to imagine, I think is more efficient a live test to see what is the proper interaction

**Comment by giohappy** [comment]
@offtherailz unfortunately I see that my edits to the initial version of this issue were lost. In my edited description I was saying exactly this: now we have only filtering (which in turn activate the selection if a single feature is inside the filter).
I don't know the internals of this system, but the way to go would be to distinguish filtering and selection, as you say. 

The following is what I exepct from this improvement:

1. **Select features**: Feature selection should be independent from the filtering. The solution in QGIS is to "highlight" the selected features inside the table and, optionally, move them to the top of the table. The selection doesn't trigger a filtering, it's just a.... selection :) 

2. **Multiselection**: with "click and drag" on the map (box selection) and keyboard modifier (Ctrl / Cmd) to add/remove features from the selection.

With the above in place we would cover most part of the requirements to speed up editing. 
One plus would be the batch updated of attributes for selected features, but this is another story...

**Comment by offtherailz** [comment]
As discussed in phone call, both multi selection or click and drag functionalities require some changes to the general editing system that have to be clarified.
I'll wait for a feedback from you @giohappy if you need more support about this.

Summarizing, I suggested to: 
- add a select tool, that does not filter but simply select the row ("scroll to" feature is not allowed)
- Adding one feature "put selected on top could help" or "filter only selected" (the second is easier). 

At this point we alreay can edit them one by one (with single line support) optionally :

- supporting multi-feature editing to avoid to go to "one line" mode, that is annoying if you need to edit more than one row.
- Adding cell drag https://codesandbox.io/s/cellrangecopypaste-2seht is a plus

**Comment by giohappy** [comment]
Taking into account the current design and what discussed during our call I would say that the pre-condition to any further analysis is if multi-edit with WFS-T is something that could be considered. 
I wasn't aware of the single-feature edit limitation, so this point is the most relevant to me now (for the requirements of the project).

If multi-edit support coasts too much, or there are technical blockers to its implementation, I must take a totally different route, with a custom component and a custom backend API.

I need to hear some feedbacks from @simboss here.

**Comment by giohappy** [comment]
I've discussed this with @simboss and we agreed on the following:

1. **Make the "filter on map" active by default when entering the editing mode**. The marker icon isn't clear at all, but it wouldn't be a big deal if the action is active by default. 
The filtering on map will be extended with the following:

    - Ctrl + click: add / remove features from filter list
    - Click 'n' drag: box selection of multiple features

2. **Do not activate sync with map by default**. The usual behaviour is to filter features inside the feature grid, and higlight them, but keep the rest of the features visible (unless explicitely requested by the user).

3. **Highlight multiple features**. In this moment only one feature is highlighted. If multiple features are selected the highlighting disappears.

4. **Save (one or multiple) edits in same context**. Disable the current behaviour which opens a "Save" view for the currently edited feature. When one or multiple features have edited contents we show the Save / Cacnel icons directly inside the table panel.
The edited features might be highlighted with a bold characted for the edited value.

![image](https://user-images.githubusercontent.com/571129/93795610-ec89a300-fc39-11ea-8829-5c8694499fae.png)
. 

5. **Multiple edited features in single transaction**. The point above assumes the ability to send edited features in a single transaction, while currently we only have one by one edits.

5. **Copy edits to multiple features**. We want to include the behaviour as from the latter point from @offtherailz comment, i.e. the ability to drag/copy a cell value to multiple features. The behaviour should also support multiple cells (range selection).

@tdipisa @offtherailz an estimate is required for all the feature requests above.

**Comment by giohappy** [comment]
closing in favour of https://github.com/geosolutions-it/MapStore2/issues/5911
