### ISSUE TITLE
Implement add and remove options in classification entries

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#5666]
## Description

Visual style editor should support add and remove options for each classification entries. This issue will implement these options on the vector classification. Once an entry has been added or removed the intervals and reverse properties should be disabled and the method set to customInterval.

The proposed ui component is a dropdown with the following options:
- add entry before
- add entry after
- remove

We should also add custom interval as default entry value of classification method

![image](https://user-images.githubusercontent.com/19175505/87802414-7d668b80-c851-11ea-9109-909d6dc6fb1b.png)

How to access the classification component in UI:

- open this [map](http://localhost:8081/#/viewer/openlayers/10358)
- login as admin
- open the TOCItemSetting and then click on the style tab (layer `States of US`)
- edit an existing style
- add a classification symbolizer

![classification](https://user-images.githubusercontent.com/19175505/90156053-5043c500-dd8c-11ea-9fdd-6a6ffe69f8ac.gif)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features

### Requirements

- add a dropdown toolbar to [ThemeClassesEditor](https://github.com/geosolutions-it/MapStore2/blob/e15c98dd6d8f39836d7740236a7f717dd67250fb/web/client/components/style/ThemaClassesEditor.jsx) component (see screenshot above)

- the dropdown needs to be enabled or disabled via props and have following actions:
  - add entry above
  - add entry below
  - remove entry (remove should be disabled if the entry is only one)

- the Methods selector should show the Custom Interval entry in the options. Currently the custom inteval entry is [dynamically added to methods options](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/styleeditor/config/blocks.js#L322-L342) we should remove this behaviour and provide the option directly at prop level in the [StyleCodeEditor](https://github.com/geosolutions-it/MapStore2/blob/c422768ade14c41070bec86c40deb1f5bbf0f461/web/client/plugins/styleeditor/StyleCodeEditor.jsx#L116) plugin component adding the customInterval entry to vector classification. The custom interval classification could be activeted in two way:
  - automatically after changing a value in the ThemeClassesEditor (this was implemented [here](https://github.com/geosolutions-it/MapStore2/commit/6aa6a434bdc7802a426952c29c9b9d252d73b572))
  - or selecting the custom interval option in the Method select. If the classification array is empty (no entry are visible in the UI) and a user switches to customInterval an entry should be added to the classification UI.

The ThemeClassificationEditor is imported in the StyleEditor [here](https://github.com/geosolutions-it/MapStore2/blob/c422768ade14c41070bec86c40deb1f5bbf0f461/web/client/components/styleeditor/Fields.jsx#L279-L295)

## Other useful information

There is an issue on temporary styles on the style editor so please close the settings panel each time you use the editor to ensure that the temporary style is deleted.

**Comment by allyoucanmap** [comment]
@tdipisa @giohappy please take a look at this issue and let me know if the proposed solution could work.

**Comment by giohappy** [comment]
@allyoucanmap it reflects what we discussed in our call, so I'm fine with it. By the way to me the before / after icons appear inverted. When you say "after" I would expect the bar to be above the plus button, and viceversa for "before"

**Comment by allyoucanmap** [comment]
If we introduce also the functionality to add new entries when the classes editor is empty we could keep the custom interval method always available as suggested by @offtherailz in this comment https://github.com/geosolutions-it/MapStore2/pull/5665#pullrequestreview-453455997:

> The code looks good and this fix the bug (adding this feature).I only express an opinion about custom interval interaction.
> 
> When you change some input number, this selects a new entry called "custom interval" and the custom intervals slider disables.
> I think is more usable if you allow to select the method "custom interval" anyway, you hide the interval slider and instead allow to add/remove rows.
>

**Comment by giohappy** [comment]
I agree with this. This was also my opinion to have Custom Interval as a method by itself.

**Comment by dsuren1** [comment]
@allyoucanmap @tdipisa @giohappy 
With recent introduction of `Unique interval` which supports both _string_ and _numbers_ attributes, having `Custom Interval` as a separate method introduces the following question
- Upon selecting `Custom Interval` method dropdown, should we retain the previous method's fields ? i.e Same as modifying any intervals/classification fields (existing behavior), automatically switches to 'Custom Interval' and retains current method's fields for modification
- When the first method selection is `Custom Interval`, then we cannot determine what type of classification fields to be displayed (Range with min and max or Unique with number or string fields)

  -  To handle this, should we introduce a new field in the classification symbolizer called _Range / Unique - String / Unique - Number_? (**Ref - Picture 1**)
  - Or Can we introduce new methods value called `Custom Interval - Range` and `Custom Interval - Unique` and then if the selection is `Custom Interval - Unique`, then additional field in classification is displayed for user to select if it is a 'Number or String' attributed classification fields (**Ref - Picture 2**)
  - Based on the selection, only one entry is displayed [Color - {Range fields}/{Unique fields of type string or number}] (**Ref - Picture 3**)

- Upon adding new entry before and after, what should be the default values for the newly added field. (Color/Min/Max/Unique string/Unique number)?
-  Should the vertical ellipsis icon displayed always or only upon selecting the `Custom Interval` method from the dropdown?

**_Picture 1_**
![2021-05-20 19_02_03-MapStore HomePage](https://user-images.githubusercontent.com/26929983/118988451-d4bc1780-b99e-11eb-9239-cf6d0f9617fd.jpg)

**_Picture 2_**
![2021-05-20 19_11_10-MapStore HomePage](https://user-images.githubusercontent.com/26929983/118988755-19e04980-b99f-11eb-944f-5aeba1b69ece.jpg)

**_Picture 3_**
![2021-05-20 19_17_26-MapStore HomePage](https://user-images.githubusercontent.com/26929983/118989866-01bcfa00-b9a0-11eb-8bed-6accb8b428a2.jpg)

**Comment by tdipisa** [comment]
@dsuren1 I would like to simplify things as much as possible for the moment, let's see then for further improvements later. In relation to what you wrote above, please follow the indications below. We mostly maintain the current logic/behaviors with few exceptions:

1. We maintain the current methods available in DD
2. The user selects one of them and the classification is performed automatically as it is now
3. The user now can customize that classification: he can change values or add/delete classification rules
4. After changing something (point 3), instead of showing **Custom Interval** as method, we show the same method label with a symbology indicating that the classification performed using the selected method has been customized (eg a pencil icon or something like that beside the method string in DD)
5. The option at point 4 is anyway a new one dinamically added to the DD as soon the user customize something in the classification as it is now; this because it should be always possible for the user to select again the same method to perform the same classifications from scratch (eg. resetting the custom one and invoking again the SLD service)
