### ISSUE TITLE
New Icon for Banner Section

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#5690]
A new icon need to be designed for the new Banner section introduced by this issue:
https://github.com/geosolutions-it/MapStore2/issues/5574

**Comment by allyoucanmap** [comment]
@tdipisa icon proposal

`story-banner-section` ![image](https://user-images.githubusercontent.com/19175505/89276482-00eeed80-d644-11ea-81c3-359923ddcda1.png)

![image](https://user-images.githubusercontent.com/19175505/89276434-f0d70e00-d643-11ea-940f-f92049c219c2.png)

**Comment by tdipisa** [comment]
@allyoucanmap we should have all these items in the same line.
