### ISSUE TITLE
Size of bullet points in stories

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#5725]
## Description

The size of text in bullets point is different between edit and view mode of rich text editor in stories.

![story_bullet](https://user-images.githubusercontent.com/1280027/89163427-d9315400-d575-11ea-82c7-e9a9eb9e25e1.gif)

## How to reproduce

-  Open a story 
-  Follow the steps of the video in the description

*Expected Result*

The size of the text in bullet points must be the same between edit and view mode

*Current Result*

The size of the text in bullet points is different between edit and view mode

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by AGMETEOR** [comment]
@tdipisa the size seems to be the same `14px` both in view and edit mode. Is this in a particular browser?

**Comment by AGMETEOR** [comment]
Approach
-----------

Give appropriate styling to` ul > li` from geostory.less
