### ISSUE TITLE
Setting hyperlinks introduce a space 

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#5726]
## Description

While adding hyperlinks in rich text editor in a story a space is introduced in the next work on the right.

![links_space_story](https://user-images.githubusercontent.com/1280027/89164356-45608780-d577-11ea-853b-e7c1485fcf92.gif)

## How to reproduce

-  Open a story like [this one](https://dev.mapstore2.geo-solutions.it/mapstore/#/geostory/11555)
-  Use the rich text editor ad illustrated in the gif above 

*Expected Result*

The hyperlink setting works well without adding additional spaces

*Current Result*

The hyperlink setting introduce a space

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by AGMETEOR** [comment]
This is coming from an issue in `react-draft-wysiwyg` whose Editor component we're using. There's been similar issues reported 
- https://github.com/jpuri/react-draft-wysiwyg/issues/676
- https://github.com/jpuri/react-draft-wysiwyg/issues/681

Unfortunately, this issue has been there for long and someone sent in this PR to fix
- https://github.com/jpuri/react-draft-wysiwyg/pull/707
but the author seems to be pre-occupied and she hasn't merged the fix yet.

**Comment by AGMETEOR** [comment]
Approach to fix
------
1 ) Try and get author to merge the fix
or
2) Fork the library in geosolutions org, merge fix into fork and push to npm or point to github fork
