### ISSUE TITLE
More font families for story rich text editor

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#5727]
## Description

Check the possibility to customize the configuration of the available font families in rich text editor for stories and improve the related [plugin documentation](https://mapstore.geo-solutions.it/mapstore/docs/api/plugins) explaining how to do it.

![image](https://user-images.githubusercontent.com/1280027/89648876-330c8380-d8c0-11ea-940e-b9bfdf703163.png)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Other... Please describe: configuration capabilities check and related documentation

**Comment by AGMETEOR** [comment]
Approach to fix
----------
In `localConfig.json` we add configuration for GeoStory like so
```json
{
"name": "GeoStory",
"cfg": {
"fontFamilies": [
{
"family": "Lemonada",
"src": "https://fonts.googleapis.com/css2?family=Lemonada:wght@300&display=swap"
}
]
}
}
```
We can then read the config at runtime from GeoStory plugin and pass down the props to the editor to merge with the default families.

We also need a third party library to load in the font files from GeoStory plugin
