### ISSUE TITLE
Size of Paragraph section configurable

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#5728]
## Description

The posibility to tune the size of the text section (width) should be provided.

![image](https://user-images.githubusercontent.com/1280027/89167029-2cf26c00-d57b-11ea-94ac-9a1087612648.png)

We should include a size button in the section's toolbar for this

![image](https://user-images.githubusercontent.com/1280027/89167303-865a9b00-d57b-11ea-96a9-3dcae1afff5d.png)

available sizes should be:

**Large:** as it is now (the default)
**Medium:** the width is reduced by 25%
**Small:** the width is reduced by 50%

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by AGMETEOR** [comment]
Follow same approach as that used to make `Title` section size configurable
