### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by sajad3731** [geosolutions-it/MapStore2#5733]
## Description

Hi

> I cloned the app and run "npm install" command successfully and after that, run the application using "npm start" command, but when the application loaded successfully, i couldn't log to it with "admin" username and password.

Do I need to do any special configuration to do this?

*Current Result*

Error: Login Fail Username or password incorrect

- [ ] Not browser related

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome|84| 
|Firefox| |
|Safari| |
</details>

**Comment by sajad3731** [comment]
I read the documents but did not understand anything about it

**Comment by offtherailz** [comment]
Hi @sajad3731, please ask to the mailing list if you have the doubts or questions. We prefer track on github only confirmed bugs or tasks. I'm going to close this issue, at least until a bug is confirmed.

Thank you :+1:
