### ISSUE TITLE
change direction of whole app (modal and text and etc.) to RTL

### ISSUE THREAD

**Issue by sajad3731** [geosolutions-it/MapStore2#5734]
## Description

Hi

> can we change direction of whole app to rtl, without any clutter in some section?
What should be done to change the direction of the application?

another question

> can we upgrade version of "bootstrap" and "react-bootstrap" packages to version 4, without any clutter?

*Documentation section involved*
- [ ] User Guide
- [ ] Developer Guide

**Comment by offtherailz** [comment]
Hi @sajad3731, please ask to the mailing list if you have the doubts or questions. We prefer track on github only confirmed bugs or tasks. I'm going to close this issue, at least until a bug is confirmed.

Thank you +1

**Comment by sajad3731** [comment]
sorry
i didn't know that
thanks for your response
