### ISSUE TITLE
Review of the story settings UI

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#5739]
## Description

The UI of the [story settings](https://mapstore.readthedocs.io/en/latest/user-guide/story-setting/) needs to be reviewed and small additional features included to improve the customization of the story header. The required updates are reported in the mockup below.

![story_settings_2](https://user-images.githubusercontent.com/1280027/89318011-81cadb00-d67e-11ea-8bc3-4fb8e9668f10.png)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by AGMETEOR** [comment]
Approach to fix
-------
Changes to be made in `components/geostory/builder/Settings.jsx`

**Comment by tdipisa** [comment]
@AGMETEOR take into account the following consideration. In my opinion the list of available font families should be shared between different components of the stories that need them.
First of all we have to establish that list of font families: by default it can be the same list available now in rich text editors. That list of font families should be included in a configuration property of the Story Settings component (plugin configuration) to be automatically used by all Rich Text Editors in the stories. In that way we can have a more coherent tool where the list of font families is defined in one single location.
