### ISSUE TITLE
Fix initially misaligned "About" modal

### ISSUE THREAD

**Issue by AGMETEOR** [geosolutions-it/MapStore2#5749]
## Description

The "About" modal is draggable, but should initially be properly aligned.

## How to reproduce
- Go to map viewer
- Go to burger menu
- Press the About button
![Screenshot 2020-08-04 at 09 57 14](https://user-images.githubusercontent.com/28563179/89424084-016cae80-d740-11ea-8a30-09a3ff867dd4.png)

*Expected Result*
An initially properly aligned About modal

*Current Result*
The About Modal is not initially properly aligned and credits can't be seen

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@AGMETEOR we had a similar issue [here](https://github.com/geosolutions-it/MapStore2/issues/5583) recently fixed. Is it a regression?

**Comment by AGMETEOR** [comment]
I think we can close this. There's no bug actually and the modal is draggable into place.
![rec](https://user-images.githubusercontent.com/28563179/89767249-38591080-db02-11ea-8b08-44bb5101ce54.gif)

**Comment by tdipisa** [comment]
@AGMETEOR we should make it centered in the view
