### ISSUE TITLE
newly created standard Project has problem with travis

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#5751]
## Description

When you create a new standard project and you run npm run travis there is this error
```
06 08 2020 10:36:11.060:ERROR [karma-server]: Server start failed on port 9876: Error: Cannot find module 
'mocha'
```

this is because the original mocha package has not being cleaned up by postinstall script that is missing in [here](https://github.com/geosolutions-it/MapStore2/blob/master/utility/projects/projectScripts.json)

## How to reproduce

- create new standard project
- npm install
- npm run travis

*Expected Result*

all works correctly 

*Current Result*

the above error

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

this line in package.json fixes it

        "postinstall": "node MapStore2/utility/build/postInstall.js",

**Comment by ElenaGallo** [comment]
Blocked by #5792
