### ISSUE TITLE
Feature info does not work correctly when a layer is selected in the TOC

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#5755]
## Description

feature info should ignore layer selection in the toc
![image](https://user-images.githubusercontent.com/11991428/89525291-3df2e580-d7e6-11ea-9f91-bc494e92f655.png)

## How to reproduce

-  add some layers, states and poi from new map (should not matter the order)
- select poi
- click on a state 

*Expected Result*

to see features from states in the results

*Current Result*

see screenshot above

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

if i select states instead it works, but probably only for it.

**Comment by tdipisa** [comment]
@MV88 it is a feature not a bug. The documentation [here](https://mapstore.readthedocs.io/en/latest/user-guide/side-bar/#identify-tool-with-more-than-one-layer).

**Comment by giohappy** [comment]
@tdipisa honestly this "feature" is quite misleading. Me and @simboss also noticed this, and we were going to ask to investigate.
I think an alternative solution should be implemented, with an explicit option to limit the GFI to the selected layer.
It could be a select inside the results window, similar to what QGIS does:

![image](https://user-images.githubusercontent.com/571129/102370169-11817e00-3fbd-11eb-9b12-90a946607fb0.png)
