### ISSUE TITLE
Implementation of MapSwipe Functionality

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#5762]
## Description
We have requested by a Client to implement a MapSwipe tool for MapStore that we also have to integrate in GeoNode (only for maps).

The original prototype that we were shown is available [here](http://cigno.ve.ismar.cnr.it/bsa/tools), however this is pretty basic and not integrated at all inside GeoNode and MapStore. We need this to be integrated properly in MapStore.

A good example of widget to take inspiration is available from ESRI [here](https://doc.arcgis.com/en/web-appbuilder/create-apps/widget-swipe.htm), notice the 3 available types of Swipe (also the spyglass). See some examples [here](https://storymaps-classic.arcgis.com/en/app-list/swipe-spyglass/).

This is also a nice tool to integrate in GeoStory asap.

## Other useful information
As I mentioned above, we need to integrate this into GeoNode as well.

The client code is C190-OAW-2020-SUPPORT available budget, comprehending the integration in GeoNode is 10 days.
We shall stay within this estimate.

to check:
https://github.com/Esri/storymap-swipe

**Comment by offtherailz** [comment]
Here some preview from a spike, Both working on mouse move for consistency.

![swipe](https://user-images.githubusercontent.com/1279510/92587031-61062e80-f297-11ea-8513-5573352d33ee.gif)
![spyglass](https://user-images.githubusercontent.com/1279510/92587050-6794a600-f297-11ea-8952-8f19394eb08d.gif)

**Comment by simboss** [comment]
Nice work.

How do you envision the following:
- how do I activate the tool?
- how do I select the two layers?

Notice that I would want this tool to be avail also on geostories!

**Comment by offtherailz** [comment]
Thank you for the feedback. 
I'm writing a technical document about it, with all the details (activation, layer selection and so on). 
I'll add the some details for the integration with GeoStory.

**Comment by simboss** [comment]
@AGMETEOR when you work on an implementation issue like this one that takes some time, please update the issue itself regularly so that people watching it know where we are withouth having to ask regularly.

Thanks a lot.

**Comment by AGMETEOR** [comment]
> @AGMETEOR when you work on an implementation issue like this one that takes some time, please update the issue itself regularly so that people watching it know where we are withouth having to ask regularly.
> 
> Thanks a lot.

Sorry, I wasn't updating here. Will do so going forward.

**Comment by AGMETEOR** [comment]
I have identified a minor bug with the feature, working on pushing a fix for it.

**Comment by simboss** [comment]
@allyoucanmap where we are with the L&F restyling?

**Comment by tdipisa** [comment]
>@allyoucanmap where we are with the L&F restyling?

@simboss [this PR](https://github.com/geosolutions-it/MapStore2/pull/5979) has already benn merged few minutes ago. Let's wait for the deploy in DEV

**Comment by simboss** [comment]
@bruncili notice that @ElenaGallo just close this issue, hence I think the development is done and we can start with the merge on GeoNode.

Please, double check.

**Comment by bruncili** [comment]
@ElenaGallo confirmed me the end of test phase, reports available at https://studio.cucumber.io/projects/48097/test-plan/folders/1615629 . I'll manage the merge on GeoNode.
