### ISSUE TITLE
Issues with GFI popup in edit mode

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#5773]
## Description
Several issues in popup of GFI (when set to burger menu --> settings --> Feature info trigger is set to `hover`).

See this map:
https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/27684

### Overlapping entries
In same cases the results come in column, instad of being paginated.
![popup1](https://user-images.githubusercontent.com/1279510/90042371-e3b4c180-dcca-11ea-9bef-bbc1a23607ed.jpg)

### Arrows are showing also with one single result
![image](https://user-images.githubusercontent.com/1279510/90042342-dbf51d00-dcca-11ea-8b8a-1afa5dc26d0d.png)

### A glitch
Sometimes the map pans even if not necessary (I think because of a temporary stacking of items in the popup). I was not able to replicate it, @tdipisa showed me in a different map.

All these are regressions not present in the latest release. So please check what recent changes introduced it and try to fix.

**Comment by tdipisa** [comment]
Thank you @offtherailz for opening this issue. The reference map I used for my test is the following one:

https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/10358

Below GIF thst shows the problem. It is a regression, I don't know if it has been introduced by the lates updates provided by @dsuren1 on the Identify tool. @dsuren1 please check it, thank you.

![info_popup_issue](https://user-images.githubusercontent.com/1280027/90046723-25e10180-dcd1-11ea-9a56-b3ce8bb01676.gif)

**Comment by dsuren1** [comment]
Related to: https://github.com/geosolutions-it/austrocontrol-C125/issues/155
