### ISSUE TITLE
Simplyfing Annotation creation and editing

### ISSUE THREAD

**Issue by dsuren1** [geosolutions-it/MapStore2#5775]
The details about the annotation refactor is in a separated PDF [[Annotations_redesign](https://drive.google.com/drive/u/0/folders/18teFXmSNF8JBqzx3YOpfoQVYp6SFO3BR)]

The re-design is mainly graphical. We need to reorganize the existing panels into the new view. All the requirements are correct and good looking. For this activity we should consider that a good part of the existing interactions, actions and controls belonging to the Annotation tool will need to be reviewed and changed to fit the new design and user interactions.

### Open Annotations

This view is the same, no changes needed

### Add Annotation

* Toolbar:  display all geometries in line and a save button on the right
* Description: Collapsible (to continue allowing rich text)

### Add Geometry

* New list of geometries, with buttons for remove, open or accept changes
* Coordinates and Style editor in accordion panel

**note**: the style on the map changes based on the accordion opened (edit style for coordinates, applied style for style accordion)

* Support Auto-save on geometry

### Annotation List

This point do not requires any change

### Edit Geometry

* When an Annotation is clicked, the editing window will be opened: according to general usages of the tool, it isn’t a good practice to directly switch in edit mode as soon as the annotation is clicked in the list (within the annotation panel), a view mode need to be activated first for consultation purposes only, then if the user has right permissions on the map, also the possibility to switch to the edit mode with a button should be provided. What we can do here is to introduce an additional configuration option (by default to false) to directly activate the edit mode once an annotation is clicked in the list

* The existing interface allows to zoom to the annotation and this detail is not present in the new mockup: we assume to maintain this functionality as it is now in the new UI, GeoSolutions will provide a new mockup 

* Two ways hover (from panel or from map) highlight of geometries when selected

* Move download annotation

### Text visualisation and style improvements

* Text Rotation: there is a separate offers for this in the estimates

* Text Style options refactor

The solution proposed by Austrocontrol seems reasonable, GeoSolutions will prepare and then share a mockup in order to agree with Austrocontrol before starting the development. 

**Reference**
https://github.com/geosolutions-it/austrocontrol-C125/issues/153
https://github.com/geosolutions-it/austrocontrol-C125/issues/187
https://github.com/geosolutions-it/austrocontrol-C125/issues/188
https://github.com/geosolutions-it/austrocontrol-C125/issues/189
https://github.com/geosolutions-it/austrocontrol-C125/issues/190
https://github.com/geosolutions-it/austrocontrol-C125/issues/191
https://github.com/geosolutions-it/austrocontrol-C125/issues/171
https://github.com/geosolutions-it/MapStore2/issues/4553

**Comment by ElenaGallo** [comment]
@dsuren1 here some notes:
- The description of the annotation with more than one line of text is displayed as follows:
![description](https://user-images.githubusercontent.com/56537133/92759204-c76e7800-f38f-11ea-86a1-2d8e94194a61.JPG)

- Opening the LineDash from the dropdown menu displays an additional an extra space  (or a scroll bar if the screen size is small)
![stroke2](https://user-images.githubusercontent.com/56537133/92761166-b0308a00-f391-11ea-9aaf-bd7e0fbce07a.gif)


*How to Reproduce*
- Reduce the screen dimensio
- On new annotation add a point geometry
- On style tab change to symbol type
- On stroke section click on the LineDash dropdown menu

**Comment by dsuren1** [comment]
> The description of the annotation

The annotation card is compact and cannot accommodate fieldValue as innerHTML, which is the reason for this issue.
Can we display only texts without the formatting? And this will make the quill editor of no use for description with html formatting.

Please advice @offtherailz @tdipisa @allyoucanmap

**Comment by offtherailz** [comment]
@dsuren1 what is the probrem if I set:
```
.mapstore-annotations-info-viewer .ms-style-manager {
 overflow: hidden
}
```

**Comment by dsuren1** [comment]
> @dsuren1 what is the probrem if I set:
> 
> ```
> .mapstore-annotations-info-viewer .ms-style-manager {
>  overflow: hidden
> }
> ```
> 
> Trying to fix somehow the position of the select menu or it's height?

@offtherailz 
By setting the style tab-container's position and overflow. I have a fix ready for this. 

> The description of the annotation with more than one line of text

Also I have a question on how the description issue mentioned above should be handled. So I can give a combined fix

**Comment by dsuren1** [comment]
Note: Description with ellipsis for lengthier texts and only text content will be displayed (No html formatting on the card preview)
