### ISSUE TITLE
GeoStory Contents - Rich Text - Interactions

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#5778]
This is an enhancement to the existing hyperlink tool currently used within the Rich Text Editor component for the GeoStory tool. 

With that hyperlink tool it is currently possible to define only hyperlinks to external web pages. The aim of this issue is to enhance it to define hyperlinks to other sections of the same story. Therefore, an improvement must be included to scroll to a section of the same story by clicking on the hyperling defined in a paragraph section.

The current Rich Text Editor component used for GeoStory is based on **react-draft-wysiwyg**: [a GeoSolutions fork](https://github.com/geosolutions-it/react-draft-wysiwyg) is available so that we can extend it for the purposes of this issue (the MS's react-draft-wysiwyg dependency is available on the GeoSolutions npm registry).

The mockup below describes the UI and relevant actions involving the enhanced component.

![section_hyperlink_tool](https://user-images.githubusercontent.com/1280027/90135126-7c524c80-dd72-11ea-99d8-f790af631981.png)

Related to https://github.com/geosolutions-it/MapStore2-C039/issues/47

# Suggested implementation

by @offtherailz 
To implement this, we need to take into account that also #5779 should work with the same system.we might be tempted to use some sort of `href` with some URL hash link `#` to parse, or browser history to manage, 

But I think this could be dangerous in terms of future integrations because :

 - it requires to have a full control on the current browser location. Future ingegrations of GeoStory in separate applications may not have this possibility
- In addition a solution like this will not work without some changes to the existing link system, because of some limitations in the current implementation of `#links` for sections

For this reasons I suggest a more stable approch that guarantees future extension (e.g. a link that zoom the map to a bbox, and/or opens the feature info in a particular point) and maintainability.

For this reasons i suggest from this phase to think to create links that instead trigger a javascript function. Let's call it **interaction**.

The interaction has :

- a **type**, that defines what the action is. For now only `scrollTo` 
- a list of parameters that depends on the type. For now only the ID of the section to scroll to.

I suggest to inspect 2 implementations (of course you the developer can propose his own, when investigated). For both you will have to create the custom http link editor tool that create a custom `a` tag. This `a` tag will be used only in GeoStory editors.

### Solution 1. use data + event bind/unbind

The link tool will create a a tag like this:
```
<a data-geostory-interaction="<type>;<param1>;<param2>;...;<paramN>" />
```

For scrollTo interaction the effective html will be (The id of the section to scroll is "my-section-id")
```html
<a data-geostory-interaction="scrollTo;my-section-id" 
```
To make this trigger the real event, some side effect should dynamically associate the onclick event handler of the `a` tag with the call of an handler, passed to the component.

something like:

```javascript
useEffect(() => { // or an epic ...
document.querySelectorAll("iframe[data-geostory-interaction])
    .map(element => element.onClick = () => interaction( ...element.getAttribute("data-geostory-interaction").split(";"))
} // TODO: handle unmount and changes on data tags.
) 

// then interaction implementation will be something like:
interaction = (type, ...params ) => 
if(type === 'scrollTo')  {
   GeoStoryUtils.scrollTo(params[0]) // or trigger some action that do this.
} 
```

Pro: 
 - More clear and 
Cons: 
 - binding have to be handled with care of mount, unmount, and in every text element, and in the popup. 

### Solution 2. javascript inline call

In this case the html link editor will generate an `a` tag like this.
```
<a onclick="__geostory_interaction(<type, param1, param2, ..., paramN)
```
Defining once for all the function `window.__geostory_interaction`  that does the same thing, on geostory mount (and removing it on story unmount).

``` javacript
useEffect(() => {
window.__geostory_interaction = (type, ...params) => interaction(type, ...params);
}) // TODO:  remove on umount.

Pro:
 - This will work in any context, and is maybe easier.
Cons: 
 - The global function breaks the self-contain rules.

**Comment by allyoucanmap** [comment]
A note about the current implementation of scroll to section/column:

Geostory scroll to a specific section using the [scrollToContent](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/GeoStoryUtils.js#L129yUtils.js#L129) utils so click on a <a/> link with href describing the internal section and column could not be enough.

So we will need to trigger the action via react taking into accout that the text is saved as plain html inside the story json configuration. This probably mean we need to add some custom `data-...` attributes to the internal link node to be able to parse the html in view mode and replace if with a react component. In the past I used this library to parse html and replace specific nodes https://github.com/remarkablemark/html-react-parser but we should evaluate if this fit this kind of enhancement. @offtherailz what do you think about this approach?

**Comment by AGMETEOR** [comment]
Some notes
------------
- I went with solution 2 as suggested by @offtherailz 
- For the whole thing to come together, made changes in our clone of `react-draft-wysiwg`, `mapstore` repo as well as a supporting library `html-to-draftjs`. Therefore, we need to also made a clone of [html-to-draftjs](https://github.com/jpuri/html-to-draftjs) into geosolutions org so that we can apply our enhancements

**Comment by tdipisa** [comment]
@offtherailz do you heva some comments about the above notes?

**Comment by ElenaGallo** [comment]
@AGMETEOR here some notes after testing this issue:

- [ ] The content of a section has dispalyed with the id insted of the content name (this happens for the paragraph section, media section and web page section)
![1_section_link](https://user-images.githubusercontent.com/56537133/94834141-47788280-0410-11eb-9404-8167fc66e838.png)

*How to Reproduce*
- Open [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/geostory/29705) story
- From a rich text click on Link


- [ ] The second content added to the section does not appear in the hiperlink dropdown menu
![2_section_link](https://user-images.githubusercontent.com/56537133/94834156-4ba4a000-0410-11eb-8e60-235bb7d5aa77.png)


*How to Reproduce*
- Open [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/geostory/29705) story
- From a rich text click on Link

**Comment by AGMETEOR** [comment]
Hi @ElenaGallo ,please share with me the story json. I think I know what's going on.

**Comment by ElenaGallo** [comment]
@AGMETEOR the story is now editable.

**Comment by AGMETEOR** [comment]
> @AGMETEOR the story is now editable.

Hello @ElenaGallo , I wanted to look at the data or json file that generates this story. It is possible that some sections or columns might not have titles. We use section titles to display in the dropdown and use ids as a fallback (from the code).

**Comment by tdipisa** [comment]
> > @AGMETEOR the story is now editable.
> 
> Hello @ElenaGallo , I wanted to look at the data or json file that generates this story. It is possible that some sections or columns might not have titles. We use section titles to display in the dropdown and use ids as a fallback (from the code).

@AGMETEOR I think you are able to check that.
