### ISSUE TITLE
Timeline showing but WMTS layer with time dimension are not supported

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#5786]
## Description
Timeline for WMTS layers for time dimension show, but changing the current time has not effect on the layer

There is a common mistake due to terminology that create misunderstandings:
Time dimension is supported for WMS layers. not yet for WMTS (because WMTSLayer doesn't accept additional parameters like "time" yet) , but it uses the extension WMTS-Multidim. For this reason many people thinks you must use WMTS catalog and layers to use time dimension. Instead WMS is enough (and tiling is supported, in any case).

## How to reproduce

-  Add a a layer with the time dimension from WMTS catalog (meteorite landings). Sample map [here](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/10279).

*Expected Result*
The timeline must not be enabled

*Current Result*
Timeline is present but changing the current time has no effect.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
@tdipisa 
an implementation of this is relatevely easy, but it doesn't seems to work
```diff
677ceb2e))$ git diff web/client/components/map/openlayers/plugins/WMTSLayer.js
diff --git a/web/client/components/map/openlayers/plugins/WMTSLayer.js b/web/client/components/map/openlayers/plugins/WMTSLayer.js
index e6f4c1eb..40bc6850 100644
--- a/web/client/components/map/openlayers/plugins/WMTSLayer.js
+++ b/web/client/components/map/openlayers/plugins/WMTSLayer.js
@@ -115,6 +115,7 @@ const createLayer = options => {
     const wmtsOptions = {
         requestEncoding,
         urls: urls.map(u => u + queryParametersString),
+        dimensions: options.params,
         layer: options.name,
         version: options.version || "1.0.0",
         matrixSet: tileMatrixSetName,
@@ -160,7 +161,8 @@ const updateLayer = (layer, newOptions, oldOptions) => {
     if (oldOptions.securityToken !== newOptions.securityToken
     || oldOptions.srs !== newOptions.srs
     || oldOptions.format !== newOptions.format
-    || oldOptions.style !== newOptions.style) {
+    || oldOptions.style !== newOptions.style
+    || oldOptions.params !== newOptions.params) {
         return createLayer(newOptions);
     }
     return null;
```
this changes allow to add the `time` parameter to WMTS request, but it doesn't seems to give the expected results
```bash
curl 'https://gs-stable.geo-solutions.it/geoserver/gwc/service/wmts?layer=mapstore%3AMeteorite_Landings_from_NASA_Open_Data_Portal&style=mapstore%3Ameteorites&tilematrixset=EPSG%3A900913&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image%2Fpng&TileMatrix=EPSG%3A900913%3A1&TileCol=1&TileRow=0&time=1931-07-15T03%3A57%3A00.257Z%2F1996-02-02T02%3A55%3A22.681Z' \
  -H 'authority: gs-stable.geo-solutions.it' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36' \
  -H 'accept: image/avif,image/webp,image/apng,image/*,*/*;q=0.8' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: no-cors' \
  -H 'sec-fetch-dest: image' \
  -H 'referer: http://localhost:8081/' \
  -H 'accept-language: en,it-IT;q=0.9,it;q=0.8,en-US;q=0.7,ja;q=0.6' \
  --compressed
```
![test_save_thumbnail](https://user-images.githubusercontent.com/1279510/96564308-475afc80-12c3-11eb-8e50-8a15c187faca.gif)

I also checked this example in Openlayers and it works, and the dimensions request looks the same (additional entry)
Did I missed something? 
We should investigate on this after diabling temporary this support, because integration is quite easy and avoid user confusion (WMTS multidim extension doesn't work with WMTS, it's strange )

**Comment by myrdstom** [comment]
If both a wms and wmts layer are selected, should the timeline be visible?

**Comment by tdipisa** [comment]
@offtherailz as we discussed in the meeting this morning, please open a separate issue for 2021.01.00 to investigate why enabling the time dimension for WMTS layers it is not working as expected.

**Comment by tdipisa** [comment]
> If both a wms and wmts layer are selected, should the timeline be visible?

what do you mean precisely?

**Comment by myrdstom** [comment]
> what do you mean precisely?
From the gif, we have both `WMS version` and `WMTS version` in the `TOC`. If only `WMS version` layer is visible, we should render the timeline. If only `WMTS version` is visible, we should not render the timeline. What happens if both `WMS version` and `WMTS version`, should the timeline be rendered?

**Comment by tdipisa** [comment]
@myrdstom the timeline is automatically enabled if there are one or more supported layers with the time dimension available in TOC: within the timeline there is the list of layers you can use indeed. Considering the example above, the timeline will be enabled for only the WMS layer
