### ISSUE TITLE
npm install fails the first time on newly created standard project

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#5792]
## Description

I was testing the creation of project while fixing #5613 and i noted the following.

let's assume you have just create a project with this script from [this master](https://github.com/geosolutions-it/MapStore2/tree/f989accfb158169d70a20529351a9955ef09e324) branch
`node ./createProject.js standard test_cesium 1.0.0 "My MS Project" "https://github.com/tdipisa/test_cesium" ../test_cesium`

now you run npm install
what happens is that npm finds the package.json of the submodule and runs the postInstall command with some errors

```

> mapstore2@0.1.0 postinstall C:\Work\Projects\test_cesium2\node_modules\mapstore2
> node utility/build/checkCesium.js && node utility/build/postInstall.js

Is project: true
Cesium not found
Copying Cesium from node_modules...
internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, stat '../node_modules/cesium'
    at Object.statSync (fs.js:915:3)
    at Object.statSync (C:\Work\Projects\test_cesium2\node_modules\graceful-fs\polyfills.js:308:16)
    at Object.copySync (C:\Work\Projects\test_cesium2\node_modules\fs-extra\lib\copy-sync\copy-sync.js:31:86)
    at copyFromNodeModules (C:\Work\Projects\test_cesium2\MapStore2\utility\build\checkCesium.js:11:8)
    at Object.<anonymous> (C:\Work\Projects\test_cesium2\MapStore2\utility\build\checkCesium.js:17:5)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Mo###dule.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10) {
  errno: -4058,
  syscall: 'stat',
  code: 'ENOENT',
  path: '../node_modules/cesium'
}


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mapstore2@0.1.0 postinstall: `node utility/build/checkCesium.js && node utility/build/postInstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mapstore2@0.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

```

so seems that the ponstinstall scripts run by node fails because they do not find the node_modules inside the parent folder. which is weird because at runtime they exists
![image](https://user-images.githubusercontent.com/11991428/90264185-02dd5b80-de51-11ea-8e7c-de0fad93f39f.png)

### Another problem is the second script after checkCesium, i.e. postInstall.js

where it should clear some packages by copying inside the forked ones inside @geosolutions in npm.
like mocha etc.

a solution to this can be using the alias of npm like
"mocha": "npm:@geosolutions/mocha@<version

*Expected Result*

npm install works flawlessy and npm run travis works too

*Current Result*

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

### html-to-draftjs only imported, missing in package.json

Another error i get **only** in the created project is the following
https://github.com/geosolutions-it/MapStore2/search?q=html-to-draftjs&unscoped_q=html-to-draftjs
![image](https://user-images.githubusercontent.com/11991428/90263509-0d4b2580-de50-11ea-8ca5-7812f8f69f98.png)

Honestly it is weird that it does not fail on master branch in mapstore..

it seems that if you use try catch to avoid failure of checkcesium and ponsinstall this happens. it resolves doing a second npm install.

### WORKAROUND for cesium

doing a second npm install should complete the npm install process, although there are other problems that would make npm start fail like html-to-draftjs, and npm run travis the postinstall.js not being run.

**Comment by mbarto** [comment]
@MV88 about the checkCesium.js issue, I believe it started when we switched to using the single file:MapStore2 dependency.
Doing this, npm is using the MapStore2 subfolder as a "real" library and applying its standard procedures to it, for example, when doing an npm install for the project, npm will execute the postinstall script in the MapStore2/package.json file (it was not doing that before, because there was no dependency to MapStore2).
In my opinion we should make the script location aware (able to understand if it is run from a MapStore2 folder of a project or from the original repo) and look for files in the correct place based on that.
Same applies to postInstall I believe.
