### ISSUE TITLE
Feature Info Zoom to feature doesn't work on first click

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#5793]
## Description
Affects new GFI layout for 2020.03.00

![image](https://user-images.githubusercontent.com/1279510/90264694-c2321200-de51-11ea-9243-f9220afa6933.png)

## How to reproduce
- Open this map https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/2464
- Click on map to a queriable layer,(check format of GFI is "text)

*Expected Result*
Feature info shows the zoom to feature button. (it should not be visible if the format is not json (properites or template) or the "highlight" is not present). Clicking on it has no effect.

*Current Result*
The zoom to feature was orgiinally disabled as well as the json data is not present.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@dsuren1, I'm not able to replicate this. Can you please check and eventually provide a fix. as you can see is something connected to Project: C125.

**Comment by dsuren1** [comment]
@tdipisa Fix is added as part of  **PR** https://github.com/geosolutions-it/MapStore2/pull/5787

**Comment by dsuren1** [comment]
Related to https://github.com/geosolutions-it/austrocontrol-C125/issues/155
