### ISSUE TITLE
Show format setting for only WMS and CSW catalog services

### ISSUE THREAD

**Issue by AGMETEOR** [geosolutions-it/MapStore2#5795]
[See 2nd paragraph of this comment](https://github.com/geosolutions-it/MapStore2/pull/5724#pullrequestreview-460586642)

WMTS format in advanced settings do not work (it seems to be ignored). 
We should use the `CommonAdvancedSetting` that should be valid for all the services. 
Raster is reserved for WMS and CSW

**Comment by tdipisa** [comment]
@offtherailz i think the format should setting should be pesent also for WMTS catalogs.

**Comment by offtherailz** [comment]
WMTS should allow the format, but the format should come from the catalog, so the selector should show the formats available from it. Actually this feature is not implemented, so is better to not show this feature until the feature is implemented.
We can implement it in the next release. @tdipisa should I open an issue for that?
