### ISSUE TITLE
Swipe stops working in case of empty results

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#5812]
## Description
On mobile, with the new viewer, if you swipe to an empty result, you can not come back (the No data view is not swipable).
![swipe](https://user-images.githubusercontent.com/1279510/91840418-f0d12a80-ec50-11ea-8964-38b896dc22a6.gif)

## How to reproduce
-  Open a map in mobile mode, with at least 2 queriable layers
- tap to get the feature info in an area that has data for only one of the two layers
- swipe with the finger to the other layer

*Expected Result*
I can not swipe to empty data or I can swipe back to other layers

*Current Result*
I see the empty view and there is no content, i can not get back to another layer.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information
@tdipisa @allyoucanmap during the mock-up procedure, I remember that there was a requirement like: 
> the layers that are loading or that are errored, empty or loading are disabled in the layer selector

I see instead that in the mock-up these kind of layers are selectable. I think that we have a better UI if the empty/not-valid/loading responses are well identified in the layer selector and swipe or selection is allowed only for current valid responses.
What do you think?  (avoiding to show empty/not valid/not ready results) can help also to simplify the display system in various mode (desktop/mobile/popup).

**Comment by tdipisa** [comment]
@offtherailz, relevant requirements for this issue are highlighted below:

>>- Invisible levels will not appear in the list
>>- **While an Identify request is performed, all the visible layer in the layer selector are disabled at the beginning**
>>- **The first element that comes will be selected (and enabled)**
>>- **While loading the other elements of the list (sorted as in TOC) will start enabling.**
>>- **If a layer responded with no-content, the selection will be anyway allowed.**
>>- The selector should look more or less like the one provided with an arrow (drop-down menu) instead of a burger menu

Therefore we only need to fix the swipe back, we have to swipe to all results (also the empty ones) but the first layer with results will be showed, as it is now. For desktop the tool is properly working according to the requirements as far I can see now, for mobile we might also consider a further improvement to allow the swipe only for layers for which we have identify results, but we can open a new issue for the future fot this.

**Comment by dsuren1** [comment]
As discussed, I have placed the renderEmptyLabel on top of the response/results viewer for mobile view, as this will prevent seeing an empty space at top as we are showing empty results and the rest remains the same in desktop view
![SwipeGFIMobile](https://user-images.githubusercontent.com/26929983/94027890-f564ab00-fdd8-11ea-8071-b11e73223f0b.gif)
