### ISSUE TITLE
Sorting not working when a layer filter is present

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#5836]
## Description
When the layer filter is present, column sorting in feature grid doesn't work. See this: https://github.com/georchestra/mapstore2-georchestra/issues/266
![Peek 04-09-2020 12-35](https://user-images.githubusercontent.com/1279510/92230565-a39cc500-eeab-11ea-9eb6-b0361f2594b4.gif)

## How to reproduce

-  Add to states layer the layer filter persons > 5000000 and save the filter
- Open feature grid
- Try to sort by column clicking on the column header (tested with "persons")

*Expected Result*
The order of rows changes

*Current Result*
The order of rows doesn't change

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information
Looking at the request the request is sent but the sort order is fixed to STATE_NAME, ascending. Clicking on the column headers doesn't change this filter.

**Comment by MuhweziDeo** [comment]
@offtherailz @tdipisa I tested this in https://dev.mapstore.geo-solutions.it/ and sorting looks to be working fine. Please confirm on your end that it works as well

**Comment by tdipisa** [comment]
@MuhweziDeo yes it seems perfectly working now on both DEV and QA instances. Moving to Test for a new check @ElenaGallo.

**Comment by ElenaGallo** [comment]
it works, I close the issue.
