### ISSUE TITLE
bookmark select visibility layer reload crashes 

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#5843]
## Description
On layer visibility toggle is set to true and when the bookmark is selected with zoomOnSelect set to true. The application crashes

## How to reproduce
1. Open a map with edit permission https://dev.mapstore2.geo-solutions.it/mapstore/?debug=true#/viewer/openlayers/25914
2. By default zoomOnSelect is set to true.
3. Create a bookmark with **Toggle visibility reload** set to true
4. Save it and select the bookmark under book select drop down

*Expected Result*
1. Map should zoom to the bookmark bbox set and the map should reload with the initial config (any visible layer that are not present in map initial config should be reset) 

*Current Result*
The application crashes

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by ElenaGallo** [comment]
@dsuren1  If the BookMark has the Toggle visibility reload set to true, selecting the bookmark the map does not have the bookmark bbox.

**How to Reproduce**
- Open this [map](https://dev.mapstore2.geo-solutions.it/mapstore/?debug=true#/viewer/openlayers/28564) with a BookMark with the Toggle visibility reload set to true
- Click on Search by bookmark
- Click on New Mexico in the dropdown menu

*Expected Result*
The map has the same bbox as the bookmark
