### ISSUE TITLE
Add documentation about configuring web server / proxy and print service

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#5871]
## Description
There are often some problems with configuration of:
-  https via Apache HTTP Server and print 
- Setup of proxy and CORS

We could add to the documentation a FAQ dedicated to installation / configuration (or add some hints in the developer faq).

*Documentation section involved*
- [ ] User Guide
- [x] Developer Guide

## Other useful information
Some of the problems related to it:

https://github.com/georchestra/mapstore2-georchestra/issues/243
https://github.com/geosolutions-it/MapStore2-C028/pull/148

**Comment by tdipisa** [comment]
closed with #5922
