### ISSUE TITLE
Uniform geodesic property setting across plugins

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#5883]
## Description

The current setting in MS is:
- QueryPanel: geodesic option is set to false by default
- Measurement: geodesic option is set to true by default
- Annotation (Circle): geodesic option is set to false by default

For the last one the config option is totally missing and it should be introduced at least to show the radius length of a circle accordingly.
In general, all these three settings should be aligned to the same value (geodesic set to true) by default to make things more consistent.

**Current Query Panel**
![measure_1.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/bb30330a-d18a-4fac-be8d-ae5f31b4af4e)

**Current Annotation (Circle)**
![measure_2.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/177b1d6b-37d4-4f3e-906d-57accbe83701)

**Current Measurement**
![measure_3.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/dd22f439-e9b2-4024-ac5c-80fcd4355803)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe: configuration + small improvement

## Other useful information

**Comment by offtherailz** [comment]
So this can be splitted in 2 different tasks.
- [ ] Support for Annotations geodesic (indication of the radius), to activate by default
- [ ] QueryPanel set to true geodesic

**Comment by MV88** [comment]
I've noticed that the radius used in annotations is different from the one used in the other tools (query form and measure) even if geodesic true is configured in localConfig. (it should be true by default.

@AGMETEOR can you verify the reason ??
try to draw circle and a measure in the same point in order to compare them

**Comment by tdipisa** [comment]
@MV88 @AGMETEOR cannot do that now, please check this and let me know.

**Comment by tdipisa** [comment]
Closed in favor of #6503
