### ISSUE TITLE
Annotations bugs 

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#5888]
## Description

1. import duplicates when saving
1. ui is not correct
1. filter by icon not work
![image](https://user-images.githubusercontent.com/11991428/93483601-4409d500-f901-11ea-9bac-eda0ed2e0420.png)
1. problem with feature title or description
as you can see i am able to add spaces in between, but i can enter a lot of chars that breaks UI
![image](https://user-images.githubusercontent.com/11991428/93485861-d317ec80-f903-11ea-9a83-f0ddfa71c60c.png)

## How to reproduce

1) 
  - import [test annotation.json.txt](https://github.com/geosolutions-it/MapStore2/files/5239746/test.annotation.json.txt)
annotation remove .txt before importing
  - open an annotation enter a title which now is empty
  - save

2) 
  - when importing i have this (notice the toolbar on the right )
![image](https://user-images.githubusercontent.com/11991428/93483831-83d0bc80-f901-11ea-9156-ff5f6e43adc4.png)

3) 
  - open annotation line,
  - go to style, add start point
  - click on icon and try to insert something

4) 
- open an annotation
- click on a feature
- start entering a long text (with spaces but it not relevant)

*Expected Result*

1. to have only one entry when saving or to have a default title @tdipisa which one?

1. to not have that ui problem

1. to be able to filter icons

1. to to avoid that strech and / or to be able to insert spaces at the end

*Current Result*

1. duplication of annotations in the ui 
1. misalignement, see previous img
1. cannot write anything it, no error are in 
1. problems, see previous img

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by dsuren1** [comment]
Note: 
**Regarding issue 1 (Import duplicates)**
This scenario will not happen in future as the **PR** (https://github.com/geosolutions-it/MapStore2/pull/5918) adds the _properties_ (title and description) and also strips the _newFeature_ prop when exporting the current annotation without saving the annotation but only saving the geometry.
To test this please don't use the attached json file above in the description of the issue. Try exporting new json from the annotation

**Comment by MV88** [comment]
> Note:
> **Regarding issue 1 (Import duplicates)**
> This scenario will not happen in future as the **PR** (#5918) adds the _properties_ (title and description) and also strips the _newFeature_ prop when exporting the current annotation without saving the annotation but only saving the geometry.
> To test this please don't use the attached json file above in the description of the issue. Try exporting new json from the annotation

this means old annotations exported will no loner work? can't we make the import retro-comaptible?

**Comment by dsuren1** [comment]
The old exported annotations (from old design) and the one's exported via **Download annotations** will work perfectly fine (from new design). 
Except for the '**current annotation**' exported via the _new annotation design_ where this bug exists (exporting current annotation without saving the annotation but only saving the geometry).
