### ISSUE TITLE
[documentation] Example link is broken

### ISSUE THREAD

**Issue by Gaetanbrl** [geosolutions-it/MapStore2#5894]
## Description
The link into `The Plugins Example Application` part seems to be broken here : 
http://dev.mapstore.geo-solutions.it/mapstore/examples/plugins/

*Documentation section involved*
- [ ] User Guide
- [X] Developer Guide

## Other useful information

Documentation page  concerned :
https://mapstore.readthedocs.io/en/latest/developer-guide/plugins-architecture/

**Comment by offtherailz** [comment]
We removed the example because it is not maintained anymore, so that reference in the documentation have to be removed. Thank you for the notification.
