### ISSUE TITLE
Swipe Tool Configuration / Switcher

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#5898]
This tool is available when the swipe tool is active. It allows to:
- Change swipe or spyglass tool
- Allows to select the radius for the spyglass.
- (future change could allow to change horizontal or vertical cut for swipe)

**Comment by AGMETEOR** [comment]
@tdipisa is it possible to get some mockups for this issue?

**Comment by tdipisa** [comment]
@AGMETEOR yes of course, we will provide it asap. in the meantime you can continue with the implementation of the core functionality by developing a floating config panel, we will probably opt for a button somewhere to open this once the tool is active.

**Comment by tdipisa** [comment]
@AGMETEOR 
below a simple mockup of what the tool activation button  should looks like to switch between the two modes (swipe/spyglass)

![5893_mockup](https://user-images.githubusercontent.com/1280027/94675916-cab7ac80-031a-11eb-84f6-b4f9eef5801e.png)

If the user clicks on **Configure**, the panel illustrated below opens to set the spyglass size (in px i guess) if the spyglass mode is active. 

![mockup_spyglass](https://user-images.githubusercontent.com/1280027/94677081-9c3ad100-031c-11eb-925c-104b918ac97b.png)

In case the of Swipe active instead, the same panel opens but with the possibility to set the swipe mode (vertical/horizontal) through two radio buttons or a dropdown (maybe it is better)

**Comment by AGMETEOR** [comment]
@tdipisa there's also some form of configuration to do for the Swipe tool i.e. switching between Horizontal and vertical swipe

**Comment by tdipisa** [comment]
> @tdipisa there's also some form of configuration to do for the Swipe tool i.e. switching between Horizontal and vertical swipe

@AGMETEOR it is already considered in my comment above.
