### ISSUE TITLE
Extend FeatureGrid to support editing of multiple features

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/MapStore2#5911]
This epic is the result of a previous issue where the topics were initially discussed. The following points were discussed with @offtherailz @tdipisa and @simboss.

The goal is to improve / extend the multi-edit capabilities of the FeatureGrid, to support the editing of multiple features at once.
The current editing mode of the FeatureGrid offers basic support for the editing of single feature + single attribute at once. This proposal wants to support:

 - quick filtering of multiple features in editing mode
 - editing of multiple features + multiple attributes in single shot

To achieve this the following relevant points must be addressed.

1. **Make the "filter on map" active by default when entering the editing mode**. The marker icon isn't clear at all, but it wouldn't be a big deal if the action is active by default. 
The filtering on map will be extended with the following:

    - Ctrl + click: add / remove features from filter list
    - Click 'n' drag: box selection of multiple features

2. **Do not activate sync with map by default**. The expected behaviour is to filter features inside the feature grid, and higlight them on the map, but keep the rest of the features visible on the map (unless explicitely requested by the user).

3. **Highlight multiple features**. In this moment only one feature is highlighted. If multiple features are selected the highlighting disappears.

4. **Save (one or multiple) edits in same context**. Currently, when a feature attribute is edited, the featuregrid hides the rest of the features and prompts the user to Save / Discard the edits. This makes editing multiple features very slow.

![image](https://user-images.githubusercontent.com/571129/93859713-416efd00-fcbe-11ea-9836-c4f220959bd4.png)

Rather then having a "confirm" view for the single edit, we want to queue all the edits (multiple features / multiple attributes) and show the Save / Discard button inside the same view showing the list of (edited) features.

![image](https://user-images.githubusercontent.com/571129/93795610-ec89a300-fc39-11ea-8829-5c8694499fae.png)

5. **Multiple edited features in single transaction**. The point above assumes the ability to send edited features in a single transaction, while currently we only have one by one edits.

5. **Copy edits to multiple features**. We want to include the behaviour as from the latter point from @offtherailz comment, i.e. the ability to drag/copy a cell value to multiple features, similar to what we can do with spreadsheets. The behaviour should also support multiple cells (range selection).  This is the demo reported by @offtherailz: https://codesandbox.io/s/cellrangecopypaste-2seht

@tdipisa @offtherailz an estimate is required for all the feature requests above.

**Comment by offtherailz** [comment]
For points 4,5,6 "Already did it in this branch:
https://github.com/offtherailz/MapStore2/tree/NO_focusONedit
It may need to be customizable and tested more. But saving seems to work well"

**Comment by AGMETEOR** [comment]
UPDATE:
All related issues almost closed. Currently, fixing 2 bugs that came up due to enabling multiple feature select. One (#6168) is in progress.

**Comment by AGMETEOR** [comment]
UPDATE:
Pushed a fix for the last reported bug from this epic

**Comment by giohappy** [comment]
@AGMETEOR does it mean that development can be considered completed?
@tdipisa let me know if I can help with a review of the functionality, as soon as it's deployed on MapStore dev server

**Comment by AGMETEOR** [comment]
> @AGMETEOR does it mean that development can be considered completed?
> @tdipisa let me know if I can help with a review of the functionality, as soon as it's deployed on MapStore dev server

Yes, it would be, because all issues belonging to the epic will be complete. But, still waiting for the last PR review before it's merged.

**Comment by tdipisa** [comment]
@giohappy one issue is still in progress (a bug fix, issue opened after tests). I have also opened three new issues after my tests yesterday in the evening. @AGMETEOR is checking them: the epic has been updated.
