### ISSUE TITLE
Search bar returns always a maximun of 15 results even with custom services

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#5929]
## Description
Search bar returns always a maximun of 15 results even with custom services

![image](https://user-images.githubusercontent.com/19175505/94250818-0240e600-ff22-11ea-9140-cf505aee6ba8.png)

## How to reproduce

- open [this map](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/10279)
- click on the cog icon in the serach bar and edit the service
- click on next and modify Max Features with a value over 15, eg 20 (note the maxResults in SearchBar should be the default one 15)
- click on save
- search with the text 'meteorite'

*Expected Result*

- the list of results related to the service has the same length of max features

*Current Result*

- the list of results is always equal to 15 (default maxResults)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by myrdstom** [comment]
<img width="830" alt="Screenshot 2020-10-15 at 13 06 16" src="https://user-images.githubusercontent.com/30922279/96109409-469f2080-0ee7-11eb-9c54-809f7e5ac3c3.png">

The reason we return only **15 results** is on line 31, there is a `maxResults` prop that is hardcoded to `15`. I have tested it out with a hardcoded figure of `100` and it adjusts accordingly. Is there a reason the figure was hardcoded? How should I proceed?

**Comment by myrdstom** [comment]
![Uploading Screenshot 2020-10-15 at 13.27.04.png…]()
I also notice the search result returned multiple unnamed meteorites sites. Is this an issue with the data or how we parse it in our application?

**Comment by tdipisa** [comment]
the second one @myrdstom. There was a typo in the service config (Title field in the form). I've fixed it now.

**Comment by myrdstom** [comment]
> The second one @myrdstom. There was a typo in the service config (Title field in the form). I've fixed it now.

awesome :)

**Comment by MV88** [comment]
> FilePath: web/client/components/mapcontrols/search/SearchBar.jsx
> 
> <img alt="Screenshot 2020-10-15 at 13 06 16" width="830" src="https://user-images.githubusercontent.com/30922279/96109409-469f2080-0ee7-11eb-9c54-809f7e5ac3c3.png">
> 
> The reason we return only **15 results** is on line 31, there is a `maxResults` prop that is hardcoded to `15`. I have tested it out with a hardcoded figure of `100` and it adjusts accordingly. Is there a reason the figure was hardcoded? How should I proceed?

that is not hardcoded, is a default value which if is not present in config it uses 
i think it should be total of the sum of maxFeatures for each service and if not defined inside a service consider 15.

example

service 1 ... max features = 20
service 2 ... max features = 10
service 2 ... max features = not defined i.e. 15

max results = 20 + 10 +15

@tdipisa correct?

**Comment by tdipisa** [comment]
@MV88 it makes sense to me. @offtherailz?

**Comment by myrdstom** [comment]
<img width="603" alt="Screenshot 2020-10-15 at 15 37 47" src="https://user-images.githubusercontent.com/30922279/96127718-27ab8900-0efd-11eb-859a-fc2a4725d907.png">

Before I implement a fix, I need some clarity on a few things. 

**Question 1**

Attached is a screenshot of a log of all services for this map. It shows that the map has 2 services, an `unnamed` service, and the `Meteorites` service. Meteorites has a `maxFeatures === 5`. However, the GUI shows that there is only one service for this map. So is the max result supposed to be 15 or 5

**Question 2**
Is it possible to have a key-value pair similar to `{maxFeatures: undefined}`


My fix will involve improving on the function that calculates these results

**Comment by MV88** [comment]
Question 1:  5 because is only one service with 5 as max features, would be 15 if max features was not defined

Question 2: i think yes, and if you find undefined you need to use 15 as a default value
