### ISSUE TITLE
Details do not work in emedded mode

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#5930]
## Description
The epics (and actions) are in `maps` files that are not included in embedded mode. 
They should be moved in a separate file to make them work ( isolate the Details plugin for map )
Probably also the epic need some more fix to work in this mode.

## How to reproduce

- Try Add Details plugins to apiPlugins.js, 
- add to localConfig.json --> plugins --> embedded
```javascript
{
          "name": "Details",
          "override": { // not sure the override is necessary, i think it is not, because burger menu is not in embedded. Anyway the final effect must be to appear in the navigation toolbar
            "Toolbar": { 
              "priority": 10
            }
          }
```
- try to open a map with Details in embedded mode.

*Expected Result*
The functinalities of Details plugin are running

*Current Result*
No detail card showing on startup (if the option selection), neither the button is available on top

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
blocked by this https://github.com/geosolutions-it/MapStore2/issues/6113

**Comment by myrdstom** [comment]
Can't seem to open a map in embedded mode. Seems to work locally for @MV88. I have debugged the issue with him to no avail

**Comment by tdipisa** [comment]
@myrdstom I think it is a problem on your side: the embedded mode seems running well on DEV and for other developers. If you have problems on troubleshooting this, I can only suggest you to do a new clone of MS and to run again **npm install** on it.
