### ISSUE TITLE
MapStore back-end jar missing in final war

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#5944]
## How to reproduce

- Try to install an extension from cotext manager

*Expected Result*
Extension is installed 

*Current Result*
Extension is not installed, due to a generic error

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
@tdipisa In order to mitigate this problem, we could add the missing mapstore-backend jar(s) to the extisting release files.

**Comment by ElenaGallo** [comment]
@offtherailz on QA the problem is still present. 

*How to reproduce*
- Click on New Context 
- Navigate de wizard untill step 3
- Click on Add an extension
- D&d the SampleExtension 
- Click on Install

*Current result*
It is not possible install an extension and the error on console is:
> POST https://qa.mapstore2.geo-solutions.it/mapstore/rest/config/uploadPlugin 500 (Internal Server Error)
