### ISSUE TITLE
WMS from MapServer does not contains map parameter when it is added as background layer in MapStore

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/MapStore2#5950]
If we try to add a WMS layer (from MapServer) as background we cannot see anything because the map parameter is removed in the request:

We used the following URL to create the catalog:
`http://www502.regione.toscana.it/ows_ofc/com.rt.wms.RTmap/wms?map=owsofc`

![create-the-wms-catalog-01.png](https://images.zenhubusercontent.com/5e98219c18069195a59f5217/35f4c033-421f-4277-9506-1733f14af562)

and the layer **rt_ofc.5k16.32bit**

If we add the layer in the TOC we can see correctly because the map parameter is present.

Here an example of request when the layer is added as backround and the **map** parameter is missing:
`https://www502.regione.toscana.it/ows_ofc/com.rt.wms.RTmap/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=rt_ofc.5k16.32bit&STYLES=&SRS=EPSG%3A3857&CRS=EPSG%3A3857&TILED=true&WIDTH=256&HEIGHT=256&BBOX=939258.2035682462%2C5009377.085697312%2C1252344.2714243282%2C5322463.153553394`

and here an example of request when the layer is added in the TOC and the **map** parameter is present:
`https://www502.regione.toscana.it/ows_ofc/com.rt.wms.RTmap/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=rt_ofc.5k16.32bit&STYLES=&SRS=EPSG%3A3857&CRS=EPSG%3A3857&TILED=true&map=owsofc&WIDTH=256&HEIGHT=256&BBOX=1095801.2374962866%2C5322463.153553393%2C1252344.2714243275%2C5479006.187481434`

**Comment by chpicone** [comment]
@tdipisa can you assign this task to someone?

**Comment by myrdstom** [comment]
The problem probably originating from the client's version. Could not replicate bug after call with @chpicone

**Comment by chpicone** [comment]
Yes, it seems that the version running on the Paul's machine does not contain this bug (**map** parameter is not removed)
