### ISSUE TITLE
Align/Review of some dependencies versions

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#5952]
We have to review the alignment for next MS releases. Versions to use are reported below (those selected are versions yet to be created):

**master**
- [x] print-lib `2.0-SNAPSHOT`
- [x] http-proxy `1.2-SNAPSHOT`
- [x] geostore `1.6-SNAPSHOT`
- [x] mapstore-backend `1.0-SNAPSHOT`

**2020.02.02** and **2020.02.xx**
- [x] print-lib `geosolutions-2.0`
- [x] http-proxy `1.1.0`
- [x] geostore `1.5.0`
- [x] mapstore-backend `1.0`

**2020.03.00** and **2020.03.xx** (as soon as the branch is created, it doesn't exists yet)
- [ ] print-lib `geosolutions-2.0`
- [ ] http-proxy `1.1.0`
- [ ] geostore `1.6.0`
- [ ] mapstore-backend `1.0`

edit from @offtherailz : 
- [ ] For mapstore back-end, we should also schedule deploy on our maven report from jenkins

**Comment by offtherailz** [comment]
can not be tested by hand
