### ISSUE TITLE
Improve styling of MapSwipe bar

### ISSUE THREAD

**Issue by AGMETEOR** [geosolutions-it/MapStore2#5957]
## Description
Make the swipe bar a little bit thinner and with integrated arrows to indicate swipe movement.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features

## Other useful information
Suggested improvements by @simboss 

cc: @tdipisa

**Comment by simboss** [comment]
I have checked around the web and I have seen this implementation ( I think it is using ESRI JS technology) which fits in part what I need (the bar is still too thick).
![image_2020_10_01T09_01_44_649Z](https://user-images.githubusercontent.com/693880/94791124-81796280-03d7-11eb-8e3a-4156f1064c9d.png)

**Comment by AGMETEOR** [comment]
![Screenshot 2020-10-06 at 12 45 58](https://user-images.githubusercontent.com/28563179/95185833-e8c95500-07d1-11eb-943d-c7d8957661cb.png)

**Comment by simboss** [comment]
Hi @AGMETEOR, I'd like the bar itself to be thinner and the two controls of a slightly different color.

**Comment by AGMETEOR** [comment]
> Hi @AGMETEOR, I'd like the bar itself to be thinner and the two controls of a slightly different color.
> Similar to the ESRI example.

Ok... let me share something else shortly.

**Comment by AGMETEOR** [comment]
![Screenshot 2020-10-06 at 13 12 53](https://user-images.githubusercontent.com/28563179/95188917-d3562a00-07d5-11eb-8269-015de51c8b6f.png)
@simboss thoughts?

**Comment by simboss** [comment]
@AGMETEOR nicer.

Just make the vertical bar a little thinner.

**Comment by ElenaGallo** [comment]
@AGMETEOR between the Swipe bar (Horizontal and Vertical) and the selected layer there is empty space.

![extra-space](https://user-images.githubusercontent.com/56537133/95585459-8bd2d680-0a3f-11eb-94d1-851a4961824d.jpg)

**How to reproduce**
- Open a map
- Select a layer on TOC
- Click on Compare tool

*Expected Result*
The layer on the right side of the Swipe bar  does not disappear

**Comment by AGMETEOR** [comment]
@ElenaGallo is it possible you resized the browser window after activating the tool?

**Comment by tdipisa** [comment]
@AGMETEOR I've tested it, it seems to happen when the browser window has been resized.

**Comment by AGMETEOR** [comment]
@tdipisa and @ElenaGallo the issue was reported and this PR fixes
https://github.com/geosolutions-it/MapStore2/pull/5988

**Comment by tdipisa** [comment]
@ElenaGallo I put this issue in test again. Let's wait for the merge of PR #5988
