### ISSUE TITLE
Error in GFI for (imported) vector layer

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#5961]
## Description
Trying to perform info on a vector layer ( from this map https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/10250) I can't see the info and in console I have this

The problem is present also on QA
```
EpicsUtils.js:20 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.buildRequest (vector.js:18)
    at Object.buildIdentifyRequest (MapInfoUtils.js:171)
    at MergeMapSubscriber.eval [as project] (identify.js:221)
    at MergeMapSubscriber._tryNext (mergeMap.js:120)
    at MergeMapSubscriber._next (mergeMap.js:110)
    at MergeMapSubscriber.Subscriber.next (Subscriber.js:89)
    at ArrayObservable._subscribe (ArrayObservable.js:114)
    at ArrayObservable.Observable._trySubscribe (Observable.js:57)
    at ArrayObservable.Observable.subscribe (Observable.js:45)
    at MergeMapOperator.call (mergeMap.js:85)
    at Observable.subscribe (Observable.js:42)
    at Object.subscribeToResult (subscribeToResult.js:22)
    at MergeAllSubscriber._next (mergeAll.js:85)
    at MergeAllSubscriber.Subscriber.next (Subscriber.js:89)
```
## How to reproduce

-  Open map https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/10250
- Click on vector feature

*Expected Result*
The featureinfo shows info about the layer
*Current Result*
Error in console, no info loaded

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by myrdstom** [comment]
Hello @offtherailz , when I click the link to the map: https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/10250, I get the following image. 
<img width="1680" alt="Screenshot 2020-10-14 at 11 29 34" src="https://user-images.githubusercontent.com/30922279/95964365-649a5180-0e11-11eb-90d4-da76c268c8d4.png">

The screenshot menitons afew issues that could be preventing me from viewing the first step of the issue. Do you think it could be any of these? I used testuser/testuser credentials to view the map on dev

**Comment by myrdstom** [comment]
Could be an authentication issue, lemme confirm with a separate account

**Comment by offtherailz** [comment]
I gave you the credentials. A working example is to get this [shape file](https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/physical/ne_110m_lakes.zip) and import it.

FeatureInfo in this case works. You need to find out the reason of this failure and provide a fix/propose a solution.

**Comment by myrdstom** [comment]
<img width="1680" alt="screen" src="https://user-images.githubusercontent.com/30922279/95982974-8b648200-0e29-11eb-9095-b35c1a30d191.png">

As per the screenshot, it appears that the provided map works with the provided shape file... unless there is something I'm missing

**Comment by myrdstom** [comment]
First off please watch the video as it is relevant to the explanation

https://drive.google.com/file/d/1FcirhKfWjpGr6mtKJbzRknhjEw_y25TM/view?usp=sharing


Every vector file is loaded in the TOC from this path: web/client/components/TOC/DefaultGroup.jsx

There is a prop, `this.props.node` which contains the data for all vector files

the data rendered when one clicks say a lake is got from an  object in an example shown below:

node[0].features[0].properties{...lots of data}

from the video, we see three vector files in the TOC, `ne_110m_lakes`,`test`, and `geojson_test`. 

The reason, for example when we click Philipines the sidebar perpetually loads is that the properties section does not have the in the above path has no data. My opinion is that the raster files are missing core data needed for the sidebar to be loaded

**Comment by offtherailz** [comment]
raster files ? probably you mean that the `properties` are not present in the JSON object of the feature.
If you debug, the reason of the issue is clear.
So please propose a fix for this bug to prevent this error, and create a unit test that solves this use case.

**Comment by myrdstom** [comment]
> raster files ? probably you mean that the `properties` are not present in the JSON object of the feature.
> If you debug, the reason of the issue is clear.
> So please propose a fix for this bug to prevent this error, and create a unit test that solves this use case.

will do

**Comment by offtherailz** [comment]
Looking at it, seems like this fixes the problem. Hope it helps to solve the problem
```diff
diff --git a/web/client/utils/mapinfo/vector.js b/web/client/utils/mapinfo/vector.js
index f237b8011..da07e4fbc 100644
--- a/web/client/utils/mapinfo/vector.js
+++ b/web/client/utils/mapinfo/vector.js
@@ -16,7 +16,7 @@ module.exports = {
                 lng: props.point.latlng.lng
             },
             metadata: {
-                fields: layer.features && layer.features.length && Object.keys(layer.features[0].properties) || [],
+                fields: layer.features?.[0]?.properties && Object.keys(layer.features[0].properties) || [],
                 title: layer.name,
                 resolution: props.map && props.map && props.map.zoom && MapUtils.getCurrentResolution(props.map.zoom, 0, 21, 96),
                 buffer: props.buffer || 2,
```

**Comment by myrdstom** [comment]
Hey @offtherailz, I just want to be clear. It would fix the problem in that we return an empty array. The returned empty array means that we don't have a loader that loads forever... On the otherhand, we get a `There is no information available for this point` error returned. See attached screenshot for more clarity. Is this the result we are looking for?

<img width="1353" alt="Screenshot 2020-10-19 at 10 37 20" src="https://user-images.githubusercontent.com/30922279/96415317-13b2a080-11f7-11eb-9a0e-b0d7f2023639.png">
