### ISSUE TITLE
ContextCreator save fails but it is reported as a success

### ISSUE THREAD

**Issue by vlt1** [geosolutions-it/MapStore2#5965]
## Description
When trying to save a context and it fails instead of showing an error notification, ContextCreator closes and displays a success one.

## How to reproduce
Was reproduced on austrocontrol
* Go to Context Manager and press New context
* Go through steps, press Save
* Server will say 404 due to CONTEXT resource type not being present and the context is not saved, but a success notification is shown.

*Expected Result*
Error notification is shown.

*Current Result*
Success notification is shown.

- [x] Not browser related

**Comment by ElenaGallo** [comment]
@vlt1 it is works as expected but, after saving the context, the following error appears on console (both on MS and on austrocontol) :

> GET https://dev.mapstore2.geo-solutions.it/mapstore/extensions.json 404 (Not Found)
