### ISSUE TITLE
Formulas and string formatting for charts

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/MapStore2#5967]
## Description
Currently charts show values based on the actual table data. Having the ability to transform the data values for presentational purposes would be a valuable improvement.
The following two features would by a big plus:

1. Formula: even the basic +, -, *, / (and parethensis) for numeric values 
2. Formatting: something like C/C++ printf. A subset of the usual formatting options would be of course enough. 

E.g. Representing a number as percentege:

Formula: value = value/100
Formatting: "%d %"

## Acceptance criteria

- [x] for numeric values an additional input textarea is provided to insert a basic formula (with validation) 
- [x] charts will show the calcuated value
- [x] beyond x-axis and y-axis combo boxes an input box gives the option to set the format for the values

**Comment by offtherailz** [comment]
This is a preview: 
![image.png](https://images.zenhubusercontent.com/5cd2e72d147fd42f2205c9d1/7d8e79f1-e77e-49dc-b75b-95dd1db0c1b0)

here some helpers to edit format:
![image.png](https://images.zenhubusercontent.com/5cd2e72d147fd42f2205c9d1/4d8fe040-2a62-4314-8aae-123cc5a4a17d)

and formula:
![image.png](https://images.zenhubusercontent.com/5cd2e72d147fd42f2205c9d1/6221a292-5b4b-4427-8ee0-2d55c4884889)

**Comment by tdipisa** [comment]
@offtherailz seems good, please fix the double ':' before and after the helper icon
