### ISSUE TITLE
Swipe/spyglass tool issue with layer group

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#5980]
If the swipe/spyglass tool is active for a layer present in a layer group by clicking on the group the swipe/spyglass tool is still active and works only for the first layer present in a layer group

![2](https://user-images.githubusercontent.com/56537133/95326092-56dd4d00-08a2-11eb-901a-4516fb88f321.gif)

**How to reproduce**

- Open [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/30320) map
- Open the TOC and select 'observatories' layer
- Click on Compare tool
- Select the Default group

*Current Result*

The swipe/spyglass tool is still active and is only active for 'Meteorite landings' layer but not for 'observatories' layer

**Comment by AGMETEOR** [comment]
@ElenaGallo and @tdipisa , I think atm the tool is indeed intended to work for only a single layer. 

cc: @offtherailz

**Comment by offtherailz** [comment]
For the moment is intended to work only for one layer, if change selection, change the layer. If a group is selected, for the moment, we should disable the tool and, **for the future,** support multiple layers, that is not that mess.

**Comment by AGMETEOR** [comment]
@tdipisa I have pushed a fix. Current behavior will be to disable the tool when group is selected
