### ISSUE TITLE
Glitch in toc toolbar

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#5996]
## Description

![bug_toc](https://user-images.githubusercontent.com/11991428/95603352-6ef5cd80-0a56-11eb-99ad-06280b20aac7.gif)

## How to reproduce

-  open [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/10358) map
- open toc
- select layer and deselect it

*Expected Result*

animation working correctly or if we remove animation just to open the toolbar

*Current Result*

glitch

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

we can consider the idea to remove the animation effect, what do you think
@allyoucanmap 
@mbarto 
@dsuren1 
@AGMETEOR 
@offtherailz

**Comment by mbarto** [comment]
Is the vertical movement of the animation by design?
In  any case I don't like animated stuff too much, so +1 from me

**Comment by tdipisa** [comment]
I agree with @mbarto, I think we can remove the animation. +1
