### ISSUE TITLE
Wrong alignement on buttons in story nav bar

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6002]
## Description

If a story is shared with the home button and the user has edit permissions to the story itself, buttont are reported as below in the navbar

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/02925862-e47f-4788-abf3-e75b8387cf05)

## How to reproduce

-  Open for example[ this link](https://qa.mapstore2.geo-solutions.it/mapstore/#/geostory/shared/11555/section/09437688-b6a5-42a6-8eed-59aec7661a09?showHome=true)

*Expected Result*

Edit and Home buttons should be one beside the other

*Current Result*

Edit and Home buttons are one under the other

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@allyoucanmap I don't think it is by design but a regression. Can you confirm please?

**Comment by allyoucanmap** [comment]
> @allyoucanmap I don't think it is by design but a regression. Can you confirm please?

@tdipisa yes, it seems a regression. they should be inline.
