### ISSUE TITLE
Issues saving geometry style or new geometry in an annotation

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#6024]
## Description

- [ ] When you change the style of a geometry the style does not change if you close the style tab delesecting the geometry in the list 
![annotation1](https://user-images.githubusercontent.com/56537133/95979242-a0d2af80-0e1b-11eb-85f5-430bde29be35.gif)

**How to reproduce**
- Open the annotation from [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/30700) map
- Select the line in the list
- Edit the style
- Deselect the line in the list 

*Current result*
The style of the geometry in the map does not change (the only way to be able to save the style is by saving the annotation or selecting another geometry from the list) 

- [ ] From a new annotation it is not possible to add two geometries one after the other
![annotation2](https://user-images.githubusercontent.com/56537133/95979283-afb96200-0e1b-11eb-859a-e8a515069edc.gif)

**How to reproduce**
- Add New annotattion from a new map 
- Click on Add marker
- Draw a marker on map
- Click on Add Line

*Current result*
You can draw the line on the map

**Comment by tdipisa** [comment]
> When you change the style of a geometry the style does not change if you close the style tab delesecting the geometry in the list

if you have multiple geometries and after changing a style you select another geometry, the style is instead maintained without clicking on save. I think we have to harmonize this behavior.
