### ISSUE TITLE
Error page selecting "Display Legend" adding chart widget

### ISSUE THREAD

**Issue by bruncili** [geosolutions-it/MapStore2#6025]
## Description
Redirect the user to an error page when selecting "Display Legend" during the configuration of a new pie chart widget 

## How to reproduce

1. Install MapStore according to https://mapstore.readthedocs.io/en/latest/quick-start/ and release https://github.com/geosolutions-it/MapStore2/releases/tag/v2020.02.01
1. Login to home page (my local address: http://localhost:8082/mapstore/#/ ) 
1. Select new Dashboard 
![image](https://user-images.githubusercontent.com/72010667/95979883-9f55b700-0e1c-11eb-900d-76f45fe5f13c.png)
1. _Add a widget to the dashboard_ 
![image](https://user-images.githubusercontent.com/72010667/95979992-cdd39200-0e1c-11eb-9f11-5ad70671bc55.png)
1. Widget type: chart
1. Add layer 
![image](https://user-images.githubusercontent.com/72010667/95980151-04a9a800-0e1d-11eb-9469-90422d401a8d.png)
1. Chart type: Pie Chart
1. Configure as follow:
![image](https://user-images.githubusercontent.com/72010667/95980321-48041680-0e1d-11eb-8505-566745407566.png)
1. Click on "Display Legend icon"

*Expected Result*

*Current Result*
Error page: 
![image](https://user-images.githubusercontent.com/72010667/95980415-6cf88980-0e1d-11eb-8db2-c15e87e9d5b4.png)

- [] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| 86 |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

Local OS: Windows 10 Home v. 2004

**Comment by tdipisa** [comment]
@bruncili thank you for reporting this. I saw this error happens also on our DEV and QA instances.

**Comment by vlt1** [comment]
@tdipisa It seems that for this map date from wps for year comes in a form of an object like this:
![image](https://user-images.githubusercontent.com/54526151/96113611-178bad80-0eed-11eb-8a21-55bd33f9d477.png)
Is this valid data? I would assume for "year" there would just be a year returned in like a string. Is this something that needs to be handled?

**Comment by offtherailz** [comment]
A small fix like this should avoid the crash. In this case corner cases (e.g. object not handled) I should use a default, to avoid future crashes, and console.log the problem:
```diff
--- a/web/client/components/widgets/enhancers/wpsChart.js
+++ b/web/client/components/widgets/enhancers/wpsChart.js
@@ -7,11 +7,31 @@
   */
 const {compose, withProps} = require('recompose');
 const wpsAggregate = require('../../../observables/wps/aggregate');
+const {isObject, isNil} = require('lodash');
+
 const propsStreamFactory = require('../../misc/enhancers/propsStreamFactory');
 const Rx = require('rxjs');
+/**
+ * Converts the value in a valid value for chart
+ * @param {object} v the value to convert
+ */
+const toValue = v => {
+    if (isObject(v) && !isNil(v.time)) {
+        // in case of date fields geoserver returns an object.
+        // this
+        return (new Date(v.time)).toISOString();
+    } else if (isObject(v)) {
+        // TODO: add a default to make not crash the application. i.e. convert the JSON to string, or hash
+        /* eslint-disable */
+        console.error("cannot parse value of chart coming from WPS");
+        console.error(v);
+        /* eslint-enable */
+    }
+    return v;
+};
 const wpsAggregateToChartData = ({AggregationResults = [], GroupByAttributes = [], AggregationAttribute, AggregationFunctions} = {}) =>
     AggregationResults.map( (res) => ({
-        ...GroupByAttributes.reduce( (a, p, i) => ({...a, [p]: res[i]}), {}),
+        ...GroupByAttributes.reduce( (a, p, i) => ({...a, [p]: toValue(res[i])}), {}),
         [`${AggregationFunctions[0]}(${AggregationAttribute})`]: res[res.length - 1]
     })).sort( (e1, e2) => {
         const n1 = parseFloat(e1[GroupByAttributes]);
```
The remaining problems are these. 
![image](https://user-images.githubusercontent.com/1279510/96132666-f336cd80-0efa-11eb-9e0a-6576cd18c1cb.png)

**Comment by ElenaGallo** [comment]
@vlt1
- [ ] By enabling the legend it is no longer possible to move forward/backward on the panel 
![pie_chart](https://user-images.githubusercontent.com/56537133/96711677-39c67500-139e-11eb-8323-413c677a034c.jpg)

**How to reproduce**
- Open the pie chart as explained above
- Click on Display Legend 

*Current Result*
The topbar is no more clickable

- [ ] The pie chart color is not correct
*Current Result*
![no](https://user-images.githubusercontent.com/56537133/96711689-3df29280-139e-11eb-8e71-bf87200cb825.png)

*Expected Result*
![si](https://user-images.githubusercontent.com/56537133/96711695-41861980-139e-11eb-80e0-ebd88952ed36.png)

**Comment by tdipisa** [comment]
@ElenaGallo this is due to another issue that mainly concerns the legend's generation for pie charts. We van ignore it for the moment.
