### ISSUE TITLE
Issue with Annotations in stories

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6043]
## Description

In map advanced editor of a story, it is not possible to open the colorpicker to change the style. If you try to do this, it is not possible to close the annotation panel

## How to reproduce

It is possible to do a try by using [this story](https://dev.mapstore2.geo-solutions.it/mapstore/#/geostory/11555)

![story_editor_ann.gif](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/7f1bd86e-7730-42b3-8f3e-96a9bdd971d4)

*Expected Result*

It is possible to change the style and close the annotation panel

*Current Result*

You cannot open the the color picker and if you try to open it to change the color, then you cannot close the annotation panel

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by ElenaGallo** [comment]
@dsuren1 In map advanced editor of a story, it is not yet possible to open the popup to change the icon and the shape of the Marker on the Point geometry 
![marker](https://user-images.githubusercontent.com/56537133/96470118-3ca25800-122e-11eb-90e7-e9a80a729f1c.gif)
