### ISSUE TITLE
Requirements collection for Time Series Charts in MapStore

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#6055]
We need to be able to turn time series data into a chart in MapStore, line chart of bar chart.
As an example we can look at the chart we have in the [MapStore CovidTrackingMap](https://www.covidtrackingmap.com/#/) at the bottom.
For a testing layer we can use the meterorites layer that is used in [this map](https://dev.mapstore.geo-solutions.it/mapstore/#/viewer/openlayers/10279).

Ideally I would want to see something like [this](https://www.xe.com/currencycharts/?from=EUR&to=USD&view=1Y) or even better [this](https://plotly.com/javascript/time-series/).

**Comment by simboss** [comment]
@giohappy can you provide more business requirements?

**Comment by giohappy** [comment]
The following two things should be kept into account when designing charts for time series:

 - Time scale representation. The user should be able to configure two alternatives:
     - linear: the time axis is laid out independently from data contents. Only the first and last point are relevant. The axis will be drawn in a linear time scale and the data values (y) will be positioned accordingly
     - series: data are plotted as a normal data series, without considering the time scale.
See for example the [scale distribution configuration](https://www.chartjs.org/docs/latest/axes/cartesian/time.html#scale-distribution) in chartjs
 - Gaps. Many generic libraries consider null values as 0 values, and connect (in the case of line charts) them with previous and next points. The line must be cut instead to represent gaps.

See [this issue](https://github.com/carbon-design-system/carbon-charts/issues/280) from Carbon Design as an example
 
An important thing to keep into account when designing charts for time series are time gaps. 

Time gaps can be of two types:

1) 


Time series might not be complete. So time gaps can be treated in to ways:
  - empty values on the time axis (x): in this case generic chart libraries fall short and connect the dots either through "0 values" or (worst) straight connections between consecutive data points. 
1 - gaps: often charts libraries report gaps as "0", with lines connecting gaps

**Comment by simboss** [comment]
@tdipisa we need to schedule someones time to look into this and prepare an estimate

**Comment by tdipisa** [comment]
Closed in favor of #6135 and #6137
