### ISSUE TITLE
Allow OSM background selection for map with custom CRS

### ISSUE THREAD

**Issue by dsuren1** [geosolutions-it/MapStore2#6057]
## Description
Currently Mapstore allows only specific CRS and layers of type WMS, compatible WMTS and empty to be selectable/clickable from the background selector. 
For projects with custom CRS, we need to at least allow OSM regardless of the CRS, as the Openlayers can reproject on the fly based on the projection defs initialized from local config for the custom CRS

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by ElenaGallo** [comment]
@dsuren1 Opening a New map the background is empty and it is not possible to select any background from the Background Selector
![no_background](https://user-images.githubusercontent.com/56537133/97160504-bf6e6a00-177c-11eb-973d-90d45272e20e.png)

**How to Reproduce**
- Open MapStore
- Open New Map
- Click on the Background Selector

**Comment by dsuren1** [comment]
@ElenaGallo 
I believe the new openlayer map is not loaded in your case and that's the reason for background selector thumbnails are disabled.
This change just allow OSM for custom CRS, and hasn't modified the existing flow. 
Also I tried to reproduce and unfortunately I couldn't.
![new_map_background_selector](https://user-images.githubusercontent.com/26929983/97254595-b8a32e00-1834-11eb-9014-f6735aad88f9.gif)

**Comment by dsuren1** [comment]
@ElenaGallo In order to test with custom CRS, you need to modify the configs of Mapstore or you can test the same in the decsira application https://decsira-dev.geo-solutions.it/decsiraweb2/map.html#/map which uses custom CRS EPSG:32632

**Comment by ElenaGallo** [comment]
@dsuren1 thank you for the note
