### ISSUE TITLE
Fix filter on map active by default

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6075]
## Description

**Make the "filter on map" active by default when entering the editing mode**. The marker icon isn't clear at all, but it wouldn't be a big deal if the action is active by default. 

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/d654c280-ce8a-4705-b4c7-f951041d66b0)

Maybe a configuration option for this can be useful.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Other useful information
The user guide related to the attribute table component is available [here](https://mapstore.readthedocs.io/en/latest/user-guide/attributes-table/).

**Comment by ElenaGallo** [comment]
@AGMETEOR  **Quit the edit mode** the **filter on map** remains active even if no feature has been selected on the map
![filter_on_map](https://user-images.githubusercontent.com/56537133/97700564-58b6bc80-1aac-11eb-875f-40e2969de09d.gif)

**How to reproduce**
- Open [this map](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/31145)
- Open a layer's attribute table
- Click on Edit mode
- Click on Quit edit mode

*Current Result*
The **filter on map** is active on the attribute table

**Comment by tdipisa** [comment]
@ElenaGallo can you explain why it should be an issue?

**Comment by ElenaGallo** [comment]
@tdipisa Because the filter on map should be active by default only in edit mode.

**Comment by tdipisa** [comment]
@ElenaGallo, this issue simply requires to activate the "filter on map" functionality (if not active) every time the user goes in edit mode. It isn't required to deactivate it by going back to view mode of the attribute table, the user can do it manually.
