### ISSUE TITLE
Deactivate MapSync by default

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6076]
## Description

**Do not activate sync with map by default**. The expected behaviour is to filter features inside the feature grid, and higlight them on the map, but keep the rest of the features visible on the map (unless explicitely requested by the user).

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/97f19f51-976e-4d3f-b730-b8ed1691ffef)

Check if a configuration option already exists in MS for this: by default in MS it should be disabled.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Other useful information
The user guide related to the attribute table component is available [here](https://mapstore.readthedocs.io/en/latest/user-guide/attributes-table/).

**Comment by ElenaGallo** [comment]
@AGMETEOR the MapSync button remains active in the following case:


- By enabling MapSync for one layer, MapSync remains enabled for all layers on the map.
![MapSync2](https://user-images.githubusercontent.com/56537133/97691669-f1464000-1a9e-11eb-8131-842cae210d5f.gif)



**How to reproduce**
- Open [this map](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/31145)
- Open a layer's attribute table
- Enable the MapSync button
- Close the Attribute table
- Open the attribute table of another level

*Current Result*
The MapSync button is active
