### ISSUE TITLE
Multiple selection on Map

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6077]
## Description

The filtering on map will be extended with the following:
    - Ctrl + click: add / remove features from filter list

At the moment using the "filter on map" tool the user can select only one feature by clicking on map and the attribute table is filtered accordingly (this happens both in vew and edit mode of the attribute table). There should be the possibility to perform a selection of multiple features with multiple clicks on map (as explained above), the attribute table will be filtered in the same way (in both vew and edit mode as it is now).

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe: improvement on an existing feature

## Other useful information
The user guide related to the attribute table component is available [here](https://mapstore.readthedocs.io/en/latest/user-guide/attributes-table/).

**Comment by ElenaGallo** [comment]
@AGMETEOR when more than one feature has been selected on the map and the SyncMap button is enabled, only the last selected feature is displayed on the map
![filter_map](https://user-images.githubusercontent.com/56537133/98276347-1c94c780-1f96-11eb-99c1-fe1eab3bc62b.gif)


**How to Reproduce**
- Open [this map]() 
- Open a layer's attribute table
- Click on Filter on map
- Select two features on map
- Click on SYNCMap

*Current Result*
It is visbile on map only the last feature selected

**Comment by AGMETEOR** [comment]
Hi @ElenaGallo , seems to be working well. Could you please try again?

**Comment by tdipisa** [comment]
@AGMETEOR I have the same result in DEV 

![image](https://user-images.githubusercontent.com/1280027/98371517-94b5c880-203c-11eb-8621-8224b70e1e34.png)

**Comment by tdipisa** [comment]
@AGMETEOR as we have anticipated during the today discussion (and agreed also with @giohappy), please remove for now the possibility to deselect a selected feature on map with **ctrl+click** since, with the current logic based on spatial WFS filter, this is poorly maintainable to combine it with filters by ID across different actions of select/unselect performed by the user (we have opened this issue for a future improvement #6191). A part from that, please refactor your selection code by using the current filter composition logic by using only spatial filters. Considering this, I think that maybe the PR #6183 can be closed in favor of a new one that provides that refactor (and that should be able to automatically fix also other issues #6185, #6186 and #6187, let me know about that).
