### ISSUE TITLE
Fix Hightlight multiple features

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6079]
## Description

**Highlight of multiple features is required in edit mode**. Currently in edit mode only one feature is highlighted. If multiple features are selected the highlighting disappears.

![fg_selection.gif](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/7c902860-272b-4b92-869c-fb54fa055da6)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe: improvement on an existing feature

## Other useful information
The user guide related to the attribute table component is available [here](https://mapstore.readthedocs.io/en/latest/user-guide/attributes-table/).

**Comment by MV88** [comment]
blocked by #6080
