### ISSUE TITLE
Template update is rendered with old component data

### ISSUE THREAD

**Issue by dsuren1** [geosolutions-it/MapStore2#6089]
## Description
During update of the template, before parseTemplate callback is completed, the component is rendered with the old component data and later forceUpdated with the newer parsed data. This is hard to reproduce as the usage in mapstore is limited and doesn't seem to involve any action performed from the rendered content. However, DECSIRA project depends on the template with some xml parsing based on the rendered content, this causes the application to crash when rendered content contains old component data with missing namespaces.

## How to reproduce
- Launch [this ](https://decsira-dev.geo-solutions.it/decsiraweb2/map.html#/map) application

**Follow the below step**
![decsira_template_fail.gif](https://images.zenhubusercontent.com/5e78827a17a9ae67e20871de/e06f2cc9-a262-409b-8d24-475e5f314665)

*Expected Result*
![decsira_template_expected.gif](https://images.zenhubusercontent.com/5e78827a17a9ae67e20871de/bca52f56-f9ea-4c30-8fe8-888ca326e040)

*Current Result*
When updating the template, the application crashed as the render content is not the updated template 

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by ElenaGallo** [comment]
@dsuren1 The application crashes when printing the template.

**How to Reproduce**
![print](https://user-images.githubusercontent.com/56537133/97158027-330e7800-1779-11eb-8c8f-077caacd6edb.gif)

**Comment by dsuren1** [comment]
@ElenaGallo 
The issue you have found during print is due to wrong pdfname used and needs to be fixed on the Decsira project. This fix on Mapstore deals only with the rendering of the template as given gif (**Expected Result**). So I think you can close this issue, as the pdf name issue will be addressed as part of decsira project.

**Comment by ElenaGallo** [comment]
@tdipisa can i open a new issue for the wrong pdf name as @dsuren1 suggests in the comment above?

**Comment by tdipisa** [comment]
@ElenaGallo, I saw @dsuren1 already opened it [here](https://github.com/geosolutions-it/csi-sira/issues/790). So please close this issue.
