### ISSUE TITLE
Advanced Options display problems on Chart Widget

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#6094]
## Description

Opening the advanced options on the bar or line chart widget and resizing the page panel display problem occurs
 
![image_2020_10_23T08_01_27_798Z](https://user-images.githubusercontent.com/56537133/96978342-8c2e9f80-151e-11eb-966d-765cc6ac3808.png)

## How to reproduce

- Open [this](https://qa.mapstore2.geo-solutions.it/mapstore/#/dashboard/30784) dash
- Edit a bar chart
- Resizing the page
- Open the Advanced Options

*Current Result*

Advanced Options are not displayed correctly on the panel

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
Fixed in 2021.01.00
