### ISSUE TITLE
Ability to disable Identify for a layer

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6101]
## Description

It is required to allow users to disable the Identify functionality per layer.
A new option must be available in Layer Settings (Feature Info Tab) so that the user can disable the identify request at layer level

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/c66d6e32-6481-4f9d-9c90-59cceec8cd00)

A new item in the list above (**DISABLE IDENTIFY**) should be added on top (in capital case like the other ones) for this purpose.

Item title: DISABLE IDENTIFY
Item description: Disable the feature info for this layer

For that item it is not needed to expand a panel to show a preview when the user clicks on it since the option is needed to disable the Identify at all for the layer.

Texts above need to be translated in all supported languages in MS and it must be possilble to persist that setting when the user save the map. 
As a result of this setting, Identify requests are not performed for the layer if **DISABLE IDENTIFY** has been selected. This means that the layer will not be present at all in the Identify side panel dropdown list.

In MapStore there are to possible use cases for Identify operations:

1. **One or more layers are selected in TOC**: in that case MapStore performs Identify requests only for the selected layers (that are available in the dropdown of the Identify side panel). In the context of this issue, if the identify mode of one of the selected layers is set to **DISABLE IDENTIFY**,  the layer will not appear in the list (same behavior of a hidden layer or not queryable layer)

2. **No specific layer is selected in TOC**: in that case MapStore performs Identify requests for all TOC layers in the clicked position. The behavior for layers with **DISABLE IDENTIFY** option enabled is the same reported in the above point: the layer will not appear in the list (same behavior of a hidden layer or not queryable layer)

The **DISABLE IDENTIFY** option **must not be available** in general settings options:

![image](https://user-images.githubusercontent.com/1280027/98359144-08010f80-2028-11eb-94ac-2c02c156c839.png)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by ElenaGallo** [comment]
@myrdstom   Selecting the *States of US* layer on the TOC (set to **DISABLE IDENTIFY**) and clicking *States of US* feature on map the GFI panel opens showing the other feature present on the map (*ETOPO_Shadow* layer)

![GFI](https://user-images.githubusercontent.com/56537133/98569406-8ec91d00-22b2-11eb-821f-4666c78494aa.gif)


**How to reproduce**

- Open [this map](hhttps://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/31273)
- Select *States of US* layer on TOC
- Click on *States of US* feature on map

*Current Result*
The layer selected is *States of US* but the *ETOPO_Shadow* layer is shown on the GFI panel

**Comment by tdipisa** [comment]
@myrdstom we should fix the behavior reported in the above comment. 
If only one layer is selected and for this layer we have the Disable Identify activated, the following message should open:

![image](https://user-images.githubusercontent.com/1280027/98657803-8e786280-2342-11eb-93d9-cb3a620cbf76.png)

**Comment by myrdstom** [comment]
If no layer is selected which of the following images should be returned,
image 1
<img width="1680" alt="Screenshot 2020-11-10 at 13 15 49" src="https://user-images.githubusercontent.com/30922279/98661060-110b1d00-2357-11eb-91d5-a60859107262.png">

image 2
<img width="1272" alt="Screenshot 2020-11-09 at 18 55 13" src="https://user-images.githubusercontent.com/30922279/98661082-15cfd100-2357-11eb-9c47-213548570878.png">

**Comment by myrdstom** [comment]
I have gone with the implementation shown in `image 1` as it is what makes sense to me. Awaiting your confirmation @tdipisa.
In summary

- If one layer is selected and has `DISABLE IDENTIFY` active, we get the `no queryable layers` popup.
- If no layer is selected but one has `DISABLE IDENTIFY` active, we return below. (ny_roads has `DISABLE_IDENTIFY` active)
<img width="1680" alt="Screenshot 2020-11-10 at 13 35 43" src="https://user-images.githubusercontent.com/30922279/98663103-b4f5c800-2359-11eb-8d72-1e3ed438d76d.png">
