### ISSUE TITLE
Multiple filter values in attribute table quick filter

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6102]
## Description

It must be possible for the user to type multiple search values **comma separated** inside the quick filter of Attribute Table (for both MS viewer and dashboard). The search request will include a filter with all values specified for an attribute in OR.

![image](https://user-images.githubusercontent.com/1280027/97024133-bef48a00-1556-11eb-8767-6c08ed39bced.png)

Currently in the quick filter we use the **like** clause for text attributes and for numbers we support one of the following possibilities: number or >number or <number

This must be allowed only for the following attribute types:
- String Attributes: like texta,textb,textn
- Numeric Attributes: 
    1. **At least fixed values such as cases like numbera,numberb.** 
    2. To check if cases like **numbera,<numberb,>numberc** can also be supported easily otherwise we can ignore these cases for the moment and support only fixed values (point 1)

This filter will then need to be translated into both GML and CQL, so it will be necessary to convert it into an **OR** clause.

A sample of map to use for this dev is:
https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/31095

A sample of dashboard to use for this dev is:
https://dev.mapstore2.geo-solutions.it/mapstore/#/dashboard/31090

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by tdipisa** [comment]
@AGMETEOR since you are working on improving the attribute table component, please let @myrdstom aware if developments on this issue will conflict in some way with your work.

**Comment by AGMETEOR** [comment]
> @AGMETEOR since you are working on improving the attribute table component, please let @myrdstom aware if developments on this issue will conflict in some way with your work.

I don't think there'll be any conflicts.
