### ISSUE TITLE
Full screen widgets

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6103]
## Description

It is required to add a control to be able to expand widgets to full screen (in both in viewer and dashboard). The widget must cover the entire viewer space when expanded. The expand tool can be included beside the other ones like (see image below).

![2020_10_23_17_43_24_MapStore_HomePage](https://user-images.githubusercontent.com/1280027/97024730-6b367080-1557-11eb-963a-1240bcef9a1e.png)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by offtherailz** [comment]
Just to confirm @tdipisa , this tool is not available for dashboards (as well as the other collapse/pin ...) tools are not present too, isn't it?

**Comment by offtherailz** [comment]
I approved the PR that adds to the widgets on Map the possibility to be maximized #6225. 
 @tdipisa  Please can you confirm that the this feature doesn't need to be implemented also on dashboard?

**Comment by tdipisa** [comment]
@offtherailz put it in blocked for now, I will take care of this. @vlt1 can't do that.

**Comment by tdipisa** [comment]
@AGMETEOR can you please develop what is missing here? this issue has been partially implemented. We need it for dashboards too.

**Comment by ElenaGallo** [comment]
@AGMETEOR in the dashboards, making the widget full screen, you can still click on the menu bar and on the widget bar (left). The toolbars should be darkened.

**How to reproduce**
- open a dash
- click on maximize from a widget
- click on burger menu

*Exprected Result*
![xs](https://user-images.githubusercontent.com/56537133/102111307-81193100-3e36-11eb-90c6-3ed765bb4e95.png)

*Current Result*
![no](https://user-images.githubusercontent.com/56537133/102111311-837b8b00-3e36-11eb-8974-fcb405ea0398.png)

**Comment by tdipisa** [comment]
@ElenaGallo @AGMETEOR 
the issue n°2 above happens also if you simply drag a widget, see the GIF below. Therefore it doesn't just happen in the case reported above, it is a general issue I think.

![dash_bar](https://user-images.githubusercontent.com/1280027/102196196-d8afaf00-3ebf-11eb-8452-e6891cc4d75f.gif)
