### ISSUE TITLE
Gray warning using map settings

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6114]
## Description

Clicking on map settings from menu options generates a gray page

## How to reproduce

![map_settings.gif](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/82bb92a1-cded-4f37-bc68-785a5788b9a2)

*Expected Result*

The setting modal must opens

*Current Result*

The gray page appears

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by MV88** [comment]
part of #6026

**Comment by tdipisa** [comment]
Seems to be solved by #6108
