### ISSUE TITLE
Widget tool button should be hidden when a raster layer is selected

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/MapStore2#6115]
## Description
Widgets aren't supported for raster layers. When a raster layer is selected inside the TOC I wouldn't expect to see the widget button available.
Indeed, if I try to click any widget type i get the information message that the widget functionality is not available for that layer. 

![image](https://user-images.githubusercontent.com/571129/97297638-96b8a400-1852-11eb-8b35-a6ab293bd496.png)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features

**Comment by MuhweziDeo** [comment]
@tdipisa I am currently blocked on this task since I am currently unable to find how to determine if a selected layer is raster. I have made some consultations to see if there is a way to determine if a layer is a raster layer.

**Comment by tdipisa** [comment]
@MuhweziDeo the logic to determine if a layer is a raster should be already in place. @allyoucanmap @offtherailz can you provide some assistance with this?
