### ISSUE TITLE
If the services are in HTTP, then GetCapabilities requests must be sent in HTTP

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#6127]
## Description

If  a map with HTTPs URL has the services in HTTP the service requests must remain in HTTP and not in HTTPS as it happens now.
## How to reproduce

-  Open [this map](https://dev.mapstore.geo-solutions.it/mapstore/#/viewer/openlayers/5849)
-  On console open a layer request

*Expected Result*

Request is in  HTTP, as follows:

> http://encws.geo-solutions.it/geoserver/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=EMSA%3AS52%20Standard&STYLES=&SRS=EPSG%3A4326&CRS=EPSG%3A4326&TILED=false&WIDTH=1085&HEIGHT=879&BBOX=35.71878433227539%2C14.203777313232422%2C36.020565032958984%2C14.576282501220703

*Current Result*

Request is in HTTPs, as follows:

> https://encws.geo-solutions.it/geoserver/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=EMSA%3AS52%20Standard&STYLES=&SRS=EPSG%3A4326&CRS=EPSG%3A4326&TILED=false&WIDTH=1085&HEIGHT=879&BBOX=35.71878433227539%2C14.203777313232422%2C36.020565032958984%2C14.576282501220703

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@ElenaGallo I don't think it is possible for security reasons of mixed content.

**Comment by simboss** [comment]
I understand what you mean but the MapStore behaviour is not correct.

It should prevent me from adding to the catalog something which is in HTTP while instead right now I can.
This means it sends a GetCapabilities and allows me to add layers from it which then fails.

This will confuse users even very smart ones like me ;)

**Comment by tdipisa** [comment]
@simboss ok I understand your point.

**Comment by tdipisa** [comment]
@MuhweziDeo yes, we have to allow using HTTP only if MS is under HTTP. We need a proper check for this.

**Comment by offtherailz** [comment]
@ElenaGallo for testing the case /geoserver/wms you should receive a different error, while saving, that the one given by the http/https mismatch

**Comment by ElenaGallo** [comment]
@offtherailz test in dev done, you can merge the backport
