### ISSUE TITLE
Proxy forced to use http (non secure)

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#613]
This line: 
https://github.com/geosolutions-it/MapStore2/blame/master/web/client/libs/ajax.js#L117

forces the proxy to be called in http, non  #https. We can replace `http://` with `//` (protocol relative) but why change the relative url `proxyUrl` (that should be something like `/mapstore/proxy/`) with `http(s)://currentdomain/mapstore/proxy` ? It is the definition of domain relative path. 

The only different behiviour happens when the proxyUrl is relative to the path (without the `/` on start) but in this case maybe it is wanted. 

In my opinion we can remove this part
```
                if (proxyUrl.match(/^http(s)?:\/\//i) === null) {
                    proxyUrl = 'http://' + window.location.host + proxyUrl;
                }
```

**Comment by mbarto** [comment]
We cannot remove this completely, we can change the rule to accept // starting urls as valid and not apply the replacement for those

**Comment by offtherailz** [comment]
To clarify I report the various use cases:
<hr/>
ProxyURL: /mapstore/proxy (domain relative)
* window.location : `http://some.domain/app` => window.host : `some.domain`

`/mapstore/proxy` => `http://some.domain/mapstore/proxy` (the same of keeping `/mapstore/proxy`)

* window.location : `https://some.domain/app` => window.host : `https://some.domain`

`/mapstore/proxy` => `http://some.domain/mapstore/proxy`

This is allowed only if the domain has cors, otherwise it is forbidden by the browser. (keeping `/mapstore/proxy` will do the correct request to  `https://some.domain/mapstore/proxy` ) 
<hr/>
ProxyURL: mapstore/proxy (path relative)

* window.location : `http://some.domain/app` => window.host : `some.domain`

`mapstore/proxy` => `http://some.domainmapstore/proxy` This is an error (keeping `/mapstore/proxy` will work in this case, and if the relative proxyUrl is a configuration error)

* window.location : `https://some.domain/app` => window.host : `some.domain`
`/mapstore/proxy` => `http://some.domainmapstore/proxy` This is allowed only if the domain has cors, otherwise it is forbidden by the browser.(keeping `/mapstore/proxy` will work in this case, and if the relative proxyUrl is a configuration error)

<hr/>
ProxyURL: `http://someother.domain/mapstore/proxy` (absolute)
* window.location : `http://some.domain/app` 
`http://someother.domain/mapstore/proxy` => `http://some.domain/mapstore/proxy` (the same of keeping `/mapstore/proxy`)
* host: `https://some.domain` 
`http://someother.domain/mapstore/proxy` => `http://some.domain/mapstore/proxy` This is allowed only if the domain has cors, otherwise it is forbidden by the browser. (keeping `/mapstore/proxy` will do the correct request to  `https://some.domain/mapstore/proxy` ) 
<hr/>
So in any case the check in the issue useless or even harmful. Can you find a use case when it is useful ?
