### ISSUE TITLE
Linear/Series Charts

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6134]
## Description

Using PlotyJS, this can be implemented adding to the UI a tool that allows to select this option to the chart. It is supported by PlotyJS.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by offtherailz** [comment]
Here how the Advanced Options change to support this:

![image](https://user-images.githubusercontent.com/1279510/98361432-ceca9e80-202b-11eb-82d1-65416e4207d8.png)

The entries are better organized, and some new options are added: 

New options are :
 - Axis type (see below) 
- X-Axis Hide  / Never skip labels: can be useful to adjust the look and feel of small charts with long labels. 

The Axis types are these:
![image](https://user-images.githubusercontent.com/1279510/98361499-ee61c700-202b-11eb-83c8-b23645da4512.png)
- **Auto** (automatic recognition, the default)
- **Category**: Each x value is a column
- **Linear**: the axis is linear, so with values for x 1 and 3, we have the 2 in the middle
- **Log**: log scale
- **Date**: the axis value is parsed as a date.

These options are valid for both X and Y and they open the possibilitis of a big set of charts, expecially when not grouping.
