### ISSUE TITLE
Data Gaps for Charts

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6135]
## Description

Using PlotyJS, this does not require any work, except the skipping aggregation. 

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Other... Please describe: Chart improvement

## Other useful information
See also #6055.

**Comment by ElenaGallo** [comment]
@offtherailz If the operation is set to *no operation*, there are sometimes white lines on the bars of the Bar chart

![line](https://user-images.githubusercontent.com/56537133/99547529-ebfe5600-29b7-11eb-8a32-6314ea0041ce.JPG)
