### ISSUE TITLE
Skip Aggregation on charts

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6136]
## Description

The [spike](https://github.com/offtherailz/MapStore2/blob/wfs_chart/web/client/components/widgets/builder/wizard/ChartWizard.jsx) provided works perfectly. Also filtering by sync map in the dashboard works perfectly. We need also to provide some unit testing and possible fixes on the data retrieve side. It already uses propertyName to get only the attribute involved, without geometries.

Instead on the UI side we have to decide if doing it automatically (if the user do not select the aggregation method) or by explicit selection of a checkbox “do not aggregate”. To verify how having the automatic version influences the performances.

When data is valid, the preview starts getting data, if we want to parse big databases, we may have problems during selection (e.g. select X, Y, want to select group by but it starts downloading a lot of data to generate the preview). 

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Other... Please describe: Charts improvements

## Other useful information

Actually MapStore supports only chart generation using WPS process “Aggregate”. We can go over this limitation in 2 ways:
- Use an alternative service that do not need aggregation
- Support WFS for chart generation (in case no aggregation method has been chosen)

This task is independent from the effective chart library we choose. This analysis includes only the option about using WFS.

**Comment by ElenaGallo** [comment]
@offtherailz If the operation is set to *no operation*, there are sometimes white lines on the bars of the Bar chart

![line](https://user-images.githubusercontent.com/56537133/99547529-ebfe5600-29b7-11eb-8a32-6314ea0041ce.JPG)

**Comment by offtherailz** [comment]
Because the values are multiple for each value, They are stacked on the same line, the white lines are the separation between the stacked bars.
We could plan to improve styling to make it more evident, and it's more or less the same issue of colors in pie charts reported here https://github.com/geosolutions-it/MapStore2/pull/6163#pullrequestreview-525028583 . 
We should open a separate issue to improve charts color (as suggested on the same PR discussion).

**Comment by ElenaGallo** [comment]
@tdipisa can I open a separate issue for the problem explained above?

**Comment by tdipisa** [comment]
@ElenaGallo yes please, I think it is a low priority now, I will schedule a milestone.
