### ISSUE TITLE
Time Series

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6137]
## Description

Time series are only a mix of the following improvements:
- Recognizing the time x-axis condition
- Linear x-axis mode (instead of series/category)
- Formatting the X axis accordingly

Plotly should recognizes automatically the timestamp as X value so no work is needed.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes 
- [X] Other... Please describe: Charts improvements

## Other useful information
See also #6055.

**Comment by offtherailz** [comment]
#6169 solves also this. So as well as it is merged, we can start testing also this

**Comment by offtherailz** [comment]
reopen because of https://github.com/geosolutions-it/MapStore2/pull/6855
