### ISSUE TITLE
WPS Download client

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6156]
## Description

A critical enhancement to the current use cases in MapStore is the implementation of an asynchronous interface. This means that the following key points must be designed and implemented:

- download estimator request to validate the download request (gs:DownloadEstimator) according to the configured limits for the WPS process
- request async execution (gs:Download)
- track execution status
- manage execution results, which will be requested as “reference” results to be obtained as link to downloadable files

The execution request will use the following parameters:

- layerName 
- outputFormat 
- targetCRS 
- filter (only for vector data)
- ROI
- RoiCRS
- cropToROI 
- writing parameters 

First three parameters are those already adopted by the current “Export Data” window. 
The filter parameter will restrict the export to a subset of data. The filter will be defined with the already existing MapStore filter panel and/or (in case of vector layers) through the FeatureGrid filters.

The ROI+RoiCRS+cropToROI parameters will be used to support cropping the dataset to the map viewport.

The [writing parameters](https://docs.geoserver.org/stable/en/user/community/wps-download/rawDownload.html#writing-params) are especially useful for raster data to, for example, request a specific compression format or the tile sizes of the downloaded file.

### Important Note:
_The implementation of the WPS async interface client will be as generic as possible, so that it will be possible to adopt it for different processes and contexts with minimal effort. A specific business logic layer will be implemented on top of it for the specific purposes of the “data export” process._

## Other useful information
- Geoserver WPS module: https://docs.geoserver.org/stable/en/user/community/wps-download/index.html
- OGC WPS Standard: https://www.ogc.org/standards/wps

**Comment by offtherailz** [comment]
This can be unblocked as well as the PR #6156 is merged
