### ISSUE TITLE
New Icon needed for disable identify

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6159]
## Description

A new icon is needed for the folowing
![image](https://user-images.githubusercontent.com/1279510/98094806-11547580-1e8a-11eb-9dc9-3b7ffd3f1572.png)

that has been developed for #6101. The new icon should be provided as soon as the PR [here](https://github.com/geosolutions-it/MapStore2/pull/6128) is merged.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by allyoucanmap** [comment]
@tdipisa here the two proposals, probably the second one is better?

![image](https://user-images.githubusercontent.com/19175505/99989494-fbfca800-2db2-11eb-88ab-94d81603527d.png)

![image](https://user-images.githubusercontent.com/19175505/99989368-d40d4480-2db2-11eb-8ac1-332bcc3acf9e.png)

![image](https://user-images.githubusercontent.com/19175505/99989570-0fa80e80-2db3-11eb-8634-e8fa71d4aa54.png)

**Comment by tdipisa** [comment]
@allyoucanmap I prefer the second one. Thank you.
