### ISSUE TITLE
Error with Mapserver WFS layer

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#6166]
## Description
Error with Mapserver WFS layer.
MS Catalog accepts the source, and shows all layers, but when I add a layer to map, it does not show. No error is reported

## How to reproduce
Use [this](http://ogc4u.geosrbija.rs/test/rpj/wfs?request=getcapabilities&service=wfs&version=2.0.0) WFS getcapabilities service.
Add it to MS catalogue and try add one layer to the map

*Expected Result*
I see something on the map.

*Current Result*
Nothin happens, no error message.

- [x] Not browser related

**Comment by offtherailz** [comment]
WFS doesn't intercepts the error from the server due to invalid srs.

```
<?xml version="1.0" encoding="UTF-8"?>
<ows:ExceptionReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ows="http://www.opengis.net/ows" version="1.1.0" language="en-US" xsi:schemaLocation="http://www.opengis.net/ows http://schemas.opengis.net/ows/1.0.0/owsExceptionReport.xsd">
  <ows:Exception exceptionCode="InvalidParameterValue" locator="srsname">
    <ows:ExceptionText>msWFSGetFeature(): WFS server error. Invalid GetFeature Request:Invalid SRS.  Please check the capabilities and reformulate your request.</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>
```
to display an error. 

Usually we have this on WMS when some error occours: 

![image](https://user-images.githubusercontent.com/1279510/99659253-e01a9e80-2a60-11eb-8e6b-478c0a7bbd14.png)

One simple solution is to handle WFS errors this way. Could this be enough ?

**Comment by tdipisa** [comment]
@offtherailz yes I think so. It is at leas important the MapStore reports the error in some way if the problem doeasn't depends by MS
