### ISSUE TITLE
Update Style button not working properly

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#617]
Steps to replicate:

- load the [demo](http://qa.mapstore2.geo-solutions.it/mapstore/examples/rasterstyler/)
- select one layer at your choice
- change opacity
- update style button does not work

**Comment by kappu72** [comment]
Apply Style button is disabled when in pseudo-color style type, user has to create a color map before applying a style. 
I suggest also to disable opacity selector.
