### ISSUE TITLE
Embedded do not work in standard projects

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#6172]
## Description

In the standard project, we reuse the product `localConfig.json` (MapStore2/web/client/localConfig.json) by default, setting it up in `app.jsx`. Anyway this configuration is not used by the embedded or api bundles, so:
- `themePrefix` is set to `ms2`, instead of the project's one
- `translation` files cannot be loaded (because of the different path)

Moreover `apiPlugins.js` has problems loading new import syntax and need to be migrated, something similar to the code at the end of the issue. 

So these additional steps are required to make it work.
- copy the `localConfig.json` in the root, set it in app.jsx to share
- add `themePrefix` and `translationsPath` to `localConfig.json`
- solve the import problem, rewriting the app plugins file in your own build of `api` and `embedded` entries (see `webpack.config.js`)

We need to find out a way to share the configuration set in `app.jsx` from all the builds. This can be a part of semplification of projects.

## How to reproduce
-  create a mapstore project
-  try to share a map as embedded

*Expected Result*
The embedded map works

*Current Result*
The embedded 

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

apiPlugins.js
```javascript
/**
 * Copyright 2020, GeoSolutions Sas.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

import BackgroundSwitcherPlugin from '../plugins/BackgroundSwitcher';
import DrawerMenuPlugin from '../plugins/DrawerMenu';
import FeedbackMaskPlugin from '../plugins/FeedbackMask';
import GoFullPlugin from '../plugins/GoFull';
import IdentifyPlugin from '../plugins/Identify';
import LocatePlugin from '../plugins/Locate';
import MapFooterPlugin from '../plugins/MapFooter';
import MapLoadingPlugin from '../plugins/MapLoading';
import MapPlugin from '../plugins/Map';
import OmniBarPlugin from '../plugins/OmniBar';
import SearchPlugin from '../plugins/Search';
import TOCPlugin from '../plugins/TOC';
import ToolbarPlugin from '../plugins/Toolbar';
import ZoomAllPlugin from '../plugins/ZoomAll';

import ReactSwipe from 'react-swipeable-views';
import SwipeHeader from '../components/data/identify/SwipeHeader';
export const plugins = {
    // framework plugins
    BackgroundSwitcherPlugin,
    DrawerMenuPlugin,
    FeedbackMaskPlugin,
    GoFullPlugin,
    IdentifyPlugin,
    LocatePlugin,
    MapFooterPlugin,
    MapLoadingPlugin,
    MapPlugin,
    OmniBarPlugin,
    SearchPlugin,
    TOCPlugin,
    ToolbarPlugin,
    ZoomAllPlugin
};
export const requires = {
    ReactSwipe,
    SwipeHeader
}
export default {
    plugins,
    requires
};
```

**Comment by tdipisa** [comment]
@allyoucanmap please provide a comment here providing the way to troubleshoot it.

**Comment by allyoucanmap** [comment]
If we want to have complete control on the embedded we should add a new entry in the webpack based on how the current project are working.

To fix this issue we should introduce a new entry in the webpack dev and prod of the standard project templates (I did not tested the below code yet):

https://github.com/geosolutions-it/MapStore2/blob/master/project/standard/templates/webpack.config.js#L9

```
{
       ...,
        '__PROJECTNAME__-embedded': path.join(__dirname, "js", "embedded"),
        ...
},

```

new js/embedded.jsx
```js
import { loadVersion } from '@mapstore/actions/version';
import appConfigEmbedded from '@mapstore/product/appConfigEmbedded';
import apiPlugins from '@mapstore/product/apiPlugins';
import main from '@mapstore/product/main';
import { checkForMissingPlugins } from '@mapstore/utils/DebugUtils';
import { setConfigProp } '@mapstore/utils/ConfigUtils';

/**
 * Add custom (overriding) translations with:
 *
 * setConfigProp('translationsPath', ['./MapStore2/web/client/translations', './translations']);
 */
setConfigProp('translationsPath', './MapStore2/web/client/translations');
setConfigProp('themePrefix', '__PROJECTNAME__');

/**
 * Use a custom plugins configuration file with:
 *
 * setLocalConfigurationFile('localConfig.json');
 */
setLocalConfigurationFile('MapStore2/web/client/localConfig.json');

checkForMissingPlugins(apiPlugins.plugins);

main(
    appConfigEmbedded,
    apiPlugins,
    (cfg) => ({
        ...cfg,
        initialActions: [loadVersion]
    })
);

```

**Comment by tdipisa** [comment]
@allyoucanmap can you please include what is still missing for new MS projects as you reported above.
