### ISSUE TITLE
MapSwipte shouldn't be deactivated when the layer is deactivated

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/MapStore2#6179]
## Description
To me this is an unexpected behaviour: when the MapSwipe tool is activated for a layer it must be activated again if we select/unselect the layer itself. In my opinion the MapSwipe tool should remain selected when toggling the layer.

![ezgif-2-aa9bb3fccdc0](https://user-images.githubusercontent.com/571129/98704592-1da26c00-237d-11eb-97f6-ac218a848f08.gif)

**Comment by ElenaGallo** [comment]
@AGMETEOR Now if I have activated the MapSwipe for a layer, it remains active even when opening another map

**How to reproduce**
Follows the steps shown in the gif below
![swipe](https://user-images.githubusercontent.com/56537133/100632839-9ae25080-332d-11eb-9c10-a5dd8750d9ee.gif)


*Expected Result**
The MapSwipe tool is disabled when a new map is opened

**Comment by AGMETEOR** [comment]
> @AGMETEOR Now if I have activated the MapSwipe for a layer, it remains active even when opening another map
> 
> **How to reproduce**
> Follows the steps shown in the gif below
> ![swipe](https://user-images.githubusercontent.com/56537133/100632839-9ae25080-332d-11eb-9c10-a5dd8750d9ee.gif)
> 
> _Expected Result_*
> The MapSwipe tool is disabled when a new map is opened

Thanks @ElenaGallo . Pushed a fix here https://github.com/geosolutions-it/MapStore2/pull/6277
