### ISSUE TITLE
Attribute Table - Multiline editing Issue

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6185]
## Description

When using the new multiline edit functionality, record visualization is not proprely managed: 

- Some records disapears cancelling the edit operation (it seems the filter is lost, see the GIF below).
- Some records disapears after saving modifications

## How to reproduce

- Open [this map](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/10358)
- Follow the steps reported in the GIFs below

**Cancel a modification**
![fg_edit_1.gif](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/8a0a3017-1602-4403-b25c-617c9a481c8f)

**Save a modification**
![fg_edit_2.gif](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/a917c21a-ca72-4a64-a177-4e89f0584293)

*Expected Result*

All initial filtered records (by clicking on map) should be retained.

*Current Result*

Only one of them is retained: the one with the multiline edit tool active on it

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

There are similar results also editing field by field, see the GIFs below:

![fg_edit_3.gif](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/1ae37c4c-0c77-4e1d-81e3-2f9050ce8e60)

![fg_edit_4.gif](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/6f027b7c-d4e9-4a9d-8ef5-8f76e27b1ad3)

**Comment by ElenaGallo** [comment]
@AGMETEOR Interacting with the new multiline editing functionality and editing field by field causes an inconsistency after saving

**How to reproduce**
- Open [this map](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/10358)
- Follow the steps reported in the GIFs below
![si](https://user-images.githubusercontent.com/56537133/99558627-384f9300-29c4-11eb-972d-4c547336a138.gif)




*Expected Result*

The initial filtered records (by clicking on map) is change after the editing (field by field ) so only the selected record should be filtered 


*Current Result*

Even unfiltered records remain filtered

**Comment by tdipisa** [comment]
@ElenaGallo the work in in @offtherailz hands, you have to refere to him.

**Comment by offtherailz** [comment]
This is a thing of database sorting. MapStore can not preserve the order, (at least until restructure the system to keep features on client)

**Comment by tdipisa** [comment]
@ElenaGallo there is nothing we can do for this I think as @offtherailz reported.
