### ISSUE TITLE
Attribute Table - Selection remain active while generating charts

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6186]
## Description

If you generate a chart from the Attribute Table when the "filter on map" tool is active, the "box selection" remain active along with the selection on map but it shouldn't. The same if you close the chart side panel while generating a chart without saving the chart itself.

## How to reproduce

-  Open [this map](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/10358)
- Follow the steps reported in the GIF below

**Open the chart side panel to generate it**
![fg_edit_5.gif](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/6306d52a-f323-4ebe-b53a-1e11085f42ee)

**Close the Chart side panel without save**
![fg_edit_7.gif](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/4f81609a-5cbf-41f1-9bc0-347e7ce7f4d2)

*Expected Result*

- The "box selection" functionality shouldn't be active while generating charts from attribute table (TBD about the selection on map). 

- Features selection on map should disappear closing the side panel without save.

*Current Result*

- Both "box selection" and the selection on map are active while generating charts.

- Selection on map is retained closing the side panel

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
@ElenaGallo this can be tested as well as I do my PR with all the fixes

**Comment by ElenaGallo** [comment]
@offtherailz 
If you create a chart from the Attribute Table when the "filter on map" tool is active, the "select box" disappears on the map but the chart is generated with the "filter on map" active.

**How to reproduce**

-  Open [this map](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/10358)
- Follow the steps reported in the GIF below

**One feature is filtered on the map**
![table1](https://user-images.githubusercontent.com/56537133/99969306-8d135500-2d9a-11eb-850c-fe37d54dc1ce.gif)

**More features are filtered on the map**
![table2](https://user-images.githubusercontent.com/56537133/99971122-1035aa80-2d9d-11eb-9adb-5c8da6e59214.gif)

*Expected result*

**One feature is filtered on the map**
The "filter on map shouldn't be active while generating charts from attribute table

**More features are filtered on the map**
Charts can be generated

**Comment by offtherailz** [comment]
Ok, able to relicate, happens when there is an or filter, where cusomize operator with "OR" and it is not supported yet.
Please when testing pay attention to this issue
https://github.com/geosolutions-it/MapStore2/issues/6221
