### ISSUE TITLE
There is an error with click on map in Cesium

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#6196]
## Description

Here is the error i get when clicking on a 3d map.

![image](https://user-images.githubusercontent.com/11991428/99368091-0dc5e300-28bb-11eb-97f4-b1db2e58e2f5.png)

## How to reproduce

- open demo map 
- go to 3d and open dev tools
- click on map and move the mouse

*Expected Result*

To see the identify info panel with correct results

*Current Result*

the errorr in console

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

A crash happen in the release

**Comment by tdipisa** [comment]
@MV88 I also see a lot of console logs while loading the 3D map

![image](https://user-images.githubusercontent.com/1280027/99376385-2804be80-28c5-11eb-8067-a7ac3e4aac1e.png)

**Comment by dsuren1** [comment]
**Question**
1. Looking at the error log (screenshot), the error was generated from leaflet (specifically from hook registered for _GET_PIXEL_FROM_COORDINATES_HOOK_)
2. Was the map click supported earlier in the cesium map implementation we have? Because I don't see any support for this. Kindly correct me if I'm wrong

**Comment by tdipisa** [comment]
@dsuren1 

>1. Looking at the error log (screenshot), the error was generated from leaflet (specifically from hook registered for GET_PIXEL_FROM_COORDINATES_HOOK)

Which is the question?

>2. Was the map click supported earlier from the cesium map implementation we have? Because I don't see any support for this. Kindly correct me if I'm wrong

It should be, @offtherailz @MV88 ?

**Comment by MV88** [comment]
> * Looking at the error log (screenshot), the error was generated from leaflet (specifically from hook registered for _GET_PIXEL_FROM_COORDINATES_HOOK_)

i don't think leaflet is involved here. i mean, i went to 3D from openlayers.

> * Was the map click supported earlier from the cesium map implementation we have? Because I don't see any support for this. Kindly correct me if I'm wrong

i do not remember if the feature info was supported before. honestly i think it was not. anyway is there a way to prevent that error?

**Comment by offtherailz** [comment]
As far as I remember, the `GET_PIXEL_FROM_COORDINATES_HOOK` in this case was not needed because it was fully simulated. The coordinates should already be present in the click info, and the `onClick` handler is implemented, so probably this bug arrived in the past release (you can see the error in the past release).

**Comment by dsuren1** [comment]
@offtherailz @MV88 Thanks. I will check where this issue was introduced and proceed with a fix accordingly.

**Comment by ElenaGallo** [comment]
@dsuren1 the problem mentioned in the [comment](https://github.com/geosolutions-it/MapStore2/issues/6196#issuecomment-728826422) above regarding the log is still present on DEV

**Comment by dsuren1** [comment]
> @dsuren1 the problem mentioned in the [comment](https://github.com/geosolutions-it/MapStore2/issues/6196#issuecomment-728826422) above regarding the log is still present on DEV

Hi @ElenaGallo 
Those are generic error (mostly _info_ log) generated by cesium library itself. We can't do anything about it. This bug fix addresses the code error reported  in this [comment](https://github.com/geosolutions-it/MapStore2/issues/6196#issue-744545094)
