### ISSUE TITLE
Attribute Table - multiselection issue 

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6206]
## Description

On bbox selection, with the UNESCO layer, applying the selection in the animation below and scrolling down, some feature seems not to be loaded correctly. 

![missing-feature](https://user-images.githubusercontent.com/1279510/99378833-2ee10080-28c8-11eb-8e26-43e413fc97be.gif)

*Expected Result*

Features should be loaded correclty in Attribute Table

*Current Result*

The selection is applied only on the first 20 features, but this is a pre-existing issue (to simulate, I zoomed out to level 0 and clicked on italy, to create a gemetric filter that includes most of the features), but the features where loaded correctly.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by ElenaGallo** [comment]
Blocked by #6234
