### ISSUE TITLE
Fix "StoryMap" with "GeoStory" in documentation

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6209]
## Description

Some parts of the documentation contains the text "StoryMap" but it should be "GeoStory", check the whole documentation and replace it.

*Documentation section involved*
- [X] User Guide
- [X] Developer Guide

**Comment by tdipisa** [comment]
@ElenaGallo this PR should fix also documentation, please do a double check.

**Comment by ElenaGallo** [comment]
Closed in favor of #6210
