### ISSUE TITLE
Style charts improvement

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#6217]
## Description

* Make more evident the white line present on a Bar Chart when there are multiple values on x value (related to this  https://github.com/geosolutions-it/MapStore2/issues/6136#issuecomment-729742593)

* Pie charts have no separation lines (related to the second point of this https://github.com/geosolutions-it/MapStore2/pull/6163#issuecomment-723030470)

*Current Result*

**Bar Chart**
![line](https://user-images.githubusercontent.com/56537133/99682677-c9377480-2a7f-11eb-9a79-fb86e3b0f7ea.JPG)

**Pie Chart**
![pie_chart](https://user-images.githubusercontent.com/56537133/99682688-cc326500-2a7f-11eb-8d8e-2d4000c0de3c.JPG)

**Comment by tdipisa** [comment]
Closed in favor of #7039

**Comment by ashraf-alsamman** [comment]
![New Project](https://user-images.githubusercontent.com/10475474/126918774-fb574f43-0e1e-43c4-bb32-99e34e565e64.png)

**Comment by ale-cristofori** [comment]
This issue is closed in favour of [7731](https://github.com/geosolutions-it/MapStore2/issues/7731)
