### ISSUE TITLE
Problem displaying MapSYNC popoup 

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#6235]
When opening the attribute table the MapSYNC popup is not located above the MapSYNC button
![popup](https://user-images.githubusercontent.com/56537133/99981219-67da1300-2da9-11eb-9c30-0c4ff99699c3.JPG)

**Comment by offtherailz** [comment]
Using git bisect, I identified that the bug was introduced in this list:

```
here are only 'skip'ped commits left to test.
The first bad commit could be any of:
4d46bd687fa6323898211fac924e8b0f79c59480
2e672e07966d2059273c2a92219edb574fcdc436
79c853350cd6191325dea5300a42f6488e52d208
1d8970e06ad9322e19c4f1a01684660b95eb056a
9e2d4a4778f08a9c906214b26fbe44628797e265
8473168377936e2b7a259c29493f471da3e4dbb1
e9346172b7a36363a56b7a08deb6178ba87febd0
01f2d58343f68d0e4214fdb13d5d514d9915a28c
95668e5fb0e57034810e6ce78503af70d61215f9
166b8c0116ec313ce86eb9450318fbad9136cb12
24940f426149a351d172cd0f506ba21e57a51782
023a1ed1a41a43fe98122adb7a803e00a55753e3
b8e0f1b66c92e44719abcb4c19705b1a7a4c29ad
d183d4bdd7418300f702bb8baae8c28c38e2bde7
```

Because of some bugs that didn't allow to open the feature grid, the investigation with git bisect have only these results. 
Should I go more in detail about this problem?

**Comment by offtherailz** [comment]
Using `git bisect` I identified the commit e26ef86d7c3eac27e74f7c7402b5834488b7545a caused the issue. 
![image](https://user-images.githubusercontent.com/1279510/99996588-3e76b280-2dbc-11eb-90b1-973cf2a9a556.png)
