### ISSUE TITLE
Review parsing of properties with 0 values in the Visual Style Editor

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#6238]
## Description

The visual style editor allows the users to select properties with values equal to 0 and sometimes this is not correctly applied to the layers.

Here the list of properties that allow such behaviour group by symbolizer type:

Mark:
- Stroke width (when 0 stroke should not be visible)
- Radius (minimum should be 1px)

Icon:
- Size (minimum should be 1px)

Line with Pattern mark style:
- Stroke width (Marker first one, when 0 stroke should not be visible)
- Radius (minimum should be 1px)

Line with Pattern icon style:
- Size (minimum should be 1px)

Fill:
- Outline width (when 0 outline should not be visible)

Fill with Pattern mark style:
- Stroke width (when 0 stroke should not be visible)
- Radius (minimum should be 1px)
- Outline width (when 0 outline should not be visible)

Fill with Pattern icon style:
- Size (minimum should be 1px)
- Outline width (when 0 outline should not be visible)

Text:
- Font size (minimum should be 1px)
- Halo width (when 0 halo should not be visible)

## How to reproduce

-  open a map as admin and a layer with editable styles
- select a leyer
- open the layer settings and select the style tab
- select an existing style or create a new one (these steps need to be verified for CSS and SLD styles)
- test the properties listed above in the description

*Expected Result*

All the properties listed in the description with minimum size equal to 1 should reflect this update in the UI while other properties should render the new value as follow

Mark (stroke width 0):

![image](https://user-images.githubusercontent.com/19175505/100222443-5e23ed00-2f1a-11eb-9229-d6e7598460bd.png)

Line with Pattern mark style (stroke width 0):

![image](https://user-images.githubusercontent.com/19175505/100222618-a511e280-2f1a-11eb-8c51-69c400327a59.png)

Fill (outline width 0):
![image](https://user-images.githubusercontent.com/19175505/100222690-c4107480-2f1a-11eb-90a1-daf7ced8886b.png)

Fill with Pattern mark style  (outline and stroke width 0):
![image](https://user-images.githubusercontent.com/19175505/100222736-d25e9080-2f1a-11eb-9ea8-21d7c6ea7bb2.png)

Text (halo width 0):
![image](https://user-images.githubusercontent.com/19175505/100222860-fe7a1180-2f1a-11eb-809d-ea9a73022a2c.png)

*Current Result*

All the properties listed in the description sometimes reset the values to the default one with missmatch between ui input and rendering.

Mark (stroke width 0):
![image](https://user-images.githubusercontent.com/19175505/100223644-12724300-2f1c-11eb-898b-60b8016774cb.png)

Line with Pattern mark style (stroke width 0):
![image](https://user-images.githubusercontent.com/19175505/100223712-23bb4f80-2f1c-11eb-9c53-6e32b112d49c.png)

Fill (outline width 0):
![image](https://user-images.githubusercontent.com/19175505/100223754-333a9880-2f1c-11eb-926b-e7f29d78c371.png)

Fill with Pattern mark style  (outline and stroke width 0):
![image](https://user-images.githubusercontent.com/19175505/100223815-46e5ff00-2f1c-11eb-9fb3-977b1337185b.png)

Text (halo width 0):
![image](https://user-images.githubusercontent.com/19175505/100224012-857bb980-2f1c-11eb-9f01-c63ebb59e966.png)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by ElenaGallo** [comment]
@allyoucanmap Now Icon opacity set to 0.00 is actually like 1.00
![2_style](https://user-images.githubusercontent.com/56537133/100440407-21383180-30a5-11eb-9b4e-829548a074f4.gif)

**How to Reproduce**
- open [this map](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/31145)
- select *Unesco Items* leyer
- open the layer settings and select the style tab
- select *prova* style
- click on edit
- Change the opacity to 0.00

**Comment by tdipisa** [comment]
@ElenaGallo please open a new issue for the above and put it in 2021.01.01 milestone. Use same labels except the Almaviva one.
