### ISSUE TITLE
Responsive Design - Info Box

### ISSUE THREAD

**Issue by vlt1** [geosolutions-it/MapStore2#6240]
## Description

refers to [austrocontrol-C125/#242](https://github.com/geosolutions-it/austrocontrol-C125/issues/242)

**Comment by ElenaGallo** [comment]
@vlt1 here are some notes after testing the issue:

- The extra white space is still present if the details are opened from the homepage
![1details](https://user-images.githubusercontent.com/56537133/100600299-68226300-3301-11eb-905e-647450a2b461.png)

**How to reproduce**
- From homepage search [6240](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/31762) map
- Click on Details

*Current result*
the extra white space is present


- The center, right and justified alignment for text are not visible in edit mode (it is correctly shown only in view mode)
![3details](https://user-images.githubusercontent.com/56537133/100601023-6016f300-3302-11eb-836a-ff424a47b32e.gif)


**How to reproduce**
- Open [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/31762) map
- Click on Burger Menu
- Click on Save
- Click on Edit details
- Select a text
- Click on right align 

*Current result*
The text is not right aligned (saving the text is aligned correctly)

**Comment by tdipisa** [comment]
@ElenaGallo the second point is working for me. Are you using chrome? If yes, can you repeate the test cleaning the browser cache before?

**Comment by ElenaGallo** [comment]
@tdipisa now the second point works for me too.

**Comment by tdipisa** [comment]
@ElenaGallo please open two separate issues for the above problems.
