### ISSUE TITLE
Problems with text in detail

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#6256]
## Description

**1_** Aligning long text right, center, left or justified (must wrap at least once at the end of the line and must be copied from multiple words) the alignment is not displayed in edit mode

**2_** Aligning a long text to the right, center, left or justified (it must wrap at least once and it must consist of a very long word) the formatting of the text is lost

**3_** If you write text that wraps before the end of the line, the text spacing is greater

## How to reproduce

-  Open a map 
- Click on Save fron the Burgre Menu
- Click on Add details
- Follow the steps explained in the gif below
**1_** ![1testo](https://user-images.githubusercontent.com/56537133/100624035-3b7f4300-3323-11eb-9f2f-3423e260909c.gif)

**2** ![3testo](https://user-images.githubusercontent.com/56537133/100624091-489c3200-3323-11eb-9d3b-e10296deff16.gif)

**3_** ![2testo](https://user-images.githubusercontent.com/56537133/100624070-44701480-3323-11eb-8ba6-8980fd102bae.gif)

*Expected Result*

**1_** The new text alignment is visible on edit mode
**2_** No horizontal scroll bar is displayed and the formatting of the text must be respected
**3_** The text must always have the same interline

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@ElenaGallo I think there is probably a CSS problem since we are using here the same text editor of Paragraph section in GeoStory and it is working finr there. I will ask developers for a check.
