### ISSUE TITLE
Hide layers with no identify content in the GFI layer selector

### ISSUE THREAD

**Issue by dsuren1** [geosolutions-it/MapStore2#6275]
## Description
GFI panel - Hide the layers with no identify content in the dropdown list (Layer selector)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Code changes to existing features

## Other useful information
https://github.com/geosolutions-it/austrocontrol-C125/issues/232#issuecomment-736571061

**Comment by ElenaGallo** [comment]
@dsuren1 I have a note to make:

when i enable the GFI popup (by selecting Hover from the settings panel) the layer with no identify content is not visible in the GFI popup.

![hover_GFI](https://user-images.githubusercontent.com/56537133/101377340-fb373c00-38b1-11eb-91f4-1b6ab5bde526.gif)
**How to reproduce**
- Open [this austrocontrol map]()
- From the Burger Menu select the Settings
- From the dropdown menu select Hover
- Hover over a single feature on map

*Current Result*
the popup shows only the selected feature and the arrows cannot be used to move to other layers

**Comment by MV88** [comment]
@ElenaGallo i do not think that is published in austrocontrol yet

**Comment by dsuren1** [comment]
Hi @ElenaGallo 
As @MV88 suggested this has not been deployed to austrocontrol. And furthermore, the popup behavior which you have demonstrated is as expected. 
Initial requirement was to show the layer with no identify content in GFI panel, now client requested that this behavior has to be reverted. 
So to be clear, the layer with _no identify content_ shouldn't be visible in both the panel and in popup
