### ISSUE TITLE
Persistance of redux state do not work with debug mode

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#628]
The rehidrate reducer is not callded.

**Comment by kappu72** [comment]
Check #651

**Comment by offtherailz** [comment]
This is a different issue: 
to reproduce: put the login tool in the ` plugins.js` : 
```
[...]
        LoginPlugin: require('../plugins/Login')
[...]
```
and this option in `appConfig.js` : 
```
[...]
    storeOpts: {
        persist: {
            whitelist: ['security']
        }
    }
[...]
```
In the normal mode it preserves the login state, but in debug mode it the rehidrate reducer is not called, i think the persistence system of the debug tools conflicts with the `redux-persist `'s one
