### ISSUE TITLE
Annotation layer in TOC and annotation panel visibility sync

### ISSUE THREAD

**Issue by dsuren1** [geosolutions-it/MapStore2#6282]
## Description
Annotation layer in TOC and annotation panel visibility sync

## Acceptance criteria
- As soon as I hide all annotations in the annotation panel, also the layer in TOC changes his state.
- If then I show one annotation in the annotation panel, also the layer in TOC changes his state accordingly
- As soon as I hide the annotation layer in TOC all the annotations are hidden accordingly

## Other useful information
https://github.com/geosolutions-it/austrocontrol-C125/issues/246#issuecomment-731289024

**Comment by ElenaGallo** [comment]
@dsuren1 As soon as I hide all the annotations in the annotation panel, the layer in TOC changes its state and also on the map the annotations are hidden but once the annotation panel is closed the annotations are visible again.
![annotation](https://user-images.githubusercontent.com/56537133/101930342-4f0a9380-3bd8-11eb-9853-95b101228264.gif)


**How to Reproduce**
- Open a Demo Map on MS
- From burger Menu click on Annotations
- Hide all the annotations
- Click on X from the annotations panel

*Current Result*
The annotations become visible again

*Expected Result*
The annotations remain hidden

**Comment by dsuren1** [comment]
Note: 
After this PR, the above issue should be fixed and also the annotation's visibility will always be in sync. i.e When adding/editing one annotation the other annotations will not be hidden. The visibility of the annotation will be retained unless changed from TOC or annotation panel by clicking on the visibility icon as per the requirement requested by the client 

Reference:
> Yes, it's no requirement. Still it would be useful to give the user the possibility to see other annotations in case they are drawing based in other annotations. Probably we will come back to this.

https://github.com/geosolutions-it/austrocontrol-C125/issues/246#issuecomment-732969958
