### ISSUE TITLE
Provide maxZoomLevel config property for Attribute Table "zoom to feature" 

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6287]
## Description

As already implemented for MS search services through [this PR](https://github.com/geosolutions-it/MapStore2/pull/5164), the same configuration property (**maxZoomLevel**) is needed also for the Attribute Table for the "zoom to feature" functionality. **The same zoom logic is needed here too** (related client issue is https://github.com/geosolutions-it/austrocontrol-C125/issues/244#issuecomment-738793469).

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/1f5fb352-3bcf-4e72-8406-38c1afbbc3f1)

Therefore we can maintain the current behavior as default but it should be possible to specify the maxZoomLevel value from localConfig (attribute table plugin configuration).

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Other useful information

No UI needed for this, only a new configuration property for the attribute table plugin ready to be used from loalConfig.

**Comment by offtherailz** [comment]
@AGMETEOR you could try a simple solution. `actionOpts` of FeatureGrid should be passed to the event handler as last parameter. (see optional `crs`)

https://github.com/geosolutions-it/MapStore2/blob/e26ef86d7c3eac27e74f7c7402b5834488b7545a/web/client/plugins/featuregrid/gridTools.jsx#L14
So you could try to get from the plugin configuration `maxZoom` and pass to the FeatureGrid component the property `"actionOpts": {maxZoom}`.
Than handle it as optional second parameter of `zoomToExtent` action.
