### ISSUE TITLE
disable google maps API ping by default

### ISSUE THREAD

**Issue by landryb** [geosolutions-it/MapStore2#6302]
## Description

google maps API is pinged at each map load in the default config
## How to reproduce

load a mapstore instance, look at network console, there are two calls to google APIs:

* https://maps.google.com/maps/api/js?v=3
* https://maps.googleapis.com/maps/api/js/AuthenticationService.Authenticate?1shttps%3A%2F%2Fxxx%2Fmapstore%2F%23%2Fviewer%2Fopenlayers%2Fnew&5shttps%3A%2F%2Fxxx%2Fmapstore%2F%23%2Fviewer%2Fopenlayers%2Fnew&callback=_xdc_._730heq&token=62482

*Expected Result*
If no google API key is configured anywhere (the default case), google maps API shouldnt be pinged, that can lead to privacy/user info leaks. Afaict, bing maps API isnt called by default..

**Comment by matself** [comment]
A newly built and deployed MapStore instance freezes at an equivalent to the second call above.
`https://maps.googleapis.com/maps/api/js/AuthenticationService.Authenticate?1shttp%3A%2F%2Fgeodatatorget.se%3A8080%2Fmapstore%2F&5shttp%3A%2F%2Fgeodatatorget.se%3A8080%2Fmapstore%2F&callback=_xdc_._vu5r6t&token=12030`
The response is
`/**/_xdc_._vu5r6t && _xdc_._vu5r6t( [1,null,0,null,null,[0]] )`
Where do I put the Google Map API key to fix this?
All is running under Tomcat 9 (and worked up until friday 2021-08-27 last week)

**Comment by landryb** [comment]
@tdipisa ping ;)

**Comment by tdipisa** [comment]
@landryb @matself you can find an update [here](https://mapstore.readthedocs.io/en/latest/developer-guide/maps-configuration/#google) in doc and in the connected PR (#7275)
