### ISSUE TITLE
Update do webpack 5 - Use Module Federation for extension system

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#6308]
## Description
Old extension system is not working properly anymore because of module mangling and renaming during build. We was luck to see examples that was working, but as well as we converted some require to imports for plugin, the issues came out. 

The main problem is the approach, that emulates the webpack loading system but that can not prevent what happens in a separate build. Also working on the same build, for instance using the SampleExtension inside mapstore, now, produces a results that is different from the main build and so even the extension built in MapStore can not work anymore.
One solution can be to build our extension together with the project, but this reducesa a lot the utility of having extensions at all. 
One of the requirements of building extensions was in fact the possibility to have separate repositories. 

Webpack 5, introduced in november, introduces [Module Federation](https://webpack.js.org/concepts/module-federation/#root) that solves the problem of loading modules from different builds from webpack.
The use case is this  [this one](https://webpack.js.org/concepts/module-federation/#dynamic-remote-containers).

We need to: 
- Update to webapck 5
- MapStore support for module federation
- conversion to sample extension in module federation

**Things to do:**
- [x] Make hot module replacement work again (after update to webpack 5 mapstore rises an error about it in dev mode)
- [x] Zip import doesn't work because of an error "Buffer is not defined" probably due to node parts not bundled anymore by default. Investigate.
- [x] Creation of a unique bundle or back-end support to multiple js bundles. Actually the extension produces 2 js files. one for module publishing, one for the plugin. We should allow to load more than one JS on from the back-end, if possible, or find out a way to create one single file. 
- [x] fix test for upload controller
- [x] Test extension unistall on client and fix tests on client
- [x] Restructure sample extension for testing (it could be simply a mapstore project with the extension file as above). Now the template project is this (https://github.com/geosolutions-it/MapStoreExtension) with a pending PR.
- [x] Change the back-end entry point to allow access to assets (should be a normal path, like `loadasset/a/b/c.js` instead of the current  `loadasset?resource=/..../path/`
- [ ] test new feature / avoid directory transversing for loadAssets entry point
- [x] Port to georchestra, thesting the new assets entry point
- [x] update karma ( in progress )
   - [x] fix issues with Leaflet __tests__ directory
   - [x] fix failing tests

## How to reproduce
- build extension 
- install

*Expected Result*
The new extension works
*Current Result*
The new extension do not work anymore. Old extensions work.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by ElenaGallo** [comment]
@offtherailz removing the SampleExtension from the context the data.json causes an error in the console and changing the MS translation a new error appears.

> GET https://dev.mapstore2.geo-solutions.it/mapstore/dist/extensions/SampleExtension/translations/data.it-IT.json 404 (Not Found)

**How to reproduce**
![error](https://user-images.githubusercontent.com/56537133/103887150-e6cda580-50e2-11eb-83b8-69c1eca6c698.gif)

*Expected Result*
No error on console changing the MS translation

**Comment by tdipisa** [comment]
@ElenaGallo if you found only this problem, please open a new issue for the above and close this.
