### ISSUE TITLE
Shape file - Unable to set polygon fill opacity to 0

### ISSUE THREAD

**Issue by dsuren1** [geosolutions-it/MapStore2#6318]
## Description
Unable to set polygon fill opacity to 0 when importing a shape file

## How to reproduce
1. Upload this [shape file](https://github.com/geosolutions-it/MapStore2/files/5709812/Afghanistan_1_mod.zip) (polygon)
2. Set fill opacity to 0 and add the vector to map

*Expected Result*
Fill opacity of 0 should be applied

*Current Result*
Fill opacity other than 0 is set properly 

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information
Related to https://github.com/geosolutions-it/webmapper-halliburton/issues/1561

**Comment by ElenaGallo** [comment]
@dsuren1 it seems the same thing happens with **stroke**. By setting the stroke opacity to 0, the opacity is not applied correctly

![stroke](https://user-images.githubusercontent.com/56537133/102906648-3706ff80-4475-11eb-87b7-b6c446eabe32.gif)

**Comment by dsuren1** [comment]
@tdipisa @ElenaGallo 
Can we create a new issue to handle this, as the objective of this issue has been resolved ?
Or fix the stroke in this issue itself ?

**Comment by tdipisa** [comment]
@ElenaGallo please open a new issue for this for the milestone 2020.01.00, assign this to @dsuren1.

**Comment by ElenaGallo** [comment]
Closed in favor of #6340
