### ISSUE TITLE
Back-end service provides wrong mimetype / error for bin files

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#6326]
## Description
Back-end service `/loadasset/` response is always of content-type `application/octect-stream`.
This content-type is not allowed by chrome in production: 
https://stackoverflow.com/questions/60994976/refused-to-apply-style-because-its-mime-type-application-octet-stream

Images provided from the same entry point return an error.

## How to reproduce
- Setup a project with datadir enabled and extensions loaded from it, in https
- install an extension

*Expected Result*
- The extension works

*Current Result*
- The extension do not work in production.
- images loaded will return error.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by ElenaGallo** [comment]
@offtherailz By clicking on the INC button the counter value does not increase.

**How to reproduce**
- Open [this geOrchstra context](https://georchestra.geo-solutions.it/mapstore/#/context/sample_extension)
- Click on INC button

*Expected Result*
The counter value increases

**Comment by tdipisa** [comment]
@ElenaGallo what you reported is not related to this issue. Please open a separate issue for the above and close this if all related things are working well.
