### ISSUE TITLE
Update Cesium to use 1.76 causes issues

### ISSUE THREAD

**Issue by dandanaus** [geosolutions-it/MapStore2#6328]
## Description
Hey guys we tried to the the latest version of cesium 1.76 as we wanted to add 3D Tiles support but after doing so we are getting a whole lot of issues 

## How to reproduce
Change the version of cesium in webpack
-  
- 

Has anyone tried to do this and wanted to check if this is possible?

**Comment by tdipisa** [comment]
Dear @dandanaus thank you so much for doing this. I appreciate that other people are trying to work with MS. Before opening issues, can you please ask in mailing list to open a discussion about that?
