### ISSUE TITLE
Issue ordering records on Attribute Table

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#6335]
Opening a layer's Attribute Table on map the it is no longer possible ordering the reconds.
![attribute_table.gif](https://images.zenhubusercontent.com/5da5b30f66de7b0001e4e77c/11c69381-e570-4de4-b85f-36b5048feca8)

**How to reproduce**
- Open a map
- Select a layer on TOC
- Click on Attribute Table 
- Ordering a record

*Expected Result*
It is possible ordering the records on a attribute table

*Current Result*
Records cannot be sorted

**Comment by tdipisa** [comment]
It seems working fine for the table widget in dashboards
