### ISSUE TITLE
Missing opacity option for the ColorMap Entries table

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#635]
In the [ColorMap](http://docs.geoserver.org/latest/en/user/styling/sld-reference/rastersymbolizer.html#colormap) of the RasterSymbolizer it is possible to have individual opacity on the single entries.

This is missing in the current version of the editor.

I would add a spinner or a slider on each entry to account for this.

**Comment by kappu72** [comment]
The opacity can be set in the color picker. There's a slider that allow to set the opacity.

**Comment by simboss** [comment]
Cool, let's close it then.
