### ISSUE TITLE
Add minResolution, maxResolution and disableResolutionLimits properties to layer object

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#6350]
## Description

We should add support for `minResolution`, `maxResolution` and `disableResolutionLimits` properties inside the layer object. These properties should hide the visibility of the layer if not included inside these resolutions range. This is a similar behaviour of minResolution and maxResolution in [OpenLayers](https://openlayers.org/en/v5.3.0/apidoc/module-ol_layer_Tile-TileLayer.html) and the minZoom and maxZoom in [Leaflet](https://leafletjs.com/reference-1.7.1.html#tilelayer-option).

**We need to investigate if Cesium supports nativily some options similar to the other map libraries**, if not we could implement something similar to the work on this branch https://github.com/allyoucanmap/MapStore2/commit/b65fcb4559447113326385e364965337db7a9363 . This [branch](https://github.com/allyoucanmap/MapStore2/tree/min-max-res) was an initial work on the possibilities to add minResolution and maxResolution to layer object.

Requirements:

- all the layers typse for each map type should support these properties

Layer options example:

```js
{
    "type": "wms",
    "format": "image/png8",
    "url": "/geoserver/wms",
    "name": "workspace:layer",
    "title": "Title",
    "bbox": {
        "crs": "EPSG:4326",
        "bounds": {
            "minx": -180,
            "miny": -85,
            "maxx": 180,
            "maxy": 85
        }
    },

    "maxResolution": 100000,
    "minResolution":  0,
    "disableVisibilityByResolutionRange": false
}
```

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features

**Comment by allyoucanmap** [comment]
@tdipisa @giohappy @offtherailz @mbarto @MV88 please let me know if you agree on call these properties:

`minScaleDenominator`
`maxScaleDenominator`

**Comment by mbarto** [comment]
@allyoucanmap I usually prefer using resolutions instead of scales, because a scale is always ambiguous if you don't specify the device you are reffering to.

**Comment by giohappy** [comment]
@mbarto we know that scale is ambigous, but it was meant to be used in pair with the scaledenominator usually set inside SLD style, and to be aligned with the scale shown on the map, even if it's inprecise.

**Comment by allyoucanmap** [comment]
> @allyoucanmap I usually prefer using resolutions instead of scales, because a scale is always ambiguous if you don't specify the device you are reffering to.

As noted by @mbarto and then discussed with the team we could use min/max resolution for the configuration of the layer object while the UI form will provide the possibility to use min/max scales inputs converted internally to resolutions #6374

The properties proposed are:

`maxResolution`
`minResolution`
`disableVisibilityByResolutionRange`

The `disableVisibilityByResolutionRange` property should disable the use of min/max resolutions to affect the visibility .Let me know if the `disableVisibilityByResolutionRange` name is fine @giohappy @tdipisa

**Comment by tdipisa** [comment]
@allyoucanmap I agree with the above: manage this by transparently using resolutions instead of scales in the internal MS codebase is the best solution in my opinion.

**Comment by landryb** [comment]
thanks for this, that's a great feature !
