### ISSUE TITLE
Errors in the console when the SampleExtension is deleted

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#6361]
Removing the new  SampleExtension from the context the data.json causes an error in the console and changing the MS translation a new error appears.

> GET https://dev.mapstore2.geo-solutions.it/mapstore/dist/extensions/SampleExtension/translations/data.it-IT.json 404 (Not Found)

**How to reproduce**
![error](https://user-images.githubusercontent.com/56537133/103887150-e6cda580-50e2-11eb-83b8-69c1eca6c698.gif)

*Expected Result*
No error on console

*Current Result*
data.json errors appears on console

**Comment by offtherailz** [comment]
I noticed that some files was saved in config dir as root, so extensions was not really uninstallable. I fixed the problem so uninstallation now works perfectly. Anyway this error still exist. 
A refresh after installation solves the problem. A refresh is needed also to see the extensions installed, and maybe they are related problems. Not blocking.

**Comment by mbarto** [comment]
@offtherailz when enabling new extensions the following is done in withExtensions.js onPluginsLoaded:

```javascript
            if (translations.length > 0) {
                ConfigUtils.setConfigProp("translationsPath", [...castArray(ConfigUtils.getConfigProp("translationsPath")), ...translations.map(this.getAssetPath)]);
            }
            const locale =  ConfigUtils.getConfigProp('locale');
            store.dispatch(loadLocale(null, locale));
```

I suppose this needs to be reverted when the extension is removed by:
 * removing extension's translations from the translationsPath
 * reloading the current locale

About the need to refresh the page when adding a new extension, this was handled by this piece of code in withExtensions.js onInit function:

```javascript
         if (store.addActionListener) {
                store.addActionListener((action) => {
                    if (action.type === LOAD_EXTENSIONS) {
                        this.loadExtensions(
                            ConfigUtils.getConfigProp('extensionsRegistry'),
                            (plugins, translations) => this.onPluginsLoaded(plugins, translations, store)
                        );
                    }
                    if (action.type === PLUGIN_UNINSTALLED) {
                        this.removeExtension(action.plugin);
                    }
                });
            }
```
We probably need to check if this has been eventually broken.
