### ISSUE TITLE
SampleExtension problem in geOrchestra 

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#6362]
By clicking on the INC button the counter value does not increase.

**How to reproduce**
- Open [this geOrchstra context](https://georchestra.geo-solutions.it/mapstore/#/context/sample_extension)
- Click on INC button

*Expected Result*
The counter value increases

**Comment by offtherailz** [comment]
When 2 extensions are present, the reducers are not correctly combined, so the reducer of sampleExtension is not working. 

Steps that made me able to reproduce it on georchestra (the extensions must be installed on the server):
- create file `extensions.json` in the root

```json
{
  "Cadastrapp": {
    "bundle": "dist/extensions/Cadastrapp/index.js"
  },
  "SampleExtension": {
    "bundle": "dist/extensions/SampleExtension/index.js"
  }
}
```
- and edit `app.jsx` like this

```javascript
// ConfigUtils.setLocalConfigurationFile("rest/config/load/localConfig.json");
// ConfigUtils.setConfigProp("extensionsRegistry", "rest/config/load/extensions.json");
ConfigUtils.setConfigProp("contextPluginsConfiguration", "rest/config/load/pluginsConfig.json");
ConfigUtils.setConfigProp("extensionsFolder", "https://georchestra.geo-solutions.it/mapstore/rest/config/loadasset/");
ConfigUtils.setConfigProp("configurationFolder", "rest/config/load/");
```
- then in localConfig.json add "SampleExtension" to `plugins/desktop` section

Running the application, you will notice "INC" button do not increment the value. The epic of the extension instead works correctly.

notes:
main code for cadastrapp extension:
`https://georchestra.geo-solutions.it/mapstore/rest/config/loadasset/dist/extensions/Cadastrapp/assets/js/864.a976e46f.js`
main code for sampleExtension:
`https://georchestra.geo-solutions.it/mapstore/rest/config/loadasset/dist/extensions/SampleExtension/assets/js/377.b841f752.js`

Putting a break-point in the reducers of both the apps, you will notice that as well as the cadastrapp's reducers start being called, the sampleExtension is not called anymore. 
I suppose the reducers of extensions are not correctly combined.

**Comment by offtherailz** [comment]
@mbarto @tdipisa it looks that the issue still exists.
https://georchestra.geo-solutions.it/mapstore/#/context/sample_extension
INC button still not work. @mbarto I'm afraid the rootEpic have to be updated too. I see that only one extension has his epic working. (now 3 installed).

**Comment by offtherailz** [comment]
ok, jenkins did the build but didn't deploy for some reason (task aborted by anonymous).
