### ISSUE TITLE
Attribute table quick filter search problem

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#6368]
## Description

Searching values inside the quick filter cause a display problem on the table 
![tabella-attributi-qucik-filter](https://user-images.githubusercontent.com/56537133/104036747-15777900-51d4-11eb-8bba-f7fd628c855a.gif)

## How to reproduce

- Open a sample map
- Select a layer on TOC
- Click on Attribute table
- From one of the last columns search values inside the quick filter 

*Expected Result*

The search carried out is found under the right column

*Current Result*

the search performed is not found under the correct column

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by luorlandini** [comment]
about this issue, seems to be related to a bug of react-data-grid library this is the PR on react-data-grid repo:
https://github.com/adazzle/react-data-grid/pull/1994

**Comment by tdipisa** [comment]
@luorlandini let's put this on hold for the moment. We are using v5.0.4 of react-data-grid that is the latest stable. Let's wait the PR merge in the official repo to evaluate later to use the new stable version if/when possible. I'm moving the issue in blocked for the moment.
