### ISSUE TITLE
RasterStyler and FeatureInfo don't play well together

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#637]
Apparently the RasterStyler is sending wrong requests.

We would also need to check if #599 is somehow interfering here but nevertheless the request we are sending is a mess and GeoServer fails to parse it.

Here below a sample GetFeatureInfo request which we are sending:

http://demo.geo-solutions.it/geoserver/wms?service=WMS&version=1.1.1&request=GetFeatureInfo&srs=EPSG:900913&info_format=text/plain&x=450&y=246&exceptions=application/json&describeLayer=%7B%22bands%22:%5B%221%22%5D,%22owsType%22:%22WCS%22,%22range%22:%7B%22max%22:10000,%22min%22:-9999%7D%7D&format=image/png&group=Meteo&name=nurc:Arc_Sample&opacity=1&title=Weather%20data&type=wms&url=http://demo.geo-solutions.it/geoserver/wms&visibility=true&id=nurc:Arc_Sample__9&loading=false&params=%7B%22SLD_BODY%22:%22%3Csld:StyledLayerDescriptor%20xmlns:sld=%5C%22http://www.opengis.net/sld%5C%22%20xmlns:ogc=%5C%22http://www.opengis.net/ogc%5C%22%20xmlns:gml=%5C%22http://www.opengis.net/gml%5C%22%20version=%5C%221.0.0%5C%22%3E%3Csld:NamedLayer%3E%3Csld:Name%3Enurc:Arc_Sample%3C/sld:Name%3E%3Csld:UserStyle%3E%3Csld:FeatureTypeStyle%3E%3Csld:Rule%3E%3Csld:RasterSymbolizer%3E%3Csld:Opacity%3E1.00%3C/sld:Opacity%3E%3Csld:ChannelSelection%3E%3Csld:GrayChannel%3E%3Csld:SourceChannelName%3E1%3C/sld:SourceChannelName%3E%3Csld:ContrastEnhancement%3E%3Csld:Normalize%3E%3Csld:VendorOption%20name=%5C%22algorithm%5C%22%3EStretchToMinimumMaximum%3C/sld:VendorOption%3E%3Csld:VendorOption%20name=%5C%22minValue%5C%22%3E1%3C/sld:VendorOption%3E%3Csld:VendorOption%20name=%5C%22maxValue%5C%22%3E255%3C/sld:VendorOption%3E%3C/sld:Normalize%3E%3C/sld:ContrastEnhancement%3E%3C/sld:GrayChannel%3E%3C/sld:ChannelSelection%3E%3Csld:ColorMap%20type=%5C%22ramp%5C%22%3E%3Csld:ColorMapEntry%20color=%5C%22#e7e1ef%5C%22%20quantity=%5C%22-3332.676666666667%5C%22%20label=%5C%22-9999.00%5C%22/%3E%3Csld:ColorMapEntry%20color=%5C%22#c994c7%5C%22%20quantity=%5C%22-3332.666666666667%5C%22%20label=%5C%22-3332.67%5C%22/%3E%3Csld:ColorMapEntry%20color=%5C%22#dd1c77%5C%22%20quantity=%5C%223333.666666666666%5C%22%20label=%5C%223333.67%5C%22/%3E%3C/sld:ColorMap%3E%3C/sld:RasterSymbolizer%3E%3C/sld:Rule%3E%3C/sld:FeatureTypeStyle%3E%3C/sld:UserStyle%3E%3C/sld:NamedLayer%3E%3C/sld:StyledLayerDescriptor%3E%22%7D&layers=nurc:Arc_Sample&query_layers=nurc:Arc_Sample&height=793&width=784&bbox=-15008563.377850927,968610.0224297553,-7337954.71537692,8727274.141488286&feature_count=103332.676666666667%255C%2522%2520label%3D%255C%2522-9999.00%255C%2522%2F%253E%253Csld%3AColorMapEntry%2520color%3D%255C%2522%23c994c7%255C%2522%2520quantity%3D%255C%2522-3332.666666666667%255C%2522%2520label%3D%255C%2522-3332.67%255C%2522%2F%253E%253Csld%3AColorMapEntry%2520color%3D%255C%2522%23dd1c77%255C%2522%2520quantity%3D%255C%25223333.666666666666%255C%2522%2520label%3D%255C%25223333.67%255C%2522%2F%253E%253C%2Fsld%3AColorMap%253E%253C%2Fsld%3ARasterSymbolizer%253E%253C%2Fsld%3ARule%253E%253C%2Fsld%3AFeatureTypeStyle%253E%253C%2Fsld%3AUserStyle%253E%253C%2Fsld%3ANamedLayer%253E%253C%2Fsld%3AStyledLayerDescriptor%253E%2522%257D%26layers%3Dnurc%3AArc_Sample%26query_layers%3Dnurc%3AArc_Sample%26height%3D793%26width%3D784%26bbox%3D-15008563.377850927%2C968610.0224297553%2C-7337954.71537692%2C8727274.141488286%26feature_count%3D10

There is a ton of parameters which have nothing to do with the GeatFeatureInfo and the style is embedded inside a JSON element called params. Not sure where this comes from.

**Comment by kappu72** [comment]
The request is created by identify plugin.
When user queries a map, identify plugin generates a getfeatureinfo request for the queried map point. The request is created by getFeatureInfo action creator in mapinfo.js actions file [line 82](https://github.com/kappu72/MapStore2/blob/master/web/client/actions/mapInfo.js#L82)
When creating the request it copies all layer options to defaultParams object.
If layers options has params object value set  this will produce a request with params passing a json object.
Looking at WMSlayer plugin implementation, params object in layers options is used to pass more wms param request [leaflet](https://github.com/kappu72/MapStore2/blob/master/web/client/components/map/leaflet/plugins/WMSLayer.js#L72).
The question is, does getFeatureInfo request need this additional params? If not, and i.e. SLD_BODY params isn't need I suggest just to strip prams object in getFeatureInfo request creation. Otherwise we have to copy this param exploding the params object and maybe stripping unused  params.

**Comment by mbarto** [comment]
In general, passing custom params to getFeatureInfo is needed (e.g. CQL_FILTER). We could put parameters that are needed by some specific plugin (such as the RasterStyler) in a section of the layer configuration that is skipped by featureInfo (describeLayer?) and/or explicitly skip some params that we know are "dangerous" (SLD_BODY?)

**Comment by kappu72** [comment]
SLD_BODY is a standard param for a getMap wms request. I suggest to configure the params that should be skipped from a getFeatureInfo request and to strip these params from the request in the action.
