### ISSUE TITLE
Implement scale based visibility for layers

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/MapStore2#6370]
## Description
We want to introduce scale based visibility for layers, which means the ability to configure the scale thresholds (upper or lower) that control wether to show or hide a layer on the map and providing visual feedback to the user about the visibility state and limits to the user accordingly.

Initially we considered basing this feature on the SLD MinScaleDenominator and MaxScaleDenominator rule's elements, which is reported inside the GetCapabilities response if set. By the way this approach poses some challenges and limits:

 - we would need to obtain and parse the GC for each on every page reload
 - we might not have control on the service but we still want to force the scale dependent visibility

The proposal is to implement the scale based visibility mechanism on the client side independently from the style consifugration ot the WMS layer and, if available, use this information to provide a starting value when a layers' scale based visibility is activated and configured in MapStore. 
The configuration of scale based visibility will be available as a new form inside the layer configuration panel. In this form user will be prompted to input either minscale, maxscale or both values. If the GC for that layer containd MinScaleDenominator and MaxScaleDenominator the form will be automatically prefilled with these values. In any case the user can change the values at its own preference.
An "activate" flag will enable / disable scale based visibility. The previously set values will be reatined so that the user can turn scale based visibility on and off without losing the existing configuration.

When scale based visibility is activated inside the TOC, the layer node will either be enabled or disabled depending on the scale visibility rules matching the current map scale. In case the layer is not visibile at the current scale it will be shown as disabled (greyed) and a hint on hover will notify the user about the scale visibility limits being applied, suggesting to zoom in/zoom out to be able to see the layer on the map.

We are aware that "scales" are a fuzzy concept when a map is disaplyed on a screen,, and are even more miningless for certain projections and for maps spanning large geographical areas. By the way this concept is what most users expect to use, it is coherent with SLD MinScaleDenominator / MaxScaleDenominator and the scale widget already provided by MapStore. Using resolutions would be lot less intuitive and would force the user to make a trial / error configuration to spot the right thresholds that would match the reported (even if fictitious) scale values.

**Comment by allyoucanmap** [comment]
@tdipisa @giohappy both related issues have been backported and tested, going to close this
