### ISSUE TITLE
create a new project will not be able to start it in dev environment

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#6424]
## Description

there is a misalignment between the start script in package.json and the one in [projectScripts.json](https://github.com/geosolutions-it/MapStore2/blob/master/utility/projects/projectScripts.json#L5)

## How to reproduce

-  create a brand new standard project
- run npm install
- run npm start

*Expected Result*

to be able to start mapstore in dev mode

*Current Result*

an error occurs

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by ElenaGallo** [comment]
@MV88 running *npm start* from a new project this error appears:

> error: unknown option '--hot=only'
[webpack-cli] Did you mean '--hot'?
[webpack-cli] Run 'webpack --help' to see available commands and options
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! msproject@1.0.0 start: `webpack serve --progress --color --port 8081 --hot=only --inline --content-base .`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the msproject@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\geosolutions\AppData\Roaming\npm-cache\_logs\2021-01-20T09_41_10_204Z-debug.log
