### ISSUE TITLE
Use layer selected in feature grid for featuregrid

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#6430]
## Description
Actually the feature grid (wfs query) uses the selected layer in TOC.
https://github.com/geosolutions-it/MapStore2/blob/f368b91bdd6981408c8263dd31a443f9ea18e199/web/client/epics/wfsquery.js#L144

Then, if the feature grid want to use a different layer we had this solution: 
https://github.com/geosolutions-it/MapStore2/pull/6412/files#diff-07bdfbf1b3d79aa0218baf51178061f7f5bc76db1ce514c8f60a001ff5439c81R157

Anyway this solution is not consistent and may be unstable due to future improvements or unexpected state changes. We should instead use the layer selected in the state of the feature grid, that should be the dedicated piece of state where to store the layerId to use in the feature grid.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by tdipisa** [comment]
@offtherailz please check if we still need this opened or we can close it.
