### ISSUE TITLE
Lots of WMS requests when opening 3D mode

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6457]
## Description

Lots of WMS requests are performed in 3D mode. I think that we should check to see if we can improve this.

## How to reproduce

- Open [this map](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/10358) 
- Open the "network" browser console and activate the 3D mode

*Current Result*

Only for the layer *ny_roads* 210 requests are performed.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by MV88** [comment]
i've done some investigation and those requests are sent by cesium, and this does not seem a bug per se.
