### ISSUE TITLE
Mobile - Aeronautical coordinate editor layout 

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#6468]
On mobile, the buttons of the *aeronautical coordinate editor*, on GFI panel, should be centered in the editor layout

*Expected Result*
![ssss](https://user-images.githubusercontent.com/56537133/105854711-84800a80-5fe7-11eb-968d-e8a26264b1c2.png)

*Current Result*
![phone.png](https://images.zenhubusercontent.com/5da5b30f66de7b0001e4e77c/38ba4637-8429-429b-8490-2a7aa66d072f)!

**Comment by MuhweziDeo** [comment]
Hi, @tdipisa @ElenaGallo  from my investigation I don't think it's possible to have all these items centered in one line because the space available on mobile view is limited and all these items cannot fit on the same line hence one of them must be pushed down as space gets smaller.

**Comment by MuhweziDeo** [comment]
Hi, @tdipisa @ElenaGallo  the alignment as described in the issue is not possible but we can get alternative wayst to display it. I have included one that @allyoucanmap suggested in the screenshot. Let me know what you think. I can also spend more time discovering other ways we solve this. Thanks

![image_2021_03_26T17_14_08_368Z.png](https://images.zenhubusercontent.com/60350ba854742f543a9fa5ff/669529cf-ea1a-4a26-9c1e-8a47b12c288e)

**Comment by tdipisa** [comment]
Hi @MuhweziDeo, I'm fine with this. Is it anyway possible to have some margin on the right?
![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630333530626138353437343266353433613966613566662f36363935323963662d656131612d346132362d396331652d386134376231326332383865](https://user-images.githubusercontent.com/1280027/112807308-076d2200-9078-11eb-8353-ec5ddfdcc564.png)

**Comment by MuhweziDeo** [comment]
Yeah, @tdipisa. I think its possible

**Comment by offtherailz** [comment]
mmm... looking better at this solutions proposed in #6708, it looks too complicated. It adds a lot of logic and need to completely break the editor only to fix this.

I'm not sure even if it is a bug (the icons and buttons are centered for the editor)
![image](https://user-images.githubusercontent.com/1279510/113118866-269eb780-9210-11eb-8ba0-55b6e3eefddb.png)

Moreover the buttons on the right get a lot of space that should be dedicated to the editor. 
![image](https://user-images.githubusercontent.com/1279510/113119682-04f20000-9211-11eb-8942-a90cf4872f81.png)

@tdipisa I'm on the opinion to avoid these changes or not doing this task at all.
