### ISSUE TITLE
Add to migration guidelines instructions for refactor to tools for map plugin

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#6477]
## Description

In some projects for the Map plugin it was configured the tools array with only the "locate" entry
this will disable all other tools for he map like measurement etc.

*Documentation section involved*
- [ ] User Guide
- [x] Developer Guide

**Comment by offtherailz** [comment]
Take into account also this: 
https://github.com/geosolutions-it/austrocontrol-C125/pull/262#issuecomment-768401981
