### ISSUE TITLE
Implement rate control for the geolocation update frequency

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/MapStore2#6481]
## Description
Currently the update of geolocation positions follows the frequency dictated by the underlying Web Geolocation API, which doesn't offer any control over a "minimum update period" ([PositionsOptions](w3.org/TR/geolocation-API/#position-options)). As soon as a position is provided MapStand will trigger the chain of events and methods downstream.

As it happens also with other platforms (Android, iOS, etc.) rate control must be perfomred by the geolocation client app.

We want to introduce a configurable control rate (thottling), that will filter the position updates and only broadcast one update within the configured period (in seconds). By default this configuration will be underfined, and all the position updates will be relaid.

## Acceptance criteria

- a new numeric setting for the geolocation control is available to configure the rate of location updates.
- when this configuration is set the update period will be reflected in the update frequency of the map location

## Other useful information

- [Geolocation API Specification 2nd Edition](https://www.w3.org/TR/geolocation-API/)
- [OpenLayers Geolocation helper class](https://openlayers.org/en/latest/apidoc/module-ol_Geolocation-Geolocation.html)

**Comment by luorlandini** [comment]
Hi @giohappy (cc: @allyoucanmap ) 

an explanation about the behavior aspect for this feature.

do You expect that a user moving with a device, his position is updated, according to the value of the control rate?

by default it will be undefined, will the position never be updated?

**Comment by giohappy** [comment]
@luorlandini the expectred behaviour is:

 - **control rate (sec) is configured**: any callback assigned to the position change event is not triggered more then 1 time per rate. E.g. if the rate is 1sec I don't want to trigger the callbacks more then 1 time per second. If more positions events are generated by the device the control rate mechanism will discard them.

![image](https://user-images.githubusercontent.com/571129/107342133-1e53b700-6ac0-11eb-8d41-8d46121ed675.png)

 - **control rate is not configured**: we trigger the callbacks for each position change

**Comment by luorlandini** [comment]
@giohappy thanks for the feedback
