### ISSUE TITLE
GetCapabilites parsing error for inspire_vs:ExtendedCapabilities

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#6489]
## Description

Mapstore currently fails to parse the GetCapabilities result that contains inspire_vs:ExtendedCapabilities for retrieving styles.
it fails [here](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/api/WMS.js#L133) and it goes then in the catch  [here](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/epics/styleeditor.js#L270)

I also noticed a variety of ways to retrieve & parse getCapabilities we should unify
https://github.com/geosolutions-it/MapStore2/blob/master/web/client/actions/layerCapabilities.js#L55
https://github.com/geosolutions-it/MapStore2/blob/master/web/client/api/WMS.js#L113
https://github.com/geosolutions-it/MapStore2/blob/master/web/client/api/WMS.js#L169
https://github.com/geosolutions-it/MapStore2/blob/master/web/client/observables/wms.js#L42

## How to reproduce

- open map with id [451](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/451) map 
- open TOC
- select layer temperatura
- open layer settings 
- check debugging the notified points

*Expected Result*

to see the styles for that layer

*Current Result*

there is this error when parsing with jsonix
```
"Element [{http://inspire.ec.europa.eu/schemas/inspire_vs/1.0}inspire_vs:ExtendedCapabilities] 
could not be unmarshalled as is not known in this context and the property does not allow DOM content."
```
so the styles list is empty
- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@MV88 I remember that this issue is related to a problem with the library MS is using to parse the GetCapabilities output. Are there more details that can be included in the description to help with the estimate?

**Comment by MV88** [comment]
the issue description is already well detailed.
The estimate is big because the only solution I can think of is:
replacing ogc schemas with xml2js

this would have also other benefits in terms of performance (reduced bundle size)

**Comment by landryb** [comment]
my understanding of this issue is that the ogc-schemas npm module lacks proper support for inspire schemas...

**Comment by landryb** [comment]
@MV88 you might want to try what i did in landryb/MapStore2@35f31b2 to add support for inspire schemas

**Comment by tdipisa** [comment]
@ElenaGallo still waiting for your functional tests here.
