### ISSUE TITLE
Deploy of a newly created project fails in Tomcat due to a missing jar

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#6494]
## Description

Mapstore fails to deploy a newly created project

## How to reproduce

- git checkout  2021.01.xx
- node ./createProject.js standard test 1.0.0 "custom mapstore test" " " ../test_create
- cd ../test_create
- ./build.sh
- deploy in tomcat
*Expected Result*

to be able to access http://localhost:PORT/test
*Current Result*

some errors occurs
[test.log](https://github.com/geosolutions-it/MapStore2/files/5895417/test.log)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

SOLUTON can be to remove this line [here](https://github.com/geosolutions-it/MapStore2/blob/master/web/pom.xml#L357)
we need to verify which version of commons-pool we need:
- commons-pool-1.5.4.jar
- commons-pool-1.3.jar
in the newly created project both were missing during deploy

**Comment by tdipisa** [comment]
@mbarto can you please check this issue to see if the solution suggested by @MV88 is enough to solve the problem? Is it a problem introduced by #6472 and related to some missing transitive dependencies?
