### ISSUE TITLE
Incorrect placement of widgets

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6495]
## Description

Regression from 2021.01.00 that affect DEV and QA instances. In latest mapstore there is a small bug in the widgets placement: with the current placement grid it is not possible to properly align widgets on the right.
![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/026a3c9e-243e-40f1-a024-78955e327dfc)

The correct position should be the following:

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/58a8c623-74c2-4f37-9559-42163e221463)

**Steps to reproduce**

![widgets_issue](https://user-images.githubusercontent.com/1280027/106454327-da8efb00-648a-11eb-87b1-5d05e2d067a3.gif)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by MV88** [comment]
so far i have noticed that the update of the version of react-grid -layout is causing this issue
working on a fix
