### ISSUE TITLE
Reset the Time Slider changing the guide layer

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6524]
## Description

If I change the guide layer, the Time Slider tick should be repositioned according to the temporal domain of the new guide layer.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by offtherailz** [comment]
It should be easy to intercept guide layer change event and trigger programmatically a "snap to nearest value" from the current time, as well as we do with click event.
