### ISSUE TITLE
Not proper validation for HTML featureinfo response

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#6539]
## Description
If the GFI of a WMS replies with HTML that starts with `<?xml`, instead of displaying data, MapStore reply with an error. 
HTML may start with `<?xml` without any problem. The feature info parsing try to catch this string to identify XML exception, but this is not valid, expecially with html or xml (GML) responses.

https://github.com/geosolutions-it/MapStore2/blob/64175ad83801593a135d2f83026cbe8a2ce1c047/web/client/utils/FeatureInfoUtils.js#L73

Note: the xml check is not a good check anyway. A check like this is more precise. Anyway it should be converted in a Promise version.

https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/ObservableUtils.js#L33

## How to reproduce

-  Open a layer that replies to GFI in html with the `<?xml ` prefix. (configure it, or use [this](http://ovc.catastro.meh.es/cartografia/INSPIRE/spadgcwms.aspx) catalog source and add some layers)
- Select HTML as feature info format and zoom to the zone with data (in the passed wms you can zoom on **Madrid**).
- Click to get the FeatureInfo. 

*Expected Result*
- If the service replies with a valid HTML (not always, it depends on the point clicked, for the example service) MapStore shows the HTML

*Current Result*
- MapStore tells "No feature found for any result.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by MuhweziDeo** [comment]
@offtherailz please help me share  a layer that replies to GFI in HTML

**Comment by MuhweziDeo** [comment]
@offtherailz is it necessary to convert the `interceptOGCError` to return a Promise version.

**Comment by offtherailz** [comment]
@MuhweziDeo The linked interceptOGCError is only an example, but it is not buggy. 
I think for the moment you can proceed improving the check in featureInfoUtils to do a real check (strings starting with `<?xml` are still valid html, an error should intercept the `<ExceptionReport` tag. To do a test about the error response you can try to do the same http request with an invalid format.

Please let me know if it is more clear now?

**Comment by offtherailz** [comment]
Sorry I checked a little bit more. The request is done in text format, but the response arrives in html. This looks to be an incorrect behavior from the server.

**Comment by MuhweziDeo** [comment]
yes I noticed that as well during the debuging

**Comment by offtherailz** [comment]
Anyway from my test if from layer settings (TOC --> select layer --> edit layer settings from TOC toolbar --> feature info tab (last tab) selcect html format, it has anyway an error (Can you confirm). We should fix only that case, don't know where comes from

**Comment by MuhweziDeo** [comment]
I reproduced the error and fixed it. It but like u said the error occurs in the HTML as opposed to TEXT. I added a check to see if `<xml?` is included such that it can be parsed as valid html

**Comment by offtherailz** [comment]
Ok, I didn't noticed the PR ;) sorry, I only found the comment in my timeline. As I said, maybe checking `<?xml` is not the best approach. Anyway @allyoucanmap will take care of the PR review
