### ISSUE TITLE
Show informative messages inside widgets rather then on hover

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/MapStore2#6560]
## Description
As an example of what I'm proposing, here below an image of a chart widget when map synced and the unlderying data is not inside the map viewport. Since no data are available in this are a not much informative "i" icon is shown.

![image](https://user-images.githubusercontent.com/571129/108696047-50720980-7501-11eb-8963-ef614ecd1d79.png)

The user has not hints of what is happening. In a case it lead the user to think it was a bug.
He will discover what's happening only if he hover the mouse on the icon

![image](https://user-images.githubusercontent.com/571129/108696153-7697a980-7501-11eb-88c1-798c85a2c0ab.png)

It shouldn't be a big deal if we show the message directly inside the widget, maybe above (or in place) of the current icon. It would be a much more effective and informative wai to make the user aware of what's happening.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features

**Comment by MuhweziDeo** [comment]
hi @tdipisa check the design below
<img width="418" alt="Screenshot 2021-03-01 at 14 43 54" src="https://user-images.githubusercontent.com/39124174/109492841-a106db00-7a9c-11eb-8fe5-ab3792d33abc.png">

**Comment by giohappy** [comment]
@MuhweziDeo the message is half true. No data is available **for this area**. This is important for the user...

**Comment by tdipisa** [comment]
I agree with @giohappy @MuhweziDeo, the message is already there and visible on mouse hover: we have to make it more visible.

**Comment by MuhweziDeo** [comment]
okay let me see how to generate the message
