### ISSUE TITLE
MapStore DNS change from geo-solutions.it to geosolutionsgroup.com

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6587]
## Description

This issue is needed to follow #6578 (point 4):

>We shall start using the geosolutionsgroup.com rather than geo-solutions.it as soon as possible, possibly from next release. It is important that the old URLs keep working though since we will have many link around pointing to those addresses. This is devops work, most probably.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Other... Please describe: geosolutions URLs changes

## Other useful information
To take into account comment [here](https://github.com/geosolutions-it/MapStore2/issues/6578#issuecomment-785824419) for this issue

**Comment by tdipisa** [comment]
Still to complete. I'm going to move this in 2021.02.00 @randomorder

**Comment by randomorder** [comment]
I've changed the temporary redirects into permanent redirect and submitted a PR to change the references in the repo. Once merged we should be done
