### ISSUE TITLE
Testing MS with new 512px tile size gridsets defined in GeoServer

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6590]
Default gridsets with 512px tiles have been recently added to GeoServer master (see [here](https://github.com/geosolutions-it/geoserver/issues/226#issuecomment-783574403)) for EPSG:4326 and EPSG:900913. These new default gridsets will be available starting from GeoServer v2.19.

We have to perform related tests in MS (where 512x512 tile size for layers is already supported) to ensure all layers are properly rendered in map for the above CRSs using the new default gridsets in GeoServer. 

To test this, [the nightly build of GeoServer master](http://geoserver.org/release/master/) need to be used.

**Comment by MV88** [comment]
@tdipisa i have tested this locally and it is working correctly

**Comment by simboss** [comment]
@MV88 lots of feedback but I have would have added conclusions as well, no?

Does it work as expected? Yes? No?
I would prefer a clear answer rather than trying to guess myself...

**Comment by MV88** [comment]
next time i'll add a TL DR as first thing :)

**Comment by simboss** [comment]
@MV88 you still have not answered, I have a backport pending on GeoServer that I want to move.
Test also 4326 gridset not just 900913.

**Comment by MV88** [comment]
@simboss 
In my tests i tried both CRS
and they were correctly being cached

here is a screenshot with CRS ESP: 4326
![image](https://user-images.githubusercontent.com/11991428/111201596-3210a280-85c3-11eb-91fb-25dd28f5e8d3.png)

**Comment by simboss** [comment]
thx
