### ISSUE TITLE
Link to the reference source for WMTS multidimensional is broken

### ISSUE THREAD

**Issue by severinmenard** [geosolutions-it/MapStore2#6594]
## Description
https://mapstore.readthedocs.io/en/latest/user-guide/timeline/ provides a link to https://docs.geoserver.org/stable/en/user/community/wmts-multidimensional/index.html, which in its first sentence links to http://demo.geo-solutions.it/share/wmts-multidim/wmts_multidim_geosolutions.html that does not exist anymore (error 404)

*Documentation section involved*
- [ X] User Guide
- [ ] Developer Guide

**Comment by tdipisa** [comment]
@severinmenard thank you for reporting it, this is an issue in the GeoServer documentation anyway that you can report [opening a JIRA](https://github.com/geoserver/geoserver#bugs).
The correct link is this one anyway:
http://demo.geo-solutions.it/share/wmts-multidim/wmts_multidim.html
