### ISSUE TITLE
Infinite scroll in layer selector and map selector of dashboard do not work anymore

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#6635]
## Description
When scrolling, the layer selector of the dashboard should load more layers. 
![infinite](https://user-images.githubusercontent.com/1279510/111135413-e89d6480-857c-11eb-933a-d49a87798371.gif)

### Issue 1
-  create or open a dashboard
- Add a widget
- select "chart"
- try to scoll down

*Expected Result*
New records are added, the footer indicates the results loaded and matched
*Current Result*
The results remain 20.

### Issue 2
- Add a widget
- select "map"

**Expected  result** : 
virtual scroll works
**Corrent result:** 
the tool loads continuosly or do not load at all.
![mapwidget](https://user-images.githubusercontent.com/1279510/112490009-4ac94700-8d7f-11eb-900c-06adbddb98ce.gif)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

Please look that MapCatalog (http://localhost:8081/#/context/mapcatalog) works too, after these changes

**Comment by tdipisa** [comment]
@MuhweziDeo please check this, @offtherailz is available to provide some hints if needed. We need first of all to check the reason of the regression.

**Comment by MuhweziDeo** [comment]
@offtherailz @tdipisa. My initial investigation I have found that the number of results being returned is not consistent.  its shows the numberOfRecordsReturned is 10 but the actual list is 8 items. I do not know if this is the cause for sure.
`
nextRecord: 81
numberOfRecordsMatched: 85
numberOfRecordsReturned: 10
records: Array(8)
0: {dateStamp: undefined, fileIdentifier: undefined, identificationInfo: undefined, boundingBox: {…}, dc: {…}}
1: {dateStamp: undefined, fileIdentifier: undefined, identificationInfo: undefined, boundingBox: {…}, dc: {…}}
2: {dateStamp: undefined, fileIdentifier: undefined, identificationInfo: undefined, boundingBox: {…}, dc: {…}}
3: {dateStamp: undefined, fileIdentifier: undefined, identificationInfo: undefined, boundingBox: {…}, dc: {…}}
4: {dateStamp: undefined, fileIdentifier: undefined, identificationInfo: undefined, boundingBox: {…}, dc: {…}}
5: {dateStamp: undefined, fileIdentifier: undefined, identificationInfo: undefined, boundingBox: {…}, dc: {…}}
6: {dateStamp: undefined, fileIdentifier: undefined, identificationInfo: undefined, boundingBox: {…}, dc: {…}}
7: {dateStamp: undefined, fileIdentifier: undefined, identificationInfo: undefined, boundingBox: {…}, dc: {…}}
`
<img width="441" alt="Screenshot 2021-03-15 at 17 27 47" src="https://user-images.githubusercontent.com/39124174/111169652-35e8f880-85b4-11eb-9539-eb1a2861b0f0.png">

**Comment by offtherailz** [comment]
Hi, I have more experience with virtual scrolling and so I should have found the problem

Here: 
https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/catalog/CompactCatalog.jsx#L75

replace with this
```
const scrollSpyOptions = { querySelector: ".ms2-border-layout-body .ms2-border-layout-content", pageSize: PAGE_SIZE};
```
Adding ` .ms2-border-layout-content"` to the querySelector should solve the problem. (it takes the wrong div to calculate scrolling, probably due to a change in layout)

Anyway, as you notice, the server response is effectively strange, replying sometimes with 10, sometimes with 8 or 9 records, depending on the page.
@tdipisa we could investigate this issue. 

```sh
curl 'https://gs-stable.geo-solutions.it/geoserver/csw?service=CSW&version=2.0.2&request=&authkey=60d2d584-2eef-4531-be15-5069ccbaed87' \
  -H 'authority: gs-stable.geo-solutions.it' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'sec-ch-ua: "Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36' \
  -H 'content-type: application/xml' \
  -H 'sec-roles: ROLE_MAPSTORE_ADMIN;ROLE_EL_APPLIS_CAD_CNIL1;ROLE_EL_APPLIS_CAD_CNIL2' \
  -H 'sec-username: testadmin' \
  -H 'origin: http://localhost:8081' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: http://localhost:8081/' \
  -H 'accept-language: en,it-IT;q=0.9,it;q=0.8,en-US;q=0.7,ja;q=0.6' \
  --data-raw '<csw:GetRecords xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dct="http://purl.org/dc/terms/" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gmi="http://www.isotc211.org/2005/gmi" xmlns:ows="http://www.opengis.net/ows" service="CSW" version="2.0.2" resultType="results" startPosition="21" maxRecords="10"><csw:Query typeNames="csw:Record"><csw:ElementSetName>full</csw:ElementSetName></csw:Query></csw:GetRecords>' \
  --compressed
```

**Comment by MuhweziDeo** [comment]
I'm now getting a CORs error 
<img width="594" alt="Screenshot 2021-03-16 at 17 31 26" src="https://user-images.githubusercontent.com/39124174/111327454-7319bd00-867e-11eb-9b08-dcb2f55f59fb.png">

**Comment by MuhweziDeo** [comment]
> Hi, I have more experience with this virtual scrolling and so I should have found the problem
> 
> Here:
> https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/catalog/CompactCatalog.jsx#L75
> 
> replace with this
> 
> ```
> const scrollSpyOptions = { querySelector: ".ms2-border-layout-body .ms2-border-layout-content", pageSize: PAGE_SIZE};
> ```
> 
> Adding ` .ms2-border-layout-content"` to the querySelector should solve the problem. (it takes the wrong div to calculate scrolling, probably due to a change in layout)
> 
> Anyway, as you notice, the server response is effectively strange, replying sometimes with 10, sometimes with 8 or 9 records, depending on the page.
> @tdipisa we could investigate this issue.
> 
> ```shell
> curl 'https://gs-stable.geo-solutions.it/geoserver/csw?service=CSW&version=2.0.2&request=&authkey=60d2d584-2eef-4531-be15-5069ccbaed87' \
>   -H 'authority: gs-stable.geo-solutions.it' \
>   -H 'pragma: no-cache' \
>   -H 'cache-control: no-cache' \
>   -H 'sec-ch-ua: "Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"' \
>   -H 'accept: application/json, text/plain, */*' \
>   -H 'sec-ch-ua-mobile: ?0' \
>   -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36' \
>   -H 'content-type: application/xml' \
>   -H 'sec-roles: ROLE_MAPSTORE_ADMIN;ROLE_EL_APPLIS_CAD_CNIL1;ROLE_EL_APPLIS_CAD_CNIL2' \
>   -H 'sec-username: testadmin' \
>   -H 'origin: http://localhost:8081' \
>   -H 'sec-fetch-site: cross-site' \
>   -H 'sec-fetch-mode: cors' \
>   -H 'sec-fetch-dest: empty' \
>   -H 'referer: http://localhost:8081/' \
>   -H 'accept-language: en,it-IT;q=0.9,it;q=0.8,en-US;q=0.7,ja;q=0.6' \
>   --data-raw '<csw:GetRecords xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dct="http://purl.org/dc/terms/" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gmi="http://www.isotc211.org/2005/gmi" xmlns:ows="http://www.opengis.net/ows" service="CSW" version="2.0.2" resultType="results" startPosition="21" maxRecords="10"><csw:Query typeNames="csw:Record"><csw:ElementSetName>full</csw:ElementSetName></csw:Query></csw:GetRecords>' \
>   --compressed
> ```
> 
> is a paginated request that looks correct, asking for maxRecords=10, startPosition=21.
> 
> the result contains 8 records instead of 10, but we have totally more records. So pagination is broken on server side.
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <csw:GetRecordsResponse xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:rim="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dct="http://purl.org/dc/terms/" xmlns:ows="http://www.opengis.net/ows" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0.2" xsi:schemaLocation="http://www.opengis.net/cat/csw/2.0.2 https://gs-stable.geo-solutions.it/geoserver/schemas/csw/2.0.2/record.xsd?authkey=60d2d584-2eef-4531-be15-5069ccbaed87">
>     <csw:SearchStatus timestamp="2021-03-16T13:29:33.177Z"/>
>     <csw:SearchResults numberOfRecordsMatched="85" numberOfRecordsReturned="10" nextRecord="31" elementSet="full">
>         <csw:Record>
>             <dc:identifier>nurc:mosaic</dc:identifier>
>             <dc:creator>GeoServer Catalog</dc:creator>
>             <dct:references scheme="OGC:WMS">https://gs-stable.geo-solutions.it/geoserver/wms?authkey=60d2d584-2eef-4531-be15-5069ccbaed87?service=WMS&amp;request=GetMap&amp;layers=nurc:mosaic</dct:references>
>             <dc:subject>WCS</dc:subject>
>             <dc:subject>ImageMosaic</dc:subject>
>             <dc:subject>mosaic</dc:subject>
>             <dc:description>Generated from ImageMosaic</dc:description>
>             <dc:title>mosaic</dc:title>
>             <dc:type>http://purl.org/dc/dcmitype/Dataset</dc:type>
>             <ows:BoundingBox crs="urn:x-ogc:def:crs:EPSG:6.11:4326">
>                 <ows:LowerCorner>36.492 6.346</ows:LowerCorner>
>                 <ows:UpperCorner>46.591 20.83</ows:UpperCorner>
>             </ows:BoundingBox>
>         </csw:Record>
>         <csw:Record>
>             <dc:identifier>sde:GRAY_HR_SR_OB_DR</dc:identifier>
>             <dc:creator>GeoServer Catalog</dc:creator>
>             <dct:references scheme="OGC:WMS">https://gs-stable.geo-solutions.it/geoserver/wms?authkey=60d2d584-2eef-4531-be15-5069ccbaed87?service=WMS&amp;request=GetMap&amp;layers=sde:GRAY_HR_SR_OB_DR</dct:references>
>             <dc:subject>WCS</dc:subject>
>             <dc:subject>GeoTIFF</dc:subject>
>             <dc:subject>GRAY_HR_SR_OB_DR</dc:subject>
>             <dc:description>Generated from GeoTIFF</dc:description>
>             <dct:abstract>Gray Earth with Shaded Relief, Hypsography, Ocean Bottom, and Drainages</dct:abstract>
>             <dc:title>GRAY_HR_SR_OB_DR</dc:title>
>             <dc:type>http://purl.org/dc/dcmitype/Dataset</dc:type>
>             <ows:BoundingBox crs="urn:x-ogc:def:crs:EPSG:6.11:4326">
>                 <ows:LowerCorner>-90.000000000036 -180.0</ows:LowerCorner>
>                 <ows:UpperCorner>90.00000000000001 180.00000000007202</ows:UpperCorner>
>             </ows:BoundingBox>
>         </csw:Record>
>         <csw:Record>
>             <dc:identifier>sde:HYP_HR_SR_OB_DR</dc:identifier>
>             <dc:creator>GeoServer Catalog</dc:creator>
>             <dct:references scheme="OGC:WMS">https://gs-stable.geo-solutions.it/geoserver/wms?authkey=60d2d584-2eef-4531-be15-5069ccbaed87?service=WMS&amp;request=GetMap&amp;layers=sde:HYP_HR_SR_OB_DR</dct:references>
>             <dc:subject>WCS</dc:subject>
>             <dc:subject>GeoTIFF</dc:subject>
>             <dc:subject>HYP_HR_SR_OB_DR</dc:subject>
>             <dc:description>Generated from GeoTIFF</dc:description>
>             <dct:abstract>Cross Blended Hypso with Relief, Water, Drains, and Ocean Bottom</dct:abstract>
>             <dc:title>HYP_HR_SR_OB_DR</dc:title>
>             <dc:type>http://purl.org/dc/dcmitype/Dataset</dc:type>
>             <ows:BoundingBox crs="urn:x-ogc:def:crs:EPSG:6.11:4326">
>                 <ows:LowerCorner>-90.000000000036 -180.0</ows:LowerCorner>
>                 <ows:UpperCorner>90.00000000000001 180.00000000007202</ows:UpperCorner>
>             </ows:BoundingBox>
>         </csw:Record>
>         <csw:Record>
>             <dc:identifier>sde:NE2_HR_LC_SR_W_DR</dc:identifier>
>             <dc:creator>GeoServer Catalog</dc:creator>
>             <dct:references scheme="OGC:WMS">https://gs-stable.geo-solutions.it/geoserver/wms?authkey=60d2d584-2eef-4531-be15-5069ccbaed87?service=WMS&amp;request=GetMap&amp;layers=sde:NE2_HR_LC_SR_W_DR</dct:references>
>             <dc:subject>WCS</dc:subject>
>             <dc:subject>GeoTIFF</dc:subject>
>             <dc:subject>NE2_HR_LC_SR_W_DR</dc:subject>
>             <dc:description>Generated from GeoTIFF</dc:description>
>             <dct:abstract>Natural Earth II with Shaded Relief, Water, and Drainages</dct:abstract>
>             <dc:title>NE2_HR_LC_SR_W_DR</dc:title>
>             <dc:type>http://purl.org/dc/dcmitype/Dataset</dc:type>
>             <ows:BoundingBox crs="urn:x-ogc:def:crs:EPSG:6.11:4326">
>                 <ows:LowerCorner>-90.000000000036 -180.0</ows:LowerCorner>
>                 <ows:UpperCorner>90.00000000000001 180.00000000007202</ows:UpperCorner>
>             </ows:BoundingBox>
>         </csw:Record>
>         <csw:Record>
>             <dc:identifier>geosolutions:Linee_in_america</dc:identifier>
>             <dc:creator>GeoServer Catalog</dc:creator>
>             <dct:references scheme="OGC:WMS">https://gs-stable.geo-solutions.it/geoserver/wms?authkey=60d2d584-2eef-4531-be15-5069ccbaed87?service=WMS&amp;request=GetMap&amp;layers=geosolutions:Linee_in_america</dct:references>
>             <dc:subject>features</dc:subject>
>             <dc:subject>Linee_in_america</dc:subject>
>             <dc:title>Linee_in_america</dc:title>
>             <dc:type>http://purl.org/dc/dcmitype/Dataset</dc:type>
>             <ows:BoundingBox crs="urn:x-ogc:def:crs:EPSG:6.11:4326">
>                 <ows:LowerCorner>23.127610208816705 -120.81670533642685</ows:LowerCorner>
>                 <ows:UpperCorner>54.34802784222738 -89.15081206496515</ows:UpperCorner>
>             </ows:BoundingBox>
>         </csw:Record>
>         <csw:Record>
>             <dc:identifier>geosolutions:NaturalEarth</dc:identifier>
>             <dc:creator>GeoServer Catalog</dc:creator>
>             <dct:references scheme="OGC:WMS">https://gs-stable.geo-solutions.it/geoserver/wms?authkey=60d2d584-2eef-4531-be15-5069ccbaed87?service=WMS&amp;request=GetMap&amp;layers=geosolutions:NaturalEarth</dct:references>
>             <dc:subject>WCS</dc:subject>
>             <dc:subject>GeoTIFF</dc:subject>
>             <dc:subject>NE2_HR_LC_SR_W_DR</dc:subject>
>             <dc:description>Generated from GeoTIFF</dc:description>
>             <dc:title>NE2_HR_LC_SR_W_DR</dc:title>
>             <dc:type>http://purl.org/dc/dcmitype/Dataset</dc:type>
>             <ows:BoundingBox crs="urn:x-ogc:def:crs:EPSG:6.11:4326">
>                 <ows:LowerCorner>-90.000000000036 -180.0</ows:LowerCorner>
>                 <ows:UpperCorner>90.00000000000001 180.00000000007202</ows:UpperCorner>
>             </ows:BoundingBox>
>         </csw:Record>
>         <csw:Record>
>             <dc:identifier>geosolutions:OrtofotoRegione2010</dc:identifier>
>             <dc:creator>GeoServer Catalog</dc:creator>
>             <dct:references scheme="OGC:WMS">https://gs-stable.geo-solutions.it/geoserver/wms?authkey=60d2d584-2eef-4531-be15-5069ccbaed87?service=WMS&amp;request=GetMap&amp;layers=geosolutions:OrtofotoRegione2010</dct:references>
>             <dc:description>OrtofotoRegione2010</dc:description>
>             <dct:abstract>OrtofotoRegione2010</dct:abstract>
>             <dc:title>OrtofotoRegione2010</dc:title>
>             <dc:type>http://purl.org/dc/dcmitype/Dataset</dc:type>
>             <ows:BoundingBox crs="urn:x-ogc:def:crs:EPSG:6.11:4326">
>                 <ows:LowerCorner>43.87583677430796 6.267501663426435</ows:LowerCorner>
>                 <ows:UpperCorner>46.64007706010537 9.47884688949385</ows:UpperCorner>
>             </ows:BoundingBox>
>         </csw:Record>
>         <csw:Record>
>             <dc:identifier>geosolutions:black_marble</dc:identifier>
>             <dc:creator>GeoServer Catalog</dc:creator>
>             <dct:references scheme="OGC:WMS">https://gs-stable.geo-solutions.it/geoserver/wms?authkey=60d2d584-2eef-4531-be15-5069ccbaed87?service=WMS&amp;request=GetMap&amp;layers=geosolutions:black_marble</dct:references>
>             <dc:subject>WCS</dc:subject>
>             <dc:subject>ImageMosaic</dc:subject>
>             <dc:subject>black_marble</dc:subject>
>             <dc:description>Generated from ImageMosaic</dc:description>
>             <dc:title>black_marble</dc:title>
>             <dc:type>http://purl.org/dc/dcmitype/Dataset</dc:type>
>             <ows:BoundingBox crs="urn:x-ogc:def:crs:EPSG:6.11:4326">
>                 <ows:LowerCorner>-90.00666691358941 -180.0</ows:LowerCorner>
>                 <ows:UpperCorner>90.0 180.00666679012568</ows:UpperCorner>
>             </ows:BoundingBox>
>         </csw:Record>
>     </csw:SearchResults>
> </csw:GetRecordsResponse>
> ```

Yeah I tried and this is the reason why it gets shows less records.

**Comment by MuhweziDeo** [comment]
@offtherailz .Adding the class .ms2-border-layout-content makes the list load more when the user reaches the bottom of the screen

**Comment by offtherailz** [comment]
@ElenaGallo I changed the text of this issue and of #5110 to better address the real issues (that during the time changes) please take them into account to test the tools.
