### ISSUE TITLE
Improve Circle selection in DrawSupport

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#664]
When drawing a circle with the leaflet DrawSupport the geometry type is set as 'Point'. This generates 
some issues in the GeometryDetails and QueryForm components:
- wrong ogc filter (gml:Point instead gml:Polygon)
- errors when trying to modify the geometry.

**Comment by kappu72** [comment]
A first simple fix is in this pull https://github.com/geosolutions-it/MapStore2/pull/663
I suggest to do a better one.
Both Leaflet and Openlayers DrawSupport should return the default geometry they generate drawing a circle, a point with a radius.
The conversion of this point with radius to a polygon should be done in the queryform reducer when consuming end draw action if the draw method is circle and the geometry type  point.
We will also simplify geometry support removing the polygon calculation.

**Comment by Gnafu** [comment]
The bug is fixed, downgrading this issue to enhancement

**Comment by tdipisa** [comment]
closed for inactivity.
