### ISSUE TITLE
Embedded maps in incognito mode

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6651]
## Description

If you open an embedded map in incognito, MS never stops loading.

![image](https://user-images.githubusercontent.com/1280027/111492695-2fd25380-873d-11eb-9a00-00935e096db5.png)

## How to reproduce

- Open an embedded map (using the related Share tool option)
- Lora it in incognito mode (e.g. using Chrome)

*Expected Result*

The map is properly loaded 

*Current Result*

MS never stops loading.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

Below what reported by the browser console:

```
Uncaught (in promise) DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at https://dev.mapstore2.geo-solutions.it/mapstore/dist/embedded.js?e8da5f0a2caf12b4845c:2:3314684
    at Array.forEach (<anonymous>)
    at Gt (https://dev.mapstore2.geo-solutions.it/mapstore/dist/embedded.js?e8da5f0a2caf12b4845c:2:3314657)
    at https://dev.mapstore2.geo-solutions.it/mapstore/dist/embedded.js?e8da5f0a2caf12b4845c:2:3320672
(index):30 Uncaught ReferenceError: init is not defined
    at onload ((index):30)
```

**Comment by offtherailz** [comment]
The issue is still present. Copying the embedded code in an  **iframe** and opening it in  **incognito mode**

**Comment by offtherailz** [comment]
Prepared the backport to merge as well as the issue has been tested.
https://github.com/geosolutions-it/MapStore2/pull/6821
