### ISSUE TITLE
Improving sharing capabilities for embedded maps

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6688]
## Description

This issue collects some enhancements reported in #6643. 

As part of this issue we should enhance a bit the sharing options for MS embedded resources (maps, dashboards, geostories) to allow the user to better configure **height** and **width** for the embedded code. A new option should be included in the advanced options for this purpose as illustrated below:

![2021_03_23_11_56_30_MapStore_HomePage](https://user-images.githubusercontent.com/1280027/112663761-7a4c8200-8e59-11eb-9d86-cbce763e80c0.png)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Other useful information
Below are reported the default sizes (WxH) corresponding to DD options (small, medium, large):

- Small: 400x300
- Medium: 600x450
- Large: 800x600

It should be also possible to configure default values from configuration file, if needed: this means that related config properties of the plugin can be added to localConfig to override default values only if needed.

**Comment by MuhweziDeo** [comment]
Hey @tdipisa where the predefined sizes available in DD (small, medium, large) agreed upon.

**Comment by ElenaGallo** [comment]
@tdipisa in a [small embedded map](https://github.com/geosolutions-it/MapStore2/files/6349855/small.zip) the sidebar overlaps the search button, isn't it better to hide the search button in the small map?

**How to Reproduce**
- Open a map
- On Burger Menu click on Share
- Click on Embed tab
- Copy the embedded code
- Save the code ad html
- Open the html file

*Current Result*
The sidebar overlaps the share button

**Comment by tdipisa** [comment]
@MuhweziDeo please change the default sizes as follow:
Small: 600x500
Medium: 800x600
Large: 1000x800
