### ISSUE TITLE
Add Slovak (SK) translation

### ISSUE THREAD

**Issue by fgravin** [geosolutions-it/MapStore2#6695]
Hi here,

To share effort and don't overlap, we would like to know if there is any work in progress about Slovak translation ?
Presov team is considering to add this language if nothing has started.

Thanks

**Comment by tdipisa** [comment]
Dear @fgravin at the moment we are not working on this and we are not aware of others who are dealing with it. Therefore, any contribution is welcome, thank you. Can I assign the issue to you then?

**Comment by fgravin** [comment]
@tdipisa yes sure !
