### ISSUE TITLE
Setting custom Identity Viewer from extension

### ISSUE THREAD

**Issue by FNI18300** [geosolutions-it/MapStore2#6702]
## Description
When we build an **extension** with a custom viewer to display Identity data in the DefaultViewer, the registered Viewer is never used.

## How to reproduce
1) Create an extension with a component.
2) In the render method (or in the constructor, or in the componentWillMount...) call setViewer from MapInfoUtils to register a Viewer with a name
...
setViewer( MY_VIEWER, ...);
...

3) via Epics, add a layer with the custom viewer. Exemple: 

export const displayAllRequest = (action$, store) =>
    action$.ofType(actions.DISPLAY_ALL)
        .switchMap(() => {
            const pluiLayer = head(store.getState().layers.flat.filter(l => l.id === myLayerId));
            return Rx.Observable.from(
                pluiLayer
                    ? [refreshLayerVersion(myLayerId)]
                    : [addLayer({
                        handleClickOnLayer: true,
                        hideLoading: true,
                        id: pluiEvolutionLayerId,
                        name: pluiEvolutionLayerName,
                        title: MY_LAYER_TITLE,
                        type: "wms",
                        search: {
                            type: "wfs",
                            url: backendURLPrefix + "/carto/wfsRequest"
                        },
                        params: {
                            exceptions: 'application/vnd.ogc.se_xml'
                        },
                        format: "image/png",
                        singleTile: false,
                        url: backendURLPrefix + "/carto/wmsRequest",
                        visibility: true,
                        featureInfo: {
                            format: "PROPERTIES",
                            viewer: {
                                type: MY_VIEWER
                            }
                        }
                    }),
                        selectNode(myLayerId,"layer",false)
                    ]
            );
        });
Using this code, in extension dev mode, the custom viewer is used.

4) Build extension
5) Deploy extension
6) Clic on the layer => the default viewer is used and the custom one is not used

If we add logs in the MapInfoUtils.js setViewer and getViewer methods in the production environnement
And we add other logs in the MapInfoUtils.js setViewer and getViewer methods in the code used to build the extension
We can see that the getViewer called by the extension is not the same as the getViewer called by the DefaultViewer

*Expected Result*
The behaviour in extension deploy and in dev mod must be the same
And the MapInfoUtils.VIEWERS objet must be shared between extension and core MapStore

*Current Result*
The MapInfoUtils.VIEWERS objet is not shared between extension and core MapStore
2 objects are created and the registered Viewer in extension are not visible by the core MapStore

- [x] Not browser related

**Comment by offtherailz** [comment]
Hi, 
yes you are right. At the actual stage the extension system allows to create custom plugins but they do not allow to access to MapStore internal objects yet. The only things shared are:
 - application state (that is immutable by definition)
 - libs in common (`lodash`, `react`, `redux`, `rxjs`...)

This is basically because `@mapstore` is not a shared module yet, so importing something in you extension will basically import a copy of the component. The possibility to share these functionalities and allow the extensions to invoke some utils that modifies the whole application is under evaluation. 

Actually doing these operation is possible only creating custom projects.

**Comment by offtherailz** [comment]
I'm going to close this in favor of #6702, that includes it.
