### ISSUE TITLE
The first GFI result visualized in Identify panel is not the expected one

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6724]
## Description

We agreed on the solution, that the first element that is received will be selected initially. This is the case so far. Nevertheless as soon as all elements are loaded, the first item in the drop down list is automatically selected, leading to a sudden change in the info panel, in case the first element in list wasn’t the first element to be loaded. We would expect that the first loaded feature stays selected, until the user changes it.

## How to reproduce

Tested on https://qa.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/10358

![gfi_order_issue](https://user-images.githubusercontent.com/1280027/113276086-c6774680-92df-11eb-884e-bf022e31e4a5.gif)

*Expected Result*

We would expect that the first loaded feature stays selected, until the user changes it.

*Current Result*

The first item in the drop down list is automatically selected even if it is not related to the first GFI respose loaded.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by MuhweziDeo** [comment]
Hey @tdipisa. Just want to confirm that the `first loaded feature` is determined the time it takes to complete the request as seen in the network tab

**Comment by tdipisa** [comment]
> Hey @tdipisa. Just want to confirm that the `first loaded feature` is determined by the time it takes to complete the request as seen in the network tab from the demo link shared above

@MuhweziDeo, yes. when the user performs an identify request clickinf on the map, MS performs N requests one for each layer visible in map: the first response MS receives for one of these layers should determines the selection of the corresponding item in DD, but currently always the first one in the list is slected at the end.
