### ISSUE TITLE
Infobox issue with image content left/right aligned

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6728]
## Description

We have the following user feedback:

>When using left/right-align for an image it is not possible to position a text below the image, although the WYSIWYG editor shows it. 
It will always be positioned next to it. We would expect the possibility to position text below an image, independent of the images position.

## How to reproduce

![infobox_issue.gif](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/c50bd143-90fc-4ca4-a8cf-823cfa12a57e)

*Expected Result*

We would expect the possibility to position text below an image, independent of the images position.

*Current Result*

 It is not possible to position a text below the image, although the WYSIWYG editor shows it.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by dsuren1** [comment]
_Note_: 
The issue happens because of empty tags created when user manually pushes the content by hitting '**Enter**'. Fix is required on handling the same.
