### ISSUE TITLE
Input fields issues

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6729]
## Description

We have the following user feedback:

>1. As already reported, coordinate input field is not working properly (for all kind of input, like searching, annotations and measurements): 
When entering coordinates via input field, it is not possible to enter 0 at the end of a decimal place. E.g. entering ‘48.5026’ will result in ‘48.526’, as 0 is skipped. The only workaround is to enter the 0 after all other digits have been entered. (you explained this by the type of input field, which reformats the input automatically)

This issue should have already been fixed in #6689

>2. But this reformatting affects the input also in other ways e.g. when changing values. See video attached below. Changes in seconds input field will reformat this field and affect minutes as well, when e.g. too high values for seconds are entered. But also completely removing values and re-entering seconds will affect minutes (see end of video). The current behavior is extremely confusing for the user and can result in unsolvable situations (e.g. enter 15°10’15’’ and then another 1 for seconds à minutes will be reformatted to ‘12’ and seconds to ‘31’. Remove the ‘31’ and try to re-enter ‘15’ for seconds à minutes will be reformatted to 14 and seconds to ‘30’).

This need to be investigated to do a preliminary evaluation of the problem and of a possible fix.

## How to reproduce

https://images.zenhubusercontent.com/39382076/fcb9c677-fed8-4ad3-bbb6-3c49d994343b/input.mp4

*Expected Result*

We would expect the input fields to work separately from each other and that, instead of any kind of reformatting a user’s input, a warning is given, whenever values are not correct. Entering a 0 without a workaround should also be possible.

*Current Result*

See description

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by dsuren1** [comment]
Yes, currently we [update ](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/misc/coordinateeditors/editors/AeronauticalCoordinateEditor.jsx#L58)the degrees, minutes and seconds fields based on the adjacent field value, when the value is greater than expected value of the field.

**Comment by tdipisa** [comment]
@dsuren1 
In general it would be good if we don't change the value of a field automatically because it can be confusing / annoining for the user. In cases like that, we should simply have a validator that inform the user that the value entered for a field is wrong by marking the field in red and/or showing a tooltip to inform about the error.

**Comment by dsuren1** [comment]
We can instead limit the user input to max value of each field. 
This way we can skip auto formatting of the field and also won't need to add red color to input field for when invalid input etc.

Do we need a helptext/tooltip to show somewhere the max value of the field?

**Comment by tdipisa** [comment]
I'm going to reopen this issue due to the following user feedback:

>-  (!) Wrong formatting after deleting a value: enter 45° 10’ 10’’: the default 0-values are overwritten = OK, BUT when removing 10 for seconds and reentering ‘20’, the zero is not overwritten, but added at the end of the reentered value à user input is changed to ‘200’ instead of ‘20’, which then is reformatted to 59. This behavior is present as well for minutes and degrees input filed

@dsuren1 please check the above, I can reproduce it.

>- Different behavior between aeronautical and decimal degrees:
   >    - When using aeronautical input fields adding a value greater than the allowed one leads to a reformatting (e.g. 100 for minutes, will be changed to 59), which is OK

@dsuren1 please check the second point below If it is quickly posible ok, otherwise we have to discuss.

   >    - When using decimal degrees it is not allowed at all to enter values, which are greater than the allowed value (e.g. entering 181 for longitude is blocked by the system), which is also OK
BUT it would be good to have the same solution for both options in order to not confuse the user, while we prefer the second option as currently used for decimal degrees

**Comment by dsuren1** [comment]
Hi @tdipisa 
Yes, I'm able to reproduce the issue wrt _wrong formatting after deleting a value_
It should be a quick fix
