### ISSUE TITLE
Share by bounding box shows wrong result ?

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6730]
## Description

We have the following user feedback.

>Share by bounding box shows wrong result. Attached you find a video and images showing the issue. In this case sharing the link: https://austrocontrol.geo-solutions.it/austrocontrol-ms2/#/viewer/openlayers/91?bbox=-1.2365477937083256,33.82441087264053,29.18639649513955,45.6371696422341
which seems to use the correct bbox for the shown map, results in opening a map with different extent, although using the same browser window size (switching to a different browser has the same result). 
When creating a new sharing link from this map, the following link is created: https://austrocontrol.geo-solutions.it/austrocontrol-ms2/#/viewer/openlayers/91?bbox=6.369188278503656,36.69457516832796,21.580660422927593,42.63895027595234
which again opens a map at a **higher zoomlevel**.

>The effect on our map is even higher. Sharing this link: https://maps.austrocontrol.at/mapstore/#/viewer/openlayers/121?bbox=7.087595302292528,45.56075722169766,19.256773017831676,49.72440265750633
which should show whole Austria results in a map only showing parts of the district of Salisbury.

**BBOX Shared**
![bbox_shared.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/22d2f4ec-5eba-43ae-80e1-6b73fad81b83)

**BBOX Result in shared map**
![bbox_result.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/961312de-a18d-4746-879b-18a9bcb4537e)

## How to reproduce

https://images.zenhubusercontent.com/39382076/1d061152-bcf4-4fe7-bff4-782a6a32e45e/bounding_box.mp4

*Expected Result*

The zoom level should be the same in the shared map.

*Current Result*

It seems a different zoom level is choosen by MS/OL for the provided BBOX

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

To evaluate if it depends on possible regressions introduced in last releases after [this MS revision](https://github.com/geosolutions-it/MapStore2/tree/706b46621d01975d094d1474fc0fbcfe1a329ddf)

**Comment by tdipisa** [comment]
@offtherailz any thought on this?

**Comment by offtherailz** [comment]
On mapstore I was able to replicate only in local, setting this in `new.json`
```
"mapOptions": {
      "view": {
        "resolutions": [
          84666.66666666688,
          42333.33333333344,
          21166.66666666672,
          10583.33333333336,
          5291.66666666668,
          2645.83333333334,
          1322.91666666667,
          661.458333333335000,
          529.166666666668000,
          396.875000000001000,
          264.583333333334000,
          132.291666666667000,
          66.145833333333500,
          39.687500000000100,
          26.458333333333400,
          13.229166666666700,
          6.614583333333350,
          3.968750000000010,
          2.645833333333340,
          1.322916666666670,
          0.661458333333335
        ]
      }
    },
```

Probably there is some error in the zoom level calculation when the map has custom resolutions. (trying to guess, I think that it calculates using the default ones, instead of custom, because when the calcolous is done, the map is not ready yet to provide the correct resolutions).

**Comment by MuhweziDeo** [comment]
From investigation, it seems there a slight difference in the bounds values in the map from which the share link in generated. Below are the values from the original map and the new map

Original
`0: 1063138.020833333
1: 5118645.833333332
2: 1436861.9791666674
3: 5621354.166666666
`

New Map(From the share link generated)
`0: 1069620.3125000007
1: 5219187.500000001
2: 1430379.6874999995
3: 5520812.499999997
`
the values are over so slightly different but am unable to find out how the `zoom` is being used for the calculations @offtherailz

**Comment by MuhweziDeo** [comment]
After close investigation, I found that the issue is not the zoom level calculations because the zoom is not used anywhere but it may be an issue with how the OpenLayers library works internally(Just guessing). There is a property(`nearest: true`) that when added to the OpenLayers `fit`
https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/map/openlayers/Map.jsx#L643 function tries to solve the issue but it doesn't match fully the zoom level. There is a difference between the original and new zoom level where is always less by one zoom level.

I am not entirely sure how the property `{nearest: true}` works. https://openlayers.org/en/latest/apidoc/module-ol_View-View.html#fit

![Screenshot 2021-04-08 at 13.57.24.png](https://images.zenhubusercontent.com/60350ba854742f543a9fa5ff/dda93686-fab7-4e8a-8df7-a4668d053cf0)

**Before**

![Screenshot 2021-04-08 at 13.57.31.png](https://images.zenhubusercontent.com/60350ba854742f543a9fa5ff/7fdbbe65-2c95-4b83-b529-fdc4f2d3368b)

**After**

![Screenshot 2021-04-08 at 13.57.38.png](https://images.zenhubusercontent.com/60350ba854742f543a9fa5ff/037701b0-a903-469b-978d-ea0e791433da)

**Comment by offtherailz** [comment]
It took a lot to me to figure out the exact problem. Anyway it looks you are on the right path. 
Looking at openlayers code, the nearest vs closest option means to round the zoom level in one direction or the other. 
Closest, (the default) is useful when you have to fit a geometry (e.g. with zoom of the feature grid). While nearest is better in our case ,when you have to fit a bbox, but excluding a small part is not that mess. I can suggest to add an `options` parameter as last parameter of the `zoomToExtent` action. It can contain additional options to pass to the zoom to extent hook (extract only `nearest` from it in the hook code). Then you should use this option only in the `zoomToExtent` of the queryparams epic.

something like this below. Please test and see if this fits the issue in any case. 

`Map.jsx`
```javascript
 this.props.hookRegister.registerHook(mapUtils.ZOOM_TO_EXTENT_HOOK, (extent, { padding, crs, maxZoom: zoomLevel, duration, nearest} = {}) => {
            let bounds = reprojectBbox(extent, crs, this.props.projection);
            // if EPSG:4326 with max extent (-180, -90, 180, 90) bounds are 0,0,0,0. In this case zoom to max extent
            // TODO: improve this to manage all degenerated bounding boxes.
            if (bounds && bounds[0] === bounds[2] && bounds[1] === bounds[3] &&
                crs === "EPSG:4326" && isArray(extent) && extent[0] === -180 && extent[1] === -90) {
                bounds = this.map.getView().getProjection().getExtent();
            }
            let maxZoom = zoomLevel;
            if (bounds && bounds[0] === bounds[2] && bounds[1] === bounds[3] && isNil(maxZoom)) {
                maxZoom = 21; // TODO: allow to this maxZoom to be customizable
            }

            this.map.getView().fit(bounds, {
                size: this.map.getSize(),
                padding: padding && [padding.top || 0, padding.right || 0, padding.bottom || 0, padding.left || 0],
                maxZoom,
                duration,
                nearest
            });
        });
```

epics/map.js:187
```javascript
export const zoomToExtentEpic = (action$, {getState = () => {} }) =>
    action$.ofType(ZOOM_TO_EXTENT).switchMap(( action ) => {
        const extent = toBoundsArray(action.extent);
        if (!extent) {
            return Rx.Observable.empty();
        }
        const hook = MapUtils.getHook(MapUtils.ZOOM_TO_EXTENT_HOOK);
        const padding = mapPaddingSelector(getState());
        if (hook) {
            const { crs, maxZoom, options } = action;
            hook(extent, {
                crs,
                padding,
                maxZoom,
                ...options
            });
            return Rx.Observable.empty();
        }
        return legacyZoomToExtent({...action, extent}, mapSelector(getState()) );
    });
```

actions/map.js:123
```javascript
/**
 * zoom to the specified extent
 * @memberof actions.map
 * @param {number[]} extent in the form of [minx, miny, maxx, maxy]
 * @param {string} crs related the extent
 * @param {number} maxZoom the max zoom limit
 * @param {object} options additional options. `nearest` supported by openlayers, allow to round the zoom level to the nearest value, not the closest (min that fully contains)
*/
export function zoomToExtent(extent, crs, maxZoom, options) {
    return {
        type: ZOOM_TO_EXTENT,
        extent,
        crs,
        maxZoom,
        options
    };
}
```

queryparams.js, line 31
```
bbox: ({ value = '' }) => {
        const extent = value.split(',')
            .map(val => parseFloat(val))
            .filter((val, idx) => idx % 2 === 0
                ? val > -180.5 && val < 180.5
                : val >= -90 && val <= 90)
            .filter(val => !isNaN(val));
        if (extent && extent.length === 4 && isValidExtent(extent)) {
            return [
                zoomToExtent(extent, 'EPSG:4326', undefined, {nearest: true})
            ];
        }
        return [
            warning({
                title: "share.wrongBboxParamTitle",
                message: "share.wrongBboxParamMessage",
                position: "tc"
            })
        ];
    },
```

**Comment by tdipisa** [comment]
I'm going to reopen this since it seems the bug is not completely resolved. Below is reported the user feedback:

>Still not working on high zoom levels. Zoom to scale 1:100.000 at https://austrocontrol.geo-solutions.it/austrocontrol-ms2/#/viewer/openlayers/763 and share by bounding box à reopens at 1:150.000 on same screen and window size.

**Comment by MuhweziDeo** [comment]
> I'm going to reopen this since it seems the bug is not completely resolved. Below is reported the user feedback:
> 
> > Still not working on high zoom levels. Zoom to scale 1:100.000 at https://austrocontrol.geo-solutions.it/austrocontrol-ms2/#/viewer/openlayers/763 and share by bounding box à reopens at 1:150.000 on same screen and window size.
> 
> @MuhweziDeo Can you please check what reported below and provide the necessary fix?

okay

**Comment by tdipisa** [comment]
@MuhweziDeo I cannot reproduce what reported [here](https://github.com/geosolutions-it/mapstore2/issues/6730#issuecomment-841142613) in both MS DEV and QA. Does [this branch](https://github.com/geosolutions-it/MapStore2/tree/c125_search_gfi) contain the fix you made for this bug? Can you please check this first of all, this is the branch we are using for the c125 MS project where @dsuren1 should have backported all fixes you did for issues belonging to [this epic](url)

**Comment by offtherailz** [comment]
When we share center and zoom, it should be guaranteed that the resolution and the position is the same.
When we share bbox, we do a zoomToExtent to the current viewport of the user. This doesn't guarantee that the resolution is the same, it depends on the current window size. This option guaraneed that all the things that the user is seeing in the current viewport is visible also to the user that gets the shared URL. 

The issue notified regards the same screen size. It doesn't happen, or at least has not been found on the standard mapstore.

So probably it can be due to some approximation did with resolutions calculation or, most probably, because of the [padding](https://github.com/geosolutions-it/MapStore2/pull/6759/files#diff-47404a67952b02809f8241233cc398f3c9b8033c9088e1f9c6e7003ff3471ebdR643)  that if it is not zero, makes the viewport not big enough to contain the shared bbox.
Note that the padding is also involved in the issue #6732 

You can debug checking the padding compared to mapstore, and try to force it to zero to see if it is the source of the problem. 

For usage: If you need the resolution to be strictly the same, use center and zoom, anyway.

**Comment by MuhweziDeo** [comment]
> When we share center and zoom, it should be guaranteed that the resolution and the position is the same.
> When we share bbox, we do a zoomToExtent to the current viewport of the user. This doesn't guarantee that the resolution is the same, it depends on the current window size. This option guaraneed that all the things that the user is seeing in the current viewport is visible also to the user that gets the shared URL.
> 
> The issue notified regards the same screen size. It doesn't happen, or at least has not been found on the standard mapstore.
> 
> So probably it can be due to some approximation did with resolutions calculation or, most probably, because of the [padding](https://github.com/geosolutions-it/MapStore2/pull/6759/files#diff-47404a67952b02809f8241233cc398f3c9b8033c9088e1f9c6e7003ff3471ebdR643) that if it is not zero, makes the viewport not big enough to contain the shared bbox.
> 
> In fact any zoom to extend in mapstore is done taking into account the padding to take into account the floating panels.
> 
> Anyway when we get the bbox, the padding is not considered, so you get the full map. Trying to zoom to an extent with some padding can cause this issue.
> Note that the padding is also involved in the issue #6732 , with a bottom padding for the future that should has been, anyway, removed.
> 
> You can debug checking the padding compared to mapstore, and try to force it to zero to see if it is the source of the problem.
> 
> For usage: If you need the resolution to be strictly the same, use center and zoom, anyway.

thanks @offtherailz

**Comment by tdipisa** [comment]
@MuhweziDeo please check what reported by @offtherailz here:

**Comment by MuhweziDeo** [comment]
@offtherailz I don't think the padding affects this in any way after testing. I can only the issue coming from the calculations because currently, the zoom will always be less by 1 as per discovery I am not entirely sure why this is so or possible cause but still trying to find out.

**Comment by MuhweziDeo** [comment]
**This is the original view of the map before sharing** 
<img width="1440" alt="Screenshot 2021-05-14 at 18 35 04" src="https://user-images.githubusercontent.com/39124174/118294377-544f6f80-b4e3-11eb-85d9-f8f435cb6b1c.png">
**This is the new view of the map after sharing with bounding box ** 
<img width="1439" alt="Screenshot 2021-05-14 at 18 35 51" src="https://user-images.githubusercontent.com/39124174/118294407-5c0f1400-b4e3-11eb-9cff-a8369dbfd393.png">

The new view is more zoomed in for sure. could the map centering coz this effect in anyway.

**Comment by offtherailz** [comment]
Please correct me if I'm wrong, so you said: 
- You tested putting resolutions in new.json, so you are able to replicate the same problem on mapstore. This means that (if you can not replicate with standard resolutions) this problem is caused by custom resolutions.
- padding is zero for all top, bottom, left, right, so it is not the cause
- `nearest` parameter has any influence on that ?
- For 'Drawing the bbox' i meant to you could try to use the exact coordinates from the state to draw a rectangle (annotation tool has the coordinate editor) to see if they go somehow outsid the current box.

I'm afraid is a problem of zoomToExtent !== currentViewport, and the calculation may differ, anyway it is strange that it never happens if you don't customize resolutions

**Comment by MuhweziDeo** [comment]
> Please correct me if I'm wrong, so you said:
> 
> * You tested putting resolutions in new.json, so you are able to replicate the same problem on mapstore. This means that (if you can not replicate with standard resolutions) this problem is caused by custom resolutions.
> * padding is zero for all top, bottom, left, right, so it is not the cause
> * `nearest` parameter has any influence on that ?
> * For 'Drawing the bbox' i meant to you could try to use the exact coordinates from the state to draw a rectangle (annotation tool has the coordinate editor) to see if they go somehow outsid the current box.
> 
> I'm afraid is a problem of zoomToExtent !== currentViewport, and the calculation may differ, anyway it is strange that it never happens if you don't customize resolutions

- Yes for sure custom resolutions coz this behavior
- nearest parameter reduces the margin indifference in the zoom levels
-

**Comment by MuhweziDeo** [comment]
could be the potential cause of the issue https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/map/openlayers/Map.jsx#L525. The `view.getZoom()` returns a value that is always less than the original value of the map share with bbox. 
<img width="703" alt="Screenshot 2021-05-18 at 10 54 08" src="https://user-images.githubusercontent.com/39124174/118613672-a6381400-b7c7-11eb-9953-207cea6cdce0.png">
<img width="802" alt="Screenshot 2021-05-18 at 10 54 18" src="https://user-images.githubusercontent.com/39124174/118613689-a9cb9b00-b7c7-11eb-9c92-011fc6c621b0.png">

**Comment by MuhweziDeo** [comment]
The view resolution is also quite different 

**Original**
<img width="702" alt="Screenshot 2021-05-18 at 11 01 02" src="https://user-images.githubusercontent.com/39124174/118614523-8523f300-b7c8-11eb-85b8-d57206467aa6.png">

**New shared map**
<img width="758" alt="Screenshot 2021-05-18 at 11 00 53" src="https://user-images.githubusercontent.com/39124174/118614556-90771e80-b7c8-11eb-9c41-8e96797211e3.png">

**Comment by MuhweziDeo** [comment]
Could this be the real cause of the issue right now I can only this point as the origin what do you think @offtherailz

**Comment by MuhweziDeo** [comment]
There is always a slight difference in the zoom and resolution from the `view` right now the new map will have a greater resolution. I have tried to look at the source code of OpenLayers https://github.com/openlayers/openlayers/blob/v6.5.0/src/ol/View.js to see if I can trace it down how `getZoom` and `getResolution`.  work internally and so far I cannot point out the exact cause. cc @tdipisa
