### ISSUE TITLE
Order of Nominatim search results

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6731]
## Description

We have the following user feedback:

>Order of Nominatim search results: they are supposed to have priority 5, but are always shown on top, although we defined other services having priority 1

## How to reproduce

-   Search for “LOWW” in [this map](https://austrocontrol.geo-solutions.it/austrocontrol-ms2/#/viewer/openlayers/763)

*Expected Result*

the order of results must respect the priority configured in the service settings.

*Current Result*

The priority seems not respected in some cases. At the moment I'm not able to reproduce this in DEV using [this sample map](https://qa.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/10358).

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@MV88 any thought on this?

**Comment by MV88** [comment]
the problem is in the configuration

if you define a search service and you do not set the priority, this one is set to 0 [here](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/epics/search.js#L77)

so the easy fix is to add "priority": 5 near "type": "nominatim" in the Search plugins in localConfig.json

**Comment by tdipisa** [comment]
@MV88 I think we simply need a PR in the c125 project to fix the configuration. I'm going to move the issue on c125 project so that you can refer it for your PR.

**Comment by tdipisa** [comment]
Issue moved to [geosolutions-it/austrocontrol-C125 #274](https://github.com/geosolutions-it/austrocontrol-C125/issues/274) via [**ZenHub**](https://www.zenhub.com/)
