### ISSUE TITLE
Different Special Group Of Users

### ISSUE THREAD

**Issue by NevesDev** [geosolutions-it/MapStore2#6734]
## Description
I want to have maps for unauthenticated users and for authenticated users.
But I don't want authenticated users to see maps of unauthenticated users.

For that I will have to create or adapt the user group "Everyone" for these characteristics.

I deleted this snippet of code to perform a test:
![2](https://user-images.githubusercontent.com/55387163/113328171-49090180-92f2-11eb-98db-39d805434a3c.png)

But it ended up only allowing the withdrawal of the group when creating a user, but when saved the changes the group "everyone" remains in the user:
![3](https://user-images.githubusercontent.com/55387163/113328169-48706b00-92f2-11eb-9f3c-02cb082d1452.png)

Every help is welcome!

Thank you very much

## Other useful information
This is the conversation about this problem on google groups, in case you need more information
https://groups.google.com/g/mapstore-developers/c/wJfL20itoJg

**Comment by offtherailz** [comment]
This feature can be added by altering the database, see the mailing list discussion. Going to close it
