### ISSUE TITLE
Cannot disable "snap to guide layer"

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/MapStore2#6741]
I'm trying to unselect the "snap to guide layer" timeline option on [this GeoNode layer](https://master.demo.geonode.org/layers/geonode_master_data:geonode:boxes_with_date).
Clicking on the switch 4 GetDomainValue requests are sent to the WMTS service, and nothing happens. The switch is not toggled.

![toggle snap option](https://user-images.githubusercontent.com/571129/113721468-daf87c00-96ef-11eb-9d4b-4305d252d1f7.gif)

**Comment by tdipisa** [comment]
@giohappy. All seems working fine in both DEV and QA instances: I've tried adding the same layer to the map. It is probably an issue to check in GeoNode (ms geonode client probably or its configuration) 

![image](https://user-images.githubusercontent.com/1280027/113866941-32f5b800-97ae-11eb-8a64-3518421f644d.png)

**Comment by giohappy** [comment]
Issue moved to [geosolutions-it/geonode-mapstore-client #216](https://github.com/geosolutions-it/geonode-mapstore-client/issues/216) via [**ZenHub**](https://www.zenhub.com/)
