### ISSUE TITLE
Spinner is not displayed in the GFI panel between user requests

### ISSUE THREAD

**Issue by dsuren1** [geosolutions-it/MapStore2#6748]
## Description
The loader/spinner is not displayed in the GFI panel between user requests

Note: This issue is a possible regression from https://github.com/geosolutions-it/mapstore2/issues/6365

## How to reproduce
- Open this [map](https://dev.mapstore2.geo-solutions.it/mapstore/?debug=true#/viewer/openlayers/10358)
- Click on any state and observe the GFI panel
- Spinner/Loader is not displayed

*Expected Result*
Spinner should be displayed until a valid response is received 

*Current Result*
Spinner is not displayed between user requests of get feature info

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by MuhweziDeo** [comment]
The issue came about because the loaded state of the MapInfo was set to true before any responses are got back.
