### ISSUE TITLE
Dev Setup and Run problem : Can not login

### ISSUE THREAD

**Issue by iamtekson** [geosolutions-it/MapStore2#6756]
## Description
I just set up and run the mapstore by following this doc: https://mapstore.readthedocs.io/en/v2019.01.00/developer-guide/. Now I tried to log in here using username `admin` and password `admin`, but it shows the error message `Login Fail Username or password incorrect`

*Expected Result*
I expected to log in as an admin user.

version: master branch from github

**Comment by iamtekson** [comment]
Sorry, I just found that the mapstore demo backend uses https://dev.geo-solutions.it/mapstore/ as back-end. And for the development, I found this doc, https://mapstore.readthedocs.io/en/latest/developer-guide/developing/. This means I need to set my own backend for `admin` access. Please correct me if I am wrong. 

Since I have windows, I found it difficult to set up my backend as explained in the documentation.

**Comment by tdipisa** [comment]
@iamtekson yes, correct. You have to setup your own local DB as explained in the documentation [here](https://mapstore.readthedocs.io/en/latest/developer-guide/database-setup/) and, yes, also the doc [here](https://mapstore.readthedocs.io/en/latest/developer-guide/developing/). In case of any trouble following the documentation, please use the MapStore mailing list for this kind of topics. The latest version is 2021.01.01.
