### ISSUE TITLE
MapStore crashes when importing a 4326 layer with data beyond the area of use of 3857

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/MapStore2#6766]
## Description
Adding an EPSG:4326 layer containing data beyond the area of use of EPSG:3857 makes something wrong happen in MapStore:

 - the data is not drawn on the map
 - trying to switch the CRS of the map to 4326 crashes MapStore

![crash_4326_import](https://user-images.githubusercontent.com/571129/114429640-e2bb9300-9bbd-11eb-8499-2e0bd7355aed.gif)

## How to reproduce
- Import [points4326_beyond3857.zip](https://github.com/geosolutions-it/MapStore2/files/6298358/points4326_beyond3857.zip) on a map with CRS EPSG:3857 selected
- Switch CRS to EPSG:4326

*Expected Result*
A baisc solution would be to warn the user about the problem with data boundaries beyond the accepted boundaries for the currently selected CRS (probably with a less technical wording!), and block the upload.

A more advanced solution would be to accept the data and show only the portion of data that is compatible with the currently selected CRS (truncate beyond -85.06 / 85.06 latituteds). The data will be fully visible when switching to an EPSG supporting its full spatial extent.

*Current Result*
- Nothing is initially shown
- A crash happens trying to switch the map's CRS

**Comment by tdipisa** [comment]
@giohappy I would like to opt for the basic solutions for the moment since also in other cases we notify the user for similar CRS incompatibilities (like the Catalog tool)

**Comment by giohappy** [comment]
@tdipisa I'm fine with that, As usual what is important is not to leave the user with a crash or a unconsistent state.

**Comment by MuhweziDeo** [comment]
@giohappy thanks for the recommendations. I just want to confirm on this point here `A baisc solution would be to warn the user about the problem with data boundaries beyond the accepted boundaries for the currently selected CRS (probably with a less technical wording!), and block the upload.`. By blocking the upload are you referring to when the user is `importing the layer`

**Comment by giohappy** [comment]
yes @MuhweziDeo
