### ISSUE TITLE
GFI Panel - Graphical bug

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6768]
## Description

We have the following user feedback:

>Graphical bug: when the coordinate editor in the GFI window is activated, the arrows of the input fields are overlapping the content of the dropdown box

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/80b36c92-0957-4c52-8137-af8b752766d4)

## How to reproduce

![gfi_overlap.gif](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/fdbbd62a-6a1a-4582-93e6-7f0079f7923c)

*Expected Result*

The DD menu must properly cover the input field behind

*Current Result*

 the arrows of the input fields are overlapping the content of the dropdown menu

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by MuhweziDeo** [comment]
Seems a z-index Issue. The editor needs to be given a z-index in order not to overlap
