### ISSUE TITLE
UniqueInterval support for classified styles in Style Editor

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6797]
## Description

The support for the **uniqueInterval** classification method need to be included for [classified styles](https://mapstore.readthedocs.io/en/latest/user-guide/layer-settings/#classification-style) in the [MapStore Visual Style Editor](https://mapstore.readthedocs.io/en/latest/user-guide/layer-settings/#visual-editor-style) (only for vector layers, the classification for raster layer is not currently available in MS, this is future task).

Currently supported methods are:
- Quantile
- Equal interval
- Natural breaks
- Standard deviation

![image](https://user-images.githubusercontent.com/1280027/116231280-f25bdf80-a758-11eb-86fa-a5bca326665e.png)

Below the expected activities for this issue:

- Add unique interval to the SLDService requests workflow
- Create/update classification component to support unique interval
- Include the new component to all classification simbolizers for vector layers (mark, line, fill, text rules in visual style editor)

The following components in the style editor need to be updated since the current ones are working only with a min/max range and number values:

- Add specific request and response parsing for unique interval
- Create/Improve the classification component: probably we need additional field for custom properties (eg. intervalForUnique) to limit the returned value
- Include the new component in the symbolizers for vector layers (only the new unique interval classificator)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Other... Please describe: Classifier improvement

## Other useful information
The development of the frontend part needs some enhancements also in the sldservice backend for GeoServer (work done with, https://github.com/geosolutions-it/C183-ALMAVIVA-2020-GeoNode-DEV/issues/193). The updates sldservice will be deployed in GeoSolutions gs-stable.

**Comment by tdipisa** [comment]
@nmco @taba90 I would like to have [this](https://github.com/geoserver/geoserver/pull/4990) deployed in our gs-stable to start the development, it seems not yet backported.

**Comment by nmco** [comment]
We are trying to early back-port it:
https://github.com/geosolutions-it/C183-ALMAVIVA-2020-GeoNode-DEV/issues/193#issuecomment-828527596

**Comment by nmco** [comment]
@tdipisa geosolutions-it/C183-ALMAVIVA-2020-GeoNode-DEV#193has been merged and backported up to 2.18.x.

**Comment by tdipisa** [comment]
@nmco thank you
