### ISSUE TITLE
Return a message to the user in case the layer for a widget is not available

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/MapStore2#6798]
## Description
If the Geoserver layer for a widget is not available a simple exlamation mark is reported, without any hint for the user.

![image](https://user-images.githubusercontent.com/571129/115576751-15ebd980-a2c4-11eb-827e-ef8b20f6dcf1.png)

A more descriptive message below the mark would help in underrstanding where the problem lies. Someting like "Layer xxxx is not available ."

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by QSafariallahkheili** [comment]
@giohappy Could you please give more details about how to reproduce this issue?

**Comment by giohappy** [comment]
A preexisting map configuration was referencing a layer that doesn't exist anymore on Geoserver. The widget that was referencing that layer is marked with the exclamation mark but it doesn't provide any hint about the problem.

**Comment by tdipisa** [comment]
@QSafariallahkheili I've prepared a [map for you in DEV](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/34802) to quickly reproduce the case mentioned by @giohappy.
The layer **test:Linea_costa_test** used for the chart widget has been deleted from GeoServer.
