### ISSUE TITLE
c125 print issue to check

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6809]
## Description

We have the following client feedback:

>When printing any WMTS layer everything outside a specific box is covered by a transparent white area (see the attached PDF). Printing the WMS of the same layer works fine. As this area possibly covers other important information, we need everything, except for the layers information, to be fully transparent, as it is displayed in the map.

[https://app.zenhub.com/files/39382076/8df63ff6-1700-41c2-84fa-762ea301c3a0/download](https://app.zenhub.com/files/39382076/8df63ff6-1700-41c2-84fa-762ea301c3a0/download)

It seems the issue is the same reported [here](https://github.com/geosolutions-it/austrocontrol-C125/issues/144#issuecomment-620455864) and [here](https://github.com/geosolutions-it/MapStore2/issues/5292).

We have only to check if there is a config.yml configuration involved and report back.

## How to reproduce

-  Not able to reproduce the issue in [c125 DEV](https://austrocontrol.geo-solutions.it/austrocontrol-ms2/#/)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
Waiting further feedback about steps to reproduce

**Comment by michegg** [comment]
use: [https://sdimdt-free.austrocontrol.at/mapstore/#/viewer/openlayers/121](https://sdimdt-free.austrocontrol.at/mapstore/#/viewer/openlayers/121)
search for "LOLW" in the ToC and activate the layer: "LOLW - VFR Chart"
Print at the current zoom level and the result should look like this: 
![print](https://user-images.githubusercontent.com/57953447/116356829-11f81400-a7fc-11eb-99d5-1dec578859cf.png)

I also haven't been able to reproduce at: [https://austrocontrol.geo-solutions.it/austrocontrol-ms2/#/viewer/openlayers/763](https://austrocontrol.geo-solutions.it/austrocontrol-ms2/#/viewer/openlayers/763)

**Comment by dsuren1** [comment]
Hi @tdipisa 
I checked all the commits involving the fixes made as part of the WMTS and other fixes related to printing. I'm sure the master branch has all the commits. Also since the dev instance of the [Austrocontrol ](https://austrocontrol.geo-solutions.it/austrocontrol-ms2/#/viewer/openlayers/763) is working fine, I would like the client to check, just to be sure, they have not missed any steps during the deployment with respect to print plugin also not accidentally using any old version (if any).
https://mapstore.readthedocs.io/en/latest/developer-guide/printing-module/

**Comment by tdipisa** [comment]
@michegg can you please ensure you have [this line](https://github.com/geosolutions-it/MapStore2/blob/c125_search_gfi/resources/geoserver/print/config.yaml#L46) in your config.yaml file.

**Comment by michegg** [comment]
@tdipisa thanks! that solves the problem.

**Comment by tdipisa** [comment]
@michegg thank you for the feedback. I'm going to close the issue.
