### ISSUE TITLE
Classification rule UI manager for raster layers

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6810]
## Description

With the current implementation, the raster symbolizer has a minimum set of functionality compared to vector symbolizers.
For vector layers it is currently possible to manage classification rules from the UI by changing values and colors for each rule 

_The current state of the Raster Symbolizer classification editor_

![image](https://user-images.githubusercontent.com/19175505/116265461-6dce8880-a77b-11eb-8029-d1f6c132ac5c.png)

Missing components and/or needed improvements:

- The Contrast enhancement properties selection is incomplete. It seems to work only with none inside the classification panel. eg: Normalize allow different algorithm with min and max value see [RasterSymbolizer doc](https://docs.geoserver.org/latest/en/user/styling/sld/reference/rastersymbolizer.html#contrastenhancement). Probably this task needs some updates on the style parsers CSS and SLD
- Add missing methods: Standard Deviation and Equal Interval (2). We should evalue if they need additional properties and/or if they makes sense for raster classification
- Add classification entries editor similar to vector layers (1)

(1) For raster layers it is possible to classify the style but the same UI to manage classifications rules is not available **and need to be included as part of this issue.**

_Classification entries editor for vector layers_

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/17a4cba2-b3b5-4051-8971-5111d982891c)

(2) Along with the above requirement, the **uniqueInterval classification method** included with #6797 need to be included also for raster styles:

_Current methods available for raster symbolizer classification_

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/c7aaaa85-e60e-4436-ba20-91e860600856)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by allyoucanmap** [comment]
The current state of the style editor:
![image](https://user-images.githubusercontent.com/19175505/116265461-6dce8880-a77b-11eb-8029-d1f6c132ac5c.png)

Missing components and/or needed improvements:

- The Contrast enhancement properties selection is incomplete. It see to work only with none inside the classification panel. eg: Normalize allow different algorithm with min and max value see [RasterSymbolizer doc](https://docs.geoserver.org/latest/en/user/styling/sld/reference/rastersymbolizer.html#contrastenhancement). Probably this task needs some updates on the style parsers CSS and SLD
- Add missing methods: Standard Deviation and Equal Interval. We should evalue if they need additional properties and/or if they makes sense for raster classification
- Add classification entries editor similar to vector layers

**Comment by dsuren1** [comment]
@tdipisa @allyoucanmap 
**Issue 1**
> Missing components and/or needed improvements:
> 
> * The Contrast enhancement properties selection is incomplete. It see to work only with none inside the classification panel. eg: Normalize allow different algorithm with min and max value see [RasterSymbolizer doc](https://docs.geoserver.org/latest/en/user/styling/sld/reference/rastersymbolizer.html#contrastenhancement). Probably this task needs some updates on the style parsers CSS and SLD

After discussion with @allyoucanmap and some investigation, it looks like the additional algorithms supported by Normalize (`StretchToMinimumMaximum`, `ClipToMinimumMaximum` and `ClipToZero`) mentioned in [RasterSymbolizer doc](https://docs.geoserver.org/latest/en/user/styling/sld/reference/rastersymbolizer.html#contrastenhancement) are not supported natively by the [geostyler-sld-parser](https://github.com/geostyler/geostyler-sld-parser/blob/b07d6e71553ca2c99a15a60e7d1bf63df091cefd/src/SldStyleParser.ts#L800) and [geostyler-style](https://github.com/geostyler/geostyler-style/blob/e11fd032b7ee21affd6548acce3ff0568439e185/style.ts#L555). 
Unfortunately there aren't any open issue on Raster symbolizer or customization of normalize contrast enhancement in the _geostyler_ library. So we might need to create a feature request or a issue proposal to _geostyler_ library for the support of _customize Normalize Contrast Enhancement_. Similiary the enhancement has to be made on [geostyler-geocss-parser](https://github.com/geosolutions-it/geostyler-geocss-parser) for css styler

**Issue 2**
> * Add missing methods: Standard Deviation and Equal Interval (2). We should evalue if they need additional properties and/or if they makes sense for raster classification

Standard Deviation is supported only on vector layers

> * Add classification entries editor similar to vector layers (1)
> 
> (1) For raster layers it is possible to classify the style but the same UI to manage classifications rules is not available **and need to be included as part of this issue.**

> (2) Along with the above requirement, the **uniqueInterval classification method** included with #6797 need to be included also for raster styles:

**_Classification rules field sample_**, assuming that it should support custom intervals
![Raster_classification](https://user-images.githubusercontent.com/26929983/119976481-c55b5080-bfd4-11eb-900e-325ab70187bc.jpg)


Could we split this (#6810) issue into two, one to separately investigate and decide on the external & internal library improvement to support algorithms and one to enhance to the raster classification styling?

**Comment by tdipisa** [comment]
@dsuren1 you can split the issue as you suggested in the above comment.
Summarizing, if I understood correclty, we have:

- One issue for the support of Normalize a algorithms that should be included in 
   - https://github.com/geostyler/geostyler-geocss-parser and https://github.com/geostyler/geostyler. Please open an issue in the official repos for this to inform about that and to start moving things to have our work merged at the end. The development for this work must be made in a geosolutions fork and PRs should be raised from there; until our PRs are merged, in mapstore we use our fork as a dependency (just in case we need to wait a long time to have them merged in the official repo)
   
   - https://github.com/geosolutions-it/geostyler-geocss-parser this is totally under our control at the moment

- One issue for the classification implementation (this issue)

**Comment by dsuren1** [comment]
**_Note:_** This issue will handle the enhancement to the raster classification styling

**Comment by tdipisa** [comment]
> **_Note:_** This issue will handle the enhancement to the raster classification styling

@dsuren1 just to be clear, this point:

> One issue for the support of Normalize a algorithms that should be included in

is covered by #6933 right?

**Comment by dsuren1** [comment]
Yes, that's right @tdipisa
