### ISSUE TITLE
Add filter to CSW Catalog to request only layers

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#6813]
## Description

The CSW requests include all the resources available so the Catalog cards will show an error when the record item is not a layer. An example is the geonode mapstore client that using the CSW catalog of GeoNode shows all other contents such as maps, documents, ... with an error

To avoid listing these additional resources inside the MapStore client catalog a filter must be always included:

```xml
<csw:Constraint version="1.1.0">
  <Filter xmlns="http://www.opengis.net/ogc">
	 <Or>
	 <PropertyIsEqualTo>
		 <PropertyName>dc:type</PropertyName>
		 <Literal>dataset</Literal>
	 </PropertyIsEqualTo>
	 <PropertyIsEqualTo>
		 <PropertyName>dc:type</PropertyName>
		 <Literal>http://purl.org/dc/dcmitype/Dataset</Literal>
	 </PropertyIsEqualTo>
	</Or>
  </Filter>
</csw:Constraint>
```

Below screenshot of the current Catalog showing resources different from layers.

![image](https://user-images.githubusercontent.com/19175505/116238474-aa8d8600-a761-11eb-8428-42e545171394.png)

The CSW catalog must continue working on: 
- GeoNode (https://master.demo.geonode.org/catalogue/csw?service=CSW&version=2.0.2&request=)
- Geoserver (https://gs-stable.geo-solutions.it/geoserver/csw?service=CSW&version=2.0.2&request=)
- GeoNetwork (http://gn3-rndt.geo-solutions.it/geonetwork/srv/eng/csw)

Showing only datasets, not services.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features

**Comment by offtherailz** [comment]
One note: http://gn3-rndt.geo-solutions.it/geonetwork/srv/eng/csw doesn't seems to be compatible, so you can skip this test.

**Comment by allyoucanmap** [comment]
please @MuhweziDeo backport this fix to https://github.com/geosolutions-it/MapStore2/tree/geonode-mapstore-client-2.1.x

**Comment by offtherailz** [comment]
Can be related to this https://github.com/georchestra/mapstore2-georchestra/issues/257

**Comment by offtherailz** [comment]
can be related to https://github.com/georchestra/mapstore2-georchestra/issues/257

**Comment by tdipisa** [comment]
@offtherailz is it possible to configure this filter?

**Comment by offtherailz** [comment]
No, it is not confiurable. The only improvement is that the generated filter now is a little more specific, to get only dataset  type contents (not other types), avoiding some results.

**Comment by tdipisa** [comment]
@offtherailz it should be configurable so that the filter can be set up depending on the use case and context where MS is used. By default we expected to have the catalog tool to browse all metadata available in a CSW catalog, with the possibility to add a layer to the map if WMS resources are connected to the metadata.
