### ISSUE TITLE
Remove 'allowFullScreen' Iframe attribute from dashboard and geostory share

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6817]
## Description

With #6761 the **allowFullScreen** attribute has been added also on the embed snippet of dashboard and geostory but it is not needed there so it should be removed for them.

## How to reproduce

-  Open the share->embed tool of a dashboard or a geostory

![2021_04_28_17_24_55_MapStore_HomePage.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/372738ca-19aa-4b19-ac8a-2b6c071874d7)

*Expected Result*

The **allowFullScreen** should not be present in the embedded snippet of dashboards and geostories.

*Current Result*

The **allowFullScreen** is present in all cases.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by ElenaGallo** [comment]
@MuhweziDeo The **allowFullScreen** attribute is still present from the dashboard and geostory cards on the home page

**How to Reproduce**
Follow the steps shown in the gif below:
![share_dash_story](https://user-images.githubusercontent.com/56537133/117954515-62e92b80-b317-11eb-841b-79f05a6fa4f2.gif)
