### ISSUE TITLE
Password reset not working anymore

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#6825]
## Description
From the mailing list. 
https://groups.google.com/g/mapstore-users/c/eZ_uL0slSgE/m/279pQOcLAgAJ

## How to reproduce
-  As user, try to change the password from the user menu

*Expected Result*
- Password change successful

*Current Result*
- Password change fails
- In console, you can see error 404 not found with the following response: `At least one User group not found; review the groups associated to the user you want to insert<ID>' where <ID> is the ID of the user on the DB.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

This bug is currently affecting only the master branch: tested in 2021.01.02 and QA instances.

**Comment by tdipisa** [comment]
Should be fixed by:
https://github.com/geosolutions-it/geostore/pull/228
