### ISSUE TITLE
3D mode issue due to invalid Cesium certificate

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6838]
## Description

Recently identified issue with the 3D: there are problems loading the 3D mode. Maybe a problem with invalid certificate on cesiumjs.org side and due to this some resources are not loaded.

## How to reproduce

-  Open a map 
- Switch to 3D mode

*Expected Result*

3D mode should work properly

*Current Result*

Switching to 3D mode the map is not loaded

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/6b937b56-9ead-4451-acd1-1ab51af8f981)

In console we have:
![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/a087b4cf-dd9e-4a09-8a58-75cdc6993b03)
![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/0352b3a4-4b21-43e6-943b-089d32ef05fc)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
The certificate expired 2021/5/5. Probably this is a temporary issue that is going to be resolved soon by cesium.org admins

**Comment by offtherailz** [comment]
Now, If accept the certificate, I'm redirected to https://cesium.com/downloads/cesiumjs/releases/1.17/Build/Cesium/Cesium.js
This means they have moved the files to another location and the certificate issue is only for the old URL. We can change the URL with the new one, avoiding this problem.

Anyway I asked a question here:
https://community.cesium.com/t/certificate-problem-on-1-17-url-cesiumjs-org-releases/13550

**Comment by offtherailz** [comment]
2 PR, one for doc, one for fix + 1 backport of both the PR ready to be merged, as well as tested.

**Comment by ElenaGallo** [comment]
@offtherailz tes in dev done, you can merge the backport
