### ISSUE TITLE
Improve strings for french translation

### ISSUE THREAD

**Issue by MaelREBOUX** [geosolutions-it/MapStore2#6843]
## Description
For the georchestra project we need to change some strings that are leading users to confusions between some concepts.

See https://github.com/georchestra/mapstore2-georchestra/issues/367 for details.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Code style update (formatting, local variables)

**Comment by MaelREBOUX** [comment]
TODO

- [ ] Afficher la légende et les outils -> Légende et visibilité

**Comment by MaelREBOUX** [comment]
I have not yet worked on the 4 string listed above. PR to come

**Comment by MaelREBOUX** [comment]
Hello @ElenaGallo 

I cannot find string to change the name of the measurement layer added when doing :

![image](https://user-images.githubusercontent.com/6370443/121690628-5f87c200-cac6-11eb-9a98-97370a668f5c.png)

We want it named in the user langage. Need a specific issu maybe ?

**Comment by tdipisa** [comment]
@MaelREBOUX this is a closed issue, so yes please open a new one. Thank you so much for contributing.
