### ISSUE TITLE
Need more tooltip for the main menu / the "burger" menu

### ISSUE THREAD

**Issue by MaelREBOUX** [geosolutions-it/MapStore2#6846]
## Description

As discussed in https://github.com/georchestra/mapstore2-georchestra/issues/369 we discovered that we can have tooltips in the burger menu.

To have them one have (thanks to @Gaetanbrl) :

- a `tooltip` item in the strings localization files in `/web/client/translations`
- a `tooltip` item to map to the string in the `.jsx` file of the plugin in `/plugins/my_plugin/my_plugin.jsx`

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [x] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Other useful information

We note that some items in the menu Burger are not JSON structured like others : there is actually no `title` or `tooltip` possible for the `Save` or the `SaveAs` functions.
We think that modifying the actual JSON structure for these 2 functions will broke all strings.
See https://github.com/geosolutions-it/MapStore2/blob/master/web/client/translations/data.en-US.json#L213-L214

**Comment by ElenaGallo** [comment]
@MuhweziDeo missing tooltips for MAP TEMPLATE and USER SESSIONS button on contexts.

![ff](https://user-images.githubusercontent.com/56537133/125049771-9c34e200-e0a1-11eb-8f9a-d62936cd9f94.png)


**How to Reproduce**
- Open [this context](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/6846)
- Click on Buerger Menu

**Comment by ElenaGallo** [comment]
Closed in favor of #7091
