### ISSUE TITLE
MapStore crashes when the JSON response from a GetFeatureInfo contains a property name with a dash

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/MapStore2#6853]
## Description
MapStore crashes if it receives a property name conainting a dash ("-") inside the JSON response to a GetFeatureInfo request.

## How to reproduce
[This layer](https://master.demo.geonode.org/layers/geonode_master_data:geonode:alberi) on GeoNode master demo contains an attribute named "data-acquisizione"
- execute [this GFI request](https://master.demo.geonode.org/geoserver/ows?service=WMS&version=1.1.1&request=GetFeatureInfo&exceptions=application%2Fjson&id=geonode:alberi__4&layers=geonode:alberi&query_layers=geonode:alberi&styles=&x=51&y=51&height=101&width=101&srs=EPSG:3857&bbox=1389752.3702168849,5148380.807455325,1389872.9974021476,5148501.434640587&feature_count=10&info_format=application%2Fjson&ENV=&access_token=fGVTE4n5db10M5xJPY6mgj3tMSKLNc)  
- a JSON response (reported below) is generated correctly and is a valid JSON

JSON response
```json
{"type":"FeatureCollection","features":[{"type":"Feature","id":"alberi.1","geometry":{"type":"LineString","coordinates":[[1389681.90463728,5148381.10627049],[1389690.26473104,5148401.40965925],[1389705.19378795,5148416.93642519],[1389722.51176114,5148432.4617204],[1389742.21865059,5148446.19634689],[1389760.72996872,5148458.73719564],[1389813.87813808,5148432.1635837],[1389801.33820576,5148483.81894254],[1389855.97822007,5148458.43881217],[1389821.64176769,5148492.17854216],[1389862.24889154,5148500.5381491],[1389896.28705224,5148513.07906922],[1389926.74183853,5148522.03709311],[1389971.52900926,5148540.54857391],[1389998.99932,5148551.29733691],[1390021.6917982,5148555.62676554],[1390033.0374807,5148555.62676554],[1390054.833837,5148552.04384157],[1390062.59725829,5148548.46091895],[1390078.12298767,5148538.30906281],[1390095.73929709,5148526.067309]]},"geometry_name":"the_geom","properties":{"fid":1,"nome":"Alberatura lineare","descrizione":"Distribuzione degli alberi regolare frode alte","data-acquisizione":null}}],"totalFeatures":"unknown","numberReturned":1,"timeStamp":"2021-05-11T15:53:48.317Z","crs":{"type":"name","properties":{"name":"urn:ogc:def:crs:EPSG::3857"}}}
```

*Expected Result*
MapStore should be able to show the attribute "data-acquisizione"

*Current Result*
It crashes instead

![image](https://user-images.githubusercontent.com/571129/117848805-f1ac6880-b283-11eb-9704-dee67e5dc2e7.png)

```
gn-map.js:2 ReferenceError: acquisizione is not defined
    at eval (eval at <anonymous> (gn-map.js:2), <anonymous>:12:26)
    at gn-map.js:2
    at Array.map (<anonymous>)
    at TEMPLATE (gn-map.js:2)
    at ra (gn-map.js:2)
    at Ys (gn-map.js:2)
    at ou (gn-map.js:2)
    at ru (gn-map.js:2)
    at Ws (gn-map.js:2)
    at gn-map.js:2
    at t.unstable_runWithPriority (gn-map.js:2)
    at qo (gn-map.js:2)
    at Go (gn-map.js:2)
    at Bo (gn-map.js:2)
    at qs (gn-map.js:2)
    at Object.enqueueSetState (gn-map.js:2)
```

**Comment by MV88** [comment]
@QSafariallahkheili you can load this map locally and then trying to perform GFI requests with Alberi layer

also add the following line to proxyUrl.useCors array
"https://master.demo.geonode.org/geoserver"

try to click on this dotted line
![image](https://user-images.githubusercontent.com/11991428/120359011-7e889600-c307-11eb-827d-c22c4084394b.png)

and see why it fails

**Comment by offtherailz** [comment]
@giohappy We are going to fix the crash into a message error. Anyway you can use the syntax ${properties["something"]} and it should work

**Comment by giohappy** [comment]
>@giohappy We are going to fix the crash into a message error. Anyway you can use the syntax ${properties["something"]} and it should work

what do you mean? I'm reporting the default behaviour from the MapStore client, I'm not considering any special configuration.

**Comment by offtherailz** [comment]
I mean the correct sintax for a template system when you have a dash in the property name is `properties["name-with-dashes"]`.
I asked @MV88 to improve the suggestion to describe this use case and to handle the error and avoid crashes, and show an error message instead.
Anyway, you have to change the template to make it work.

**Comment by giohappy** [comment]
thx @offtherailz for the clarification. I'm going to open an issue for the geonode mapstore client to improve the template.
