### ISSUE TITLE
chart does not work when Catalog service url is a list of urls

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#6862]
## Description

You can have catalog service with multiple urls in a comma-separeted list
you can't add charts for this because it fails in creating WPS url

## How to reproduce

- open [this](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/34079) map
  - [optional a layer is already been added] open catalog
  - [optional a layer is already been added] select "comma-separated list" or add a service with url list like this `https://gs-stable.geo-solutions.it/geoserver/wms,https://gs-stable.geo-solutions.it/geoserver/wms`
  - [optional a layer is already been added] add a vector layer, like **gs:us_states**
- try to add a counter for this layer

*Expected Result*

it should be possible

*Current Result*

![image](https://user-images.githubusercontent.com/11991428/118123120-17f11600-b3f4-11eb-8db8-0ae0882a48de.png)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by MV88** [comment]
@ElenaGallo please test in DEV

**Comment by ElenaGallo** [comment]
@MV88 test done, you can backport this. Thank you
