### ISSUE TITLE
Identify Popup Issue

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6869]
## Description

There is a small regression on the Identify popup component where the pagination is active when it should not be (eg. reporting empty layer info). This regression involves only embedded maps.

## How to reproduce

-  To reproduce it is possible to use [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/10358). The GIF below explains the steps to reproduce. The embedded URL is [this](https://dev-mapstore.geosolutionsgroup.com/mapstore/embedded.html#/10358)

![gfi_bug](https://user-images.githubusercontent.com/1280027/118246264-09613800-b4a2-11eb-93b9-6ec4971c9e23.gif)

*Expected Result*

The Identify popup should reports Info pages only if they effectivelly exist for the clicked point and the pagination should work properly to allow browsing all existing layer info. 

*Current Result*

In embedded maps the Identify popup is reporting pages for layers where no info is present for the clicked point and the pagination dosn't properly work (eg. at a certain point it is blocked)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

In normal map like this the same tool works as expected. It is possible to activate it for example enabling the **Hover** mode in Option->Settigns for the Identify.

**Comment by tdipisa** [comment]
@QSafariallahkheili @MV88 I'm changing the milestone since the Identify popup has been enabled by default only in master branch (#6796) as part of 2021.02.00.

**Comment by ElenaGallo** [comment]
@MV88 sometimes in embedded map the popup is not displayed correctly

**How to Reproduce**
- Open [this embedded map](https://dev-mapstore.geosolutionsgroup.com/mapstore/embedded.html?forceDrawer=true#/10358)
- Click on the map where there is more than one layer

*Current Result*
![embedded](https://user-images.githubusercontent.com/56537133/125759269-e443e4f5-0e96-43fe-a4bd-7e5a082dd5ca.png)

**Comment by tdipisa** [comment]
@ElenaGallo please open an issue and mention this coment, then assign the issue to @MV88 for 2021.02.00

**Comment by ElenaGallo** [comment]
Closed in favor of #7104
