### ISSUE TITLE
The Tutorial tool conflicts with the details panel if it is opened at startup

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6871]
## Description

When both the Totorial and Details tools are active to be opened at startup, they conflict.

## How to reproduce

-  Open [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/34133)
- Switch in 3D mode (by default the Tutorial is configured to be automatically opened in this mode but the same configuration can be applied for the 2D mode as well)
- Navigate the Tutorial steps

*Expected Result*

Both tools should not conflict. The requested solution is to give the priority to the tutorial if present and active and open the Details panel (either in modal or side panel mode) right at the end of the tutorial.

*Current Result*

At a certain point of the tutorial both tools conflict.

![details_tutorial](https://user-images.githubusercontent.com/1280027/118249710-f6506700-b4a5-11eb-8559-88b385195aaf.gif)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by ElenaGallo** [comment]
Hi @QSafariallahkheili,
I found a small bug related to 3d mode and details popup:

- Once a new map is opened and 3d mode is activated or deactivated, the Details tool opens:
![3D-details11](https://user-images.githubusercontent.com/56537133/121539949-5d5e2e80-ca06-11eb-991e-255397e90175.gif)

**How to Reproduce**
- Open a New Map
- Click on 3D button

*Expected Result*
The detail tool does not have to open when 3D mode is activated/deactivated and the 3D tutorial is present when the user activates the 3D mode.

**Comment by MV88** [comment]
@QSafariallahkheili the problem is around here https://github.com/geosolutions-it/MapStore2/blob/82e267946e92bad2ef7162c1518d3a489fcf1e35/web/client/epics/details.js#L59
