### ISSUE TITLE
Remove floppy save icon

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/MapStore2#6879]
## Description
The style selection panel shows a save button (flobby icon) to update the local state when a style has been selected.
This additional click can be avoided. As soon as the user selects a style it should update the state, and the selection will be kept if the panel is closed, without the need of saving the selection.

As already discussed with @allyoucanmap I suggest to remove that button (action).

![image](https://user-images.githubusercontent.com/571129/118663865-52dabb80-b7f1-11eb-8004-2f066781515e.png)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features

**Comment by giohappy** [comment]
@tdipisa @allyoucanmap I've removed the "style selection" from the title since I think that this improvement shuould be more general. Saving the local state is something that the user shouldn't care about. It should be done transparently, as soon as something has been edited (even in the settings, the style editor, etc.).

I think this local save is something that makes a technical detail surface, but it clutters the UX without any benefit.

**Comment by joey2031** [comment]
So you just need someone to remove the icon, and action code that corresponds to it? If that's the case may I work on this issue please?

**Comment by tdipisa** [comment]
Hi @joey2031, you are welcome if you want to provide your contribution for this issue. Anyway it is not only a matter of removing the icon and the associated action. What we need here is to make the corresponding behavior transparent for the user: the persistence of this in the app state should be automatic without the user clicking on the button. If you are still interested I can ask to one of our team member to provide some hints if needed.

**Comment by giohappy** [comment]
@tdipisa can we plan the work for this issue?

**Comment by tdipisa** [comment]
@giohappy as you can see it is already planned. This morning I've assigned a resource and a milestone.
