### ISSUE TITLE
BG layers disabled in BG Selector tool for 3D

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6889]
## Description

All backgrounds in the Background Selector tool are disabled when switching to 3D mode with the exception of the empty one. As soon as you activate the empty background other backgrounds become active.

## How to reproduce

- It is possible to reproduce using [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/cesium/10358)

![3d_issue.gif](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/b6e8a12b-edbd-4464-9958-b4360dc5a7ef)

*Expected Result*

All background layers can be activated by the user

*Current Result*

All background layers are initially disabled when switching to 3D mode with the exception of the empty one.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by QSafariallahkheili** [comment]
> All backgrounds in the Background Selector tool are disabled when switching to 3D mode with the exception of the empty one. As soon as you activate the empty background other backgrounds become active.

I am reproducing this issue both locally (http://localhost:8081/?debug=true#/viewer/cesium/10358) and with the referred map  in the description (https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/cesium/10358).
It seems that all the basemaps are activated and can be added to the 3D map.
Could you please check it again?

**Comment by tdipisa** [comment]
@QSafariallahkheili the problem is still there as reported in the description of the issue. When you open the first time the map and switch to 3D mode, all backgrounds are disabled with the exception of the last one in the list (the empty backgrounds).

![image](https://user-images.githubusercontent.com/1280027/122189487-42217200-ce91-11eb-9ca6-d606223e89c0.png)

Then, if you click on the empty background and you expand again the list, all backgrounds become enabled.

**Comment by MV88** [comment]
@QSafariallahkheili 
the reason is because:
the checks for validity on layers are performed before the layers being registered in time and the background layers become invalid
https://github.com/geosolutions-it/MapStore2/blob/08048111f1ea1f182c8942a282e50b24918ab6d1/web/client/utils/cesium/Layers.js#L43
then if you toggle on/off visibility of a layer the check is done again, and they are enabled

**Comment by offtherailz** [comment]
correct @MV88 
I see MapPlugin calls an handler at the beginning and at the end of loading, but it is not used. `onLoadingMapPlugins`.
https://github.com/geosolutions-it/MapStore2/blob/3140a7b066a46bd4eccf01d419b9c28bb84517ae/web/client/plugins/Map.jsx#L431

I suggest bind this event to an action. (modify a little bit, I suggest to include the `mapType` in both calls and adding more info, like this:

```javascript
/**
 * Event triggered during 
 * @prop {string} maptype
 * @prop {boolean} loading true when the loading is active. False when the loading is finished.
 * @prop {boolean} loaded true if the plugin for the map type is effectively loaded. false or undefined if it is not loaded or there was some error loading
 * @prop {Error} error if valorized, contains the error occurred during the map plugin loading.
 */
export function mapPluginLoad(mapType, loading, loaded, error) {
    return {
        type: MAP_PLUGIN_LOAD,
        mapType,
        loading,
        loaded,
        error
    };
};
```
then intercept this events to update the layers

**Comment by MV88** [comment]
@offtherailz 
i agree 

We need to bind in the connect **onLoadingMapPlugins** to the new action **mapPluginLoad**
and we should use MAP_PLUGIN_LOAD inside maptype reducer where you set for each maptype the loaded status.
Then you can edit the background layers selector

```js
export const backgroundLayersSelector = createSelector(layersSelector, mapTypeSelector, mapTypeLoadedSelector (layers, maptype, isLoaded) => {
    const  backgroundLayers = layers.filter((l) => l && l.group === "background");
    return isLoaded ? backgroundLayers.map((l) => invalidateUnsupportedLayer(l, maptype)) || [] : backgroundLayers;
});
```
