### ISSUE TITLE
Cesium attribution covered in 3D

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6890]
## Description

Currently the Cesium attribution is covered when switching in 3D mode.

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/e581d2c3-1549-4817-8442-e412fd370d12)

It should be included in left side of the footer as it is in 2D mode.

## How to reproduce

-  Open a map and switch in 3D mode

*Expected Result*

The Cesium attribution is not covered by the Background Selector tool and it is reported in the footer instead, as it is in 2d mode.

*Current Result*

The Cesium attribution is covered by the Background Selector tool.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
This is probably caused by the changes in layout did in this PR.
https://github.com/geosolutions-it/MapStore2/pull/6872 
We need to understand if we can move up the tools without restoring the issue #6732, that the PR tried to fix.

Another solution. for consistency with what we do with leaflet and openlayers, we could move it in the footer (as for the other attributions), like this (I added a grey background because it was not readable, white over white.
![image](https://user-images.githubusercontent.com/1279510/118967505-1632cf80-b96b-11eb-8ecb-3e291d9548b9.png)

**Comment by tdipisa** [comment]
@offtherailz 
>Another solution. for consistency with what we do with leaflet and openlayers, we could move it in the footer (as for the other attributions), like this (I added a grey background because it was not readable, white over white.

Thank you for the screenshot, this is exactly what is required in the issue description.

**Comment by offtherailz** [comment]
sorry, I concentrated on the regression, because I missed the line below the screenshot in PR :facepalm:  I updated my comment with my suggestion.

**Comment by MV88** [comment]
@QSafariallahkheili 

I will give you some feedback here on how i would proceed:
- MapFooter is the plugin present within the viewer page ( the single map with /viewer in the url) for all three mapping libraries
- The attribution is pushed into MapFooter div, with some DOM manipulation, see for example leaflet https://github.com/geosolutions-it/MapStore2/blob/82e267946e92bad2ef7162c1518d3a489fcf1e35/web/client/components/map/leaflet/Map.jsx#L140-L145
- we need to do the same with Cesium Map component

and you have to pass from the configuration to the component where the attribution is present by adding this

```
"cesium": {
  "attribution": {
	"container": "#footer-attribution-container"
  }
},
```
here https://github.com/geosolutions-it/MapStore2/blob/82e267946e92bad2ef7162c1518d3a489fcf1e35/web/client/configs/localConfig.json#L286-L301

i noticed that the attribution in cesium JS is contained in this div
![image](https://user-images.githubusercontent.com/11991428/122008431-54c87800-cdb9-11eb-9760-34842c181449.png)

@offtherailz 
i'm not sure how to edit credits in cesium and to move them in a different container
i've found [this](https://cesium.com/learn/cesiumjs/ref-doc/Credit.html?classFilter=credit).
what do you think?
