### ISSUE TITLE
Illogical tab order

### ISSUE THREAD

**Issue by magnusnil** [geosolutions-it/MapStore2#6913]
## Description
When using tab to shift focus using the keyboard, the order in which the tools are activated doesn´t make sense. It starts top left with Layers, then moves to the lower right corner, then to the tools (such as the zoom button) and then back to home page. It should be in a more straight forward order, such as left to right.

Tested in Chrome and Microsoft Edge, using MapStore 2021.01.03.

**Comment by fkellner** [comment]
PR https://github.com/geosolutions-it/MapStore2/pull/9983 has fixed tab navigation within the layers. However, even if the TOC is hidden, the controls within it are still tabbable.

On the home page:
- Cards are not accessible via keyboard (will do a PR for grid cards fixing this this afternoon)
- Login-Button cannot be tabbed to

**Comment by fkellner** [comment]
Edit: Login button can be reached with `Arrow Down` once the menu is active
