### ISSUE TITLE
Update documentation about supported Java and Tomcat versions

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#6935]
## Description
Actually MapStore build process uses Java 8. 
Anyway the documentation tells to use java 8 only as a minimal version.

[Here](https://groups.google.com/g/mapstore-developers/c/CZ8tNJJY19A/m/6QhyxjCMAgAJ) a user notified a failure building with Java 16 (confirmed my me, @offtherailz) 
I did also a test of build with Java 13. The build is successful. 

We have to investigate the issue notified in Java 16 and define more the Java versions supported by MapStore, or fix the problem with Java 16, if possible. 

Also adding the information about the suggested tomcat version should be added

*Documentation section involved*
- [ ] User Guide
- [x] Developer Guide

**Comment by offtherailz** [comment]
We tested with @randomorder 
The version working on Ubuntu :
- tomcat 9.0.31
- JDK 11

**Comment by mbarto** [comment]
We should at least have: 
 - a list of tested JRE versions, that we know are working
 - a list of tested Tomcat versions, that we know are working and the related minimum required java version

To collect these lists we need to install various versions of JRE and tomcats and a set of smoke-tests for the backend functionalities:
 * geostore (home page resources load / modify)
 * security (login / logout)
 * datadir configs/ assets loading
 * extensions uploading

**Comment by offtherailz** [comment]
Just to reduce the list here a small summary of my thoughts


Starting from this table about Java Version Support  ([source](https://en.wikipedia.org/wiki/Java_version_history))

Java SE 7 | July 2011 | April 2015 | July 2022
Java SE 8 (LTS) | March 2014 | January 2019 for Oracle (commercial)December 2030 for Oracle (non-commercial)December 2030 for ZuluAt least May 2026 for AdoptOpenJDKAt least May 2026 for Amazon Corretto | December 2030
-- | -- | -- | --
Java SE 9 | September 2017 | March 2018 for OpenJDK | N/A
Java SE 10 | March 2018 | September 2018 for OpenJDK | N/A
Java SE 11 (LTS) | September 2018 | September 2027 for ZuluAt least October 2024 for AdoptOpenJDKAt least September 2027 for Amazon Corretto | September 2026,or September 2027 for Zulu,[8] e.g.
Java SE 12 | March 2019 | September 2019 for OpenJDK | N/A
Java SE 13 | September 2019 | March 2020 for OpenJDK | N/A
Java SE 14 | March 2020 | September 2020 for OpenJDK | N/A
Java SE 15 | September 2020 | March 2021 for OpenJDK, March 2023 for Zulu[8] | N/A
Java SE 16 | March 2021 | September 2021 for OpenJDK | N/A
Java SE 17 (LTS) | September 2021 | September 2030 for Zulu | TBA
Java SE 18 | March 2022 | September 2022 for OpenJDK | N/A

And this compatibility table for Tomcat ([source](http://tomcat.apache.org/whichversion.html))

Servlet Spec | JSP Spec | EL Spec | WebSocket Spec | Authentication (JASIC) Spec | Apache Tomcat Version | Latest Released Version | Supported Java Versions
-- | -- | -- | -- | -- | -- | -- | --
5.1 | TBD | TBD | TBD | TBD | 10.1.x | 10.1.0-M1 (alpha) | 8 and later
5.0 | 3.0 | 4.0 | 2.0 | 2.0 | 10.0.x | 10.0.7 | 8 and later
4.0 | 2.3 | 3.0 | 1.1 | 1.1 | 9.0.x | 9.0.48 | 8 and later
3.1 | 2.3 | 3.0 | 1.1 | 1.1 | 8.5.x | 8.5.68 | 7 and later
3.1 | 2.3 | 3.0 | 1.1 | N/A | 8.0.x (superseded) | 8.0.53 (superseded) | 7 and later
3.0 | 2.2 | 2.2 | 1.1 | N/A | 7.0.x | 7.0.109 | 6 and later(7 and later for WebSocket)

(7 and later for WebSocket)

I think we can take in account to support Java LTS versions (also Java 16 will be discontinued in updates the end of this year):
- 8
- 11
- 17 (probably not working)

And for tomcat 8, 9, 10.

This is only an opinion, what do you think ?

**Comment by mbarto** [comment]
@offtherailz agree with both. We can eventually try to understand which version JVM made changes incompatible with our current code and evaluate if the needed changes are trivial or not
