### ISSUE TITLE
Update style packages dependencies

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#6946]
## Description

It would be nice to update following libraries:
- update bootstrap to 3.3.7 the latest supported version of react-bootstrap. This update will help the geonode-mapstore integration
- and less language to 4.1.1 to support [map functionalities](https://lesscss.org/features/#maps-feature). This will help in the creation of for loop for theme variants

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features

**Comment by ElenaGallo** [comment]
@allyoucanmap there are some style problem:

- The **toc toolbar** and the **search layers bar** are moved up
![1](https://user-images.githubusercontent.com/56537133/121199415-33283780-c873-11eb-9048-cf4e959bafec.png)

- The color of the **family font** on visual editor is lighter
![2](https://user-images.githubusercontent.com/56537133/121200573-25bf7d00-c874-11eb-8edf-58fc34fb36bd.png)

- The **close button** in the save changes pop up and the **delete button** in delete pop up are moved up
![3](https://user-images.githubusercontent.com/56537133/121200603-29eb9a80-c874-11eb-90dd-95e4ce3e7ae8.png)
![4](https://user-images.githubusercontent.com/56537133/121200608-2b1cc780-c874-11eb-98f7-b551094d23ba.png)

**Comment by allyoucanmap** [comment]
@ElenaGallo thanks, I'll work on it

**Comment by dsuren1** [comment]
@allyoucanmap Looks like degrading `less` lib to 3.13.1 seems to work

**Comment by allyoucanmap** [comment]
@dsuren1 I would prefer to keep latest version of less, the issue is due to computation of variables not included in parentheses, working on it

**Comment by dsuren1** [comment]
@allyoucanmap  Yes that's right, but it's also affecting some styles (scss) from other libraries as well. I just came across one.
Ex. `NumberPicker` from  `react-widgets` 
![2021-06-08 20_22_44-MapStore HomePage](https://user-images.githubusercontent.com/26929983/121208008-5cf35580-c897-11eb-8280-862d2d1719fa.jpg)
We can just override those classes, however, not sure how many such similar libs have impacted.

**Comment by allyoucanmap** [comment]
@dsuren1 just checked and it seems react-widget is not included in the main theme but included directly in the components. The library has an issue with the computation of the buttons. Just tried to add it to the main theme with the overrides and it solve the issue:

```less
@import 'react-widgets/lib/less/react-widgets.less';
.rw-numberpicker {
    .rw-btn {
        height: (@input-height / 2);
        line-height: (@input-height / 2);
    }
}
```
![image](https://user-images.githubusercontent.com/19175505/121212224-6ff92c00-c87d-11eb-846e-32c3383b58a5.png)

I would like to use a version of less greater or equal than v3.5.0 to be able to use map functionalities for theming pourpose so I would prefer to fix the style
https://lesscss.org/features/#maps-feature

**Comment by offtherailz** [comment]
Save modal for maps stories etc... have some misalignments

dev: 
![image](https://user-images.githubusercontent.com/1279510/121214498-74264900-c87f-11eb-8a52-c79a20fb6043.png)

Original:
![image](https://user-images.githubusercontent.com/1279510/121214599-8d2efa00-c87f-11eb-9a67-3e3e361208a8.png)

**Comment by allyoucanmap** [comment]
@offtherailz thanks, solved
