### ISSUE TITLE
GeoStory shared URL sometimes becomes inconsistent

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#6970]
## Description

Opening GeoStory shared URL. e.g. the following: 

https://dev-mapstore.geosolutionsgroup.com/mapstore/#/geostory/shared/11555/section/7eca906c-5dae-431c-b313-80721d4af301/column/08b82a2d-057c-4a22-991d-92911b115d86

Sometimes, randomly, the URL is replaced by the application in this way:

https://dev-mapstore.geosolutionsgroup.com/mapstore/#/geostory/shared/11555/section/title_section_id1/column/b9b758ba-bf93-48f5-9bcd-92292e7d9858

`title_section_id1` is not correct, even the scroll is correct and it works anyway:

Other times I have this URL and the scroll position is not correct:
https://dev-mapstore.geosolutionsgroup.com/mapstore/#/geostory/shared/11555/section/title_section_id1

I think this is due to the scroll event on page load (the ID is referred to the first section) that has a race condition with the one coming from the URL. So it is probably 

## How to reproduce

-  Open a URL like this (https://dev-mapstore.geosolutionsgroup.com/mapstore/#/geostory/shared/11555/section/7eca906c-5dae-431c-b313-80721d4af301/column/08b82a2d-057c-4a22-991d-92911b115d86) - generically share the URL of geostory immersive section.

*Expected Result*
- The URL may change but should remain consistent with the current section/column visible on the screen.

*Current Result*
- Sometimes (randomply) the URL replaces the sectionID (`7eca906c-5dae-431c-b313-80721d4af301`) with the first section URL (`title_section_id1`)
- Other times I have this URL and the scroll position is not correct:
https://dev-mapstore.geosolutionsgroup.com/mapstore/#/geostory/shared/11555/section/title_section_id1
 
https://dev-mapstore.geosolutionsgroup.com/mapstore/#/geostory/shared/11555/section/title_section_id1/column/b9b758ba-bf93-48f5-9bcd-92292e7d9858

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

(Originally from this discussion) https://github.com/geosolutions-it/MapStore2/issues/6830#issuecomment-847708987

**Comment by tdipisa** [comment]
@offtherailz can you please investigate this?
