### ISSUE TITLE
Images are broken in online documentation for latest

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6974]
## Description

It seems all images are broken in opnline documentation for latest (master).

## How to reproduce

-  Open the latest user guide for example

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/fa413a88-9ecc-4526-a8f4-b6148ccd60e3)

*Expected Result*

Images should not be broken and available

*Current Result*

Images in documentation are broken

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by ElenaGallo** [comment]
@tdipisa locally I have no problems viewing the images and even adding a new image the problem is still present on RdT. I think the problem is related to the Read the Docs remote repository.

**Comment by tdipisa** [comment]
@ElenaGallo I found also another issue, see the GIF below.

![doc](https://user-images.githubusercontent.com/1280027/122028851-b514e500-cdcc-11eb-8df3-6c70c02f34c4.gif)

Please do a complete tour of the online documentation to see if there are also other broken links in the doc. then open an issue and fix them as part of 2021.01.04

**Comment by tdipisa** [comment]
@ElenaGallo, correct if I'm wrong, but it seems images are broken due to a wrong path used in the documentation. 

For example in doc we have:
https://mapstore.readthedocs.io/en/latest/img/button/remove-edit.jpg

While the correct one is:
https://mapstore.readthedocs.io/en/latest/user-guide/img/button/remove-edit.jpg

Did I miss something?
