### ISSUE TITLE
Theme switch mechanism/workflow for context pages

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#6987]
## Description

We should introduce a mechanism/workflow to associate a theme to a specific context

## Acceptance criteria

- [x] Switch theme based on the selected context
- [x] Associated theme could be a css url or a style block with css variables (css variable will ready soon)

**Comment by ElenaGallo** [comment]
@allyoucanmap The dark theme causes some display problems:

**1_** The LineDash on the Annotation style panel is not visible
![LineDash](https://user-images.githubusercontent.com/56537133/124151406-d0514700-da92-11eb-9b8e-a9234c70ec13.png)

*How to Reproduce*
- Open [this context](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/temadark)
- From the Options menu, click Annotations
- Open an Annotations
- Select a geometry
- Click on Style
- Click on LineDash


**2_** The tutorial popups are white
![tutorial](https://user-images.githubusercontent.com/56537133/124151424-d515fb00-da92-11eb-87ee-08d5004949ee.png)

*How to Reproduce*
- Open [this context](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/temadark)
- From the Options menu, click Tutorial
- Navigate the tutorial 

**3_** All the sidebar plugins are not present in the context even if they have been inserted in the list of enabled plugins
![sidebar](https://user-images.githubusercontent.com/56537133/124151486-e52dda80-da92-11eb-8c68-2793778f1731.png)

*How to Reproduce*
- Open [this context](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/temadark)

**Comment by tdipisa** [comment]
@ElenaGallo, have you already done extensive tests also to check all the other plugins?

**Comment by ElenaGallo** [comment]
Closed in fevore of #7051

**Comment by ElenaGallo** [comment]
Closed in favor of #7051
