### ISSUE TITLE
New context wizard page UI with theme selector

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#6988]
## Description

The context creation manager should add a new page to allow the user to select a theme from a list of available css.

## Acceptance criteria

- [ ] New page in the context creation process
- [ ] The page should allow the user to select a theme from a list of css themes

**Comment by tdipisa** [comment]
@MV88 it seems working really well in DEV. I only would like to review a bit the L&F by adding something like in the first step of the wizard (same text style and a corresponding simbology)

![2021_07_01_12_42_29_MapStore_HomePage](https://user-images.githubusercontent.com/1280027/124111716-e0a0fc00-da69-11eb-92b6-a6f688ef0f7b.png)
