### ISSUE TITLE
Add Custom theme form UI based on CSS properties to context theme page 

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#6989]
## Description

More complex form to allow the context editor to customize all theme variables through a form using colorpickers and save the theme in geostore. The theme resource will be fetched during the context loading

## Acceptance criteria

- [ ] Add ui component to select css properties to apply to the context theme
- [ ] Add script to create the root selector with css properties to apply to the edited context

**Comment by allyoucanmap** [comment]
The variables are described in this file [variables.less](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/themes/default/variables.less).

We could start to add 4 color pickers:
- main background->@ms-main-bg
- main color (text) -> @ms-main-color
- primary -> @ms-primary
- primary contrast -> @ms-primary-contrast

and compute all the variables that depends on these 4 colors.

Requirements:

- [ ] UI color picker with label
- [ ] A switch or similar to enable/disable the use of css variables
- [ ] Compute the css variable from the value of four pickers (We should decide if a selection level or at runtime in ContextTheme compoenent)

We have two options to compile the derived variables and we need to choose one:

- 1 using less in [programmatic usage](https://lesscss.org/usage/#programmatic-usage) and use the option [modifyVars](https://lesscss.org/usage/#less-options-modify-variables). **Pros**: we don't need a new computing method and we could use `.get-root-css-variables()` to write the classes. **Cons**: we need to verify if the less library increase the bundle size and find a way to import the variables.less file without duplicate it
- 2 compute the new variables in javascript with tynicolor (an example in [geonode-mapstore-client](https://github.com/GeoNode/geonode-mapstore-client/blob/master/geonode_mapstore_client/client/js/components/RootStyle/RootStyle.jsx)). **Pros**: tynicolor is already include so it will not increase the bundle size. **Cons**: we need to keep aligned the variables.less computation with the one inside our new javascript function

## Proposals css variables theme structure:

```json
{
    "id": "custom-variables",
    "type": "css-variables",
    "variables": {
        "ms-main-bg": "#ffffff",
        "ms-main-color": "#000000",
        "ms-primary": "#0000ff",
        "ms-primary-contrast": "#ffffff"
    }
}
```

**Comment by tdipisa** [comment]
@ElenaGallo let's collect our findings in a new issue. Mine are in #7162, please add yours there.
