### ISSUE TITLE
GeoCarousel section for GeoStory

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6993]
## Description

A new type of section for GeoStory will be available: the **GeoCarousel** section.
The aim of this new section is to enhance the user experience in using geostories by adding a different kind of section to browse map locations with an accompanying descriptive content.

A GeoCarousel section is a full screen section, like the [immersive](https://mapstore.readthedocs.io/en/latest/user-guide/immersive-section/) one currently available, that allows the story editor to define a list of items to be presented with a accompanying descriptive content (using text, media etc) and a geographic location.

## Acceptance criteria

1. In [editing mode](![image](https://user-images.githubusercontent.com/1280027/115413546-8e379980-a1f5-11eb-95af-2caa7de06054.png)) It will be possible to add the GeoCarousel section in the same way of other existing main sections: a new button will be added to the toolbar along with a dedicate icon to properly represent the section type (the icon to use will be defined by @allyoucanmap)

![image](https://user-images.githubusercontent.com/1280027/115413578-955ea780-a1f5-11eb-8dfc-fa362cbc0df4.png)

2. When the GeoCarousel section is added to the story (the user clicks on the related button in the above toolbar), the story will scroll to the new section that will cover the entire screen (as it is now for immersive sections)

3. In edit mode the GeoCarousel section will be composed by: a background with its editing toolbar, a descriptive (narrative) panel on top with its editing toolbar (the same column component of the immersive section), a carousel just below the background to list/manage items to be associated with a position in the map. The view mode will be basically the same but without editing toolbars

![2021_06_18_15_03_59_](https://user-images.githubusercontent.com/1280027/122567091-9884e100-d048-11eb-9e4c-ba2d8ce29b81.png)

4. **GeoCarousel background toolbar**: it provides the same functionalities/buttons of the [background toolbar](https://mapstore.readthedocs.io/en/latest/user-guide/title-section/#background) available for [immersive sections](https://mapstore.readthedocs.io/en/latest/user-guide/immersive-section/#background) in case of  a map selected for the background: **when the [media editor](https://mapstore.readthedocs.io/en/latest/user-guide/media-editor-window/) is opened for this section, it is possible to select only maps (the map tab is active and other tabs are disabled)**

![image](https://user-images.githubusercontent.com/1280027/122535126-893f6c80-d023-11eb-947e-2643b22485bf.png)

5. **Descriptive panel toolbar**:  it provides the same functionalities/buttons of the [columns contents](https://mapstore.readthedocs.io/en/latest/user-guide/title-section/#content) available in [immersive sections](https://mapstore.readthedocs.io/en/latest/user-guide/immersive-section/#content): the same component should be used.

![image](https://user-images.githubusercontent.com/1280027/122533962-61033e00-d022-11eb-936b-ab3a530128ee.png)

6. **Descriptive panel**: it is the same component available in [immersive section](https://mapstore.readthedocs.io/en/latest/user-guide/title-section/#content) but, for this section a fixed height must be set for this panel so that the scrollbar appears at a certain point: **the GeoCarousel section is not expected to have a variable height like for Immersive sections**. We have to set a proper height and make the Descriptive panel responsive depending on the screen.

7. In viewing mode the GeoCarouser and all editing controls (such as toolbars) disappear as usual and it is possible to browse the carousel items by scrolling with the mouse in the carousel section or using left/right arrows

![2021_06_18_15_21_18_Window](https://user-images.githubusercontent.com/1280027/122569557-2792f880-d04b-11eb-84e2-c34b8177950f.png)

8. In edit mode the GeoCarousel will allow to manage the following:

   - [ ] The map for the background by opening the media editor as usual
   - [ ] The contents (media or not) in the descriptive panel as usual
   - [ ] The position (left/right) and the size of the descriptive panel as usual
   - [ ] All other aspects connected to the involved toolbars for the background map and the descriptive panel (such as the theme etc.) 

9. Two buttons on the left side of the GeoCarousel will allow to:
      - [ ] Remove the GeoCarousel section from the story
      - [ ] Add new items to the carousel: when clicked a new box appears in the carousel with an empty thumbnail (see below). The box is selected automatically and the corresponding Descriptive panel will appear empty on the background so that the editor can start adding contents (texts and/or media) in it 

   Below are two proposals for the two buttons in the UI:

![image](https://user-images.githubusercontent.com/1280027/122536585-fb648100-d024-11eb-865a-3c172fc6eca7.png)

![image](https://user-images.githubusercontent.com/1280027/122536612-00c1cb80-d025-11eb-9f4c-19a3a341cb54.png)

10. For each item in the carousel a small toolbar allows the story editor to control actions like:

   - Edit the properties of the carousel item such as: **thumbnail**, **name**. If the usual modal of resource properties cannot be used, we can also opt for an inline editing of these two properties
      - The thumbnail, if specified, will be used to fill the item box      
      - The name, if specified, will appear just below, on top of or on the carousel item: let's see what looks better 
   - Define a location in map by adding a marker: a toggle button in the toolbar, if clicked, will activate the possibility to interact with the backgroung map to add a marker. In that case:
      -  The map is highlighted and the descriptive panel disappear, as it happens now when the Map Inline Editor is activated for a map in geostory, so that the user can interact only with the map until the position of the marker is fixed. The user can click on the map to add the marker and drag it to the effective position he wants. The story editor can click then an 'X' button somewhere to exit from the marker editing and the toggle button changes its state accordingly
      - When loading a GeoCarousel section the first time (both view and edit mode), each click on a item in the carousel will produce a zoom of the map to the related marker position (if defined). As soon as the user zoom or pan the map, further clicks on items in carousel will produce only a pan to the related marker **if it is not in view**
      - For this first implementation the marker symbol is always the same (the story editor cannot choose the marker type to be used). The marker type can be obviously configured in the plugin configuration (eg. in localConfig) with a dedicated property
      - The name of a carousel item (see above), if specified, will be automatically used for the retaled marker tooltip in the map to be visualized when the user hover the mouse over the marker
   - Delete the related carousel item (a confirmation dialog will be prompted)

11. It is possible to drag&drop items in the carousel to change their order in the list

12. Selecting a card item in the carousel (bot view and edit mode) the map can move/zoom to the related marker as specified above but also the descriptive panel changes accordingly by showing the content configured for the selected carousel item

13. As usual also for all the other sections types, a plus button in the mid-bottom side of the slideshow section allows to add other sections

![image](https://user-images.githubusercontent.com/1280027/115432110-4f5e0f80-a206-11eb-8c44-a00fdb1534c7.png)

## Other useful information

The responsivnes should be taken into account and better evaluated for mobile devices. The presentation could be the same of an immersive section. Users can tap on the descriptive panel to zoom the map to the marker and it is also possible to:

- Swipe left or right the descriptive panel to see other carousel items (the map is centered accordingly to the related marker)
- Hide the descriptive panel to show only the map as it is now for Immersive sections

![image](https://user-images.githubusercontent.com/1280027/122571643-3aa6c800-d04d-11eb-8840-68b81832e9fc.png)

**Comment by dsuren1** [comment]
**Needed as part of this issue**
1. Location on map is mandatory for a carousel item
2. Marker should be interactive. Clicking on marker should in turn select the respective item in the carousel window
3. Marker should be relatable to the carousel item ( i.e a number on marker and same in the card should be present)

**Needs to be estimated**
4. Ability to customize marker (Like annotation - UI to select marker style)
5. Arrow on descriptive panel (Include swipe for mobile) 

**Nice to have**
6. Ability to provide precise location coordinates  (Coordinates field or geocoder)

**Comment by tdipisa** [comment]
@dsuren1 let's have a quick call for these points so that you can do the requested evaluation:

>4. Ability to customize marker (Like annotation - UI to select marker style)
>5. Arrow on descriptive panel (Include swipe for mobile)

**Comment by tdipisa** [comment]
@dsuren1
I've created a new [dedicate issue](url) for the estimate of the point below
> 4. Ability to customize marker (Like annotation - UI to select marker style)

You can open an issue for the other point, that is already clear to you, and do the estimate there.
> 5. Arrow on descriptive panel (Include swipe for mobile)

**Comment by ElenaGallo** [comment]
@dsuren1 @tdipisa here some notes on the Goecarousel section:

1_ By adding a new item, the geostory scrolls down
![New items](https://user-images.githubusercontent.com/56537133/125814007-596b5bbd-9a41-4d8d-9c06-2d549466b4b7.gif)


**How to Reproduce**
- Open [this geostory](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/geostory/35029/section/35843410-e56b-11eb-9c88-67f0508f31e5)
- Click on + from the carousel toolbar

*Current Result* 
Adding a new item moves the section


2_ From View Mode, by selecting a GeoCarousel section from the navigation bar, you are not shown on the corresponding section

**How to Reproduce**
- Open [this geostory](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/geostory/35029/section/35843410-e56b-11eb-9c88-67f0508f31e5)
- Follow the gif below
![view sidebar](https://user-images.githubusercontent.com/56537133/125815142-ab50256b-41d9-417b-8796-9af30d488588.gif)

*Current Result* 
the geostory does not bring you back to the selected section

3_ From the sharing map, the markers are not present on the map

**How to Reproduce**
- Open [this geostory link](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/geostory/shared/35029)
- Go to the Geocarousel section

*Current Result*
The markers are not present on the map

4_ From the embedded map, clicking the marker on the map displays the gray error page
![gray](https://user-images.githubusercontent.com/56537133/125816480-bce89559-d670-42a1-ba34-9448d1be127b.gif)

**How to Reproduce**
- Open [this embedded geostory link](https://dev-mapstore.geosolutionsgroup.com/mapstore/geostory-embedded.html#/35029)
- Go to the Geocarousel section
- Click on the markers

*Current Result*
The gray error page appears

5_ From mobile, clicking the marker on the map displays the gray error page
![mobile](https://user-images.githubusercontent.com/56537133/125816576-cc46a358-78b0-48e8-b37e-e4569d8ccb80.gif)


**How to Reproduce**
- Open [this geostory](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/geostory/35029/section/35843410-e56b-11eb-9c88-67f0508f31e5) from mobile
- Go to the Geocarousel section
- Click on the markers

*Current Result*
The gray error page appears

**Comment by ElenaGallo** [comment]
@dsuren1 I found another problem in the embedded geostory:

* The layer present in the background map, on  GeoCarousel section, is not visible.

**How to Reproduce**

- Open the [embedded geostory](https://dev-mapstore.geosolutionsgroup.com/mapstore/geostory-embedded.html#/35059)

*Expected Result*

![1](https://user-images.githubusercontent.com/56537133/125914812-938d24e8-5412-4f9a-96c6-6ce42d6a2b32.png)

*Current Result*
![2](https://user-images.githubusercontent.com/56537133/125914833-38feb71a-078e-4294-8ee1-6043ba4d4e91.png)

Gostory link [here](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/geostory/35059/section/81b08b86-6474-41f7-b005-ac00fbf0858e/column/f81b176c-9ef4-4571-b334-47f5efcb384d)

**Comment by dsuren1** [comment]
> @dsuren1 I found another problem in the embedded geostory:
> 
> * The layer present in the background map, on  GeoCarousel section, is not visible.
> 
> **How to Reproduce**
> 
> * Open the [embedded geostory](https://dev-mapstore.geosolutionsgroup.com/mapstore/geostory-embedded.html#/35059)
> 
> _Expected Result_
> 
> ![1](https://user-images.githubusercontent.com/56537133/125914812-938d24e8-5412-4f9a-96c6-6ce42d6a2b32.png)
> 
> _Current Result_
> ![2](https://user-images.githubusercontent.com/56537133/125914833-38feb71a-078e-4294-8ee1-6043ba4d4e91.png)
> 
> Gostory link [here](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/geostory/35059/section/81b08b86-6474-41f7-b005-ac00fbf0858e/column/f81b176c-9ef4-4571-b334-47f5efcb384d)

I believe it has something to do with layer/style permission as geostory-embedded needs shared/accessible resource to work with.
As you can see here https://dev-mapstore.geosolutionsgroup.com/mapstore/geostory-embedded.html#/35120, this geostory displays layers properly, as it uses layer from _gs:us_states_ which is accessible. 
**_Note:_** You can see this behavior with existing sections as well, so I'm pretty sure this is not an issue and especially not an issue with carousel section. 
Hope it helps!

**Comment by tdipisa** [comment]
@ElenaGallo, that's true.

>I believe it has something to do with layer/style permission as geostory-embedded needs shared/accessible resource to work with.
As you can see here
https://dev-mapstore.geosolutionsgroup.com/mapstore/geostory-embedded.html#/35120,
https://dev-mapstore.geosolutionsgroup.com/mapstore/geostory-embedded.html#/34844, these geostory displays layers properly, as it uses layer from gs:us_states & topp:states_test which are accessible.
Note: Also you can see this behavior with existing sections as well, so I'm pretty sure this is not an issue and especially not an issue with carousel section.
Hope it helps!

**Comment by ElenaGallo** [comment]
@dsuren1 @allyoucanmap 

- [ ] On the embedded geostory and on mobile, the title popoup cover the marker.
See [this enbedded geostory](https://dev-mapstore.geosolutionsgroup.com/mapstore/geostory-embedded.html#/35185)
![11](https://user-images.githubusercontent.com/56537133/126801744-163aaa8c-155e-4b5c-94a2-5632cac7632e.png)

- [ ] The carousel map has a different bbox after it is saved with the marker

**How to reproduce**
Follow the gif below:
![22](https://user-images.githubusercontent.com/56537133/126801866-8816a4b7-7acc-42d4-a958-92e6c1d0debe.gif)

**Comment by tdipisa** [comment]
@ElenaGallo 
>On the embedded geostory and on mobile, the title popoup cover the marker. See this enbedded geostory

Please open a new issue for this with **Internal** label

>The carousel map has a different bbox after it is saved with the marker

This is a fetaure not a bug, the map is always zoomed to the selected marker.

**Comment by ElenaGallo** [comment]
Closed in favor of #7143
