### ISSUE TITLE
Update JDK/Tomcat

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#6998]
## Description
- [x] Update URL https://github.com/geosolutions-it/MapStore2/blob/master/release/pom.xml#L117 su bucket s3 (and check version) for release JDK/tomcat to jdk8/tomcat8
- [x] Use tomcat 8 for dev run, if possible https://github.com/geosolutions-it/MapStore2/blob/master/java/web/pom.xml#L14

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by tdipisa** [comment]
@offtherailz can we close this?

**Comment by offtherailz** [comment]
Second point is completed in another way (changed using `cargo`). About the first point, the URL still points on demo.geo-solutions.it so it is not completed. About using S3, I reported only what it was asked to be done. I think it is bacuese we should not rely on demo.geo-solutions.it for downloads. 
So for the first point, it is not done yet.

**Comment by randomorder** [comment]
> I think it is bacuese we should not rely on demo.geo-solutions.it for downloads

Definetly not. That machine will be decommissined

**Comment by tdipisa** [comment]
Thank you @offtherailz @randomorder so how can we schedule this? I would like to amend these things for the next release of MS.
