### ISSUE TITLE
Bar/Line chart not clear in case of multiple x values

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#7039]
## Description

Bar or Line charts with multiple values on x axis are not clear because all values are not properly represented.

## How to reproduce

-  It is possible to reproduce using [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/10358)
- and create Bar/Line chart widgets using the "State of US" layer
- using the following attributes/operation configuration

![2021_06_30_14_20_53_MapStore_HomePage.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/799e0ba8-df9d-467d-9bbf-c699e36d6a5e)

*Expected Result*

All x values should be represented someway in the chart when the user hovers the mouse over the chart itself

*Current Result*

For Bar charts we have the following:

![2021_06_30_14_18_44_MapStore_HomePage.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/6ec1d1a2-fdb0-4c1b-8e48-e5a757ea3ded)

where the value represented in the tooltip is related to the **Ohio** state as you can see openig the Attribute Table:

![2021_06_30_14_22_40_Window.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/6f2d49c6-bd7a-4fcf-b731-3e4663dfe107)

And for Line charts it is mostly the same:

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/decb16a4-32c0-4edf-b686-2fd6336302ce)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by ale-cristofori** [comment]
Closed in favour of #7731
