### ISSUE TITLE
Catalog loading spinner is fixed

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#7046]
## Description

The loading spinner of the catalòog tool is now fixed.

## How to reproduce

![catalog_loading_spinner.gif](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/3d796223-3359-44ae-9dcc-edc032b15913)

*Expected Result*

It should be like in QA

![catalog_loading_spinner_2.gif](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/770bb55b-2a2a-4c65-9b4b-02fb6a81fe67)

*Current Result*

It is fixed

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by ElenaGallo** [comment]
@allyoucanmap @tdipisa The same happens for the Get Feature Info spinner, see the follows gif:

**Comment by tdipisa** [comment]
@ElenaGallo 
>@allyoucanmap @tdipisa The same happens for the Get Feature Info spinner, see the follows gif:

I suppose that as soon as we fix the problem for one tool (eg. the Catalog), we fix contextually the same problem for all plugins. Isn't it @allyoucanmap?
