### ISSUE TITLE
Contrast in the box issue

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#7052]
## Description

On the dark theme, in the level settings, the Group, Tooltip and Position options the writings are not very visible (black) and when you click the box and the dropdown menu they are white (maybe there is too much contrast)

## How to reproduce

- Open a dark thema context
- Select a layer
- Click on Settings

*Current Result*

![3 1](https://user-images.githubusercontent.com/56537133/124295541-3f916e80-db59-11eb-9045-6e04e0b92eb0.png)

![3](https://user-images.githubusercontent.com/56537133/124295560-461fe600-db59-11eb-988e-21a955546175.png)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

Also in the catalog the dropdown menu of the search bar is white
![3 2](https://user-images.githubusercontent.com/56537133/124295980-c2b2c480-db59-11eb-9516-c0a31c74f4db.png)

**Comment by allyoucanmap** [comment]
> Also in the catalog the dropdown menu of the search bar is white
> ![3 2](https://user-images.githubusercontent.com/56537133/124295980-c2b2c480-db59-11eb-9516-c0a31c74f4db.png)

@tdipisa @ElenaGallo The dropdown generated from the attribute [autocomplete](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) of a text input is a native behaviour of the browser and cannot be styled
