### ISSUE TITLE
Background problem on setting panel

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#7053]
## Description

On dark thema, scrolling down the display panel, the background is white

## How to reproduce

- Open a dark thema context
- Select a layer
- Click on Settings > Display

*Current Result*

![4](https://user-images.githubusercontent.com/56537133/124296700-8cc21000-db5a-11eb-867a-c64859bb77df.png)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by ElenaGallo** [comment]
@allyoucanmap In the settings panel, the background of the legend is dark while the TOC is still white

![legend](https://user-images.githubusercontent.com/56537133/124784002-cd989b00-df45-11eb-9f62-5b1dff25101f.png)

**Comment by allyoucanmap** [comment]
Missing
- [ ] Improve toc legend background

from:

![image](https://user-images.githubusercontent.com/19175505/125918368-b874b225-1435-4810-a319-dfbe7de69dd5.png)

to:

![image](https://user-images.githubusercontent.com/19175505/125918299-81161a1a-554b-4d3b-89d9-9384e0dd79ac.png)
