### ISSUE TITLE
Tutorial is white

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#7058]
## Description

The tutorial popups are white

## How to reproduce

- Open [this context](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/temadark)
- From the Options menu, click Tutorial
- Navigate the tutorial 

*Current Result*

![tutorial](https://user-images.githubusercontent.com/56537133/124151424-d515fb00-da92-11eb-87ee-08d5004949ee.png)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by allyoucanmap** [comment]
@tdipisa as agreed we will keep the white tutorial popup for the moment the only fix we should add is to use the right contrast color on the primary button (the blue one should have dark text)
