### ISSUE TITLE
Domain Sharding in Catalog

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#7080]
## Description
Actually MapStore allows to set domain sharding for a WMS layer by adding an array for the URL, in the catalog. This is a little hard to understand (setting the URL of the catalog, comma separated, for configure alternative URLs is not immediate and documented).
In addition, configuring this way, the Format Options menu doesn't work anymore.

I suggest to move domain sharding in a separated option of the catalog advanced options (doesn't makes sense, for instance for CSW where the address of the catalog is not the address of the resource)

adding a list of alternative domains:

## How to reproduce
- Open the catalog
- Create a new catalog with the following URL: `https://gs-stable.geo-solutions.it/geoserver/wms,https://gs-stable.geo-solutions.it/geoserver/wms `
- Try to open format options

*Expected Result*
- I see the format options listed

*Current Result*
- I can not see the format option listed. 
- The other things works (because this is setting for format options).

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@alexander-fedorenko (but also @ElenaGallo and @MV88)
Multiple URLs previously reported in the same URL field (eg. see [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/10358), catalog "Comune di Firenze") are continue working anyway. Is this expected as backward compatibility?

In that case @ElenaGallo please ensure to put this detail in documentation.
