### ISSUE TITLE
More enhancements needed for Infobox

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#7083]
## Description

Some margins are not fully managed in the right way. 

1. In case of text wrapped around an image, the margin is needed for better readability (left and right)

![2021_07_08_13_08_40_MapStore_HomePage.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/1a3f3804-515d-4fd7-a46d-77f6bc68ac1f)

2. In case of titles (eg. H1, H2, H3 etc) the same margin should be applied too. 

![2021_07_08_13_05_26_MapStore_HomePage.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/6c762716-a20b-47d6-b9de-4c0066eeff50)

3. The header of the Detail panel is smaller than the one used for other panels:

![image](https://user-images.githubusercontent.com/1280027/124913456-6cc59d00-dfef-11eb-9991-e37d7d353a7f.png)

For example, for the Catalog tool we have the following:

![image](https://user-images.githubusercontent.com/1280027/124913623-a4344980-dfef-11eb-9566-e36a05ecf60a.png)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Other useful information
The screenshots above come from [this demo map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/10358)

**Comment by thottunkan** [comment]
{
margin-left : 100px;
}
