### ISSUE TITLE
Wrong group names in layer setting selector

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#7090]
## Description

There is a small regression involving group names in Layer Settings drop down: groups names are reported with the uuid instead of the real name.

![image](https://user-images.githubusercontent.com/1280027/125043848-a81da580-e09b-11eb-850a-f91318e59e80.png)

## How to reproduce

- Open a map with groups in TOC (eg. [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/10358))
- Open [Layer Settings ](https://mapstore.readthedocs.io/en/latest/user-guide/layer-settings/)
- Expand the group dropdown 

*Expected Result*

The group dropdown should report group names instead of the related uuid

*Current Result*

![wrong_groups.gif](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/57b9fea4-8f5e-40bd-a601-b54332c71d34)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

Maybe connected to #7037

**Comment by offtherailz** [comment]
A not complete solution is present in https://github.com/geosolutions-it/MapStore2/pull/7129#pullrequestreview-711513371 
(as from the review, the issue with localized group names that makes the application crash still exists)

**Comment by tonym3nsa** [comment]
@tdipisa The backend returns an array of objects. 
This is a sample:
```
{label: "Default", value: "Default"}
{label: "7d6a2230-9120-11ea-a97f-31058eec749a", 
value: "7d6a2230-9120-11ea-a97f-31058eec749a"}
```
Is this the expected behavior?
