### ISSUE TITLE
Enable the data dir on MapStore product

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#7102]
## Description
Now that the `/configs/` path contains all the configs, we can map this path to the current `/config/load` and make it a default, so locally you will continue to load localConfig, while in a prod context, when the `data-dir` is enabled, they are provided from the `data-dir` (or in cascade from webapp) supporting also the patch system.
This should be transparent with no more configuration needed, or explicit editing in `app.jsx`. 

## Acceptance criteria

- [x] If data dir is enabled `/configs/` directory should provide the files from data dir, or in cascade from webapp
- [x] The other services should work with the data dir or in cascade in the webapp (e.g. upload of extensions)
- [x] When data dir is set up, all the configuration files of back-end, must be loaded following the data dir specification, otherwise from webapp, or how it is configured
- [x] Generally speaking, if you set up a data dir, follow the data-dir specification, otherwise it should allow the original behavior, for backward compatibility
- [x] In documentation, we need to well define the configurations for data-dir and not, in a clear and compact way.
- [ ] Hopefully we can then remove from `localConfig.json` the references to `gs-stable` that can be applied to the production environment (#7165)
- [ ] #7176

## Other useful information

**Comment by tdipisa** [comment]
Remaining two issues in descriptions have been moved to 2021.02.01
