### ISSUE TITLE
Possibility of integrating Mapillary for street level view

### ISSUE THREAD

**Issue by aaj013** [geosolutions-it/MapStore2#7103]
## Description
What will be the possibility of integrating MapillaryJS with Mapstore? 
![Screenshot 2021-07-14 at 23-40-18 Mapillary](https://user-images.githubusercontent.com/5847582/125671770-13717273-7b02-43a0-aa24-188a69c9db62.png)

**Comment by tdipisa** [comment]
Dear @aaj013 it would be great if you can start a discussion in the [ML](https://github.com/geosolutions-it/MapStore2#communication) before. Thank you so much for your interest.
