### ISSUE TITLE
Custom project theme class not working anymore on projects

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#7118]
### steps to reproduce
- Creating a new project from master
- CustomizE theme following the documentation

The theme is doesn't work because the theme class is not applied. Editing the html manually adding to the main container the name of the project makes things work. Restore the application of custom project class.

Here reports also creating a project without changing the theme: 
https://groups.google.com/g/mapstore-developers/c/CXp-zGIzUwc/m/KMYwq4kzBQAJ?utm_medium=email&utm_source=footer

**Comment by offtherailz** [comment]
I tried (create a project and customize theme) and I can not reproduce anymore, too. 
The issue with the spaces in project name should be avoided, anyway it is unrelated with this issue, that I can not repoduce. 
Let's ask on ML how to repoduce the issue.

**Comment by MV88** [comment]
@offtherailz @tdipisa 
seems to be resolved during recent updates.
closing
