### ISSUE TITLE
Feature grid example does not work properly

### ISSUE THREAD

**Issue by Masoud-kamali** [geosolutions-it/MapStore2#7120]
Hello guys, I used feature grid example in localhost, but it has some issues. I did not change anything in file and only used webpack to run it.
the error is about searchUrl that the project needs to query WFS service.  The picture of error was attached there.

![1](https://user-images.githubusercontent.com/59616210/126120768-82c882e8-89c2-4ef0-8f9b-bff5c5ea9dbd.JPG)

**Comment by tdipisa** [comment]
Hi @Masoud-kamali this example is no longer supported and it will be removed from the wiki soon.
