### ISSUE TITLE
Allow to disable share tool in Maps, GeoStories, Featured Dashboards plugins

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#7126]
## Description

`shareToolEnabled` is not passed from the plugin to the GeoStories, Dashboards plugins. This doesn't allow to configure these plugins of the home page to hide the share button. 

See what reported and the suggested solution in this discussion on the mailing list: 
https://groups.google.com/g/mapstore-developers/c/yEtuCmsTPos/m/vw5g0o0GBAAJ?utm_medium=email&utm_source=footer

## Acceptance Criteria

- [ ] As an administrator I should be able to edit localConfig.json in --> maps section to manually set `shareToolEnabled` option of the "Maps", "Dashboards" and "GeoStories" and FeaturedMaps plugins. Setting it to false, I can remove the share plugin from the home page cards
- [ ] These option must be true by default, so the tool is enabled by default
- [ ] These options bust be documented for all the plugins involved.

**Comment by thga489** [comment]
salut
