### ISSUE TITLE
Arrows on GeoCarousel section

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#7142]
## Description

Introduce the left and right arrow to navigate the different slides in the GeoCarousel sections

## How to reproduce

-  Open a GeoStory
- Add GeoCarousel section
- Add map background
- Add new items

**Expected Result**
left and right arrow in the GeoCarousel sections
![ss](https://user-images.githubusercontent.com/56537133/126990569-27ab32ee-6fc0-45c8-a3c0-906f9616e8e2.png)

**Comment by dsuren1** [comment]
@tdipisa 
From the screenshot attached it looks the arrow keys are present on the whole carousel section (background), is it what is expected or should it be on the section content itself like in the example site
(https://sitmilano.maps.arcgis.com/apps/MapTour/index.html?appid=1061f64e268d4c3cb9887011e4cb4e53&webmap=a6423bc77c7e43189e4622ec7f07c9c7#map)
![2021-07-27 12_50_40-_Le vie dedicate alle donne_ and 1 more page - Profile 1 - Microsoft​ Edge](https://user-images.githubusercontent.com/26929983/127112686-e7f681f9-2f47-45d4-8124-e8220063af7e.jpg)

**Comment by tdipisa** [comment]
@dsuren1 
I confirm what reported above in order to always have the arrows in the same position regardless of the size and position of the descriptive panel. Therefore let's estimate this: just small arrows (only in desktop mode) in the available space on right/left (like [these](https://getbootstrap.com/docs/4.0/components/carousel/))

**Comment by tdipisa** [comment]
> @dsuren1
> I confirm what reported above in order to always have the arrows in the same position regardless of the size and position of the descriptive panel. Therefore let's estimate this: just small arrows (only in desktop mode) in the available space on right/left (like [these](https://getbootstrap.com/docs/4.0/components/carousel/))

@dsuren1 I'm sorry, I forgot to mention that we should include also a control using keyboard arrows. That should not be a big deal anyway.
