### ISSUE TITLE
Marker popup issue on mobile and embedded geostory

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#7143]
## Description

 On the embedded geostory and on mobile, the title popoup cover the marker.
![11](https://user-images.githubusercontent.com/56537133/126801744-163aaa8c-155e-4b5c-94a2-5632cac7632e.png)
## How to reproduce

-  See [this enbedded geostory](https://dev-mapstore.geosolutionsgroup.com/mapstore/geostory-embedded.html#/35185)
or
- Open [this geostory](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/geostory/35185) on mobile
- Slect GeoCarousel section
- Click a marker on map

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@dsuren1, as @allyoucanmap reported, this is probably depending on the mapping library used for embedded and mobile mode that is Leaflet.
