### ISSUE TITLE
Theme Selection Issues 

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#7162]
## Description

Quick test tour performed this morning using [this context](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/tob_test_theme)

- [x] Wrong state selecting the theme the first time

- Opened step 4 of the wizard
- Selected the dark theme and activated the switch for custom colors

![image](https://user-images.githubusercontent.com/1280027/127478959-9b9b9796-cb66-4a0b-8eb7-18be1c3b4516.png)

Doing the above steps, I'm expecting to have the colors of the Dark theme applied by default in the form as soon as I select the theme.

The result is the Dark theme as it is by default without the custom colors applied.

![image](https://user-images.githubusercontent.com/1280027/127479131-d1ea3169-1a30-4973-ba89-4a997451b7bc.png)

- [x] In some cases the X close button does not have the right color applied (Printing, Settings, Share, About, Measure, Search service, Configure bookmark dialogs)

![image](https://user-images.githubusercontent.com/1280027/127480005-b3c33e1a-1849-4e54-8315-9f1e4991da4d.png)

- [x] Is the share text area color for the share panel correct? Is it automatically calculated (white text and black BG)?

![image](https://user-images.githubusercontent.com/1280027/127480756-c8051710-a39a-4b27-be09-e42b256d3ca1.png)

- [x] When custom colors can be reset? I always see buttons disabled

![image](https://user-images.githubusercontent.com/1280027/127482043-0979d0cb-6c43-47d9-8668-10b1f3bee33c.png)

Test tour performed by @ElenaGallo using [this context](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/theme2). The theme colors are:
![ssss](https://user-images.githubusercontent.com/56537133/127500484-288d7da4-cbdb-40cb-94b6-296b950b7657.png)

- [x] On Annotations, the selected  LineDash becomes totally white on the dropdown menu
![2](https://user-images.githubusercontent.com/56537133/127497691-d4b50a26-7320-4510-8875-6b790594c1f8.gif)

- [x] On Counter Widget, the number is not visible in preview
![6](https://user-images.githubusercontent.com/56537133/127498750-701916b6-59f4-486c-bc8a-5128e6b635f7.png)

- [ ] It is not visible when, the Filter button by clicking on the map and the map synchronization button, in the attribute table, are active because they do not change color. 
![4si](https://user-images.githubusercontent.com/56537133/127497844-a24c36b2-968c-469d-8dab-57933cd907bf.gif)

- [ ] For all types of themes, in Annotations, the coordinate box changes color when adding Point, Text or Circle to the map
![3](https://user-images.githubusercontent.com/56537133/127498564-1ed0bfbb-a5b3-42ce-b974-c761098ff980.gif)

- [x]  For all types of themes, the download button is not visible  (or it is not the same color) on Print panel (the Primary Text Color is not is applied)
![1](https://user-images.githubusercontent.com/56537133/127497451-7fa0f5a3-3f7d-46ed-91d7-f2f616ca3957.png)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by MV88** [comment]
@ElenaGallo @tdipisa 
see my answers here, the rest is going to be fixed

>  Is the share text area color for the share panel correct? Is it automatically calculated (white text and black BG)?

changed to 

![image](https://user-images.githubusercontent.com/11991428/127535868-545cd174-aae8-4139-8d6f-b66030423da5.png)


>  For all types of themes, in Annotations, the coordinate box changes color when adding Point, Text or Circle to the map

this is because the danger color is configured to be red and when you have a background color red this is not fully visible
@tdipisa do we need to let customize also the danger color? we can discuss it with @allyoucanmap 

> it is not visible when, the Filter button by clicking on the map and the map synchronization button, in the attribute table, are active because they do not change color.

This is because you chose a primary color equal to the secondary color
there many combination of colors that are prone to error, honestly is very hard to prevent them all 
maybe we can improve the tooltips

i will push the fixes Friday late morning

**Comment by tdipisa** [comment]
@MV88 

>this is because the danger color is configured to be red and when you have a background color red this is not fully visible
@tdipisa do we need to let customize also the danger color? we can discuss it with @allyoucanmap

Yes, I think it is really important to have an automated check for this to recognize the opposite color to use or to let the user to choose it (the first option is really better for this). It is important to not compromise this kind of things when customizing a theme.

>This is because you chose a primary color equal to the secondary color there many combination of colors that are prone to error, honestly is very hard to prevent them all maybe we can improve the tooltips

Maybe we can simply introduce a validation check to prevent this possibility?
