### ISSUE TITLE
Enhancements to theme selection in context

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#7170]
## Description

This is a follow up from the discussion about this: 
https://github.com/geosolutions-it/MapStore2/issues/7162

A few enhancements will be needed:
- [x] Add in UI guidelines for the theme variables
- [x] Invert the validation check to be done in the text color of each type (main, primary, secondary)
- [x] Add validation check near secondary color between itself and the primary color
- [x] Add "buttons" in tooltip for text and primary color
- [x] Change tooltip for secondary text color to specify, "when secondary color is used as background"
- [x] the secondary color seems not applied correctly when using dark theme
- [x] the default value of secondary color should be coherent with the one used in the dark theme

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features

**Comment by ElenaGallo** [comment]
@tdipisa @MV88  there is a small text error:
* in English, Francais, Deutsch and Espanol translations, on the tooltip of the secondary color it says: "An alternative text color is .." but it is not a text

![text_color](https://user-images.githubusercontent.com/56537133/127837284-fa9dbf6b-e25a-4dd4-be72-9c616551b1a3.png)

* In Italian the tooltip itself is written half translated into Italian and half into English
![test it](https://user-images.githubusercontent.com/56537133/127837883-f84f54e1-2153-49a5-a384-9bda4219c777.png)

**Comment by tdipisa** [comment]
@ElenaGallo I think it is simply a matter of providing a small fix to the current translations. Can you take care of this please and raise a PR? Thank you.
