### ISSUE TITLE
Improve/add documentation: how to create a theme, how to customize it inside context

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#7175]
## Description

Add doc for: how to create a theme and how to customize it inside context

in the documentation there should be the specification that 
everything outside the proposed guidelines will not work proberly

*Documentation section involved*
- [ ] User Guide
- [x] Developer Guide

**Comment by tdipisa** [comment]
@MV88 @ElenaGallo please see comment [here](https://github.com/geosolutions-it/MapStore2/pull/7249#issuecomment-921644345)
