### ISSUE TITLE
Set up mapstore data-dir in docker.

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#7176]
Data dir is now enabled for product, so we can configure it in docker image

**Comment by randomorder** [comment]
Can you add instructions or a link to the doc please? @offtherailz

**Comment by tdipisa** [comment]
@offtherailz I suppose this need to be inclukded in 2021.02.00, right?

**Comment by offtherailz** [comment]
Hi, @randomorder, I updated the documentation of MapStore, but I noticed that automatic build has not been triggered automatically, as usual.
I triggered it manually.
https://mapstore.readthedocs.io/en/latest/developer-guide/externalized-configuration/#using-a-data-directory

Here the documentation. Let me know if you have any issues with this.

**Comment by sycured** [comment]
Pushed on specifc branch: [docker_data_dir](https://github.com/geosolutions-it/MapStore2/tree/docker_data_dir)

**Comment by offtherailz** [comment]
@randomorder LGTM

**Comment by randomorder** [comment]
PR is outdated, we'll provide an updated PR

**Comment by tdipisa** [comment]
@randomorder the new PR is this right?

**Comment by randomorder** [comment]
correct
