### ISSUE TITLE
Read the docs build seems not to be triggered automatically

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#7178]
## Description
- [x] Most recent automcatic readthedoc build is one month ago. Investigate on it
![image](https://user-images.githubusercontent.com/1279510/128014567-e887adba-b882-46c2-9795-c41ea0538300.png)

**Comment by offtherailz** [comment]
I refreshed webhook and updated the configuration. Lets' monitor future commits on master or on branches, to se if it resolves.

**Comment by tdipisa** [comment]
@ElenaGallo please take a look at his as per above comment

**Comment by offtherailz** [comment]
great !!!

**Comment by offtherailz** [comment]
I manually started the bilds for v2021.01.04 and 2021.01.xx to make sure they are aligned to latest, going to close this issue

**Comment by offtherailz** [comment]
Sorry, I read it wrong. :facepalm: Reopening

**Comment by offtherailz** [comment]
Anyway it seems to work. @ElenaGallo did you look at this project:

https://readthedocs.org/projects/mapstore/builds/
![image](https://user-images.githubusercontent.com/1279510/128321248-fd07ba76-a789-435d-bb90-a34b02eb9bbc.png)

**Comment by ElenaGallo** [comment]
@offtherailz mine is now aligned too, probably it had not built yet sorry.

**Comment by tdipisa** [comment]
@offtherailz @ElenaGallo can we close then?

**Comment by offtherailz** [comment]
@tdipisa The autobuild seems to be solved. RTD-Helper issue need to be invstigated (to understand if it is still running or have to be disabled or reconfigured)

**Comment by tdipisa** [comment]
@offtherailz thank you. Can you please open a new issue for the pending problem and close this issue in favor of the new one?

**Comment by offtherailz** [comment]
Here it is https://github.com/geosolutions-it/MapStore2/issues/7186, closing this one
