### ISSUE TITLE
npm install fails with npm > 7

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#7181]
## Description

Probably caused by these changes 
https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies

![image](https://user-images.githubusercontent.com/1279510/128142362-a132401c-08fb-42ac-8073-76afce999bd0.png)
## How to reproduce
-  use npm v > 7
- run `npm install`

*Expected Result*
Dependencies installed 

*Current Result*
Error in description

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by Gaetanbrl** [comment]
Link https://github.com/georchestra/mapstore2-georchestra/issues/396

**Comment by tonym3nsa** [comment]
Just a side note - this happens in NPM 7 because peer dependencies issues are treated as errors in v. 7 whereas they were only warnings in earlier NPM versions. Adding the flag `--legacy-peer-deps` makes it work in NPM 7.
