### ISSUE TITLE
Add support arrays in query form

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#7217]
## Description

Add support in Mapstore for creating filters for attributes that are array from queryform

## Acceptance criteria

- [ ] if the fieldType of an attribute is "array" it will handle the creation of proper cql and ogc filter
- [ ] cql filter will be like 

`InArray(VALUE,ATTRIBUTE_NAME)=true`

- [ ] the ogc filter will be
```
<ogc:PropertyIsEqualTo>
  <ogc:Function name="InArray">
     <ogc:Literal>VALUE</ogc:Literal>
     <ogc:PropertyName>ATTRIBUTE_NAME</ogc:PropertyName>
  </ogc:Function>
  <ogc:Literal>true</ogc:Literal>
</ogc:PropertyIsEqualTo>

```

## Other useful information

see [this](https://docs.google.com/document/d/1hGwlVuUrP31QZM2E1v2d37Gl9JwYbYtHUiHNth8yKmQ/edit?usp=sharing) doc for more info

**Comment by tdipisa** [comment]
@ElenaGallo we have already tested on c039 the specific enhancement. Please do in DEV just some regression test and let us know if we can proceed with the backport.
