### ISSUE TITLE
Plugins - Work with openLayers events

### ISSUE THREAD

**Issue by Gaetanbrl** [geosolutions-it/MapStore2#7218]
[⚠️ Issue maybe in the wrong category ]

**Hi,**

I try to trigger some map / layers OpenLayers events from a plugin.
In a first simple case, a plugin will juste force the WMS layer tile re render (redraw layer).

[REFRESH_LAYERS](https://github.com/geosolutions-it/MapStore2/blob/09e8d32e7a2c511adccc6516a7d17df66895d0f1/web/client/actions/layers.js#L218) action exists and refresh layer's source correctly, but layer's pictures tiles are not re render / up to date.

I'm not sur the `TileWMS` re render is possible because OpenLayers API have not entry about that.
https://openlayers.org/en/latest/apidoc/module-ol_source_TileWMS-TileWMS.html

Generally, if i want to trigger something on layer or map  from MapStore2, what is the best way to open an Openlayers event or create a new action with openLayers effect ? (same for leaflet i guess).

Thanks for help ! ;)

**Comment by tdipisa** [comment]
@Gaetanbrl thank you for reporting this. Can you please use the MS's usual mailing list for this kind of questions? Thank you very much.
