### ISSUE TITLE
The map coordinate system is not supported by this service

### ISSUE THREAD

**Issue by yazoury** [geosolutions-it/MapStore2#7225]
## Description
Getting the error message :
"The map coordinate system is not supported by this service" when trying to add new raster image from WMS though geoserver online service which I can access it online ..

## How to reproduce

-Open mapstorehome page after create new Map
-click on add new layer 
- Catalog is shown
-select type WMS then enter title 
-Then enter URL of service as https://XXXXr.XXXXXX.com/geoserver/wms?request=getCapabilities
-The click on save and then click on search and add click to map and that's happened with all layers.

*Expected Result*
it shows the message :
The map coordinate system is not supported by this service

*Current Result*
it shows the message :
The map coordinate system is not supported by this service

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by yazoury** [comment]
Any help

**Comment by tdipisa** [comment]
@yazoury thank you for reporting this. MapStore default CRS is 3857. Therefore, I can only suppose that probably this coordinate system is not currently supported by your GeoServer (eg. not configured): it is difficult to confirm this without having access to the WMS Capabilities. Please, use the mailing list for this by providing more information. Thank you so much.
