### ISSUE TITLE
Map catalog problems

### ISSUE THREAD

**Issue by matself** [geosolutions-it/MapStore2#7227]
## Description
In a new MapStore2 Tomcat9 instance, the sampled Geosolution catalogs cannot be accessed.
If I add a new Geoserver catalog, it does not get saved between sessions

## How to reproduce
ONE
Start Mapstore home page
Login as admin
Add a new map
Add layer
Select Geosolutions WMS
Hit Search
You get  'An error occurred while loading data'

TWO
Add new catalog
Enter http://geodatatorget.se:8080/geoserver/wms?
Hit Search
The default Geoserver stuff is listed, six pages.
Add any layer to the map and save it.
Close and reopen Mapstore
Repeat ONE above. The added catalog in TWO has disappeared
Open the saved map from TWO. The layer from my Geoserver is displayed correctly

*Expected Result*
Abililty to add Geosolution sample layers
Ability to save and keep other catalogs between sessions

*Current Result*
see above

- [x] Not browser related

## Other useful information
The URL:s to the Geosolution catalogs can be accessed and services consumed in QGIS without problem.
I am using the default h2 database.

**Comment by tdipisa** [comment]
@matself, thank you for reporting this.

>ONE
Start Mapstore home page
Login as admin
Add a new map
Add layer
Select Geosolutions WMS
Hit Search
You get 'An error occurred while loading data'

It is working fine for me (same conditions). Probably you have just experienced a networking issue. Did you check the browser cosole log (network section)? Please follow in the MS's usual mailing list for this.

>TWO
Add new catalog
Enter http://geodatatorget.se:8080/geoserver/wms?
Hit Search
The default Geoserver stuff is listed, six pages.
Add any layer to the map and save it.
Close and reopen Mapstore
Repeat ONE above. The added catalog in TWO has disappeared
Open the saved map from TWO. The layer from my Geoserver is displayed correctly

When you add a new catalog source from the UI and then you save the map, it will be available only in that map. If you want to customize the default list of catalog sources for all new maps, you have to do this in the configuration file (see [here](https://mapstore.readthedocs.io/en/latest/developer-guide/local-config/#catalog-tool-configuration))

**Comment by matself** [comment]
1: Change the URL to the demo server to https://demo.geo-solutions.it/geoserver... and it works.
2: Not very intuitive I must say. Perhaps the documentation needs to be improved.
On the other hand, I see an obvious need to be able to share data sources from a number of sources in a number of different maps. So I expected that sources once added would be accessible to all new maps on the same MapStore instance.
I see no way to cut and paste data sources across, or any way to copy and paste an entire map.
Both these functions could remedy the situation. I agree that sharing all sources for all new maps could lead to clutter, but that an orderly way of sharing selected resources would be a substantial improvement.
