### ISSUE TITLE
Mapstore printing error

### ISSUE THREAD

**Issue by abakostar** [geosolutions-it/MapStore2#7228]
I have this error in my configured Masptore version. To check if the error does not come from my version, I downloaded the .war from the official site and zipped printing module and when I deploy in my Tomcat 9.0 I still have the same error.
I am using Geoserver 2.19.0 and I do not know if the error comes from there but that would surprise me since the version that I am testing and without change compared to that of the official site just that I copy them to my file tomcat. Thanks for your help

My envrironnement is:
node 14 and npm 6.x
apache maven 3.8.2 and tomcat 9.0
openjdk 11.0.11
Geoserver 2.19.0

here is the error message below:

Error on printing: Error while generating PDF: org.mapfish.print.InvalidValueException: url has an invalid value: /${configDir}/print_header.png at org.mapfish.print.config.layout.ImageBlock.render(ImageBlock.java:87) at org.mapfish.print.PDFUtils.createCell(PDFUtils.java:631) at org.mapfish.print.PDFUtils.buildTable(PDFUtils.java:616) at org.mapfish.print.config.layout.ColumnsBlock$1.render(ColumnsBlock.java:58) at org.mapfish.print.PDFCustomBlocks.addAbsoluteDrawer(PDFCustomBlocks.java:183) at org.mapfish.print.config.layout.ColumnsBlock.render(ColumnsBlock.java:56) at org.mapfish.print.config.layout.Page.render(Page.java:80) at org.mapfish.print.config.layout.Layout.render(Layout.java:67) at org.mapfish.print.output.AbstractOutputFormat.doPrint(AbstractOutputFormat.java:30) at org.mapfish.print.output.PdfOutputFactory.print(PdfOutputFactory.java:62) at org.mapfish.print.MapPrinter.print(MapPrinter.java:184) at org.mapfish.print.servlet.MapPrinterServlet.doCreatePDFFile(MapPrinterServlet.java:409) at org.mapfish.print.servlet.MapPrinterServlet.createPDF(MapPrinterServlet.java:190) at org.mapfish.print.servlet.MapPrinterServlet.doPost(MapPrinterServlet.java:107) at javax.servlet.http.HttpServlet.service(HttpServlet.java:652) at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Unknown Source) Caused by: java.net.URISyntaxException: Illegal character in path at index 11: /C:/Program Files/Apache Software Foundation/Tomcat 9.0/webapps/mapstore/printing/print_header.png at java.net.URI$Parser.fail(Unknown Source) at java.net.URI$Parser.checkChars(Unknown Source) at java.net.URI$Parser.parseHierarchical(Unknown Source) at java.net.URI$Parser.parse(Unknown Source) at java.net.URI.<init>(Unknown Source) at org.mapfish.print.config.layout.ImageBlock.render(ImageBlock.java:85) ... 37 more

**Comment by tdipisa** [comment]
@abakostar thank you for reporting. Let's follow the discussion in ML [here](https://groups.google.com/d/msgid/mapstore-users/09bc2e32-a1ec-4133-bf72-1e813a632b60n%40googlegroups.com?utm_medium=email&utm_source=footer).
