### ISSUE TITLE
Feature info sometimes renders infinite loading spinner

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#7229]
## Description

This happens when all the Get Feature Info requests return "" 
and hover is not used and no loaded:true flag is returned

## How to reproduce

unfortunately this happened with a specific instance of a mapstore project because 
the proxy were returning empty string

*Expected Result*

to not have the infinite spinner

*Current Result*

infinite loading

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by MV88** [comment]
- [ ] In case all layers returns empty body let's add a dedicated message in the feature info panel

**Comment by ElenaGallo** [comment]
@MV88 on QA opening [this test map](https://qa-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/35736) displays the gray error page.

**Comment by MV88** [comment]
> @MV88 on QA opening [this test map](https://qa-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/35736) displays the gray error page.

the gray error was due to a [backport](https://github.com/geosolutions-it/MapStore2/pull/7305) that we have recently merged

you can test again now, be sure to toggle visibility of the two layers regioni italiane e linea costa in order to test initial use case
