### ISSUE TITLE
Problem with layer order at export

### ISSUE THREAD

**Issue by jusabatier** [geosolutions-it/MapStore2#7265]
## Description
I try to export a map context with layer folders and subfolders.
When reload the generated file, the folder/layer order change.

## How to reproduce
-  Create a tree of layers in the TOC (folder and subfolders with layers) : 
![image](https://user-images.githubusercontent.com/8310116/131802646-440f8cf0-72c4-4df4-a823-eee926427b53.png)
- Export this map with the MapExport plugin
- Clear the TOC (or refresh the page to remove loaded layers)
- Import the json previously generated context with the MapImport plugin
- At this point, the order of layers in the TOC is not the same as when we export the map : 
![image](https://user-images.githubusercontent.com/8310116/131803174-1e5082ae-23c6-45e2-9b25-b07aecbd336b.png)
=> "Autres prescription" is now before other layers.

*Expected Result*
The layers/folders order should be the same when exporting then reimport a map.

*Current Result*
The layers/folders order appear to sometimes be random.

- [x] Not browser related

**Comment by tdipisa** [comment]
@jusabatier thank you for reporting this.

**Comment by MV88** [comment]
@jusabatier can you share the exported json as reference?
thanks

**Comment by jusabatier** [comment]
Sure, here it is : https://gitlab.agglo-lepuyenvelay.fr/-/snippets/1023

**Comment by jusabatier** [comment]
Here is the good link: https://gitlab.agglo-lepuyenvelay.fr/-/snippets/1024

**Comment by alexander-fedorenko** [comment]
Here is the custom projection definitions that need to be added into web/client/configs/localConfig.json in order to allow import of maps in EPSG:2154 projection. This is required to reproduce problem with the configuration snippet provided above:

```
    "projectionDefs": [
      {
        "code": "EPSG:2154",
        "def": "+proj=lcc +lat_1=49 +lat_2=44 +lat_0=46.5 +lon_0=3 +x_0=700000 +y_0=6600000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs",
        "extent": [-378305.81, 6093283.21, 1212610.74, 7186901.68],
        "worldExtent": [-9.86, 41.15, 10.38, 51.56]
      }
    ],
```
