### ISSUE TITLE
Bump postgres jdbc to 42.2.23	

### ISSUE THREAD

**Issue by lpasquali** [geosolutions-it/MapStore2#7272]
## Description
At the moment with postgresql-8.4-702.jdbc3.jar MapStore2 is unable to connect to datastores running on posgtres13 because of postgres13 default new encryption default for password (they switched from MD5 to SCRAM-SHA-256 algorithm)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Other... Please describe: database compatibility

## Other useful information
Substitution without any MS rebuild of postgresql-8.4-702.jdbc3.jar with postgresql-42.2.23.jar resulted in the application being able to authenticate on posgtres13

Error of plain MapStore2 when trying to connectiong to postgres13 is

```
org.postgresql.util.PSQLException: The authentication type 10 is not
supported. Check that you have configured the pg_hba.conf file to
include the client's IP address or subnet, and that it is using an
authentication scheme supported by the driver. 
```

**Comment by tdipisa** [comment]
@lpasquali thank you for reporting this

**Comment by mbarto** [comment]
Postgresql driver is inherited from geostore. A PR to update geostore (master) to the required version is here:  https://github.com/geosolutions-it/geostore/pull/238

If needed, we can also update 1.7.x branch of geostore, by backporting the above PR

**Comment by tdipisa** [comment]
@mbarto thank you so much. We don't nee a backport to 1.7.x now for MS v2021.02.00. We will need to have that update in master to test it for 2021.03.00. @offtherailz please proceed with the review of the PR in geostore as soon as possible.

**Comment by tdipisa** [comment]
@mbarto PR GeoStore side merged [here](https://github.com/geosolutions-it/geostore/pull/238#issuecomment-920091256)

**Comment by mbarto** [comment]
@tdipisa mapstore will automatically use the new geostore build at the next deploy, no work needed here

**Comment by offtherailz** [comment]
Can the [fix in GeoStore](https://github.com/geosolutions-it/geostore/pull/238#issuecomment-920091256) be backported, then create a minor of GeoStore, then update it in MapStore stable?

**Comment by tdipisa** [comment]
@offtherailz no. It will land in 2022.01.00. MS downstream projects can use the new jar version independently in the meantime.

**Comment by lu-io** [comment]
Hello, 
I'm currently using version 2022.01.00 but I still have the same issue. In the new image there's the old postgres jdbc jar file. 
Is there a workaround? Can I just replace the old jar file with the new jdbc driver ( using same name ) to make it work?

Thanks!

**Comment by tdipisa** [comment]
@lu-io I've checked and for what I can see in the published war file there is the correct driver version. Can you please share more info about your installation? did you install MS with docker?

**Comment by lu-io** [comment]
@tdipisa I'm using the docker image from dockerhub geosolutionsit/mapstore2:2022.01.00

**Comment by tdipisa** [comment]
@lu-io we will check. thank you for reporting. In the meantime I think you can solve the issue by replacing the old jar with the expected new one.

**Comment by tdipisa** [comment]
@lu-io just to notify you that the issue you reported has been fixed few days ago. Thank you again.
