### ISSUE TITLE
[FeatureEditor] Allow to provide editable layers list

### ISSUE THREAD

**Issue by jusabatier** [geosolutions-it/MapStore2#7285]
## Description
Actually, when FeatureEditor is activated, it's for all context's layers.
It would be great to have an option like "editingAllowedLayers" listing layers that we want to enable edition for.
For example in a context some layers can just be there for information, not edition.
This feature allow them to not look like they can be edited.

## Acceptance criteria

- Allow to parameter layers in a context for which we want to enable feature edition tools. (not all)

**Comment by deepseainside75** [comment]
That would be a great feature for us as well. 
It would be an enabler for a lot of derived features from UI/UX perspective as well!

**Comment by jusabatier** [comment]
@tdipisa answers : 

> The context editor (who has write permission on the context) can control that option from layers settings of layers added in the context (step #2 of the wizard). The map editor (who has write permission on a map) can do the same at map level. If enabled, the Attribute Table (if present) will not appear in the toolbar when the layer is selected in TOC.

I didn't found such option that allow to set if a layer is available or not in edition.

**Comment by tdipisa** [comment]
@jusabatier this need to be implemented indeed.

**Comment by landryb** [comment]
> If enabled, the Attribute Table (if present) will not appear in the toolbar when the layer is selected in TOC.

@tdipisa  i suppose you meant "the edit button in the attribute table will not appear" right ? we still want users not allowed to edit the data in a given layer to be able to see its attribute table..

**Comment by tdipisa** [comment]
yes @landryb let me reformulate in the right way. I'm sorry.

>The context editor (who has write permission on the context) can control that option from layers settings of layers added in the context (step 2 of the wizard). The map editor (who has write permission on a map) can do the same at map level. If enabled and the Attribute Table is present, the edit button will not appear in the toolbar.

**Comment by dsuren1** [comment]
@tdipisa @offtherailz 
### Possible approaches
Kindly let me know which design to proceed with. Your thoughts @tdipisa 

**Option 1**
To have layer option under `Display` to enable/disable the layer for edit in Attribute table
<img width="397" alt="Screenshot 2023-05-16 at 2 20 06 PM" src="https://github.com/geosolutions-it/MapStore2/assets/26929983/ab31b05d-bcd4-43fd-aa6c-9a0c5c8991d9">



**Option 2**
To have a toolbar option under `Fields` 
<img width="397" alt="Screenshot 2023-05-16 at 2 20 06 PM" src="https://github.com/geosolutions-it/MapStore2/assets/26929983/4ac93b8c-d209-4c52-a87a-6f43b900b4e0">

**Comment by tdipisa** [comment]
@dsuren1 I would opt for **Option 1** but it should stay in _General_ and not in _Display_ tab. I'm not convinced about **Option 2** since this should be a general option to disable the layer editing while the Fields panel id dedicated to configure the aliases.
As far as the name of the option is concerned, it could be: _Disable editing with Attribute Table_ or something like that.

**Comment by tdipisa** [comment]
Closed in favor of #9180
