### ISSUE TITLE
loading too many extension crashes

### ISSUE THREAD

**Issue by isanchez-c2c** [geosolutions-it/MapStore2#7294]
## Description
On one of our georchestra platforms we need to load 4 different extensions wich leads mapstore to randomly either crash completely (even with contexts where no extensions are used), either randomly load some of the extensions and not the others (in that case in the console for the extension that didn't get loaded we get this error : "Error loading MapStore extension "<extension name>": TypeError: r[t] is undefined").
However, I tried to load a bunch of 10/11 SampleExtensions in an other instance, it makes the tab crash because it is too slow to load, but I don't get the TypeError.

## How to reproduce
[Our platform](https://georchestra.ac-corse.fr/mapstore/#/)

*Expected Result*

*Current Result*

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
I see the extensions failing because of some modules missing. 
Can I suggest to test your extensions with `npm run ext:start` and `npm run ext:startapp`, as described [here](https://github.com/geosolutions-it/MapStoreExtension#test-module). Most of the module reference issues can be found using this mode.

**Comment by offtherailz** [comment]
We recently discovered this issue. 
https://github.com/geosolutions-it/MapStoreExtension/issues/12
Can you try to change the "name" in "package.json" for each extension you are using and rebuild them. This should solve the problem

**Comment by jdugh** [comment]
Hi @offtherailz .
This solution seems to be great !
After change each name in package.json and rebuild and repost on georchestra platforms, there are no more errors.
Maybe an update of the https://github.com/geosolutions-it/MapStoreExtension/blob/master/README.md would be welcome ?
Thank's !

**Comment by offtherailz** [comment]
Great! 
I did the update this moring. https://github.com/geosolutions-it/MapStoreExtension/pull/13
Notice that @allyoucanmap is providing this fix that solves the problem without the needing to change the name in `package.json`: https://github.com/geosolutions-it/MapStore2/pull/7343 So for future extensions, this will not be needed this "workaround" anymore.
