### ISSUE TITLE
Printing Module proxied requests doesn't work with HTTPS.

### ISSUE THREAD

**Issue by drumbsd** [geosolutions-it/MapStore2#7298]
## Description
printUrl and createURL inside /pdf/info.json are always referring to http protocol, instead of https, even if Apache/Nginx are correctly configured (according to what is described in documentation). The only way to have the printing moduly properly working is to use AJP protocol.

## How to reproduce
* Build mapstore2 with "printing" module.
* Install in front of Mapstore2 a reverse proxy, like Apache or Nginx, and configure them as HTTPS termination. Refer to documentation provided [here]:(https://mapstore.readthedocs.io/en/latest/developer-guide/printing-module/#i-have-an-error-printing-using-reverse-proxyhttps)
* Trying to print a map. You see an error, and looking inside $URL/pdf/info.json you see that printUrl and createURL refers to http protocol.
*
*Expected Result*
printUrl and createUrl should correctly point to https protocol , as described in documentation.

*Current Result*
printUrl and createUrl point to http:// protocol instead of https://

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information
Only using AJP protocol, seems that we are able to have the printing module properly working. Maybe is the documentation that needs to be updated, or maybe there's something to fix in the code.

**Comment by tdipisa** [comment]
@drumbsd 
it seems working as expected in [DEV](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/10358).

info.json

![image](https://user-images.githubusercontent.com/1280027/133221529-2a5b32e3-bb83-42f0-95bc-9a79a22278b7.png)

create.json

![image](https://user-images.githubusercontent.com/1280027/133221776-c7d801f7-1b6f-44ba-af77-bf6e615e29a6.png)

**Comment by drumbsd** [comment]
DEV is using AJP and not HTTPS.

**Comment by mbarto** [comment]
@tdipisa @drumbsd mapfish-print builds urls in info.json using standard java discovery of the current Request (the info.json one). If the request is proxied and for any reason the underlying java/tomcat environment is not reporting it properly to the application (for example not recognizing the incoming request protocol) the only viable solution is to configure the proxy as explained here:

https://github.com/geosolutions-it/mapfish-print/issues/31

**Comment by tdipisa** [comment]
>geosolutions-it/mapfish-print#31

That is also reported in documentation [here](https://mapstore.readthedocs.io/en/latest/developer-guide/printing-module/#forcing-print_base_url-of-printing-module). Probably the issue above can be closed @randomorder

**Comment by randomorder** [comment]
thanks
let us know @drumbsd

**Comment by drumbsd** [comment]
Ok so PRINT_BASE_URL is a mandatory parameter? Because it's not still clear to me. In the documentation I read :"If, for any reason, you can not modify the proxy configuration.." seems like an alternative. But at this point , since that with just Apache/Nginx configuration it doesn't work, maybe is not an alternative but it's something that needs to be used in addition with the proxies directive.

**Comment by tdipisa** [comment]
@drumbsd 

I think the @mbarto comment above is explanatory:

>and for any reason the underlying java/tomcat environment is not reporting it properly to the application (for example not recognizing the incoming request protocol)

Therefore

>Ok so PRINT_BASE_URL is a mandatory parameter?

I don't think so since we are using AJP now and it is working also without PRINT_BASE_URL. Isn't it? Using a different setting than AJP, that property seems to be necessary in our case because the application is not able to retrieve the right protocol from tomcat, as far as I can understand from @mbarto

**Comment by offtherailz** [comment]
As I said here: 
https://github.com/geosolutions-it/MapStore2/pull/7295#issuecomment-918901154

We can simplify the configuration on MapStore by setting somehow PRINT_BASE_URL to `pdf`. 

Some solutions can be:
- Setting a default system property to `pdf`
- Passing the `pdf` as URL to the services (I noticed a long time ago inspecting mapfish code that this should be feasable).
- Customizing our MapFish print to allow to set/have this default.

**Comment by tdipisa** [comment]
@offtherailz please open a new issue for the above and assign it to 2021.02.01. Please mention this issue too. I think this one can be closed.
