### ISSUE TITLE
Is a simple text input expected for Layer filter attributes search?

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/MapStore2#7302]
A customer asked this question, since he expected to see a searchable dropdown as we have inside the Attribute filter box.

![image](https://user-images.githubusercontent.com/571129/133283237-709b981e-34e7-4703-b334-14ad3986ccf1.png)

**Comment by tdipisa** [comment]
@giohappy this has already been done with #2972 which will be available in the next major release 2021.02.00
