### ISSUE TITLE
Update Apache Tomcat to 8.5.69 (or greater) for QA

### ISSUE THREAD

**Issue by drumbsd** [geosolutions-it/MapStore2#7306]
As already did for DEV environments, we need to upgrade Tomcat version also for QA instance.

**Comment by tdipisa** [comment]
We can use the same tomcat version used for DEV for the moment.

**Comment by tdipisa** [comment]
@randomorder let me know when we can schedule this, please.

**Comment by randomorder** [comment]
done. Moving to Test

**Comment by tdipisa** [comment]
@randomorder thank you
