### ISSUE TITLE
Update Apache Tomcat to 8.5.69 (or greater) for RELEASE

### ISSUE THREAD

**Issue by drumbsd** [geosolutions-it/MapStore2#7307]
As already did for DEV environments, we need to upgrade Tomcat version also for RELEASE instance.

**Comment by tdipisa** [comment]
We can use the same tomcat version used for DEV for the moment @randomorder.

**Comment by tdipisa** [comment]
@randomorder let me know when we can schedule this, please.

**Comment by randomorder** [comment]
I am going to switch to the new Tomcat instance tomorrow morning at 09:30 @simboss @tdipisa . No significant downtime expected

**Comment by randomorder** [comment]
done

**Comment by tdipisa** [comment]
@randomorder thank you
