### ISSUE TITLE
Check if we can remove wofkflow for readthedocs

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#7321]
## Description
Integration of the webhook by readthedocs in MapStore settings seems to do the job originally provided by RTD-bot and then by https://github.com/geosolutions-it/MapStore2/blob/master/.github/workflows/readthedocs.yml. 
So we should check if remove the workflow, that changes only the text of the PR, and works only when the PR is done from a branch of MapStore directly.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes
- [ ] Other... Please describe:

**Comment by tdipisa** [comment]
Can you please provide a feedback on this @offtherailz. It can be probably closed, right?

**Comment by offtherailz** [comment]
Done here:
https://github.com/geosolutions-it/MapStore2/pull/7392 Probably the issue has not been connected in error. 

We can close.
