### ISSUE TITLE
Identify for annotations is showing all internal properties rather than title/description

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#7332]
## Description

The annotation is showing the default identify viewer with all the internal properties of the feature.

## How to reproduce

- open this map http://localhost:8081/embedded.html#/10358
- click on a annotation

*Expected Result*

-  the identify popup should show only the needed information without the editing buttons if the Annotation plugin is not included

![image](https://user-images.githubusercontent.com/19175505/133976246-afaa0706-4527-4d25-a0e6-ea4c1313e7b4.png)

default viewer in map:

![image](https://user-images.githubusercontent.com/19175505/133976441-14dc5a7e-4804-4bef-9724-a4204b6b2c66.png)

*Current Result*

- The annotation shows info such as visibility and id and the viewer is different from the one displayed in the default map viewer

![image](https://user-images.githubusercontent.com/19175505/133975403-5f61030c-bb1b-44f3-838e-2079d201ea94.png)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

It seems that the custom viewer for annotations is included only if the Annotations plugin is in localConfig in particular it needs to include the reducers and the [addAnnotationsLayerEpic](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/epics/annotations.js#L216-L251) epic

**Comment by allyoucanmap** [comment]
@tdipisa @giohappy Proposal:

- change the default properties response similar to the one presented by annotation to keep a UI consistency between responses

### before

![image](https://user-images.githubusercontent.com/19175505/134907357-00e0159b-c33a-4ac7-914d-a3235295ca4c.png)
![image](https://user-images.githubusercontent.com/19175505/134907760-ed2ca59e-ba05-436d-b628-a3a0d7ace12e.png)

### after

![image](https://user-images.githubusercontent.com/19175505/134907317-c8c78138-2bfd-4742-832f-39344f15de70.png)
![image](https://user-images.githubusercontent.com/19175505/134907724-91ff3513-2e43-428a-b553-6623cb24c8b1.png)

- add a layer property to include only a list of properties (eg includeInfoProperties: [ 'title', 'description' ])

**Comment by giohappy** [comment]
It's fine to me but I leave the final decision to the frontend team (@tdipisa)
