### ISSUE TITLE
Annotations plugin crashes the app if geometry step is skipped

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#7345]
## Description

Annotations plugin crashes the app if geometry step is skipped

## How to reproduce

- open a map and open annotations from burger menu
- add new annotation (plus button)
- add a title
- add a point annotation (marker plus button)
- deselect the point entry from the geometry list
- click on save

*Expected Result*

- prevent the application to crash

*Current Result*

- the application crashes

![image](https://user-images.githubusercontent.com/19175505/134347922-88da7b0b-7881-4e37-ac43-4bf49065f15a.png)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@MV88 it is not clear to me if this issue can be moved to test or not. @alexander-fedorenko did you finally fix this in one recent PR? Please confirm.

**Comment by alexander-fedorenko** [comment]
@tdipisa it can be safely closed. This issue is covered by fixes implemented with #7508 #7511
