### ISSUE TITLE
Main dependencies check

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#7349]
@offtherailz
As we have done with #7233 for branch 2021.02.xx, we have to do the same for master branch:

- [x] print-lib geosolutions-2.0-SNAPSHOT (nothing to do)
- [x] http-proxy 1.3-SNAPSHOT @offtherailz 
- [x] geostore 1.9-SNAPSHOT (#7829) @offtherailz 
- [x] mapstore-services 1.4-SNAPSHOT @offtherailz 

For 2022.01.00 we need:

- [x] print-lib geosolutions-2.0.1(nothing to do)
- [x] http-proxy 1.3.0 (to release) @taba90 
- [x] GeoStore 1.8.0 (nothing to do)
- [x] mapstore-services 1.3 (to release) @offtherailz

**Comment by tdipisa** [comment]
Hi @Mauro 
The next major release of MapStore is currently scheduled for mid March. If you have changes/upades to provide for mapfish-print, I think it would be good to agree now on how to release them as part of a new geosolutions version of the library. Now we are using this: https://github.com/geosolutions-it/mapfish-print/tree/geosolutions-2.0.x

Do you have updates for this? I'm asking because I haven't seen yet a PR on mapfish-print and I see all issues still in progress in the kanban. Will you be able to deliver them all in time to allow testing in master for the major release? We have also to establish what should be the new geosolutions version of mapsfish-print lib.

I'm available to have a quick chat with you to discuss/agree on this.

**Comment by tdipisa** [comment]
@taba90 we need you to release some dependencies for 2022.01.00 (see description). We need these new releases done and available in mvn repo by tomorrow.

**Comment by taba90** [comment]
@tdipisa @offtherailz:
http-proxy 1.3.0 has been released.
According to our call the 1.9.0 release for geostore is no more needed, I've restored the version of master branch back to 1.9-SNAPSHOT.

**Comment by tdipisa** [comment]
Thank you @taba90

**Comment by offtherailz** [comment]
This doesn't need any test from @ElenaGallo . JFI
