### ISSUE TITLE
Document how to add GeoPackage format to layer wps downlaod default configuration

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#7350]
## Description

We should add documentation on how to add the GeoPackage format to layer wps download default configuration. (LayerDownload plugin)

```js
{"name": "application/geopackage+sqlite3", "label": "GeoPackage", "type": "vector", "validServices": ["wps"]},
{"name": "application/geopackage+sqlite3", "label": "GeoPackage", "type": "raster", "validServices": ["wps"]}
```
This documentation should include also what's needed GeoServer side

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features

**Comment by tdipisa** [comment]
Please correct me if I'm wrong but, as far as I know, the geopackage extension is non part of GeoServer by default. Therefore, having that configuration in MS by default is not good. Document that in the plugin configuration, yes.

**Comment by allyoucanmap** [comment]
@tdipisa updated as documentation issue
