### ISSUE TITLE
User logs out after 5 minutes of work (on session refresh)

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#7371]
## Description
On dev a user logged on MapStore is disconnected after the first token refresh happens (evey 5 minutes)

## How to reproduce
-  Login to mapstore
- Wait 5 minutes (or wait in dev tools the refersh request is performed, every 300s = 5min)
- Refresh the page

*Expected Result*
- You are still connected

*Current Result*
The user has been disconnected

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

From a first inspection, it seems like the token is invalidated with the refresh, because the request to `user/details` that is done by MapStore on frist load (or refresh) to check if the session is still on fails.

Anyway I can not see the "Authentication: Bearer <token-id>" in the request to user deails, so some issue can be happened before

**Comment by tdipisa** [comment]
@offtherailz @ElenaGallo can you check please if also QA is affected?

**Comment by offtherailz** [comment]
QA from my checks seems not to be affected.

**Comment by ElenaGallo** [comment]
QA works as expected for me too
