### ISSUE TITLE
Minor improvements to the feature grid

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#7384]
## Description
I suggest improve the feature grid with the following options
- Allow to disable layer filter
- Allow to show checkboxes 
- Allow to enable multiple selection in view mode
- The options above can be activated programmatically, using actions
- *by default the behavior remains the same*

These changes provide the following advantages: 
- Possibility to control and configure feature grid for custom purposes
- Initial work for #6625 (providing decoupling between selection and filtering)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by tdipisa** [comment]
+1

**Comment by offtherailz** [comment]
this issue has no functional test.
