### ISSUE TITLE
Annotation plugin crash issue for empty geometry's value cases

### ISSUE THREAD

**Issue by sumithiverve** [geosolutions-it/MapStore2#7395]
## Description
- Annotation plugin crash issue for empty geometry's value cases

### Case 1: 
- For any geometry selection from annotation plugin, if we keep empty value then it get crash.
### Steps to reproduce:
1. Go to annotation plugin
2. Click on Plus icon button
3. Enter title value in textbox
4. Click on any item from geometries section at bottom.
5. Deselect added geometry.
6. Click on save icon on top to save annotation.
7. Click on created annotation
8. Select already created geometry
9. Click on "Add New Coordinate" button (Plus button)
10. Perform step 5 to 7 again.

https://user-images.githubusercontent.com/91316104/135570764-f8d8cddb-a064-422f-809f-563abbcea399.mp4

### Case 2: 
- Annotation plugin crashes when circle geometry has empty value
### Steps to reproduce:
1. Go to annotation plugin
2. Click on Plus icon button
3. Enter title value in textbox
4. Click on circle geometry from geometries section at bottom.
5. Deselect added geometry.
6. Select geometry again.

https://user-images.githubusercontent.com/91316104/135570675-e26fce42-be6d-47f5-aa91-7234bacd70e1.mp4

*Expected Result*
- Application should not crash

*Current Result*
- Application crashes

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by MV88** [comment]
@tdipisa
 in my opinion we should prevent the user to unselect features
 when they have an invalid state (like missing coordinates /center etc... )

for example avoiding step 5 in the first case
in this way we fix both problems

**Comment by tdipisa** [comment]
> @tdipisa in my opinion we should prevent the user to unselect features when they have an invalid state (like missing coordinates /center etc... )
> 
> for example avoiding step 5 in the first case in this way we fix both problems

It could be a solution. Generally speaking, introducing a further validation step that check the state to prevent the user to do certain actions like this.

**Comment by MV88** [comment]
@sumithiverve instead of blocking pint 5, we can block point 6
also if you notice the valid icon when you unselect is wrong

add also a tooltip on the save annotation button when one of the features is in an unconsistent state

**Comment by sumithiverve** [comment]
@MV88 
As per our discussion, I will follow bellow points for resolution of this issue:
So I will do bellow three things for resolve of issue (for invalid geometry case only) :
1. Disable save button
2. Set tooltip for save button  (tooltip text: "Saving is disabled due to one or more invalid geometries, please fix them to save the annotation")
3. Show invalid icon on geometry instead of valid icon.

**Comment by MV88** [comment]
@sumithiverve and me had a quick discussion regarding the trash button

@tdipisa when do you want to show this trash button ?
- always (invalid or valid) when the feature is not selected 
- always also when selected? (new behaviour)
- only when not selected and when it is valid
?

**Comment by sphingu** [comment]
@tdipisa Here is the screenshot for delete button UI if we change as per 1st point.
![image](https://user-images.githubusercontent.com/4688134/136185390-0241511b-1fba-42cf-9679-159306831ea0.png)

**Comment by tdipisa** [comment]
@arjuni84 ok thank you, that's clear now. Please proceed with the fix as already agreed with @MV88 We are looking forward to receive you PR for all problems depicted in this issue.

**Comment by alexander-fedorenko** [comment]
There's the case that makes app crash even before you save annotation. Invalidation of annotation based on existence of invalid geometry won't be enough in this case.

Steps to reproduce:
1. Create new annotation.
2. Create new geometry (e.g. "Line").
3. Add new coordinate. Keep it invalid.
4. Deselect geometry.
5. Try to create new geometry.

Video:

https://user-images.githubusercontent.com/4226620/140468610-e0a60b44-d86d-4b3c-b646-c74ddcfd0c11.mp4

**Comment by tdipisa** [comment]
@alexander-fedorenko thank you for the above. There are also additional things repoted [here](https://github.com/geosolutions-it/MapStore2/issues/7395#issuecomment-945618853). Therefore we can consider to open a new issue by reporting there all points in the description so that it can be more clear to tester what to check during testing. An additional possibility could be to open more separated issues if possible. Let's hear also from @MV88 about that.

**Comment by tdipisa** [comment]
@alexander-fedorenko @MV88 I think this issue can now be closed in favore of #7508
