### ISSUE TITLE
Add the possibility to copy WMS and WFS links to a layer from the catalog interface

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/MapStore2#742]
WMS and WFS get capabilities links are useful to share or use the layers in other applications, like QGIS for example.

Is possible to configure GeoServer CSW module to provide get capabilities links per layer:
```
references.scheme=list('OGC:WMS', 'OGC:WMS-1.3.0-http-get-capabilities', 'OGC:WFS-1.1.0-http-get-capabilities')
references.value=list(strConcat('${url.wms}?service=WMS&request=GetMap&layers=', prefixedName), Concatenate('http://localhost:8080/geoserver/', "store.workspace.name", '/', "name", '/wms?service=wms&version=1.3.0&request=GetCapabilities'), Concatenate('http://localhost:8080/geoserver/', "store.workspace.name", '/', "name", '/wfs?service=wfs&version=1.3.0&request=GetCapabilities'))
```

**Comment by offtherailz** [comment]
cool, we can recognize these entries in MapStore2 to provide links. I suggest a menu like "get Link" with the various recognized links and the possibility to copy it in the clipboard.

**Comment by nmco** [comment]
Humm I'm not sure to understand what you mean by "a menu like get links" I follow what wad defined in the mockups: https://www.dropbox.com/work/GeoSolutions/2016/NPA/MOCKUPS/v2?preview=04_catalog.png
