### ISSUE TITLE
User Guide - Layer Metadata tool 

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#7442]
## Description

Add a **Layer Metadata** tool on *Table of contents* section 

*Documentation section involved*
- [x] User Guide
- [ ] Developer Guide

## Other useful information
Related to https://github.com/geosolutions-it/MapStore2/issues/5090

**Comment by landryb** [comment]
As i'm struggling real hard to use this feature, it would be nice if the documentation would also explicitely list what's expected by mapstore in the wms getcapabilities urls, with formats etc. Trying with a CSW `GetRecordById` request fails here, as does with a new-style geonetwork API eg URLs `/geonetwork/srv/api/records/<uuid>/formatters/xml` which apparently is fetched as json (at least that's what the browser console says), and kills the browser ?
