### ISSUE TITLE
Style Editor filter tooltip suggests wrong wildcard for CSS styles

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#7444]
## Description

The suggested wildcard chart does not seem correct for the CSS style

original issue https://github.com/GeoNode/geonode-mapstore-client/issues/485

> @allyoucanmap  the tooltip in Filter Modals (css styles) suggests * as a wildcard character.
> 
> <img width="456" alt="Bildschirmfoto 2021-08-30 um 21 49 32" src="https://user-images.githubusercontent.com/20478652/131396778-5a8f05c4-4ade-4744-9713-c36a8dc9292a.png">
> 
> However, this is not working in my tests. What is working is **%** (like in SQL like) as explained in the geocss docs: https://docs.geoserver.org/stable/en/user/styling/css/filters.html#filtering-on-data-attributes
> 
> Is this a bug (and * should be explained as %)?

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Other... Please describe: Investigation

**Comment by alexander-fedorenko** [comment]
@allyoucanmap I've tested filter creation UI and can't confirm that % works as wildcard. Below is the screencast showing that * works as wildcard for "ilike" condition:

https://user-images.githubusercontent.com/4226620/150426128-05736421-66ac-4482-8fde-968289dc48ba.mp4

At the same time, underscore _ works as a regular character, it doesn't work as a wildcard for a single character.
Same rules work for filters in attributes table:

https://user-images.githubusercontent.com/4226620/150427683-47b22e73-0b50-4ced-a08a-e18641036634.mp4



@tdipisa Is it enough to update tooltip message for this case, keeping words about asterisk * as wildcard, but removing everything about underscore?

**Comment by tdipisa** [comment]
@allyoucanmap maybe I'm missing something but the above seems correct, can you please double check? Anyway @alexander-fedorenko, I'm just wondering what does this have to do with 'underscore'.

**Comment by allyoucanmap** [comment]
@tdipisa @alexander-fedorenko 
what's the encoding of the style in the video sld or geocss?
the issue reported was referring to a difference in the use of wildcards where in sld was working as explained by the tooltip while css not

**Comment by tdipisa** [comment]
@allyoucanmap oh right. I didn't test with CSS, I'm sorry, my fault. @alexander-fedorenko can you please check again?

**Comment by alexander-fedorenko** [comment]
@allyoucanmap @tdipisa thanks, I confirm that issue can be reproduced with CSS styles. I will provide an update for tooltip based on style encoding asap
