### ISSUE TITLE
Copy to clipboard plugin should give some visual feedback

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/MapStore2#745]
The user should have some visual feedback that something has been added to the clipboard.

**Comment by offtherailz** [comment]
It can be implemented manually using, for instance, tooltip overlays and so on. We can at least implement a more complex container that provides copy functionality + bootstraps overlay triggers on click and focus to provide some feedbacks.

**Comment by tdipisa** [comment]
closed for inactivity.
