### ISSUE TITLE
clean up the main product references to  server

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#7452]
## Description

For this task it can be good to merge together some work done here https://github.com/offtherailz/MapStore2/tree/mapstore_clean
- [ ] Remove references authkey to gs-stable (in the meantime prepare patches file to apply in the datadir)
- [ ] Investigate how mapstore product adapts if no catalog is available (map viewer, dashboard editor) and provide something as default. 
- [ ] Remove references to DEV REST services (dev server now points to dev-mapstore..., remove this dependency, use localhost:8080)
- [ ] Create a command to start both back-end and front-end for dev instance
- [ ] Update **documentation** about changes of product above
    - [ ] Migration guidelines?
    - [ ] dev doc
    - [ ] Update ReadMe.md
    - [ ] Update training?
    - [ ] Release procedure - remove parts concerning auth

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe: clean up

## Other useful information

**Comment by tdipisa** [comment]
Closed in favor of #7165
