### ISSUE TITLE
Allow to set maxLengthUrl from config

### ISSUE THREAD

**Issue by Gaetanbrl** [geosolutions-it/MapStore2#7470]
## Description

We use a plugin to filter some layers with many features ID.
But some getMap GET requests are too large and return :

```
Bad Message 431
reason: Request Header Fields Too Large
```

After dscussion with @tdipisa, a `maxLengthUrl` already exists to use a POST request instead of GET request.

https://github.com/geosolutions-it/MapStore2/blob/544ce327140a0d80969145c53fda5e2317c2f264/web/client/components/map/openlayers/plugins/WMSLayer.js#L46

So, we will contribute about that, but i need a feed back to propose a great improvement.

**1st solution**

I suggest to add a `maxLengthUrl` param for the TOC plugin (number) : 

```
      {
        "name": "TOC",
        "cfg": {
          "maxLengthUrl": 5000
        }
      }
```

If some usage needs a specific limit for each layer layer, we could set an object instead of number and defined a specific limit for each layers . But i'm not sur this config by layer is really usefull and a global number is more fast to config.

```
      {
        "name": "TOC",
        "cfg": {
         "maxLengthUrl": 5000,
          "maxLengthUrlByLayer": [
            {
              "id": "tabou2:iris_4",
              "size": 5000
            }
          ]
        }
      },
```

**2nd Solution**

We could use this param as plugin map param.

In your opinion, what is the best solution ? 

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features

## Other useful information

Link to :

* https://github.com/geosolutions-it/MapStore2/pull/6260
* https://github.com/georchestra/mapstore2-georchestra/issues/412

**Comment by offtherailz** [comment]
Sorry I missed this email. 
Yes, I suggest this.
