### ISSUE TITLE
The GeoCasousel section and the Paragraph section are not highlighted in the navigation toolbar

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#7474]
The GeoCasousel section is not highlighted by clicking on it in the navigation toolbar and sometimes it also happens for the Paragraph section with no text content.

![www](https://user-images.githubusercontent.com/56537133/140051972-976a1a4b-d8c5-40c9-aea4-22a533a40497.gif)

**How to Repeoduce**
- Open [this geostory](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/geostory/36690/section/955b08d1-522a-4393-be35-5fc5bbbf2044)
- Click on GeoCasousel section in the navigation toolbar or the first Paragraph section with no text content 

*Current Result*
The  GeoCasousel section and the Paragraph section are not highlighted

*Expected Result*
The  GeoCasousel section and the Paragraph section are always highlighted

**Comment by DavidQuartz** [comment]
I have solved the GeoCarousel issue, however the Paragraph issue needs some more investigation. @allyoucanmap @tdipisa

**Comment by tdipisa** [comment]
> I have fixed the GeoCarousel part of this issue, however the Paragraph issue needs some more investigation. @allyoucanmap @tdipisa

Please, explain better.

**Comment by allyoucanmap** [comment]
@tdipisa from an investigation did by @DavidQuartz we noticed that the nature of the issues related to GeoCarousel and Paragraph are not the same and for this reason I would suggest to split this in two issues.
In particular the issue related to the highlight of paragraph is something that happened in a different way in the past:

- https://github.com/geosolutions-it/MapStore2/issues/4848

The solution there were to change some threshold values for the visibility of contents that does not seems enough for this case (when the paragraph has small height). But if we restore the values to make the paragraph work we will introduce regressions for sure. In conclusion the way we are using to highlight the items in the navbar seems inconsistent and probably needs more time to be fixed properly.

**Comment by tdipisa** [comment]
As agreed with @allyoucanmap he will open a separated issue for the Paragraph problem and, more in general, for the enhancement of the navigation toolbar to make it more consistent in expected use cases.

@DavidQuartz, @allyoucanmap reported me that you found an additional issue here: the carousel secion item is not effectively selected in toolbar. Please provide this fix directly in the existing PR for this issue.

**Comment by allyoucanmap** [comment]
@tdipisa opened paragraph related issue here https://github.com/geosolutions-it/MapStore2/issues/7515
