### ISSUE TITLE
Name of element of the TOC should be editable only if supported

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#7487]
## Description

The name of an element for the TOC is always editable (WMS,WMTS, layer groups, groups in the TOC, WFS).
Anyway it is supported only for WMS layers.
## How to reproduce

1. case
- add a new group 
- edit its settings
current result: 
- The layer name is editable
expected: 
-  it doesn't make sense. It allows to edit the internal group name. 

2-3 case
- add a WMTS/WFS layer
- edit layer settings
- edit name 
- current result: 
- The layer name is editable
- If i try to edit and save, I have an infinite loading
expected: 
-  it should be disabled where not supported.

4. case
- add a annotation layers (adding annotations from annotations tool) 
- edit its settings
current result: 
- The layer name is editable
expected: 
-  it doesn't make sense. It allows to edit the internal name. 

*Current Result*

![image](https://user-images.githubusercontent.com/11991428/139434492-7f8fb678-b6e7-4721-9a33-84573343a080.png)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by ale-cristofori** [comment]
@tdipisa A fix has been applied to this bug. I suspect we would need to update the translations for new strings that were introduced as part of this bug resolution.

@MV88 @offtherailz Before proceeding could you please advise if the proposed fix is correct?

**Comment by offtherailz** [comment]
Guys, group name "ID" should not be shown at all, I think. Is an internal id, it doesn't make sense to make it editable. 
It makes sense only for WMS/WMTS/WFS ... Moreover it works only for WMS. 
So please show this tool only for WMS layers.

**Comment by offtherailz** [comment]
@ale-cristofori I've changed title and description of the issue. Now it is completely clear.
Please send a PR to fix it, thank you :+1:

**Comment by ale-cristofori** [comment]
> @ale-cristofori I've changed title and description of the issue. Now it should be completely clear. Please send a PR to fix it, thank you 👍

Ok will do
