### ISSUE TITLE
Sharing a web map not working correctly on mobile phone

### ISSUE THREAD

**Issue by magnusnil** [geosolutions-it/MapStore2#7504]
## Description
When I hit "Share" on my phone for a web map, not all of the tabs are shown and I can´t close the window. If I rotate the phone to gain horizontal space, I can´t scroll in the pop-up window, making the full QR code unavailable.

## How to reproduce

- Open at https://mapstore.geosolutionsgroup.com/mapstore/#/ on a phone. I used Firefox and Chrome on my Galaxy S9.
- Hit "Share" for a map
- Try to select the different tabs and close the window

*Expected Result*
All tabs shown, the cross for closing the window shown

*Current Result*
All tabs are not shown, the cross for closing the window is not shown

![Screenshot_20211105-101035_Firefox](https://user-images.githubusercontent.com/43540361/140487647-a5cb482d-911a-450c-9b11-544aaeb19d0f.jpg)

**Comment by ale-cristofori** [comment]
There is a PR open to fix the issue described here. I reduced the width of the modal in case the screen is <768px. I noticed though the modal isn't showing correctly when the screen is rotated horizontally 

see below (same screen size of Samsung Galaxy9) 740*360px

![image](https://user-images.githubusercontent.com/14953970/141147429-f7127277-14c9-4b3b-9a5b-af118ead53bc.png)

@tdipisa shall the fix of this be part of this ticket? estimate 0.5

**Comment by tdipisa** [comment]
>@tdipisa shall the fix of this be part of this ticket? estimate 0.5

yes, please proceed as we agreed in the call: let's try to have the scrolling in the modal when needed instead on the background.

**Comment by ale-cristofori** [comment]
The above fix was superseded by replacing the component that renders the share modal `Dialog` with `ResizableModal`. The latter provides responsiveness so that both header and content of the share modal window fit entirely within the screen of small devices, see below.

![recording_1](https://user-images.githubusercontent.com/14953970/141481210-f405f03e-1231-4db5-8227-3c7dd00432a6.gif)
