### ISSUE TITLE
Incorrect handling of wildcards in FilterLayer

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#7506]
## Description
like/ilike filters wildcards in filter panel are the same of Feature grid, that uses "*" as a wildcard (Passed to WFS). 
Anyway when the filter is used in filter layer plugin, the filter is converted to CQL_FILTER where the wildcard is "%". The converter transforms a filter like `"STATE_NAME" - "LIKE"  - "T*"` in `STATE_NAME "ILIKE '%T*%"` where * should be a %.

## How to reproduce
- Add to the map the gs:us_states layer. (us states)
-  Open filter panel
- Insert an attribute filter "STATE_NAME" - "LIKE"  - "T*"
- Apply the filter

*Expected Result*
I see on the map only "Texas" and "Tennessee" states

*Current Result*
I don't see any state.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
One thing. like / ilike now adds automatically the wildcard at the beginning and at the end of the search text.
I'm thinking if makes sense to avoid this when a wildcard is present in the string (that means the user wants to explicitly put the wildcards when he likes. 
This may help in case the user want to search "all the strings that starts with" or "all the strings that end with" and so on. 
@tdipisa what do you think?

**Comment by tdipisa** [comment]
>So if the user types `Tex` it will search for `*Tex*`, if types `Tex*` search for `Tex*`
@tdipisa what do you think? Maybe a separate issue for it.

Yes, and to discuss also.
