### ISSUE TITLE
Fix printing files default template path 

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#7507]
## Description
This path is wrong. 
https://github.com/geosolutions-it/MapStore2-C040/tree/master/backend/resources/printing

It should point to this file: 
https://github.com/geosolutions-it/MapStore2/blob/master/java/printing/resources/geoserver/print/config.yaml

## How to reproduce
-  Create a project with profile standard
- build the project with `./build.sh version printing`
- Install the war in tomcat and try printing functionalitiy

*Expected Result*
- The printing functionality is working

*Current Result*
- The printing functionality is not working (not tested effective behavior, @allyoucanmap if you want you  can integrate)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by alexander-fedorenko** [comment]
@offtherailz 
./build.sh master printing
Installed war in tomcat and it looks that everything works fine. Is there any specific case that fails? I've tried to print new map.

**Comment by offtherailz** [comment]
The problems happen when you create a new project (don't remember if with projectScript or `npx @mapstore/project create {project-type}` 
@allyoucanmap do you remember?

**Comment by offtherailz** [comment]
I asked to @allyoucanmap that originally found the problem.
It happened during the training, for this reason he reported in it the workaround for this issue:
[Here in the training](http://training.mapstore.geosolutionsgroup.com.s3-website-eu-west-1.amazonaws.com/project/introduction/index.html#include-print-module)

**Comment by alexander-fedorenko** [comment]
@offtherailz task description is still a bit confusing, it's not clear where should issue appear?
Following training section I was able to build and deploy war with printing activated and working (deployed not without issues, but that's probably out of this ticket scope).
Should it be possible to activate printing without manual actions with files and configs? What is desirable fix?

**Comment by offtherailz** [comment]
The training was not working because the copy of the file during the build was not pointing to the right file. 
The training was based on 2021.02.xx. 
Note that in the meanwhile master may have been changed and the problem can be fixed.
Can you try to build a project on  `2021.02.xx` branch too, and check the problem is still present on 2021.02.xx ?
If so, we may assume that recent changes to pom fixed the problem. 

Probabily the issue was due to some wrong path in pom.xml files when copying files from/to the paths indicated in the training.

**Comment by alexander-fedorenko** [comment]
Built project on 2021.02.xx branch, all looks good, printing works fine.
According to the git log recent change to the template of pom.xml is a part of this ticket #7687 
I believe that's the reason why this issue cannot be reproduced anymore.

**Comment by tdipisa** [comment]
@offtherailz can we close this then?

**Comment by tdipisa** [comment]
@offtherailz moving this to 2022.01.00. Please review it as soon as you can.

**Comment by offtherailz** [comment]
Ok, I see that this has been solved in 2021.02.02, going to close
