### ISSUE TITLE
Annotation plugin crash because of invalid geometry

### ISSUE THREAD

**Issue by alexander-fedorenko** [geosolutions-it/MapStore2#7508]
## Description
There is a set of use-cases that leads to app getting crashed while editing annotation.
All these cases are related to the invalid geometry (empty coordinates)

### Case 1: Attempt to edit annotation that was saved when it had invalid geometry.
1. Create new annotation or edit existing one. Specify title.
2. Create new geometry and add one point with empty coordinates, line or polygon.
3. Deselect geometry and save annotation.
4. Open annotation.

*Expected Result*
App opens toolbar to edit annotation

*Current Result*
App crashes

https://user-images.githubusercontent.com/4226620/140523658-6a6a47a5-dc41-4705-9b7f-e926665cfcb4.mp4

### Case 2: Attempt to create new geometry while geometry with empty coordinate exists in the list.
1. Create new annotation or edit existing one.
2. Create new geometry and add one point with empty coordinates, line or polygon.
3. Deselect geometry.
4. Try to create new geometry of any type.

*Expected Result*
App opens toolbar to edit geometry

*Current Result*
App crashes

https://user-images.githubusercontent.com/4226620/140523688-e0a5803b-5a4a-47f8-8f12-c815150573d7.mp4

### Case 3 Geometry is marked as incorrect while it's correct ([https://github.com/geosolutions-it/MapStore2/issues/7395#issuecomment-945618853](link)):

1. Go to annotation plugin
2. Click on Plus icon button
3. Enter title value in textbox
4. Click on line from geometries section at bottom.
5. Add 2 Coordinates for the line then Deselect that.
6. Add One more line geometry.
7. Deselect that.

Issue:
    Even if 2 Coordinates are given in the first geometry while selecting any other geometry it shows error sign.

https://user-images.githubusercontent.com/92375187/137712440-d6f1e578-e866-4b87-a2d7-f1526dc0d733.mp4

### Case 4 "Point" geometry is created unexpectedly on attempt to modify "Text" geometry coordinates
1. Go to annotation plugin
2. Create new or edit existing annotation.
3. Add "Text" geometry.
4. Click on the map to get coordinates pre-filled.
5. Remove value from one coordinate to make geometry invalid.
6. Click on the map somewhere.

*Expected Result*
Text geometry coordinates updated to the point clicked.

*Current Result*
New "Point" geometry is created and gets selected for editing. This geometry can't be removed and app will crash on attempt to edit point coordinated before text validation errors are resolved.
This issue needs to be resolved along with three previous because it break workflow where geometries can be added only using controls and it won't be possible to limit geometries editing if/when invalid one exists.

https://user-images.githubusercontent.com/4226620/141128519-d99f74cb-89d0-4511-be65-9337e59d6046.mp4

- [x] Not browser related

### Common issue for all cases: some coordinate in saved on non-saved annotation is array of two empty strings.
This bug report is successor of #7395 with all the issues collected in a single place

**Comment by alexander-fedorenko** [comment]
Eventually, I think that the only proper solution is to prevent invalid geometries from being saved via deselection, like suggested here: https://github.com/geosolutions-it/MapStore2/issues/7395#issuecomment-933316912

@tdipisa @MV88

**Comment by MV88** [comment]
@alexander-fedorenko 
I agree with myself of the past otherwise we have to add more logic in the codebase to handle invalid geometries 
and it's easier to prevent those situations

let's also add a point that validation check when editing an not are always aligned 
or better we can remove it from editing panel and leave it inside geometries items list with a tooltip 
having two validations icons that needs to be aligned and somehow are not complicates things

@tdipisa 
I suggest to proceed with this
> Eventually, I think that the only proper solution to resolve app crash is to prevent invalid geometries from being saved via deselection, like suggested here: https://github.com/geosolutions-it/MapStore2/issues/7395#issuecomment-933316912

@alexander-fedorenko @tdipisa 
let's also consider to update user guide once done the implementation

**Comment by MV88** [comment]
@alexander-fedorenko also let's split issue by moving case 3 and 4 to a new issue since these are new bugs not present in old issue

**Comment by alexander-fedorenko** [comment]
Issues previously listed as 3 and 4 are now in the separate issue #7511

**Comment by alexander-fedorenko** [comment]
@tdipisa @MV88 I've added steps to reproduce another issue I discovered while testing changes. It needs to be resolved along with first three because it breaks workflow of restricting to edit geometries if one of them is invalid. WIP.
