### ISSUE TITLE
 Annotation plugin - geometries become invisible when Marker or Text element is being added

### ISSUE THREAD

**Issue by alexander-fedorenko** [geosolutions-it/MapStore2#7511]
## Description
Geometries on the map become invisible when new Text or Point element is being added to the annotation.

### Case 1: Geometries become invisible while you create new marker or text.
1. Create new annotation or edit existing one.
2. Create new geometry, e.g. polygon or line.
3. Deselect geometry, check that it's visible on the map.
4. Create new point or text geometry.

*Expected Result*
All existing geometries displayed on the map while text or point is in edit mode.

*Current Result*
All annotation geometries become invisible.

https://user-images.githubusercontent.com/4226620/140523717-d8261a82-8738-4ab9-8da7-9ff92db9b074.mp4

### Case 2: Attempt to edit coordinates of any existing geometry ends up with an error if there is a marker or point with empty coordinate.
1. Create new annotation or edit existing one.
2. Create new geometry, e.g. polygon or line.
3. Deselect geometry, check that it's visible on the map.
4. Create new point or text geometry. Skip coordinates setup. 
5. Deselect geometry.
6. Select it again. Add coordinate but keep lat/lon empty and invalid.
7. Deselect geometry.
8. Select polygon and try to edit any coordinate with arrows at the right side of the input.

*Expected Result*
Polygon coordinates are updated.

*Current Result*
App crashes.

https://user-images.githubusercontent.com/4226620/140523753-0ee97461-4e78-48b6-bdfb-949dbc87b884.mp4

- [x] Not browser related

## Other useful information

None for now

**Comment by alexander-fedorenko** [comment]
This is regression bug introduced by #7393
Changes there is one-line fix and this fix can be safely reverted since after #7508 app will make sure that geometry coordinates are valid before giving user opportunity to save data.
It might need additional investigation to check if initializing Marker and Text with geometry = null is a proper way of doing things.

**Comment by thga489** [comment]
salut
