### ISSUE TITLE
Implement bearer authentication support for WMS GetMap requests

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#7516]
## Description

We want to add support for authentication through a bearer Authorization header in WMS GetMap requests (as needed by https://github.com/geosolutions-it/webmapper-halliburton/issues/2080).

Both ol and cesium WMS layer implementation will support this.

## Acceptance criteria

- [ ] WMS layers implementation for ol and Cesium will send the user access_token as a bearer Authorization header if configured through the localConfig authenticationRules with the bearer method

**Comment by offtherailz** [comment]
See this comment. @mbarto Probably the PR causes cross-origin requests where before were not needed. Please investigate.
https://github.com/geosolutions-it/MapStore2/pull/7518#issuecomment-966438590

**Comment by mbarto** [comment]
@offtherailz I should have fixed the issue with https://github.com/geosolutions-it/MapStore2/pull/7548
