### ISSUE TITLE
Set the visibility limits active by default on layers

### ISSUE THREAD

**Issue by dsuren1** [geosolutions-it/MapStore2#7565]
At the moment when you add a layer on the map, if you want to set the **visibility limits** using the data from the server you have to manually open the layer settings and click on **refresh** button. 

https://mapstore.readthedocs.io/en/latest/user-guide/layer-settings/#display

With this changes you can configure the catalog to automatically get from capabilities these information and set it on the layer on layer add. (check if possible together with same operation done when setting available formats (png/jpg ...) or if need to create a custom side effect).

Configuration is "cfg.autoSetVisibilityLimits"

I suggest to create a custom side effect that does this operation on layer add under the conditions of:
- The layer is supported (WMS only)
- The URL to query is know
- Catalog is configured to do so. 

**Ref**: https://github.com/georchestra/mapstore2-georchestra/issues/424
## Acceptance Criteria AC

- If I configured the option `autoSetVisibilityLimits` in `MetadataExplorer` plugin to true, and if I add a WMS layer that has some visibility hints on capabilities for its default style, this values have to be automatically applied to the layer, in the same way I do when I explicitly click on refresh button in Display tab of layer settings. 
- The options is available in advanced settings of WMS catalogs UI, as a checkbox
- If `autoSetVisibilityLimits` is false or not configured, the catalog should have the same current behavior. 

## Note for testers
on gs-stable, `gs:ny_poi` can be used for testing.

**Comment by offtherailz** [comment]
Please @dsuren1 change the issue to put a flag in the catalog settings of WMS type as you suggested, instead of a static cfg in plugin. It makes moer sense, and is a lot more practical and maintainable.
