### ISSUE TITLE
The X for closing more details panel of cookie tool is not visible

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#7566]
## How to reproduce

- open mapstore in incognito 
- click on more details of cookie tool
 
![image](https://user-images.githubusercontent.com/11991428/142192778-389883ee-bf67-4c86-b563-97d13aa79914.png)

- check in top right corner

*Expected Result*

to see the X

*Current Result*

i made it red to make you see where is the X, but now is not visible since has no color applied
![image](https://user-images.githubusercontent.com/11991428/142192509-e5bfcd5f-0511-41cf-9ecc-9e0ccccd36b3.png)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
```
