### ISSUE TITLE
Parsing of layer name from CSW

### ISSUE THREAD

**Issue by ale-cristofori** [geosolutions-it/MapStore2#7587]
## Description
The new specs for metadata cataloguing (RNDT / INSPIRE) for CSW do not enforce on the presence of  the attribute `name` on the `<dc:URI>` tag of the returned XML response
 
Such attribute was used by MapStore to trace back the associated WMS endpoint for the layer, since the attribute was normally formatted as `workspace:layer`.

This piece of information with the new specs has got to be found in the textual content of the element `dc:URI` containing the WMS url endopint for a layer, the parameters have to be extracted from this text and made available to the current code design in mapstore so that users can add the WMS layer to the map searching for its CSW counterpart.

## How to reproduce

-  Open a new map and in the catalog add a new CSW service.
- An example of a CSW service containing RNDT records is the following (must be accessed within VPN) `http://sr-vm107-sitgs1.comune.intranet:8080/geonetwork/srv/ita/csw`.
- Save service settings with `Show Preview` and `Show Metadata Template` in `Advanced Settings`, user must provide the customer defined metadata template.
- User clicks on the search button, returned records won't show the add '+' button on the top right corner of the record card.
- User expands the card component to show the extended information for the dataset on the metadata template. Links texts to download the source data (shp, kmz, etc.) are showing with the text `undefined`.

*Expected Result*
User clicks on the search button, returned records will show the add '+' button on the top right corner of the record card where WMS getMap request template is correctly returned from the CSW service. User expands the card component to show the extended information for the dataset on the metadata template. Links texts to download the source data (shp, kmz, etc.) are showing with the text `Title of the resource - download format`.

*Current Result*
User clicks on the search button, returned records won't show the add '+' button on the top right corner of the record card. User expands the card component to show the extended information for the dataset on the metadata template. Links texts to download the source data (shp, kmz, etc.) are showing with the text `undefined`.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information
This is issue was originally raised in an MS2 downstream project repo 
[This is the link to the original downstream project issue C0027 #72](https://github.com/geosolutions-it/MapStore2-C027/issues/72)

The fix for this issue must be backported to `master` `2021.01.xx` and `2021.02.xx`, there is already a fix for this issue 
[this is the PR for it](https://github.com/geosolutions-it/MapStore2/pull/7575)

This issue was created to keep track of the bug so that we can correctly backport the fix on the desired branches.

**Comment by offtherailz** [comment]
@ElenaGallo a metadata published by @etj is available at http://gn3-rndt.geo-solutions.it/geonetwork/srv/ita/csw (search for mapstore).
Anyway it is not availale with https. 
DevOps are going to rename it to http://gn3-rndt.geosolutionsgroup.com/geonetwork/srv/ita/csw (see this issue)

**Comment by etj** [comment]
DC xsl deployed.
Sample metadata here:

http://gn3-rndt.geo-solutions.it/geonetwork/srv/ita/csw?service=CSW&version=2.0.2&request=GetRecordById&outputschema=http://www.opengis.net/cat/csw/2.0.2&elementsetname=full&typenames=csw:Record&id=c_d612:947471bb-55d0-455a-99d3-2b4b654bfc85

**Comment by ale-cristofori** [comment]
> Please let us know the results. @ale-cristofori can you write if you need more metadata from that service to well test your feature.

Of course that would be indeed useful, I think @etj just provided a link, will soon test and let you know how it goes.

**Comment by ale-cristofori** [comment]
@etj  @ElenaGallo 
> Please let us know the results. @ale-cristofori can you write if you need more metadata from that service to well test your feature.

I tested with the above link and looks fine to me (see below)

![image](https://user-images.githubusercontent.com/14953970/143414102-50f716c7-18c8-42d4-84f8-7bc82de306be.png)

@offtherailz shall I proceed with the PR on [C027](https://github.com/geosolutions-it/MapStore2-C027)?

**Comment by offtherailz** [comment]
Yes, you can. I'll wait to close this issue until it is testable on dev/qa without workarounds, so @ElenaGallo can write a test for it.

**Comment by ale-cristofori** [comment]
This is the link to the PR for [C027](https://github.com/geosolutions-it/MapStore2-C027):

https://github.com/geosolutions-it/MapStore2-C027/pull/83/files

**Comment by lpasquali** [comment]
@offtherailz gn3-rndt ssl certificates are fixed so you could remove https://github.com/geosolutions-it/DevOps/issues/777 as a blocker if it works for you now

**Comment by offtherailz** [comment]
@ale-cristofori can you please provide the details about how to test this on dev instance (master) ?
I know I have to : 
- create a new map
- [ ] add a CSW catalog with this URL http://gn3-rndt.geo-solutions.it/geonetwork/srv/ita/csw but I don't know how to configure the metadata template (@ale-cristofori please indicate the template and where to set, for testers)
- save the catalog
- search for "mapstore"

Expected result: 
- one result is shown
- [ ] there is the possibility to add the layer (+ icon) --> here @etj the layer looks empty? is it ok?
- [ ] expanding you will see the URLs of various services as following (@ale-cristofori please explain)

**Comment by ale-cristofori** [comment]
> * @ale-cristofori please indicate the template and where to set, for testers)

@offtherailz this is an example of the metadata template used for testing locall
[metdata_template_CSW_comune_firenze.txt](https://github.com/geosolutions-it/MapStore2/files/7634940/metdata_template_CSW_comune_firenze.txt)
y


> * expanding you will see the URLs of various services as following (@ale-cristofori please explain)

These are the URL links to the WMS (if exists), to download the file in other formats (KML, shapefiles) if available. See image below


> @ale-cristofori can you please provide the details about how to test this on dev instance (master) ?

paste this URL:
http://gn3-rndt.geo-solutions.it/geonetwork/srv/ita/csw 
in the catalog.
 _N.B. on dev http requests are inhibited and you won't be able to access the CSW records, unless you know a workaround for this._

Using the metadata template provided above paste it in the text box that will appear when you select 'Advanced Settings -> Show Metadata Template'.

In the search bar type `test` so that you will be able to retrieve the record that @etj made for us to test `Metadato RNDT di test per MapStore`.

At this point, you will see both plus and expand button (the arrow). Expanding the metadata below with that button will open the filled metadata template with the links (highlighted in the image below).

Adding a layer with the add button (the plus sign) will result in the layer USA states being added to the map.

![RNDT metadata](https://user-images.githubusercontent.com/14953970/144261748-ba79a864-5e27-4e16-90fa-4be59db7313c.JPG)

**Comment by offtherailz** [comment]
@ElenaGallo please use the things above to test it.

**Comment by offtherailz** [comment]
@ElenaGallo I think this has been tested as for https://github.com/geosolutions-it/MapStore2/pull/7589#issuecomment-985532767 Isn't it?

**Comment by ElenaGallo** [comment]
yes, @offtherailz. Thanks for writing the comment
