### ISSUE TITLE
Print "Include scale in print" plugin

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#7595]
## Description

We want a subplugin for the Print plugin that:
 * shows the current printing scale
 * allows including the scale in the printed page, using a checkbox

Connected to geosolutions-it/mapfish-print#37

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by offtherailz** [comment]
@tdipisa this is not included by default as a panel in default print.
Is a separate plug-in, available but not included in the build. 
Should we include? 
I don't know if makes sense to make the print plugin to complex for the user as it's default implementation for testing.

**Comment by ElenaGallo** [comment]
@tdipisa I can not test the **Scale** plug-in on MS because it is not present in the  `plugins.js` file

**Comment by ElenaGallo** [comment]
Missing documentation and tests will be done with #8596
