### ISSUE TITLE
Metatiling usage for WMS layers

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#760]
Try to use metatiling by default (tiled=true) to improve performance / quality of maps

**Comment by offtherailz** [comment]
I'm working on layer properties style editor and it will be included soon. 
![image](https://cloud.githubusercontent.com/assets/1279510/17210689/97b048f0-54c4-11e6-81b6-564527760ba1.png)

Should this additional tool fit the requirement?

**Comment by simboss** [comment]
Does this kepp into account metatling parameters for GeoServer and integrate GeoWebCache? See [this](http://docs.geoserver.org/stable/en/user/geowebcache/using.html#direct-integration-with-geoserver-wms) and [this](http://docs.geoserver.org/latest/en/user/services/wms/vendor.html#tiled).

**Comment by offtherailz** [comment]
It takes into account only GeoWebCache `tiled` parameter. 
I see only now that tiled can be confused with the possibility to get single image vs tiled layer. Leaflet WMS do not support single tile layers, so it can not be implemented in this way. 

I could place a label on top of the 2 options to clarify it, like this : 

<hr/>
**WMS Parmeters**
- [ ] Tiled 
- [ ] Transparent

<hr/>
Or remove the tiled option and set it by default. IYO What is the best choice?

**Comment by simboss** [comment]
I'd go for tiled=true, which is a GeoServer vendor param by default for the moment. Other servers should simply ignore it.

This is horthogonal to what you are talking about for "Tiled" maps.
