### ISSUE TITLE
Documentation page not rendering correctly

### ISSUE THREAD

**Issue by tseggelidisf** [geosolutions-it/MapStore2#7612]
## Description
While reading the documentation i  noticed that the following url is not rendered properly.

https://mapstore.readthedocs.io/en/v2019.02.00/developer-guide/plugins-howto/mapstore-projects

Can you please check ?

Thanks in advance.

*Documentation section involved*
-  Developer Guide

**Comment by offtherailz** [comment]
You are looking for documentation of version `v2019.02.00`
The URL for that page is not correct (did you edited it by hand? )
The page of `MapStore project` section for that version was located here:
https://mapstore.readthedocs.io/en/v2019.02.00/developer-guide/mapstore-projects/
