### ISSUE TITLE
editingAllowedRoles are not catch anymore by feature grid

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#7649]
## Description
As from this email on mailing list:
[here](https://groups.google.com/g/mapstore-users/c/7rB_izIRo_4/m/DlX4vHlDCQAJ?utm_medium=email&utm_source=footer&pli=1)

## How to reproduce
-  Create a context with featuregrid configured as described in the mailing list
- login as normal user
- Verify if edit button is visible to the normal user

*Expected Result*
- It should be visible

*Current Result*
- It is not visible. 

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
@tdipisa the solution was quite easy, I already did a PR for that

**Comment by tdipisa** [comment]
@offtherailz thank you so much
