### ISSUE TITLE
Implement Test container for MapStore docker-compose stack

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/MapStore2#7654]
We would like to test MapStore docker images as part of our CI/CD pipelines. The idea is to complement the existing `docker-compose.override.yml` for MapStore with a `docker-compose.override.yml` definiing a "test" container.

This test container will have a dependency on mapstore to wait for complete mapstore startup and then make a set of test calls to MapStore endpoints (details below).

At the end of each docker image build, the pipeline will take care of spinning up the compose for mapstore with the newly created image as well as the testing container to test it and clean up the environment after the execution.

**The Pipeline**

The pipeline is to be implemented in the form of a Jenkins job on the [official build server](http://build.geosolutionsgroup.com/) and executed on a dedicated [Executor](https://www.jenkins.io/doc/book/glossary/) (not on the jenkins master)

To be executed at the end of a successful build of the mapstore docker image. See the [MapStore Dev Job](http://build.geosolutionsgroup.com/job/MapStore/job/MapStore2_Dev_Build/) for instance

**The Tests**

Dedicated docker container running a Python script to test MapStore endpoints. Dedicated PostgreSQL geostore database with preconfigured users and resources.

Mandatory tests:
As anonymous user, test access to resources:
- mapstore homepage
- map
- dashboard
- geostory
- thumbnail
- context
- datadir externalization

A s authenticated user (basic authentication) *:
- private map

Optional Tests
- users manager
- context manager
- embedded html for dashboards
- embedded html for geostory
- embedded html for maps

* we'll eventually need to configure mapstore to allow for basic auth

**Comment by tdipisa** [comment]
@randomorder @PabloBaronetti I've asked @MV88 to provide assistance on this to let you know the endpoints to test.

**Comment by MV88** [comment]
@randomorder 
a few clarifications

- [ ] **As anonymous user, test access to resources:** 
as anonymous users one can access public resources and it is fine, but he can also access to private resources
which use cases do you want to cover? only public? both?

- [ ] **what do you mean exactly by testing ?**
  - embedded html for dashboards
  - embedded html for geostory
  - embedded html for maps

  to test the url accessing those type of embedded urls?
like this one https://dev-mapstore.geosolutionsgroup.com/mapstore/embedded.html#/10358 ?

**Comment by randomorder** [comment]
> * [ ]  **As anonymous user, test access to resources:**
>   as anonymous users one can access public resources and it is fine, but he can also access to private resources
>   which use cases do you want to cover? only public? both?

anon can access private resources? anyway yes, publicly available resources

> * [ ]  **what do you mean exactly by testing ?**
>   
>   * embedded html for dashboards
>   * embedded html for geostory
>   * embedded html for maps

checking that the src url works I guess
![image](https://user-images.githubusercontent.com/5264230/146030905-1c94b932-d42a-460c-bc2b-c74a7a74b732.png)
Open to suggestions though

>   to test the url accessing those type of embedded urls?
>   like this one https://dev-mapstore.geosolutionsgroup.com/mapstore/embedded.html#/10358 ?

**Comment by MV88** [comment]
@PabloBaronetti  a few notes 

Mandatory tests:
As anonymous user, test access to resources: 
- mapstore homepage
  - list of maps https://dev-mapstore.geosolutionsgroup.com/mapstore/rest/geostore/extjs/search/category/MAP/***/thumbnail,details,featured?start=0&limit=12&includeAttributes=true
  - list of geostories https://dev-mapstore.geosolutionsgroup.com/mapstore/rest/geostore/extjs/search/category/GEOSTORY/***/thumbnail,details,featured?start=0&limit=12
  - list of dashboards https://dev-mapstore.geosolutionsgroup.com/mapstore/rest/geostore/extjs/search/category/DASHBOARD/***/thumbnail,details,featured?start=0&limit=12
  - list of contexts  https://dev-mapstore.geosolutionsgroup.com/mapstore/rest/geostore/extjs/search/category/CONTEXT/***/thumbnail,details,featured?start=0&limit=12
  
  change id based on resource
- map https://dev-mapstore.geosolutionsgroup.com/mapstore/rest/geostore/data/10358
- dashboard https://dev-mapstore.geosolutionsgroup.com/mapstore/rest/geostore/data/<dashboard_id>
- geostory https://dev-mapstore.geosolutionsgroup.com/mapstore/rest/geostore/data/<geostory_id>
- context https://dev-mapstore.geosolutionsgroup.com/mapstore/rest/geostore/data/20772

- thumbnail https://dev-mapstore.geosolutionsgroup.com/mapstore/rest/geostore/data/22381/raw?decode=datauri

- datadir externalization
it should be enough to test that this url will fetch the overridden file on a configred datadir
https://dev-mapstore.geosolutionsgroup.com/mapstore/configs/localConfig.json

**access_token** can be fetched here
where TOKEN_HERE is a base 64 of user:pwd
```sh
curl 'https://dev-mapstore.geosolutionsgroup.com/mapstore/rest/geostore/session/login' \
  -X 'POST' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 0' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Authorization: Basic <TOKEN HERE> ' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'Origin: https://dev-mapstore.geosolutionsgroup.com' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: https://dev-mapstore.geosolutionsgroup.com/mapstore/' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  --compressed 
```

then this access_token must be passed as bearer authentication header to the /data requests

As authenticated user (basic authentication) *:
- private map (the  same request a

Optional Tests (all with Authorization bearer token)
- users manager  https://dev-mapstore.geosolutionsgroup.com/mapstore/rest/geostore/extjs/search/users/*?start=0&limit=12
- groups  https://dev-mapstore.geosolutionsgroup.com/mapstore/rest/geostore/extjs/search/users/***?start=0&limit=5
- context manager https://dev-mapstore.geosolutionsgroup.com/mapstore/rest/geostore/extjs/search/category/CONTEXT/***/thumbnail,details,featured?start=0&limit=12

in this case a snapshot comparison can be used or maybe by checking that html is loaded
- embedded html for dashboards, for html see https://dev-mapstore.geosolutionsgroup.com/mapstore/dashboard-embedded.html
- embedded html for geostory https://dev-mapstore.geosolutionsgroup.com/mapstore/geostory-embedded.html
- embedded html for maps https://dev-mapstore.geosolutionsgroup.com/mapstore/embedded.html

* we'll eventually need to configure mapstore to allow for basic auth
see here https://github.com/geosolutions-it/MapStore2/blob/master/web/client/configs/localConfig.json#L38-L43


some link for reference 
https://github.com/geosolutions-it/geostore/wiki/REST-API
https://mapstore.readthedocs.io/en/latest/developer-guide/externalized-configuration/

**Comment by PabloBaronetti** [comment]
Work progress:

Docker-compose-override:
* Alpine Linux Test Container Definition (Dockerfile) 
* Docker-compose-override.yml - Dockerized to sync containers startup


Python Endpoint Tests
Base URL for the tests: https://mapstore.geosolutionsgroup.com/mapstore/#/

* Anonymous User :
  - Home Page Test (Multiple URL checks)
  - Individual Map Test 
  - Individual Dashboard Test
  - Individual Geostory Test

For more details:
https://github.com/geosolutions-it/MapStore2/tree/pbaronetti-endpoint-tests

**Comment by PabloBaronetti** [comment]
*Fixed the issue with access token on the test container
* Final test and wrap up of the [Jenkins Job](http://build.geosolutionsgroup.com/job/MapStore/job/MapStore2-EndPoints-Tests/)

All the tasks are completed and ready to test, 

The only thing we need to enable in the Jenkins Job is the "Build after other projects are built" option and bind the MapStore Jobs of our choice.

Thank you!

**Comment by randomorder** [comment]
enabled trigger after dev builds

**Comment by PabloBaronetti** [comment]
Understood @randomorder

I configure the build for this Job:
Dev Build: [Link](http://build.geosolutionsgroup.com/job/MapStore/job/MapStore2_Dev_Build/)

Do you want me to add additional emails in the notifications apart of ours directions?

Thanks!
