### ISSUE TITLE
Media Editor: maintain the resource origin when switching between resource types

### ISSUE THREAD

**Issue by tonym3nsa** [geosolutions-it/MapStore2#7693]
## Description

Switching between media types the media service always resets to the first/default one, which is annoying since the user needs to reselect the one previously selected.

Implement a fix In the media editor that persists the selected media service even after switching to different media types.

![switching.gif](https://images.zenhubusercontent.com/61236737eb6eac6b03da89b8/1f145b78-b44f-4c43-ab31-bbb2f00f14fc)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by MV88** [comment]
@tonym3nsa which story can i use to reproduce this?

**Comment by tonym3nsa** [comment]
@MV88 this is the original story https://github.com/geosolutions-it/nexus-geonode/issues/493

**Comment by MV88** [comment]
ok. but have you created a story in here https://dev-mapstore.geosolutionsgroup.com/mapstore/#/ for testing the fix, right?
or have you created it locally? 

anyway can you create a story (in DEV mapstore) if not present that can be used for testing?
thanks

**Comment by tonym3nsa** [comment]
@MV88 here you're https://dev-mapstore.geosolutionsgroup.com/mapstore/#/geostory/38147

**Comment by MV88** [comment]
there is not double services for images and videos

**Comment by MV88** [comment]
> there is not double services for images and videos

@tonym3nsa can you fix this. otherwise i cannot test the fix. i need double service scenario also for images or videos

**Comment by tdipisa** [comment]
Closed in favor of #7961
