### ISSUE TITLE
Ability to list contexts on the home page

### ISSUE THREAD

**Issue by alexander-fedorenko** [geosolutions-it/MapStore2#7717]
## Description
This task is created to backport changes initially implemented for geOrchestra repository 
https://github.com/georchestra/mapstore2-georchestra/pull/445
Improvement provides a way for user to add contexts list to the home page, along with a way to perform set of actions upon existing context: add into featured, share, edit, delete etc.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Other useful information
Changes are mostly re-use existing components with minor changes related to the specifics of the "Context" resource type.

**Comment by tdipisa** [comment]
@offtherailz correct me if I'm wrong but this should go in 2021.02.02.
