### ISSUE TITLE
Improvements to Map Widgets Pie and Bar Charts - attribute based colour coded classification

### ISSUE THREAD

**Issue by ale-cristofori** [geosolutions-it/MapStore2#7734]
## Description
This issue is created to keep track of the improvements suggested on #7594 , also tries to solve an issue raised with #6217,
regarding pie chart separation line not displaying correctly.

The original requirements were drawn after a request that came from a customer in a MS2 downstream project. Link to the issue: [#C070#214](https://github.com/geosolutions-it/npa-cgg/issues/214)

## Acceptance criteria
Summary of ACs requested:

1. Implementation of a DD with autocomplete for Class Value to have available classification attribute values, rather than text boxes.

2. The classification drop down menu is hidden since it drops down the modal window.
![image](https://user-images.githubusercontent.com/14953970/149348275-f9950df1-a9a2-4532-a0a8-5edcfadb26c1.png)

3. When the user adds a new classification rule, a colour different from the others should be automatically assigned.

4. You cannot close the custom colour setting panel except by clicking on save. There should be both save/close button with the usual confirmation message when needed (eg. for pending changes/mandatory empty fields in the form.
A confirmation modal dialog is now shown to ask for confirmation if some values are empty.

5. Add more margin around the new advanced option `Bar Chart Type` to make the form more readable.
![image](https://user-images.githubusercontent.com/14953970/149348381-f9f543ed-ae45-4c37-8a5a-2c6934a070db.png)

6. Issue raised within #6217 - Pie charts have no separation lines 
![image](https://user-images.githubusercontent.com/14953970/149348906-a4a2ef8d-0945-4e95-85f3-d268891adc57.png)

**Comment by ElenaGallo** [comment]
@ale-cristofori here some notes after testing this issue:

**1_** When adding a new entry above, the new Class Color and Class Label are added above, but the existing Class Value remains in the same position. See the gif below:

![1 1](https://user-images.githubusercontent.com/56537133/150777417-41d9bcd8-228d-416e-8d7f-a563cc4c340b.gif)

**2_** When the third value is added, a scroll bar appears, although it is not necessary. It creates problems when entering the class value and class label. See the gif below:

![2](https://user-images.githubusercontent.com/56537133/150777470-5b0e3f5f-ef5d-4e39-86ca-28e45ccfa0a5.gif)

**3_** When there are few slices in the pie chart the separation line is not present in the preview. See the image below:

![3](https://user-images.githubusercontent.com/56537133/150777579-e7846ba7-5ca5-4231-9ace-9b7ade4ebae8.png)

**Comment by ale-cristofori** [comment]
@ElenaGallo I see, thanks for having a look I will try to solve point 2 and 3. I am not too sure what the issue is with point 1. 
I am calling you, so that you can explain to me the issue in details.

**Comment by tdipisa** [comment]
@ale-cristofori @ElenaGallo I'm sorry for the delay. I saw you already opened a dedicated issue and raised a PR for the above. Thank you

> issue n.1: this is a bug and needs working on.

I noticed the issue happens also when you delete a record. Does your fix cover also this case?

> issue n.2: this issue is dependent on the screen size and I would need some advice as CSS can fix it.

@ElenaGallo please open a dedicated issue for this for 2022.01.00 and assign it to me.

> issue n.3 : the same fix applied for even coloured charts seems to be solving the issue and can be immediately applied.

Ok, thank you.
