### ISSUE TITLE
WFS request are no longer working in DEV

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#7736]
## Description

there are "" around paylod sent in wfs request that causes issue
probably connected to https://github.com/geosolutions-it/MapStore2/pull/7723

## How to reproduce

- open a new map
- add a layer (gs:states) from wms service
- open feature grid

*Expected Result*

it opens ok

*Current Result*

it has problems
![image](https://user-images.githubusercontent.com/11991428/149363906-9fa90b6d-1b96-4ac8-be29-956c7782230b.png)

![image](https://user-images.githubusercontent.com/11991428/149363914-95775345-7ca0-43e6-9d59-44f9dfdcef7a.png)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
@ElenaGallo I reverted the PR that caused this issue. We can close it if the bug is not present anymore. I'll work on #7531

**Comment by ElenaGallo** [comment]
@offtherailz @MV88 I need to know if there are other things to test after [this issue](https://github.com/geosolutions-it/MapStore2/issues/7708), which created the problem described above, has been merged. Thanks

**Comment by offtherailz** [comment]
This issue has been fixed in the second PR. So if you find more problems, maybe we should open other issues?
