### ISSUE TITLE
Bump Bootstrap to v3.4.1

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#7754]
## Description

Bootstrap (current version used by MS is 3.3.7) should be updated in MS to 3.4.1. No special particular breaking changes are expected but

- We have to ensure **ALL** the UI components will continue working as expected after the version update. Therefore a complete check tour is requested as part of this issue along with eventual necessary fixes.
- We have to check if also react-bootstrap need to be updated accordingly

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Other... Please describe: Bootstrap lib update

**Comment by allyoucanmap** [comment]
@alexander-fedorenko probably the update of react-bootstrap is not needed
