### ISSUE TITLE
Display tab is not displayed correctly in the Settings panel

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#7776]
On the _dashboard_ and _geostory_, the **Display** panel is larger than the default panel and a horizontal scroll bar appears on the Setting layer options
![display.gif](https://images.zenhubusercontent.com/5da5b30f66de7b0001e4e77c/08b3f34b-69b0-49b0-bd28-d177c825347e)

**How to Reproduce**
_On dashboard_ 
- Click on Map Widget
- Select a map
- Select a layer
- Click on layer settings
- Click on Display tab

_On geostory_ 
- Click on Chnage Media Source > Map tab
- Select a map > Apply
- Click on Edit map configuration
- Select a layer
- Click on layer settings
- Click on Display tab

***Current Result***
Display tab is not displayed correctly in the Settings panel

**Comment by mayankdp** [comment]
Hello, I have an assignment on Software Development Methodology where I have to contribute to an open-source repository. I am very interested in working on this issue. So can I work on this issue?

**Comment by tdipisa** [comment]
Dear @mayankdp fill free to contribute if you want and thank you so much for this. Consider that this issue is currently scheduled for the next major release, therefore a fix is needed by February, if you can.

**Comment by mayankdp** [comment]
Ok. I'll start working on this. If I have any questions I'll reach out to you. Thank you!

**Comment by mayankdp** [comment]
<img width="600" alt="Screen Shot 2022-01-27 at 11 32 42 PM" src="https://user-images.githubusercontent.com/45217514/151487792-5abea8e7-b082-4f40-a4c9-4f484179e73c.png">
@tdipisa, I have a question regarding running this issue while running npm install. Can you help?

**Comment by mayankdp** [comment]
Hii @tdipisa 
I have figured out the error I was getting. 
Could you help me on finding a Display tab that needs to fix? I tried to follow the above steps, but provided steps aren't helping.

**Comment by mayankdp** [comment]
Is this issue been resolved?
I was having a hard time finding the display tab. I am sorry about that. but it looks like it's been resolved (see below image).
<img width="721" alt="Screen Shot 2022-02-19 at 5 30 15 PM" src="https://user-images.githubusercontent.com/45217514/154821314-67a3a5ba-7792-4543-9ac1-7df0a31482a7.png">

**Comment by ElenaGallo** [comment]
Hi @mayankdp, the issue occurs for dashboards and geostories, look at the steps described in the gif below:
**On a dashboard**

![dash](https://user-images.githubusercontent.com/56537133/154918909-44de00b0-3c83-4cea-893d-e51b4241fe91.gif)

**On a geostory**
![geo](https://user-images.githubusercontent.com/56537133/154918922-99c631cc-8264-41a1-9ef7-b2714368109f.gif)

**Comment by mayankdp** [comment]
I have been trying to follow the step but when I run the project, I do not see create dashboard or story.
See below image: 
![IMG_6246](https://user-images.githubusercontent.com/45217514/156233816-7c17f354-8ba4-4395-8bf5-cdb18778aac6.jpg)

Do I need logging to see that bar (New Dashboard/ New Geostory)?

**Comment by tdipisa** [comment]
> Do I need logging to see that bar (New Dashboard/ New Geostory)?

yes

**Comment by mayankdp** [comment]
> > Do I need logging to see that bar (New Dashboard/ New Geostory)?
> 
> yes

So, How can I get that login?
