### ISSUE TITLE
Wrong tooltip in map viewer widgets

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#7779]
## Description

In the editing wizard of viewer widgets there is a wrong tooltip (the one that is used within dashboards).  

## How to reproduce

-  Edit for example an existing chart widget in [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/10358)

*Expected Result*

The tooltip should report: "Connect to the map"

*Current Result*

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/f282b010-ef9e-47f1-9973-149e7b7d7e9d)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by rohitp20092** [comment]
Investigation : When user create a new map , with adding layer have option to create widget after adding widget have to select chart type there is connect icon after connected it should show the **connect to the map** .
