### ISSUE TITLE
Further fixes are needed for the new charts classifier

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#7784]
## Description

1. The autocomplete field for classification values takes too long to load and, in certain cases, the loading is triggered simultaneously for different fields. 

![autocomplete.gif](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/9dafc4b7-c534-474a-8837-0c2845075e22)

2. The classification attribute is maintained in the WPS request even after switching to a solid color.

![solid_color_wps.gif](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/c8ebc25e-306d-4afc-ad76-ec917505d241)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by ale-cristofori** [comment]
the PR for this issue is https://github.com/geosolutions-it/MapStore2/pull/7830
