### ISSUE TITLE
WMS layers are not added from CSW sources in some cases

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#7800]
## Description

In some cases it is no longer possible to add WMS layers from a CSW catalog. Looking in the DEV tool, a wrong request to _/undefined?service=WMS&version=&request=GetCapabilities_ is also performed.

## How to reproduce

-  Open [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/10358)
- Open the Catalog tool and select "_CSW Catalog Geo Bretagne"_
- Do a search

*Expected Result*

It is possible to add WMS layers where a WMS resource is defined in the metadata.

*Current Result*

![csw_issue](https://user-images.githubusercontent.com/1280027/151553627-15036677-eb06-406f-b84f-a6e05361454c.gif)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

This is affecting also v2021.02.01

**Comment by tdipisa** [comment]
@MV88 @ElenaGallo 

> In some cases it is no longer possible to add WMS layers from a CSW catalog. Looking in the DEV tool, a wrong request to /undefined?service=WMS&version=&request=GetCapabilities is also performed.

I've just realized that the request to _/undefined?service=WMS&version=&request=GetCapabilities_ is always performed. Why @MV88? If this is effectively a typo, please open an issue to sort this too.

**Comment by MV88** [comment]
@tdipisa sorry i focused on fixing the problem when adding csw layers.
and since this wrong call still occurs having fixed that error it must not be correlated

opened #7849
