### ISSUE TITLE
when JRE_HOME is defined in the env variables the binary does not start

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#7810]
## Description

In my case:
- Windows 10
- java 11.0.11

when launching the mapstore-startup.bat it was not starting anything
we need to investigate if the usage of JRE_HOME is a common practice

@tdipisa 
we should investigate if a fix is needed or we can simply improve feedbacks and or documentation

## How to reproduce

-  have a JRE_HOME var defined in the system variables (windows)
- try to start this binary when it will be released https://github.com/geosolutions-it/MapStore2/releases/tag/v2021.02.02
or apply [this](https://github.com/geosolutions-it/MapStore2/commit/342181a5680945907040bef4e7ff08e6661fdfb2) patch to https://github.com/geosolutions-it/MapStore2/releases/tag/v2021.02.01

*Expected Result*

mapstore binary starts  correctly

*Current Result*

opening http://localhost:8082/mapstore/#/ it says not reachable
![image](https://user-images.githubusercontent.com/11991428/151946139-d2dcd96f-da97-40c4-9e34-df2473609073.png)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

# SOLUTION

- move JRE_HOME  value to Path system vars
- %JAVA_HOME%\bin
- delete JRE_HOME

**Comment by tdipisa** [comment]
@MV88 is it maybe connected to #7513 recently fixed by @offtherailz?

**Comment by offtherailz** [comment]
No @tdipisa , this is another small issue discovered when `JRE_HOME` variable is defined. We need to investigate if it affects linux and windows or only windows and provide a separate fix.

Anyway take into account that it is a rare condition:
- You are usually a java developer if you did this, probably 
- we usually we define only `JAVA_HOME`, not `JRE_HOME`
- it happens only if the `JRE_HOME` java version is not compatible

So it needs a lot of conditions to happen. Moreover, it can be fixed easely on binary by redefining vars or editing scripts (and the developer ho set the variable,

**Comment by MV88** [comment]
idk I have to check
