### ISSUE TITLE
Restore States geometry

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#7812]
## Description

with testing and trainings we modified the states geometry too much and we need to:
- restore it
- create a clone of this layer and a dedicated map to be used inside trainings / testing 

![image](https://user-images.githubusercontent.com/11991428/151970137-3728fbcc-aad3-483f-ab78-77d6e91ac1b4.png)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by tdipisa** [comment]
@MV88 @offtherailz @allyoucanmap done. Training map available [here](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/37796). Training layer is _geosolutions:states_training_
