### ISSUE TITLE
OpenID support

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#7872]
## Description
Provide support for OpenID login. 

## Acceptance criteria

- [ ] As an dev/sys admin, I can edit `localConfig.json` to add `authenticationProviders` entry to configure openID login
```
"authenticationProviders": [{"type": "openID", "provider": "acm"}, {"type": "basic", "provider": "geostore"}],
```
   Every element of this entry should allow to login with a different login system. 
   - `{"type": "basic", "provider": "geostore"}` represents the current login system with username/password prompt login to GeoStore. If  `authenticationProviders` is not present, it will work as it was configured 

- [ ] As a user, **if more than one provider is present**, the user will see a prompt window where he can select to login with one of the given openID services, by clicking on the related entry, or using username/password (if `{"type": "basic", "provider": "geostore"}` is present in the list).
![image](https://user-images.githubusercontent.com/1279510/154671505-07d31b07-fdc8-4cd5-beda-527a5aa8efba.png)

- [ ] As a user, **if only one "openID" entry is present**, the login will attempt directly the login with the given service, without promting anything

- [ ] As an administrator I can associate users logged in using the openID service to roles or groups, because, as well as a user is logged in using the openID service, a new user is created in MapStore database, if it doesn't exist. 

- [ ] As a user, if I logged using a openID service, I'm not allowed to change password or see my info. 

- [ ] This feature have to be documented on configuration section of MapStore documentation. 

## Other useful information

This needs support on GeoStore 1.8.x of openID login.

**Comment by ale-cristofori** [comment]
This ticket is dependent on the closing merging of this PR #7873 
this piece of work is preparatory to #8192

**Comment by ale-cristofori** [comment]
As of today 04/08/2022, the testing of this feature on our dev environment is dependent on time constraints dictated by our resources availability, estimation on the setup of the testing environment has been given by @offtherailz, we are now waiting for any free MapStore resource who can work on this.

see https://github.com/geosolutions-it/MapStore2/issues/8429

**Comment by ElenaGallo** [comment]
The OPEN ID support has been tested with #8434
