### ISSUE TITLE
Align print-lib to the latest version

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#7890]
## Description

After merging https://github.com/geosolutions-it/mapfish-print/pull/49, some changes to the application context will be needed to match requirements of the updated print-lib library (that has been aligned with the latest official 2.1.5 version).

In particular, the following should be added to all the instances of applicationContent-print.xml in the repo (both for the product and standard project):

```xml
<bean id="threadResources" class="org.mapfish.print.ThreadResources">
        <property name="connectionTimeout" value="30000"/>
        <property name="socketTimeout" value="30000" />
        <property name="globalParallelFetches" value="200"/>
        <property name="perHostParallelFetches" value="30" />
</bean>
...
<bean id="metricRegistry" class="com.codahale.metrics.MetricRegistry" lazy-init="false"/>
<bean id="healthCheckRegistry" class="com.codahale.metrics.health.HealthCheckRegistry" lazy-init="false"/>
<bean id="loggingMetricsConfigurator" class="org.mapfish.print.metrics.LoggingMetricsConfigurator"  lazy-init="false"/>
<bean id="jvmMetricsConfigurator" class="org.mapfish.print.metrics.JvmMetricsConfigurator" lazy-init="false"/>
<bean id="jmlMetricsReporter" class="org.mapfish.print.metrics.JmxMetricsReporter" lazy-init="false"/>
```

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by tdipisa** [comment]
Thank you @mbarto for the update. The migration guidelines should be updated accordingly then. It would be good to start testing the new version in DEV soon if we want to release this on 2022.01.00, the release deadline is quite close.

**Comment by offtherailz** [comment]
I had to revert the PR because it caused the problem listed.
See details here: https://github.com/geosolutions-it/MapStore2/pull/7891#issuecomment-1060455482
