### ISSUE TITLE
A wrong GML format is used for the WPS export spatial filter

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/MapStore2#7893]
## Description
When trying to download a dataset with a **spatial filter** applied like shown here below an error is thrown by Geoserver. 

According to the analysis performed by the Geoserver team, the filter being declared is 1.1 whilst the GML polygon definition used is GML v2 instead of GML v3 required by OGC Filter 1.1.

So, gml:exterior should be used instead of gml:outerBoundaryIs and gml:posList instead of gml:coordinates.

(I did a test with some local data and after changing the polygon syntax it worked for me).

This is the a working polygon definition:
```gml
<gml:Polygon srsName="EPSG:3857">
  <gml:exterior>
    <gml:LinearRing>
      <gml:posList>-11662456.027639 5009377.085697 -11662456.027639 4050551.002887 -9236039.001754 4050551.002887 -9236039.001754 5009377.085697 -11662456.027639 5009377.085697</gml:posList>
    </gml:LinearRing>
  </gml:exterior>
</gml:Polygon>
```

But MapStore created the following, which causes the error:
```gml
<gml:Polygon srsName="EPSG:3857">
  <gml:outerBoundaryIs>
    <gml:LinearRing>
      <gml:coordinates>90319.02643363085,3414964.3591960706 90319.02643363085,3991448.246372885 687801.5984746646,3991448.246372885 687801.5984746646,3414964.3591960706 90319.02643363085,3414964.3591960706</gml:coordinates>
    </gml:LinearRing>
  </gml:outerBoundaryIs>
</gml:Polygon>
```

*How to reproduce*
1. Open [this GeoNode dataset](https://master.demo.geonode.org/catalogue/#/dataset/706) 
2. Click "Filter" in the top bar
3. Set a spatial filter and apply
4. Click "Export" in the top bar
5. Activate the Downlkoad filtered dataset option and click "Export"
6. An error is returned

![image](https://user-images.githubusercontent.com/571129/156142693-c89acd9d-5fd8-4b9b-8626-5c5c2cc7eccb.png)

![image](https://user-images.githubusercontent.com/571129/156142722-a77b4231-ca1a-45d2-bcfe-c8a04db552e6.png)

![image](https://user-images.githubusercontent.com/571129/156142739-717edfa9-2a58-44e9-8b33-62a7086bcb69.png)

*Expected Result*
 I'd expect the process correctly generating the output file

*Current Result*
An error from Geoserver is returned instead of the output file.

## Other useful information
GeoNode uses MapStore at commit [9bb7b14](https://github.com/geosolutions-it/MapStore2/tree/9bb7b146177c8fffaa3192e5aacd8689d32c0065)

**Comment by giohappy** [comment]
@DavidQuartz it can be replicated on [MapStore demo site](https://mapstore.geosolutionsgroup.com/) usinn this [map.json](https://github.com/geosolutions-it/MapStore2/files/8176521/map.json.zip), which contains a filtered layer.

1. Import `map.json`
2. Click the xport icon of "Reg01012019_g_WGS84"
3 . Activate the Downlkoad filtered dataset option and click "Export"

**Comment by DavidQuartz** [comment]
After fixing this issue, I have realised that on mapstore Dev instance, there seems to be an issue with geoserver version. The wps export sometimes returns a NullPointer error from geoserver (for every format except CSV) even though the same request on geonode works.
Mapstore Dev geoserver version 2.20-SNAPSHOT
Geonode geoserver version 2.19.5 (with some plugins officially released)

**Comment by tdipisa** [comment]
> After fixing this issue, I have realised that on mapstore Dev instance, there seems to be an issue with geoserver version. The wps export sometimes returns a NullPointer error from geoserver (for every format except CSV) even though the same request on geonode works. Mapstore Dev geoserver version 2.20-SNAPSHOT Geonode geoserver version 2.19.5 (with some plugins officially released)

Dear @DavidQuartz can you open a dedicate issue for this please indicating the exact steps to reproduce it so that I can ask devops for a check?
