### ISSUE TITLE
Remove / Replace MapQuest layer type

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#790]
See https://github.com/openlayers/ol3/issues/5484

We could: 
- remove support for MapQuest layer type (and/or transparently replace it with another tiled layer service, such as OSM)
- implement leaflet support through the MapQuest leaflet plugin
- what can we do for ol3? Probably not much, just doing a transparent replace with OSM for retro-compatibility

**Comment by offtherailz** [comment]
MapQuest background has been properly disabled when API key is missing and excluded from the default background. 
I'm going to close this issue.
