### ISSUE TITLE
Remove custom template for project

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#7918]
## Description
We need to dismiss also the **custom** project template, that has been not maintained or used for a long time. 

e.g. 
https://github.com/geosolutions-it/MapStore2/blob/master/project%2Fcustom%2Ftemplates%2Fweb%2Fpom.xml#L23

Is old, with mapstore-backend. I think nobody is using it, also because only MapStore expert can understand the difference, and MapStore expert can use the new project system now. 

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by ale-cristofori** [comment]
@tdipisa can this be closed now?
