### ISSUE TITLE
Mobile - Extra page on GFI panel

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#7928]
## Description

Some time on GFI panel there is a page with this message: `no features were found` and a blank page.

![MOBILE TRUE](https://user-images.githubusercontent.com/56537133/157256232-8a5c4e82-67a7-405f-920c-f6f0261dff94.gif)

## How to reproduce

-  Open a map on mobile
- Click e feature 
- Scroll the page on GFI panel

*Current Result*

On GFI panel there is a page with this message: `no features were found` and a blank page.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by buhao75** [comment]
Hello!

Sorry for cross posting but could you have a short look at this post of me in the developers group: https://groups.google.com/g/mapstore-developers/c/cqNUL_-n5jg
Might this be related to this issue or this one: https://github.com/geosolutions-it/MapStore2/pull/7867

It took me quite a while to figure it out and if it is a bug it would be cool if it would be solved.

Thanks and all the best,
Michael
