### ISSUE TITLE
'Sentinel 2 Cloudless' background does not work in 3D mode

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#7964]
The 'Sentinel 2 Cloudless' background is not visible in 3D mode. Error on console:

> An error occurred in "wOe": Failed to obtain image tile X: 8 Y: 2 Level: 3.

**How to Reproduce**
See the gif below:
![3d background](https://user-images.githubusercontent.com/56537133/158398989-3952db9d-db2f-43e9-a629-d1b48a13a1d0.gif)

*Expected Result*
The 'Sentinel 2 Cloudless' background is visible in 3D mode.

**Comment by allyoucanmap** [comment]
@tdipisa @ElenaGallo the tiles are requested using the mapstore proxy path:

`https://dev-mapstore.geosolutionsgroup.com/mapstore/proxy/?url=https%3A%2F%2F3maps.geo-solutions.it%2Fgeoserver%2Fwms%3Fstyles%3D%26format%3Dimage%252Fjpeg%26transparent%3Dtrue%26opacity%3D1%26tiled%3Dtrue%26width%3D256%26height%3D256%26service%3DWMS%26version%3D1.1.1%26request%3DGetMap%26layers%3Ds2cloudless%253As2cloudless%26bbox%3D22.5%252C22.5%252C45%252C45%26srs%3DEPSG%253A4326`

and same is happening at https://mapstore.geosolutionsgroup.com/ instance:

`https://mapstore.geosolutionsgroup.com/mapstore/proxy/?url=https%3A%2F%2F4maps.geo-solutions.it%2Fgeoserver%2Fwms%3Fstyles%3D%26format%3Dimage%252Fjpeg%26transparent%3Dtrue%26opacity%3D1%26tiled%3Dtrue%26width%3D256%26height%3D256%26service%3DWMS%26version%3D1.1.1%26request%3DGetMap%26layers%3Ds2cloudless%253As2cloudless%26srs%3DEPSG%253A4326%26bbox%3D45%252C22.5%252C67.49999999999997%252C45`

![image](https://user-images.githubusercontent.com/19175505/158408068-528dd14e-a2c4-4396-a6c6-8f41ce7edcab.png)


layer configuration is using following urls that probably are not supported by the proxy?

```js
{
  "format": "image/jpeg",
  "group": "background",
  "name": "s2cloudless:s2cloudless",
  "opacity": 1,
  "title": "Sentinel 2 Cloudless",
  "type": "wms",
  "url": [
    "https://1maps.geo-solutions.it/geoserver/wms",
    "https://2maps.geo-solutions.it/geoserver/wms",
    "https://3maps.geo-solutions.it/geoserver/wms",
    "https://4maps.geo-solutions.it/geoserver/wms",
    "https://5maps.geo-solutions.it/geoserver/wms",
    "https://6maps.geo-solutions.it/geoserver/wms"
  ],
  "source": "s2cloudless",
  "visibility": false,
  "singleTile": false
},
```

If I send a direct riquest to the proxied url the tile is visible:

https://6maps.geo-solutions.it/geoserver/wms?styles=&format=image%2Fjpeg&transparent=true&opacity=1&tiled=true&width=256&height=256&service=WMS&version=1.1.1&request=GetMap&layers=s2cloudless%3As2cloudless&srs=EPSG%3A4326&bbox=-90%2C0%2C-45%2C45

![image](https://user-images.githubusercontent.com/19175505/158409211-e230996b-7362-4272-8106-52b31aeb67a3.png)
