### ISSUE TITLE
Update the release procedure on milestones usage dismiss

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#7967]
## Description
The release procedure relies on milestones in compiling changelogs and release notes.
We recently replaced github milestones with zenhub releases. We have to update the release procedure to use it. 

## Possible solutions

- Remove changelog at all and find a way to export release issues from zenhub, to have somehow a summary of the issues solved
- try to automatically sync releases with milestones (if some API or github action allows it)  and continue using milestones to generate changelog
- Rely on automated github release notes generation (it works only on the same branch, so this doesn't work with our current workflow, only for minor). 

note: autogenerated release notes do not work because of stable branch work ( it works if you have more tags on the same line, with a develop branch to merge) evaluate this possibility with rebase merge or something ...
e.g. part of the output tested with the latest release is is this: **Full Changelog**: https://github.com/geosolutions-it/MapStore2/compare/v2018.01.00...v2022.01.00

*Documentation section involved*
- [ ] User Guide
- [x] Developer Guide

**Comment by tdipisa** [comment]
@offtherailz one possible solution through a backing label :) we assign all issues in a Release to a release label and then we assign a milestone from github to issues with that label. Finally we delete the label and we close the milestone.
