### ISSUE TITLE
Printing Preview in printing panel does not show layers in OL3

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#797]
I tested on Windows with [this](http://qa.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/464?_k=rnesqm) map.

See image below (no old maps for Florence city centre):
![clipboard02](https://cloud.githubusercontent.com/assets/693880/16564798/d427a832-4209-11e6-8de1-6b47f5782946.jpg)

**Comment by mbarto** [comment]
I can fix the layer not showing on the preview. To fix the printed map we would need to patch MapFish-print to support tiling on WMS, since this layer is served by a GWC only service that cannot serve tiles of more than 256x256 pixels
