### ISSUE TITLE
Minor user and developer documentation fixes 

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#7981]
## Description
- [x] [here](https://mapstore.readthedocs.io/en/latest/developer-guide/externalized-configuration/#externalize-front-end-configurations)Customization of app.jsx for configuration should be moved to a specific section for developers, outside the part of the data dir, because it is not strictly in the context (I suggest to move it at the end of the page, in a separate paragraph).
- [x] Review overrides functionality. I wasn’t able to reproduce adding the given files mapstore.properties and env.properties to the datadir. https://mapstore.readthedocs.io/en/latest/developer-guide/externalized-configuration/#overriding-front-end-configuration
- [x] Catalog settings now has domain aliases, it can be documented easely

*Documentation section involved*
- [x] User Guide
- [x] Developer Guide

**Comment by tdipisa** [comment]
This is already documented [here](https://mapstore.readthedocs.io/en/v2022.01.00/user-guide/catalog/#wmswmts-catalog) in user guide. Do you think it is not enough?

**Comment by offtherailz** [comment]
I didn't see it, it is enough I think. I agrre, so I assigned the release

**Comment by MV88** [comment]
@offtherailz
Second points seems more a bug to me

I have tested it by configuring a datadir but is not clear to me a couple of things:
- where is expected to place mapstore.properties and env.properties?
   - in tomcatpath\webapps\mapstore\WEB-INF\classes
   OR
   - in tomcatpath\datadir 
 
Currently placing those in **classes** folder it ignores them,
placing them in the **datadir** folder it does not do the override, but it leaves the value in localConfig as empty string

here is the zip of properties file

[properties.zip](https://github.com/geosolutions-it/MapStore2/files/8483027/properties.zip)

I'm struggling a bit at debugging this, so let me know when we can a have a quick sync
about it

In the meantime I can provide a quick PR for the first point
