### ISSUE TITLE
GeoStories - support of WMTS layers with tileMatrix configuration

### ISSUE THREAD

**Issue by ale-cristofori** [geosolutions-it/MapStore2#7983]
We need to enable the inclusion of WMTS defined layers with a tileMatrix for geostories. There are currently several way for including maps with WTMS layers in geoStories, and since WMTS is not supported we can have undesired effects:

1. Export a map from map Editor in WMC will only export non-WMTS layers, if a subsequent import of  the same map is attempted in GeoStory within the WMTS layers will not display, the application won't crash though

![recording_1](https://user-images.githubusercontent.com/14953970/158156505-588a7f20-742a-4c1f-9f12-9e4aba75ff68.gif)

2. Export a map from map Editor in `json` format and subsequently import the map in GeoStory within the media import, the import is successful, the application will crash upon geostory map confirmation. See below
![recording_1](https://user-images.githubusercontent.com/14953970/158159731-21e6751c-1b01-4ec9-a260-c2962f5d4a3b.gif)

 
3.  create a new map from the map editor of GeoStory and add a WMTS layer (as a background or not), same result as point 2.

![recording_1](https://user-images.githubusercontent.com/14953970/158160342-b6ccc3db-4f67-450a-8a2f-8e535316ac29.gif)

**Comment by tdipisa** [comment]
@ale-cristofori moving in blocked for the moment. Let's discuss with @allyoucanmap before proceeding with the remaining implementation.

**Comment by ale-cristofori** [comment]
As for export/import WMTS specs layers within WMC. The feature is not supported by the the official OGC WMC specification, therefore we won't implement it in MS2 for the time being.

The missing specification for all layers but WMS in the WMC specification is documented in the official OGC documentation and in previous MS2 issues (see https://github.com/georchestra/mapstore2-georchestra/issues/60#issuecomment-584231493)

I am going to progress this issue for points 2 and 3 of the [original issue explanation](https://github.com/geosolutions-it/MapStore2/issues/7983#issue-1172231400)
