### ISSUE TITLE
Amend migration guidelines for 2022.01.00

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#7992]
## Description

Since the print lib update will lands in 2022.02.00, the following section should be removed from the 2021.02.00 to 2022.01.00 migration guidelines:
https://mapstore.readthedocs.io/en/latest/developer-guide/mapstore-migration-guide/#upgrading-the-printing-engine

A new dedicated paragraph for 2022.02 should be created for this probably.

*Documentation section involved*
- [ ] User Guide
- [X] Developer Guide

**Comment by offtherailz** [comment]
This work has been done here:  
https://github.com/geosolutions-it/MapStore2/pull/7996/files#diff-3599ba7c628c7c764665046828bad74c0c8576aad03f5497cf426b59010a6d07R23

**Comment by tdipisa** [comment]
@offtherailz it doesn't seem to me we need to amend the same in the doc for 2022.01.00. Can you confirm? Anyway the doc for 2022.01.xx is no longer available, can you please restore it?

**Comment by offtherailz** [comment]
Now, after a re-build. The link to 2022.01.xx is present in the list.
