### ISSUE TITLE
Main depencencies check 

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#7994]
@offtherailz
Also for 2022.02.00 we have to include in the release plan some libs update for master branch:

- [x] print-lib geosolutions-2.1-SNAPSHOT (nothing to do)
- [x] http-proxy 1.4-SNAPSHOT @taba90 
- [x] geostore 2.0-SNAPSHOT @taba90 
- [x] mapstore-services 1.5-SNAPSHOT @taba90 

For 2022.02.00 we need:

- [x] print-lib geosolutions-2.1.0 (to release) @taba90
- [x] http-proxy 1.3.0 (to release) @taba90
- [x] GeoStore 1.9.0 (to release for openid updates) @taba90
- [x] mapstore-services 1.4 (to release) @taba90
- [x] https://github.com/geosolutions-it/MapStoreExtension master should be updated in advance to the new 2022.02.xx as soon as available and the related stable branch created on the extension repo @MV88
done here https://github.com/geosolutions-it/MapStoreExtension/pull/34

https://github.com/geosolutions-it/MapStore2/wiki/MapStore-Releases-2022

**Comment by tdipisa** [comment]
@mbarto is all ready in master branch [here](https://github.com/geosolutions-it/mapfish-print) to release version _geosolutions-2.1_ after our testing in MS DEV?

**Comment by offtherailz** [comment]
Here release procedure for mapfish print. I wrote it without testing but it should be fine. 

https://github.com/geosolutions-it/mapfish-print/wiki/How-to-Release

**Comment by tdipisa** [comment]
Thank you so much @offtherailz

**Comment by taba90** [comment]
@tdipisa geostore, http-proxy and print-lib releases are completed.

**Comment by tdipisa** [comment]
> @tdipisa geostore, http-proxy and print-lib releases are completed.

@taba90 new stable branch created here https://github.com/geosolutions-it/MapStore2/tree/2022.02.xx please provide a PR to update dependencies

**Comment by MV88** [comment]
@tdipisa yes authkey is not the right one, we should be able to fix when we work on #7165 
![image](https://user-images.githubusercontent.com/11991428/182655604-7263eedf-994f-4f85-b983-020977fde6a8.png)

**Comment by taba90** [comment]
@tdipisa everything should be done (mapstore services apart).
Here the last pr to change the print-lib version to use tag instead of snapshot https://github.com/geosolutions-it/MapStore2/pull/8540

**Comment by tdipisa** [comment]
Thank you @taba90 ;-)

**Comment by tdipisa** [comment]
Updated and working also DEV with #8459

**Comment by tdipisa** [comment]
Waiting fro the release to proceed with the pending activity as per description.
