### ISSUE TITLE
Change order of migration guidelines (from top to bottom)

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#7998]
## Description

About order I think the current way of scrolling from bottom to top and then read from top to bottom is quite silly and uncomfortable. can we use an approach from topo to bottom that when you reach migration guidelines you end up focused on last update, but read everything from top to bottom? what about using accordions? 

here an image that explain current reading flow

![image](https://user-images.githubusercontent.com/11991428/159446088-29365a65-a8fc-4427-b0b4-f133db63532a.png)

blue arrow is where you start reading migration changes and you go down, 
then at the end of that section you have to go back up and again this repeats

I think we can do better

*Documentation section involved*
- [ ] User Guide
- [ ] Developer Guide

## Other useful information

Feel free to open the discussion

**Comment by tdipisa** [comment]
not needed, we are ok with the current order
