### ISSUE TITLE
WMTS Background layers attributions handling 

### ISSUE THREAD

**Issue by ale-cristofori** [geosolutions-it/MapStore2#8004]
WMTS `getCapabities` does not natively handle retrieval from server of Attributions (copyright statements, credits, etc.) for single background layers, as it does for WMS. Some external WMTS services (e.g OSM) implement a custom retrieval of such information, we need to implement the same result for background layers sourced from Geoserver.

Layer attributions, displayed on the left bottom part of the map, for WMTS background layers need to be handled this client-side. We can provide attributions as items of background layers configuration and let users modify the attributions text within the MapStore UI, creating an a text edit area in the background layers settings modal window.

The attribution text in the WMTS background layer configuration will be the default attribution text, could also be empty as default.

The attribution text will be handled and stored in memory as an HTML string, allowing only basic styling tags (bold, italic, anchor).

Background WMTS layers attributions will only be edited by logged in and authorized MS2 roles, if a user can edit a background layer then they will also be able to edit its attribution text.

the edit text area will be placed in the `Edit Current Background` modal that will open when users click on the 'spanner' icon button on the background layers cards appearing on the bottom left corner of the map.

![image](https://user-images.githubusercontent.com/14953970/159515037-b3279e3f-d27c-4429-8463-dd52c8ec10f8.png)

The edit text box will be 'wysiwyg', which means users will be able to format the text directly in the textbox and see the final result, internally the string will be stored as HTML.

![image](https://user-images.githubusercontent.com/14953970/159530329-b601ef50-f058-4051-9caa-fbf33ed53622.png)

Once user saves the edited attribution text, the changes will be recorded in the map state, saved as a child map, the edited attribution text will display on all maps using that background layer.

The enhancement has to be implemented for openlayers, leaflet and cesium maps

**Comment by ElenaGallo** [comment]
Test passed, @ale-cristofori please backport this to 2022.01.xx. Thanks
