### ISSUE TITLE
Extend the map viewer query parameter API.

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#8006]
## Description

This issue tryies to provide the functionalities of https://github.com/georchestra/mapstore2-georchestra/issues/476. 

This can be done via query parameters adding: 

- a `map` parameter with the mapstore map. The map can include the "layers" and other options (also to center/zoom). If `center` `bbox` and or `zoom` are persent, they will have priority over the map passed. If they are not present, the default map ones will be used. Generally speaking, the `map` parameter will be used as an override of the current map. All the fields that are present will completely override the existing ones.
- for FeatureInfo we can use an existing action (or create a custom one, if not present) for that can be passed in the existing `actions` parameter. 

example: `#/mapstore/viewer/config?map={title:"Title of the map", layers: [...], ....}&actions=[....]`

**notes**: 
- the parameters can be applied to every map. `config ` is one of the default ones. The map object will be merged with the current map. Because the JSON format is this (with a sub-attribute `map`)
![image](https://user-images.githubusercontent.com/1279510/159679490-9c0f10a3-e728-4695-a761-1f18fa410f59.png)
In order to allow merging map efficenty adding layers we will need to merge the root object and the `map` su attribute, like this:
```
{
...originalMap,
...queryParamsMap,
map: {
      ...(originalMap?.map ?? {}),
      ...(queryParamsMap?.map ?? {})

}
```

- the map must be *url encoded* and have the format of the map of MapStore.  

This approch (instead of the initial idea of expanding the existing functionalities proposed [here](https://github.com/georchestra/mapstore2-georchestra/issues/476#issuecomment-1026885629)) simplifies a lot the management and the documentation. 

This solution has the counter effect of being limited by the URL size limitation. 

Instead of trying to workaround this issue by shorting up URL with some tricks (e.g. passing only layers and reying on catalogs)  I suggest to pass this limitation supporting POST in the back-end. 

Any POST request via back-end to a given sub-service will be handled by the back-end, that stores in `sessionStorage` the params of the request and redirects to the correct page. 

`POST /mapstore/rest/config/setParams?page=<REDIRECT_PAGE>`
e.g. `POST /mapstore/setParams 
body: 
```
map={....}
center={...}
bbox={...}
featureinfo={...}
actions={...}
page=#/viewer/openlayers/config
```

This saves in `sessionStorage` and object `queryParams` with all the arguments and redirects to the page passed as parameter. These argument will be used in the exact same way as they was received from the query string. 

The page will read the `sessionStorage` and simply use the parameter as they was coming from the query string to use them, and delete them after reading.

Anyway this requires some small work on server side. Please give me your opinion @tdipisa 

For no base map, we can use the standard : #/viewer/openlayers/config  (`config.json` )

**note** for storage, I preferred sessionStorage instead of `localStorage` because it is limited to the tab and will be deleted on close. While login state should be shared across tabs and when closing the window and reopen, this params are only valid on first page load. They should be deleted as well as they are read, if present. 

here the template of the page to render in the POST service
```html
<!DOCTYPE html>
<html>
<head>
    <script>
        sessionStorage.setItem("queryParams", JSON.stringify(<JSON_PARAMS>));
        location.href='<PAGE_PARAM>'; 
    </script>
</head>
<body>
</body>
</html>

```
where 
- `<JSON_PARAMS>` is a json with all the params of the request body except `page`
- `<PAGE_PARAM>` is the `page` param of the request body. 

## Acceptance criteria

- [ ] As a user/application I can create a URL for the map viewer that allows me to configure arbitrary map and layers for the viewer. 
- [ ] As a user/application I can create a URL for the map viewer that allows me to perform a getFeatureInfo on a given point specifying, optionally, the layers IDs to apply. If no layers specified, it will work on all layers as usual. 
- [ ] The features above can be used together (map+feature info) and in combination with the other existing parameters (actions, bbox, center, actions, marker* --> marker is not mandatory to work with feature info). 
- [ ] support passing these params also with POST request

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Other useful information

here a snippet for a test page to redirect to that should display the queryParams

```html
<!DOCTYPE html>
<html>
<head>
    <script>
        onLoad = () => {
        var div = document.createElement('div');
        div.innerHTML = sessionStorage.getItem("queryParams");
        document.body.appendChild(div);
        }

    </script>
</head>
<body onLoad="onLoad()">
</body>
</html>
```

**Comment by tdipisa** [comment]
@taba90 I'm lookign forward to hearing from you how we can schedule the backend part for this implementation. As I told you in the call, we can also consider to split the issue in two if you need.

**Comment by offtherailz** [comment]
After a check we contiunue with the idea of sessionStorage (the page is very simple): 
Here the code of the page. 
```
<!DOCTYPE html>
<html>
<head>
    <script>
        sessionStorage.setItem("queryParams", JSON.stringify(<JSON_PARAMS>)); // h map and actions is a json to render in the page
        location.href='<PAGE_PARAM>'; // this is the redirect
    </script>
</head>
<body>
</body>
</html>

```
where 
- `<JSON_PARAMS>` is a json with all the params of the request body except `page`
- `<PAGE_PARAM>` is the `page` param of the request body. 

The entry point will be `/rest/config/setParams`

**Comment by taba90** [comment]
I've created a separate issue for the backend taks available [here](https://github.com/geosolutions-it/MapStore2/issues/8034).
I've started working on it.

**Comment by tdipisa** [comment]
Thank you @taba90

**Comment by landryb** [comment]
my 2c, after stumbling on this implementation proposal, and having used a bit the existing GET support params: in georchestra/mapstore2-georchestra#476 it was proposed to use a simple GET url (and extend the existing support) for a reason: it allows someone to quickly build a map by just editing the url in the browser, passing some parameters overriding the defaults, which is how it works (and what admins are used to) in mapfishapp or sviewer or mviewer.

If i get it right, this convoluted method of having to POST a 'rather large' json to an URL which would then build something in session storage (will it work in private browsing ?) and redirect to the map (correct me if i misunderstood) makes it rather difficult for someone to quickly build a map from the browser url.

Unless somewhere there's a (hidden?) plan to provide a web page/form allowing end users/admins to build that json to POST :)

I'm not 200% sure what was expected, just wanting to be sure what will be implemented matches expectations. @jusabatier @MaelREBOUX  ?

**Comment by tdipisa** [comment]
@landryb thank you for sharing your considerations. Below my feedbacks:
- Having a POST method, you probably know that, was one of the possibilities as mentioned in the requirements. This is especially to manage long query parameters where the size exceed the browser GET request limitations 
- This parameters can be anyway managed also via GET. Below an example:

```
https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/38982?center=10.724764124999998,43.3545336417839&zoom=8&featureinfo={%22lat%22:%2043.559,%20%22lng%22:%2011.036,%20%22filterNameList%22:%20[]}&map={%22version%22:2,%22map%22:{%22projection%22:%22EPSG:4326%22,%22units%22:%22m%22,%22center%22:{%22x%22:15.535581676494019,%22y%22:44.830249175294,%22crs%22:%22EPSG:4326%22},%22zoom%22:5,%22maxExtent%22:[-20037508.34,-20037508.34,20037508.34,20037508.34],%22layers%22:[{%22id%22:%22mapnik__0%22,%22group%22:%22background%22,%22source%22:%22osm%22,%22name%22:%22mapnik%22,%22title%22:%22Open%20Street%20Map%22,%22type%22:%22osm%22,%22visibility%22:true,%22singleTile%22:false,%22dimensions%22:[],%22hideLoading%22:false,%22handleClickOnLayer%22:false,%22useForElevation%22:false,%22hidden%22:false},{%22type%22:%22wms%22,%22title%22:%22Reg01012019_g_WGS840%22,%22style%22:%22geosolutions:italian_regions___f6084f90-9c3d-11eb-942e-edbf4e249c97%22,%22name%22:%22geosolutions:Reg01012019_g_WGS840%22,%22url%22:%22https://gs-stable.geo-solutions.it/geoserver/wms%22,%22params%22:{%22cql_filter%22:%22DEN_REG='Toscana'%22},%22visibility%22:true},{%22type%22:%22wms%22,%22title%22:%22points%22,%22style%22:%22geosolutions:base___6dddfdd0-9d33-11eb-a98d-2719389c9f56%22,%22name%22:%22geosolutions:points%22,%22url%22:%22https://gs-stable.geo-solutions.it/geoserver/wms%22,%22visibility%22:true}]}} 
```

**Comment by landryb** [comment]
> This parameters can be anyway managed also via GET. Below an example:

i know that, just wanted to make sure "missing" parameters would be available via GET too, like the ones already supported... and yes i'm aware of the GET size limitations :) but sometimes you only want to do a single operation/add/zoom, you dont plan to override *all* params, in that case GET is simpler.

**Comment by jusabatier** [comment]
For us the GET parameters allows to quickly provide maps for external website that are embeded in iframes.

Is it possible to have the layer's "url" parameter binded to "/geoserver/ows" (the instance one) if not provided ?
I think this is a good way to shorten the query parameter by not provide it for each layers.

Also in your example, some params are provided twice like "center" and "zoom".

For GET request we need to have the possibility to short the URL.
Can it work with an URL like that : 

> https%3A%2F%2Fdev-mapstore.geosolutionsgroup.com%2Fmapstore%2F%23%2Fviewer%2Fopenlayers%2F38982%3Ffeatureinfo%3D%7B%22lat%22%3A%2043.559%2C%20%22lng%22%3A%2011.036%2C%20%22filterNameList%22%3A%20%5B%5D%7D%26map%3D%7B%22version%22%3A2%2C%22map%22%3A%7B%22center%22%3A%7B%22x%22%3A15.535581676494019%2C%22y%22%3A44.830249175294%7D%2C%22zoom%22%3A5%2C%22layers%22%3A%5B%7B%22type%22%3A%22wms%22%2C%22title%22%3A%22Reg01012019_g_WGS840%22%2C%22name%22%3A%22geosolutions%3AReg01012019_g_WGS840%22%2C%22params%22%3A%7B%22cql_filter%22%3A%22DEN_REG%3D%27Toscana%27%22%7D%7D%2C%7B%22type%22%3A%22wms%22%2C%22title%22%3A%22points%22%2C%22name%22%3A%22geosolutions%3Apoints%22%7D%5D%7D%7D

That assume the values not provided are the default of the used context ?

**Comment by tdipisa** [comment]
@jusabatier 

> For us the GET parameters allows to quickly provide maps for external website that are embeded in iframes.
> 
> Is it possible to have the layer's "url" parameter binded to "/geoserver/ows" (the instance one) if not provided ? I think this is a good way to shorten the query parameter by not provide it for each layers.

The configuration mechanisms are the usual ones: the layer URL (relative or absolute) must be provided.
 
> Also in your example, some params are provided twice like "center" and "zoom".

Yes because it wants to be an example of how parameters have priorities to others if specified.
 
> For GET request we need to have the possibility to short the URL. Can it work with an URL like that :
> 
> > https%3A%2F%2Fdev-mapstore.geosolutionsgroup.com%2Fmapstore%2F%23%2Fviewer%2Fopenlayers%2F38982%3Ffeatureinfo%3D%7B%22lat%22%3A%2043.559%2C%20%22lng%22%3A%2011.036%2C%20%22filterNameList%22%3A%20%5B%5D%7D%26map%3D%7B%22version%22%3A2%2C%22map%22%3A%7B%22center%22%3A%7B%22x%22%3A15.535581676494019%2C%22y%22%3A44.830249175294%7D%2C%22zoom%22%3A5%2C%22layers%22%3A%5B%7B%22type%22%3A%22wms%22%2C%22title%22%3A%22Reg01012019_g_WGS840%22%2C%22name%22%3A%22geosolutions%3AReg01012019_g_WGS840%22%2C%22params%22%3A%7B%22cql_filter%22%3A%22DEN_REG%3D%27Toscana%27%22%7D%7D%2C%7B%22type%22%3A%22wms%22%2C%22title%22%3A%22points%22%2C%22name%22%3A%22geosolutions%3Apoints%22%7D%5D%7D%7D
> 
> That assume the values not provided are the default of the used context?

Yes. With the current mechanism you are able to selectively override only properties of the resource JSON you need.

**Comment by jusabatier** [comment]
`The configuration mechanisms are the usual ones: the layer URL (relative or absolute) must be provided.`

I know that but is it possible that for georchestra fork, if not provided, it's binded to the instance's one ?
It allow to short the layer part of the URL when we need a GET call with local layers only.
