### ISSUE TITLE
Review Mobile Layout

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#803]
I believe we still have too many things on the map, we need to make the mobile view much simpler on smaller devicer (phones), maybe more complex on larger devices (tablets).

- [ ] I think we need to get rid of the history buttons, at least on the phone

**Comment by Gnafu** [comment]
Please do not use "Request Desktop site" flag on the mobile browser, many of this point are already covered in the mobile configuration.

**Comment by simboss** [comment]
Updated my initial issue, my fault.

We can discuss about the history buttons though.

**Comment by simboss** [comment]
After discussion, let's remove the history button.

See #862
