### ISSUE TITLE
Extend the map viewer query parameter API (BackEnd)

### ISSUE THREAD

**Issue by taba90** [geosolutions-it/MapStore2#8034]
Any POST request via back-end to a given sub-service will be handled by the back-end, that stores in sessionStorage the params of the request and redirects to the correct page.

e.g. `POST /mapstore/setParams`
body:

```
{
"map":{....},
"center":{...},
"bbox":{...},
"featureinfo":{...},
"actions":{...},
"page":"#/viewer/openlayers/config"
}
```
page=#/viewer/openlayers/config
This saves in sessionStorage and object queryParams with all the arguments and redirects to the page passed as parameter. These argument will be used in the exact same way as they was received from the query string.

The page will read the sessionStorage and simply use the parameter as they was coming from the query string to use them, and delete them after reading.

**Comment by taba90** [comment]
working on this

**Comment by taba90** [comment]
made a pr https://github.com/geosolutions-it/MapStore2/pull/8038 targeting master

**Comment by tdipisa** [comment]
@taba90 thank you
