### ISSUE TITLE
Some dependencies to amend for 2022.01.01

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#8048]
## Description

There are some backend dependencies to amend in master and stable branch (2022.01.xx) for the next minor release. The following ones should be used:

dao-1.3.0
dao-hibernate-1.3.0
search-1.3.0
search-hibernate-1.3.0
search-jpa-hibernate-1.3.0

Also the documentation [here](https://mapstore.readthedocs.io/en/latest/developer-guide/mapstore-migration-guide/#migration-from-20210200-to-20220100) need to be fixed for some small typos: -SNAPSHOT versions texts should be removed.

**We have to also release mapstore services 1.3.1 due to #8034**

**We have to also release geostore 1.8.1 due to [#281](https://github.com/geosolutions-it/internal/issues/281)** 

## Other useful information
https://github.com/geosolutions-it/MapStore2/wiki/MapStore-Releases-2022

**Comment by taba90** [comment]
For the listed dependencies there is no 1.3.0 but only a SNAPSHOT. To use an official release we would have to downgrade the library and this is not the desired choice.
