### ISSUE TITLE
WPS exports fail for all file formats except CSV - GeoServer - Workaround

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/MapStore2#8052]

**Comment by nmco** [comment]
This issue is for the quick fix, @taba90 can you provide pointers to @fostash here?

**Comment by taba90** [comment]
[Here ](https://github.com/geoserver/geoserver/blob/254bed97a1c41adaa4d74cdd817ffecbbc7d3280/src/main/src/main/java/org/geoserver/ows/LanguageURLMangler.java#L26) instead of iterating over the HttpServletRequest params we should use the rawKvp of the ows Request object (Request.get().getRawKvp()) that provides a case insensitive map detached from the httpServletRequest parameters.

**Comment by nmco** [comment]
@fostash  please link the JIRA ticket and PR.

**Comment by fostash** [comment]
[![GEOS-10454](https://badgen.net/badge/JIRA/GEOS-10454/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10454)

PR: https://github.com/geoserver/geoserver/pull/5790

**Comment by aaime** [comment]
/me sits back and waits for Marco's epic explanation on how INSPIRE choice of param names really sucked :-D

**Comment by taba90** [comment]
@nmco yes we have two different parameters:
- **AcceptLanguages** is the one coming from OGC OWS 2.0 specifigication used for support capabilities in different languages.
- **Language** is the parameter defined by INSPIRE specifications for internationalized content in capabilities. While AcceptLanguages  support multiple params and use ISO codes the INSPIRE one uses IETF language tags.
- **Language** as a parameter is also used for internazionalization for labels and getLegendGraphic and uses ISO codes. This is why everything is translated to Language parameter: outside the capabilities context the AcceptLanguages param doesn't do anything. For i18n support over legends and labels the **Language** parameter is the only one used. This second Language param used for labels and legends is not coming from any specs as far as I know but it happened to have the same name of the INSPIRE Language parameter for capabilities.

Here the relevant documentation:
- [AcceptedLanguages] (https://docs.geoserver.org/latest/en/user/services/internationalization/index.html)
- [INSPIRE Language](https://docs.geoserver.org/stable/en/user/extensions/inspire/using.html#internationalization-support)
- [Language param for SLD](https://docs.geoserver.org/latest/en/user/styling/sld/language.html)

**Comment by aaime** [comment]
To be fair, in capabilities request OWS requires the usage of "AcceptVersions" while all other calls use "Version". What's odd about inspire is that language names are not ISO codes, but its own thing (e..g, "ger" instead of "de").

**Comment by taba90** [comment]
merged on main. details on jira ticket https://osgeo-org.atlassian.net/browse/GEOS-10454

**Comment by fostash** [comment]
Start worked on it
PR: https://github.com/geoserver/geoserver/pull/5832

**Comment by nmco** [comment]
Can you have a look at the backports @taba90 ?

**Comment by giohappy** [comment]
@taba90 I see this has been [backported to GS 2.20.x](https://github.com/geoserver/geoserver/pull/5832) the 28th April so I suppose that GS 2.20.4, which was release April 11th doesn't contain the fix, right?

**Comment by taba90** [comment]
@giohappy i confirm that is not on 2.20.4
