### ISSUE TITLE
3dtiles layer wrongly overlayed on top of custom terrain

### ISSUE THREAD

**Issue by landryb** [geosolutions-it/MapStore2#8058]
## Description
following up to #7924, testing a 3d tiles layer on top of a custom terrain provider the overlaying looks wrong:

![image](https://user-images.githubusercontent.com/3421760/161950803-6d3a8ec9-2254-445c-a122-12a4253d00ac.png)

## How to reproduce

- configure a custom terrain using this in localConfig.json:
```
          "terrainProvider": {
              "type": "cesium",
              "url": "https://3d.craig.fr/terrain",
              "requestVertexNormals": true
          }
```
- load 3dtiles layer from https://3d.craig.fr/datasets/Aurillac/3dtiles/tileset.json

*Expected Result*

it should display fine like below:
![image](https://user-images.githubusercontent.com/3421760/161951488-3c0277b7-605c-4f5e-b4f0-620dc886442d.png)

this screenshot comes from https://3d.craig.fr/viewer/ which is a simple cesium viewer displaying our 3dtiles on top of our own terrain server, select 'Aurillac' layer in the 3rd menu on the left.

*Current Result*

the terrain/osm background layer comes on top of the 3dtiles in some areas.

if using the default `"ellipsoid"` terrain (without another layer configured as BIL terrain provider), then the 3dtiles layer *floats* above the ground.

![image](https://user-images.githubusercontent.com/3421760/161952823-248debb9-80d6-4938-a60a-d3454f13b023.png)

## Other useful information

something wrong in the z-index for the 3dtiles layer ?

**Comment by landryb** [comment]
changing the layer ordering in the layertree to put a WMS/WMTS layer on top/below the 3d tiles layer (to force updating the z-index/cesium layer order?) doesn't change anything wrt this strange display behaviour. (in the screenshot below, 'test' is the 3dtiles layer)

![image](https://user-images.githubusercontent.com/3421760/161957113-033e2440-2f72-40f8-bf48-44e442e6c94e.png)

**Comment by tdipisa** [comment]
@landryb Does the terrain you are using have the same elevation profile as the 3D tile you are loading?
If not, in layer setting/display tab you have also the ability to tune the height offset
![image](https://user-images.githubusercontent.com/1280027/162007440-7a8fe6d4-f51d-4a8f-aefd-f151e9fd6a8f.png)

**Comment by landryb** [comment]
i know the same combination of terrain + 3dtiles layer in plain cesium works, as seen in the screenshot above - my expectation would be to have the same result in ms2, without fiddling with offsets/etc.

as for the height offset, nice trick i hadnt noticed it - in that tileset case, adding a ~15m offset sortof helps, but then the 3d layer floats above the ground..

**Comment by allyoucanmap** [comment]
> this screenshot comes from https://3d.craig.fr/viewer/ which is a simple cesium viewer displaying our 3dtiles on top of our own terrain server, select 'Aurillac' layer in the 3rd menu on the left.

@landryb @tdipisa 

The Cesium viewer in MapStore is setting the property  [depthTestAgainstTerrain](https://cesium.com/learn/cesiumjs/ref-doc/Globe.html?classFilter=globe#depthTestAgainstTerrain)  to **true** by default. If this property is false the 3d tiles will be always visible even if behind a mountain

your viewer with `depthTestAgainstTerrain` equal to **false**

https://user-images.githubusercontent.com/19175505/162421344-3c1e5ae6-ae25-47e9-ac00-6286fff4c213.mp4

mapstore viewer with `depthTestAgainstTerrain` equal to **true**

https://user-images.githubusercontent.com/19175505/162421665-d759ad43-fae3-4995-97f6-247192594347.mp4

you can disable the depthTestAgainstTerrain by setting it to false in the configuration with

```diff
"defaultMapOptions": {
  "cesium": {
      "flyTo": true,
      "navigationTools": true,
+     "depthTestAgainstTerrain": false,
      "terrainProvider": {
        "type": "cesium",
        "url": "https://3d.craig.fr/terrain",
        "requestVertexNormals": true
      }
  },
  "floatingIdentifyDelay": 1000
},
```

mapstore with depthTestAgainstTerrain set to false

![image](https://user-images.githubusercontent.com/19175505/162421926-bf6bcec2-0035-4453-a29f-8a81beef41c4.png)

we are currently working on the doc issue to add this info https://github.com/geosolutions-it/MapStore2/issues/8012

> changing the layer ordering in the layertree to put a WMS/WMTS layer on top/below the 3d tiles layer (to force updating the z-index/cesium layer order?) doesn't change anything wrt this strange display behaviour. (in the screenshot below, 'test' is the 3dtiles layer)

The layer order has effect only on the imagery layer rendered on the surface while all the other 3D primitive featurues will be displayed based on their z position including the 3d tiles feartures

**Comment by landryb** [comment]
aah, perfect, that totally makes sense now. I knew there was some kind of related setting somewhere in cesium, i just couldnt put my finger on it/hadn't figured out how to pass it to cesium via ms2 config.

I guess the DTM used conflicts too much with the relief/height used inside the 3dtiles, and setting `"depthTestAgainstTerrain": false` in localConfig.json definitely fixes it. I admit it's a bit strange to still see the tileset when the camera is behind another relief (side effect) but at least it's properly displayed when flying into it.

Many thanks @allyoucanmap for your hindsight, that's much clearer now (and much appreciated :) !
