### ISSUE TITLE
Sidebar for MS Options 

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#8086]
## Description

There is the need to access the option menu to open other tools contextually (e.g. when the side panel is opened). At the moment the Option button is covered when a side panel is opened so that certain operations are not possible. We need a way to place the menu option somewhere else and properly manage possible conflicts when certain tools are opened together (eg. tools that interacts with the map) 

## Acceptance criteria

The general aims are: 

- [ ] Remove the burger menu, with other buttons like Home (and the Login one in MS) to move all of them, along with all menu options, in a vertical side toolbar

![2022_02_18_16_42_05_2Window](https://user-images.githubusercontent.com/1280027/154733906-1e324875-5057-4c3c-b401-c1da4d46ab3a.png)

- [ ] Reduce the size of side panels that opens on the right to make them smaller (around width: 550px) and with a smaller header

- [ ] The Search bar will move to the left when a right-side panel open, to be collapsed in a spyglass button and be opened when that button is clicked. The Search bar is opened by default when there's no panels opened on the right

![2022_02_18_16_42_05_Window](https://user-images.githubusercontent.com/1280027/154733865-b9441a41-79b6-456f-98b5-1845df69bb4e.png)

- [ ] As far as the annotation panel is concerned, it will be moved on the left side to be more "driven" by the TOC: a new button ("Create annotations") in the TOC toolbar will open the annotation panel on the left. When annotations have been created (the related layer is present in TOC with the others) an annotation pencil icon in the TOC toolbar ("Edit annotations") will allow to open the annotation panel again for editing purposes as soon as the annotation layer is selected in TOC

![image](https://user-images.githubusercontent.com/1280027/154732614-29055cd0-cf99-4b63-8623-a4a6ce8cdca0.png)

![image](https://user-images.githubusercontent.com/1280027/154733790-e20f9dcf-9f1d-4849-8d00-54781c7469b1.png)

- [ ] The DrawSupport will be also reviewed a bit to ensure there will be no conflicts between tools interacting with the map using a proper policy

- [ ] The printing tool will provide an option to include additional layers (eg. selection of parcels) in the  final print

- [ ] The new sidebar menu should be obviously available also in the app context wizard to be included in a context in the same way of the current BurgerMenu

- [ ] We have to manage someway the migration from BurgerMenu to this new menu (e.g. existing contexts). What we have to do for existing contexts where the burger menu is used?

**Comment by alexander-fedorenko** [comment]
Some statements after demo call with @tdipisa
Please correct me if something is wrong. 

1. Sidebar behavior when there are more elements than sidebar can fit:
There will be a separate button at the bottom of sidebar that will "hide" items that sidebar can't fit. Click on the button will list remaining tools in the dropdown (just like in BurgerMenu or Login menu).
Active tool will reflect its state by changing tool button style into primary (blue-white colored).
Last activated tool will always be moved from dropdown to the main list of tools, to the place right before that extra button with dropdown.

2. Sidebar will allow to open only one tool that implements dock panel. E.g. if MetadataExplorer is active and user clicks on Details - MetadataExplorer will be closed and Details dock will be open. Identify tool is exception and it will always appear above any active dock panel.

3. Search plugin behavior.
Search plugin will track how much empty space is available for search input. If available space (window width - right sidebar - right dock - left dock) is not enough - it will fall-back into the state when it's available as a toggle. Existing behavior will also stay - search input will fall-back into toggle-button mode when total window width is less or equal 768px.

**Comment by landryb** [comment]
all this looks great - one thing i havent seen mentioned is the featuregrid/attribute table bottom panel interactions - thinking specifically at interaction issues like georchestra/mapstore2-georchestra/#360

> 2\. Identify tool is exception and it will always appear above any active dock panel.

does that mean using the identify tool on layer X will stop hiding an opened attribute table for layer Y ?

**Comment by tdipisa** [comment]
> all this looks great - one thing i havent seen mentioned is the featuregrid/attribute table bottom panel interactions - thinking specifically at interaction issues like georchestra/mapstore2-georchestra/#360
> 
> > 2. Identify tool is exception and it will always appear above any active dock panel.
> 
> does that mean using the identify tool on layer X will stop hiding an opened attribute table for layer Y ?

This behavior will remain the same as before. This is not part of the development planned and requested for this task.
