### ISSUE TITLE
3D Tiles Styling with filter

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#8087]
The filter for the 3D Tiles style does not works as expected.

**How to reproduce**
- Open [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/38821)
- Select the layer enabled
- Click on settings > On Style tab enter this code :
```
{
    "type": "3dtiles",
    // ...
    "style": {
        "format": "3dtiles",
        "body": {
            "color": {
                "conditions": [
                    [
                        "((!(${height} === undefined || ${height} === null || isNaN(${height})) && ${height} < 5))",
                        "color('#f0f9e8', 1)"
                    ],
                    [
                        "((!(${height} === undefined || ${height} === null || isNaN(${height})) && ${height} < 10))",
                        "color('#ccebc5', 1)"
                    ],
                    [
                        "((!(${height} === undefined || ${height} === null || isNaN(${height})) && ${height} < 15))",
                        "color('#a8ddb5', 1)"
                    ],
                    [
                        "((!(${height} === undefined || ${height} === null || isNaN(${height})) && ${height} < 20))",
                        "color('#7bccc4', 1)"
                    ],
                    [
                        "((!(${height} === undefined || ${height} === null || isNaN(${height})) && ${height} < 25))",
                        "color('#43a2ca', 1)"
                    ],
                    [
                        true,
                        "color('#3879ff', 0.12)"
                    ]
                ]
            },
            "meta": {
                "title": "'3D Tile Style'",
                "names": "'height < 5,height < 10,height < 15,height < 20,height < 25,others'"
            }
        },
        "metadata": {
            "editorType": "visual",
            "styleJSON": "{\"name\":\"3D Tile Style\",\"rules\":[{\"name\":\"others\",\"ruleId\":\"39298070-b031-11ec-927f-2911a3e94ad4\",\"symbolizers\":[{\"kind\":\"Fill\",\"color\":\"#3879ff\",\"fillOpacity\":0.12,\"symbolizerId\":\"39298071-b031-11ec-927f-2911a3e94ad4\"}]},{\"name\":\"height < 25\",\"ruleId\":\"25c4e6f0-b031-11ec-927f-2911a3e94ad4\",\"symbolizers\":[{\"kind\":\"Fill\",\"color\":\"#43a2ca\",\"fillOpacity\":1,\"symbolizerId\":\"25c50e00-b031-11ec-927f-2911a3e94ad4\"}],\"filter\":{\"filterFields\":[{\"rowId\":1648648576697,\"groupId\":1,\"attribute\":\"height\",\"operator\":\"<\",\"value\":25,\"type\":\"number\",\"fieldOptions\":{\"valuesCount\":0,\"currentPage\":1},\"exception\":null}],\"groupFields\":[{\"id\":1,\"logic\":\"OR\",\"index\":0}]}},{\"name\":\"height < 20\",\"ruleId\":\"116c5080-b031-11ec-927f-2911a3e94ad4\",\"symbolizers\":[{\"kind\":\"Fill\",\"color\":\"#7bccc4\",\"fillOpacity\":1,\"symbolizerId\":\"116c5081-b031-11ec-927f-2911a3e94ad4\"}],\"filter\":{\"filterFields\":[{\"rowId\":1648648539186,\"groupId\":1,\"attribute\":\"height\",\"operator\":\"<\",\"value\":20,\"type\":\"number\",\"fieldOptions\":{\"valuesCount\":0,\"currentPage\":1},\"exception\":null}],\"groupFields\":[{\"id\":1,\"logic\":\"OR\",\"index\":0}]}},{\"name\":\"height < 15\",\"ruleId\":\"e37cf9e0-b030-11ec-927f-2911a3e94ad4\",\"symbolizers\":[{\"kind\":\"Fill\",\"color\":\"#a8ddb5\",\"fillOpacity\":1,\"symbolizerId\":\"e37cf9e1-b030-11ec-927f-2911a3e94ad4\"}],\"filter\":{\"filterFields\":[{\"rowId\":1648648461084,\"groupId\":1,\"attribute\":\"height\",\"operator\":\"<\",\"value\":15,\"type\":\"number\",\"fieldOptions\":{\"valuesCount\":0,\"currentPage\":1},\"exception\":null}],\"groupFields\":[{\"id\":1,\"logic\":\"OR\",\"index\":0}]}},{\"filter\":{\"filterFields\":[{\"rowId\":1648648217777,\"groupId\":1,\"attribute\":\"height\",\"operator\":\"<\",\"value\":10,\"type\":\"number\",\"fieldOptions\":{\"valuesCount\":0,\"currentPage\":1},\"exception\":null}],\"groupFields\":[{\"id\":1,\"logic\":\"OR\",\"index\":0}]},\"name\":\"height < 10\",\"symbolizers\":[{\"kind\":\"Fill\",\"color\":\"#ccebc5\",\"fillOpacity\":1,\"symbolizerId\":\"5070c7d1-b030-11ec-927f-2911a3e94ad4\"}],\"ruleId\":\"5070c7d0-b030-11ec-927f-2911a3e94ad4\"},{\"name\":\"height < 5\",\"ruleId\":\"6df8e670-b030-11ec-927f-2911a3e94ad4\",\"symbolizers\":[{\"kind\":\"Fill\",\"color\":\"#f0f9e8\",\"fillOpacity\":1,\"symbolizerId\":\"6df8e671-b030-11ec-927f-2911a3e94ad4\"}],\"filter\":{\"filterFields\":[{\"rowId\":1648648265523,\"groupId\":1,\"attribute\":\"height\",\"operator\":\"<\",\"value\":5,\"type\":\"number\",\"fieldOptions\":{\"valuesCount\":0,\"currentPage\":1},\"exception\":null}],\"groupFields\":[{\"id\":1,\"logic\":\"OR\",\"index\":0}]}}]}"
        }
    },
    // ...
}
```

*Current Result*
The style is not valid
![filter.png](https://images.zenhubusercontent.com/5da5b30f66de7b0001e4e77c/51d72bf5-7267-4bdb-bf52-6638ecd19b9f)

**Comment by allyoucanmap** [comment]
@ElenaGallo the actual style than you can apply in the textarea editor is only the body property of the layer.style configuration (the code you are sharing is a layer configuration). you can see here the specification https://github.com/CesiumGS/3d-tiles/tree/1.0/specification/Styling#overview

```js
{
            "color": {
                "conditions": [
                    [
                        "((!(${height} === undefined || ${height} === null || isNaN(${height})) && ${height} < 5))",
                        "color('#f0f9e8', 1)"
                    ],
                    [
                        "((!(${height} === undefined || ${height} === null || isNaN(${height})) && ${height} < 10))",
                        "color('#ccebc5', 1)"
                    ],
                    [
                        "((!(${height} === undefined || ${height} === null || isNaN(${height})) && ${height} < 15))",
                        "color('#a8ddb5', 1)"
                    ],
                    [
                        "((!(${height} === undefined || ${height} === null || isNaN(${height})) && ${height} < 20))",
                        "color('#7bccc4', 1)"
                    ],
                    [
                        "((!(${height} === undefined || ${height} === null || isNaN(${height})) && ${height} < 25))",
                        "color('#43a2ca', 1)"
                    ],
                    [
                        true,
                        "color('#3879ff', 0.12)"
                    ]
                ]
            },
            "meta": {
                "title": "'3D Tile Style'",
                "names": "'height < 5,height < 10,height < 15,height < 20,height < 25,others'"
            }
        }
```

and a json cannot contain comments

![image](https://user-images.githubusercontent.com/19175505/163164710-d251d012-758a-42ec-9a60-6c34fa2501f1.png)

**Comment by tdipisa** [comment]
@allyoucanmap this is what I saw

![image](https://user-images.githubusercontent.com/1280027/163165598-26596c49-51bc-4b11-a449-76d3aa8d2008.png)

With the height properti it is working with the name it no.

I'm trying with [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/cesium/38821) layer **_aa5_**

**Comment by tdipisa** [comment]
> @ElenaGallo the actual style than you can apply in the textarea editor is only the body property of the layer.style configuration (the code you are sharing is a layer configuration). you can see here the specification https://github.com/CesiumGS/3d-tiles/tree/1.0/specification/Styling#overview
> 
> ```js
> {
>             "color": {
>                 "conditions": [
>                     [
>                         "((!(${height} === undefined || ${height} === null || isNaN(${height})) && ${height} < 5))",
>                         "color('#f0f9e8', 1)"
>                     ],
>                     [
>                         "((!(${height} === undefined || ${height} === null || isNaN(${height})) && ${height} < 10))",
>                         "color('#ccebc5', 1)"
>                     ],
>                     [
>                         "((!(${height} === undefined || ${height} === null || isNaN(${height})) && ${height} < 15))",
>                         "color('#a8ddb5', 1)"
>                     ],
>                     [
>                         "((!(${height} === undefined || ${height} === null || isNaN(${height})) && ${height} < 20))",
>                         "color('#7bccc4', 1)"
>                     ],
>                     [
>                         "((!(${height} === undefined || ${height} === null || isNaN(${height})) && ${height} < 25))",
>                         "color('#43a2ca', 1)"
>                     ],
>                     [
>                         true,
>                         "color('#3879ff', 0.12)"
>                     ]
>                 ]
>             },
>             "meta": {
>                 "title": "'3D Tile Style'",
>                 "names": "'height < 5,height < 10,height < 15,height < 20,height < 25,others'"
>             }
>         }
> ```
> 
> and a json cannot contain comments
> 
> ![image](https://user-images.githubusercontent.com/19175505/163164710-d251d012-758a-42ec-9a60-6c34fa2501f1.png)

@allyoucanmap is this reported in our online documentation?

**Comment by allyoucanmap** [comment]
> @allyoucanmap is this reported in our online documentation? If not @ElenaGallo please include it in the related user guide.

This is what I added https://github.com/geosolutions-it/MapStore2/blob/master/docs/developer-guide/maps-configuration.md#3d-tiles

![image](https://user-images.githubusercontent.com/19175505/163167344-90ddfd20-7407-4d67-a487-91a1aeb4a782.png)

**Comment by tdipisa** [comment]
@ElenaGallo please refer to it in your guide ok?

**Comment by allyoucanmap** [comment]
> @allyoucanmap this is what I saw
> 
> ![image](https://user-images.githubusercontent.com/1280027/163165598-26596c49-51bc-4b11-a449-76d3aa8d2008.png)
> 
> With the _height_ property it is working while with the _name_ one no.
> 
> I'm trying with [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/cesium/38821) layer **_aa5_**

@tdipisa I confirm that there are some issue in the string filter conversion

**Comment by tdipisa** [comment]
@allyoucanmap we have to schedule a fix for this during next days.
