### ISSUE TITLE
Mapstore stable version has outdated resources pointing to demo geoserver

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#8088]
## Description

list here all the resources that uses https://demo.geo-solutions.it/geoserver/ as geoserver

list:
- https://mapstore.geosolutionsgroup.com/mapstore/#/dashboard/5728
- https://mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/6200
- https://mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/4093
- https://mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/1740
-

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe:

## Other useful information

after we have listed them all here we can decide what to delete and what to update
eventually we can check also other instances (DEV, QA)

**Comment by tdipisa** [comment]
@ElenaGallo can you please do a quick check tour before the release 2022.01.02?

**Comment by ElenaGallo** [comment]
Hi @MV88 @tdipisa, the list of maps is in the issue above.

**Comment by tdipisa** [comment]
@ElenaGallo please fix involved maps by updating the catalog source using GS-STABLE and/or re-adding layers in TOC from it. If layers are missing in GS-STABLE and there aren't other contents, please delete the map.

**Comment by ElenaGallo** [comment]
The maps and dashboards are update with gs-stable layers.

**Comment by tdipisa** [comment]
good, feel free to close at your convenience.
