### ISSUE TITLE
Support of Multiple Terrains in Cesium

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#8101]
## Description

It is not currently possible to select different Terrain layers in a single map.  The current terrain support is based on a global configuration used for all 3D maps or context maps. It should be possible to define multiple Terrain layers to switch between them in a single Cesium map. 

## Acceptance criteria

- [x] The work should be based on the DDS/BIL support using raster data from GeoServer. 
- [x] Include a new layer type for Terrain layers
- [x] Investigate on the configuration design for a future UI Terrain Switcher 
- [x] Check positioning behaviours of entities or 3D tiles over a terrain.
- [x] Check configuration to apply different terrain per context

**Comment by landryb** [comment]
> * The work should be based on the DDS/BIL support using raster data from GeoServer.

are you also planning support for `Cesium.CesiumTerrainProvider` ? it works just fine and is the 'native' terrain provider in cesium.. and as such, it's *much* faster than the DDS/BIL hack used by GeoserverTerrainProvider.

granted, one then needs to self-generate a terrain cache with ctb-tile (or use a 3rd-party provider?), its not as easy as dropping a DEM raster in geoserver, but it's much much better.

**Comment by tdipisa** [comment]
@landryb 

>are you also planning support for Cesium.CesiumTerrainProvider ?

Yes, we are doing it too.
