### ISSUE TITLE
Vlaanderen Dev Geoserver cannot communicate with Postgres

### ISSUE THREAD

**Issue by ale-cristofori** [geosolutions-it/MapStore2#8115]
## Description
In order to start the FE development of new feature of the timeline intervals we are using a dev stack (postgres + Geoserver + MapStore) deployed on a dedicated VM, to include the latest BE changes for the FE to implement the features described

## How to reproduce

-  
- 

*Expected Result*

*Current Result*

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by randomorder** [comment]
waiting for feedback from @ale-cristofori 
![image](https://user-images.githubusercontent.com/5264230/164176383-179d5d69-fbad-4eac-bd9c-cc92a1387e9d.png)

**Comment by ale-cristofori** [comment]
@randomorder and @tdipisa 

I testes this morning with changes suggested and it is working as expected. The issue can be closed.

![recording_1](https://user-images.githubusercontent.com/14953970/164179007-e29a4032-84a7-45c5-b63a-3dfb6ff1726c.gif)
