### ISSUE TITLE
GetCapabilities request performed twice

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#8137]
## Description

When you add a new catalog source (eg. WMS) a GetCapabilities request is performed as for health/status check before adding the source to the catalog source. Leaving the default options, when saving the new source you have to click on search and the GetCapabilities request is performed again. We should improve this if possible.

![capabilities.gif](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/952e07bc-8d8f-4dce-b082-d68748ff538b)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by dsuren1** [comment]
@tdipisa 
Just to be clear, on adding new catalog service `GetCapabilities` testservice call is applicable only for **WMTS** & **WMS**. So improving calls of this catalog service alone is fine as part of this issue. Kindly let me know if these needs to be extended to other catalog services as well. Thanks!
