### ISSUE TITLE
Review map markers management

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#815]
Investigate svg icons usage.
The main goal of this review is to ease the marker layers customization.

**Comment by tdipisa** [comment]
We are working now on implementing significative improvements for the annotations tool including the svg support. The work is currently in progress into the [c125_annotations](https://github.com/geosolutions-it/MapStore2/tree/c125_annotations) branch and it will be available in next minor release probably. We can close this issue.
