### ISSUE TITLE
measure tool window goes below layertree pane

### ISSUE THREAD

**Issue by landryb** [geosolutions-it/MapStore2#8151]
## Description

minor issue but confusing for users

## How to reproduce

-  go to https://georchestra.geo-solutions.it/mapstore/#/
-  open measure tool
- open layertree pane
- move measure tool to the left

*Expected Result*

measure tool window should be above layertree as its floating

*Current Result*

it's displayed below the layertree
![image](https://user-images.githubusercontent.com/3421760/165951081-5bc43b42-841d-418f-9245-fe38a894fd2a.png)

**Comment by barema4** [comment]
Would it be better to display the measure tool also on top of the panes on the right @MV88  @tdipisa  @offtherailz

**Comment by MV88** [comment]
@barema4 please update the PR  accordingly to this new AC

**Comment by barema4** [comment]
Alright , let me work on it.
