### ISSUE TITLE
OPEN ID - Design Keycloak security filter

### ISSUE THREAD

**Issue by ale-cristofori** [geosolutions-it/MapStore2#8189]
## Description
In order to have Keycloak to transpose in the authentication/authorization policies defined by the client in its workflow we need to define a filter configuration, for users, groups and roles. Such configuration will have to adaptable to Geostore and Keycloak. This task will require dev work on the MapStore backend library for the transposition of the configuration and the design of a dedicated Keycloak filter to be used in the MapStore configuration.

## Acceptance criteria

- [x]  Keycloak will be able to implement the filter configuration as actual authentication/authorization policies.   
- [x]  The filter will be configurable by simply passing to it the JSON file available once the client configuration is done

**Comment by taba90** [comment]
opened pr on master

**Comment by ale-cristofori** [comment]
@taba90 is this is the associated PR https://github.com/geosolutions-it/geostore/pull/282
could this be closed now?

**Comment by ale-cristofori** [comment]
As of today 04/08/2022, the testing of this feature on our dev environment is dependent on time constraints dictated by our resources availability, estimation on the setup of the testing environment has been given by @offtherailz, we are now waiting for any free MapStore resource who can work on this.

see https://github.com/geosolutions-it/MapStore2/issues/8429

**Comment by ElenaGallo** [comment]
The Keycloak OPEN ID has been tested on client istance.
