### ISSUE TITLE
OPEN ID - Keycloak roles management

### ISSUE THREAD

**Issue by ale-cristofori** [geosolutions-it/MapStore2#8190]
## Description
Keycloak will be able to transpose the roles provided by the OPEN ID authentication provider to actual MapStore roles, in order to do so, Keycloak will have to correctly identify the roles defined by the provider and consistently map those to roles that will be recognized by MapStore  (MS_ROLE_ADMIN, MS_ROLE_USER, MS_GROUP_* …)

**Comment by taba90** [comment]
working on this

**Comment by ale-cristofori** [comment]
@taba90  thanks for the update

**Comment by ale-cristofori** [comment]
@taba90, any development on this? I would like to inform client to the current progress of the situation
