### ISSUE TITLE
Vlaanderen PhotoViewer custom extension - invoke ConfigUtils.loadConfiguration 

### ISSUE THREAD

**Issue by ale-cristofori** [geosolutions-it/MapStore2#8198]
The client developed their own custom extension in their own git hub repo
[repo here](https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/cc-dmow-fietsgis-temp). Branch: "photoviewer". 

Full support ticket history [here](https://github.com/geosolutions-it/support/issues/2049)

They are experiencing a config mismatch between their Map Store `localConfig.json` settings and those required by the extesion which isn't able to load their custom `acceess_token` param, needed to authorise layer read permissions for the extension. A known limitation of Map Store extension is that `For now, components retrieved from MapStore (using the import) will be a copy of the existing ones, so calling methods directly on some files imported from MapStore will not have any effect` see 
https://github.com/geosolutions-it/MapStoreExtension#limitations

As @offtherailz pointed out in [this support comment](https://github.com/geosolutions-it/support/issues/2049#issuecomment-1124951617). The solution could be to call `ConfigUtils.loadConfiguration` in the extension code, on startup. 

The client is asking us to put in place such fix in their own source code.
No release for this issue is needed as it has to be done on the client codebase.

**Comment by offtherailz** [comment]
I think you opened this issue on the wrong repository @ale-cristofori 

You can trasfer it with the button "transfer issue" to the correct repository:
![image](https://user-images.githubusercontent.com/1279510/168813478-05d3e972-9374-46ba-8974-8bf3d212573a.png)

**Comment by ale-cristofori** [comment]
@offtherailz of course, which repository you think I should move this issue to ? support?

**Comment by offtherailz** [comment]
Maybe...

 there is already an issue created by the ticket, so I think you can simply continue on that thread, instead of creating a new issue

**Comment by ale-cristofori** [comment]
Closing this as requirements are already captured in https://github.com/geosolutions-it/support/issues/2049
