### ISSUE TITLE
Map Switcher for Map widget

### ISSUE THREAD

**Issue by dsuren1** [geosolutions-it/MapStore2#8211]
## Description

It is requested to provide a new feature to Map widgets in MapStore dashboards to allow switching from multiple maps in a single Map widgets.

## Acceptance criteria

- [ ] A kind of dropdown on top of the Map widgets allow to switch between different pre-configured maps
- [ ] It will be possible to activate this function and to select the list of maps during the Map widget creation/editing
- [ ] The connection capabilities with other widgets at map widget level will remain the same so that existing functionalities should continue working also when the widget switch over another map selected by the user

**Requirement**:
The Map Switcher will be implemented as part of the Map widget wizard, where there will be an option (maybe in the toolbar) to define a list maps (maps and maps coming from a context) through a map catalog with multiple selection.
If one or more maps are selected, the map switcher will appear automatically.

For what concern the Legend part, to be in line with the current MapStore functional logic widget oriented, the proposal is to enhance the current legend widget by improving its functionalities. The user will be able to control from the legend widget the layer visibility and opacity and it will be also possible to consult the legend as depicted below.

As soon as the user switch to another map using the Map Switcher above, the legend is updated accordingly.

![2022_04_27_16_42_46_Window](https://user-images.githubusercontent.com/1280027/165548733-daa5e556-b0e1-42ac-8844-a03f279df2d6.png)

The purpose of the screenshot above is to give an high level indication of what is requested in terms of functionalities, while it is requested to take into account also the following point.

1. Better decide which is the more convenient place (also for responsive aspects) to put the switcher (widget header/in overlay to the map)
2. Optimize the space as much as possible inside the legend (eg. placing the slider just below the layer title)
3. Include the ability to collapse/expand the legend

**Reference**: https://github.com/geosolutions-it/MapStore2-C040/issues/575

**Comment by dsuren1** [comment]
@tdipisa 
For widget creation of type `MapList`. Is this design approach fine, your thoughts?
![MapList](https://user-images.githubusercontent.com/26929983/169262414-341c8ade-4c45-4243-b9c6-dd71dd4b909d.png)

**Comment by tdipisa** [comment]
@dsuren1 the description of this issue need to be reviewed because it need to take into account what is effectively agreed [here](https://github.com/geosolutions-it/MapStore2-C040/issues/575#issuecomment-1111109756).

For what concern the comment above:
>For widget creation of type map with list. Kindly let me know if this design sits well with the requirement. Your thoughts?

What happens if the user select Empty map? Probably a quick call tomorrow is enough to clarify.

**Comment by dsuren1** [comment]
Hi @tdipisa 
I have added here a workflow including selection of `Empty Map` for map widget creation. Kindly have a look and let me know if it's okay to proceed with this workflow
[Dashboard - Map list widget (Workflow).pdf](https://github.com/geosolutions-it/MapStore2/files/8738123/Dashboard.-.Map.list.widget.Workflow.pdf)

**Comment by tdipisa** [comment]
@dsuren1 I think teh step 2 is not so clear to me. Please better articulate it to clarify if there is an intermediate step to assign only the map name before you can configure each map separately including the empty one.

**Comment by dsuren1** [comment]
@tdipisa 
I have amended step 2 [here](https://docs.google.com/document/d/1cRGdMZGDhFGSBVjxAkSG__Vyty9FAhIA2grVserH9Xc/edit). Kindly let me know if it's clear now

**Comment by tdipisa** [comment]
@dsuren1 make sense now. Please proceed.
