### ISSUE TITLE
WFS Identify in Cesium map and layer settings

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#8227]
## Description

The Identify function for WFS layers in available only in 2D map and it should be allowed also in Cesium map.

**Identify settings**
As part of this task it is requested to include the possibility to control the Identify type also for WFS layers (currently not possible even for the 2D map) from layer settings. Only the following 3 options should be allowed:

- DISABLE IDENTIFY
- PROPERTIES 
- TEMPLATE

From a preliminary investigation it should be only a matter to enable the UI part.

## Acceptance criteria

- [ ] Add support for Get feature info requests for wfs layers in cesium
- [ ] Make Identify settings available for this type of layer both 2d/3d
- [ ] make sure that the selection of the preferred feature info format is saved when you save the map and restored when you load it, i.e. (if you click on map it will use the saved info format for that layer)

## Other useful information

this needs to be backport in a dedicated branch for the update of genova project
https://github.com/geosolutions-it/MapStore2-C040/issues/582

**Comment by barema4** [comment]
@MV88 , What is the best way for retrieving feature info, should it be via the GetFeature in the `WFS.js` or GetFeatureInfo in the `Identify.jsx`

**Comment by MV88** [comment]
@barema4 the better approach would be to understand why the current GetFeature Request  was not working in cesium (returning always empty results)

Since this is a complicated topic I've investigated it a bit, and found that the geometry filter generated from here was wrong
https://github.com/geosolutions-it/MapStore2/blob/da9de13243223e709945bec5bdbedcfcea16ca8f/web/client/utils/IdentifyUtils.js#L33-L76

because  `const hook = getHook(GET_COORDINATES_FROM_PIXEL_HOOK);` was undefined in the case of WFS layer in Cesium since the cesium map component does not implement it.

so it would always use a default radius of 0.01 meters that would make impossible to fetch data because the intersection of the circle drawn around the clicked point would always be too small

so with [these](https://github.com/geosolutions-it/MapStore2/compare/master...MV88:fixes_for_wfs_cesium?expand=1) changes we use the current resolution to generate a valid radius to use 

in this you will get data from WFS layer in cesium
