### ISSUE TITLE
Annotation state fix when in edit mode

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#8237]
## Description

At the moment the state of the annotation tool when an annotation is not yet saved is lost if you open another drawing tool like measurement. 

At least a confirmation dialog should be visualized in this case to ask the user if he wants to proceed and lose drawn annotations.

## How to reproduce

![annotation_state_fix.gif](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/ca98ee51-1df4-43c1-a667-19248af40c89)

*Expected Result*

Confirmation dialog appears.

*Current Result*

The confirmation dialog is not displayed.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by ElenaGallo** [comment]
@tdipisa No, Confirmation dialog now appears.
