### ISSUE TITLE
Save dialog is not properly displayed in certain cases

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#8238]
## Description

The Save confirmation dialog should be always visible.

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/f51959cc-8788-4ecb-b9cb-986ce4d19089)

## How to reproduce

- Open a map 
- Open for example the measurement tool
- Save the map

*Expected Result*

The Save confirmation dialog is visible over all other panels.

*Current Result*

The Save confirmation dialog can be covered by other panels.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

Since we have changed the UI of the measurement tool on master, the issue cannot be reproduced there. This issue is affecting only the last release therefore a fix should be provided only for the stable branch 2022.02.xx

**Comment by alexander-fedorenko** [comment]
@tdipisa This looks to be a quick thing to fix, but I can't really get the result you described.
I'm trying to reproduce it on https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/10358 and when I open measure, drawing something and then click on "Save map" - all I get is save dialog with no modals requesting me to proceed with unsaved changes.
