### ISSUE TITLE
Import geoJson is no longer working

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#8270]
## Description

Unless is one of my picnic, but I remember you could import geojson files

## How to reproduce

- un pack this file locally
[clickedpoint.zip](https://github.com/geosolutions-it/MapStore2/files/8813370/clickedpoint.zip)
- drag it on the import tool

*Expected Result*

-  you can import it

*Current Result*

nothing happens

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

```json
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [
      125.6,
      10.1
    ]
  },
  "properties": {
    "name": "Dinagat Islands"
  }
}
```

@tdipisa 
This occurs also in the stable version

**Comment by tdipisa** [comment]
I think it is a problem involving that specific geojson as far as I can see. Using a geojson exported from GS it is working as expected. So I think we have to investigate why with the geojson you have indicated is not working.

**Comment by tdipisa** [comment]
@MV88 I think I can confirm this. MS accepts _FeatureCollection_ for the geojson import and not single features.

**Comment by MV88** [comment]
@tdipisa i see, anyway it can be a nice improvement imho

**Comment by tdipisa** [comment]
@MV88 no. Are you sure it is not already specified in our current online doc? Anyway, this issue is referring another thing. Please open a new one if you want for the needed improvement if effectively necessary.

**Comment by MV88** [comment]
@tdipisa sorry to be pedantic

our doc specifies only generic GeoJSON

![image](https://user-images.githubusercontent.com/11991428/183392923-8fc03d74-944d-4ab7-888b-75500f71027d.png)

The import tool too

![image](https://user-images.githubusercontent.com/11991428/183393015-d0cf8588-cf8b-49f4-a9dd-3d33adad552f.png)

If you really want we can open an issue to specify to change the messages and docs, but imo this task is a quick one (max 1d) and would be better to support any type of GeoJson, not only FeatureCollection 

we may change title of this issue to 

**Add support to any kind of GeoJSON in the import plugin**

**Comment by tdipisa** [comment]
@MV88 we have to open an issue for an improvement.
