### ISSUE TITLE
Add support for height and extrudedHeight properties for 3D vector style WFS/Vector type

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#8298]
## Description

The graphics classes for Cesium Entity could support properties related to height and extrudedHeight. we should improve the cesium style parser for WFS/Vector layer to support these properties and the Visual Style Editor ui to support related inputs.

Graphics that could support height are:

- [BillboardGraphics](https://cesium.com/learn/cesiumjs/ref-doc/BillboardGraphics.html) used by Mark and Icon
- [PolygonGraphics](https://cesium.com/learn/cesiumjs/ref-doc/PolygonGraphics.html) used by Fill symbolizer
- Verify [LabelGraphics](https://cesium.com/learn/cesiumjs/ref-doc/LabelGraphics.html?classFilter=Label)

Graphics that could support extrudedHeight is:

- [PolygonGraphics](https://cesium.com/learn/cesiumjs/ref-doc/PolygonGraphics.html) used by Fill symbolizer

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features

**Comment by tdipisa** [comment]
Finally implemented through https://github.com/geosolutions-it/MapStore2/issues/9807
