### ISSUE TITLE
Line cap and join are not working in visual style editor for WFS/Vector in 3D

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#8301]
## Description

Line cap and join properties are not working in visual style editor for WFS/Vector in 3D

## How to reproduce

-  
- 

*Expected Result*

*Current Result*

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
> Hi @allyoucanmap, the Line cap and join are now enabled in 2D but disabled in 3D.

It is effectively what expected, please look better at the connected PR https://github.com/geosolutions-it/MapStore2/pull/8955
