### ISSUE TITLE
GS problem saving new features on attribute table

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#8356]
The error shown in the gif below appears when saving a new feature in the attribute table.

https://images.zenhubusercontent.com/39382076/1c605ec3-168c-45f4-a507-377bc26ea9c2/save_new_feature.mov

**How to reproduce**
- Open [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/39517)
- Select the layer  on TOC
- Click on attribute Table
- Click on Edit 
- Create new feature
- Click on Save

*Current Result*
It is not possible to save a new feature

**Comment by tdipisa** [comment]
@randomorder we should investigate what is happening here. Since the error is "no space left on device" I suspect there is a problem with the GS system.

**Comment by tdipisa** [comment]
@randomorder thank you so much. @ElenaGallo can you please retest?
