### ISSUE TITLE
Review BILTerrainProvider get capabilities request

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#8373]
## Description

The [BILTerrainProvider](https://github.com/geosolutions-it/MapStore2/blob/2022.01.xx/web/client/utils/cesium/BILTerrainProvider.js) is performing a complete get capabilities to the server to get information related to the layer at every initialization of the 3D viewer.
We need to verify if we can apply some improvements:

- [ ] request capabilities to the single layer endpoint
- [ ] avoid to send a get getcapabilities and provide needed options via BILTerrainProvider interface

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features

## Other useful information
Ref: https://github.com/geosolutions-it/MapStore2-C027/issues/127

**Comment by ale-cristofori** [comment]
as discussed with @allyoucanmap we would ideally implement a fall back system to slim down the response to `getCapabilites` performed by the `BILTerrainProvider` class.

1. No `getCapabilities` request required user inputs parameters and information manually, as soon as the user switches to 3D view, that pieces of information for rendering a 3D map will be used, avoiding the firing of an HTTP request.
2. In case the information and parameters required described in point 1 are not set then the HTTP request `getCapabilities` will be needed, in that case if the layer for which the 3D representation is requested is prefixed with its workspace  AND is a geoserver layer (most likely as 3D support only works for Geoserver layers to present date) `workspace:layer` then the `getCapabilities` request will be performed against the layer, a reduced response will be returned in this case.
3. If layer is not prefixed with its workspace, then the global/workspace scoped `getCapabilities` request will be performed and the information required will be got from that request (this is the current behaviour).
