### ISSUE TITLE
Update LeafletDraw to 0.2.4

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#838]
npmcdn hosts version 0.2.4 tagged as 0.2.3
Investigate if the upgrade to 0.2.4 will cause any issue
Minified javascript should be used.

**Comment by Gnafu** [comment]
Reopening this.
We are still not using the minified version and all the examples should be updated too.

**Comment by tdipisa** [comment]
closed for inactivity.
