### ISSUE TITLE
3D mode remains enabled on other map

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#8397]
Only in mapstore dev, when a map in 3D mode is closed, the mode 3D is active when another map or a new map is opened.

**How to Reproduce**
- Open a map
- Enable the 3D mode
- Go back to the homepage
- Open a map or a new one

*Expected Result*
The 3D mode is not enable

*Current Result*
The 3D mode is enable

**Comment by tdipisa** [comment]
@allyoucanmap can you please do a quick check to understand the reason of this regression and report back?

**Comment by allyoucanmap** [comment]
@tdipisa the map viewer is currently looking for some query parameters: heading, pitch and roll to switch the map to cesium (this is used mainly for share and embed pages)
If we follow the steps described in the issue we will see that [cesiumViewerOptions](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/epics/queryparams.js#L67) is true if the previous map type was cesium even if the query parameters of the url are empty.
I think we need to review how the [getCesiumViewerOptions](https://github.com/geosolutions-it/MapStore2/blob/b15ec38fdfa82a49f055b7b35482dcda8159e964/web/client/utils/QueryParamsUtils.js#L145-L149) works.

**Comment by tdipisa** [comment]
Thank you so much @allyoucanmap for the rapid check. That's really appreciated.
