### ISSUE TITLE
Export data options are no longer present.

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#8407]
The *Crop dataset* and *Download filtered dataset* options on Export Data panel are no longer present for vector layers and the WPS is not active for raster layer.

**Current Result**
*Vector Layer*
![v_no.png](https://images.zenhubusercontent.com/5da5b30f66de7b0001e4e77c/8dd9a999-6151-4747-a2bb-f6bf9ba49e3f)!
*Raster Layer*
![r_no.png](https://images.zenhubusercontent.com/5da5b30f66de7b0001e4e77c/3166c43b-c57e-4707-a907-84d96c6653c0)

**Expected Result**
*Vector Layer*
![v_ok.png](https://images.zenhubusercontent.com/5da5b30f66de7b0001e4e77c/2f62ad71-0d31-4d28-aa27-0cba892b2ff7)
*Raster Layer*
![r_ok.png](https://images.zenhubusercontent.com/5da5b30f66de7b0001e4e77c/57327907-133e-49f1-986b-cc867f3886d7)

**Comment by tdipisa** [comment]
@ElenaGallo I can see them. Can you please try again by cleaning up the browser cache?

**Comment by ElenaGallo** [comment]
@tdipisa Cleaning the browser cache I have the same problems.

**Comment by tdipisa** [comment]
@ElenaGallo so please logout, clean cache, login again and retry

**Comment by ElenaGallo** [comment]
@tdipisa ok, now it works

**Comment by tdipisa** [comment]
@ElenaGallo thank you. @offtherailz please let me know if you have some feeedback anyway.

**Comment by offtherailz** [comment]
The only idea I can figure out is that something happened in the token workflow system we are working on.

Let's monitor if this happens again to check if the authkey / toke system is workin6 correctly
