### ISSUE TITLE
Backend changes to "/rest/config/setParams" endpoint to support multiple embedded maps via POST on the same page

### ISSUE THREAD

**Issue by alexander-fedorenko** [geosolutions-it/MapStore2#8413]
## Description
This is a companion task for https://github.com/geosolutions-it/mapstore2/issues/8393
Basic functionality remains the same as it was introduced by https://github.com/geosolutions-it/MapStore2/issues/8034.
In addition, on each POST request backend will generate random queryParamsID value (UUID v4) and will use it as a suffix for item name  in sessionStorage. Structure of the object will not change.

Content of the page writing data to the sessionStorage and triggering redirect will be slightly changed.
- It will write into "queryParams-<QUERY_PARAMS_ID>" item of session storage, where `QUERY_PARAMS_ID` is the randomly generated UUID.
- `PAGE_PARAM` will contain GET parameter `queryParamsID` with the value of the randomly generated UUID.
E.g. `../../#/viewer/openlayers/config?queryParamsID=9631ae85-898e-4a9d-aafd-9d85c522a8ee`

Content of the page:
```html
<!DOCTYPE html>
<html>
<head>
    <script>
        sessionStorage.setItem('queryParams-<QUERY_PARAMS_ID>', JSON.stringify(<JSON_PARAMS>)); 
        location.href='<PAGE_PARAM>?queryParamsID=<QUERY_PARAMS_ID>';
    </script>
</head>
<body>
</body>
</html>
```

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by taba90** [comment]
opened pr  on master

**Comment by tdipisa** [comment]
Thank you so much @taba90

**Comment by taba90** [comment]
backport pr [here](https://github.com/geosolutions-it/MapStore2/pull/8428)
