### ISSUE TITLE
Tests can fail if Chrome takes too long to start

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/MapStore2#842]
By default Karma will wait for 10 seconds for Google Chrome to start and run the tests.
Build at http://build.geo-solutions.it/ occasionally timeout and fail. Would it be possible to increase the timeout?

**Comment by Gnafu** [comment]
Close by https://github.com/geosolutions-it/MapStore2/commit/d8b7fe5a321efe00527440ec9b5152fc329d5c6d
