### ISSUE TITLE
Problem with expired / invalid sessions

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#8440]
## Description

When you recover a previous session, sometimes (probably due to expiration or server reboot) you look like you are logged in, but you are not able to perform logged user operation. 
Checking the tokens, both the refresh and the access token are empty. 

## How to reproduce
-  login on dev instance
- turn off browser and wait (expiration time have to be checked)
- open mapstore again

*Expected Result*
- You are logged out or logged in

*Current Result*
- You seems to be logged in, but you can not do any operation.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

As a certain point mapstore sends this:

```
curl 'https://dev-mapstore.geosolutionsgroup.com/mapstore/rest/geostore/session/refreshToken' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.9,it-IT;q=0.8,it;q=0.7' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Cookie: _gcl_au=1.1.1419708036.1652977723; _ga=GA1.2.810097953.1652977723; SL_C_23361dd035530_KEY=1e81b1058a277e08b89ce1a8afae7c273bf43218; SL_C_23361dd035530_VID=BZZeO3lUq-' \
  -H 'Origin: https://dev-mapstore.geosolutionsgroup.com' \
  -H 'Referer: https://dev-mapstore.geosolutionsgroup.com/mapstore/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: ".Not/A)Brand";v="99", "Google Chrome";v="103", "Chromium";v="103"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  --data-raw '{"sessionToken":{"access_token":"","refresh_token":""}}' \
  --compressed
```

You can notice the "access_token" and "refresh_token" are empty. 
Probably due to a previous communciation we didn't identified yet. 

Anyway, the refreshToken entry point replies with 204 to this request or any other request with arbitrary tokens. 
(e.g . `{"sessionToken":{"access_token":"test","refresh_token":"test"}}`)
It should instead return:
- the new tokens (or the same tokens if valid)
- or respond with an error, so mapstore can logout the user correctly

**Comment by taba90** [comment]
The previous refresh endpoint was deprecated in favour of a new one that allows anonymous to try refresh the token (this due keycloak/openid support as a token might be invalid and thus not authenticable but still the refresh token might be valid).
In order to fix this I will return a FORBIDDEN status when the token cannot be refreshed as it was before for the default token mechanism.
