### ISSUE TITLE
More doc for Extension update

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#8454]
## Description

It would be good to enhance [this section](https://mapstore.readthedocs.io/en/latest/developer-guide/extensions/#installing-extensions) of the online documentation to better explain how to update an extension already installed along with all relevant considerations concerning its configuration.

*Documentation section involved*
- [ ] User Guide
- [X] Developer Guide

**Comment by alexander-fedorenko** [comment]
@tdipisa We have similar content about extensions management available both in user-guide and developer-guide, so I've added a section with update instructions in user-guide and referenced it in developer guide.
