### ISSUE TITLE
Produce a meaningful warning when printing cannot be performed

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#846]
In [this](http://mapstore2.geo-solutions.it/mapstore/#/viewer/leaflet/464?_k=lm66i2) map there is a GWC layer which cannot be printed by theMapStore 2 Printing engine.

At the time of writing this is a normal situation since the printing engine does not support tiled services, however no feedback is provided to the users leaving them in the dark with a map which only partially printed.
I believe we should catch this condition before doing the actual print, I mean, if there is content on the map which is not printable we should let users know in advance.

**Comment by mbarto** [comment]
I cannot imagine any way to know that in advance.
Open to suggestions.

**Comment by tdipisa** [comment]
closed for inactivity
