### ISSUE TITLE
Versioning of data dirs

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#8465]
## Description

Add versioning of data dirs

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes infrastructure change
- [ ] Other... Please describe: 

## Other useful information
MS data dir repo here: https://github.com/geosolutions-it/mapstore-datadir

**Comment by tdipisa** [comment]
@randomorder let's decide together the best approach.

**Comment by ibrahimcengizgeo** [comment]
Hi @tdipisa @randomorder ,
we can use **[mapstore-datadir](https://github.com/geosolutions-it/mapstore-datadir)** repo for changes.

After making a change, you should wait 1 minute for it to take effect in the mapstore folders, [There is a '**pool SCM**' that checks the repo every 1 minute]

be informed.

**Comment by tdipisa** [comment]
As agreed also with @randomorder three branches have been created in [mapstore-datadir](https://github.com/geosolutions-it/mapstore-datadir) repo, one for each MS instance we have to maintain: DEV, QA and STABLE.

@ibrahimcengizgeo has already versioned the current state while @MV88 will update each branch next days according to what scheduled for #7165.

Three additional Jobs will be created in Jenkins to fetch updates from each branch of [mapstore-datadir](https://github.com/geosolutions-it/mapstore-datadir) and so update the data dir of each instance (eg. one datadir update job for each MS instance). A separate issue has been created for the implementation of these jobs.

**Comment by tdipisa** [comment]
@MV88 jenkins jobs are already in place and the update of data dirs is triggered automatically after few minutes when we commit/merge updates. I've asked @ibrahimcengizgeo to put a brief documentation about three jobs in the repo readme.

**Comment by MV88** [comment]
@tdipisa thanks, i like the fact there is no manual operation involved other than pushing changes to the datadir repo

**Comment by ibrahimcengizgeo** [comment]
@tdipisa, @MV88
it seems this task was assigned to me. if it's not related to me I will unassign it, 
I guess only https://github.com/geosolutions-it/DevOps/issues/1046 was on me.

**Comment by MV88** [comment]
yes, you can unassign now

**Comment by tdipisa** [comment]
moving in Review. Related PRs for this issue are here:
- https://github.com/geosolutions-it/mapstore-datadir/pull/2 that depends on:
   - Merge https://github.com/geosolutions-it/MapStore2/pull/8511
   - Merge https://github.com/geosolutions-it/MapStore2/pull/8522
- https://github.com/geosolutions-it/mapstore-datadir/pull/3 that depends on
   - Testing of [#2](https://github.com/geosolutions-it/mapstore-datadir/pull/2) above for DEV

**Comment by offtherailz** [comment]
There are no functional changes in this PR. The refactor involves the geoserver integrations. So please test them on DEV and QA.
I tested on myself the integration is working. 

The only thing left is to merge this during release. https://github.com/geosolutions-it/mapstore-datadir/pull/4 
Already noted in #8660 

So I'm going to close and accept this issue
