### ISSUE TITLE
TOC - Header toolbar buttons are wrapped and partially hidden

### ISSUE THREAD

**Issue by dsuren1** [geosolutions-it/MapStore2#8471]
## Description
Header toolbar buttons are wrapped and partially hidden in some cases where layer config allows multiple actions to be performed

## How to reproduce
1. Open this [map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/10358)
2. Select a layer ex: `Manhattan (NY) point of interest`
3. Enable metedata tool on layer options

*Expected Result*
![image](https://user-images.githubusercontent.com/26929983/184143674-66da739e-435d-4975-b4da-24a215f4ce4e.png)

*Current Result*
![image](https://user-images.githubusercontent.com/26929983/184143738-2a3d9ef3-61ab-4185-a83a-fa0b883c824b.png)

**Comment by allyoucanmap** [comment]
@tdipisa this has been solved in #9982 so it can be closed
