### ISSUE TITLE
Annotations - Circle geometry issue 

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#8475]
## Description

By drawing a circle with the mouse, it remains attached to the map

## How to reproduce

-  Open a map
- Open the Annotations panel
- Click on +
- Follows the steps in the gif below:
![circle3](https://user-images.githubusercontent.com/56537133/184312233-d4579fd6-43d7-47cf-8277-481e76fcea00.gif)

*Current Result*

The mouse remains attached to the map

**Comment by MV88** [comment]
@tdipisa I confirm what reported above

@ElenaGallo please re-test this issue in DEV
