### ISSUE TITLE
The MAP EDITOR INLINE is not visible 

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#8481]
## Description

On geostory The MAP EDITOR INLINE is not visible
  
## How to reproduce

-  Login as admin
- Click on new map
- Click on Change Media Source
- Click on Maps tab
- Click on +

or
- Open a geostory
- From the map background, click on Edit map
- Click on Open advanced map editor

*Current Result*

The MAP EDITOR INLINE is not visible 
![map editor](https://user-images.githubusercontent.com/56537133/184393914-206225be-196a-4c39-b69e-baee6e20043a.png)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

It seems a regression introduced after #8457. The tool works well in QA.

**Comment by tdipisa** [comment]
@ElenaGallo this seems to be solved for me in DEV. Please double check.

**Comment by ElenaGallo** [comment]
@alexander-fedorenko

**1_** After testing the #8481 I found this:

I can not save the map from the MAP EDITOR INLINE
  
## How to reproduce

-  Login as admin
- Click on new geostory
- Click on Change Media Source
- Click on Maps tab
- Click on +
- Click on OK


*Current Result*
The Ok button is not clickable
