### ISSUE TITLE
Add an Extension on a context issue

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#8482]
## Description

It is not possible to add a new extension on a context

## How to reproduce

-  Login as admin
- Open a new context
- On Configure plugins step, click on Add extension
- Add [this extension](https://github.com/geosolutions-it/MapStore2/files/9324681/SampleExtension.zip)
- Click on Install

*Expected Result*

The extension is present on the available Plugins list

*Current Result*

The extension is not installed

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

It seems a regression introduced after #8457. The tool works well in QA.

**Comment by tdipisa** [comment]
https://github.com/geosolutions-it/MapStore2/files/9324681/SampleExtension.zip
