### ISSUE TITLE
App Context Manager issues

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#8483]
## Description

The Application context manager has problems to work on DEV.
- On new context, the Show Tutorial on the wizard steps does not work 
- When modifying an existing context the changes cannot be saved, the Save button at the end of the wizard does not work

## How to reproduce

-  Login as admin 
- Open the app context manager and try to edit and create contexts as described above
 

*Expected Result*

It is possible to start a tutorial though the Show Tutorial for all the steps of the wizard.
It is possible to save changes on a context

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

It seems a regression introduced after https://github.com/geosolutions-it/MapStore2/pull/8457. The tool works well in QA.

**Comment by tdipisa** [comment]
@ElenaGallo this seems to be solved for me in DEV. Please double check.

**Comment by ElenaGallo** [comment]
@alexander-fedorenko 

**2_** After testing the #8483  I found this:

For the second steps of the wizard, the tutorial start at the beginning but then when I click on Show Tutorial button the tutorial does not start and for the third steps of the wizard, the tutorial does not start and when I click on Show Tutorial button the tutorial does not start. 

## How to reproduce
See the gif below: 

https://user-images.githubusercontent.com/56537133/188417165-a6aa5978-9e89-49e9-abea-3225fcf2ef95.mov
