### ISSUE TITLE
Homepage buttons sometime does not work

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#8484]
## Description

From a geostory, it seems that after opening the INLINE MAP EDITOR, it is no longer possible to go back to the MS homepage
![geostory](https://user-images.githubusercontent.com/56537133/184397254-111454d3-6f1d-4860-90f8-969de5d76e2d.gif)

## How to reproduce

-  Open a geostory
- Click on Change media source
- Click on Maps tab
- Click on +
- Click on OK
- Click on Go back to the homepage

*Current Result*

it is no longer possible to go back to the MS homepage

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@ElenaGallo this seems to be solved for me in DEV. Please double check.
