### ISSUE TITLE
An error occurred in display cesium

### ISSUE THREAD

**Issue by jiaguohuiDeep** [geosolutions-it/MapStore2#8485]
![error](https://user-images.githubusercontent.com/22003758/184632421-5681019f-68d0-401e-9919-e53b18d2f194.jpg)

**Comment by MV88** [comment]
@jiaguohuiDeep hi can you give use more details?
which version are you using?
Are you using some customized version of mapstore or have you downloaded a war?
What are the steps to reproduce this?
