### ISSUE TITLE
Open ID with google no longer works in DEV

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#8487]
## Description

probably due to modular plugin change in DEV we have issues to open id authentication

## How to reproduce

-  try to login with google in DEV
- (this issue is caused by introduction of modularization of plugin, so it doesn't affect 2022.02.xx)

*Expected Result*

you can login

*Current Result*

you cannot login
it logs you out immediately

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

probably the Login plugin should not be modular?

**Comment by offtherailz** [comment]
Probably this is due to the modulization of login plugin. Can we disable the modulePlugin until we migrated it properly? @allyoucanmap

**Comment by offtherailz** [comment]
I tested and works for me. The other issues of OpenID are still to be fixed and backported, but at least we can now test them on dev too.
