### ISSUE TITLE
Our documentation has a lot of markdown lint errors

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#8491]
## Description

We should use this extension locally to check over the various .md files for lint errors
https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint

for example with this tool installed in VSCode you see this
![image](https://user-images.githubusercontent.com/11991428/185183567-ab3d5d6b-eb7b-4cf1-b68d-4046387e9cba.png)

*Documentation section involved*
- [x] User Guide
- [x] Developer Guide

**Comment by belom88** [comment]
Our docs contain "admonition" syntax that is not supported by the "markdownlint" plugin.
The issue: https://github.com/DavidAnson/markdownlint/issues/207
The example in our code that is not supported by the plugin:
https://github.com/geosolutions-it/MapStore2/blob/99132d457d1368470ed1b64bc8aeed65e124e2f1/docs/user-guide/adding-widgets.md?plain=1#L54

**Comment by belom88** [comment]
> Our docs contain "admonition" syntax that is not supported by the "markdownlint" plugin. The issue: [DavidAnson/markdownlint#207](https://github.com/DavidAnson/markdownlint/issues/207) The example in our code that is not supported by the plugin:
> 
> https://github.com/geosolutions-it/MapStore2/blob/99132d457d1368470ed1b64bc8aeed65e124e2f1/docs/user-guide/adding-widgets.md?plain=1#L54

@MV88

**Comment by MV88** [comment]
markdownlint was a proposal, my intention is to help us prevent to insert syntax error in general 

in any case right now this tool seems not signaling those as an issue so i guess it can be used to fix these syntax error

also I suggest to add this to vs code settings

```
"editor.codeActionsOnSave": {
        "source.fixAll.eslint": true,
        "source.fixAll.markdownlint": true
    },
```

**Comment by MV88** [comment]
Also if you want to see the warnings near the codebase I suggest adding [errorlens](https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens)

said that can you provide a fix of all markdown syntax errors?

**Comment by belom88** [comment]
> in any case right now this tool seems not signaling those as an issue so i guess it can be used to fix these syntax error

It sees the indented piece after !!!note as code snippet. It is incorrect validation. I stumbled on to that fixing [MD046](https://github.com/DavidAnson/markdownlint/blob/v0.26.2/doc/Rules.md#md046---code-block-style) .
I will try to fix the code snippets to indentations all around the docs. But anyway it is  incorrect behavior of the plugin that could lead to issues in future.
