### ISSUE TITLE
Contexts have unexpected behaviour when a Map plugin uses mapType equal to cesium

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#8493]
## Description

Currently it is possible to configure a Map plugin inside a context using a cesium map type, this will work for the map but other plugins are not aware of this configuration.
For example [this context](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/austrocontrol-terrain/40096) uses the cesium map type, the map viewer is correctly using the 3D view but other plugins are not working as expected, eg. TOC shows 3D tile layer disable with the info sign icon. This is related to the fact that map type is managed with the redux state and when we using the Map plugin cfg to define the mapType this is referred to the map only:

If we look at the code a configuration like this will override the one from the state
```js
{
  "name": "Map",
  "cfg": {
    "mapType":  "cesium"
  }
}
```
because the Map plugin is using the custom connect from the utils file introduced in this [PR](https://github.com/AGMETEOR/MapStore2/commit/23d4d7708d300044d168a4705fa71990a9ad41ee) to allow to override the shouldLoadFont via localConfig.json.

Probably we should add an external field from the plugin config in the context steps to define the map type to use.

## How to reproduce

- open [this context](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/austrocontrol-terrain/40096)
- open the TOC

*Expected Result*

- 3D tiles menu items should be displayed without info icon

*Current Result*

- 3D tiles menu items should be displayed without info icon because the mapType in the state is still openlayers

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Sdafari| |
</details>

## Other useful information

This issue is probably connected to also https://github.com/geosolutions-it/MapStore2/issues/8334

**Comment by MV88** [comment]
Note for the tester:

In addition while reviewing this PR #8489 I spotted an error in this context while opening it and activating 3D
![image](https://user-images.githubusercontent.com/11991428/185636948-7893957b-6678-4b11-9529-da3ee05047f0.png)
http://localhost:8081/?debug=true/#/context/7111withIdentify

so I suggest to test this bit when the fix for this issue is done and the other PR is merged

**Comment by tdipisa** [comment]
@ElenaGallo after https://github.com/geosolutions-it/MapStore2/pull/8990 this can be closed, I think? Can you confirm?

**Comment by ElenaGallo** [comment]
@tdipisa yes, the issue can be closed.
