### ISSUE TITLE
Error Adding CSW, WMS of WFS to catalog

### ISSUE THREAD

**Issue by gisnederland** [geosolutions-it/MapStore2#8505]
## Description
Adding CSW, WMS of WFS services other than the one of geosolutions gives an error

## How to reproduce
Options menu -> Catalog -> plus-sign:
Tried these URLs:
WFS: https://service.pdok.nl/lv/bag/wfs/v2_0?request=getCapabilities&service=WFS&version=2.0.0
WMS: https://service.pdok.nl/brt/top10nl/wms/v1_0?service=wms&request=getCapabilities
CSW: https://nationaalgeoregister.nl/geonetwork/srv/dut/csw?request=GetCapabilities&service=CSW

*Expected Result*
Services added to the list

*Current Result*
Error message that service could not be loaded

## Other useful information
Error occurs in version 2022.01.02 (I used the binary), 
but does *not* occur in release 2021 (using the war-file in Tomcat)  

GetCapabilities on the 3 services (in the browser) gives normal reply

**Comment by MV88** [comment]
@gisnederland thanks a lot for your feedback, much appreciated

We will check this to see if there is any problem to the version we are going to release in September 
and also on the master branch

Since 2022.01.02 things have changed, so the error may be no longer present

**Comment by derekvb** [comment]
I am running the 2022.02.00 binary, the same error message is still occuring.

**Comment by derekvb** [comment]
Thank you, this worked (I also shutdown and restarted mapstore, in order to load the changes made to the localConfig.json file)

But this will be necessary for any web service endpoint? Also in future versions of Mapstore?

**Comment by MV88** [comment]
> Thank you, this worked (I also shutdown and restarted mapstore, 

When you edit the changes in localconfig is not necessary to shutdown the tomcat, you can simply refresh the page where you are in mapstore, because this is a static file loaded everytime you load the app

> But this will be necessary for any web service endpoint? 

yes, I would advidse so, but only in the binary config this should be needed now as a workaround

> Also in future versions of Mapstore?

This has to be investigated, but consider that binary should be used mostly for testing and exploring mapstore and not in production

@tdipisa 
I'll leave this issue open for further investigations

**Comment by derekvb** [comment]
Thank you

**Comment by tdipisa** [comment]
@derekvb I think you are experiencing an issue with the SSL handshake that are preventing the MS proxy to retrieve the response from the server in this case. Check your mapstore logs to confirm. 
I think this can happen if you use the binary from your local machine against a public service in HTTPS. That's the reason why it worked for you using a deployed WAR. I'm going to close the issue for now.
