### ISSUE TITLE
Version info in "about" box instead of in "settings"

### ISSUE THREAD

**Issue by gisnederland** [geosolutions-it/MapStore2#8506]
## Description
The Mapstore version number information (eg 2021.02.02) is now displayed in the settings menu.
It would make more sense to move it to the "about" menu-option

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X ] Minor changes to existing features

**Comment by MV88** [comment]
Thanks @gisnederland but there is a PR ready for that #8504 which targets #7934
