### ISSUE TITLE
Create github actions for builds in MapStoreExtension project

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#8516]
## Description

Add GitHub actions for https://github.com/geosolutions-it/MapStoreExtension

## Acceptance criteria

- [x] move checks.yml workflow present in this repo to https://github.com/geosolutions-it/MapStoreExtension
- [x] extend it by testing other commands like `npm run build:ext`

**Comment by offtherailz** [comment]
- Created checks for master and stable, added mandatory status checks to merge
