### ISSUE TITLE
Reduce dashboards clutter

### ISSUE THREAD

**Issue by dsuren1** [geosolutions-it/MapStore2#8520]
### Description
The client is asking for a review of the Dashboard layout aimed to reduce the clutter of widgets and their components (fonts, buttons, panels etc.).

From the client: 

>- abbiamo ragionato nel meeting sulla questione layout geodashboard ovvero come ridurre i caratteri e dimensioni bottoni e rendere il tutto meno 'ingombrante' 
in riferimento a questo argomento abbiamo inteso che ci fornirai alcune informazioni

The customer explicitly did this example by changing the browser scale %

![image](https://user-images.githubusercontent.com/1280027/141816301-35e12d46-1e35-4687-b11b-fb9caf9bb283.png)

Below is the current state as a reference for the above
![image](https://user-images.githubusercontent.com/1280027/141816610-b2448f96-b6e1-4741-9482-661e59833df9.png)

### Ref 
https://github.com/geosolutions-it/mapstore2-c040/issues/495

**Comment by dsuren1** [comment]
@tdipisa 
> * Check if also the font size of the table content can be configured (eg. to be reduced a bit if needed by configuration)

After discussion with @allyoucanmap , we believe that font size configuration can be done via css in the downstream project instead of the default font size on table widget based on the use case, rather than having a plugin configuration to set font size in the table as it proves to be less efficient.

**Comment by ElenaGallo** [comment]
@tdipisa @dsuren1 I just noticed that the widget title, if long compared to the box, is cut off for all widget types except the map.

![title issue](https://user-images.githubusercontent.com/56537133/191486394-4cb97ae4-be28-4b59-a2da-ef51abf98d0e.png)

**Comment by ElenaGallo** [comment]
@dsuren1 @tdipisa test passed on DEV
