### ISSUE TITLE
Burger menu not visible in DEV for context

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#8523]
## Description

Its seems that due to recent updates in DEV the burger menu is no longer visible in DEV if configured for a context

## How to reproduce

- Open [this context](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/espacesvertsdrennes) in edit mode
- In the plugin wizard add the burger menu
- Save and then open the context again

*Expected Result*

The sidebar disappear and the burger menu is available and functional

*Current Result*

A sidebar covering the burger menu with only the measurement tool is present.

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/82586923-c1ed-475a-be25-fd72e5df0f37)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

The tool works well in QA.

Related comment is https://github.com/geosolutions-it/MapStore2/pull/8530#issuecomment-1235240725

**Comment by alexander-fedorenko** [comment]
Not a regression, see description here https://github.com/geosolutions-it/MapStore2/issues/8463#issuecomment-1232954389
Requires a minor fix in sidebar menu visibility logic.

**Comment by tdipisa** [comment]
Relevant comment from @allyoucanmap in [#8530](https://github.com/geosolutions-it/MapStore2/pull/8530#issuecomment-1235240725) to resume the work for this issue as part of the 2022.02.01 iteration.

**Comment by offtherailz** [comment]
@allyoucanmap need to set the alwaysRender flag in the plugin to make it work?

**Comment by allyoucanmap** [comment]
@offtherailz this PR has already the Measure plugin updated with alwaysRender
https://github.com/geosolutions-it/MapStore2/pull/8754/files#diff-434d509b048e12e9e1c4c92944d208355b10faf3f2528ff363b5113199ffb6d7R203

**Comment by offtherailz** [comment]
Sorry my fault. I filtered commits for the review and then I forgot to reset before doing my comment.
