### ISSUE TITLE
custom search service is crashing mapstore in 3D mode

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#8537]
## Description

the app crash when...

## How to reproduce

- load a map 
- go in 3d 
- try to edit a custom search service 

*Expected Result*

it should not crash

*Current Result*

it crash

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@MV88 I've just tried this using https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/10358

No issue found so far following your steps. Can you please double check and let me know? Thank you so much.

**Comment by MV88** [comment]
Apparently this issue no longer happens. well it was raised more than 2 month ago so... happy end
