### ISSUE TITLE
Dynamic module documentations and more

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#8541]
## Description

- [x] We need to improve the documentations related to [dynamic import of extension](https://github.com/geosolutions-it/MapStore2/blob/master/docs/developer-guide/extensions.md#dynamic-import-of-extension):
  - highlight the behaviours introduces by this modularization, mute/unmute of epics and lazy loading of the js file
  - review all the steps based on latest update of store manager

- [x] We need to update the official [MapStoreExtensions](https://github.com/geosolutions-it/MapStoreExtension) repository and convert it to module. We can later update the SampleExtension in the dev/qa instances to test it.

- [x] We need to add also documentation that describe the [store manage api](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/StateUtils.js#L136) in JSDoc:  addReducer, removeReducer, addEpics, muteEpics, unmuteEpics (verify is compiled in the final framework doc)

*Documentation section involved*
- [x] Developer Guide

**Comment by tdipisa** [comment]
Point 2 in description done here https://github.com/geosolutions-it/MapStoreExtension/pull/36
