### ISSUE TITLE
Ability to configure the use of WFS instead of WPS for layer downloads

### ISSUE THREAD

**Issue by jusabatier** [geosolutions-it/MapStore2#8545]
## Description
Currently, the WPS is used if available for downloading layer's datas. On our instance, WFS support more formats, doesn't alter data's structure and is synchronous what is less complex for end user (only 1 click vs 3 with WPS).

In order to use WFS, we' have to disable WPS processes from GeoServer. I suggest to make this configurable from an option, for example in a plugin's config.
Some other applications ou usecaes may relly on those processes so it can be a problem to disable them.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features

**Comment by belom88** [comment]
Is it meant functionality behind this button:
![Screenshot from 2022-09-20 16-22-00](https://user-images.githubusercontent.com/18549629/191270282-94f9a395-7035-443b-9bee-5946d401480c.png)

**Comment by allyoucanmap** [comment]
@belom88 yes, this issue is referred to the LayerDownload plugin that is included in the TOC (your screenshot) and inside the FeatureEditor, see the containers property of the createPlugin export.
