### ISSUE TITLE
Embedding of Dashboards not working on DEV

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#8551]
## Description

The embedding of dashboard is no longer working in DEV

## How to reproduce

-  Open [this](https://demo.geo-solutions.it/share/mapstore/share_test/index_dev.html) online page from our online demo server

*Expected Result*

The embedding of dashboards is working

*Current Result*

As it is possible to see in the sample online page, the embedding of maps and geostory is working as expected while it is not working for dashboard (last iframe).

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by MV88** [comment]
this is a regression of https://github.com/geosolutions-it/MapStore2/pull/8531, going to provide a quick PR
