### ISSUE TITLE
Feature grid aliases and tooltips for columns

### ISSUE THREAD

**Issue by dsuren1** [geosolutions-it/MapStore2#8559]
### Description
In table widget creation wizard, there should be the possibility to configure a **Title** and a **Description** to each selected attribute:

- _Title_: it is used to set the attribute alias to be visualized in the table header
- _Description_: it is used to show the attribute description through a tooltip 

![table_chart_attributes](https://user-images.githubusercontent.com/1280027/180752381-eb330775-332c-4307-a74a-e902e1340e69.png)

The same functionality should be available for both dashboards and Table widgets in the viewer.

Ref: https://github.com/geosolutions-it/mapstore2-c040/issues/514

**Comment by MV88** [comment]
@dsuren1 i was passing by and i wanted to warn you about this:
be careful when working on this especially on the creation of ogc and cqlFilters (alias there should not be used)
