### ISSUE TITLE
Group permission dropdown not properly visible 

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#8573]
## Description

It is no possible to properly scroll groups of user to assign permissions to MS resources, the current UI makes it difficult to do sometime (eg. when there are more that one permission rules already configured in the list)

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/89e7e65a-1b64-49f6-9023-01fe94ff8200)

## How to reproduce

-  Open the Edit properties modal of a MS resource with more than one group permission rule set
-  Open the dropdown to select a new group of user to add a new rule

*Expected Result*

The dropdown should be always visible to be able to use its scrollbar and select a group

*Current Result*

The dropdown is covered by the panel at the bottom

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by belom88** [comment]
Make dropdown menu `position: fixed`. Adjust position of the menu in JS code in `onOpen` event handler.
