### ISSUE TITLE
Unable to filter with other layers

### ISSUE THREAD

**Issue by DavidQuartz** [geosolutions-it/MapStore2#8595]
## Description

Trying to set a layer as target for another layer filter causes an error.

## How to reproduce

-  Create a map
- Add 2 layers which intersect
- Filter one layer with the other set as target layer
- Select 'Intersects' as Operation
- Apply and Save filter
<img width="591" alt="Screenshot 2022-09-20 at 09 37 51" src="https://user-images.githubusercontent.com/42542676/191225081-3af6500a-f623-411c-9cf0-4043eff31a08.png">

*Expected Result*

Filter is applied

*Current Result*

We get an error on the layer 
<img width="357" alt="Screenshot 2022-09-20 at 09 39 53" src="https://user-images.githubusercontent.com/42542676/191225292-762cbfb6-ace7-4349-97ab-d6929f0a1d39.png">

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@DavidQuartz @giohappy it seems working for me on DEV. Is it maybe something related to data you are using with this functionality?

**Comment by DavidQuartz** [comment]
You are right @tdipisa. It may have been an issue with the layers I was testing with. I tested with other layers and it worked. Now I am able to filter. I will open an issue for the original problem we faced. cc @giohappy

**Comment by tdipisa** [comment]
So can we close this @DavidQuartz ?

**Comment by DavidQuartz** [comment]
> So can we close this @DavidQuartz ?

Yes we can @tdipisa
