### ISSUE TITLE
Introduce wizard-like help system

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#861]
We should introduce a wizard like help system taking extra care that it will work nicely on the mobile where it will be the default help system.

**Comment by simboss** [comment]
A few interesting examples:

1. [http://www.geoportal.org/](http://www.geoportal.org/)
2. google "Take a Tour" feaure 
![google](https://cloud.githubusercontent.com/assets/693880/21431530/e50053cc-c867-11e6-8f18-3894a1572e13.png)

**Comment by allyoucanmap** [comment]
We could include the intro.js library (http://introjs.com/) in a new plugin to manage and control the steps

concept visualization:

- first start:

![wizardhelp01](https://cloud.githubusercontent.com/assets/19175505/22555241/56867e2e-e963-11e6-92dd-1fc0c06cd90f.png)

- using help button:

![wizardhelp02](https://cloud.githubusercontent.com/assets/19175505/22555273/6fb20a94-e963-11e6-89b4-5c744335dfe3.png)

- focus on a object:

![wizardhelpan](https://cloud.githubusercontent.com/assets/19175505/22555289/7cd8a93a-e963-11e6-8d70-a15fcf8df31a.gif)

**Comment by mbarto** [comment]
Look also at this one: https://gilbarbara.github.io/react-joyride/

**Comment by offtherailz** [comment]
Yes, take a look at which better fits for us. They seem very similar, but the second seems already react-integrated and with more built in options. What do you think @allyoucanmap ?

**Comment by allyoucanmap** [comment]
I just finished to try react-joyride and i think it's better than introjs.
The steps and the main component are easy to stylize and modify rather than introjs. I think we should use 'react-joyride'.

**Comment by mbarto** [comment]
Ok, let's move on with react-joyride
