### ISSUE TITLE
Remove History Buttons from Mobile layout

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#862]
The history buttons on mobile phones push the loading icon too high when the cell phone is in landscape mode; see image below.

![screenshot_2016-07-18-13-01-50](https://cloud.githubusercontent.com/assets/693880/16913436/9886ce48-4cea-11e6-9a71-46daef32fac2.jpg)

I believe it is sage to get rid of the history buttons to fix this ugly effect.

**Comment by MV88** [comment]
has been solved with cdf71cd629ee6046cbe93235c353359082c99654 , closing this issue
