### ISSUE TITLE
Issues with Fill style symbolizer for vector/WFS layer in 3D maps

### ISSUE THREAD

**Issue by DavidQuartz** [geosolutions-it/MapStore2#8670]
## Description

There are two problems with the Fill style symbolizer for vector/WFS layer
- [x] Polygon Type style settings are not highlighted on user selection.
- [x] Also the 'Clamp to ground' label is not descriptive enough. It should be 'Clamp outline to ground'.
<img width="493" alt="Screenshot 2022-10-07 at 10 58 52" src="https://user-images.githubusercontent.com/42542676/194538721-a2cab915-4eb9-47ab-9173-0f6a4084cfe8.png">

## How to reproduce

-  Open a 3d map (eg [this one](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/cesium/38732))
- Import a polygon layer
- Navigate to polygon layer's style settings
- Create new style
- Select a Polygon type

*Expected Result*

The selected Polygon Type is highlighted and the clamp to ground label refer only to outline

*Current Result*

No highlight is applied and wrong label

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

GeoJSON polygon layer to import
[polygon.zip](https://github.com/geosolutions-it/MapStore2/files/9734101/polygon.zip)

**Comment by tdipisa** [comment]
The first point in description has been fixed already. Please @allyoucanmap can you plink here the PR that fixes it?
@allyoucanmap you can proceed then with the label fix.

**Comment by allyoucanmap** [comment]
@tdipisa fixed in the 3D Model symbolizer PR [here](https://github.com/geosolutions-it/MapStore2/commit/0a1a3fcb302a960d9889008b9c058584572585c4#diff-66ab62031fd5d81a531000589842c94fc82a930c392a2e18396322ea60fa0daeL337)
