### ISSUE TITLE
Snapshot plugin - refactoring to be compatible with sidebar menu

### ISSUE THREAD

**Issue by alex-fko** [geosolutions-it/MapStore2#8686]
## Description
As agreed here https://github.com/geosolutions-it/MapStore2-C040/pull/646#issuecomment-1274354048 `Snapshot` plugin should be slightly refactored.

Acceptance criteria:
- Snapshot plugin work both for burger menu and sidebar;
- Use a separate render with the item only as a button for burgerMenu/sideBarMenu;
- Make you sure that the panel is rendered only when open, not only hidden, it must be not rendered at all because it renders a preview map.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by marthamareal** [comment]
Snapshot functionality tested locally with a Jenkins war file.

**Comment by tdipisa** [comment]
@alex-fko can you please backport to 2022.02.xx?

@marthamareal as soon as a PR for a minor release is tested in DEV please remember to ask for the backport to the stable branch.

**Comment by tdipisa** [comment]
@marthamareal please don't close issues for which the backport is still missing.
Thank you @alex-fko for reopening it.
