### ISSUE TITLE
Implement a scalebar component

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#87]
The component should:
 - show a scalebar to identify the current scale graphically
 - show a combo  to select a new scale and show the current one

We would like to have some configuration options to customize the scalebar: 
 * show sample distance in m, km, mi
 * only scalebar / only scale combo / both

**Comment by mircobe87** [comment]
![scale-mock](https://cloud.githubusercontent.com/assets/5262132/10196505/806117de-6793-11e5-959e-8e5c16d9c3a2.png)

here a mockups for **scalebar** and **scalebox** component (for openlayers and leaflet in this order)
