### ISSUE TITLE
Out-of-the-box support for CRSes / projections other than WGS84 & Web Mercator

### ISSUE THREAD

**Issue by derekvb** [geosolutions-it/MapStore2#8716]
## Current workflow
At the moment, by default the only two options for the projection of your map are EPSG:4326 and EPSG:3857. If the user wants any other CRS, the CRS has to be manually added to a configuration file, for which you need to look up the projection definition and extent. You then need to update the "CRS Selector" plugin when editing a context. This also requires manually editing a configuration file. 

## Desired workflow (functionality)
That's not really user friendly. I want to suggest out of the box support for any other EPSG projection. When editing a context, the only thing you would have to do is choosing which projections you want to make available within the context. 
The following screenshot shows how to choose the projections for grids in GeoServer. This is how it could maybe be implemented in MapStore: as dropdown list in which the user can search. 

![afbeelding](https://user-images.githubusercontent.com/50830605/196930916-9eb74e3e-fdd3-4d3e-8e41-0ae4ad1e92f6.png)

## Acceptance criteria

- All projections are available and preconfigured
- No manual editing of configuration files

**Comment by tdipisa** [comment]
Closed in favor of https://github.com/geosolutions-it/MapStore2/issues/9591
