### ISSUE TITLE
Adding security UI for managing GeoFence security rules

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/MapStore2#873]
Proposal: https://github.com/geosolutions-it/MapStore2/wiki/GeoFence-Security-Rules-Management-Proposal

GeoServer mailing list discussion about GeoFence REST interface extension: http://osgeo-org.1560.x6.nabble.com/Extending-GeoFence-REST-interface-td5276626.html

**Comment by mbarto** [comment]
Not visible in the Manager UI by default
