### ISSUE TITLE
Identify no longer work on 3D in QA for WFS layers

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#8739]
## Description

And hovering over a point feature the following error is raised
![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/5559048b-966c-4e99-88b8-efe54e091b24)

## How to reproduce

-  Open [this](https://qa-mapstore.geosolutionsgroup.com/mapstore/#/viewer/cesium/39593?center=8.92368793487549,44.414175805394656&zoom=16.999999999999325&heading=8.881784197001252e-16&pitch=-1.5707963267948966&roll=0) map 
- Use the Identify

*Expected Result*

Identify works.

*Current Result*

Identify don't works.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@alex-fko we have to understand what introduced this regression. I will add then the corresponding project label accordingly.

**Comment by alex-fko** [comment]
This is regression introduced by: https://github.com/geosolutions-it/MapStore2/pull/8602 (https://github.com/geosolutions-it/MapStore2/commit/ced3990a708f94d5c53dcb38ee67a45d18048323#diff-14825f064f4138a20fe9c4a2c4222a5be38dbf4ec0450c7ba8df03b7b6f13e65R30)
Can't be reproduced on master, fixed by: https://github.com/geosolutions-it/MapStore2/pull/8700

**Comment by tdipisa** [comment]
@allyoucanmap can we maybe simply wait for the backport of #8700 where anyway we have [this](https://github.com/geosolutions-it/MapStore2/pull/8700#issuecomment-1293750183) to check?

**Comment by allyoucanmap** [comment]
@tdipisa yes, we could backport that even if needs an additional fix related to drillPick implementation I'll provide soon
