### ISSUE TITLE
Date picker to edit time attributes

### ISSUE THREAD

**Issue by alex-fko** [geosolutions-it/MapStore2#8745]
## Description

At the moment the date picker is not available when editing a temporal attribute (eg. Dates) and the temporal value must be provided manually. The DatePicker should be included for this to make easier the editing and prevent errors.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Other useful information
Check the ability to configure additional properties for the date picker to eventually be able to set time and not only date.

**Comment by ElenaGallo** [comment]
Hi @tdipisa, on MapStore DEV and on Genova test i found those issues:

- The date searched in the quick filter of the attribute tables does not give results
![data-attribute-table](https://user-images.githubusercontent.com/56537133/203756475-05ff9eba-f154-4f3a-8cb8-e916d8c6e238.gif)

- When an edited date is saved, the hours return as those present before editing (only the minutes change)
![edit-data-attribute-table](https://user-images.githubusercontent.com/56537133/203756817-8464fbfc-ecb3-4dd6-b895-f08f0f989535.gif)

**Comment by ElenaGallo** [comment]
@tdipisa you can use this map: https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/42438

**Comment by tdipisa** [comment]
@ElenaGallo I think there is a problem with this dataset. As far as I can see the time is properly set

![image](https://user-images.githubusercontent.com/1280027/203767592-a14e906b-9389-4e08-b5ac-d7597b8fe09d.png)

@offtherailz do you have a chance to check that please?

**Comment by offtherailz** [comment]
I investigated on MapStore possible bugs a lot, but then I noticed that Date is in Date format (without hours), while Time is full iso string.
This doesn't happens in GML response. It looks an issue of GeoServer.

GML: 

https://gs-stable.geosolutionsgroup.com/geoserver/mapstore/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=mapstore%3ATypes&maxFeatures=50

**Comment by offtherailz** [comment]
I found several issues in editing, so I had to fix them all. Moreover I made the editor robust enough to read the date also in the wrong format provided by GeoServer.

**Comment by tdipisa** [comment]
@offtherailz thank you so muck. Just pay attention to [this](https://github.com/geosolutions-it/MapStore2/pull/8844#issuecomment-1330783136).

**Comment by offtherailz** [comment]
Ok @tdipisa . I've seen "2022.02.xx-c040" in the title of the PR linked and I was confused. Thank you for correcting me :+1:
