### ISSUE TITLE
Allow full range startup configuration for timeline 

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#8766]
## Description

The timeline plugin can be configured to have different initial setups. Now by default it snaps to a single time, the nearest to `now`. We should allow to start with range, instead of single time, and to automatically include the whole interval on startup. 

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Acceptance criteria
- [x] As an administrator I can configure the timeline plugin to start as a range, instead of a single value (name the config property and the values accordingly with the name of the variable used for it. E.g. if it is mode, set "initialMode": "range").
- [x] As an adminsitrator I can configure the timeline plugin to snap on startup to the full size of the guide layer, if any. the property is "initialSnap": "now"|"fullRange" (second makes sense only if initialMode: "range".
- [x] As an adminsitrator, I can configure the timeline plugin display a reset to the initial state, that means to snap to full range or now, depending on the plugin configuration. 
    - [x] By default the button is not pesent, and it will appear only if I add the configuration "resetButton" true.
 - [x] Properly document the new options of the timeline plugin

**Comment by offtherailz** [comment]
@tdipisa I'm assigning release 2023.01.00, hope it is good

**Comment by dsuren1** [comment]
Mockup [here](https://github.com/geosolutions-it/npa-cgg/issues/282#issuecomment-1302140507)

**Comment by dsuren1** [comment]
Updated reset button feature [here](https://github.com/geosolutions-it/npa-cgg/issues/282#issuecomment-1315245145)
