### ISSUE TITLE
Exclude some layers from timeline 

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#8767]
## Description
To avoid a lot of layers in the timeline, some layers can be configured to not appear in timeline, even if syncronized with time selected.
If you have a lot of data with the same dates, this will simplify the visualization (10 layers with the same point may show 10 lines in the timeline, all with the same points, the UI is redundant). 

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Acceptance criteria
- [x] Prepare a mockup first
- [ ]  As a user, if a layer has a time dimension, I can hide it from timeline settings tool. The timeline settings panel has  a new "layers" panel. in this panel you can see the list of layers. Each layer has a checkbox, 
    - [ ] By default every checkbox is checked. This means that the layer is visible in the timeline.
    - [ ] If the checkbox is unchecked the layer disappears from the timeline. 
    - [ ] If I check the checkbox, the layer appears again in the timeline.
    - [ ] The guide layer can not be hidden.
    - [ ] At least one layer must stay on the timeline. 
    - [ ] Anyway the layers will all be in sync with the current time, even if hidden.
    - [ ] If I save the map and reload, the status of the checkboxes must be persisted.

**Comment by dsuren1** [comment]
@offtherailz 
Basic mockup of the layer selector in timeline settings. Kindly let me know if needs some refinement.

![time_layers](https://user-images.githubusercontent.com/26929983/200324908-63ac823b-c693-4e95-9fbe-099a42961552.jpg)

**Comment by offtherailz** [comment]
ok @dsuren1 keep in mint to 
- store the hidden ones list (new layers should be visible by defalut)
- make the it scrollable when the layers when overflows.

**Comment by dsuren1** [comment]
**Updated mockup**
![image](https://user-images.githubusercontent.com/26929983/201946846-14f94d31-8c3b-4bfd-9d6c-6721dba6bb5a.png)
