### ISSUE TITLE
Attribute table does not draw new features on layers with point geometries

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#8781]
## Description

![image](https://user-images.githubusercontent.com/19175505/199997605-d58fa675-31ef-46cf-a7f6-c2b12f1ac8fa.png)

## How to reproduce

-  login in mapstore as admin
-  add from catalog the `Types` layer from WMS gs-stable
- edit the layer in with the attribute table
- add a new row and the add a new feature geometry

*Expected Result*

- The client should allow to add the new geometries without breaking the app

*Current Result*

- The client shows an error in console and it's not possible to add the new row

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

This is affecting master, qa (2022.02.xx) and the release

**Comment by tdipisa** [comment]
@alex-fko we need a quick investigation here to see what introduced this regression.

**Comment by alex-fko** [comment]
This regression is introduced by: https://github.com/geosolutions-it/MapStore2/issues/8148
I didn't trace down what exactly changes delay added by commit to produce this behavior, but that's the point when error starts to appear upon feature drawing.

**Comment by alex-fko** [comment]
It's possible to prevent error by modifying condition at https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/map/openlayers/DrawSupport.jsx#L720 to check geometry type only when it exists or rely on `drawMethod` like it was in older revisions. Though, it is requires an extra check for side-effects if `GeometryCollection` is a geometry type for the edited layer.
