### ISSUE TITLE
Map view on Sidebar cover the Burger Menu

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#8783]
On Context, if the Burger Menu are enable, the Map view button cover the Burger Menu button.
![nnnn](https://user-images.githubusercontent.com/56537133/200028525-91771b55-ef72-4d1a-8884-3b684f682c20.png)

**How to Reproduce**
- Open [this context](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/11)

*Current Result*
 the Map view button cover the Burger Menu button

*Expected Result*
The Burger Menu button is visible and the Map view button is on the Options list

**Comment by allyoucanmap** [comment]
@ElenaGallo could you provide steps on how to reproduce this?
If we open the linked context the sidebar is not visible so it's not possible to replicate it



![Image](https://user-images.githubusercontent.com/19175505/213703181-fdad5866-91f9-4aab-b973-7ef31bc2d65b.png)

**Comment by ElenaGallo** [comment]
@allyoucanmap you should now see the sidebar covering the burger menu. In any case, just create a context and enable the burger menu and the map viewer plugin.

**Comment by Gaetanbrl** [comment]
hi,
> you should now see the sidebar covering the burger menu. In any case, you can create a context and enable the burger menu and the map viewer plugin.


i get some trouble around this issue.

- If i deactivate SideBar, ma custom panel is hover search bar.

**BurgerMenu is end of life @ElenaGallo  ?**

**Comment by Gaetanbrl** [comment]
Oh and i forgot -> if i deactivate burgermenu to only keep sidebar, my sidebar is hover my custom panel

**Comment by Gaetanbrl** [comment]
in addition,

i'd create a simple extension from SampleExtension (master branch) and [official doc](https://docs.mapstore.geosolutionsgroup.com/en/latest/developer-guide/extensions/)  this morning and search toolbar is always in front of my panel : 

![image](https://user-images.githubusercontent.com/16317988/214024198-f48ec012-f4ba-40c3-8337-0b768599e6be.png)


Code is very simple.

```
const Extension = ({dockStyle, active, size = 550, onToggleControl}) => {
    return (<ResponsivePanel
        containerStyle={dockStyle}
        containerId="SampleComponent-container"
        containerClassName="dock-container"
        className="SampleComponent-dock-panel"
        open={active}
        position="right"
        size={size}
        bsStyle="primary"
        glyph="maps-catalog"
        title={"SampleComponent"}
        onClose={() => onToggleControl()}
        style={dockStyle}
    >
        <h2>SampleComponent</h2>
    </ResponsivePanel>);
};

export default Extension;
```


 The module.jsx : 
 
```
 ...
import { mapLayoutValuesSelector } from "@mapstore/selectors/maplayout";


const MainComponent = compose(
    connect(createStructuredSelector({
        active: state => state.controls && state.controls[name] && state.controls[name].enabled,
        dockStyle: state => mapLayoutValuesSelector(state, { height: true, right: true }, true)
    }), {
        open: () => toggleControl(name, "enabled", true),
        onClose: () => toggleControl(name, "enabled", false)
    })
)(ExtensionComponent);

export default createPlugin(name, {
    component: MainComponent,
    containers: {
        BurgerMenu: {
            name: name,
            position: 6,
            icon: <Glyphicon glyph="maps-catalog" />,
            tooltip: "SampleComponent",
            action: () => toggleControl(name, 'enabled'),
            priority: 2,
            doNotHide: true
        },
        SidebarMenu: {
            name: name,
            position: 10,
            tooltip: "SampleComponent.title",
            icon: <Glyphicon glyph="maps-catalog" />,
            doNotHide: true,
            action: toggleControl.bind(null, name, null),
            priority: 1
        }
    },
    reducers: {reducers},
    epics
});
```

**Comment by tdipisa** [comment]
@Gaetanbrl Thank you for reporting the above. Did you already reported the above in ML? If not please do that since it is the dedicated channel for these things. In general, you can off course mention this and/or other issues if you need. Doing that we will try to provide assistance as soon as possible by opening a dedicated issue (and maybe a more generic one) if needed. This issue is specific to the Map Views tool.

**Comment by Gaetanbrl** [comment]
ok thantk @tdipisa i had already opened an issue (because i dont know if it's the same topic for @ElenaGallo).

I can open a diff list message if you prefer.
