### ISSUE TITLE
Allow to customize QueryPanel panels

### ISSUE THREAD

**Issue by alex-fko** [geosolutions-it/MapStore2#8794]
The current query panel holds only the panels for filtering by attributes, viewport and cross layer.
With this improvement the quick filters panel should allow to customize the view by layer.

### Acceptance Criteria
- [ ] As a developer I want to be able to inject some items in the QueryPanels plugin to customize panels to show when the layer filter is opened on a particular layer
    - [ ] The existing panels (by attribute/viewport/crosslayer) should be optionally set in / out in addition to the new ones.
    - [ ] I can customize the position of each panel (see the print plugin injection system, that provides a similar functionality to add panels in certain position and include/exclude the existing ones. 
    - [ ] The injection comes from another plugin. The plugin will define the target and some options to decide if the tool should be shown for the given layer ("layer name regex") In this case use a filtering system similar to the CustomEditor of the feature grid.
    - [ ] The option must be documented in JSDoc, as well as for the print plugin
- [ ] The support should allow the developer to configure the functionalities [#291](https://github.com/geosolutions-it/npa-cgg/issues/291), [#292](https://github.com/geosolutions-it/npa-cgg/issues/292) and [#293](https://github.com/geosolutions-it/npa-cgg/issues/293)

Here an example of one result we want to obtain. In this case we have, for a given layer, 2 additional panels + the viewport. The attribute filter and the cross-layer filter are not present

![image](https://user-images.githubusercontent.com/1279510/197543965-eea697af-ceea-4da4-9bb5-f9e0989b2c28.png)

Reference issue: https://github.com/geosolutions-it/npa-cgg/issues/290

**Comment by offtherailz** [comment]
We can close this. No need for other test.
