### ISSUE TITLE
Attribute table has highlighted boolean empty cells even if they are not changed

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#8795]
## Description

Attribute table has highlighted boolean type empty cells even if they are not changed

https://user-images.githubusercontent.com/19175505/200610039-9663be92-863d-4839-a40f-b58ca0a5c11a.mp4

## How to reproduce

- login in mapstore as admin
- add from catalog the `Types` layer from WMS gs-stable
- edit the layer in with the attribute table
- double click on an Boolean type empty cell to edit it and keep the value empty

*Expected Result*

- The cell should not be highlighted as changed

*Current Result*

- The cell is highlighted as changed

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by mulondo** [comment]
This issue looks to be fixed, I can't replicate it on my side


https://user-images.githubusercontent.com/22595454/214548468-5b53e853-ff98-408b-a5d2-b61108ee4d9d.mp4

**Comment by tdipisa** [comment]
@mulondo is is perfectly reproducible, but it seems not with all field types but only text ones.

**Comment by mulondo** [comment]
@tdipisa, with which fields can I test it no?

**Comment by allyoucanmap** [comment]
@mulondo just updated the layer, now the string field is empty so you can test it

![image](https://user-images.githubusercontent.com/19175505/214791647-b1871ac3-23e3-41cf-91b2-5ba39415d3af.png)

**Comment by mulondo** [comment]
Alright let me test it again @allyoucanmap

**Comment by mulondo** [comment]
@allyoucanmap, still I can't reproduce the bug, everything seems fine.


https://user-images.githubusercontent.com/22595454/214799503-bc8d66f0-942c-4740-8d6c-a23347632a37.mp4

**Comment by mulondo** [comment]
@allyoucanmap and @tdipisa, I have seen it. It's on the String and Boolean.

**Comment by allyoucanmap** [comment]
@tdipisa as discussed in the PR the boolean and string issues have been split in two different issue so this is the new one
#8958
