### ISSUE TITLE
Implement a MousePosition Component for Leaflet

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#88]
The component should:
 * be enabled / disabled by a specific button on top of the map
 * when enabled, show the current cursor position as coordinates in a specific area on top of the map
 * allow configuration of coordinates type (lat - lon, projected using a particular EPSG)
show a combo to select a new scale and show the current one

**Comment by kappu72** [comment]
Hi Mauro, the last sentence confuses .."show a combo to select a new scale and show the current one".
Do you mean that, when enabled, the MousePosition component should show a select box to change map scale?

**Comment by simboss** [comment]
I think this is a typo. This component should allow to change the CRS and see the mouse coords in a different CRS.

We might want to have the list of target CRS configurable in terms of which items you have, and searchable with autocomplete.

Some examples:
* http://epsg.io/4326/map
* http://openlayers.org/en/v3.4.0/examples/mouse-position.html
* http://mrmufflon.github.io/Leaflet.Coordinates/
* more leaflet plugins [here](http://leafletjs.com/plugins.html)

I'd like to see a proposal before starting the impl.

**Comment by kappu72** [comment]
Hi Simone, [here] (http://www.screencast.com/users/kappu/folders/Default/media/0f001c55-6ab8-4b4f-88aa-287b81d4b769) the component's mockup. 
I suggest to use a combobox with autocomplete to select coordinate reference system. 
The selection of a c.r.s. activate the printing of mouse position in the printing area. If none c.r.s is  selected, the component is disabled and the printing area is hidden.

**Comment by simboss** [comment]
Kappu, I don't like the symbol it is too similar to the use used for the "locate me" function. Use a circle with a cross in it otherwise.

Aside, it is not clear to me how you want to show the coordinates. Can you update the mockup?

**Comment by kappu72** [comment]
Simo, maybe the printing area in the top center of the map with semitransparent blue background color isn't big enough. For the icon I agree, too similare to locate me  icon.

**Comment by kappu72** [comment]
Changed Icon [Mockup](http://www.screencast.com/users/kappu/folders/Default/media/8c61be4a-df61-498a-aec9-d6e4f13d41dc)

**Comment by simboss** [comment]
Nice, I would put it next to the target icon though.

Aside from this, I think we can move on.

**Comment by offtherailz** [comment]
Ok for me too. Make the position of the coordinate box configurable (via css or style).

**Comment by kappu72** [comment]
[Updated](http://www.screencast.com/t/fb1pGIWxUOd)

**Comment by kappu72** [comment]
Hi all, for this component we need a combobox with suggestion and filter capabilities.
If we don't want to rebuild the wheal I suggest this  [package](http://jquense.github.io/react-widgets/docs/#/getting-started) of widgets for React

**Comment by mbarto** [comment]
We are currently using react-bootstrap as a basic widget set. If you can't find anything similar in that library, please move on with the one you suggest.
