### ISSUE TITLE
QA is not showing some widgets for certain dashboards

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#8800]
## Description

Some widgets are not visible in QA. For the moment only [21694](https://qa-mapstore.geosolutionsgroup.com/mapstore/#/dashboard/21694) seems affected. 

## How to reproduce

-  Open [this](https://qa-mapstore.geosolutionsgroup.com/mapstore/#/dashboard/21694) in QA

*Expected Result*

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/ca282e74-1e49-4a19-b58f-22a0fe3b51c4)

*Current Result*

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/db503e41-dd74-4376-9dc4-be58bfcf100a)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by alex-fko** [comment]
This problem affects not only dashboards, but also some maps, e.g. https://qa-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/10358

It caused by the changed structure of chart configuration introduced with #8684. Problem appears because we share backend for DEV and QA, while QA doesn't yet have support of the mentioned changes. Therefore, chart widgets with the new configuration format cannot be loaded, which causes this issue and issue mentioned in #8801

**Comment by tdipisa** [comment]
@alex-fko thank you so much for the investigation.

**Comment by tdipisa** [comment]
@randomorder we have tho start using a dedicated DB for DEV and QA. Can you please duplicate the existing one of DEV so that we can use it for QA?

**Comment by randomorder** [comment]
the new database is called `geostore_mapstore2_qa` @tdipisa

**Comment by tdipisa** [comment]
Wonderful @randomorder thank you so much. @offtherailz can you please change the QA config accordingly?

**Comment by offtherailz** [comment]
I changed data dir with this 
https://github.com/geosolutions-it/mapstore-datadir/commit/f10f8958ff06cc03b47c628781bbfd600bf179f0 
Then runned the QA datadir task
http://build.geosolutionsgroup.com/view/MapStore/job/MapStore/view/MapStore%20QA/job/MapStore2-QA-DataDir/
and the QA deploy (doing a rerun last)
http://build.geosolutionsgroup.com/view/MapStore/job/MapStore/view/MapStore%20QA/job/MapStore2-QA-Deploy/

I created this QA only map named "QA only map"
https://qa-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/42309

It is not reachable on dev :

https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/42309

(future map creation may use the id, so the map could be reachable, but make sure that is titled "QA only map" from TOC).


**Anyway** I notice that the map is infinite loading. It should instead prompt login OR tell "not found" . It looks a regression.
We should open an issue for this. @tdipisa

**Comment by tdipisa** [comment]
@offtherailz 

> Anyway I notice that the map on dev is infinite loading.
It should instead prompt login OR tell "not found" . It looks a regression. We should open an issue for this. @tdipisa

I don't know what you did but I created a new map in QA now and on DEV I've this 

![image](https://user-images.githubusercontent.com/1280027/201675765-ef17517b-2766-4b9b-bf9e-dbbfd4d464eb.png)


it seems correct tbh

**Comment by tdipisa** [comment]
@alex-fko we have a dedicated DB now. Can you please amend the following two in QA please?

https://qa-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/10358
https://qa-mapstore.geosolutionsgroup.com/mapstore/#/dashboard/21694

Please do a quick check if there are other resources for which the configuration need to be adjusted (eg. in the first page).
@ElenaGallo if you are aware of other resources (maps containing widgets or dashboards) recently updated (eg. in the last 7-10 days) in DEV let us know.

**Comment by alex-fko** [comment]
@tdipisa I've updated both resources to make charts widgets visible. I didn't notice similar problems in first 12-16 featured maps and first page of Maps/Dashboards in contents section.

**Comment by offtherailz** [comment]
@ElenaGallo We have to clean up all the new dashboards from QA, because they have been created / edited with the new MapStore.
