### ISSUE TITLE
Test related to DateTimePicker utc time is failing

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#8808]
## Description

The unit test related to `DateTimePicker test calendarSetHours disabled option` seems to fail based on the current localization of the machine running the test probably due to [missing hour time in the data input](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/misc/datetimepicker/__tests__/DateTimePicker-test.js#L145) 

We need to investigate based on the problem reported in the [mailing list](https://groups.google.com/g/mapstore-users/c/lB-u6y1r9Eo/m/94Qa0Hl2AgAJ) and make the [test](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/misc/datetimepicker/__tests__/DateTimePicker-test.js#L144-L157) more stable

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@alex-fko this seems connected to #8745. The fix is for you.
