### ISSUE TITLE
The video and web page are not visible on a geostory

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#8811]
## Description

Video and web page are not visible in a geostory because they violate the Content Security Policy

Error on console  (for a Video):
> Refused to frame 'https://www.youtube.com/' because it violates the following Content Security Policy directive: "frame-src https://dev-mapstore.geosolutionsgroup.com http://dev-mapstore.geosolutionsgroup.com https://demo.geo-solutions.it http://demo.geo-solutions.it".
> Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('<URL>') does not match the recipient window's origin ('null').

## How to reproduce

-  Open [this geostory](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/geostory/42326/section/7313978b-4ab6-4039-a11f-7807384333f5)
- Scroll done on a Media section and then on Web Page section

*Expected Result*

The video and the web page are visible

*Current Result*

The two sections are not visible

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@allyoucanmap can you please do a quick investigation?

**Comment by allyoucanmap** [comment]
@tdipisa I noticed the [Content-Security-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) response header on **dev** and **qa** that seems to cause the issue

![image](https://user-images.githubusercontent.com/19175505/201715172-4122fc50-0d6c-4e99-aeef-f6e8e1250c7d.png)

This header is not present on mapstore **stable** demo so the embedded resources are working there

- https://mapstore.geosolutionsgroup.com/mapstore/#/geostory/7726

![image](https://user-images.githubusercontent.com/19175505/201715959-b84b6514-e7d2-405b-8128-493136046809.png)

**Comment by randomorder** [comment]
no recent changes. We'll have a look and add the header as needed

**Comment by randomorder** [comment]
Internal devops ticket here: https://github.com/geosolutions-it/DevOps/issues/1113

**Comment by tdipisa** [comment]
it is working now. thank you @randomorder
