### ISSUE TITLE
gs-stable gives an error if the catalog is opened by a new user

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#8812]
## Description

On  QA the gs-stable gives an error if the catalog is opened by a new user. 
Error on console:
> Access to XMLHttpRequest at 'https://gs-stable.geo-solutions.it/geoserver/wms?service=WMS&version=1.3.0&request=GetCapabilities&authkey-qa=0fa780a3-5d0a-48f3-8421-510d27dbf87d' from origin 'https://qa-mapstore.geosolutionsgroup.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
 > GET https://gs-stable.geo-solutions.it/geoserver/wms?service=WMS&version=1.3.0&request=GetCapabilities&authkey-qa=0fa780a3-5d0a-48f3-8421-510d27dbf87d net::ERR_FAILED 500

## How to reproduce

-  Create new user 
- Login with the new user
- Open a new map
- Click on Catalog

*Expected Result*

The default gs-stable services are available on catalog tool

*Current Result*

The default gs-stable services are not available on catalog tool

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
This is a limitation with stable too. Actually gs-stable has the integration with MapStore dev database only. 
This because geoserver supports only one "Active role service" service at time, even if we can configure more.

**Comment by tdipisa** [comment]
You are right. If so I think we should configure both role services and I think we should activate the QA one only when we need QA for testing. We will see then if/when we can provide a new dedicated GS instance for QA.

**Comment by offtherailz** [comment]
I configure 2 user services (to catch also new users created in qa) and 2 role services (to switch between them).
I also associated the `geostore-qa` authkey to the `geostore-qa` user service (we should do the same for `mapstore-stable` users). 
So association using the auth key should be consistent. The only issue will concern the authorization and we will switch on needing.

**Comment by offtherailz** [comment]
If this test passes, we can close this issue. Isn't it?
