### ISSUE TITLE
Update to Log4j2 and usage of dependenciesManagement

### ISSUE THREAD

**Issue by taba90** [geosolutions-it/MapStore2#8816]
## Description

This issue is to track on mapstore board the upgrade to log4j2 and the generalization of usage for dependenciesManagement in projects pom.xml files.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by taba90** [comment]
Opened pr on master branch for:
- mapstore https://github.com/geosolutions-it/MapStore2/pull/8815
- geostore https://github.com/geosolutions-it/geostore/pull/316
- printlib https://github.com/geosolutions-it/mapfish-print/pull/59
- proxy https://github.com/geosolutions-it/http-proxy/pull/68

**Comment by taba90** [comment]
pr on geoorchestra will be opened if this modifications will ever land on stable branch since georchestra is not using master.

**Comment by offtherailz** [comment]
This issue has been merged #8815. Logs works as expected. So I am going to close it.

**Comment by offtherailz** [comment]
Accepted because logs works as expected
