### ISSUE TITLE
Issue with jenkins jobs

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#8833]
## Description

The builds of MapStore do not seems to run anymore. 

List of failures:

http://build.geosolutionsgroup.com/view/MapStore/job/MapStore/view/MapStore/job/MapStore2-QA-Build/33/
http://build.geosolutionsgroup.com/view/MapStore/job/MapStore/view/MapStore%20Stable/job/MapStore2-Stable-Build/69/
http://build.geosolutionsgroup.com/view/MapStore/job/MapStore/view/MapStore%20DEV/job/MapStore2-Dev-Build/178/

Now they seems to be back to normal (some workflows like dev and stable build now runs). Need to investigate.

**Comment by tdipisa** [comment]
@offtherailz is there effectively a blocker here. It doesn't seems to me. Should we need this issue open?

**Comment by offtherailz** [comment]
For sure we can downgrade the priority of this issue
Anyway, the problem seems to be disappear. The incident has happened, but can not be replicated anymore, so if you agree we can close this issue.

**Comment by tdipisa** [comment]
> For sure we can downgrade the priority of this issue Anyway, the problem seems to be disappear. The incident has happened, but can not be replicated anymore, so if you agree we can close this issue.

ok @offtherailz, I'm going to close this for now. Let's keep an eye on that to open a new issue if needed in the future.
