### ISSUE TITLE
Empty Language parameter in printing legend seems to be refused by some servers. 

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#8871]
## Description

MapStore by default sends a LANGUAGE parameter for the legend generation in print plugin. This parameter is empty if the i18n for the source is not configured. 

https://github.com/geosolutions-it/MapStore2/blob/ffc8d215d866c27b89ec5762b5602d349b99daa3/web/client/utils/PrintUtils.js#L551

Anyway, sending and empty string for it seems to make some GeoServers rise an error. 

```xml
<ows:ExceptionReport xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" xsi:schemaLocation="http://www.opengis.net/ows https://geoportail.lepuyenvelay.fr/geoserver/schemas/ows/1.0.0/owsExceptionReport.xsd">
<ows:Exception exceptionCode="NoApplicableCode">
<ows:ExceptionText>A Language parameter was provided in the request but it cannot be resolved to an ISO lang code. Parameter value is empty while supported languages are hun,swe,dut,est,fin,ice,gsw,rum,pol,cze,dan,nor,por,ger,lit,ita,fre,gre,eng,lav,gle,spa,hrv,mlt,slo,bul,slv</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>
```

See this mailing list for the example and the details: 

https://groups.google.com/g/mapstore-users/c/PZWlYsDrEMY

## How to reproduce
-  Add a layer to the mapstore map from the GeoServer that has this problem (I did my test with [this](https://geoportail.lepuyenvelay.fr/mapstore/#/context/Services) adding as WMS source `https://geoportail.lepuyenvelay.fr/geoserver/ows` , adding the parkings layer as for the mailing list )
- Try to print the map with the new layer, adding the legend. 

*Expected Result*
- The legend is present

*Current Result*
- The legend is not present
- Opening the URL generated my mapstore  for the legend (from `create.json` request body) you have the error reported. 
- 

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

- It works on GeoServer 2.21 (gs-stable)
- server `https://geoportail.lepuyenvelay.fr/geoserver/ows` has other **new** problems with printing that need to be investigated (see comments below https://github.com/geosolutions-it/MapStore2/issues/8871#issuecomment-1983731010 )

**Comment by jusabatier** [comment]
> MapStore by default sends a LANGUAGE parameter for the legend generation in print plugin. This parameter is empty if the i18n for the source is not configured.

Is there a way to specify this in Mapstore config ? (-> force it to 'fre' on our platform for example)

**Comment by offtherailz** [comment]
The fix applied looks to solve the issue on a similar environment, but in the meanwhile, the original server used for this test `https://geoportail.lepuyenvelay.fr/geoserver/ows` seems to not be printable at all (neither the map and legend).

This looks to be a separate issue and it may require a different investigation/issue @tdipisa

**Comment by tdipisa** [comment]
Reopening due to wrong backport provided for v2024.01.00. Backport PR available at 
https://github.com/geosolutions-it/MapStore2/pull/10443
