### ISSUE TITLE
MapStore `AvailableStyles` component won't filter styles

### ISSUE THREAD

**Issue by ale-cristofori** [geosolutions-it/MapStore2#8911]
Reproduction steps:

1. Log-into MapStore
2. Load a map with overlay WMS layers on it, [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/37044) on DEV is an example.
3. On the TOC component select the `Manhattan (NY) points of interest`, click on the `layer settings` button and then on the `styles` tab, the colour picker icon.
4. The `AvailableStyles` component will show with all available styles for the selected layer, on the top there is a text bar to filter the layer based on their attributes (Title, abstract, ect), if any test is typed in the text box the filtering won't work and the layers list will remain the same, unfiltered (see below) 

The investigation showed the bug might be related to the JS array function `.filter` not filtering correctly. 
see 
https://github.com/geosolutions-it/MapStore2/blob/77dad25fbae83191d2661eeda147a591831decda/web/client/components/styleeditor/StyleList.jsx#L83

![Image](https://user-images.githubusercontent.com/14953970/212638342-c54a31b6-8a0c-4fce-9c59-38a7414c65b5.gif)

**Comment by ale-cristofori** [comment]
@allyoucanmap, this feature should be backported to client's branch https://github.com/geosolutions-it/MapStore2/tree/C047-2021.02.xx. Shall your team take care of it?

**Comment by ale-cristofori** [comment]
@ElenaGallo, where are you with tests on this ?

**Comment by allyoucanmap** [comment]
@ale-cristofori backport merged https://github.com/geosolutions-it/MapStore2/pull/8947
