### ISSUE TITLE
Leader line is not correctly positioned when relative from ground

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#8920]
## Description

This issues seems related to a wrong computation of the leader line when relative to ground
![image](https://user-images.githubusercontent.com/19175505/213487943-0bdf34cc-72b4-4d69-890b-42a0b9b3aa82.png)

## How to reproduce

-  open this [map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/dem3d/42640) (click on 3D button and then open the style editor for the marker layer to ensure the marker is rendered)

*Expected Result*

- the line points should start from terrain and reach the marker

*Current Result*

- the line points starts from 0 and reach the initial position of the marker (similar to Height reference from ground = none)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

From an initial investigation it seems that the `getLeaderLinePositions` function in the CesiumStyleParser has some problem:

- we should check if the terrain is ready before use the internal functions
- sampleTerrainMostDetailed and sampleTerrain need an array of cartographic positions instead of a single position
- we need to check if the heightReference is relative and add the z value to the cartographic height of the point

This should be the correct function but must be double checked in development phase
```js
function getLeaderLinePositions({
    map,
    cartographic,
    heightReference
}) {
    return new Promise(resolve => {
        const isRelative = heightReference === 'relative';
        const drawLine = (zValue) => {
            resolve(
                zValue === cartographic.height
                    ? undefined
                    : Cesium.Cartesian3.fromRadiansArrayHeights([
                        cartographic.longitude,
                        cartographic.latitude,
                        zValue,
                        cartographic.longitude,
                        cartographic.latitude,
                        cartographic.height + (isRelative ? zValue : 0)
                    ])
            );
        };
        const terrainProvider = map?.terrainProvider;
        if (!terrainProvider) {
            drawLine(0);
            return;
        }

        const readyPromise = terrainProvider.ready
            ? Promise.resolve(true)
            : terrainProvider.readyPromise;

        readyPromise.then(() => {
            const promise = terrainProvider?.availability
                ? Cesium.sampleTerrainMostDetailed(
                    terrainProvider,
                    [new Cesium.Cartographic(cartographic.longitude, cartographic.latitude, 0)]
                )
                : Cesium.sampleTerrain(
                    terrainProvider,
                    terrainProvider?.sampleTerrainZoomLevel ?? 18,
                    [new Cesium.Cartographic(cartographic.longitude, cartographic.latitude, 0)]
                );
            if (Cesium.defined(promise)) {
                promise
                    .then((updatedPositions) => drawLine(updatedPositions?.[0]?.height ?? 0))
                    .catch(() => drawLine(0));
            } else {
                drawLine(0);
            }
        });
    });
}
```

Note: there is also a problem with the italian translation of the `Height reference from ground` that must be fixed:

- None ->Nessuno
- Relative -> Relativo
- Clamp -> A terra

![image](https://user-images.githubusercontent.com/19175505/213522631-38aabbda-ed58-4236-bfc8-841dfbf30eb8.png)

**Comment by mulondo** [comment]
Hello @allyoucanmap, I can't replicate the issue. I would like to know what I am missing. Watch this.



https://user-images.githubusercontent.com/22595454/216548710-4631efae-962f-439d-a232-613759343618.mp4

**Comment by tdipisa** [comment]
@mulondo you have opened the style editor of the wrong layer....

**Comment by mulondo** [comment]
> @mulondo you have opened the style editor of the wrong layer... please, look better at the description.

It's good now
