### ISSUE TITLE
How Add 3D Terrain Layer clear explanation

### ISSUE THREAD

**Issue by Magio94** [geosolutions-it/MapStore2#8938]
Dears,

we need to implement a raster layer that shows the 3D Elevation inside the Map on which to insert the Geometries of Buildings always in 3D. 
We started trying to follow the instructions at the following links: https:///docs.mapstore.geosolutionsgroup.com/en/latest/developeloper-guide/maps-configuration/#terrain and https///docs.mapstore.geosolutionsgroup.p.com/en/latest/developer-guide/mapstore-migration-guide/using-terrain-layer-type-to-define-3d-map-elevation-profile
We installed the plugin DDS/BIL plugin correctly and we used geoserver as service provider setting everything as required in the instructions.
 
We then went inside the pluginsConfig.json file and tried with various solutions to insert the layer. For example, we tried to insert it as a terrainprovider, then inside the code as additonallayers and finally as a base. Although the MapStore ran without errors we could not under any circumstances to view the dem. 

Is it possible to have precise instructions on how to carry out the operation?

**Comment by Magio94** [comment]
What is the MS ML? The links you inserted are exactly the ones I used as reference

**Comment by simboss** [comment]
**M**ap**S**tore **M**ailing **L**ist

**Comment by tdipisa** [comment]
Hi @Magio94 
> What is the MS ML? 

you can find what you need about the MS mailing list [here](https://github.com/geosolutions-it/MapStore2#communication)

> The links you inserted are exactly the ones I used as reference

Did you add the needed configuration in localConfig.json as indicated? I saw you mentioned pluginsConfig.json instead.
