### ISSUE TITLE
Ability to expand the TOC at context loading

### ISSUE THREAD

**Issue by jusabatier** [geosolutions-it/MapStore2#8953]
## Description
As discussed here : https://groups.google.com/g/mapstore-users/c/-98PPR3Ml8s

It could be a good enhancement to have the ability to configure the TOC plugin to be expanded on context load.

## Acceptance criteria

- [ ] Have some config option in TOC plugin to expand the TOC on load

**Comment by allyoucanmap** [comment]
@tdipisa we included the [defaultOpen](https://github.com/geosolutions-it/MapStore2/blob/2024.01.xx/web/client/plugins/TOC/index.js#L569) internal config that can be enabled by the UI (conetxt menu) or in cfg of localConfig. I just noticed that the JSDoc is missing to describe how to configure it in the plugin cfg so this cannot be closed.

**Comment by tdipisa** [comment]
@allyoucanmap ok thank you. Can I please ask you to provide the missing JS doc?
