### ISSUE TITLE
Map Sync issue

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#8997]
## Description

The map sync issue seems to not work as expected.

## How to reproduce

![adv_search_sync_,map](https://user-images.githubusercontent.com/1280027/222501649-22f1c605-e795-4887-ab8d-cc65a27365ea.gif)

![adv_search_sync_,map_2](https://user-images.githubusercontent.com/1280027/222501665-971d55dc-1a5b-437c-9edf-42043aa27356.gif)

*Expected Result*

If activated it should remain active after using the Advanced Search in theory. If active by default, there should not be the need to click twice to put in sync the map.

*Current Result*

- If enabled by default, you need to click twice on it to put in sync the map. 
- If not enabled by default when you toggle it then it is toggled off  as soon ad a filter is defined with the Advanced Search. It looks like not expected, is this a behavior introduced for some reason?

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by allyoucanmap** [comment]
> It looks like not expected, is this a behavior introduced for some reason?

There are some changes applied in the past to the feature grid that are causing this unexpected behaviors, in particular following PRs:
- https://github.com/geosolutions-it/MapStore2/pull/6155 this PR introduced a behavior that [deactivates the map sync](https://github.com/geosolutions-it/MapStore2/blob/c0697db6fb454110aa3b94febded6934ffb8000c/web/client/epics/featuregrid.js#L1103-L1108) every time the feature grid has been closed, this include also when the advanced filter is enabled (at that point the feature grid is closed)
- https://github.com/geosolutions-it/MapStore2/pull/8531 this PR introduced some changes on the structure of the feature editor plugin, in particular the asynchronous import of the grid when the component is actually open. This update changes the way this component mount/unmount affecting the [setSyncTool](https://github.com/geosolutions-it/MapStore2/blob/c0697db6fb454110aa3b94febded6934ffb8000c/web/client/plugins/featuregrid/FeatureEditor.jsx#L304-L327) that represents the initialization of the map sync.

We should review the workflow of the map sync tool focusing on following steps:
- do not deactivate the map filter every time the feature grid has been closed but instead improve the [isSyncWmsActive](https://github.com/geosolutions-it/MapStore2/blob/c0697db6fb454110aa3b94febded6934ffb8000c/web/client/selectors/query.js#L70) selector to be true only if the feature grid is open:
  - remove the [deactivateSyncWmsFilterOnFeatureGridClose](https://github.com/geosolutions-it/MapStore2/blob/c0697db6fb454110aa3b94febded6934ffb8000c/web/client/epics/featuregrid.js#L1103-L1108) epic and
  - change selector to  eg.  `export const isSyncWmsActive = (state) => state?.featuregrid?.open && get(state, "query.syncWmsFilter", false);`
- review how we store the `enableMapFilterSync` cfg in the state. We should not update this property every time but only when we open the feature grid from the TOC toolbar (it should be the `LAYERS:BROWSE_DATA`)
- finally we need to ensure that the map sync functionality is working and consistent with the state button in the toolbar so we need to initialize it every time we open the feature grid if the map sync is enabled in the state, something like this:
```js
export const activateSyncWmsFilterOnFeatureGridOpen = (action$, store) =>
    action$.ofType(OPEN_FEATURE_GRID)
        .filter(() => isSyncWmsActive(store.getState()))
        .switchMap(() => {
            return Rx.Observable.of(startSyncWMS());
        });
```

All the above codes is part of an investigation so it needs to be verified and validated during the development
