### ISSUE TITLE
[Print plugin] Layers with visibility scale limits do not print if "useFixedScales" is true

### ISSUE THREAD

**Issue by catmorales** [geosolutions-it/MapStore2#8998]
## Description
Layers with visibility scale limits do not print if "useFixedScales" is  true
Version : 
*mapstore2georchestra* : [2022.02.00-geOrchestra](https://github.com/georchestra/mapstore2-georchestra/commits/2022.02.00-geOrchestra)[(f3ce6b9e)](https://github.com/georchestra/mapstore2-georchestra/commit/f3ce6b9eb6f684bc0932b54af7738e965d8c26c2)
*mapstore2* : [2022.02.xx](https://github.com/geosolutions-it/MapStore2/commits/2022.02.xx)[(15c07932)](https://github.com/geosolutions-it/MapStore2/commit/15c079322f4ce44f73f957bd145a1bf209c695f2)
Print plugin configuration:
```
{
  "cfg": {
    "useFixedScales": true,
    "mapPreviewOptions": {
      "enableScalebox": true
    },
    "outputFormatOptions": {
      "allowedFormats": [
        {
          "name": "PDF",
          "value": "pdf"
        },
        {
          "name": "PNG",
          "value": "png"
        }
      ]
    },
    "overlayLayersOptions": {
      "enabled": true
    },
    "overrideOptions": {
      "geodetic": true
    }
  },
  "override": {}
}
```
config.yaml configuration:
```
#==========================================================================
# Formats
# added for migration to 2022.02.00 version
#==========================================================================
formats:
  - '*'

#===========================================================================
# allowed DPIs
#===========================================================================
dpis:
  - 96
  - 150
  - 300

#===========================================================================
# the allowed scales
# catherine: ne pas mettre plus de 23 échelles
#===========================================================================
scales:
  - 100
  - 250
  - 500
  - 1000
  - 2000
  - 4000
  - 5000
  - 8000
  - 10000
  - 12000
  - 16000
  - 25000
  - 30000
  - 40000
  - 50000
  - 100000
  - 250000
  - 500000
  - 1000000
  - 2500000
  - 5000000
  ...
```
## How to reproduce
* connect to https://portail-test.sig.rennesmetropole.fr/mapstore/#/context/test_catherine
* you see the layer "Arbres d'ornement" which has a max visibility limit to 1:25000
![image](https://user-images.githubusercontent.com/4659829/222749329-dc705002-4c23-4121-8d92-4298d6a46157.png)
* print the map at 1:5000

*Expected Result*
The layer must be printed when printing at a valid scale 

*Current Result*
 The layer "Arbres d'ornement" don't print (not in the preview neither in the pdf)

![image](https://user-images.githubusercontent.com/4659829/222750565-767a263d-869f-47b1-b2ae-408a3b16a794.png)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

This need to be backported also to _2022.02.xx_ so that it will be possible to release _2022.02.02-geOrchestra_ including this

**Comment by tdipisa** [comment]
@catmorales there is a small bug to fix in how scales are handled.  I've already provided feedback about this in https://github.com/georchestra/mapstore2-georchestra/issues/585 that I think is connected.
