### ISSUE TITLE
Loading spinner no longer appear whan saving a resource

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#9034]
## Description

When saving a resource (no matter if it is a map, dashboard or geostory) the loading spinner no longer appear. This is a regression. To check possibly what introduced it.

## How to reproduce

 
![loading_regression](https://user-images.githubusercontent.com/1280027/225682421-41a1cbac-c5aa-446a-8d30-ee537083d357.gif)

*Expected Result*

The loading spinner should appear on bottom-left of the edit properties panel (also from home page).

*Current Result*

The loading spinner doesn't appear.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by dsuren1** [comment]
**Investigation:**
The visibility of the spinner is affected by [this](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/themes/default/less/loaders.less#L59), where the border value is not formulated (it should be `(@icon-size-md/10)`) introduced as part of MS theme update [issue](https://github.com/geosolutions-it/MapStore2/pull/7002).

However I don't see an implementation causing a regression that hides the loading spinner on click `Save` action. Checked it all the way to v2021, if I'm not wrong. Probably present before that.

In this case, I believe this specific scenario of showing spinner on save progress needs to be implemented.

**Comment by tdipisa** [comment]
@dsuren1 

>Anyway, in this case, I believe the code needs to tweaked to address this specific scenario of showing spinner on save progress.

Yes, 

>Maybe also take this time to also disable user interaction on the save modal fields when save is in progress?

It would be better, yes. 

Please provide an estimate in pts for both

**Comment by tdipisa** [comment]
@dsuren1 3pts are too much now. Let's concentrate on fixing the regression by restoring the spinner. Then we can open an issue for the other point.

**Comment by offtherailz** [comment]
Sorry, 
I also did  this change to make it visible and missed a save to delete this change,

```
diff --git a/web/client/components/resources/modals/Save.jsx b/web/client/components/resources/modals/Save.jsx
index 76ac8d227..43cfbd815 100644
--- a/web/client/components/resources/modals/Save.jsx
+++ b/web/client/components/resources/modals/Save.jsx
@@ -144,7 +144,7 @@ class SaveModal extends React.Component {
 
         return (<Portal key="saveDialog">
             <ResizableModal
-                loading={this.props.loading}
+                loading={this.props.loading || this.state?.loading}
                 title={<Message msgId={this.props.title}/>}
                 show={this.props.show}
                 clickOutEnabled={this.props.clickOutEnabled}
@@ -157,7 +157,10 @@ class SaveModal extends React.Component {
                     disabled: this.props.resource.loading
                 }, {
                     text: <span><Message msgId={this.props.saveButtonLabel}/></span>,
-                    onClick: () => { this.onSave(); },
+                    onClick: () => {
+                        this.setState({loading: true});
+                        this.onSave();
+                    },
                     disabled: !this.isValidForm() || this.props.loading || !this.props.canSave
                 }]}
                 showClose={!this.props.resource.loading}
```

This was showing the loader. Effectively the logic doesn't exist. This was a workaround that I forgot to delete while checking.

So summarizing,
The spinner exists, but the logic to show it does not. Moreover the spiller was not working because of the css rule. 
Very strange. 
I'm afraid this was a mix of errors between migration to new save dialogs (old save dialog showed the spinner) and the theme update that created this confusion, that also confused me.

In fact the loading flag is passed, but only to show the details loading.

**Comment by dsuren1** [comment]
> I should try to handle this in the Save modal as much as possible, so we can avoid to handle the loading state for every resource in a lot use cases, for each resource and save tool.

I agree @offtherailz
