### ISSUE TITLE
HTTP Status 404 – Not Found mapstore2 2023

### ISSUE THREAD

**Issue by pete4576** [geosolutions-it/MapStore2#9035]
## Description
I unpack the war file to tomcat webapp but never succeed to open the mapstore webpage. Always getting the next error.
HTTP Status 404 – Not Found
Type Status Report

Message The requested resource [/mapstore] is not available

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

Apache Tomcat/9.0.58 (Ubuntu)

**Comment by tdipisa** [comment]
Hi @pete4576 I've already answered in Mailing List for this. I kindly ask you to use the ML for these kind of things. Thank you so much for using MapStore.
