### ISSUE TITLE
Implement User Management as per MapStore 1

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#905]
See mockups below:

1. [user manager](http://lf.mapstore2.geo-solutions.it/samples/map/manager.html)
2. [add user 1](http://lf.mapstore2.geo-solutions.it/samples/map/add-user-1.html)
3. [add user 2](http://lf.mapstore2.geo-solutions.it/samples/map/add-user-2.html)
4. [add user 3](http://lf.mapstore2.geo-solutions.it/samples/map/add-user-3.html)

**Comment by Gnafu** [comment]
In the mockup there is a "Default map" in the user properties.
Are we using that property anywhere?
