### ISSUE TITLE
Error in Header Content-Type in GeoStore DAO

### ISSUE THREAD

**Issue by buhao75** [geosolutions-it/MapStore2#9056]
## Description
We think we have found a little bug in mapstore. At the end of  following code line a extra " character is added :
'application/json; charset=utf-8"'

https://github.com/geosolutions-it/MapStore2/blob/1b4ab9bcb7050d7c5e1b3c978cfb8d4ae7fd01ae/web/client/api/GeoStoreDAO.js#L295

## How to reproduce
In our environment this " made mapstore crash as we were not using nginx but a ktor based reverseproxy without a header validation. 

*Expected Result*
Mapstore should not send the additional " in the request header

*Current Result*
Mapstore crashes due to the 500 response from geostore

- [x] Not browser related

## Other useful information
First reported here: https://groups.google.com/g/mapstore-developers/c/gLVqc3iQ0JQ

**Comment by offtherailz** [comment]
This issue is not testable on dev server. (only if there is a check on the back-end on valid types.
