### ISSUE TITLE
Query Panel isNull operator is buggy

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#9085]
## Description

The isNull operator in the query panel can not be applied alone

[isNull1.webm](https://user-images.githubusercontent.com/1279510/231113004-5f3fbff6-089c-4764-a8bc-17a0a6926c09.webm)

Event when used in couple, it is basically ignored on the map. 

[screencast-github.com-2023.04.11-11_17_06.webm](https://user-images.githubusercontent.com/1279510/231114672-e9dd3944-842c-4716-a075-909d64bb93d6.webm)

## How to reproduce

Bug 1: The isNull filter can not be applied
-  Add a vector layer to the map
- Open the query panel
- add a isNull filter condition on an attribute

*Expected Result*
- The filter can be applied

*Current Result*
- The filter can not be applied

Bug 2:  The isNull filter is ignored on the map.
- Add a vector layer to the map
- Open the query panel
- Add a isNull filter condition
- Add another attribute filter condition that should produce one or more result 
- Set the filter logic condition to "All" so the filter is something like ATTR isNull AND ATTR = "Alabama" so the filter should produce no results
- Apply the filter 
*Expected Result*
The map should show no result

*Current Result*
The map shows some results, as the "isNull" filter is not applied. 

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by ElenaGallo** [comment]
Hi @offtherailz, the second issue does not seem fixed:


https://user-images.githubusercontent.com/56537133/231217022-8f8b4a0f-7d7f-4c8c-9f47-a4611e5d7014.mov

**Comment by ale-cristofori** [comment]
The wps query sent to retrieve the drop down list unique values result, when there is a `isNull` condition, seems to contain the map filter (not sure it is correct)

```xml
<wps:Execute xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" service="WPS" xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd">
	<ows:Identifier xmlns:ows="http://www.opengis.net/ows/1.1">gs:PagedUnique</ows:Identifier>
	<wps:DataInputs>
		<wps:Input>
			<ows:Identifier xmlns:ows="http://www.opengis.net/ows/1.1">features</ows:Identifier>
			<ows:Title xmlns:ows="http://www.opengis.net/ows/1.1">features</ows:Title>
			<wps:Data/>
			<wps:Reference xmlns:xlink="http://www.w3.org/1999/xlink" mimeType="text/xml" xlink:href="http://geoserver/wfs" method="POST">
				<wps:Body>
					<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" service="WFS" version="1.0.0">
						<wfs:Query typeName="gs:us_states">
						
						<!-- this part seems to be redundant --> 
							<ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
								<ogc:And>
									<ogc:And>
										<ogc:PropertyIsNull>
											<ogc:PropertyName>STATE_NAME</ogc:PropertyName>
										</ogc:PropertyIsNull>
										<ogc:PropertyIsEqualTo>
											<ogc:PropertyName>STATE_NAME</ogc:PropertyName>
											<ogc:Literal>Alabama</ogc:Literal>
										</ogc:PropertyIsEqualTo>
									</ogc:And>
									<ogc:PropertyIsLike matchCase="false" wildCard="*" singleChar="." escapeChar="!">
										<ogc:PropertyName>STATE_NAME</ogc:PropertyName>
										<ogc:Literal>*California*</ogc:Literal>
									</ogc:PropertyIsLike>
								</ogc:And>
							</ogc:Filter>
							<!-- this part seems to be redundant -->
							
							<ogc:SortBy xmlns:ogc="http://www.opengis.net/ogc">
								<ogc:SortProperty>
									<ogc:PropertyName>STATE_NAME</ogc:PropertyName>
								</ogc:SortProperty>
							</ogc:SortBy>
						</wfs:Query>
					</wfs:GetFeature>
				</wps:Body>
			</wps:Reference>
		</wps:Input>
		<wps:Input>
			<ows:Identifier xmlns:ows="http://www.opengis.net/ows/1.1">fieldName</ows:Identifier>
			<ows:Title xmlns:ows="http://www.opengis.net/ows/1.1">fieldName</ows:Title>
			<wps:Data>
				<wps:LiteralData>STATE_NAME</wps:LiteralData>
			</wps:Data>
		</wps:Input>
		<wps:Input>
			<ows:Identifier xmlns:ows="http://www.opengis.net/ows/1.1">maxFeatures</ows:Identifier>
			<ows:Title xmlns:ows="http://www.opengis.net/ows/1.1">maxFeatures</ows:Title>
			<wps:Data>
				<wps:LiteralData>5</wps:LiteralData>
			</wps:Data>
		</wps:Input>
		<wps:Input>
			<ows:Identifier xmlns:ows="http://www.opengis.net/ows/1.1">startIndex</ows:Identifier>
			<ows:Title xmlns:ows="http://www.opengis.net/ows/1.1">startIndex</ows:Title>
			<wps:Data>
				<wps:LiteralData>0</wps:LiteralData>
			</wps:Data>
		</wps:Input>
	</wps:DataInputs>
	<wps:ResponseForm>
		<wps:RawDataOutput mimeType="application/json">
			<ows:Identifier xmlns:ows="http://www.opengis.net/ows/1.1">result</ows:Identifier>
		</wps:RawDataOutput>
	</wps:ResponseForm>
</wps:Execute>
```

**Comment by offtherailz** [comment]
Hi, this is an existing bug, not strictly related to the isNull filter, but general.

Not sure but it is not new to me, so maybe an issue about this already exists. If no, we can create it. 

[screencast--2023.04.12-12_53_52.webm](https://user-images.githubusercontent.com/1279510/231437081-76b02d1a-6d3f-453b-a13b-2ae28b23da90.webm)

**Comment by offtherailz** [comment]
backport ready at 
https://github.com/geosolutions-it/MapStore2/pull/9088

**Comment by ale-cristofori** [comment]
@ElenaGallo, as assessed by @offtherailz. The remaning buggy behaviour, consisting in the extra layer filter applied to the autocomplete wps filter request, is a pre-existing buggy behaviour and we will deal with this last issue separately #9089
