### ISSUE TITLE
Replace react-sortable-items with react-dnd

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/MapStore2#909]
Those libraries are used to provide drag an drop support. 

Library react-sortable-items doesn't work with tables (creates divs around elements) and uses mixins which are deprecated. The library also seems to not be maintained anymore.

Library react-dnd is very complete and provide different backends that implement the drag and drop events. This library is used by many other high level drag an drop libraries.

Links:
- https://www.npmjs.com/package/react-sortable-items
- https://www.npmjs.com/package/react-dnd

**Comment by tdipisa** [comment]
closed for inactivity.
