### ISSUE TITLE
Improving filtering capabilities for widgets

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#9098]
## Description

If a **dashboard widget** is connected to a map it is currently filtered based on the extent of the map view. 
This task is aimed to provide the ability to define a spatial filter for dashboard widgets (charts, table and counter) so that it is possible to define a predefined filter **without** connecting the widget with the map one.

For **viewer widgets** it should also be possible through an option to use the filter already defined with the [Filter Layer](https://docs.mapstore.geosolutionsgroup.com/en/latest/user-guide/filtering-layers/#layer-filter) tool so that you don't need to reconfigure it from scratch for the widget.

## Acceptance criteria

- [ ] Provide the ability to configure a spatial filter for dashboard widgets (UI design included)
- [x] Provide an option for viewer widgets to reuse the filter already defined in [Filter Layer](https://docs.mapstore.geosolutionsgroup.com/en/latest/user-guide/filtering-layers/#layer-filter) tool

## Other useful information

[summary info here](https://docs.google.com/document/d/13FH52OhFst3b4zWWsVaMjeqvJ7aFJF5UcsfBCcbLSmE/edit)

**Comment by MV88** [comment]
> For **viewer widgets** it should also be possible through an option to use the filter already defined with the [Filter Layer](https://docs.mapstore.geosolutionsgroup.com/en/latest/user-guide/filtering-layers/#layer-filter) tool so that you don't need to reconfigure it from scratch for the widget.

This is already in place and currently this option is the one desired because it acts in and with any filters defined in the chart wizard
![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/78db2912-2d55-4041-9211-110715b860b9)

**Comment by MV88** [comment]
@tdipisa @allyoucanmap @offtherailz 
Here is some design proposals:

# proposal 1

- the idea would be to store somehow the spatial filter generated with a dedicated name
- [ideally] one can also upload a vector layer like a geojson or insert through a field a wkt string 
![proposal 1](https://github.com/geosolutions-it/MapStore2/assets/11991428/7d075a3e-950a-4b28-b0ca-9add930f3db0)

# proposal 2
- same as before but the map is on the left and the rest of the dashboard is disabled temporarily
- we can also avoid to disable it
![proposal 2](https://github.com/geosolutions-it/MapStore2/assets/11991428/9ba62648-8c0c-4cce-ad85-24b59cade040)

# proposal 3
- probably the simplest solution, but the user has to redraw everytime the spatial filter and cannot share it between widgets
![proposal 3](https://github.com/geosolutions-it/MapStore2/assets/11991428/9f94ab19-7883-4200-9ad2-fade7778bdc4)

**Comment by offtherailz** [comment]
Here reporting only my ideas:

Now we are using the same query panel of the map, but in this context the map is not present.
The query panel is now pluggable, so we can imagine to create a custom panel to embed a map, similar to the one for the area of interest, but that shows, as well as activated, a map to draw the area of interest. 
From the UI the best approach is to show the map bigger on the right. I think it is feasable (with a Portal or similar), anyway we should give it a try.

**Comment by MV88** [comment]
so the direction is proposal 3, but with a big map in the right
