### ISSUE TITLE
Define guidelines to document React components

### ISSUE THREAD

**Issue by mircobe87** [geosolutions-it/MapStore2#91]
It would be useful to have documentation that describe:
- all the properties for each developed React component;
- what the developed actions mean

We have to define a style for inline documentation and we have to evaluate if look for a useful tool to generate React documentation from code comments.

For example [react-docgen](https://github.com/reactjs/react-docgen) extracts information from React component files and puts it into a JSON file.

**Comment by offtherailz** [comment]
Take a look at this to generate doc using react-docgen. 
https://www.npmjs.com/package/sourcejs-react-docgen

**Comment by offtherailz** [comment]
We could evaluate this https://github.com/onury/docma
This should help to keep a manual using markdown, jsdoc if needed for the future, and it can be published on github pages.

**Comment by tdipisa** [comment]
closed for inactivity.
