### ISSUE TITLE
Maps widget dropdown menu is not visible on embedded dashboard

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#9110]
## Description

On QA only, the maps widget dropdown menu is not visible on embedded dashboard.

https://user-images.githubusercontent.com/56537133/233031019-7759b9fc-8c46-4b62-8752-f3200ecd6f65.mov

## How to reproduce

-  Open [this embedded dash](https://qa-mapstore.geosolutionsgroup.com/mapstore/dashboard-embedded.html#/43005)
- Try to change map on maps widget

*Expected Result*
**On DEV** (**_it is the correct one_**)

![ok](https://user-images.githubusercontent.com/56537133/233031426-8ac32ca2-e0a5-4080-b51c-abe4a209fd4c.png)

*Current Result*

**On prod: the dropdown menu is cut off**
![prod](https://user-images.githubusercontent.com/56537133/233032114-aee3ef3f-e901-4140-9a96-d9275aad2d61.png)

**On QA: the dropdown menu is under the map**
![qa](https://user-images.githubusercontent.com/56537133/233032173-5486df00-2646-4407-9aab-dc59b1e7501e.png)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@dsuren1 

> We can modify on the cadastrapp extension's css or do it on the MS 

I wouldn't like to touch extensions for this. I think MS should be hardened for this.

> Adding maptype reducer to appConfigDashboardEmbedded will set default maptype from localConfig.json

Ok. Since you mentioned #8334, please consider also further changed included with https://github.com/geosolutions-it/MapStore2/pull/9012 that mya be relevant

**Comment by dsuren1** [comment]
> @dsuren1
> 
> > We can modify on the cadastrapp extension's css or do it on the MS
> 
> I've removed the cadastrapp extension from the PROD instance but the issue is still there.

It is now fixed in PROD. WRT to width of the select dropdown
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/26929983/233087635-a3c540a4-0e8d-43b0-984b-79177be48471.png">
