### ISSUE TITLE
Implement language selector tool to use in fields editor

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#9122]
Implement a localized input to allow localization of fields.

The input should support the data format of normal **strings** or object (with "default" + <language-code> as keys for the various strings.

The input should be used in "General" tab of layer settings ( titles ), to also provide a sample of usage.

example 

```json
{
   "default": "String (not localized)", 
   "en-US": "String", 
   "it-IT": "Stringa"
}
```

## Acceptance Criteria

- [ ] The input will edit a string as a string passed as `value`, as well as no translation is performed, through the "onChange" handler
- [ ] If the value is an object, it can be edited as an object, and the object **will not** be converted in string anymore. 
- [ ] In the default input you will see the default value. One option `showCurrent` should enable to display the current language in the main input (if `currentLcoale` is provided as prop to indicate the current locale
- [ ] a `locales` property allows to configure which locales use for translation. If not present, it will use `LocaleUtils.getSupportedLocales()` to identify which locales the application is actually using
- [ ] When the user clicks on the button to localize the string, will be able to edit the default string and all the localized strings in the languages provided (or default list used by the current application). 
- [ ] The input allows to edit the various translations. When the user starts to edit one translation, the string is automatically converted to an object with the shape above.
- [ ] The input is present in TOCItemsSettings plugin --> General tab --> title, instead of the localized titles

**Comment by ElenaGallo** [comment]
Hi @offtherailz @tdipisa, testing this issue I found that in the dash/geostory the layer titles in the map don't keep the translation.

**However, this is not related to the issue because it is also on QA, do I open a new issue?**

https://user-images.githubusercontent.com/56537133/234043679-b3c68608-4617-459a-a995-a5eef4290333.mov
