### ISSUE TITLE
Upload shape file hang and failed.

### ISSUE THREAD

**Issue by changliang** [geosolutions-it/MapStore2#9130]
## Description
When import a map file more than 100MB, it will make the mapstore web page very slow and hang. 
And it failed to save the map.
<img width="929" alt="image" src="https://user-images.githubusercontent.com/3905544/234531998-f73956f2-7845-4345-9b9c-c20210c9d238.png">

## How to reproduce
Use this shape zip file to import in mapstore.

https://drive.google.com/file/d/1A21DF3BFcR5OooxGWQyZiFlquL043dm5/view?usp=share_link

- [x] Not browser related

**Comment by tdipisa** [comment]
@changliang thank you for reporting this. Well, 177MB of SHP ZIP is effectively to much for a web client, I think. Consider that MS is a WebGIS and not a Desktop GIS. Therefore a SHP of that size can easily consume all browsers resources. That's the reason why MS is slow and has problem to process it. The only strategy I can see at the moment to avoid these kind of situations is to prevent the user from importing vector files above a certain size but it is also depending on the machine available resources, I think.
