### ISSUE TITLE
New WFS layers no longer visible in dashboards

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#9139]
## Description

New WFS layers added to a map widget in dashboard are no longer visualized. [QA](https://qa-mapstore.geosolutionsgroup.com/mapstore/#/) and [2023.01.01](https://mapstore.geosolutionsgroup.com/mapstore/#/) are affected, where **an empty CQL_FILTER is included in the GetFeature request** when the map widget is finally added to the dashboard. 

A few more things have been contextually identified also in [DEV](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/):
1. When a WFS layer is selected from the Catalog tool in dashboards a WMS DescribeLayer request is performed . This doesn't break any functionality but is is not correct anyway
2. The Zoom to layer is not enabled but it should be
 
![image](https://user-images.githubusercontent.com/1280027/236473225-c25b2d1b-59a4-4c5b-8df0-aae4919b1727.png)

## How to reproduce

![wfs_dashboard](https://user-images.githubusercontent.com/1280027/236470490-864fbf79-a377-479d-9595-859e20d0c66a.gif)

*Expected Result*

- Layers added from a WFS resource in dashboard should be visualized in Map Widgets
- The WMS DescribeLayer request should not be performed in this case
- The Zoom to layer should be enabled using info retrieved from the Feature Collection

*Current Result*

See _How to reproduce_ above. an empty CQL_FILTER is included in the GetFeature request when the map widget is finally added to the dashboard. 

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by dsuren1** [comment]
Investigation:

- _**CQL_FILTER: undefined**_
    This is not a regression from MS side. And the reason this not happening in DEV is because of this implementation as part of [#8990](https://github.com/geosolutions-it/MapStore2/pull/8990/files#diff-583b74a187f011ba7c105f1ed37a80c174fe22d304640aad417b8d75a80f427dR34)

- _**Zoom to layer is not enabled**_ 
  Caused when layer has `boundingBox` instead of `bbox` prop resulting [`isEpsgSupported`](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/plugins/widgetbuilder/enhancers/handleMapZoomLayer.js#L57) to return `false`, disabling the zoom button to be disabled
