### ISSUE TITLE
Make Map Views tool progress bar more evident

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#9176]
## Description

Improve the visibility of the MapViews tool progress bar to make it more evident. It should be more clear to the final user there is a progress in the views visualization flow. 

![image](https://github.com/geosolutions-it/MapStore2/assets/1280027/84beb1ed-f6c5-41c1-8433-f24687bd20ad)

Let's consider to change color at least for example. any other suggestion is anyway appreciated and can be considered.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by allyoucanmap** [comment]
# Proposal

- different style from the previous steps from the next ones
- different style when the play button is active (green)
- allow to click on steps
- display tooltip on steps

https://github.com/geosolutions-it/MapStore2/assets/19175505/d6869209-01dd-4f63-8ab5-02a15967689c

**Comment by tdipisa** [comment]
@allyoucanmap can we also have a lighter color for the progress bar to have some color contrast?

**Comment by allyoucanmap** [comment]
@tdipisa 

https://github.com/geosolutions-it/MapStore2/assets/19175505/8279c211-2cde-40ba-a5d3-763155ee11b7
