### ISSUE TITLE
Include editing support to allowed user groups 

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#9179]
## Description

As discussed and agreed with #7636 it is required to allow certain editing functionalities depending on the groups the user belongs to. 
At the moment the _editingAllowedRoles_ configuration property is available for [FeatureEditor](https://mapstore.geosolutionsgroup.com/mapstore/docs/api/plugins#plugins.FeatureEditor) and [StyleEditor](https://mapstore.geosolutionsgroup.com/mapstore/docs/api/plugins#plugins.StyleEditor) tools to allow users to use the editing functionality depending on their role (ADMIN or USER) by disabling the pencil icon if the user belongs to a role not granted.

**It is necessary to extend this system to allow editing functions to users also according to the groups they belong to.**

## Acceptance criteria

- [x] The support for a new configuration property named _editingAllowedGroups_ will be included
- [x] That new property can work together with the existing one. For example:

    ```
    "editingAllowedRoles": [
          "ADMIN",
          "USERS"
     ],
    "editingAllowedGroups": [
          "Group 1",
          "Group 2",
          "Group 3",
          ...
     ],
     ```
- [x] That new property will be supported everywhere the existing _editingAllowedRoles_ is managed in the MS code base (that means for both [FeatureEditor](https://mapstore.geosolutionsgroup.com/mapstore/docs/api/plugins#plugins.FeatureEditor) and [StyleEditor](https://mapstore.geosolutionsgroup.com/mapstore/docs/api/plugins#plugins.StyleEditor))
- [x] Both properties should be probably prioritized somehow to properly catch special cases. For example an ADMIN user should be always allowed independently of the group he belongs to. Therefore _editingAllowedGroups_ should be applied only to users with USER role 
- [x] The editing functionality of the Attribute Table ([plugins.FeatureEditor](https://mapstore.geosolutionsgroup.com/mapstore/docs/api/plugins#plugins.FeatureEditor)) can be reached also from the [Identify](https://mapstore.geosolutionsgroup.com/mapstore/docs/api/plugins#plugins.Identify) tool if its `cfg.showEdit` property is set to _true_. That case should be managed accordingly (eg. the pencil icon in Identify panel not available) according the role/group permission rules defined for the [plugins.FeatureEditor](https://mapstore.geosolutionsgroup.com/mapstore/docs/api/plugins#plugins.FeatureEditor) tool (there is already a control in the Identify plugin to check, looking at the Attribute Table state, if the user is allowed or not)
- [ ] If the _Disable editing with Attribute Table_ property is set to True for a layer the editing function in Attribute Table will be disabled at all independently of the value _editingAllowedRoles_ and _editingAllowedGroups_. **ADMIN users can do everything as usual anyway**

## Other useful information
See also #9180

**Comment by dsuren1** [comment]
> If the Disable editing with Attribute Table property is set to True for a layer the editing function in Attribute Table will be disabled at all independently of the value editingAllowedRoles and editingAllowedGroups. ADMIN users can do everything as usual anyway

Will be applicable when https://github.com/geosolutions-it/MapStore2/issues/9180 is implemented

**Comment by dsuren1** [comment]
**Updates**
1. Default value for `editingAllowedRoles: ['ADMIN']` and `editingAllowedGroups: []`
2. User is allowed to edit, if they belong to one of the roles or groups configured
3. Support for 'ALL' roles. Takes highest precedence and allows all users regardless of the role or group the user is
