### ISSUE TITLE
Timeline map sync does not update for time ranges visualization

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#9208]
## Description

The timeline chart does not update based on viewport even if the map sync button is selected.

https://github.com/geosolutions-it/MapStore2/assets/19175505/e0e7537a-6975-43b4-a738-7f88eabfe3ec

## How to reproduce

- open this [map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/44392) (login as admin if needed)
- expand the timeline
- zoom on a feature to exclude the other
- click on map sync

*Expected Result*

The timeline should update the visualization of time intervals based on the viewport of the map

*Current Result*

The timeline does not update the visualization of time intervals based on the viewport of the map

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

The sync issue it seems related to inconsistent state of the time domain property. The timeline updates the new range data inside the [updateRangeDataOnRangeChange](https://github.com/geosolutions-it/MapStore2/blob/53713aeb41af739abebb64ab44d4fce78da9295b/web/client/epics/timeline.js#L418-L423) epic dispatching rangeDataLoaded action and then read the new histograms and rang line items using the [itemsSelector](https://github.com/geosolutions-it/MapStore2/blob/53713aeb41af739abebb64ab44d4fce78da9295b/web/client/selectors/timeline.js#L147-L162). The itemsSelector is using different parts of the state to create the correct items used by the timeline for the visualization:

- layer reducer static domain properties
- dimension reducer domain properties
- timeline reducer rangeData properties

After some check it seems that even if the rangeData is correctly updated the dimension reducers is still containing information related to domain that are taking precedence over the new rangeData.
We will need to review the update workflow of range data to properly fix this issue.

- [Layer for testing](https://github.com/geosolutions-it/MapStore2/files/11623108/test_time.zip)

**Comment by offtherailz** [comment]
I noticed that with this map works. 
https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/42064
What's the difference ?

**Comment by ale-cristofori** [comment]
> I noticed that with this map works. https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/42064 What's the difference ?

@offtherailz, I suspect it is because the time dimension on the layers included in the map you link is unique rather than a range (start/end date).
