### ISSUE TITLE
Spatial filter is not visible for widgets created by the attribute table

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#9216]
## Description

https://github.com/geosolutions-it/MapStore2/assets/19175505/896a4b2b-7799-45ec-aaad-a390073122c0

From:
https://github.com/geosolutions-it/MapStore2/pull/9214#pullrequestreview-1471946755

## How to reproduce

- open this [map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/10358)
- select states of us from the map
- open the attribute table
- apply a rectangle spatial filter
- create a chart from the attribute table
- click on filter button to apply an additional filter

*Expected Result*

The spatial filter is visible on map

*Current Result*

The spatial filter is not visible on the map. It renders only after editing it

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@allyoucanmap I think it is a regression. Can you confirm that?
