### ISSUE TITLE
Allow to configure hidden columns in featuregrid

### ISSUE THREAD

**Issue by dsuren1** [geosolutions-it/MapStore2#9219]
## Description
Allow user configuration of the feature grid columns to be saved on map save and also in usersession when user session plugin is enabled. It should be applicable for both map and context

**Ref:** https://github.com/georchestra/mapstore2-georchestra/issues/378

## Acceptance criteria
Save attribute table column state 
- [x] On map save
- [x] In user session

**Comment by offtherailz** [comment]
Hi, my understanding is that here we are saving only the attributes selected for the current layer. I think these settings should be saved layer by layer. Isn't it?

**Comment by tdipisa** [comment]
@offtherailz we have to make persistent in map state when saving the map and in user session the status of visible attributes in Attribute table. Therefore yes, it should be managed for each layer, I think.

**Comment by dsuren1** [comment]
@offtherailz 
> So we should have a by-id reference.
I believe now it saves all attributes reference by map for all layers in it. I will modify this

**Comment by offtherailz** [comment]
I can confirm you are right. My apologies for the noise

**Comment by tdipisa** [comment]
I'm sorry @offtherailz who is right and for what? :-)

**Comment by offtherailz** [comment]
@dsuren1 is right, the feature grid saves layer by layer the options.
I probably did an error during the preliminary check.

**Comment by tdipisa** [comment]
Ok @offtherailz. Thank you.
