### ISSUE TITLE
Better handle of context access restriction

### ISSUE THREAD

**Issue by dsuren1** [geosolutions-it/MapStore2#9251]
## Description
The context access requires modification when user faces one the below scenario

1. A user want to load a Context but not logged in
**Current behavior**:  "Resource not found"
**Expected behavior**: Redirect to login form if the user is anonymous and try access protected context

2. A user want to load a Context but doesn't have permission to access it
**Current behavior**:  "Error loading context"
**Expected behavior**: "User is not allowed to access this context"
3. Make `Back to Home page` redirect configurable in FeedbackMask component. Use `miscSettings -> homePath`
4. Also provide an option to configure login page when provided. i.e When in Mapstore, the login panel is shown upon requesting a resource when the user is not logged in, else redirect to the loginpage configured. Use `miscSettings -> loginPage: '/?login'` (ex: for geOrchestra)

Suggested tasks:

- [x] Modify context to prompt user with a login form when it needs user login just like with map, geostory & dashboard (i.e when not logged in and accessing protected content)
- [x] Modify project with a handler, maybe a custom handler which can be registered and triggered in these use cases which has custom authentication feature. Or simply add a epic to listen to certain login required actions and in turn navigate user to a custom login page or dispatch custom login action. That's the case of MS resources defined in geOrchestra, for example:

![image](https://github.com/geosolutions-it/MapStore2/assets/1280027/e0839468-4073-4aa2-ac26-2cdf0cb17304)

@offtherailz Kindly let me know your thoughts.

## Other useful information
https://github.com/georchestra/mapstore2-georchestra/issues/415

**Comment by tdipisa** [comment]
>The back to home link in this case is ambigous, we have a different home path in the geOrchstra environment, so the button should be obmitted or configurable.

The home page may not be present in geOrchestra if it has been configured to not provide that. Therefore we should simply tell the user to authenticate with a message on the screen or directly redirect to the login form.
