### ISSUE TITLE
Map embed url is not correct

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#9269]
## Description

The map embed link should point to:

- `/embedded.html#/{mapId}`

but currently is pointing to the map viewer

- `/#/viewer/{mapId}`

![image](https://github.com/geosolutions-it/MapStore2/assets/19175505/8ee41e83-c708-4c3d-9fa7-03a3e95a2b7c)

## How to reproduce

-  go to the homepage or inside a map
- click on the share button of the map card or from the side bar inside the map viewer
- select the embed tab

*Expected Result*

- the embed url should point to the correct html page

*Current Result*

- the embed url is the map viewer page

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
@dsuren1 take this into account developing Permalink feature.
