### ISSUE TITLE
Fork Plugin image missing

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#9272]
## Description

![image](https://github.com/geosolutions-it/MapStore2/assets/1279510/e5f37b26-d77a-424d-b646-987334bcd54b)

## How to reproduce
-  open the home page
- see the top left corner

*Expected Result*
fork me on github link should show

*Current Result*
fork me on github is missing

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
@tdipisa should this be backported?

**Comment by tdipisa** [comment]
@offtherailz it would be better since it is a really small thing and also QA is affected.

**Comment by offtherailz** [comment]
Yes, it contained an hard-coded link that is now broken. My PR contains the new link from Github APIs and a way to fix the link via properties, if it breaks in the future.
