### ISSUE TITLE
Graticule issues

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#9292]
## Description

These are the problems with adding the Graticule config (used [this context](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/graticule)):

- [ ] The y-axis of the grid is not visible, it is behind the sidebar
![sidebar](https://github.com/geosolutions-it/MapStore2/assets/56537133/ffbd80ff-7213-4110-bd27-393cabe19954)

- [x] When zooming in the map, loading is slow because the grid is calculated on the whole world instead of the part visible in the viewer
![1](https://github.com/geosolutions-it/MapStore2/assets/56537133/edda789f-014e-4839-9644-a63f4cd0afd6)

- [x] When the map is zoomed to a small scale, such as a city, the map freezes and it is no longer possible to navigate within the viewer

![2](https://github.com/geosolutions-it/MapStore2/assets/56537133/400f0fba-c000-464b-860c-1c6d516247d7)

- [x] By zooming out, to the maximum extent, the grid is no longer visible

![3](https://github.com/geosolutions-it/MapStore2/assets/56537133/52dc2d12-c555-4fb8-a2f9-fbd443408b50)

**Comment by allyoucanmap** [comment]
Closed and opened a separate issue for missing problem #9347
