### ISSUE TITLE
Format and Information sheet format fields not populated in GN CSW catalog source

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#9295]
## Description

Contents for _Format_ and _Information sheet format_ fields are not properly fetched in Advanced Settings of a GeoNetwork CWS catalog source (eg. using [this](http://geonetwork.comune.intranet/geonetwork/srv/ita/csw) in c027 VPN).

## How to reproduce

-  Open the map viewer and configure a CSW source against GeoNetwork
- Open the advanced settings and try to expand the _Format_ or _Information sheet format_ fiels

*Expected Result*

Contents in drop down are fetched 

*Current Result*

Contents in drop down are not fetched. Wrong request performed by MS in this case 

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by MV88** [comment]
hi @tdipisa 

As discussed with @allyoucanmap we can propose this to resolve this issue

- No need to create a dedicated geonetwork service type
- We can handle the failure of the request and show an alert box just below the information sheet format with a generic explanation why it has failed with a status of an error ("danger" bootstrap)
- Message could be: "it was not possible to fetch format and information sheet format from the service configured. Probably you are using a no vendor service and this is not supported (geonetwork)"
- if user changes url we can remove the alert box

**Comment by tdipisa** [comment]
> * No need to create a dedicated geonetwork service type

I agree with that

> * We can handle the failure of the request and show an alert box just below the information sheet format with a generic explanation why it has failed with a status of an error ("danger" bootstrap)

Ok.

> * Message could be: "it was not possible to fetch format and information sheet format from the service configured. Probably you are using a no vendor service and this is not supported (geonetwork)"

better "...you are using a _No Vendor_ service and this is not supported (e.g. GeoNetwork)""

> * if user changes url we can remove the alert box

Yes, but In my opinion the alert box should also disappear after a while, if the user stays in the panel, to appear again if the user tries to select a Format a second time.

What do you think about adding instead a alert icon beside the _Format_ and _Info sheet format_ fields with a popup appearing showing the message above when the user move the mouse hover it (in case of _No Vendor_ selected as **Service Type**) ? 

As also discussed with @allyoucanmap the _Service Type_ should stay on top because it indicates a priority field.

![image](https://github.com/geosolutions-it/MapStore2/assets/1280027/0317f796-23ac-4a17-8083-2834906f8449)

**Comment by MV88** [comment]
@tdipisa 
The reason behind the alert box is the "visibility of the message"
 - an alert box is fully visible from the start it appears, no hover action required
 - it should be used to communicate info that user must not miss
 - normally they do not disappear after a while

We proposed the alert box because we wanted to provide a visible feedback to the user based on his action.

> As also discussed with @allyoucanmap the Service Type should stay on top because it indicates a priority field.

Good that you provided the screenshot because I thought you wanted to have it **just above** the **format field**.

**Comment by tdipisa** [comment]
let's talk

**Comment by MV88** [comment]
Final ACs
- [ ] move Server Type just above Format
- [ ] if user clicks on format and an error occurs
  - [ ] a red icon appears on the far right 
  - [ ] it will show from the start a tooltip in a disposable popover
  - [ ] Message will be `"It was not possible to fetch format and information sheet format from the service configured. Probably you are using a No Vendor service and this is not supported (e.g. GeoNetwork)"`
  - [ ] user can click to dispose the popover
  - [ ] if user changes url we can remove this icon and error state
- [ ] if user select No Vendor in Server Type
  - [ ] format field gets disabled
  - [ ] information sheet format field gets disabled
