### ISSUE TITLE
Attribute edit option on Layer (General Tab) is not hidden in some cases

### ISSUE THREAD

**Issue by dsuren1** [geosolutions-it/MapStore2#9314]
### Description
As part of #9180, the `Disable editing on Attribute table` is shown in some cases where it should be hidden

This issue handles all possible scenario (some are already working fine)

**User is not logged in**
- Map -> hide
- New map -> hide
- Shared map -> hide
- Shared context -> hide

**User is logged in**

- New map -> show
- Map with edit permission -> show
- New context (context creator) -> show
- Context with edit permission -> hide
- Context map with edit permission -> show
- Shared context - everyone/specific group (only view permission) -> hide
- Shared context map - everyone/specific group (view permission) -> hide
- Shared map - everyone/specific group (view permission) -> hide
- Shared map - everyone/specific group (edit permission) -> show

The selector to be implemented should be like this. Tested locally to handle all the above mentioned scenarios
```javascript
export const isResourceEditableSelector = state => {
    const { id: mapId, canEdit: mapCanEdit } = mapInfoSelector(state) ?? {};
    const { id: contextId, canEdit: contextCanEdit } = get(state, 'context.resource', {});
    if (isLoggedIn(state)) {
        return contextId ? contextCanEdit : mapId ? mapCanEdit : true;
    }
    return false;
};
```

**Comment by dsuren1** [comment]
@offtherailz Kindly let me know your thoughts

**Comment by offtherailz** [comment]
1. Save button is working as expected now, so I think that this logic, so the selector, should be used only for the edit tool, not for resource. So I should name it "showEditableFeatureCheckboxSelector", and if so, use part of the logic. 
2. Map permission should win over context permission, while here:

```
return contextId ? contextCanEdit : mapId ? mapCanEdit : true;
```
`contextCanEdit` seems to win over `mapCanEdit`.

3. The only thing in that is in doubt is in this point:

- Context with edit permission -> show

The edit permission on the context are not related to the effective interaction with the context (in fact you edit the context, and so it's map, in the context editor)

Contexts can be used in various use cases: 
- As a base to create new maps, and in this case I may want the flag
- As a pure map that users use in read-only mode. In this case I want to hide the flag.

Depending of the usage context, an administrator that creates it may want it to show or not. 

So we should rationally add option for that, in the TOCItemsSettings plugin. 

```
/**
 * ...proper JSDoc
 * @returns {boolean|undefined} returns undefined if the condition can not be determided...
 */
export const showEditableFeatureCheckboxSelector = state => {
    const { id: mapId, canEdit: mapCanEdit } = mapInfoSelector(state) ?? {};
    const { id: contextId } = get(state, 'context.resource', {});
    if (isLoggedIn(state)) {
       // in case of context without a map, use the configured value 
        if(contextId && !mapId) {
              return undefined;
        }
        // 
        return mapId ? mapCanEdit : true;
    }
    return false;
};
```
and in case it returns undefined, use the configured option to show/hide the checkbox. 

I think this is the more rational way to see this. 

About the configured option, let it false by default.

**Comment by dsuren1** [comment]
@offtherailz I think it's distinguishable and clear adding a configuration, in the case of opening a context without a map, assuming that the this configuration (in `TOCItemsSettings`) is used regardless of user's edit permission to the context. i.e user is logged in and viewing a shared context (view only/write permission)

**Comment by offtherailz** [comment]
In order to simplify, with tobia, we decied that in a context without a map, the checkbox is not visible.
So it should be visible
- in new map
- in context wizard
- in maps I'm allowed to edit (given the context or not).
