### ISSUE TITLE
[Print plugin] Ability to rotate the map

### ISSUE THREAD

**Issue by dsuren1** [geosolutions-it/MapStore2#9318]
## Description
Ability to rotate the map in the printed document. It must be visible on the preview.

### Acceptance criteria
- [x] Add a rotation field to print form
- [x] The rotation field accepts degree value
- [x] rotation flag is enabled by default in `mainPage` of print config.yaml (check)
- [x] Rotation should be visible in map preview
- [x] Printed map show rotation applied (if specified any)

## Other useful information
Ref: https://github.com/georchestra/mapstore2-georchestra/issues/582

**Comment by dsuren1** [comment]
@tdipisa @offtherailz 
Kindly let me know if the placement of `rotation` field is okay or should it be moved inside `Layout`?
<img width="826" alt="image" src="https://github.com/geosolutions-it/MapStore2/assets/26929983/e22027e8-34a7-482a-be8b-885a10075374">

**Comment by tdipisa** [comment]
@dsuren1 that's ok for me. Please ensure the compass in the PDF has the right orientation.

**Comment by offtherailz** [comment]
I think this needs a backport
adding label
