### ISSUE TITLE
Support for isNull logical operator on date field in layer filter  

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#9325]
## Description

To provide the support for `isNull` as a new operator on **date** field in Attribute Filter for LayerFilter tool.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by dsuren1** [comment]
Date field by default uses [defaultOperator](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/data/query/GroupField.jsx#L134) configured. So for this custom operator support add type for `date`, something like this to include `isNull`
```js
 case "date": {
     return [...this.props.defaultOperators, "isNull"];
 }
```

**Comment by itsajay1029** [comment]
I want to work for this. Can you assign it to me @tdipisa ?

**Comment by tdipisa** [comment]
Dear @itsajay1029 I'm happy to have you involved to contribute for this if you wish. If you think you can contribute relatively soon to this we can consider to have the enhancement for the next major release 2023.02.00. Just let me know.
