### ISSUE TITLE
Disable functionalities if Photorealistic 3D Tiles are included inside the map?

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#9344]
## Description

Based on this [FAQ](https://cloud.google.com/blog/products/maps-platform/commonly-asked-questions-about-our-recently-launched-photorealistic-3d-tiles):

> Can I use it for precise measurements? Can I get the elevation info or other attribution?
> Danbi: The Photorealistic 3D Tiles are not considered ‘survey-grade’ at this time. The original intent of the product is to power immersive visualizations, rather than support spatial analysis or model measurements. Also note that programmatically reading and recording measurements (heights, distances, elevations, etc.) from our 3D imagery is considered derivative and is prohibited. For details, in addition to our Terms of Service, please read our Policies page on “[Pre-Fetching, Caching, or Storage of Content](https://developers.google.com/maps/documentation/tile/policies)” where we explicitly state that any “image analysis, machine interpretation, object detection/identification, geodata extraction or resale, offline uses, including any of the above” based off of our imagery data is not allowed. 
> 
> Lisa: Developers can use Cesium to combine the current release of Photorealistic 3D Tiles with other data to support some use cases like those Danbi described above. In [this example](https://sandcastle.cesium.com/?src=Google%20Photorealistic%203D%20Tiles%20with%20Building%20Insert.html), a precise building model is visualized in context provided by Photorealistic 3D Tiles. ...

Even if the answer states that is possible to combine personal data and Photorealistic 3D Tiles we need to find a way to exclude this type of data from operation that could return information (eg Measurement).

Maybe with the measurement/drawing tools we are able to exclude the Photorealistic 3D Tiles from the layer the could be picked from the scene, if this will be not possible we will need to disable this kind of functionality when the layer is enable.

Options to prevent derived information from Photorealistic 3D Tiles:

- hide the layer
- exclude the layer from the one pickable
- disable functionality if the layer is visible

The functionality that should be disabled:

- Measurement
- Annotations
- Identify
- Height offset ?

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features

**Comment by tdipisa** [comment]
moved in blocked for further evaluation of terms.

**Comment by tdipisa** [comment]
@allyoucanmap MapStore is not built for GP 3D Tiles and it is not released with GP 3D Tiles enabled by default. MapStore is built to support 3D Tiles in general. Therefore it is essentially up to the users to ensure that they can use and visualize certain datasets in MS through its tools and  utilities. For this reason it doesn't make sense to include a so strict dependency in MS to GF 3D Tiles. It is simply enough to put something in the User Guide online (maybe [here](https://docs.mapstore.geosolutionsgroup.com/en/latest/user-guide/catalog/#3d-tiles-catalog) is the right place with a brief warning) to inform and warn about possible related restrictions in using certain tools when GP 3D Tiles are enabled in a 3D map.
