### ISSUE TITLE
Print plugin is not showing the printable area

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#9346]
## Description

The map is not visible on the printed preview and pdf.
![print](https://github.com/geosolutions-it/MapStore2/assets/56537133/c2594030-3033-45c2-998c-4e7d20df5188)

## How to reproduce

https://github.com/geosolutions-it/MapStore2/assets/19175505/3cde60db-88d1-44ee-804d-1542af17ac50

- open a new map https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/new
- switch to 3D and then go back to 2D
- open print
- zoom out

*Expected Result*

Preview and output should show the printable area

*Current Result*

Print preview and output is blank

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

Found in #9302

**Comment by ElenaGallo** [comment]
@allyoucanmap it seems like the second time you try to print the print preview pdf and pdf sometimes don't have the correct zoom.


https://github.com/geosolutions-it/MapStore2/assets/56537133/9ae53fa6-8cef-4135-82e1-0230175cc579
