### ISSUE TITLE
Update MS background layers using GS OSM ones

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#9361]
## Description

By default the MS viewer should provide GeoSolutions OSM background (see [this](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/20985) demo map). The list of current background should be also reviewed to remove unnecessary ones (eg. OpenTopoMap and NASAGIBS Night 2012).

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Other... Please describe: configuration update for background layers

**Comment by ElenaGallo** [comment]
@tdipisa I noticed that when opening a new map, the OSM Bright background is highlighted in the background selector but OSM is visible in the viewer



https://github.com/geosolutions-it/MapStore2/assets/56537133/750a219e-fe14-49f8-abff-4c24c7a15292

**Comment by tdipisa** [comment]
@ElenaGallo the pending PR [here](https://github.com/geosolutions-it/MapStore2/pull/9376) already handle this fix. Thank you.

**Comment by tdipisa** [comment]
@ElenaGallo I don't know if it is related. I will ask for a check, thank you.

**Comment by ElenaGallo** [comment]
@tdipisa The new issue is: #9464

**Comment by tdipisa** [comment]
Waiting for GS-MAIN update before proceeding with the backport.

**Comment by tdipisa** [comment]
This will land directly in 2024.01.00
