### ISSUE TITLE
GeoProcessing tool review

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#9367]
## Description

This issue collects a few findings I discovered while checking the tool [here](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/tdipisa_demo_theme).

1. It seems all times I try to use the Intersection process, the tool returns the same error.  **This need to be investigated**
![image](https://github.com/geosolutions-it/MapStore2/assets/1280027/a8b2af45-1fcb-42bc-a1ec-579049ccae53)

Below the WPS output:

```
<?xml version="1.0" encoding="UTF-8"?>
<wps:ExecuteResponse xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:xlink="http://www.w3.org/1999/xlink" xml:lang="en" service="WPS" serviceInstance="https://gs-stable.geosolutionsgroup.com/geoserver/ows?authkey=f7a11038-a04d-4519-b778-d0994232e9ae&amp;" version="1.0.0">
	<wps:Process wps:processVersion="1.0.0">
		<ows:Identifier>gs:IntersectionFeatureCollection</ows:Identifier>
		<ows:Title>Intersection of Feature Collections</ows:Title>
		<ows:Abstract>Spatial intersection of two feature collections, including combining attributes from both.</ows:Abstract>
	</wps:Process>
	<wps:Status creationTime="2023-08-29T13:49:41.590Z">
		<wps:ProcessFailed>
			<ows:ExceptionReport version="1.1.0">
				<ows:Exception exceptionCode="NoApplicableCode">
					<ows:ExceptionText>Failed to retrieve value for input first feature collection</ows:ExceptionText>
				</ows:Exception>
			</ows:ExceptionReport>
		</wps:ProcessFailed>
	</wps:Status>
</wps:ExecuteResponse>
```

Does it maybe depends on the dataset used fro this test? In this case an hardening is requested.

2. There is no need to have the validation icon clickable as a button
![image](https://github.com/geosolutions-it/MapStore2/assets/1280027/385c1929-a656-4874-982c-cb776671ccc4)

3. Let's use simply **GeoProcessing** and **Select the process to use**
![image](https://github.com/geosolutions-it/MapStore2/assets/1280027/63017c4b-2dbd-4669-811e-79aa7b35ef91)

4. One of the main goal of a tool should be to display the result clearly without letting the user to find it. It is not the case here, where the result of the geoprocessing tools is not visible at the end:
    - Both Buffer and intersection layers are appended in TOC and for this reason they are not visible
![Image](https://github.com/geosolutions-it/MapStore2/assets/1280027/c973261f-9147-403d-8509-929daa2dcaf2)

    - At the end of the process the map should zoom to the interested area covered by the geometry produced by the process. At the same time the layer should have a good default style to properly highlight it and make it more evident. Where is the intersection below? This test has been performed using [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/geoprocessing_rev/45727).
![Image](https://github.com/geosolutions-it/MapStore2/assets/1280027/5b802fb1-d612-49d1-acd1-1b87fc6710e9)

   - When selecting the layer result of a process, the "zoom to" doesn't appear in TOC toolbar but it should be.

5. Tow consecutive runs of the same process (and also more making the problem incremental) generate an inconsistent behavior in TOC. This test has been performed using [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/geoprocessing_rev/45727). 
![Image](https://github.com/geosolutions-it/MapStore2/assets/1280027/6edef4c0-a0b1-4d4d-badc-c21fcd1390df)

   - I think it is totally useless to create at each run a new group in TOC and it must be avoided
   - In addition the layer name should have some sense, but it is also true the user can change it in a second moment throug layer settings (so nothing to do for this now)

6. When switching from a geoprocess to another, all the form should be cleaned (see also https://github.com/geosolutions-it/MapStore2/pull/9351/#pullrequestreview-1599950036). At the moment the previous selection performed by the client remains and it is not coherent with the state of the form
![Image](https://github.com/geosolutions-it/MapStore2/assets/1280027/4125a4eb-be82-4679-9146-042c55bfe9be)

7. A more coherent tool icon must be created
![Image](https://github.com/geosolutions-it/MapStore2/assets/1280027/185743c6-0bd0-480c-a667-bd3fba8f5c3c)

8. If you click on the tool icon with the catalog tool opened the tool's panel is not visible. Visibility rules and thees kind of interactions must be better managed 
![Image](https://github.com/geosolutions-it/MapStore2/assets/1280027/664bb2a9-1c49-45c0-9045-545a08a1818a)

9. Typo to be fixed for the following notification message
![Image](https://github.com/geosolutions-it/MapStore2/assets/1280027/7e77f60d-c8b2-4086-8cc9-949001050b47)

10. As I indicated [here](https://github.com/geosolutions-it/MapStore-C265/issues/4#issue-1700382132) in the original issue, the request was to implement an extendable WPS tool also for future evolutions while, talking with @offtherailz that reviewed the work, it seems the current implementation it's overdressed on the two currently supported processes. An abstraction level in the middle should be present so, we have to discuss about that**What kind of improvement you want to add?** (check one with "x", remove the others) 

- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by MV88** [comment]
> It seems all times I try to use the Intersection process, the tool returns the same error. This happen on GS-STABLE where the WPS community module has been installed using [this version](https://build.geoserver.org/geoserver/2.21.x/community-latest/geoserver-2.21-SNAPSHOT-wps-longitudinal-profile-plugin.zip). This need to be investigated

This was reported twice times in the PR [here](https://github.com/geosolutions-it/MapStore2/pull/9316#issuecomment-1668178740) and [here](https://github.com/geosolutions-it/MapStore2/pull/9316#issuecomment-1669131830)
and it could be due to the version used by the gs-stable which is on old 2.21, instead of gs-main which is on 2.24

consider that simply changing the geoserver to make the request it is enough to make this working. 
We might investigate where this is fixed to suggest start using **a minimum** version of geoserver?

> There is no need to have the validation icon clickable as a button

sure ok

> One of the main goal of a tool should be to display the result clearly without letting the user to find it. It is not the case here, where the result of the geoprocessing tools is not visible at the end:

the difference at that scale between the normal feature and the buffered one is subtle, Also the highlight layer by implementation is using a system that appends layer on top (these are called additionalLayers) so the highlight can hide the generated one. at this point we can turn off highlight mode as soon the user clicks run 

> At the end of the process the map should zoom to the interested area covered by the geometry produced by the process. At the same time the layer should have a good default style to properly highlight it and make it more evident.

sure, I can also change the style of highlighted layers

> When selecting the layer result of a process, the "zoom to" doesn't appear in TOC toolbar but it should be.

Ok can check this 

> When switching from a geoprocess to another, all the form should be cleaned

ok will fix

> As I indicated https://github.com/geosolutions-it/MapStore-C265/issues/4#issue-1700382132 in the original issue, the request was to implement an extendable WPS tool also for future evolutions while, talking with @offtherailz that reviewed the work, it seems the current implementation it's overdressed on the two currently supported processes. An abstraction level in the middle should be present so, we have to discuss about that

sure we can discuss it

> A more coherent tool icon must be created

well I'm open to suggestion

> If you click on the tool icon with the catalog tool opened the tool's panel is not visible. Visibility rules and thees kind of interactions must be better managed

same as above, I'm open to suggestion. Consider that  we do not have a layout manager system so either and this has effect on the z-index. maybe a dedicated issues is needed

> Typo to be fixed for the following notification message

 ok, will fix
