### ISSUE TITLE
Catalog Tool update to support 3D tiles resources in CSW metadata

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#9368]
Thanks to https://github.com/geosolutions-it/MapStore2-C027/issues/155 it is now possible to configure 3D Tiles metadata on the GeoNetwork side. 
Within this issue it is requested to update the Catalog tool of MapStore (the CSW parsing part) in order to be able to recognize this data type and manage it client side.

## Acceptance criteria

- [ ] MS is loading DC metadata from CSW, therefore it should be possible to distinguish 3D Tiles online resources from the other and catch them for their purposes
- [ ] MS receives the URL of the 3D Tile in the metadata to be able to add it to the map. By properly configuring the _metadata template_ editor in advanced settings of the CSW source, it should also be possible then to show the direct link to the 3D Tile online resource when expanding the item in the catalog result list (eg. using the ${uri} placeholder to show automatically all clickable links of online resources available in the metadata). Clicking on that link a new browser tab should open to bring user to the tileset.json of the 3D Tile.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Other useful information
Sample metadata and sample CSW catalog to be used for this issue are reported [here](https://github.com/geosolutions-it/internal/issues/333#issuecomment-1698728895). VPN connection needed.

**Comment by tdipisa** [comment]
moving temporarily in blocked to migrate the sample metadata to a public CSW

**Comment by tdipisa** [comment]
@ElenaGallo this is our GN instance you can use for functional tests: http://gn3-rndt.geo-solutions.it/geonetwork

**Comment by tdipisa** [comment]
@etj it is working now, thank you. @ElenaGallo you can start testing in DEV.

**Comment by ElenaGallo** [comment]
@tdipisa zoom to layer seems to work for me but I don't see the layer on the map (no error on console).

This is the [test map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/46313)

https://github.com/geosolutions-it/MapStore2/assets/56537133/f46e7df4-0a92-4863-960b-ede53fbdb763

**Comment by tdipisa** [comment]
> @tdipisa zoom to layer seems to work for me but I don't see the layer on the map (no error on console).

That's the problem when I say

> I see there is only an issue with the zoom to layer for which an improvement is necessary (new issue @ElenaGallo same milestone).

The zoom area is not correct. Please open the issue.

**Comment by ElenaGallo** [comment]
@tdipisa new issue here: #https://github.com/geosolutions-it/MapStore2/issues/9585

**Comment by tdipisa** [comment]
@ElenaGallo can we backport this in the meantime then?

**Comment by ElenaGallo** [comment]
@tdipisa yes, @mahmoudadel54 please backport #9465 and #9443
