### ISSUE TITLE
Scale selector not in sync

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#9399]
## Description

[screencast-dev-mapstore.geosolutionsgroup.com-2023.09.07-15_14_34.webm](https://github.com/geosolutions-it/MapStore2/assets/1279510/58225a01-7292-49b6-9832-ac544bee1984)

## How to reproduce
-  Open a new map
- Scroll

*Expected Result*
- the scale indicator updates

*Current Result*
the scale indicator do not change accoringly to the current map resolution

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information
Affects also QA (2023.02.xx)

**Comment by allyoucanmap** [comment]
@offtherailz I think it's the same issue described here https://github.com/geosolutions-it/MapStore2/issues/9363

**Comment by offtherailz** [comment]
Correct,  I'm going to mark it as duplicate and close.
