### ISSUE TITLE
Fix marker shadow to center correctly the default marker image. Now it seems it's not centered when using the align style property

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#9407]
The default generated marker icon is not centered inside the canvas because of the shadow that needs more horizontal space

current:
![image](https://github.com/geosolutions-it/MapStore2/assets/19175505/a5ed6696-a4a4-4698-a35a-23850e6ca01e)

expected:
![image](https://github.com/geosolutions-it/MapStore2/assets/19175505/6c63ae72-b1c1-4520-9c20-26b1543812fe)

**Comment by allyoucanmap** [comment]
Worked inside #9397
