### ISSUE TITLE
Currently is possible to edit title and description inside default settings and edit annotation. This cause a duplication that should be solve.

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#9409]
We should add a setting panel for general options (eg. visibility limits) inside the annotation edit panel and disabled the default TOC settings panel (wrench button)

![image](https://github.com/geosolutions-it/MapStore2/assets/19175505/cf019917-fadc-4908-961f-0c8207fd7381)

**Comment by allyoucanmap** [comment]
Fixed inside #9397
