### ISSUE TITLE
Advanced map editing in geostory crashes the app

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#9434]
## Description

https://github.com/geosolutions-it/MapStore2/assets/19175505/d27e0f3c-6dd7-4ada-b262-daf99a81edd6

## How to reproduce

- login
- create a new geostory
- add a map as background of a section
- edit map configuration
- click on advanced editing option

*Expected Result*

Advanced editing is working

*Current Result*

Application crashes (grey screen)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by dsuren1** [comment]
#### Investigation
- The error seems to happens only with context map.

- As of react-redux v6, `context` is treated as reserved prop. Hence passing [context](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/plugins/Map.jsx#L421) as part of props to connected component causes the application to crash with following error

  <img width="326" alt="image" src="https://github.com/geosolutions-it/MapStore2/assets/26929983/5401ff1b-fe36-4c89-9372-cb7fe8b4527d">

  <img width="981" alt="image" src="https://github.com/geosolutions-it/MapStore2/assets/26929983/b3cad528-94eb-4b62-a4d2-700bf9847d72">

#### Solution
Omit `context` props being passed through. Currently this happens only in geostory, so the fix can be limited to geostory for now.

**Comment by tdipisa** [comment]
@dsuren1 can you please confirm this problem is also present in QA now?

**Comment by dsuren1** [comment]
@tdipisa Yes, the issue exists also in QA
