### ISSUE TITLE
Annotations UI issues

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#9447]
# Description

Issue to collect bugs found during tests of the new annotation tool.

## Other useful information

From https://github.com/geosolutions-it/MapStore2/issues/9396#issuecomment-1717948989

```[tasklist]
### Tasks
- [ ] #9650
- [ ] #9651
- [ ] #9653
- [ ] #9654
```

**Comment by tdipisa** [comment]
> 5- On the point style tab, it is possible to overlay multiple icons and markers

This is not a bug @ElenaGallo. Having the possibility to add multiple rules is is now possible to configure more complex styles.

**Comment by offtherailz** [comment]
Closing because moved in done
