### ISSUE TITLE
User Guide - Add new Annotations UI

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#9448]
## Description

Add new Annotations UI and 3D mode option on [Annotations](https://docs.mapstore.geosolutionsgroup.com/en/latest/user-guide/annotations/) section
*Documentation section involved*
- [x] User Guide
- [ ] Developer Guide

## Other useful information
Related to #9447

**Comment by tdipisa** [comment]
Duplicate of #9472. Closing this.
