### ISSUE TITLE
Issue after updating mapfish printing

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#9459]
## Description

Using npm start the backend doesn't start properly now

## Other useful information

Related to [#9453](https://github.com/geosolutions-it/MapStore2/pull/9453#issuecomment-1721546399)

**Comment by tdipisa** [comment]
@offtherailz running `npm start ` locally I've experienced this problem: both fe and be start but when you load the home page DB resources are not fecthed (the usual red popups appears with no errors in console). Can you please confirm the behavior is the same for you. It seems strange a strange problem.

**Comment by tdipisa** [comment]
@offtherailz is this still an issue or a kind of false positive only on my side? Can you please provide feedback?

**Comment by offtherailz** [comment]
`npm start` works for me, tested both on `2024.01.xx` and on `master` branches today.
If you still have the problem, we can look at it.
