### ISSUE TITLE
COG layer improvement - Zoom to layer

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#9469]
## Description

When we add the geotiff to the layer, we are not able to zoom on it by default, and we are not able to guess the position of the data.
We may find out a way: 
- By the mapping library core object.
- using extenal library parsing COG data
- adding it manually

**Note**:
The `extent` and `geokeys` are required metadata to formulate layer bounds. The bbox info is skipped when either of the metadata prop is missing in source

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Other useful information

See also the original discussion [here](https://github.com/geosolutions-it/MapStore2/pull/9394) and the comment about possible impelementation suggestion [here](https://github.com/geosolutions-it/MapStore2/pull/9394#issuecomment-1729324114)

**Comment by dsuren1** [comment]
### Investigation

#### Bundled size difference (overall)
49128.794 bytes - without `geotiff` import
49218.033 bytes - with `module` import (diff **~89kb**) - **FAVOURED**
49388.697 bytes - with `runtime` require (diff **~259Kb**)

#### Original module size (geotiff)
_without `geotiff` import_
<img width="180" alt="image" src="https://github.com/geosolutions-it/MapStore2/assets/26929983/fefcf292-fefb-4cbc-9eb3-f03ee9ab084d">
_with `module` import_  (**FAVOURED**)
<img width="252" alt="image" src="https://github.com/geosolutions-it/MapStore2/assets/26929983/441121b0-07e0-4e03-9312-2241b834dd8d">
_with `runtime` require_
<img width="212" alt="image" src="https://github.com/geosolutions-it/MapStore2/assets/26929983/c40d2365-8992-4f25-8256-230544fc3eca">

**Behavior**:
User can select prefetching metadata on adding the service, this is to support zoom to extent of the layer
<img width="590" alt="image" src="https://github.com/geosolutions-it/MapStore2/assets/26929983/c180818a-febe-4eea-91b2-3496c4e50ac7">
