### ISSUE TITLE
localConfig load and read functionalities are not standard

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#948]
ConfigUtils is used as a singleton to access to the configuration.

ConfigUtils can be loaded twice, depending on webpack. 
see this: 
http://stackoverflow.com/questions/25509471/webpack-multiple-requires-resolving-to-same-file-but-being-imported-twice

So the usage of ConfigUtils as a singleton is not correct (and it doesn't follow the rule of redux - single source of truth from store). 

So we should save localConfig in the application State, and then refactor the application properly to always read localConfig from the state.

**Comment by offtherailz** [comment]
The discussion is still open and the localConfig is now in state. We have to convert this issue into "take a decision" about how to bring the configuration.
IMHO we should use the state part, but refactoring is hard.

**Comment by tdipisa** [comment]
No longer needed. Closed for inactivity.
