### ISSUE TITLE
Add support for style with properties for Vector and WFS layers

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#9539]
## Description

Allow to choose a property of a feature as value for a symbolizer option. This work includes the update of all libraries style parsers used by the 2D/3D styler for WFS and Vector layers.

Relevant styling properties for which this can be enabled as an option could be the following:

- [x] Color properties
- [x] Width properties
- [x] Radius
- [x] Size
- [x] Rotation properties
- [x] Scale
- [x] Image/3D model URL

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features

**Comment by ElenaGallo** [comment]
@allyoucanmap I noticed that the *property value* of a 3D option can be changed even when in 2D mode.

https://github.com/geosolutions-it/MapStore2/assets/56537133/a0d22f2d-998e-4ef6-87ae-10f56499eb36

**Comment by ElenaGallo** [comment]
New issue for https://github.com/geosolutions-it/MapStore2/issues/9539#issuecomment-1758062353 is #9609
