### ISSUE TITLE
Improving readability of long attribute values in attribute table and table widgets

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#9553]
## Description

For attribute values that are not entirely visible in the attribute table, show a tooltip to visualize the entire attribute value to the user when hovering over the value (for both view and edit mode).

![Image](https://github.com/geosolutions-it/MapStore2/assets/1280027/70675e4a-03ae-4062-9945-9982b0f877c4)

Also table widgets should be covered by this issue. The tooltip should appear only if necessary to ensure a good UX.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by mahmoudadel54** [comment]
Hi @tdipisa 
These are 2 demos one for map viewer and the other one for dashboard viewer demonstrating showing tooltip on table cells that has content longer than the cell width.

1st demo (map viewer): 

https://github.com/geosolutions-it/MapStore2/assets/58145645/cd969c29-e42a-4280-9ab8-20054d4c416e


2nd demo (dashboard): 

https://github.com/geosolutions-it/MapStore2/assets/58145645/04ba72dc-0aca-42a9-b46f-2008c1d11871


Is this acceptable for UX point of view ?

**Comment by MV88** [comment]
@mahmoudadel54 yes looks great

**Comment by tdipisa** [comment]
@mahmoudadel54 it looks really good.
