### ISSUE TITLE
Add MIME type support for `info_format=application/geo+json` for getFeatureInfo

### ISSUE THREAD

**Issue by ale-cristofori** [geosolutions-it/MapStore2#9564]
## Description
Some upstream getFeatureInfo providing WMS services will not accept  `info_format=application/json` as valid parameter for requesting getFeatureInfo result in the properties format, returning the results in JSON format.

## Acceptance criteria

- [ ] Send a getFeatureInfoRequests like this example https://geo.api.test-vlaanderen.be/DHMV/wms?service=WMS&version=1.1.1&request=GetFeatureInfo&id=DHMVII_DSM_1m__c2e29a60-628f-11ee-afd1-15d345606d0c&layers=DHMVII_DSM_1m&query_layers=DHMVII_DSM_1m&styles=&x=51&y=51&height=101&width=101&srs=EPSG%3A3857&bbox=494501.97122686997%2C6583470.655381802%2C496432.00619107066%2C6585400.690346002&feature_count=10&info_format=application%2Fgeo%2Bjson&format=image%2Fpng&ENV=mapstore_language%3Aen

to get back only the properties of the returned features and process them as result of getFeatureInfo

## Other useful information
in the getCapabilities of the above WMS service (ESRI) the MIME type is included in the supported for `getFeatureInfo`
https://geo.api.test-vlaanderen.be/DHMV/wms?service=WMS&version=1.1.1&request=GetCapabilities

**Comment by ale-cristofori** [comment]
@tdipisa customer asks for an initial investigation to come up with an estimate for the development of this feature

**Comment by tdipisa** [comment]
@ale-cristofori 

1. I understand you are asking here to support application/geo+json as possible GFI format in MS (currently we are not supporting)
2. It is not possible to connect MS to that WMS. 404 is always returned. Connecting to this is necessary to proceed with the investigation

**Comment by ale-cristofori** [comment]
@tdipisa 

> I understand you are asking here to support application/geo+json as possible GFI format in MS (currently we are not supporting)

Yes this is the requirement in a few words.

> 2. It is not possible to well connect MS to that WMS. 404 is always returned when we try to add layers to the map. Connecting to this is necessary to proceed with the investigation

I noticed that too. I opened that in a local MapStore and I can access the `getCapabilities` and visualize the layers, I did not test each one of them but the layers `Digitaal Hoogtemodel Vlaanderen I, digitaal terreinmodel 5 m` and `Vectorlaag die voor ieder deel van het bijhorende product de opnamedatum weergeeft.` seem to work. Since locally I have some clients based MS2 versions this needs to be tested with master because it contains this fix

**Comment by MV88** [comment]
Would be acceptable to implement a Retry logic  ~1,5gg dev

if a request with info_format fails we can retry doing the same request by just changing that param to application/geo+json
this would save us to edit the UI and handle a new info_format value selection in layer settings / global settings

**Comment by ale-cristofori** [comment]
linked MapStore issue is  https://github.com/geosolutions-it/MapStore2/issues/9268

**Comment by offtherailz** [comment]
Here we have 2 problems: 
1 - Proxy seems to raise an error on the getcapabilities request - This have to be investigated separetely.
2 - On front-end side, MapStore recognize only `application/json` while the server provided (https://geo.api.test-vlaanderen.be/DHMV/wms) returns `application/geo+json`. 

So the purpose of this issue is to support this alternative `info_format` in MapStore, treating it as an alias of `application/json`.

**Comment by Igi-ID** [comment]
This service https://geo.api.test-vlaanderen.be/DHMV/wms has been unavailable for a few days. By my intermittent attempts to test and use the resource, it has been unavailable since Tuesday, the 30th of January. Maybe we can reach out to the client in order to test the provided solution in #9917.
