### ISSUE TITLE
Zoom to record in table widgets

### ISSUE THREAD

**Issue by mahmoudadel54** [geosolutions-it/MapStore2#9567]
## Description

At the moment [table widgets](https://docs.mapstore.geosolutionsgroup.com/en/latest/user-guide/widgets/#table) can be defined for both map viewer and dashboards but it is not possible to zoom a map to the selected record. 

It is requested to include a zoom icon on the left side of each record to allow the zoom operation:

- to the related layer feature the table widget is referring to (in case of map viewer)
- to the related feature extent in the map widget the table widget is connected to (in case of dashboards)

EDIT: adding here some details on how it can be the ideal workflow:

- [ ] The zoom to button must be always visible in the table widgets: please include a new configuration option at plugin json config level to include it or not (default to _true_)
- [ ] geometry need to be fetched on demand and should never appear in the list of attributes
- [ ] when you click the zoom button of a feature, it starts fetching the geom of that feature or 
   better only the extent if possible trough a WFS call 
- [ ] in the meantime a spinner takes the place of the zoom button 
- [ ] when the response is back we can trigger the zoomToExtent action
- [ ] and restore zoom to button

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by MV88** [comment]
this has to be backported in c040-2023.02.xx
