### ISSUE TITLE
Selection of features with Alt + Mouse in the attribute table does not work

### ISSUE THREAD

**Issue by diegovargasg** [geosolutions-it/MapStore2#9568]
## Description
In the attribute table, the selection of features by using Alt + Mouse does not work and generates an exception: 
Uncaught TypeError: Cannot read properties of null (reading 'getCoordinateFromPixelInternal')

## How to reproduce
- Open the attribute table of a layer
- Enable the selection of features on the map
![image](https://github.com/geosolutions-it/MapStore2/assets/1714616/45b0e314-fc2d-4087-840e-d7334de3934c)

- Draw a selecting-box on the map by using Alt + Mouse dragging
![image](https://github.com/geosolutions-it/MapStore2/assets/1714616/5337c5cb-b7bd-41d6-8e4d-2ca2cdd60520)

*Expected Result*
It should be posible to select features by Alt + Mouse dragging

*Current Result*
Exception is thrown
![image](https://github.com/geosolutions-it/MapStore2/assets/1714616/7909657e-285b-40da-94ad-b72e8cc9c936)

- [x] Not browser related

## Other useful information
Affects version v2023.02.00

**Comment by MV88** [comment]
@ElenaGallo please test it in DEV

**Comment by MV88** [comment]
nevermind, i thought it was the pr
