### ISSUE TITLE
Unadvertised resources

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#9583]
## Description

Include the possibility to have unadvertised resources in MS: maps, dashboards and geostories (app contexts are excluded for now).

From the _Edit properties_ panel of a resource it is possible for the admin/owner to make a resource unadvertised. Doing that, the resource will appear in the **[Home](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/)** page or in the **[Map Catalog](https://mapstore.geosolutionsgroup.com/mapstore/docs/api/plugins#plugins.MapCatalog)** tool only for admin users or the owner (as per usual behaviour admins can change that setting for all resources and normal users only for their own resources).

![image](https://github.com/geosolutions-it/MapStore2/assets/1280027/ae3ffa8d-0f58-4226-944f-7146a4a106bf)

~For other users accessing the resources directly (e.g. that can open the Edit Properties within it), we can consider to include a notifications simply to inform that the resource is Unadvertized so that they can be aware of this (for example the same as above screenshot but with the checkbox disabled).~

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by offtherailz** [comment]
@tdipisa I suggest to use permalinks for this purpose. Does this satisfy the requirement? They are not listed in maps or in Map catalog.

**Comment by tdipisa** [comment]
>I think there are some typos in this issue that make us difficoult to understand.
From my undestanding it is asking for "Unadvertized" resources not listed in Home and not listed in the Map Catalog plugin.

I've updated a bit the description to make it clearer. That's the point anyway, what is difficult tu understand here?

>In this case @tdipisa I suggest to use permalinks for this purpose. Does this satisfy the requirement? They are already not listed in maps or in Map catalog, because they belong to a different, separated category.

Why using permalinks should satisfy the requirements that are asking for a completely different thing? Unadvertized resources must be anyway visible in MS Catalog but only for admins.

**Comment by tdipisa** [comment]
> @tdipisa Kindly clarify So the `Unadvertised` flag takes precedence over group permission? (i.e when the resource is `Unadvertised`, and group permission is `everyone` with `can view/edit`, it is still ignored and treated as a private resource)

@dsuren yes, I think this from description make it already quite clear:

> Doing that, the resource will appear in the [Home](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/) page or in the [Map Catalog](https://mapstore.geosolutionsgroup.com/mapstore/docs/api/plugins#plugins.MapCatalog) tool only for admin users or the owner

isn't it?

**Comment by dsuren1** [comment]
So in that case, wouldn't it be better that we disable the group permission options when `unadvertised` field is checked ?

**Comment by tdipisa** [comment]
No, nothing should change for this.

**Comment by dsuren1** [comment]
Okay. Thanks

**Comment by offtherailz** [comment]
For our investigation we absolutely need a backend support for this feature. 
Actual filtering support on client side is not enough for providing this functionality.

**Comment by tdipisa** [comment]
Blocked waiting for further evaluations on the backend.

**Comment by tdipisa** [comment]
Thank you @afabiani. @offtherailz will review asap.

**Comment by offtherailz** [comment]
# Reporting usage info

Basically you have to add to POST/PUT requests for create/edit the resource adding the `advertised` tag in the request XML. 
Here below some examples verified working on geostore from pr https://github.com/geosolutions-it/geostore/pull/332 :

- Create (POST): 
```xml
<Resource>
    <description>
        <![CDATA[]]>
    </description>
    <metadata></metadata>
    <name>
        <![CDATA[test-save-unadvertised]]>
    </name>
    <advertised>
        false
    </advertised>
    <category>
        <name>MAP</name>
    </category>
    <Attributes>
        <attribute>
            <name>attributes</name>
            <value>null</value>
            <type>STRING</type>
        </attribute>
    </Attributes>
    <store>
        <data>
// DATA
        </data>
    </store>
</Resource>
```

- Update (PUT) (essential is the body) can contain `advetised` tag. If not present, it will be set to true

```xml
<Resource>
    <description>
        <![CDATA[]]>
    </description>
    <metadata></metadata>
    <name>
        <![CDATA[a]]>
    </name>
    <advertised>
        false
    </advertised>
</Resource>
```

**Comment by tdipisa** [comment]
@Igi-ID (FYI @offtherailz)
GeoStore PR https://github.com/geosolutions-it/geostore/pull/332 has been merged, therefore we can proceed implementing the front-end part. Thank you.

**Comment by tdipisa** [comment]
>Please confirm that `unadvertised` should be shown to every user that have edit permissions on it.

Confirmed @offtherailz @Igi-ID
