### ISSUE TITLE
Zoom to layer is not correct for the 3D tiles resources in CSW 

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#9585]
## Description

After adding 3D tile layer, from a CSW service, to a map, the "Zoom to Layer" works but does not zoom to the layer correctly.

https://github.com/geosolutions-it/MapStore2/assets/56537133/140047a9-0e31-40ce-94a3-c12c1affd125

## How to reproduce

-  Open [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/46313)
- Activate the 3D mode
- Open the catalog 
- Add `20230829_test_3dtile_01` layer

*Expected Result*

The "Zoom to Layer" and the layer is visible on map

*Current Result*

The "Zoom to Layer" works but does not zoom to the layer correct

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

Related to https://github.com/geosolutions-it/MapStore2/issues/9368#issuecomment-1759384254

**Comment by tdipisa** [comment]
@mahmoudadel54 the DC output of the metadata from GeoNetwork is returning the right BBOX covering the area of Florence but MS is zooming to the wrong area. 
We have to:

1. Properly handle the BBOX in the metadata and use it
2. If it is missing or MS is not able to parse it for some reason, as a fallback we can get the extent from the 3D tile as we usually do when we add 3D Tiles to the map using the related source type
