### ISSUE TITLE
Add support to multi-band color mapping for COG layers

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#9588]
## Description

As visible [here](https://openlayers.org/en/latest/examples/multiple-cogs.html), we can associate the colors to bands. Actually mapstore supports only standard 3 bands RGB or 1 band gray (because it is the openlayers default)

We have to implement the support to associate colors to bands.
This means: 
- Retrieve bands information from metadata (in advance from catalog, or when needed)
- to persist the association of bands with color. It should be implemented in a 
    - styling model and format open to future updates as color scales or other known raster styling formats.
    - Compatible to be read to cesium implementation for future implementation
- Provide a UI to edit this style (ideally both in catalog and layer style tab)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by dsuren1** [comment]
As part of fetching metadata, we read only one image to get metadata info of the tif source. Reading raster data of the entire image can puts too much load on CPU and can severly impact performance, hence we need to specify a window/bbox, width, height and pooling to read raster data. We can specify some defaults to fetch from but we can't assure that it always reads the area of interest.

So my thoughts, we can get the banding information from the user in catalog and add it to COG source for user defined rendering of tif source and skip any reading of banding info from the image in catalog. 
And In layer -> style, we can allow user to pick a aoi by allowing user to click a point on map and using layer's `getData` to get rgba value to populate the bands fields (slider)?

**Mocks**

- This way we can also modify the band on the fly by changing values via sliders

  <kbd>
  <img width="501" alt="Screenshot 2023-12-11 at 5 37 51 PM" src="https://github.com/geosolutions-it/MapStore2/assets/26929983/7569c087-da21-4153-8828-c517929f7bcd">
  </kbd>

- Or should we also allow user to modify the channels to certain colors as shown here?
  <kbd>
   <img width="252" alt="Screenshot 2023-12-11 at 5 38 38 PM" src="https://github.com/geosolutions-it/MapStore2/assets/26929983/12306e9a-f36d-466f-9acf-96f79ace1b9d">
  </kbd>

We can discuss on this @offtherailz to establish an acceptance criteria

**Comment by dsuren1** [comment]
**Updated acceptance criteria**

- Retrieve bands information from metadata. Reading image's raster data is not required as the samples/band information can be obtained from `getSamplesPerPixel`
  - If RGB set style color with an array of bands in OL supported expression
  - if the image has a single band set band 1 to all bands
- In layer -> style, user should be able to select `channel` based on the band available. Should we show Alpha channel ?

**Comment by offtherailz** [comment]
### Max/Min

About min/max please ask to @tdipisa if it should be done in this dev cycle.  I was thinking to work values of data more with advanced style features (like calculations an so and so) in a context of an advanced raster styler).
I think the choice to implement them now or layer is in what it means required. What happens if we do not have them? 

### Apha channel

Yes, good idea. I think it can stay always together with the RGB, and optional (can be unselected). look at similar tools to get an idea of how it should work.

**Comment by tdipisa** [comment]
@dsuren1 

>there are cases where the max/min value of source data value is required when raster statistics is not available at the source leaving OL to use the maximum available for the data type which could leave the rendered image to be not visually appealing. Maybe this could be a future enhancement or we could add these fields in the style panel for the user to configure after the layer is added. Your thoughts @offtherailz ?

Since the support for min/max in 'layer settings->style' is included in your evaluation please consider also this in the development so that we will be able to better support also these special cases if needed.

**Comment by tdipisa** [comment]
blocked by https://github.com/geosolutions-it/MapStore2/issues/10083
