### ISSUE TITLE
Notify data projection not compatible / available for COG

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#9589]
## Description

When the download metadata is checked (and it should be by default), we have to check the CRS and notify the user if the CRS definiton is not defined in MapStore, so the layer can not be reporojected in the map CRS.

CRS should be avaliable from `const crs = getProjectionFromGeoKeys(image);` we already query on catalog to get the BBOX

Also if the layer in map is in a projection not compatible, it should be grayed out and notified as for WMTS. 

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Other useful information

I don't think is relevant for our implementation,
but we noticed that in this example openlayer do not define any projection for the map or include the tiff projection

https://openlayers.org/en/latest/examples/cog.html

Probably the OL map has some automation to properly target projection

Instead here they are defined

https://openlayers.org/en/latest/examples/multiple-cogs.html

**Comment by dsuren1** [comment]
@offtherailz  Kindly clarify
If I'm not wrong, currently only warning notification is shown when the layer is not compatible and added from catalog
<img width="349" alt="image" src="https://github.com/geosolutions-it/MapStore2/assets/26929983/a479e559-c8ab-4c2e-aaec-e76a8c976a30">

And catalog panel shows something like this when the selected crs is not compatible for WMS/WMTS and prevents the layer from being added, but the _layer is not disabled/greyed out_ after added to TOC panel. Maybe this needs to be implemented for all layers. 
<img width="550" alt="image" src="https://github.com/geosolutions-it/MapStore2/assets/26929983/065c7a1d-4506-4465-b514-e253ec4894ca">

**Comment by dsuren1** [comment]
@tdipisa @offtherailz 
### Updated acceptance criteria
- Restrict user from adding the cog layer when incompatible (just like with WMTS/WMS)
- Show a warning when the layer is already added and reloaded/recreated (imported map etc)
- Show a error on the toc layer node with a tooltip on the info icon `The layer's source data projection definition (${sourceCRS}) is not available in the application for reprojecting the data in the current map`
