### ISSUE TITLE
Make COG download metadata by default

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#9590]
## Description

This option is necessary to allow zoom to layer and to get the data projection (see #9589 )

The reason why it was optional was because for big geotiffs it can take minutes. 

We can overcome to this problem by:

- Allowing to preload this data in catalog add/edit form. Because this takes a long time, a botton should allow it (with the option to cancel), and this information will be saved in the catalog, among the records. This means that also the UI with the URL(s) may need a revision, probably with a list of records, or we may have undefined behaviors when we edit URLs. 
- Store the data in the catalog so they do not have to be reloaded anymore. The user will have to refresh the metadata in catalog to reload the metadata and re-save if something changes.
- Store these data in the layer too, so they will be available for 

The metadata stored in layers/records should provide at least data about:
- data projection and bbox
- bands

These data can be refreshed for the styling tool (or if was not originally saved) 

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by dsuren1** [comment]
### Updated acceptance criteria

- Enable download metadata option by default to fetch metadata on save
- Change the text of the checkbox field to `Download file metadata on save`
- Hide cancel button on save and metadata is being fetched. Replace with a `Cancel request` button during fetching process
- Additional layer metadata info should be saved in this format
 ``` javascript
 sourceMetadata: {
   crs: "",
   bands: ""
 }
 ```

**Comment by tdipisa** [comment]
@dsuren1 @offtherailz 
support for bands is already captured by #9588 therefore all related aspects should be reported there and worked separately.
