### ISSUE TITLE
Make COG Source type disabled by default until experimental

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#9592]
## Description

COG source type should be excluded from the default configuration until this feature is experimental. The way for MS admins to add it by configuration should be anyway maintained. Intervention area:

- Catalog tool in viewer: it is enough to properly configure [serviceTypes](https://mapstore.geosolutionsgroup.com/mapstore/docs/api/plugins#plugins.MetadataExplorer) if we want to add COG. Remove from default
- Catalog tool in dashboard: it is not present (nothing to do)
- Catalog tool in geostories: to be implemented the possibility to configure it or simply change the default config by making it different between various resource types

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Other useful information

**Comment by dsuren1** [comment]
@tdipisa 
> * Catalog tool in viewer: it is enough to properly configure [serviceTypes](https://mapstore.geosolutionsgroup.com/mapstore/docs/api/plugins#plugins.MetadataExplorer) if we want to add COG. Remove from default
> * Catalog tool in geostories: to be implemented the possibility to configure it or simply change the default config by making it different between various resource types

Removing from default (`serviceTypes`) in MetadataExplorer plugin should be enough to hide `COG` option from catalog in Map and Geostory's MapEditor

If needs to be configured differently in two places, we can configure it in MapEditor's [`DefaultConfigurations`](https://github.com/geosolutions-it/MapStore2/blob/70e0acf8f5bd9697349c0f3b014a3e2979fcd359/web/client/plugins/mapEditor/DefaultConfiguration.js#L78). But I think, for now this is not needed.
