### ISSUE TITLE
Better link or document the proper version in MapStore Documentation in home page

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#9600]
## Description

The home page of MapStore points always to _latest_ documentation of MapStore. 

![image](https://github.com/geosolutions-it/MapStore2/assets/1280027/f491c919-7708-4c31-8d05-1684491e578b)

In order to make clear to the users what version of the documentation to use we should do one of the following:
- Change the link accordingly for each release
- Clarify in the home page (Documentation section) how to get the proper version of the documentation accordingly to the owned version.

**Comment by dsuren1** [comment]
@offtherailz 
>Change the link accordingly for each release

To change the default link to point the version released. We can do it from admin console of [readthedocs](https://readthedocs.org/). Kindly correct me if this is not what is expected in the issue. Thanks!
<img width="400" alt="image" src="https://github.com/geosolutions-it/MapStore2/assets/26929983/a9fb5edd-33d3-489e-86b3-02d7e12888c3">

**Comment by tdipisa** [comment]
@dsuren1 I've updated the description to clarify what is requested here.

**Comment by dsuren1** [comment]
@tdipisa 
### Updated acceptance criteria

- Update release procedure to include steps to modify `readthedocs`'s _advanced settings_ to point to the version released, so documentation by default loads the version configured
- Update the documentation url to point the root of the url (`https://docs.mapstore.geosolutionsgroup.com`)
