### ISSUE TITLE
Viewer Widgets - Add possibility to configure via localConfig the rowHeight and cols property as "Dashboard" plugin does

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#9622]
## Description

edit this within **localConfig.json**
```
{
        "name": "Widgets",
        "cfg": {
          "cols": { "md": 48, "xxs": 1 },
          "rowHeight": 10
        }
},
```

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Other useful information
To review and coordinate implementation strategy with @offtherailz

**Comment by tdipisa** [comment]
@ElenaGallo (FYI @MV88) I'm wondering how this issue has the _Accepted_ label. The placement grid of widgets doesn't look correct in DEV: it is not possible to place widgets properly above the tray. Moving back to ready for further checks @MV88. Did I miss something?

**Comment by MV88** [comment]
> @ElenaGallo (FYI @MV88) I'm wondering how this issue has the Accepted label. The placement grid of widgets doesn't look correct in DEV: it is not possible to place widgets properly above the tray. Moving back to ready for further checks @MV88. Did I miss something?

what do you mean exactly? do you have a context to be used for testing and comparing behaviours?
testing [this](https://qa-mapstore.geosolutionsgroup.com/mapstore/#/viewer/10358) map in QA (without cfg changes) I got the same results as in DEV, i.e. tray stays on top of widgets

> In addition. the Tray always cover and this should not be allowed (look at QA to see how it works):

 you can obtain same results in QA by just moving down a bit the widgets
![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/dd2e53f3-3c3d-4e99-b9b6-078237624246)

**Comment by tdipisa** [comment]
> what do you mean exactly? do you have a context to be used for testing and comparing behaviours? testing [this](https://qa-mapstore.geosolutionsgroup.com/mapstore/#/viewer/10358) map in QA (without cfg changes) I got the same results as in DEV, i.e. tray stays on top of widgets

I mean that widgets in this [existing demo map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/10358) are not placed correctly 

> > In addition. the Tray always cover and this should not be allowed (look at QA to see how it works):

It doesn't seems to me, maybe you can show it to me.

> you can obtain same results in QA by just moving down a bit the widgets ![image](https://user-images.githubusercontent.com/11991428/282122538-dd2e53f3-3c3d-4e99-b9b6-078237624246.png)

QA, unlike DEV, is working as expected. That's my impression. Maybe you can explain it better in a quick call.

**Comment by MV88** [comment]
ok, but I'm not sure you have to reopen this issue. probably what you see regards the work done for the charts refactor

**Comment by tdipisa** [comment]
@MV88 as agreed in the call, please check why there is that wrong placement of widgets to understand if it has been introduced by the work done for this issue or the cause of the regression is another one.
