### ISSUE TITLE
Replace Quill editor with Draftjs editor in Dashboard's Text widget 

### ISSUE THREAD

**Issue by dsuren1** [geosolutions-it/MapStore2#9627]
## Description
As part of enhancement to MS in replacing quill editor across the application. We would like to replace Quill editor used in Dashboard Text widget with Draftjs in this issue

### Acceptance criteria

- Replace quill editor with [Draftjs editor](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/resources/modals/fragments/editors/DraftJSEditor.jsx) in Dashboard [Text widget](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/widgets/builder/wizard/text/TextOptions.jsx#L30) (_Note: Refer also Mapview implementation of [text editor](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/mapviews/settings/CompactRichTextEditor.jsx) with Draftjs_)
- With `embedded` toolbar options enabled additionally
- Allow `fontFamilies` to be configurable just like in Geostory plugin

### Screenshot (Expected)
<img width="503" alt="Screenshot 2023-10-19 at 2 57 06 PM" src="https://github.com/geosolutions-it/MapStore2/assets/26929983/d6bbfaec-ec1f-41ea-a15d-5e0fa515bc3f">

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by mumairr** [comment]
@dsuren1 a quick question regarding the update, I can see draft-js has been archived this February and won't receive any future updates. 
On the other hand, react-quill is updated around the same time but still active and most probably recieve updates as well.
Any specific reason to upgrade to draftjs from quill? for the pdf thing, I tested it out on already integrated quill and works fine.

Please guide if i am missing something important. Thanks

**Comment by dsuren1** [comment]
@mumairr 
The decision mainly comes from maintaining a single editor across the application, as most of the parts have been replaced already.

**Comment by mumairr** [comment]
@dsuren1 makes sense. Thanks for the explanation
