### ISSUE TITLE
Details panel for MS dashboards

### ISSUE THREAD

**Issue by mahmoudadel54** [geosolutions-it/MapStore2#9683]
## Description

It is requested the implementation of a [Details](https://docs.mapstore.geosolutionsgroup.com/en/latest/user-guide/resources-properties/#details) panel for Dashboards

## Acceptance criteria

- [ ] The tool should be defined in the same way of the corresponding one for maps. We could also consider to move the details definition outside the Save modal
- [ ] The tool should have the same options of the existing one (eg. show as modal, show at startup etc.)
- [ ] It should be possible to open it from the left side toolbar 

## Other useful information

**Comment by mahmoudadel54** [comment]
## Description


It is requested the implementation of a [Details](https://docs.mapstore.geosolutionsgroup.com/en/latest/user-guide/resources-properties/#details) panel for Dashboards

## Acceptance criteria


- [ ] The tool should be defined in the same way of the corresponding one for maps. We could also consider to move the details definition outside the Save modal
- [ ] The tool should have the same options of the existing one (eg. show as modal, show at startup etc.)
- [ ] It should be possible to open it from the left side toolbar 

## Other useful information
Internal issue is https://github.com/geosolutions-it/support/issues/2404

**Comment by mahmoudadel54** [comment]
This is a simple demo showing the layout change --> I have tried, it helps yes but doesn't give the required style in sidebar 
```{
"name": "SidebarMenu",
"cfg" : {
  "containerPosition": "columns"
  }
}
```
So I have to put a flag in sideBarMenu plugin if it is dashboard ---> edit style to be like that [just 2 lines in css]

@tdipisa @MV88  
Is it suitable ? for layout 

https://github.com/geosolutions-it/MapStore2/assets/58145645/9c8bad27-b64e-4277-b5f5-f54d230f0ed3

**Comment by ElenaGallo** [comment]
@mahmoudadel54 sorry for the double comment, I also noticed that the connections button, when disabled, is blue instead of white. Open [this dashboard](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/dashboard/21694)

![Image](https://github.com/geosolutions-it/MapStore2/assets/56537133/ae674914-a60c-403e-a048-5ca14c0b72ad)

**Comment by tdipisa** [comment]
@ElenaGallo @mahmoudadel54 

>the details tooltips report About this map instead About this dashboard

not only the tooltip, also the panel title is reporting the same but it should be resource related.

![image](https://github.com/geosolutions-it/MapStore2/assets/1280027/c6317039-a948-42e5-bfe1-d99be8c2d337)

**Comment by mahmoudadel54** [comment]
@tdipisa @ElenaGallo 
Can I make it "About this content" ? to make it generic for the future if geostory needs to use this as well ?

**Comment by MV88** [comment]
> @tdipisa @ElenaGallo Can I make it "About this content" ? to make it generic for the future if geostory needs to use this as well ?
> 
> ![image](https://user-images.githubusercontent.com/58145645/285197728-dd8a3bcd-503c-4867-b0f1-8080f88a54d5.png)

yes go ahead
