### ISSUE TITLE
Allow time range filtering for Attribute Table quick filter

### ISSUE THREAD

**Issue by mahmoudadel54** [geosolutions-it/MapStore2#9706]
## Description

Enhance the quick filter for time attributes to be able to filter by time range.

- [ ] create a new datetime icon
- [ ] remove the double icon present for date time 
- [ ] add an operator for date, time and datetime with same list from filterfield
- [ ] if operator is **><** datepicker will open with mode "range"
- [ ] otherwise it will open in single mode
- [ ] as soon there is a valid range or single date/time it gets applied in the attribute table
- [ ] an x should close the popover

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

### Suggested mockup
![range_picker](https://github.com/geosolutions-it/MapStore2-C040/assets/1280027/7f9c8e9c-6276-47f4-82cf-dfb40a8767ef)

**Comment by tdipisa** [comment]
@mahmoudadel54 please proceed with the pending fix, thank you.
