### ISSUE TITLE
User Guide - Zoom to record for Table widget

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#9708]
## Description

Add Zoom to record for Table widget on [Widget](https://docs.mapstore.geosolutionsgroup.com/en/latest/user-guide/widgets/#table) section

*Documentation section involved*
- [x] User Guide
- [ ] Developer Guide

## Other useful information
Related to #9567 and #9783

**Comment by tdipisa** [comment]
Blocked by https://github.com/geosolutions-it/MapStore2/issues/9783
