### ISSUE TITLE
User Guide - Add Details panel and new Side Bar for dashboards

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#9721]
## Description

Add Details panel and new Side Bar for dashboards on [Details](https://docs.mapstore.geosolutionsgroup.com/en/latest/user-guide/resources-properties/#details) section and on [Exploring Dashboards](https://docs.mapstore.geosolutionsgroup.com/en/latest/user-guide/exploring-dashboards/) section

*Documentation section involved*
- [x] User Guide
- [ ] Developer Guide

## Other useful information
Related to #9683

**Comment by tdipisa** [comment]
Blocked by https://github.com/geosolutions-it/MapStore2/issues/9780
