### ISSUE TITLE
Form fields not aligned in chart classification

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#9726]
## Description

Classification fields (class value drop down) are no longer aligned properly in the new chart classification panel. **Release 2023.02.00 not affected!**

## How to reproduce

- Open [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/10358) 
- Open the chart editor of **US Population** chart widget
- Switch to _Persons_ Trace 
- Open the **Custom Color Settings** panel of _Color ramp_ property (see screenshot below)

*Expected Result*

Class value drop down are properly aligned with other fields of the same row

*Current Result*

Class value drop down are not properly aligned with other fields of the same row

![image](https://github.com/geosolutions-it/MapStore2/assets/1280027/15484b55-12d7-4556-9aed-30eb01396b47)

Also QA is affected for the same form fields even if in master there has been an huge refactor of charts, therefore most probably the cause is the same.

![image](https://github.com/geosolutions-it/MapStore2/assets/1280027/002bc74c-505b-4d65-b33b-df195d5118b9)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

We need to understand what introduced this regression in QA.

**Comment by MV88** [comment]
@tdipisa i think this issue is similar to #9295, we can test this again after merging that

**Comment by tdipisa** [comment]
@MV88 ok let's check and confirm once deployed.

**Comment by MV88** [comment]
closing it because it is fixed in DEV

**Comment by MV88** [comment]
@ElenaGallo please double test this in DEV
