### ISSUE TITLE
Form fields not aligned in Layer Filter

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#9728]
## Description

Attribute filter fields are no longer aligned properly in the Layer Filter panel. **Release 2023.02.00 not affected!**

## How to reproduce

- Open [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/10358) 
- Select the _State of US_ layer in TOC
- Open the **Layer Filter**
- Look at the attribute filter fields alignment

*Expected Result*

Value drop down are properly aligned with other fields of the same row

*Current Result*

Value drop down are not properly aligned with other fields of the same row

![image](https://github.com/geosolutions-it/MapStore2/assets/1280027/e26c8af4-a5dc-48f3-82ae-a7f4152ea94c)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

We need to understand what introduced this regression in QA.

**Comment by MV88** [comment]
for the record the regression was introduced [here](https://github.com/geosolutions-it/MapStore2/pull/9715)
