### ISSUE TITLE
Some possible enhancements to dashboard and geostory page

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#9735]
## Description

Some possible changes to uniform the UI/UX across MS resources.

## Acceptance criteria

- [ ] add sidebar in geostory
- [ ] remove attribution  from both dashboard and geostory
- [ ] move LocaleSelector into settings plugin to be added to the sidebar of both dashboard and geostory
- [ ] add resource title in omnibar for dasbhoards and geostories or remove it

**Comment by tdipisa** [comment]
@allyoucanmap I've asked @MV88 to open this. thank you @MV88 
I would like to discuss on this to uniform things and UI/UX for 2024.01.00

**Comment by MV88** [comment]
> @allyoucanmap I've asked @MV88 to open this. thank you @MV88 I would like to discuss on this to uniform things and UI/UX for 2024.01.00

I would like to suggest to have the discussion to be open for the core dev team as well (Like old brainstorming meeting)
my two cents

**Comment by tdipisa** [comment]
Closed in favor of #9780. Other issued will be opened later as par to the layout refactor.
