### ISSUE TITLE
Do not visualize map sync popup by default for Attribute Table

### ISSUE THREAD

**Issue by mahmoudadel54** [geosolutions-it/MapStore2#9806]
## Description

Is this already possible via config?

![image](https://user-images.githubusercontent.com/1280027/205676589-73004991-5f48-46dd-87ca-ea3a7187d1df.png)

The option is present as `initialState` and we will re-enable it through a new PR for free.
Anyway, as any initialState, is deprecated (difficoult to use, not compatible with contexts etc...) For this reason we should add an option for the feature editor.

We can provide an option here, in initialization, to define the default in plugin configuration:

https://github.com/geosolutions-it/MapStore2/blob/a939ded4f02add6e1b08a2713f1970dbb98987e1/web/client/reducers/featuregrid.js#L156

called here, adding the new option 

https://github.com/geosolutions-it/MapStore2/blob/master/web/client/plugins/featuregrid/FeatureEditor.jsx#L190

And document, everything of course.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by tdipisa** [comment]
@ElenaGallo @mahmoudadel54 it seems to me this still need to be backported to c040-2023.02.xx
