### ISSUE TITLE
Extruded features in Cesium 3D

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#9807]
## Description

Giving one attribute of type Number, it is requested the possibility to extrude layer features (Annotation, Vector and WFS) in the 3D map.

## Acceptance criteria

- [ ] Extrusion of polygon features extending fill symbolizer
- [ ] Extrusion of polyline features extending line symbolizer

**Comment by ElenaGallo** [comment]
@allyoucanmap The UI of *Pattern mark style* and *Pattern icon style* are not correct.

**Pattern mark style**
![1](https://github.com/geosolutions-it/MapStore2/assets/56537133/cb92fdd3-0de2-4128-966a-c993cac47a6b)


**Pattern icon style** 
![2](https://github.com/geosolutions-it/MapStore2/assets/56537133/59cc03e6-c549-4a9a-bd6f-43f7ac34c41f)

**How to Reproduce**
- Open the demo map
- Open the style tab for 'States of US'
- Click on Add fill rule
- Click on Pattern icon style
