### ISSUE TITLE
[Annotations] Disabled annotations are printed

### ISSUE THREAD

**Issue by dsuren1** [geosolutions-it/MapStore2#9823]
**Describe the bug**
If several annotations exist in the "Annotations" layer, the annotations whose visibility is disabled are still printed and visible in the PDF generated by MapfishPrint.

**Expected behavior**

**Screenshots**
![print_disabled _annotation](https://github.com/georchestra/mapstore2-georchestra/assets/4659829/5e443140-d413-4470-8eee-ccbf82374413)

**Version**
2023.02.xx

**Comment by offtherailz** [comment]
@ElenaGallo, could you please test this on  DEV  ? Thank you
