### ISSUE TITLE
Support for IFC as a further 3D model managed by MapStore

### ISSUE THREAD

**Issue by mahmoudadel54** [geosolutions-it/MapStore2#9830]
## Description

The 3D model capabilities in MS are currently supporting GLTF in 3D model symbolizers. It is requested to provide also support for IFC 3D models:

- georeferenced if IFC v4 is used 
- non-georeferenced for older IFC versions to be used instead of GLTF in model symbolizer

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Other useful information
Proposal based on shared model by @ufficiosit 

It is proposed here to create a new type of layer of type model to allow to include:
- Catalog to include an ifc as layer
- Workflow for import and visualize an ifc on map
- Identify workflow
- Panel settings with following options:
   - Visibility
   - General tab (title and description)
   - Custom tab to add possibility to change position of the center of the model
- [Optional] Add adjustment of the center interacting with the map (this need to include a review of the settings panel)

**Notes:**
We need to include the [web-ifc](https://github.com/IFCjs/web-ifc/tree/main) library in MapStore (**check license compatibility**). 

- Style panel will not be available for this type of layer. It is already defined within the model.
- This type of layer should be used for small IFC files. **For large files it’s better to convert to 3D Tiles**. we should consider to show a message to the user if the IFC file is too big to be rendered in MS (to evaluate during design)

**Comment by mahmoudadel54** [comment]
Hi @tdipisa 

As per a discussion with @allyoucanmap regarding the origin point that model will relate to 
The issue is not all ifc files has an assigned coordinate system, and the origin of the model is required to show it to the map 
So the possible workflow could be:
- a user adds ifc file from catalog
- a popup dialog will open like this showing 
1-  the origin of the model is it is existing and can be read, 
2- if not it will be by default (0,0) and user can edit them manually 
3- there is an option to user to pick a point via map to be the origin 

![image](https://github.com/geosolutions-it/MapStore2/assets/58145645/a8f2ef95-6664-4352-b41d-389b8407da3f)


the same popup dialog will be used if user want to move the model location later
Is it Ok ?

**Comment by tdipisa** [comment]
@mahmoudadel54 ok sounds good. Thank you.
