### ISSUE TITLE
Terrain configuration on localConfig overrides context configuration

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#9838]
## Description

The context terrain configuration is not taken into account in a derived map when localConfig has terrain configured. The issue must be investigated before proceed in an implementation because it could be evaluated within #8338

## How to reproduce

- add in localConfig a terrain configuration
- create a new context with a different terrain configuration and set the viewer on 3D
- create a new map from the context just created

*Expected Result*

The terrain is the one configured in the context

*Current Result*

The terrain is the one configured in the localConfig.json

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by mahmoudadel54** [comment]
Hi @allyoucanmap @tdipisa 
I am not able to reproduce the issue, I have added terrain layer into localConfig then created a context adding a different terrain layer into cfg of Map plugin.
Then I open the map context finding the context terrain layer is only added to map not the one of localConfig

**Comment by tdipisa** [comment]
@allyoucanmap can you please provide some feedback on the above?

**Comment by allyoucanmap** [comment]
@tdipisa I'm not able anymore to reproduce this issue

**Comment by tdipisa** [comment]
Thank you so much for reporting. Do you know or maybe remember any possible commit which might have fixed this issue?
