### ISSUE TITLE
Print Tool - Error to generating PDF

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#9861]
## Description

It is not possible to print layer.
Error on console: 
> POST https://dev-mapstore.geosolutionsgroup.com/mapstore/pdf/create.json 408 (Request Timeout)

![print error](https://github.com/geosolutions-it/MapStore2/assets/56537133/f4b92bd5-70c9-477d-9be5-f611d6af594e)

## How to reproduce

- Open a map with a layer
- Click on Print tool
- Click on Print 

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

On DEV and QA

**Comment by tdipisa** [comment]
@ElenaGallo it seems perfectly working for me both on dev and qa. Are you sure of that problem?

**Comment by ElenaGallo** [comment]
@tdipisa it works now, I'm closing the issue.
