### ISSUE TITLE
Layer BG Selector - Implement size checks on uploaded images and downsampling

### ISSUE THREAD

**Issue by ale-cristofori** [geosolutions-it/MapStore2#9867]
In the BG layer selector plugin users can upload an image as thumbnail to show in the buttons of the plugin. Images are stored within the map and context configuration as text (format base64).
In case users upload quite large or high resolutions images the parsed text will result in a very long string and this does have an impact on the resulting configuration JSON created (long loading times, crash on saves).

https://github.com/geosolutions-it/MapStore2/assets/14953970/cecc3d9b-aef8-4466-85e5-cbd6d7c3d3d7

AT THE MOMENT THE LIMIT OF THE IMAGE IS 500KB, which is already quite high for a thumbnail. 

The fix could have two actions:

1. Reduce the allowed limit in KB of the image the user can upload as a thumbnail (for example up to 50KB would seem to be enough)
2. Implement a mechanism to scale and save in base64 the uploaded image to a fixed scaled size, with the view to reduce the resulting string size.

**Comment by ElenaGallo** [comment]
@MV88 The message in the Italian translation is not completely visible.

![italian](https://github.com/geosolutions-it/MapStore2/assets/56537133/97feadc3-fbb3-40e6-bb61-a2eebebc5730)

**Comment by MV88** [comment]
@ElenaGallo please test again in DEV

**Comment by MV88** [comment]
nevermind
