### ISSUE TITLE
Issue with style symbolizer assignment for WFS layer

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#9884]
## Description

When loading a WFS layer in MS the default style symbolizer is not assigned properly in certain cases. 

## How to reproduce

- Open [this](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/10358) map
- Load the US States layer from WFS 
- Open the style editor

*Expected Result*

By default only the Fill rule shoudl be applied to that type of layer

*Current Result*

![Image](https://github.com/geosolutions-it/MapStore2/assets/1280027/ab59107f-36d2-488b-bd9e-a8b1d9980164)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by ElenaGallo** [comment]
@tdipisa This issue is still present for some layers of this WFS service: https://mappe.comune.genova.it/geoserver/SITGEO/ows

**How to Reproduce**
- Open [this](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/39593) map
- Load the PIANI DI BACINO - AREE ESONDABILI layer from WFS
- Open the style editor

**Comment by tdipisa** [comment]
> * AREE ESONDABILI

@ElenaGallo that's because the geometry type for this layer is not specified 

![image](https://github.com/geosolutions-it/MapStore2/assets/1280027/27b43400-8065-4bb2-88e8-bf325257a51d)

Therefore it is a normal behavior.
