### ISSUE TITLE
Components in Login plugin should be Dialog

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#989]
The Account info and Change Password components sometimes are displayed as modal and sometimes as Dialog. They should be all dialog. Check localConfig

**Comment by offtherailz** [comment]
Has this been fixed by recent changes on login?
https://github.com/geosolutions-it/MapStore2/issues/1087

**Comment by MV88** [comment]
Yes, i forgot to close it.  i fixed this and #1087 in the #1091
