### ISSUE TITLE
Is a way to move the ZoomControl to bottomLeft position?

### ISSUE THREAD

**Issue by SaiAnandPeketi-GIS** [geosolutions-it/MapStore2#9904]
Hi,

Could you please provide me documentation of how to change the position of zoom control to bottom left?

Thanks

**Comment by tdipisa** [comment]
Dear @SaiAnandPeketi-GIS thank you for your question. Usually the MapStore mailing list is used for these purposes. [Here](https://github.com/geosolutions-it/MapStore2?tab=readme-ov-file#communication)you can fine links to subscribe and get in touch with the community. Thank you.
