### ISSUE TITLE
Examples for vector tile layers

### ISSUE THREAD

**Issue by elwoodhouse** [geosolutions-it/MapStore2#9921]
## Description

I'm not quite clear from the documentation if vector tile layers are fully supported in MapStore. I can't find much mention of them in the developer documentation but they are referenced in the code base in a few places.

The 2 type of vector tile layers that I'd be interested in is as a basemap or as a separate operational layer. I'm guessing they are likely to work in the 2D viewer (as they are supported in OpenLayers) but are both of these use cases supported in the 3D viewer?

A pointer to some examples or a comment on why I shouldn't be using them if that is the case would be much appreciated.

*Documentation section involved*
- [ ] User Guide
- [x] Developer Guide

**Comment by tdipisa** [comment]
@elwoodhouse vector tiles are not fully supported yet. There is only a partial integration at the moment still experimental. For any further question you can interact also with the [Mailing List](https://github.com/geosolutions-it/MapStore2?tab=readme-ov-file#communication).
