### ISSUE TITLE
[Annotation] Circle radius is modified when saving the annotation

### ISSUE THREAD

**Issue by dsuren1** [geosolutions-it/MapStore2#9937]
Description
[Annotation] Circle radius is modified when saving the annotation (Happens only in **stable** `2023.02.xx`)

**To Reproduce**
- Set new.json to `EPSG:3857`
- Open a new map
- Add a circle annotation and save
- Upon saving the circle radius changes

**Expected behavior**
conservation of the circle size 

**Investigation**
This issue is caused by `transformPolygonToCircle` when the circle is geodesic

**Ref:** 
https://github.com/georchestra/mapstore2-georchestra/issues/681

**Comment by tdipisa** [comment]
To be backported to 2023.02.xx
