### ISSUE TITLE
Plugins can not show when login in the mapview page

### ISSUE THREAD

**Issue by jiafengwang** [geosolutions-it/MapStore2#9954]
## Description
I have a map that created based on a context, and all plugins are enabled for it. 
When I Login on the MapStore Homepage first, then open this map, I can find all the plugins. 
But when I open this map first, then login on the mapview page, I can not find some plugins.

MapStore Version
Version
2023.02.02
Message
Release 2023.02.02 (#9934)
Commit
43520f184dd6fc950ea214bde5be711f24f4f335
Date
Tue, 30 Jan 2024 12:36:40 +0100

## How to reproduce
![PixPin_2024-02-05_09-34-28](https://github.com/geosolutions-it/MapStore2/assets/2180882/fc72b851-64b4-4c40-af56-4f8c54aa41e0)

-  
- 

*Expected Result*
All plugins should be find after login 

*Current Result*
![PixPin_2024-02-05_09-44-08](https://github.com/geosolutions-it/MapStore2/assets/2180882/bad8f821-3c2d-4a21-93fa-167281c83ec3)
![PixPin_2024-02-05_09-46-04](https://github.com/geosolutions-it/MapStore2/assets/2180882/53f76ab9-c24f-4f4c-a5b9-6ea6839d9c39)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge|121.0.2277.83 64Bit |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@jiafengwang tested through It seems not reproducible on our side and that's strange indeed as a behavior. I suspect a temporary networking issue that prevented some plugin bundle from loading properly.
