### ISSUE TITLE
Editing of date/time attributes is not working

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#9959]
## Description

The editing of date, time and date-time attributes are not working as expected. Here main problems:

- value selected from the date calendar or time select popover is not applied
- the only way to activate the editing is to click on the cell border. Clicking on the center will not work

https://github.com/geosolutions-it/MapStore2/assets/19175505/2583611d-4cd0-4655-b91d-0de5c7a97836

## How to reproduce

- open this [map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/28584) or add a WMS layer with at least date, time or date-time attribute to the map
- login as an admin
- open the TOC and select the WMS layers (Types in the map example)
- open the attribute table
- switch to edit mode

*Expected Result*

- Editing should work both via text input or popover
- A user should be able to click also on the center of the cell to enter edit mode

*Current Result*

- Clicking on an empty cell with date, time or date-time values allows to add a value only by typing a text
- The only way to enter in edit mode is to click on the cell border once the cell has been filled with a value
- The editing via popover is not working

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
Thank you @allyoucanmap 
@ElenaGallo I kindly ask you to improve the functional test scenario once this issue is fixed.

**Comment by tdipisa** [comment]
@ElenaGallo please test with priority tomorrow morning in DEV.
