### ISSUE TITLE
Remove Edit Icons (plus sign and pencil) for NON-ADMIN role users from Catalog Component

### ISSUE THREAD

**Issue by ale-cristofori** [geosolutions-it/MapStore2#9974]
## Description
As things are at the moment for MapStore, if I am logged in as a NON-ADMIN role, a normal user or even an anonymous user, I can access a map and I still can add - edit and remove services from the catalogue drop-down list. I won't be able to save the map and all changes will be lost but in any case I still can operate on the catalogue services to edit within a session.

The above behaviour could potentially be seen as non-coherent with the NON-ADMIN/edit role on the map and it could be useful to remove/hide the two buttons directly via a configuration key.

example of potential cofiguration:

```json
. . .
"catalog": {
    .  .  .
    allowedEditingRoles: ["ADMIN"]
}
```
See below the buttons
![image](https://github.com/geosolutions-it/MapStore2/assets/14953970/a31a8d9c-7f47-4608-bd6a-8b112c9f0002)

## Acceptance criteria

- [ ] As non-authorized user role I won't be able to see the two buttons (pencil and plus) next to the dropdown list of available services in the catalog.
- [ ] As an authorized user role I will be able to see and operate on the two buttons (pencil and plus) next to the dropdown list of available services in the catalog.
- [ ] As a user I will be able to control the authorized roles  (or groups ) depending on the design we would like to give to the solution, to see and operate on the two buttons that allow to add/modifiy existing services to the catalog.

**Comment by dsuren1** [comment]
@tdipisa 
I think we should integrate the `allowedEditingRoles` and `allowedEditingGroups` configurations, similar to what we've done for the StyleEditor and FeatureEditor plugins, into the MetadataExplorer (catalog) plugin? This would ensure consistency across all plugins

**Comment by tdipisa** [comment]
> @tdipisa I think we should integrate the `editingAllowedRoles` and `editingAllowedGroups` configurations, similar to what we've done for the StyleEditor and FeatureEditor plugins, into the MetadataExplorer (catalog) plugin? This would ensure consistency across all plugins. Kindly let me know your thoughts. Thanks!

@dsuren1 yes.

**Comment by dsuren1** [comment]
**Updated**: 

- Two configuration props`editingAllowedRoles` and `editingAllowedGroups` are supported to determine if the user is allowed to add/edit catalog services

- By default `editingAllowedRoles: ["ADMIN"]`

**Comment by tdipisa** [comment]
> By default editingAllowedRoles: ["ADMIN"]

@dsuren1 default is USER. Nothing should change for the default behavior, we have only to provide the possibility to intervene in the configuration to change the allowed role if necessary
