### ISSUE TITLE
Mapstore catalog sometimes does not respect geofence geoserver rules

### ISSUE THREAD

**Issue by Bobox948** [geosolutions-it/MapStore2#9988]
## Description 

Hello,

I am using geonode, geoserver and mapstore together. So instead of having to reproduce the permissions for the layers and the accounts in those 3, I am using keycloak.

Now, when I launch mapstore and open the WMS catalog on one user's accounts, everything seems to be fine. Each account has only access to the layers that he is entitled to see. But when I decide to add one layer to the map with the "+" button on one of these accounts, then every other account on the server has access to the same catalog that the user that has added this layer. 
The other users will see the same catalog, but when they will try to add the layers that they are not entitled to use, the layers will be blank and won't show on the map.

I have noticed that when you curl directly the getcapabilities with the account in question, the right layers come in the getcapabilities from geoserver, but when this url passes through mapstore/proxy , then it's the wrong one, like if there is some caching of the catalog via mapstore or the proxy...

So my guess is that the problem comes from mapstore side caching something (through the proxy?) and not geoserver because the layers, even if they show in the catalog, the user that is not entitled to see them can add them to the map but they are empty and "errored".

## How to reproduce

Explained above.

*Expected Result*

Each account can only see its own catalog all the time. Even after other users use mapstore and manipulate data.

*Current Result*

Currently, every user only sees his catalog and layers (saved in mapstore menu) if no one touches the catalog or manipulates data. When they start to add data from the catalog, it crashes for everyone for a period of a couple hours and then it comes back all by itself, I don't understand why (synchronization ?)

I think the problem comes from /mapstore/proxy redirecting to geoserver, and if we could directly call geoserver getcapabilities it would work, any ideas of how to di this ?

- [x] Not browser related

## Other useful information

Thanks a lot in advance, if i'm not clear please let me know. For know I am not adding screenshots because I believe they won't add any valuable information.

**Comment by tdipisa** [comment]
@Bobox948 Thank you so much for contacting us.
I'm sorry but it is not really clear for me if you are using MS standalone or GeoNode and what is effectively your current setup. Anyway, if you are using GeoNode it is better if you get in touch directly with the GeoNode community. If you are using MS standalone you can also use the mailing list to open a discussion for your problem. Links to subscribe the MS mailing list can be found [here](https://github.com/geosolutions-it/MapStore2?tab=readme-ov-file#communication).
