### ISSUE TITLE
Integrity check attribute for external JS resources

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#9997]
## Description

Evaluate and possibly implement [integrity check attribute](https://www.w3schools.com/tags/att_script_integrity.asp) for external JSs resources used in the application.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Other useful information

resources check have to be checked on core and on C125 project

**Comment by offtherailz** [comment]
Setting to done, no required functional test
